### ISSUE TITLE
Qualité replay M6

### ISSUE THREAD

**Issue by tug912** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#100]
Hello,

je viens signaler un pb de qualité sur l'ensemble des chaines du groupe M6. Depuis quelque temps les replay sont en qualité très faible (400x266). J'ai bien vérifié dans les options la HD est bien activée.

**Comment by wwark** [comment]
Bonjour @tug912,

Merci pour l'alerte! 

Nous sommes au courant que les flux des replays non protégé par DRM du groupe M6 M6 ont une faible qualité. Nous ne pouvons rien faire sur ce point.

Cependant nous avons travaillé  sur un plugin de test DRM (https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmoretestdrmkodi18) qui peut s'installer à côté de l'autre sans problème et aussi disponible sur notre répo (https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmoretestdrmkodi18/wiki/Add-the-official-repository)
Ce plugin de test DRM requiert la version Kodi 18 pour fonctionner (>Kodi 18 beta 3)
Les flux DRM sont de meilleurs qualités pour les Replay et ce plugin propose aussi les direct TV du groupe M6.

Dans un future proche nous allons merger les travaux DRM dans le plugin principal pour la sortie de Kodi 18.

N'hésite pas à nous faire des retours sur ce plugin de test si tu as la possibilité de tester.

Merci,
Wwark

**Comment by tug912** [comment]
Merci pour ta réponse ! 
J'essayerais de tester ça sur Kodi 18 un de ces jours alors.
Bonne journée.

**Comment by tug912** [comment]
Testé sur kodi 18.0 RC1 x64
La vidéo replay ne se lance pas. Erreur "authentification failed"

Voici le log

13:27:00.791 T:14860  NOTICE: Running the application...
13:27:00.791 T:14968  NOTICE: ES: Starting UDP Event server on port 9777
13:27:00.791 T:14968  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
13:27:05.288 T:11872   ERROR: XFILE::CDirectory::GetDirectory - Error getting
13:27:18.288 T:11556   ERROR: Previous line repeats 6 times.
13:27:18.288 T:11556 WARNING: CPythonInvoker(7, C:\Users\XXXXX\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmoretestdrmkodi18\addon.py): the python script "C:\Users\XXXXX\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmoretestdrmkodi18\addon.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcgui::ListItem
13:27:20.156 T:11412 WARNING: CPythonInvoker(8, C:\Users\XXXXX\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmoretestdrmkodi18\addon.py): the python script "C:\Users\XXXXX\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmoretestdrmkodi18\addon.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcgui::ListItem
13:27:22.340 T:5208 WARNING: CPythonInvoker(9, C:\Users\XXXXX\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmoretestdrmkodi18\addon.py): the python script "C:\Users\XXXXX\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmoretestdrmkodi18\addon.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcgui::ListItem
13:27:30.643 T:14860   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.catchuptvandmoretestdrmkodi18/resources/lib/channels/fr/6play/get_video_url?_pickle_=80027d71002855076974656d5f6964710158020000006d36710255075f7469746c655f710358080000004172c3a76169732071045508766964656f5f69647105580d000000636c69705f3131363130383836710655096974656d5f6469637471077d7108285804000000696e666f71097d710a285804000000706c6f74710b5890030000432765737420c3a0204172c3a76169732064616e73206c65204d617261697320506f69746576696e20717565204368616e74616c2065742073612066616d696c6c65206f6e74206661697420617070656c20c3a0205068696c69707065204574636865626573742e200a0a496c20792061203820616e732c204368616e74616c20657420736f6e206d61726920416c61696e206f6e742072657072697320756e6520617562657267652065742079206f6e7420696e766573746920746f75746573206c6575727320c3a9636f6e6f6d6965732e20416c61696e2c20706f757274616e742072657472616974c3a92c2073276f6363757065206475206261722e204a696d6d792c206c6575722066696c732c2065737420656e2063756973696e652c206574204368616e74616c2067c3a87265206c612073616c6c652e204d6169732c20616e6ec3a96520617072c3a87320616e6ec3a9652c206c2761666661697265207327657374206566666f6e6472c3a965e280a620466175746520646520636c69656e74732c206c65732070726f707269c3a974616972657320736f6e7420c3a0206465757820646f69677473206465206d6574747265206c6120636cc3a920736f7573206c6120706f7274652c206574206c612066616d696c6c652065737420617520626f7264206465206c61207275707475726520210a0a5068696c69707065207661207669746520636f6d7072656e64726520717565206c652076c3a972697461626c6520736f75636920646520636574746520617562657267652c206327657374206c27616d6269616e6365e280a620556e6520616d6269616e6365206f726167657573652c20c3a0206c6120666f697320656e2063756973696e6520657420656e2073616c6c652c20717569207661206c65206d65747472652064616e7320746f75732073657320c3a9746174732e204c65206368656620766120642761696c6c65757273206c65757220706f73657220756e20756c74696d6174756d203a207369204368616e74616c2065742073612066616d696c6c65206e27616363657074656e742070617320736f6e2061696465206574207265667573656e742064276f7576726972206c657320796575782c20696c207365726120636f6e747261696e742064276162616e646f6e6e6572207361206d697373696f6e206574206465206c6573206c616973736572207365756c73206661636520c3a0206c6575722064657374696ee280a6710c55056169726564710d580a000000323031382d31312d3137710e55057469746c65710f58080000004172c3a761697320711058080000006475726174696f6e71114d4616550479656172711258040000003230313871135504646174657114580a00000031372e31312e32303138711575580300000061727471167d711728580600000066616e6172747118582c00000068747470733a2f2f696d616765732e36706c61792e66722f76312f696d616765732f3736383632302f726177711958050000007468756d62711a582c00000068747470733a2f2f696d616765732e36706c61792e66722f76312f696d616765732f3736383632302f726177711b75580600000073747265616d711c7d711d58050000006c6162656c711e58080000004172c3a761697320711f5806000000706172616d73712063636f6465717569636b2e6c697374696e670a506172616d730a7121298171227d712355087261775f646963747124680073625807000000636f6e7465787471257d7126580800000070726f7065727479712763636f6465717569636b2e6c697374696e670a50726f70657274790a7128298171297d712a2868247d712b55095f6c6973746974656d712c6378626d636775690a4c6973744974656d0a712d2981712e756275752e]
13:27:30.657 T:5240 WARNING: CPythonInvoker(13, C:\Users\XXXXX\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmoretestdrmkodi18\addon.py): the python script "C:\Users\XXXXX\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmoretestdrmkodi18\addon.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcgui::ListItem

**Comment by wwark** [comment]
Bonjour Tug912,

Je pense que nous devons améliorer notre message d'erreur.
Pour lire les vidéos protégés par DRM du groupe M6. Nous avons besoin d'un compte 6play.fr. Ce compte est à renseigner dans la configuration du plugin au niveau des 'Accounts'

Après avoir correctement renseigner ce compte tu n'auras plus d'erreur.

Merci,
Wwark

**Comment by tug912** [comment]
Hello,

j'ai donc créé un compte et installé des pluggins manquants. Le replay se lance bien mais la qualité reste la même (très faible)

**Comment by wwark** [comment]
Pour les replay groupe M6 on a jamais eu du 720p normalement tu devrais avoir du 480p qui est mieux que du 240p :).

Tu utilises bien le bon plugin ? normalement tu as la mention "test drm kodi 18" en rouge sur l'icon du plugin. 
Pour vérifier si c'est bien le bon plugin que tu utilises. Est-ce que tu arrives à lire des replay de la serie Bull qui sont protégés par DRM par exemple?

Merci,
Wwark

**Comment by tug912** [comment]
J'ai vérifié ca fonctionne bien. Bull est bien en 480p.
Mais d'autres émissions sont en 240...
Je pense simplement que certaines émissions sont mise en qualité très faibles sur le site de 6play....

Merci à vous en tt cas :)

**Comment by wwark** [comment]
ok tu aurais un exemple d'emission en 240p que je regarde? Il est possible qu'on trouve une solution.
Merci,
Wwark.

**Comment by tug912** [comment]
Alors par exemple il y a capital ou cauchemars en cuisine !

Merci à toi :)

**Comment by wwark** [comment]
Merci ! J'ai pris un exemple de bull et cauchemars en cuisine. La qualité est identique.

![screenshot from 2018-11-23 20-17-40](https://user-images.githubusercontent.com/469461/48958046-e1da2600-ef5c-11e8-94b1-94324637b0e6.png)
![screenshot from 2018-11-23 20-17-29](https://user-images.githubusercontent.com/469461/48958047-e272bc80-ef5c-11e8-9d3c-729f40a91a2b.png)
![screenshot from 2018-11-23 20-16-48](https://user-images.githubusercontent.com/469461/48958048-e272bc80-ef5c-11e8-99a4-471b99c802ee.png)
![screenshot from 2018-11-23 20-16-32](https://user-images.githubusercontent.com/469461/48958049-e272bc80-ef5c-11e8-9c32-0c88db3be11a.png)

**Comment by wwark** [comment]
Hello,
Je ferme ce ticket.
N'hésite pas à le rouvrir si besoin.
Merci,
Wwark
