### ISSUE TITLE
TF1 Issue - GeoBlocked

### ISSUE THREAD

**Issue by nirolfa** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1000]
TF1 Issue - GeoBlocked even when using vpn

**Comment by nirolfa** [comment]
some url i grabbed from browser

https://live-tf1-das-secure.cdn-0.diff.tf1.fr/out/v1/98f48bb09cf04832a076ef2aa2f3394d/index_video_7_0_init.mp4?m=1668588854

https://dnl-q1-cf.tf1.fr/2/USP-0x0/82/11/13928211/ssm/13928211-1200-64k.mp4?max_bitrate=1200000&Expires=1669428252&Signature=W2Rmi2eOIbgy9wNZE1-1VopyQtcJeJkZaNiycaPu7bxvdzkYYOdwQ0~9wJBNTzc27PyBru9q8CSYVgK0iyd~TbMAvQT1vwXOBpntIT0wqfrMKut~ZAyitXiCuYrz2CE-FjpCvd4cTjLt53J9TWoEEABoJSRfcygE6JI7FNH4~yfEtAZzylFu~VmrvbrcGMwjbhXfZU27WlasQk95q~Yn8Ba4Y84VdkyDSI-5jPH0-AdcSQgGh8gdeIV7u0k5UIxZYhJD7hTWbdAiR-yXf0Yh22gN0hByihPoXU9UDhXBHIJXV~RAUXMkKH~N-t7~RM0Mu4CRfyhNbOMFnbXdIyn-pQ__&Key-Pair-Id=APKAJAMWITFXB27R5I4A

**Comment by joaopa00** [comment]
That's not a Catchuptvandmore problem. Please refer to your vpn provider.

**Comment by nirolfa** [comment]
well it s working with the sams vpn provide using browser , just not working with kodi & catch up tv 
so just wondering what they changed  in mytf1 platform ?

**Comment by joaopa00** [comment]
Unable to reproduce even in using a vpn.
