### ISSUE TITLE
Replay arte.fr KO

### ISSUE THREAD

**Issue by ppoi202** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1001]
Bonjour,

Je n'arrive pas à lire des replay sur le site arte.fr.
J'utilise Libreelec sur Raspberry-Pi.

 - Kodi version: 19.4
 - Catch-up TV & More version: branch dev (6297503e57a01c53448604fdd294ea4c4b20dc2b)

log : 

`2022-11-29 15:47:09.938 T:957     ERROR <general>: [Catch-up-TV-&-More.support] HTTPSConnectionPool(host='www.arte.tvhttps', port=443): Max retries exceeded with url: //www.arte.tv/fr/videos/RC-022903/in-the-flesh/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x4e127ab8>: Failed to establish a new connection: [Errno -2] Name or service not known'))`

Merci pour votre aide.

**Comment by joaopa00** [comment]
Il faut donner le nom de la video qui pose problème, la démarche pour y accéder et attcher ici le log de kodi avec le mode déboggage activé.
Sinon, on ne peut rien faire.

**Comment by ppoi202** [comment]
Désolé pour le log... Je pensais que les infos étaient suffisantes. 
Enfin de compte, je n'arrive pas à rentrer dans le répertoire de la série car j'ai une notification d'erreur (c'est pas la lecture d'un épisode).

`HTTPSConnectionPool(host='www.arte.tvhttps', port=443): Max retries exceeded with url: //www.arte.tv/fr/videos/RC-022903/in-the-flesh/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x4e127ab8>: Failed to establish a new connection: [Errno -2] Name or service not known'))`

Exemple avec le lien suivant d'une série sur Arte.fr -> www.arte.tv/fr/videos/RC-022903/in-the-flesh/.

Je peux par contre lire certaine videos du site.
Je poste des infos supplémentaire quand je suis de retour à la maison.

Bonne soirée

**Comment by ppoi202** [comment]
Merci pour la correction !
