### ISSUE TITLE
Bug -  Délai entre 3h et 4h sur les direct/live

### ISSUE THREAD

**Issue by Latury** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1003]
### Describe the bug
Bonjour depuis quelques jours j'ai remarqué un bug que lorsque je veux regarder un live sur l'application exemple sur tf1 une chaîne française il y a un délai entre le live et le programme que j'ai devant moi. Une exemple si je veux regarder par exemple à 20h un match de la coupe du monde sur tf1 quand je lance le live je me retrouve avec un délai entre 3h et 4h en arrière {comme s'il était 16h} et même si j'avance manuellement je ne suis pas en live il y a un décalage de quelques minutes. Il me semble qu'une personne sur le forum anglais a le même souci. J'espère que ce bug pourra être corrigé, merci bonne journée/soirée. 

### To Reproduce
Steps to reproduce the behaviour:
1.
2.
3.
4.

### Expected behaviour
A clear and concise description of what you expected to happen:

### Actual behaviour
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
Android smartphone 
Android tablette
Android Google tv

 - Operating system version/name:
 - Kodi version: 19.4
 - Catch-up TV & More version: v0. 2.38
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment]
C'est déjà résolu dans la version béta. Voir [wiki](https://catch-up-tv-and-more.github.io/fr/installation/#2-installer-le-d%C3%A9p%C3%B4t-officiel-de-catch-up-tv--more) pour installer le version béta.
