### ISSUE TITLE
Replay Arte.fr Accès aux différentes langues et sous-titre possible ?

### ISSUE THREAD

**Issue by ppoi202** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1004]
Bonsoir,

Est-il possible d'intégrer au replay du site Arte.fr (exemple pour les séries), l'accès aux différentes langues et sous-titres comme sur le site ? Je n'ai actuellement accès qu'à la langue française.

Merci d'avance ;)

**Comment by joaopa00** [comment]
Paramètres de l'extension -> Qualité et contenus->Arte

**Comment by ppoi202** [comment]
Merci pour l'info.

Je viens de faire le manipulation en activant la langue EN, je n'ai par contre plus accès au site Arte (FR). J'ai maintenant accès au site Arte (EN) et je n'ai plus accès au séries (FR) sur ce pointeur. 
Les séries Arte (FR) diffusent plusieurs langues et sous-titres dont j'ai actuellement seulement accès à la langue française.

Il y a peut être une contrainte technique pour réaliser l'accès aux choix de la langue sur le site Arte (FR) ?
