### ISSUE TITLE
Replay Arte.fr pour l'accès aux différentes langues et sous-titres

### ISSUE THREAD

**Issue by ppoi202** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1005]
Après activation par exemple de la langue EN dans les paramètres de l'extension pour Arte.
Je n'ai plus accès au site Arte (FR) mais accès accès au site Arte (EN) et sur ce dernier je n'ai pas accès aux mêmes vidéos.
Les séries Arte (FR) diffusent plusieurs langues et sous-titres dont j'ai actuellement seulement accès à la langue française (via les paramètres de l'extension -> Qualité et contenus -> Arte -> FR).

Y-a-t'il une contrainte technique pour ajouter l'accès aux choix de la langue sur le site Arte (FR) ?

**Comment by joaopa00** [comment]
>Les séries Arte (FR) diffusent plusieurs langues 
Lesquelles?
Il faut donner la méthode pour reproduire le problème.
J'ai testé la série "Life" Je sais qu'elle est disponible en 2 langues: VO et VF.
Mais sur le site d'ARTE si tu as une IP française seule la langue francaise est proposée.
[life](https://www.arte.tv/fr/videos/101339-001-A/life-1-6/)

**Comment by ppoi202** [comment]
C'est toutes les séries, c'est pour ça que je n'ai pas donné d'exemple.
J'ai une @IP française et via mon navigateur internet, j'ai bien accès à toutes les langues comme pour la série life (français et allemand). Alors qu'avec catch-up-tv, je n'ai accès qu'à la langue française.

**Comment by joaopa00** [comment]
Voici patch pour une version de test. Pour voir si ca correspond à ce que tu demandes.
[0001-WO-ARTE-Propose-multiple-versions-of-the-stream.txt](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/10147039/0001-WO-ARTE-Propose-multiple-versions-of-the-stream.txt)

**Comment by ppoi202** [comment]
Super ça marche ! On peut avoir exactement les mêmes flux que sur le site internet de Arte. 
Est-il par contre possible de changer le flux en cours de lecture comme sur le site ? C'est juste au cas ou...

Sinon top !!!

MERCI

**Comment by joaopa00** [comment]
Non, ça c'est pas passible.

**Comment by ppoi202** [comment]
Ok pas de pb. Top le patch :)
