### ISSUE TITLE
Euronews ne fonctionne plus

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1011]
Dans le log j'ai : 

ERROR <general>: [Catch-up-TV-&-More.support] 404 Client Error: Not Found for url: http://fr.euronews.com/api/geoblocking_live.json

 - Operating system version/name: Linux Mint 20.4
 - Kodi version: 19.4.0
 - Catch-up TV & More version: 0.2.39 beta 15
 - Channel version : 1.0.17

Chaine demandée depuis la France.

Une mise à jour est-elle envisageable ?

**Comment by darodi** [comment]
@enigma131 

fixé dans la PR

**Comment by enigma131** [comment]
Merci
