### ISSUE TITLE
Tmc don't work in live Channel france

### ISSUE THREAD

**Issue by MM44340** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1013]
### Describe the bug
A clear and concise description of what the bug is:
Kodi crash or Black screen with sound of Channel Tmc or nothing passed (wrong message popup) since 08/12/2022. 

### To Reproduce
Steps to reproduce the behaviour:
1. Select live Channel
2. Select France
3. Select Tmc channel
4.
5.

### Expected behaviour
A clear and concise description of what you expected to happen:

### Actual behaviour
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:
![Screenshot_20221209_230855](https://user-images.githubusercontent.com/120181146/206898441-6cd987cc-6925-419c-9cea-9dfb4bb64246.jpg)

### Your environment
 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: 12.0
 - Kodi version: 19.3
 - Catch-up TV & More version: 0.2.37
 - Installation method: Apps store

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment]
Already fixed in beta.

**Comment by MM44340** [comment]
Sorry. But try with beta version. Nothing passe.
Black screen or message error since 08/12...

Some advices please ?

**Comment by joaopa00** [comment]
Attacher ici le log complet avec le mode de déboggage a tivé.

**Comment by joaopa00** [comment]
Je peux reproduire le problème. Mais ca ne vient pas de Catchuptvandmore ni même de Kodi. Sur le site de TF1, avec firefox, cela ne marche pas non lus.
"Nous éprouvons des difficultés à lancer cette vidéo sur votre navigateur
Veuillez vérifier que vous utilisez une version récente de votre navigateur"

Le direct des autres chaînes du groupe TF1 ne pose pas de problème avec Firefox. Certainement le sitede TF1 utlise quelque chose qui n'est pas dans les standards de W3 pour satisfaire Gogle chrome puisque la chaîne fonctionne sur Google chrome.

**Comment by MM44340** [comment]
Quelle est la suite à donner à ce ticket ?
Dois je fournir les logs complet ?

Tnt flash tv ne fonctionne plus non plus. Le flux semble interdit ou coupé par la chaîne depuis mercredi dernier. C'est étrange.

**Comment by joaopa00** [comment]
J'ai  réussi à rétablir le flux. Besoin de nettoyer le patch. Prendra peut-être quelques jours.

**Comment by Magicflyy** [comment]
Bonjour,
J'ai aussi soucis avec la chaine TMC en direct depuis le 08/12/22. (pas de soucis avec le Replay)
Lorsque je choisis la chaine TMC j'ai un message d'erreur "Echec de lecture d'un ou plusisuer fichier. Consultez le journal pour plus d'information sur ce message" 
initialement je suis sur KODI 19.4 avec catch-up-tv 2.38+matrix1 
J'ai essayer d'installer la pre-release de kodi 20.0 et la beta de catcth up 1.39-beta15 et ca ne change rien.
J'ai installer log viewer pour regarder le log mais je n'ai pas de trace de l'erreur.

Si je comprend bien le probléme est résolu et le patch en cours?
Merci

**Comment by joaopa00** [comment]
Quelqu'un peut-il essayer ce patch. Pour moi, il fonctionne aléatoirement sous android.
[0002-FR-TMC-Fix-live.txt](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/10241168/0002-FR-TMC-Fix-live.txt)

**Comment by Magicflyy** [comment]
Je peux si tu me dis comment l'intégrer.

**Comment by enigma131** [comment]
De mon coté pour Tmc je n'ai que le son. Les autres chaînes du groupe sont OK. Linux Mint 20.4 kodi, catchup et channels à jour.

**Comment by joaopa00** [comment]
Should be fixed in git.
