### ISSUE TITLE
french Channel M6 , sound only since few days

### ISSUE THREAD

**Issue by ouinouin** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1014]
Hi, since 3 to 4 days, M6 channel looks not working anymore, the sound is there but no image is displayed, i can access to the text description of the actually streamed program and that all.

tried to upgrade to 0.2.38+matrix.1 , but still have the issue.

doesn anyone have the same issue ? 

### Your environment
 - [ ] Android
 - [ ] iOS
 - [x] Linux on intel nuc

 - Operating system version/name:
 - Kodi version: 19.4 matrix
 - Catch-up TV & More version:  0.2.38+matrix.1
 - Installation method: from repository

### Additional context
Add any other context about the problem here:

### Debug log

i ll try to get log once i ll understand how to find it and to upload it somewhere.

**Comment by enigma131** [comment]
Is it working via web browser ?  On my side I had to re register 6play

**Comment by ouinouin** [comment]
@enigma131 : re register means recreate an account or changing your password , i already tried to change my password with no success.

i can access 6 play and play the replay on their site , but i couldnt find anything regarding to live stream in their website

**Comment by joaopa00** [comment]
Je confirme le problème.

**Comment by joaopa00** [comment]
Mauvaise nouvelle. C'est un problème de Linux. Fonctionne très bien sur Android et Windows. Certainement un probleme de CDM.

**Comment by ouinouin** [comment]
@joaopa00   : CDM acronyme de ? coupe du monde ? :-) ?

**Comment by joaopa00** [comment]
cdm = module de déchiffrement de contenu

**Comment by ouinouin** [comment]
> cdm = module de déchiffrement de contenu. J'ai vu que Google (puis Kodi) a mis à jour son CDM sous LInux il y a quelques jours. Le problème doit être apparu à ce moment là.

Is  the CDM plugin named widevine ?

**Comment by enigma131** [comment]
Yes. Normally kodi ask for update widevine and you have to answer yes.
All m6 group is working here under linux PC. What is intel nuc and what kernel have you + widevine version ?

**Comment by ouinouin** [comment]
hi , without any intervention, M6 channel got back on line today ...
i couldnt find where is widevine located (under which extension category or name.)

**Comment by joaopa00** [comment]
Pour moi aussi, ça remarche. Surement , M6 qui fasait des choses différentes suivant l'user-agent. Je ferme. Si ça reproduit, on pourra réouvrir.
