### ISSUE TITLE
Erreur téléchargement replay avec caractères spéciaux

### ISSUE THREAD

**Issue by miloumeeloo** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1015]
Bonjour,
Je reçois ces erreurs en essayant de télécharger des vidéos du replay de franceTV contenant des caractères spéciaux dans leurs titres.
Ici avec un "œ"
`UnicodeEncodeError: 'ascii' codec can't encode character '\u0153' in position 97: ordinal not in range(128)`
Là avec un ":"
`UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 103: ordinal not in range(128)`

 - UBUNTU 22.04
 - Kodi version: 19.4 GIT:20220330
 - Catch-up TV & More version: 0.2.39~beta15
 - Installation method: Repo

**Comment by joaopa00** [comment]
Il faut donner le nom d'une émission qui ne fonctionne pas ainsi que la façon de l'obtenir.

**Comment by brethil** [comment]
Bonjour,  

J'ai une erreur comparable 
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 103: ordinal not in range(128)
en essayant tout simplement d'ouvrir la liste de chaînes France pour le direct si jamais ça peut aider au diag

-    Kodi version: 19.4
-    Catch-up TV & More version: 0.2.37
-    Installation method: Repo

**Comment by joaopa00** [comment]
Il faut toujours préciser le système sur lequel Catchuptvamore est utilisé.

**Comment by joaopa00** [comment]
Il faut installer l'addon locales.
