### ISSUE TITLE
Plus de M6, TMC, BFM, RMC

### ISSUE THREAD

**Issue by cabaret11** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1018]
Depuis quelques jours, M6 ne fonctionne plus. J'ai le son mais pas d'image avec un navigateur M6 fonctionnent très bien. BFM, RMC cela mouline mais rien se passe. Au démarrage de catch-up j'ai un message d'erreur me disant que la connexion a été refusée. Je suis sous windows 10, matrix 19.4 et catch-up 0.2.39 beta 15. J'ai essayé avec la version de catch-up 0.2.38 +Matrix .1 même problème.

**Comment by joaopa00** [comment]
Il y a déjà des rapports de bugs pour M6 et TMC. Pour le groupe BFM, il y a encore un changement d'API. Celui semble complexe à reproduire. Pas sûr que soit résolu prochainement dans Catchuptvandmore.

**Comment by cabaret11** [comment]
B‌onsoir,
Merci pour votre réponse et bon courage aux développeurs
 

De : "joaopa00"
A : "Catch-up-TV-and-More/plugin.video.catchuptvandmore" ,"cabaret11" ,"Author"
Envoyé: jeudi 15 Décembre 2022 19:40
Objet : Re: [Catch-up-TV-and-More/plugin.video.catchuptvandmore] Plus de M6, TMC, BFM, RMC (Issue #1018)
 

 

Il y a déjà des rapports de bugs pour M6 et TMC. Pour le groupe BFM, il y a encore un changement d'API. Celui semble complexe à reproduire. Pas sûr que soit résolu prochainement dans Catchuptvandmore.

**Comment by bercoq** [comment]
Je suis sous  Mac avec Kodi et depuis une semaine M6 ne s'ouvre plus avec le message d'erreur "list index out of range"

**Comment by funtravel1208** [comment]
> Je suis sous Mac avec Kodi et depuis une semaine M6 ne s'ouvre plus avec le message d'erreur "list index out of range"

@bercoq J'ai exactement le même problème mais sur Amazon Fire.

**Comment by joaopa00** [comment]
Ce genre de commentaires "ça ne marche pas moi" ne sert strictement à rien. Il faut toujours préciser l'appareil sur lequel cela se passe, la version de Catchuptvandmore utilisée et surtout attacher un log avec le mode déboggage activé.

**Comment by funtravel1208** [comment]
Merci pour vos commentaires. Je ne pense pas avoir simplement dit « ça ne marche pas pour moi », j’ai détaillé les problèmes spécifiques dans le post. Je ne pouvais malheureusement pas vous donner plus de détails car il y avait une erreur pour le log aussi que je ne pouvais pas obtenir mais c’est bien noté, j’ajouterai tous ces détails la prochaine fois.Merci encore!ChristineSent from my iPhone 13!On Jan 14, 2023, at 12:11 PM, joaopa00 ***@***.***> wrote:﻿
Ce genre de commentaires "ça ne marche pas moi" ne sert strictement à rien. Il faut toujours préciser l'appareil sur lequel cela se passe, la version de Catchuptvandmore utilisée et surtout attacher un log avec le mode déboggage activé.

**Comment by bercoq** [comment]
Tout à fait de  votre avis mais malheureusement lorsque je veux transmettre le journal "Cette sélection a déclenché une erreur inattendue ,souhaitez vous nous partager votre journal d'erreurs afin que nous puissions essayer de résoudre le problème" ; je réponds bien sûr oui mais à ce moment là nouvelle fenêtre " Désolé le partage de votre  journal d'erreur a échoué : unable to retrieve the paste url" . 
J'utilise KODI sur mon Macbook comme précisé . N'étant pas spécialiste je ne vois pas quoi faire d'autre . Désolé !!!!

**Comment by joaopa00** [comment]
Il suufit de récupérer le fichier log et de l'attacher ici.

**Comment by bercoq** [comment]
Désolé , j'ai cherché mais étant néophyte je n'ai pas trouvé ce fichier log.

**Comment by cabaret11** [comment]
B‌onjour,
Je suis sous Pc et depuis que j'ai fait la mise à jour de kodi matrix en 19.5 la plupart des chaînes marchent sauf celles du groupe France TV et j'ai une erreur "HTTP Error". La version de catchup que j'ai est la 0.2.39-beta 17
 

De : "bercoq"
A : "Catch-up-TV-and-More/plugin.video.catchuptvandmore" ,"cabaret11" ,"Author"
Envoyé: samedi 14 Janvier 2023 14:17
Objet : Re: [Catch-up-TV-and-More/plugin.video.catchuptvandmore] Plus de M6, TMC, BFM, RMC (Issue #1018)
 

 

Je suis sous Mac avec Kodi et depuis une semaine M6 ne s'ouvre plus avec le message d'erreur "list index out of range"

**Comment by cabaret11** [comment]
B‌onjour,
Je suis sous Pc et depuis que j'ai fait la mise à jour de kodi matrix en 19.5 la plupart des chaînes marchent sauf celles du groupe France TV et j'ai une erreur "HTTP Error". La version de catchup que j'ai est la 0.2.39-beta 17
‌
 

De : "funtravel1208"
A : "Catch-up-TV-and-More/plugin.video.catchuptvandmore" ,"cabaret11" ,"Author"
Envoyé: samedi 14 Janvier 2023 18:23
Objet : Re: [Catch-up-TV-and-More/plugin.video.catchuptvandmore] Plus de M6, TMC, BFM, RMC (Issue #1018)
 

 
Merci pour vos commentaires. Je ne pense pas avoir simplement dit « ça ne marche pas pour moi », j’ai détaillé les problèmes spécifiques dans le post. Je ne pouvais malheureusement pas vous donner plus de détails car il y avait une erreur pour le log aussi que je ne pouvais pas obtenir mais c’est bien noté, j’ajouterai tous ces détails la prochaine fois.Merci encore!ChristineSent from my iPhone 13!On Jan 14, 2023, at 12:11 PM, joaopa00 ***@***.***> wrote:﻿
Ce genre de commentaires "ça ne marche pas moi" ne sert strictement à rien. Il faut toujours préciser l'appareil sur lequel cela se passe, la version de Catchuptvandmore utilisée et surtout attacher un log avec le mode déboggage activé.

**Comment by hokapefr** [comment]
Bonjour,

Je ne peux que confirmer les problèmes ci-dessous : Shield TV 2017 avec Kodi v19.3, catch up tv 0.2.39~beta07

"Cette sélection a déclenché une erreur inattendue ,souhaitez vous nous partager votre journal d'erreurs afin que nous puissions essayer de résoudre le problème" ; je réponds bien sûr oui mais à ce moment là nouvelle fenêtre " Désolé le partage de votre journal d'erreur a échoué : unable to retrieve the paste url" .

Lors de l'accès au live ou au "rattrapage" du groupe M6 et malgré la vérfication de l'utilisateur et du mot de passe : 
"index error, list index out of range"

De plus malgré l'activation du mode debug de kodi et de nombreux tests, le fichier log de kodi sur shield tv reste vide : \\192.168.x.xx\internal\Android\data\org.xbmc.kodi\files\.kodi\temp\kodi.log

Comment générer "autrement" des logs plus parlants, et vous aider ?

Salutations

**Comment by funtravel1208** [comment]
Merci beaucoup d’avoir cherché le pb avec la version 07 mais ne vous inquiétez pas j’ai installé la version 17 et plus de problèmes pour M6 et TF1. On verra à l’avenir si le log marche avec la version 17.Merci encore!ChristineSent from my iPhone 13!On Jan 15, 2023, at 8:59 AM, hokapefr ***@***.***> wrote:﻿
Bonjour,
Je ne peux que confirmer les problèmes ci-dessous : Shield TV 2017 avec Kodi v19.3, catch up tv 0.2.39~beta07
"Cette sélection a déclenché une erreur inattendue ,souhaitez vous nous partager votre journal d'erreurs afin que nous puissions essayer de résoudre le problème" ; je réponds bien sûr oui mais à ce moment là nouvelle fenêtre " Désolé le partage de votre journal d'erreur a échoué : unable to retrieve the paste url" .
Lors de l'accès au live ou au "rattrapage" du groupe M6 et malgré la vérfication de l'utilisateur et du mot de passe :
"index error, list index out of range"
De plus malgré l'activation du mode debug de kodi et de nombreux tests, le fichier log de kodi sur shield tv reste vide : \192.168.x.xx\internal\Android\data\org.xbmc.kodi\files.kodi\temp\kodi.log
Comment générer "autrement" des logs plus parlants, et vous aider ?
Salutations

**Comment by raydenxxx** [comment]
**même problème que cité plus haut avec M6 et toutes les chaines du groupe**, que ce soit en direct ou en replay on obtient une erreur "list index out of range"

Voici le bout de log de l'erreur:
`2023-01-15 18:51:24.470 T:16488    INFO <general>: initializing python engine.
2023-01-15 18:51:24.505 T:16488   ERROR <general>: [Catch-up-TV-&-More.support] list index out of range
                                                   Traceback (most recent call last):
                                                     File "C:\Users\coren\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "C:\Users\coren\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                     File "C:\Users\coren\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "C:\Users\coren\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\channels\fr\6play.py", line 572, in get_live_url
                                                       api_key = re.compile(r'\"eu1.gigya.com\"\,key\:\"(.*?)\"').findall(
                                                   IndexError: list index out of range
2023-01-15 18:51:24.509 T:16488 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2023-01-15 18:52:20.462 T:16488    INFO <general>: CPythonInvoker`

Je joins aussi deux captures de l'erreur dans l'interface.

J'ai tout remis à jour pour vérifier, problème toujours présent.
J'ai testé aussi sous android tv, même souci.

Mes versions : 
Kodi : 19.5.0 windows 64 bit
Catch-up : 0.2.38+matrix.1

[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/10420871/kodi.log)

![1 selection flux m6](https://user-images.githubusercontent.com/122745590/212558736-6bbc4947-a217-4132-9e3b-14d2038616e3.jpg)

![2 refus envoi log](https://user-images.githubusercontent.com/122745590/212558741-fbd8175a-b694-4f6c-844b-d3d73160a998.jpg)

**Comment by joaopa00** [comment]
Avant de reporter un bug, il faut toujours tester la dernière béta. Il se peut que le bug est déjà fixé. Ce qui est le cas ici.

**Comment by raydenxxx** [comment]
> Avant de reporter un bug, il faut toujours tester la dernière béta. Il se peut que le bug est déjà fixé. Ce qui est le cas ici.

Merci pour l'info, je suis pas adepte du channel beta pour l'instabilité.

**Comment by joaopa00** [comment]
Le répertoire stable ne sert pas pour le développement. Aucun rapport de bug concernant la version stable n'est pris en compte. Si on utilise la version stable, on accepte les bugs qui y sont présents.

**Comment by raydenxxx** [comment]
> Je me suis un peu avancé. Le bug est fixé, mais dans git. La version béta ayant le fix n'est pas encore sortie. Le répertoire stable ne sert pas pour le développement. Aucun rapport de bug concernant la version stable n'est pris en compte. Si on utilise la version stable, on accepte les bugs qui y sont présents.

Comme mentionné, j’étais sur la release 02.38 et pas le Channel stable. Dans l’extension il est spécifié que si on a un bug ou des demande il faut passer par GitHub ce que j’ai fait. Maintenant j’ai la bêta… avec le bug de francetv. Je remettrai la prochaine release.

merci pour les infos

**Comment by hokapefr** [comment]
Bonjour, 

Je confirme bien que le problème signalé avec le groupe M6 sous : Shield TV 2017 avec Kodi v19.3, catch up tv 0.2.39~beta07 est bien corrigé par la version 0.2.39-beta avec le nr 17, ce qui correspond à la branche DEV.

Il est donc important de bien choisir le channel BETA dans KODI pour l'installation de catch up tv, car la version 0.2.38+matrix.1 contenue en standard de kodi ou la version 0.2.39~beta07 ne fonctionnent pas et produisent bien les copies d'écran fournies par [raydenxxx].

Le problème du ticket "Http error France2/france3/france4/france5 #1056" est par contre bien encore présent dans la version 0.2.39-beta avec le nr 17.

Merci à [raydenxxx] pour ses nombreuses copies d'écran.

**Comment by joaopa00** [comment]
Pour le dernier commentaire, ouvrir un nouveau rapport e bogue avec un log complet de kodi (mode déboggage active avec tous les channels activés). Pas un log de osmc.
Je ferme. Pour le problème de BFM sur Nexus, il y a déjà un rapport d'ouvert.
