### ISSUE TITLE
UnknownTimeZoneError: cannot find any time zone configuration

### ISSUE THREAD

**Issue by wwark** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#102]
Hi, @funtravel1208

J'ai ouvert un ticket sur le problème que tu as remonté ici https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/62. J'ai pu reproduire sous Android.
Nous avons effectué des modifications sur les timezones dans le guide TV sur la branche de développement.
Quel est l'OS utilisé de ton côté?

Avec la version 0.2.0~beta24
- [x] Test OK sur Linux (ubuntu, librelec, ...)
- [x] Test OK sur Android - (Erreur UnknownTimeZoneError: cannot find any time zone configuration => avec la version 0.2.0~beta23)
- [x] Test OK MacOS
- [x] Test OK Test Windows 

Pour contourner le problème il suffit de désactiver le guide TV pour l'instant dans les options du plugin.
![screenshot from 2018-11-28 08-10-47](https://user-images.githubusercontent.com/469461/49134805-2101d180-f2e5-11e8-885b-b98344166922.png)

Merci,
Wwark.

**Comment by wwark** [comment]
Le log d'erreur

> 8:15:31.928 T:18446744071993280816   ERROR: [script.tubecast] script.tubecast: [Errno 92] Protocol not available
08:15:38.174 T:18446744071921596720 WARNING: CPythonInvoker(5, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui8ListItemE
08:15:41.543 T:18446744071885113648   FATAL: [Catch-up-TV-&-More.support] 'Can not find any timezone configuration'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 285, in run_callback
                                                parent_ins._process_results(results)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 93, in _process_results
                                                raw_listitems = validate_listitems(raw_listitems)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 33, in validate_listitems
                                                raw_listitems = list(raw_listitems)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 208, in tv_guide_menu
                                                tv_guide = tv_guide_module.grab_tv_guide(channels_id)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/tv_guides/fr_live.py", line 352, in grab_tv_guide
                                                programs = telerama._get_programs_data(channels)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/tv_guides/fr_live.py", line 344, in _get_programs_data
                                                program_dict = self._parse_program_dict(program)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/tv_guides/fr_live.py", line 158, in _parse_program_dict
                                                local_tz = get_localzone()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/tzlocal/unix.py", line 131, in get_localzone
                                                _cache_tz = _get_localzone()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/tzlocal/unix.py", line 125, in _get_localzone
                                                raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')
                                            UnknownTimeZoneError: 'Can not find any timezone configuration'
08:15:41.544 T:18446744071885113648 WARNING: ###### debug ######
08:15:41.544 T:18446744071885113648 WARNING: [Catch-up-TV-&-More.support] Dispatching to route: '/main/tv_guide_menu'
08:15:41.544 T:18446744071885113648 WARNING: [Catch-up-TV-&-More.support] Callback parameters: '{'menu_id': u'fr_live', 'item_dict': {u'info': {'title': u'France'}, u'art': {u'thumb': u'/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/media/channels/fr.png'}, u'stream': {}, u'label': u'France', u'params': <class 'codequick.listing.Params'>({'menu_id': u'fr_live', '_title_': u'France', u'item_module': None, 'item_dict': {...}}), u'context': {u'Move down': 'XBMC.RunPlugin(plugin://plugin.video.catchuptvandmore/main/move_item?_pickle_=80027d71002855076974656d5f69647101580700000066725f6c697665710255076d656e755f6964710358070000006c6976655f747671045509646972656374696f6e71055804000000646f776e7106752e)', u'Connect VPN': 'XBMC.RunPlugin(plugin://plugin.video.catchuptvandmore/resources/lib/vpn/vpn_item_callback)', u'Hide': 'XBMC.RunPlugin(plugin://plugin.video.catchuptvandmore/main/hide_item?_pickle_=80027d710055076974656d5f69647101580700000066725f6c6976657102732e)'}, u'property': <class 'codequick.listing.Property'>({})}, u'item_module': None}'
08:15:41.544 T:18446744071885113648 WARNING: [urlquick] Requesting resource: https://api.telerama.fr/v1/programmes/maintenant?appareil=android_tablette&api_cle=apitel-5304b49c90511&nb_par_page=100&api_signature=dcd1522e726dcb84c50c9aa6ed66301e6ee4fc7a&id_chaines=192%2C4%2C80%2C34%2C47%2C445%2C195%2C446%2C444%2C78%2C481%2C226%2C458%2C482%2C160%2C1404%2C1401%2C1402%2C1399%2C2111%2C1073%2C112%2C234%2C1400%2C110&page=1
08:15:41.544 T:18446744071885113648 WARNING: [urlquick] Request headers: {u'Accept-language': u'en-gb,en-us,en', u'Accept-Encoding': u'gzip, deflate', u'Host': u'api.telerama.fr', u'Accept': u'*/*', u'User-agent': u'okhttp/3.2.0', u'Connection': u'keep-alive'}
08:15:41.545 T:18446744071885113648 WARNING: [urlquick] Attempting to decode with default encoding: 'utf8'
08:15:41.545 T:18446744071885113648 WARNING: ###### debug ######
08:15:41.664 T:18446744071885113648 WARNING: CPythonInvoker(6, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui8ListItemE
08:15:41.681 T:18446744072350726448   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/main/tv_guide_menu?_pickle_=80027d71002855076d656e755f69647101580700000066725f6c697665710255075f7469746c655f710358060000004672616e63657104580b0000006974656d5f6d6f64756c6571054e55096974656d5f6469637471067d7107285804000000696e666f71087d710955057469746c65710a58060000004672616e6365710b735803000000617274710c7d710d58050000007468756d62710e587f0000002f73746f726167652f656d756c617465642f302f416e64726f69642f646174612f6f72672e78626d632e6b6f64692f66696c65732f2e6b6f64692f6164646f6e732f706c7567696e2e766964656f2e636174636875707476616e646d6f72652f7265736f75726365732f6d656469612f6368616e6e656c732f66722e706e67710f73580600000073747265616d71107d711158050000006c6162656c711258060000004672616e636571135806000000706172616d73711463636f6465717569636b2e6c697374696e670a506172616d730a7115298171167d711755087261775f646963747118680073625807000000636f6e7465787471197d711a2858090000004d6f766520646f776e711b55f358424d432e52756e506c7567696e28706c7567696e3a2f2f706c7567696e2e766964656f2e636174636875707476616e646d6f72652f6d61696e2f6d6f76655f6974656d3f5f7069636b6c655f3d383030323764373130303238353530373639373436353664356636393634373130313538303730303030303036363732356636633639373636353731303235353037366436353665373535663639363437313033353830373030303030303663363937363635356637343736373130343535303936343639373236353633373436393666366537313035353830343030303030303634366637373665373130363735326529711c580b000000436f6e6e6563742056504e711d555a58424d432e52756e506c7567696e28706c7567696e3a2f2f706c7567696e2e766964656f2e636174636875707476616e646d6f72652f7265736f75726365732f6c69622f76706e2f76706e5f6974656d5f63616c6c6261636b29711e580400000048696465711f558f58424d432e52756e506c7567696e28706c7567696e3a2f2f706c7567696e2e766964656f2e636174636875707476616e646d6f72652f6d61696e2f686964655f6974656d3f5f7069636b6c655f3d3830303237643731303035353037363937343635366435663639363437313031353830373030303030303636373235663663363937363635373130323733326529712075580800000070726f7065727479712163636f6465717569636b2e6c697374696e670a50726f70657274790a7122298171237d71242868187d712555095f6c6973746974656d71266378626d636775690a4c6973744974656d0a712729817128756275752e
08:15:41.684 T:18446744072350726448   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/main/tv_guide_menu?_pickle_=80027d71002855076d656e755f69647101580700000066725f6c697665710255075f7469746c655f710358060000004672616e63657104580b0000006974656d5f6d6f64756c6571054e55096974656d5f6469637471067d7107285804000000696e666f71087d710955057469746c65710a58060000004672616e6365710b735803000000617274710c7d710d58050000007468756d62710e587f0000002f73746f726167652f656d756c617465642f302f416e64726f69642f646174612f6f72672e78626d632e6b6f64692f66696c65732f2e6b6f64692f6164646f6e732f706c7567696e2e766964656f2e636174636875707476616e646d6f72652f7265736f75726365732f6d656469612f6368616e6e656c732f66722e706e67710f73580600000073747265616d71107d711158050000006c6162656c711258060000004672616e636571135806000000706172616d73711463636f6465717569636b2e6c697374696e670a506172616d730a7115298171167d711755087261775f646963747118680073625807000000636f6e7465787471197d711a2858090000004d6f766520646f776e711b55f358424d432e52756e506c7567696e28706c7567696e3a2f2f706c7567696e2e766964656f2e636174636875707476616e646d6f72652f6d61696e2f6d6f76655f6974656d3f5f7069636b6c655f3d383030323764373130303238353530373639373436353664356636393634373130313538303730303030303036363732356636633639373636353731303235353037366436353665373535663639363437313033353830373030303030303663363937363635356637343736373130343535303936343639373236353633373436393666366537313035353830343030303030303634366637373665373130363735326529711c580b000000436f6e6e6563742056504e711d555a58424d432e52756e506c7567696e28706c7567696e3a2f2f706c7567696e2e766964656f2e636174636875707476616e646d6f72652f7265736f75726365732f6c69622f76706e2f76706e5f6974656d5f63616c6c6261636b29711e580400000048696465711f558f58424d432e52756e506c7567696e28706c7567696e3a2f2f706c7567696e2e766964656f2e636174636875707476616e646d6f72652f6d61696e2f686964655f6974656d3f5f7069636b6c655f3d3830303237643731303035353037363937343635366435663639363437313031353830373030303030303636373235663663363937363635373130323733326529712075580800000070726f7065727479712163636f6465717569636b2e6c697374696e670a50726f70657274790a7122298171237d71242868187d712555095f6c6973746974656d71266378626d636775690a4c6973744974656d0a712729817128756275752e) failed

**Comment by SylvainCecchetto** [comment]
Hotfix pushé ba109aae7c9749d9534b9e0388456129b1d51f7c 

Je viens de forcer la màj du repo donc logiquement la version 0.2.0~beta24 est dispo pour tous automatiquement.

Par contre je n'ai pas de Windows sous la main pour tester, si quelqu'un peut me confirmer que le fix fonctionne ?

Merci et bonne journée à tous ;-)

**Comment by wwark** [comment]
Test OK sur android avec la version 0.2.0~beta24.
Je teste ce soir sur windows.
Merci pour le fix !

**Comment by funtravel1208** [comment]
Merci à tous d’avoir réglé le problème aussi rapidement!!!! 👍🏻👍🏻👍🏻

Christine

**Comment by SylvainCecchetto** [comment]
Fermeture de ce ticket --> Pour les Guides TV il est maintenant recommandé d'utiliser la nouvelle fonctionnalité de Live TV (voir https://catch-up-tv-and-more.github.io/fr/live_tv_installation/)
