### ISSUE TITLE
Veely (Websides) catchup not working

### ISSUE THREAD

**Issue by Arkadia2008** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1023]
### Describe the bug
A clear and concise description of what the bug is:
Live TV works fine but catchup programmes won't play.

### To Reproduce
Steps to reproduce the behaviour:
1.Open the addon
2.Select Veely from websites menu
3.Select any programme from one of the menues
4.

### Expected behaviour
A clear and concise description of what you expected to happen:
Video should play

### Actual behaviour
Tell us what happens instead:
Infinite loading wheel, no error message

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
  - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 19.4
 - Catch-up TV & More version: 0.2.39 beta 15
 - Installation method: Beta Repository

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):
[log](https://paste.kodi.tv/rigihatanu)

**Comment by darodi** [comment]
I can't help you sorry.
There is a geographical restriction now.
In which country is it available? 

![image](https://user-images.githubusercontent.com/4682830/208750304-76ca806a-8c4a-4ae8-8414-ee4ce123b340.png)

**Comment by joaopa00** [comment]
Royaume-uni

**Comment by joaopa00** [comment]
Kodi can play this direct link (veely/inside the royal family/Prince Willan and Prince Harry)
''https://cdn-ue1-prod.tsv2.amagi.tv/avod/simplestream-lds-ldtimln/ODYPPCS001EP001/7ff2f622-f0d0-4810-87e7-fcdf65d690c0/0.m3u8''

But it did not manaeg to play the requesting link "https://cdn-ue1-prod.tsv2.amagi.tv/avod/simplestream-lds-ldtimln/ODYPPCS001EP001/ODYPPCS001EP001.m3u8"

Need to investigate why...

**Comment by joaopa00** [comment]
Works fine for me in Windows with Kodi Matrix 19.5 and Android with Nexus 20.0
You did not provide your environment. Please do it.

**Comment by Arkadia2008** [comment]
Still not working for me with latest beta on Windows and Android running Matrix and Nexus.

[https://paste.kodi.tv/udiqawifud](url)

**Comment by Arkadia2008** [comment]
Started to work again with beta20 and latest InputStream Adaptive.

**Comment by joaopa00** [comment]
Nothing was changed in Catchuptvandmore about Veely....

**Comment by joaopa00** [comment]
Reported more or less fixed...
