### ISSUE TITLE
Mismatch broadcastername in tver.py

### ISSUE THREAD

**Issue by kalun85** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1027]
There are 2 mismatch broadcasterName values in plugin.video.catchuptvandmore/resources/lib/channels/jp/tver.jp.

### Mismatch 1
There mismatch is 読売テレビ

The current label is: 'ytv': ['読売テレ']

This mismatch causes the list_categories function to fail.

To fix, update the ytv value for Broadcaster to be : 'ytv': ['読売テレビ']

This will make it match tver API's returning result on broadcasterName.  Here is an example tver API output for ytv:

`"content": {
                    "id": "ep3pil4306",
                    "version": 5,
                    "title": "第６話：焼き小籠包の誓い",
                    "endAt": 1673189940,
                    "broadcastDateLabel": "12月25日(日)放送分",
                    "isNHKContent": false,
                    "isSubtitle": false,
                    "ribbonID": 0,
                    "seriesTitle": "失恋めし",
                    "isAvailable": true,
                    "broadcasterName": "読売テレビ",
                    "productionProviderName": "読売テレビ"
                },`

### Mismatch 2

Similar to issue above.  The broadcasterName is currently:

'tver': ['TVER']

The value should be:

'tver': ['TVer']

Here is an example API result for TVer:

`"contents": [
            {
                "type": "episode",
                "content": {
                    "id": "eponjyulzi",
                    "version": 6,
                    "title": "silent 村瀬健P 後編",
                    "endAt": 1688137140,
                    "broadcastDateLabel": "",
                    "isNHKContent": false,
                    "isSubtitle": false,
                    "ribbonID": 3,
                    "seriesTitle": "最強の時間割 〜若者に本気で伝えたい授業〜【TVer完全オリジナル】",
                    "isAvailable": true,
                    "broadcasterName": "TVer",
                    "productionProviderName": "TVer"
                },`

**Comment by joaopa00** [comment]
Thank you for this very precise report. I pushed a patch based on your orK
