### ISSUE TITLE
Add Aljazeera

### ISSUE THREAD

**Issue by ltai0001** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1030]
### Content description

* Name: Aljazeera Arabic and English
* Type [e.g. TV channel, Catch-up TV, Website, Radio]:
* Website URL: https://www.aljazeera.com/ and https://www.aljazeera.net/
* Content language/country:Arabic and English

### Content access

- [ ] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [ ] This content is geographically restricted

### More information

If you want to add more information, put it here:
Arabic and English languages with live streaming as well as on demand videos available in both websites

**Comment by darodi** [comment]
@ltai0001 

Lives added in the PR #1033 , will be available after merge.
One channel 'الوثائقية' seems geographically restricted.

Still TODO:
These sections
https://www.aljazeera.com/videos/
https://www.aljazeera.net/video
can be used fore replays

I can't read arabic.
Are there other sections with videos?
https://www.aljazeera.net/programs/  ?

**Comment by ltai0001** [comment]
@darodi 
Yes www.Aljazeera.net/programs has videos
