### ISSUE TITLE
TV de rattrapage: impossible de choisir la version originale sur Arte

### ISSUE THREAD

**Issue by cepamoi** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1034]
Ce problème affecte Arte en TV de rattrapage.

Pour les séries et films étrangers, Arte donne presque toujours la possibilité de choisir entre la version française ou la version originale sous-titrée.

Lorsque je lance la lecture d'un film ou d'une série, la bande son est en français et il n'y a pas de sous-titres.
Si j'essaie de changer le flux audio (Paramètres->Changer de flux audio), rien ne se passe, seul le français est proposé.
Pourtant, la version originale est proposée sur le site d'Arte. Voir par exemple ici:
[https://www.arte.tv/fr/videos/096217-001-A/vigil-1-6/](https://www.arte.tv/fr/videos/096217-001-A/vigil-1-6/)

Est-il possible d'avoir la version originale sous-titrée avec Arte en TV de rattrapage ?
Merci.

 - Operating system version/name: LibreElec 10.0.3
 - Kodi version: 19.4
 - Catch-up TV & More version: 0.2.39~beta07

**Comment by darodi** [comment]
@cepamoi 

C'est déjà disponible depuis la beta15

![image](https://user-images.githubusercontent.com/4682830/211206618-eff9ade5-7b2e-4d3b-be22-84fae95b4ac1.png)

**Comment by cepamoi** [comment]
Effectivement.
J'étais sur une version "stable", la beta 07. Je viens d'installer la 
beta16 et ça marche maintenant.
Merci !


Le 08/01/2023 à 17:01, darodi a écrit :
