### ISSUE TITLE
[rtl be] live - failed

### ISSUE THREAD

**Issue by nirolfa** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1038]
### Describe the bug
RTL-TVI Live : ne fonctionne plus

### To Reproduce
Steps to reproduce the behaviour:
1. Start RTL-TVI live

 - Operating system version/name: All (windows, linux, ..)
 - Kodi version: matrix
 - Catch-up TV & More version: latest dev branch

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

line 707
get_live_url
api_key=re.compile(r'login.rtl.be\
 IndexError : list out of range

**Comment by nirolfa** [comment]
linked to #1039 (same api)

**Comment by nirolfa** [comment]
@darodi 
j'ai jamais fait attention, mais est que la résolution du stream a toujours été de 960x540 ?
(j'ai vérifié car j'ai constaté une baisse en qualité d image / image un peu pixelisé par endroits)

**Comment by darodi** [comment]
@nirolfa 

je viens de regarder rapidement, je pense que c'est comme ça sur le site:
```
<Representation bandwidth="2100000" codecs="avc1.4d001f" frameRate="25" height="540" id="vcMgoH5/pjJ3BnT/eTGqnIB/v" sar="1:1" scanType="progressive" width="960"/>
<Representation bandwidth="300000" codecs="avc1.4d000c" frameRate="25" height="224" id="vTEMxhh/pjJ3BnT/eTGqnIB/v" sar="224:225" scanType="progressive" width="400"/>
<Representation bandwidth="800000" codecs="avc1.4d0016" frameRate="25" height="360" id="v5htbxW/pjJ3BnT/eTGqnIB/v" sar="1:1" scanType="progressive" width="640"/>
<Representation bandwidth="1500000" codecs="avc1.4d0016" frameRate="25" height="404" id="vu240CX/pjJ3BnT/eTGqnIB/v" sar="404:405" scanType="progressive" width="720"/>
```
