### ISSUE TITLE
6play Replay - "IndexError: list index out of range" & "Unable to retrieve the paste url"

### ISSUE THREAD

**Issue by kamil-hammouche** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1039]
### Describe the bug
I encounter an error since two days: `IndexError: list index out of range` when trying to watch a French replay and after closing the information modal, which asks me if I agree to share the error logs, an other error occurs saying "Unable to retrieve the paste url"

### To Reproduce
Steps to reproduce the behaviour:
**Télévision de rattrapage > France > 6play > M6 > Divertissement > En route pour le meilleur pâtissier > Saison 3**

### Expected behaviour
It should have started the video.

### Actual behaviour
An error occurs and the video never starts.

### Your environment
 - [X] Android

 - Operating system version/name: **Android 9.0.0 API level 28 running on Amazon Fire Stick**
 - Kodi version: **19.3.0**
 - Catch-up TV & More version: **0.2.38+matrix.1**

**Comment by Dayoros** [comment]
Same problem for me on FireTV Stick or Macbook Air M1... My Version of Kodi is 19.5

**Comment by matwillshak** [comment]
Same problem with all the channels of the M6 ​​group (Gulli, 6TER, M6).  I'm on firestick 4K.

**Comment by eragon59210** [comment]
bonjour,
depuis hier il m'est impossible de regarder les chaine du groupe M6.
je ne sais pas comment régler ce problème.
je suis un boitier android tv avec kodi 19.4

**Comment by Motopomp** [comment]
Je pense que le mode d’authentification a changer , sur le site 6play , ils demande un code pour lier un appareil…
Après je peut me tromper .
