### ISSUE TITLE
Pas de son - Kodi 18 RC1

### ISSUE THREAD

**Issue by camelreef** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#104]
Je n'ai pas de son quand je veux jouer un replay, quelle que soit la chaine ou le programme.
Mon ampli Denon AVR-2310 ne detecte pas de son qui arrive (alors qu'il indique normalement le nombre de canaux recus, la, il n'affiche rien).

J'ai bien du son AAC quand je regarde ma tele DVB via un serveur TVheadend.

Infos generales, y-compris un debug log qui essaye de jouer le 20h de France 2 (sans son a l'ampli...).

The computer is a Dell Latitude E6220, i5 Sandy Bridge with Intel video.
On-board HDMI used (2 DVI-D/DisplayPort available on attached docking station, but unused/untested).
Up-to-date Ubuntu 18.04-LTS.
Unstable Kodi PPA (18RC1 at the moment).
Followed the Intel VAAPI with v18 guide.
Framerate adjusted with a 2.5s pause.
The AVR is a Denon AVR-2310
The TV is a Toshiba 37" 1080p.

EDID manually loaded from a GRUB Option:
GRUB_CMDLINE_LINUX_DEFAULT="drm.edid_firmware=HDMI-A-1:edid/denon-edid.bin video=HDMI-A-1:e quiet splash"
EDID file copied from /sys

KODI DEBUG LOG: 
https://paste.ubuntu.com/p/W8hxKDywXN/

MESA info:
http://paste.ubuntu.com/p/9KSfnj3GZv/

VAINFO:
http://paste.ubuntu.com/p/6YF6tnMtKp/

DMESG:
http://paste.ubuntu.com/p/t9gXPYDXBQ/

ID:
http://paste.ubuntu.com/p/tcsMJPNm8Y/

AMIXER:
http://paste.ubuntu.com/p/VKywCYQKgH/

XORG LOG:
https://paste.ubuntu.com/p/dFxnqbkFJy/

J'ai un post sur le forum Kodi, des fois  que ce soit de leur cote, vu que le probleme est arrive apres le passage de Beta 4 a Release Candidate 1 de v18, et que l'addon Freplay a le meme probleme...

https://forum.kodi.tv/showthread.php?tid=337885

**Comment by SylvainCecchetto** [comment]
Bonjour camelreef,

Je n'ai pas encore regardé les logs mais comme ça au premier abord j'aurais tendance à incriminer Kodi ... Surtout si le problème est apparu après la mise à jour de Kodi et que ke problème et le même avec FReplay.

Quelques pistes pour essayer d'isoler le problème :

* Test avec Kodi 17
* Test avec un autre plugin (YouTube par exemple)

**Comment by camelreef** [comment]
Wahou, rapide!

Tester v17 est un retour en arriere assez penible, j'ai vire les bases de donnees MySQL partagees !

Je vais voir avec le plugin YouTube...

**Comment by camelreef** [comment]
Youtube marche bien, j'ai le son.

Seulle difference est que Youtube me donne de l'AAC 32 bit / 44.1 kHz alors que la tele francaise est en 32/48. Une piste pour Kodi ?

**Comment by SylvainCecchetto** [comment]
Peut être en essayant avec des fichiers vidéos pour lesquels le format de son est différent ?

**Comment by camelreef** [comment]
tout le reste marche, ac3, eac3, dts, dts-hd ma, TrueHD....

**Comment by wwark** [comment]
Hello @camelreef,
On a des vidéos hosté par Youtube par exemple sur le site Web de "Noob TV". 
Est-ce que tu arrives à avoir du son sur ces contenus?

Merci,
Wwark.

**Comment by camelreef** [comment]
Salut @wwark,

J'y accede par l'addon Catch-up TV and More ?

**Comment by wwark** [comment]
Tu le trouveras dans la section "websites" ou "site webs"

**Comment by camelreef** [comment]
Noob TV marche avec le son. La aussi, AAC 32/44.1 et pas AAC 32/48 comme les chaines de tele

**Comment by mcdu77** [comment]
> Ca marche. J'ai mis a jour le post chez Kodi. 32/48 stereo, ne marche pas. 32/44.1 stereo marche 32/48 5.1 marche
> 
> Y-compris pour des fichiers locaux, donc pas le plug-in en effet...
> 
> Merci pour le temps donne!
> 
> (et j'ai ouvert un autre bug pour LibreELEC!)

Thanks dude ! 😁
