### ISSUE TITLE
Index error list index out of range

### ISSUE THREAD

**Issue by Cecilebub** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1044]
### Content description
Bonjour.

Depuis hier impossible de lire les chaines du groupe m6 ça marque Index error.
Version Kodi 19.3
 Version Catch up tv and more 0.2.39-beta16
Box android

Si quelqu'un a une solution... merci
*

**Comment by nairolf26** [comment]
@Cecilebub, bonjour,

J'ai également eu le problème depuis 48h.
La solution est de modifier le fichier 6play.py (notamment au niveau de la fonction get_api_key())

Voir la mise à jour dans la dernière branche du projet

**Comment by Cecilebub** [comment]
Merci pour l'information mais comment fait-on sur une box android ?
Je suis désolée je suis novice dans ce domaine, je ne l'ai que depuis 10 jours...

**Comment by Cecilebub** [comment]
Merci pour l'information mais comment fait-on sur une box android ?
Je suis désolée je suis novice, je ne l'ai que depuis 10 jours...

**Comment by Cecilebub** [comment]
> @Cecilebub, bonjour,
> 
> J'ai également eu le problème depuis 48h. La solution est de modifier le fichier 6play.py (notamment au niveau de la fonction get_api_key())
> 
> Voir la mise à jour dans la dernière branche du projet

Pouvez-vous me dire comment faire car je suis novice dans ce domaine... merci

**Comment by darodi** [comment]
@Cecilebub 

https://catch-up-tv-and-more.github.io/fr/installation/#ii-ajouter-le-d%C3%A9p%C3%B4t-officiel-de-catch-up-tv--more

choisir la distribution `beta`

**Comment by darodi** [comment]
> J'ai la version beta 16

la dernière est la 17

**Comment by Cecilebub** [comment]
> > J'ai la version beta 16
> 
> la dernière est la 17

Il ne me propose pas de mise à jour...
Du coup je refais la manip d'installation totale ?

**Comment by Cecilebub** [comment]
> > J'ai la version beta 16
> 
> la dernière est la 17

J'ai refait la manip et j'ai la version beta 17 et... ça marche !!!!

Merci beaucoup 😊
