### ISSUE TITLE
Channel group M6 replay not working

### ISSUE THREAD

**Issue by Nu-Rapeup** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1049]
Since a few days, I have a "IndexError: list index out of range" when I try the channel of group M6.

Did someone has the same issue ?

**Comment by darodi** [comment]
Duplicate

- #1042
- https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1039
- #1044 
- #1046

**Comment by almoreau** [comment]
Just installed 0.2.39-beta17, seems to be working fine for all channels of M6 group !

**Comment by funtravel1208** [comment]
@darodi Thank you!
