### ISSUE TITLE
M6 and TF1 TV are not working properly!

### ISSUE THREAD

**Issue by funtravel1208** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1055]
Hello,

I love Catch-up-TV but I have 2 issues to resolve for TV French channels as follows:

1) I am having issues with M6 TV - it does not let me start this channel anymore. I get a message error " list index out of range".

2) TF1 TV is not real time anymore. It's a few hours behind compared to France.

If anyone experienced and knows how to resolve this issue, please let me know.

Thanks,

**Comment by darodi** [comment]
M6 group 
Duplicate, update to version

- #1042
- https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1039
- #1044 
- #1046 
- #1049

**Comment by funtravel1208** [comment]
Oh désolée ! Je n’ai pas cherché suffisamment.Si vous avez des infos pour TF1 qui n’est plus en real time, faites moi signe.Merci pour tout ce que vous faites! Votre logiciel est génial !!!👍🏻 ChristineSent from my iPhone 13!On Jan 14, 2023, at 10:12 AM, darodi ***@***.***> wrote:﻿
M6 group
Duplicate, update to version

#1042
#1039
#1044
#1046
#1049

**Comment by funtravel1208** [comment]
Ok, la nouvelle version a réglé tous mes problèmes ! Merci encore!ChristineSent from my iPhone 13!On Jan 14, 2023, at 10:23 AM, Christine Lascols ***@***.***> wrote:﻿Oh désolée ! Je n’ai pas cherché suffisamment.Si vous avez des infos pour TF1 qui n’est plus en real time, faites moi signe.Merci pour tout ce que vous faites! Votre logiciel est génial !!!👍🏻 ChristineSent from my iPhone 13!On Jan 14, 2023, at 10:12 AM, darodi ***@***.***> wrote:﻿
M6 group
Duplicate, update to version

#1042
#1039
#1044
#1046
#1049
