### ISSUE TITLE
Ne marche pas sur LibreELEC (Leia) v8.90.008 ALPHA

### ISSUE THREAD

**Issue by camelreef** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#106]
selection de catch-up (20h de France 2 dans les logs), et la roue tourne... tourne...et disparait... et rien...

Debug log:
http://ix.io/1uKA

**Comment by wwark** [comment]
Hello,
On a eu une erreur de timeout

19:40:11.389 T:1451402096   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
19:40:11.389 T:1451402096   ERROR: CCurlFile::Open failed with code 0 for http://replayftv-vh.akamaihd.net/i/streaming-adaptatif/2018/S48/J2/193403607-5bfd9dba797ae-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/master.m3u8?caption=%2F2018%2F11%2F27%2F%2F193403607-5bfd9dba797ae-1543348020.m3u8%3Afra%3AFrancais&audiotrack=0%3Afra%3AFrancais

Est-ce que tu peux essayer de lire cette url via VLC pour voir si ça marche depuis le même réseau où s'exécute Kodi?

**Comment by camelreef** [comment]
`Bob:~ nicolaswill$ ffmpeg -i "http://replayftv-vh.akamaihd.net/i/streaming-adaptatif/2018/S48/J2/193403607-5bfd9dba797ae-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/master.m3u8?caption=%2F2018%2F11%2F27%2F%2F193403607-5bfd9dba797ae-1543348020.m3u8%3Afra%3AFrancais&audiotrack=0%3Afra%3AFrancais"
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 10.0.0 (clang-1000.11.45.5)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.1 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gpl --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-opencl --enable-videotoolbox
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[hls,applehttp @ 0x7fdb5c800400] Opening 'http://replayftv-vh.akamaihd.net/i/streaming-adaptatif/2018/S48/J2/193403607-5bfd9dba797ae-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/index_0_av.m3u8?null=0' for reading
[http @ 0x7fdb5c81b400] Opening 'http://replayftv-vh.akamaihd.net/i/streaming-adaptatif/2018/S48/J2/193403607-5bfd9dba797ae-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/index_1_av.m3u8?null=0' for reading
[http @ 0x7fdb5c81b400] Opening 'http://replayftv-vh.akamaihd.net/i/streaming-adaptatif/2018/S48/J2/193403607-5bfd9dba797ae-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/index_2_av.m3u8?null=0' for reading
[http @ 0x7fdb5c81b400] Opening 'http://replayftv-vh.akamaihd.net/i/streaming-adaptatif/2018/S48/J2/193403607-5bfd9dba797ae-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/index_3_av.m3u8?null=0' for reading
[http @ 0x7fdb5c81b400] Opening 'http://replayftv-vh.akamaihd.net/i/streaming-adaptatif/2018/S48/J2/193403607-5bfd9dba797ae-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/index_4_av.m3u8?null=0' for reading
[hls,applehttp @ 0x7fdb5c800400] Opening 'http://replayftv-vh.akamaihd.net/i/streaming-adaptatif/2018/S48/J2/193403607-5bfd9dba797ae-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/segment1_0_av.ts?null=0' for reading
[hls,applehttp @ 0x7fdb5c800400] Opening 'http://replayftv-vh.akamaihd.net/i/streaming-adaptatif/2018/S48/J2/193403607-5bfd9dba797ae-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/segment2_0_av.ts?null=0' for reading
[hls,applehttp @ 0x7fdb5c800400] Opening 'http://replayftv-vh.akamaihd.net/i/streaming-adaptatif/2018/S48/J2/193403607-5bfd9dba797ae-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/segment1_1_av.ts?null=0' for reading
[hls,applehttp @ 0x7fdb5c800400] Opening 'http://replayftv-vh.akamaihd.net/i/streaming-adaptatif/2018/S48/J2/193403607-5bfd9dba797ae-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/segment2_1_av.ts?null=0' for reading
[hls,applehttp @ 0x7fdb5c800400] Opening 'http://replayftv-vh.akamaihd.net/i/streaming-adaptatif/2018/S48/J2/193403607-5bfd9dba797ae-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/segment1_2_av.ts?null=0' for reading
[hls,applehttp @ 0x7fdb5c800400] Opening 'http://replayftv-vh.akamaihd.net/i/streaming-adaptatif/2018/S48/J2/193403607-5bfd9dba797ae-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/segment2_2_av.ts?null=0' for reading
[hls,applehttp @ 0x7fdb5c800400] Opening 'http://replayftv-vh.akamaihd.net/i/streaming-adaptatif/2018/S48/J2/193403607-5bfd9dba797ae-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/segment1_3_av.ts?null=0' for reading
[hls,applehttp @ 0x7fdb5c800400] Opening 'http://replayftv-vh.akamaihd.net/i/streaming-adaptatif/2018/S48/J2/193403607-5bfd9dba797ae-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/segment2_3_av.ts?null=0' for reading
[hls,applehttp @ 0x7fdb5c800400] Opening 'http://replayftv-vh.akamaihd.net/i/streaming-adaptatif/2018/S48/J2/193403607-5bfd9dba797ae-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/segment1_4_av.ts?null=0' for reading
[hls,applehttp @ 0x7fdb5c800400] Opening 'http://replayftv-vh.akamaihd.net/i/streaming-adaptatif/2018/S48/J2/193403607-5bfd9dba797ae-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/segment2_4_av.ts?null=0' for reading
Input #0, hls,applehttp, from 'http://replayftv-vh.akamaihd.net/i/streaming-adaptatif/2018/S48/J2/193403607-5bfd9dba797ae-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/master.m3u8?caption=%2F2018%2F11%2F27%2F%2F193403607-5bfd9dba797ae-1543348020.m3u8%3Afra%3AFrancais&audiotrack=0%3Afra%3AFrancais':
  Duration: 00:37:03.15, start: 0.100667, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 192000
    Stream #0:0: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yuv420p, 256x144 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 192000
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 192000
  Program 1 
    Metadata:
      variant_bitrate : 313000
    Stream #0:2: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yuv420p, 320x180 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 313000
    Stream #0:3: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 313000
  Program 2 
    Metadata:
      variant_bitrate : 593000
    Stream #0:4: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yuv420p, 512x288 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 593000
    Stream #0:5: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 593000
  Program 3 
    Metadata:
      variant_bitrate : 850000
    Stream #0:6: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 704x396 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 850000
    Stream #0:7: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 850000
  Program 4 
    Metadata:
      variant_bitrate : 1497000
    Stream #0:8: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 1024x576 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 1497000
    Stream #0:9: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 1497000`

Ca marche nickel dans VLC, image et son.

**Comment by camelreef** [comment]
C'est space, depuis une autre machine du reseau:

`wget` -S "http://replayftv-vh.akamaihd.net/i/streaming-adaptatif/2018/S48/J2/193403607-5bfd9dba797ae-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/master.m3u8?caption=%2F2018%2F11%2F27%2F%2F193403607-5bfd9dba797ae-1543348020.m3u8%3Afra%3AFrancais&audiotrack=0%3Afra%3AFrancais"
--2018-11-28 21:33:41--  http://replayftv-vh.akamaihd.net/i/streaming-adaptatif/2018/S48/J2/193403607-5bfd9dba797ae-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/master.m3u8?caption=%2F2018%2F11%2F27%2F%2F193403607-5bfd9dba797ae-1543348020.m3u8%3Afra%3AFrancais&audiotrack=0%3Afra%3AFrancais
Resolving replayftv-vh.akamaihd.net (replayftv-vh.akamaihd.net)... 90.223.233.139, 90.223.233.136
Connecting to replayftv-vh.akamaihd.net (replayftv-vh.akamaihd.net)|90.223.233.139|:80... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Server: AkamaiGHost
  Content-Length: 1838
  Content-Type: application/vnd.apple.mpegurl
  Set-Cookie: _alid_=AmUTLANyR+Gdl4CiGeWM5A==; path=/i/streaming-adaptatif/2018/S48/J2/193403607-5bfd9dba797ae-,standard1,standard2,standard3,standard4,standard5,.mp4.csmil/; domain=replayftv-vh.akamaihd.net
  Mime-Version: 1.0
  Access-Control-Allow-Origin: *
  Expires: Wed, 28 Nov 2018 21:33:41 GMT
  Cache-Control: max-age=0, no-cache
  Pragma: no-cache
  Date: Wed, 28 Nov 2018 21:33:41 GMT
  Connection: keep-alive
Length: 1838 (1.8K) [application/vnd.apple.mpegurl]
Saving to: `‘master.m3u8?caption=%2F2018%2F11%2F27%2F%2F193403607-5bfd9dba797ae-1543348020.m3u8:fra:Francais&audiotrack=0:fra:Francais’`

master.m3u8?caption=%2F2018%2F11%2F27%2 100%[==============================================================================>]   1.79K  --.-KB/s    in 0s      

2018-11-28 21:33:41 (72.4 MB/s) - ‘master.m3u8?caption=%2F2018%2F11%2F27%2F%2F193403607-5bfd9dba797ae-1543348020.m3u8:fra:Francais&audiotrack=0:fra:Francais’ saved [1838/1838]
```

Mais depuis le Pi avec LibreELEC, zero connection avec wget...

**Comment by wwark** [comment]
Ok merci pour le test.
Est-ce que la vidéo a mis du temps à se lancer dans VLC ?
Kodi a un timeout par défaut et s'il dépasse ce timeout. La vidéo n'est pas lue.

Il est possible que ce point arrive de temps en temps à cause la connexion internet.

SI la connexion internet est lente et que le problème persiste. il y a des options dans Kodi pour augmenter ce timeout détaillé ici: https://kodi.wiki/view/Advancedsettings.xml#network

Merci,
Wwark

**Comment by camelreef** [comment]
Quasiment instantanne dans VLC, ainsi que sur une autre machine Kodi Linux (pas LibreELEC).

**Comment by wwark** [comment]
Un VPN qui tournerait ? ou autre chose qui bloquerait la partie réseau sur LibreElec?

**Comment by camelreef** [comment]
Pas un pb de resolution de nom depuis le Pi LibreELEC non plus... C'est la connection qui est refusee silencieusement, on dirait.

Chambre:~ # ping replayftv-vh.akamaihd.net
PING replayftv-vh.akamaihd.net (176.31.111.191): 56 data bytes
64 bytes from 176.31.111.191: seq=0 ttl=56 time=10.644 ms
64 bytes from 176.31.111.191: seq=1 ttl=56 time=75.651 ms
64 bytes from 176.31.111.191: seq=2 ttl=56 time=10.507 ms

--- replayftv-vh.akamaihd.net ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss

Non, pas de VPN, pas non plus de service DNS/proxies pour delivrer du geobloquage...

**Comment by wwark** [comment]
OK. Est-ce qu'il serait possible de faire un test sur un Kodi déployé sur la même machine que VLC?

Si le test est passant. Il faudrait soumettre le log à l'équipe LibreElec. Il pourrait surement déterminer dans les logs la cause du timeout sur cette instance.

**Comment by camelreef** [comment]
Bon...

Ayant reflechi plus longtemps au service DNS/proxies pour delivrer du geobloquage...

J'en avais essaye un il y a plus d'1 an, le truc gratuit genre 1 mois. J'etais donc passe en configuration IP manuelle. Puis repasse en DHCP une fois la periode d'essai passee. Je ne suis pas plus passionne que ca par la tele francaise, les news me suffisent.

Je viens donc de verifier la configuration IP... qui etait repassee en manuel avec les DNS du service !

Repassage en DHCP.

Et la Akamai ne resoud plus sur la meme adresse, et j;ai un serveur au bout que me repond !

Ca remarche, et je sais pourquoi...

Desole du derangement pour un truc de mon cote... (meme si c'est etrange que le systeme repeche une vieille config manuelle...).

Ticket clos !

**Comment by wwark** [comment]
Cool :) Au dodo pour moi !

**Comment by camelreef** [comment]
Pareil ! Merci pour le temps donne !
