### ISSUE TITLE
Plus de chaînes rtl tvi sur catch-up tv

### ISSUE THREAD

**Issue by Rxman06** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1060]
Depuis quelques jours plus d accès au chaînes belge rtl tvi plug...
Index error list index out of range

**Comment by darodi** [comment]
@Rxman06 

déjà fixé, mettre à jour vers la dernière beta.
Voir les tickets existants déjà fermés.

**Comment by nirolfa** [comment]
@darodi  @joaopa00 
rtl-be de nouveau pas ok, mais m6 marche
