### ISSUE TITLE
Erreur List index out of range sur replay M6

### ISSUE THREAD

**Issue by jackbubble** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1062]
J'ai l'erreur List index out of range lors des tentatives de replay sur la chaîne 6Play M6.

Ça fonctionnait bien sur la version précédente, mais plus sur la dernière version.

J'ai Kodi version 20, mais c'était la même chose sur la version 19.5.

**Comment by joaopa00** [comment]
Déjà fixé dans la dernière béta.
