### ISSUE TITLE
Error open live TV - France - M6

### ISSUE THREAD

**Issue by FM0813** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1064]
### Describe the bug
Error message while opening channel M6 in live channels /France
Similar error for other channels of M6 group such as W9

### Expected behaviour
A clear and concise description of what you expected to happen:

### Actual behaviour
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android and Google TV

### Debug log

https://paste.kodi.tv/oteyexaqar

**Comment by joaopa00** [comment]
Déjà résolu dans la béta 18
