### ISSUE TITLE
Plantage de kodi sur chaine du groupe M6

### ISSUE THREAD

**Issue by b-remi** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1066]
### Describe the bug
Bonjour à tous,
Ayant eu le bug du groupe M6 présent sur le channel stable, je suis passé sur la version beta du plugin, mais ça ne fonctionne toujours pas de mon coté. Je n'ai plus de message d'erreur présent dans la version stable (list index out of range) mais un plantage complet de l'interface dès que j'essai de lancer la chaine M6 (ou autre du groupe).
L'installation OSMC est toute fraiche de mercredi matin, afin de pouvoir tester et reproduire le bug dans un environnement le plus propre possible.
Le plugin a été installé suivant la procédure présente sur votre site. Il n'y a aucune autre config particulière faite sur le système.

### To Reproduce
Steps to reproduce the behaviour:
Accèder à TV en direct > France > M6

### Expected behaviour
A clear and concise description of what you expected to happen:
Pouvoir voir la chaine M6 en direct

### Actual behaviour
Tell us what happens instead:
Plantage de kodi et redemarrage d'OSMC

### Your environment
Raspbery Pi 3
 - Operating system version/name: OSMC October 2022.10-1
 - Kodi version: 19.4
 - Catch-up TV & More version: 0.2.39 beta18
 - Installation method: via dépot officiel https://catch-up-tv-and-more.github.io/repo/

### Debug log
Voila le fichier de log, en mode debuggage activé avec tous les paramètres de log actif (il me semble)
[http://paste.kodi.tv/nehumelagu](http://paste.kodi.tv/nehumelagu)

Si il manque des détails, des infos, ou si je peux tester des solutions, n'hesitez pas à prevenir.
Merci à toute l'equipe pour le travail effectué.

**Comment by joaopa00** [comment]
Est-ce que les chaînes francetelevisions fonctionnent?
Il semblerait que Widevine n'est pas installé.

**Comment by b-remi** [comment]
Bonjour, merci pour la réactivité.
Etant sur une nouvelle installation, je me rappelais plus si widevine avait été installé.
Je viens de retester a l'instant, les chaines de FranceTélévision fonctionne sans souci (Tester sur France 2, France 3).
Les chaines du groupe TF1 aussi, aucun souci.

**Comment by joaopa00** [comment]
As-tu bien rentré tes identifiants?

**Comment by b-remi** [comment]
Oui, les identifiants sont saisies pour le groupe M6 dans les paramètres.
Par contre, je suis entrain de regarder le fichier de logs que je vous ai transmis, il ne correspond pas au plantage, mais au fichier après redemarrage.

Y'a-t-il un moyen d'uploader les logs de l'instance précedente depuis le plugins Kodi Logfile Uploader (ou un autre moyens pour les récupérer).

**Comment by b-remi** [comment]
ok, désolé, je viens de trouvé dans les paramètres du plugins.
Je régénére des logs et vous envoi ça

**Comment by b-remi** [comment]
Voila le processus réalisé : 
21h27: démarrage d'OSMC et de CatchUp (Tv en direct > France)
21h29: lancement de M6 & plantage / redemarrage
21h30 : génération et envoi des logs
=> No crash logs found
=> upload log file to https://paste.kodi.tv/tikabikuta
=> Error posting the old log file. The file is too large. Max size is 1MB

J'essai de trouver l'ancien fichier de logs via ssh et vous le transmettre.

**Comment by b-remi** [comment]
[kodi.old.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/10473032/kodi.old.log)

Voila le fichier de logs correspondant.
J'y ai jeter un oeil vite fait mais ne vois aucune erreur particulière...

**Comment by joaopa00** [comment]
Le log s'arrête juste au moment où le fluw va être décrypté. C'est un problème de widevine qui est embarqué dans ton système. Il faut que tu rapportes ça à ta distribution.

**Comment by b-remi** [comment]
Ok, j'irai voir du côté osmc ce que je peux trouver alors.

Pour info, avez vous une idée de pourquoi ça fonctionne quand même pour les autres chaînes TV. Widevine est bien utilisé aussi sur France Télévision et TF1 non?

**Comment by joaopa00** [comment]
Les flux ne font pas les mêmes types de requêtes de license. Cela dépend donc de la license utilisée.

**Comment by Nico83500** [comment]
Pour info j'ai un problème identique sur les replays du groupe M6, pas testé le live. Je suis pour ma part sur Android TV Pro 2019, je vais tester le live et essayer de générer les logs.

**Comment by joaopa00** [comment]
Il faut donner le nom d'une vidéo qui pose problème et le façon d'y accéder par catchuptvandmore.

**Comment by toto6976** [comment]
Bonjour,
Je ne peux pas accéder aux programmes du groupe m6. J'ai un écran et des annonces ou pubs qui tournent en boucle avec écrit : ce programme ne peut être accessible sur cet appareil; (ou un truc équivalent).
J'ai rentré les codes...
Lorsque je vais sur le site via mon ordi, on me dit de me synchroniser via un code qui s'affiche sur la tv. Cela fonctionne avec ma tv et le boitier 'mi box' mais pas sur la tv avec le boitier 'raspberry'.

**Comment by enigma131** [comment]
Widevine est utiisé aussi pour les chaînes du groupe BFM. Faut un identifiant aussi, à tester

**Comment by joaopa00** [comment]
@toto
Ton problème n'est certainement pas lié à ce rapport de bug. Ouvre un nouveauticket s'il te plaît.

**Comment by Falcou85** [comment]
J’ai le même problème sur M6 mais je pense que c’est globale catch up le live fonctionne en plus y’a la nouvelle version kodi nexus qui vient de sortir mais je ne pense pas que c’est lié

**Comment by nirolfa** [comment]
m6 ok pour moi, mais rtl-be marche plus :(

**Comment by joaopa00** [comment]
Il ne faut pas utiliser les rapports de bugs d'autres intervenants si on ne peut pas prouver que c'est le même problème. Ouvrez de nouveaux rapports de bugs s'il vous plaît.

**Comment by nirolfa** [comment]
@joaopa00 oui; ok. Sorry.
C'est juste que c est le meme groupe, donc en general quand y a un bug sur l un, le bug est sur les 2 chaines ;)

**Comment by joaopa00** [comment]
Donc ouvre un nouveau rapport. N'oublie pas d'y attacher  un log complet avec le mode déboggage activé ainsi que les channels curl, ffmepeg audio, video,

**Comment by Nico83500** [comment]
Comment générer et envoyer les logs svp ?

**Comment by ouinouin** [comment]
meme issue ici depuis quelques jours aussi sur PC nuc , j'ai upgradé widevinde avec le helper de libreelec., upgradé libreelec aussi en 10.0.4, (embarque kodi 19.5 je vais voir si une beta de catchup tv ameliore les choses.

**Comment by b-remi** [comment]
Pour ma part, le problème a bien l'air de venir d'osmc.
J'ai refait une installation avec la dernière version de Librelec et je n'ai plus de souci a ce niveau. 
Par contre, je confirme qu'il faut dans tous les cas utiliser le Channel beta pour avoir les derniers correctifs. Le Channel stable est encore buggé a l'heure actuelle.

@Nico83500 pour générer et envoyer les logs de Kodi, j'utilise le plugin Kodi Logfile Uploader

**Comment by Nico83500** [comment]
Merci, j'essaye de faire ça ce soir.
J'ai juste remarqué 2 différences : sur une Shield Pro 2019 avec Kodi 20 + Catch Up stable, j'ai une erreur List out of range. Sur une autre Shield Pro 2019 avec Kodi 20 + Catch Up bêta, j'ai une erreur Échec d'authentification 
Je vais générer les logs pour les 2 ce soir ou demain

**Comment by darodi** [comment]
@Nico83500 
La version stable est en retard sur la beta. Ça ne sert à rien de tester la stable.
List out of range est corrigé en beta.

**Comment by Rimtef** [comment]
Bonjour, j'ai désinstallé la version d'origine et installé la béta et cela corrige le problème avec M6.

Mais Problème avec TF1 : j'entends le son mais je ne vois pas l'image et j'ai la roue bleue immobile sur l'écran ( celle qui apparait au lancement d'une chaine)...

**Comment by darodi** [comment]
@Rimtef 

TF1 est une autre chaîne, un autre module.
Ouvrir une autre issue pour ça

**Comment by joaopa00** [comment]
Pour éviter que ce rapport soit recyclé à l'infini pour des choses non reliées, je le ferme puisque le problème est principalement résolu.

**Comment by Rimtef** [comment]
Ce lien :  dépot officiel https://catch-up-tv-and-more.github.io/repo/

Il mène vers la béta 0.0.6 et pas vers la  0.2.39 beta18...

**Comment by joaopa00** [comment]
Au minimum, il faut lire le wiki d'installatin [wiki](https://catch-up-tv-and-more.github.io/fr/installation/)

**Comment by Rimtef** [comment]
Merci donc cela veut dire qu'en ayant installé la béta 0.0.6, elle s'est mise à jour à la dernière version.

Donc comment expliquer que le replay de Tf1 ne fonctionne plus ? et comment résoudre le problème?
cordialement

**Comment by joaopa00** [comment]
L'API du replay de TF1 a changé. Il y a déjà eu un rapport de bug de pour ça (voir #1091). Il vient d'être réglé dans GIT par un intervenat (merci à lui !!)
