### ISSUE TITLE
BVN TV has stopped playing

### ISSUE THREAD

**Issue by nzljohn** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1067]
### Describe the bug

Everything works in catchup except BVN live.

Steps to reproduce the behaviour:
1.  Go to TV channels Live TV
2.  Click on international
3.  Click on BVN (Dutch TV)
4.  Message appears "List index out of range"

 Expected behaviour
The channel normally appears

Actual behaviour
Message pops up "List index out of range"

### Your environment
 Android
 
 
 

 - Operating system version/name:
 - Kodi version: 20
 - Catch-up TV & More version: 2.38
 - Installation method: I did a factory reset and installed Kodi20 via USB
 - Then installed catchup 2.38

All the other channels work, but not BVN

**Comment by joaopa00** [comment]
Give a try at the beta-18

**Comment by nzljohn** [comment]
I installed beta-18.
BVN live TV now works. Thank you very much.
By the way, is there anyone (perhaps yourself) that I can get to do a programing job for me.
I would like to pay someone to make a program that will get just one channel (BVN live) on an android box.
When the box turns on, it should automatically display BVN live. No buttons to push or any clicking.
This is for old people who are not technical. Perhaps you can refer me to someone.

**Comment by joaopa00** [comment]
Closed as fixed
