### ISSUE TITLE
Some archived programs not playing BVN catchup TV

### ISSUE THREAD

**Issue by nzljohn** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1069]
### Describe the bug
I don't know if this is fixable.
About 20% of archived TV programs on BVN catchup will not play. Comes up with "Playback failed" " One or more items failed to play. 
Check the log for more information about this message"
The other 80% or so play fine.

I have the same symptom on 
          2 x Windows 10 computer
          multiple android boxes running Kodi20
          I have tried multiple boxes just to be sure.
          They all do exactly the same.
          They all miss the same TV programs.

### To Reproduce
Steps to reproduce the behaviour:
1.  Click on CatchupTV addon.
2.  Click Catch-up TV  (Not live TV)
3.  Click international
4.   Click BVN
5.   Click Zondag 22 jan
6.   Click 16:45-Ivo op zondag (This is one of the archived programs that does not play. There are others.)
8.  Error message pops up

### Expected behaviour
TV program should play. (About 80% do play)

### Actual behaviour
"Playback failed" message pops up.

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
  - [ ] Windows

 - Operating system version/name:
 - Kodi version: 20
 - Catch-up TV & More version: Beta-18 (The previous 2.38 version did the same.)
 - Installation method: via USB from downloaded apk

### Additional context
I have had the same problem on all boxes I have used.

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):
Error log is:
https://paste.kodi.tv/ezevisomid

Hope I did it right.

**Comment by joaopa00** [comment]
Can you play them from the site?
For me, the list of available programs is empty.

**Comment by nzljohn** [comment]
I have done a comparison.
The programs that will not play on catchup will play on the site.

**Comment by nzljohn** [comment]
I have a log file for this example.
https://paste.kodi.tv/eniratiyaw
This example will not play on my android box with kodi 20 catchup-beta18 but
will play on my windows computer from the site.

**Comment by joaopa00** [comment]
Thanks for the log. A note: the next time please enable debugging and specific channels (curl, ffmpeg,video,audion). With luck I think I found the proble in the small log you attached.
Problem should be fixed in GIT.
