### ISSUE TITLE
Perfect player and replay

### ISSUE THREAD

**Issue by Che-debarras** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#107]
Désolé pour cette question mais est ce que votre plugin est compatible avec perfect player?
C'est un lecteur qui accepte des plugins et je me demande si le votre est compatible vu que j'ai lu que votre plugin peut etre lu en dehors de kodi

Ce n'est pas un souci mais un souhaite pour un request

**Comment by wwark** [comment]
Bonjour @Che-debarras,

Ce plugin est compatible que pour Kodi.
Nous n'avons pas prévu de porter ou de rendre compatible pour d'autres applications.

Merci,
Wwark

**Comment by wwark** [comment]
Je ferme ce ticket.
N'hésite pas à le rouvrir si besoin.
Merci,
Wwark
