### ISSUE TITLE
Beta-18 fixes BVN live but knocks out NPO1 and NPO2

### ISSUE THREAD

**Issue by nzljohn** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1072]
### Describe the bug
I previously lost BVN live  (the free to air dutch TV)
Upon installing beta-18 this was fixed.
The problem is that now I cannot get NPO1 or any other dutch Tv that requires a vpn
I can go back to the old catchup and get NPO1 and 2 (with the VPN)but then I loose BVN

I am using android 10 and up and Kodi 20
 I have tried on more than one box with the same result.

**Comment by joaopa00** [comment]
There is a canvas when one fills a bug reort. Please uses it. Useful informations are missing. For instance what version of catchuptvandmore do you use? Where is the log?

**Comment by joaopa00** [comment]
We need a log. Without it, there is nothing we can try to do.

**Comment by nzljohn** [comment]
This is the log file for when I try to open NPO1
Catchup2.39-beta18
This is with VPN on.
https://paste.kodi.tv/xupafomici
This is the one that does not work.
------------------------------------------------------------------
Catchup 2.38 works on NPO1

**Comment by joaopa00** [comment]
I did a regression test. As predictable, the bad commit is
git bisect bad
f492c475be813143b8f6d1b964dd62d8853fbea8 is the first bad commit
commit f492c475be813143b8f6d1b964dd62d8853fbea8
Author: Age Bosma <age.bosma@protonmail.com>
Date:   Thu Nov 17 16:13:43 2022 +0100

    [NL- NPO]: Fix infos

 resources/lib/channels/nl/npo.py | 255 ++++++++++++++++++++-------------------
 1 file changed, 133 insertions(+), 122 deletions(-)

**Comment by joaopa00** [comment]
Ifound the culprit. Will send a patch soon.

**Comment by joaopa00** [comment]
Fixed in git.
