### ISSUE TITLE
M6 direct and replay error: list index out of range

### ISSUE THREAD

**Issue by QuentinLf** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1073]
Bonjour,

Je viens d'installer Kodi 20 ainsi que Catch-up TV & More (version stable) sur ma TV android.
J'ai suivi quelques tuto, je peux regarder TF1 et France 2 en direct et en replay. Par contre, dès que je lance M6 soit en direct, soit en replay j'ai un message d'erreur qui s'affiche disant "list index out of range". 

J'ai pourtant indiqué mon identifiant et mot de passe 6Play dans les paramètres de Catch-up TV & More.

Avez vous déjà rencontré ce problème ? Comment le résoudre ?

Merci :)

**Comment by khalistoo** [comment]
@QuentinLf  peux tu essayer d'installer la dernière beta via le repo beta que tu peux trouver a cette address: 
[https://catch-up-tv-and-more.github.io/repo/Beta_channel/](https://catch-up-tv-and-more.github.io/repo/Beta_channel/)

**Comment by david63236** [comment]
Looks like the same problem as RTLplay (.be), the api_key is not found.
I tested the "dernière beta" and it solves the RTLplay problem, but as i'm not in france i think i can not test 6Play...
PS: I already closed my issue 1075 for RTLplay

**Comment by david63236** [comment]
Great news, the "dernière beta" version successfully plays all the RTBF Auvio (.be) videos.
I can now use the "Catch-up TV & More" add-on as replacement for the "RTBF Auvio" add-on.

**Comment by QuentinLf** [comment]
Bonjour,

Merci pour vos conseils, j'ai désinstallé la version stable de Catch-up TV puis réinstallé la version Beta et M6 replay et direct fonctionnent correctement.

**Comment by pulsarcust** [comment]
Bonjour,

J'avais le même problème et j'ai désinstallé laversion stable pour installer la version beta disponible dans le repo partagé par Khalistoo.
Ca ne marche pas tout a fait. Je n'ai plus d'erreur, par contre je n'ai que le son et pas l'image pour les chaines du groupe M6. Les autres ca fonctionne. 
Des idées ?

**Comment by darodi** [comment]
@joaopa00 

Il vaudrait mieux changer le titre ou ouvrir un ticket pour 
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1073#issuecomment-1406895579
"reference in new issue"
