### ISSUE TITLE
The rmc replay no longer works I try to watch top gear replays

### ISSUE THREAD

**Issue by monfiston** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1076]
### Describe the bug
Hello
The rmc replay no longer works I try to watch top gear replays, but it does not work, see The error message
![d9yr](https://user-images.githubusercontent.com/109015014/214644242-4ffc9420-a1d9-4ff0-bb2a-9582af82275a.jpg)

### Your environment
  - [ ] Linux correlec

 - Operating system version/name:
 - Kodi version:18.9
 - Catch-up TV & More version:02.39 beta 18

**Comment by joaopa00** [comment]
Il faut attacher le log avec le mode débogagge active ainsi que les channels curl video ffmpeg

**Comment by joaopa00** [comment]
Devrait être résolu dans GIT.
