### ISSUE TITLE
Failure to install a dependency

### ISSUE THREAD

**Issue by Condottiero1** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#108]
https://pastebin.com/QU65jJ6X
Avec Win 10 et Kodi 17.6
Cordialement

**Comment by wwark** [comment]
Bonjour,

Merci pour ces logs. Les logs indique que la dépendance script.module.pytz-2014.2.zip ne peut pas être téléchargée et les logs remontent beaucoup d'erreur.
Cette dépendance est téléchargée sur un repo (ligne 511) ne fonctionnant plus et qui n'est pas un repo officiel de Kodi.

Il faudrait désinstaller ce répo ou télécharger ce zip "script.module.pytz-2014.2.zip" ici https://mirrors.kodi.tv/addons/krypton/script.module.pytz/ et l'installer.

La mise à jour du plugin '0.2.0' devrait fonctionner ensuite.

Merci,
Wwark.

**Comment by Condottiero1** [comment]
Merci beaucoup Wwark. En effet je n'avais pas vu que le Smash Repo avait ete ferme. J'ai elimine Smash et la mis a jour a fonctionne.

Condottiero
