### ISSUE TITLE
VEELY: python 2 error: 'return' with argument inside generator 

### ISSUE THREAD

**Issue by joaopa00** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1080]
### Describe the bug
When using veely on Leia, the mentioned error occurs. Always the infamous error with yield in python 2....

### To Reproduce
1. Use a VPN from UK
2. Websites
3. Veely

### Expected behaviour
List of programs shows

### Actual behaviour
Kodi fails with an error

### Your environment
 - [x] Linux

 - Operating system version/name:
 - Kodi version: 18.9
 - Catch-up TV & More version: 0.39 beta18
 - Installation method: by zip

### Additional context
Problem does not occur with CUTVM greater than Leia.

### Debug log
[log.txt](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/10525282/log.txt)

**Comment by darodi** [comment]
@joaopa00 

avec ceci, ça irait mieux?

```
@Route.register
def list_programs(plugin, url, **kwargs):
    program = url_constructor(url)

    if (URL_LIVE == program) or (URL_LIVE + '/' == program):
        from resources.lib.kodi_utils import PY3
        if PY3:
            return False
        else:
            yield False
            return
```

**Comment by joaopa00** [comment]
Malheureusement, cela ne résout pas le problème. Toujours le même message d'erreur.

**Comment by darodi** [comment]
je vais essayer d'installer un kodi 18.x pour voir

**Comment by joaopa00** [comment]
Devrait être résolu dans GIT.
