### ISSUE TITLE
runtime error impossible de résoudre l'url

### ISSUE THREAD

**Issue by toto6976** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1081]
Bonjour,
J'utilise catchup tv beta 17 sur kodi matrix 19.4 le tout sur raspi 3 avec dietpi v7 32 bits.

Les chaines du groupe C : C8 Cnews Cstar me renvoient la même erreur : 
'runtime error impossible de résoudre l'url'.
Je peux poster le log de kodi si vous avez besoin. 

Pouvez-vous m'aider ?

**Comment by joaopa00** [comment]
Pouquoi avoir effacer le canevas de rapport de bug pour écrire ton propre rapport de bug?
Remplis le canevas et il y aura alors les informations que l'on a besoin pour essayer de résoudre ton problème.
