### ISSUE TITLE
Problème avec TF1 sur catch up TV béta

### ISSUE THREAD

**Issue by Rimtef** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1082]
### Content description

* Name:
* Type [e.g. TV channel, Catch-up TV, Website, Radio]: catch up TV béta / TF1
* Website URL:
* Content language/country: french

### Content access

- [ ] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [ ] This content is geographically restricted

### More information

If you want to add more information, put it here: j'ai installé la béta de catch up TV pour résoudre un problème sur M6.
cela m'a résolu le problème avec M6 mais j'ai maintenant un problème avec TF1 : j'entends le son mais je ne vois pas l'image et j'ai la roue bleue immobile sur l'écran ( celle qui apparait au lancement d'une chaine)...
Est ce que quelqu'un voit une solution ? Merci par avance

**Comment by joaopa00** [comment]
Ce n'est pas un problème de CUTVM mais de Inpustream adaptive. Voir  [rapport de bug sur IA]((https://github.com/xbmc/inputstream.adaptive/issues/1043#issuecomment-1387532120)

**Comment by Rimtef** [comment]
Votre réponse est du chinois pour moi...pourquoi avoir clot le topic ?

**Comment by sancelot** [comment]
je vois pas trop le rapport avec IA. puisque ca fonctionne en stable.

**Comment by Rimtef** [comment]
OK alors comment résoudre ce problème?

**Comment by sancelot** [comment]
Dans mon cas, j 'ai compris ce qui se passe . 
Cela n'a rien a voir avec un pb d input stream adaptative mais plutot un pb de configuration je pense . 
Je m explique . Dans les paramètres, j ai activé input stream hls . j ai bien le meme pb : on a le son mais un écran noir avec la "roue" bleue. 
j ai pris ma télécommande, et appuyé sur ok, pour afficher l'osd (le panel avec les boutons d infos etc ....), j ai séléctionné la barre du player qui avait le taquet tout a droite. j ai reculé le taquet avec la fleche gauche de ma télécommande .... et la l image apparait  .... c'est donc un pb de paramétrage de la mise en tampon je suppose.

**Comment by Rimtef** [comment]
OK donc je comprends que c'est "juste" un problème de paramétrage.
par contre je ne vois pas où précisément accéder à celui-là : "activer input stream hls" ???
Pourrais tu détailler davantage le process ?

merci d'avance

**Comment by sancelot** [comment]
@Rimtef faire un click long sur l icone catchuptv / selectionner parametres / et l onglet "qualité et contenu". je pense qu'il est activé par defaut, donc essaie deja de bouger le curseur du player quand tu visualises tf1 avec l ecran noir.

**Comment by joaopa00** [comment]
>'est donc un pb de paramétrage
Ce qui montre que cela a tout à voir avec Inpustreamadaptive. Pour les chaînes TF1 et RMC qui utilsent des flux  découpés en chapitres, on est obligé de décaler la lecture des chapitres puisque IA ne peut que commencer que par le chapitre 1. IL faut donc rajouter une solution de contournement qui provoque dans certains cas la disparition de l'image.Et décaler le lieu de lecture l'a fait réapparraître. C'est ce qui expliqer dans le fil que j'aavis déjà indiqué. Ilfallait le lire....

**Comment by Rimtef** [comment]
@sancelot je vous remercie pour votre aide. Dans l'onglet "qualité et contenu", Utiliser Inputstream HLS est coché par défaut.
Par contre je ne vois pas de curseur à déplacer ?
et avec quoi le déplacer ? les flèches de la télécommande ?

**Comment by sancelot** [comment]
@Rimtef  visualiser ta page en noir de tf1, appuyer sur ok de la telecommande et bouger le curseur du player.

**Comment by Rimtef** [comment]
Je dois être un boulet car quand j'appuie sur OK de la télécommande cela met la diffusion sur pause :-(

**Comment by Rimtef** [comment]
Voilà les copies écran...si quelqu'un voit quelque chose à corriger, je suis preneur
![IMG_20230203_153720](https://user-images.githubusercontent.com/123748967/216631150-f3360df2-23b8-4ed9-bc43-264b652161b7.jpg)
![IMG_20230203_153640](https://user-images.githubusercontent.com/123748967/216631165-3f0131a8-cc85-47ed-aee3-256a92cb3634.jpg)

**Comment by khalistoo** [comment]
@Rimtef  il parle de la bare de lecture, il te suffit de revenir en arrière sur le stream pour que l'image se cale

![image](https://user-images.githubusercontent.com/1178270/216669948-49309379-2b72-4d97-8f76-579e680c312f.png)

**Comment by Rimtef** [comment]
OK, l'image se cale mais impossible de reprendre la lecture...
