### ISSUE TITLE
Replay Arte donne l'erreur « KeyError 'zones' »

### ISSUE THREAD

**Issue by OlivierV78** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1083]
### Describe the bug
Le replay d'Arte par International -> Arte(FR) produit l'erreur « KeyError 'zones' »

### To Reproduce
Steps to reproduce the behaviour:
Lancer le replay de la chaîne Arte(FR)

### Expected behaviour
A clear and concise description of what you expected to happen:
Obtenir le replay

### Actual behaviour
Tell us what happens instead:
Erreur "KeyError 'zones'"

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [X] Linux (Enigma2)
 - Operating system version/name: Openatv 7.3
 - Kodi version: 20.0 RC
 - Catch-up TV & More version: 0.2.38+martrix+1
 - Installation method: depuis Openatv 7.3

![20230128_173529](https://user-images.githubusercontent.com/22917586/215278441-cd987a00-cb66-42fe-aa78-4c44da5a7b1a.jpg)
![20230128_173519](https://user-images.githubusercontent.com/22917586/215278445-a2702fb2-62ee-4903-8610-55bc2886ec73.jpg)

**Comment by joaopa00** [comment]
Essaie la version béta-18.

**Comment by OlivierV78** [comment]
Merci pour la réponse.
J'ai installé la version beta mais maintenant je n'ai plus rien du tout avec l'erreur « RouteMissing » au démarrage.

**Comment by joaopa00** [comment]
Il faut un log complet avec le mode déboggage activé ainsi que les channels curl, ffmpeg, video.

**Comment by OlivierV78** [comment]
Je vais regarder comment faire ça.
Faut-il le faire sur la version stable ou la version beta ?

**Comment by joaopa00** [comment]
J'ai réussi à reproduire le problème. Devrait être fixé dans GIT.

**Comment by OlivierV78** [comment]
Merci pour le travail et le suivi.
Je vais donc attendre la prochaine version beta.

**Comment by OlivierV78** [comment]
Bonjour,

A toutes fins utiles voici le log (obtenu à l'instant sur une machine sous linux mais l'erreur est la même).

Cordialement.

[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/10701033/kodi.log)

**Comment by joaopa00** [comment]
Il est inutile d'ajouter de nouveau logs puisque le bug est déjà résolu. Soit tu installes la dernière béta. Soit tu attends qu'une version stable sorte (cela prendra quelques mois).

**Comment by OlivierV78** [comment]
J'ai installé hier la 0.2.39-beta19 à partir de la branche beta des dépôts officiels et j'ai toujours le bug (c'est à partir de cette version que j'ai envoyé le log).
Y a-t-il une autre beta plus à jour quelque part ?
Merci.

**Comment by joaopa00** [comment]
Le bug est revenu. Certainement que Arte fait des tests et modife son site très régulièrement. Je regarde ce weekend

**Comment by joaopa00** [comment]
Ca devrait être fixé dans GIT.

**Comment by OlivierV78** [comment]
Merci ça fonctionne.
