### ISSUE TITLE
Kodi 20 Linux , la version beta ne s'installe plus

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1084]
Tout est dans le titre.
Seule la version 0.2.38 Matrix1 demeure.
Comment installer la dernière beta?

**Comment by joaopa00** [comment]
Pas de problème pour moi. Vérifie bien que le channel beta est bien dsponible dans tes sources.

**Comment by enigma131** [comment]
Oui il l'est
![kodi1](https://user-images.githubusercontent.com/31815445/215696295-3a9ce867-e18e-4f62-aaaf-887b947d75be.png)

**Comment by joaopa00** [comment]
Je parlais  dans engrenages/système de fichiers

**Comment by enigma131** [comment]
Les 2 et les bonnes versions
![kodi3](https://user-images.githubusercontent.com/31815445/215830240-1d57b108-0948-4c64-ab18-979cc9fb4bfb.png)

**Comment by joaopa00** [comment]
Refais le processus à partir d'ici maintenat [inastallation](https://catch-up-tv-and-more.github.io/fr/installation/) Clique sur beta channel maintenant et reinstalle tranquillement.

**Comment by enigma131** [comment]
Oui cela rétabli la version beta. Pourquoi doit-on réinstaller sous Kodi 20 ?

**Comment by joaopa00** [comment]
CHez moi, tout s'est bien passé. Il y a du avoir une corruption des fichiers de configuration lors de ta mise à jour. En tous cas, ce n'est pas un problème de CUTVM. Je me permts donc de fermer ce sujet.

**Comment by enigma131** [comment]
Pour info, j'ai du faire la même chose sous Windows. Les résolutions sont passés en 1024 pix pour les chaines BFM
