### ISSUE TITLE
Add Live Tunisian Channel Elhiwarettounsi

### ISSUE THREAD

**Issue by ltai0001** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1085]
### Content description

* Name: Elhiwarettounsi is a Tunisian TV Channel
* Type [e.g. TV channel, Catch-up TV, Website, Radio]: TV Channel
* Website URL: https://www.elhiwarettounsi.com/vod/live
* Content language/country:
Language is Arabic - this is a TV Channel from Tunisia

### Content access

- [ X] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [ ] This content is geographically restricted

### More information

There is a Live section which I suspect is easy to add but there is also a large VOD content with different programs.
I dont believe this is Geo restricted

**Comment by joaopa00** [comment]
Au moins, le direct est implémentée dans  GIT. Je regarde pour le télévision de rattrapage.

**Comment by ltai0001** [comment]
@joaopa00 thank you very much for all your efforts - 
I really appreciate it...

**Comment by joaopa00** [comment]
Le direct étant implémenté. Je ferme. Ouvrir un autre sujet pour la télévision par rattrapage (j'y travaille!)

**Comment by ltai0001** [comment]
J'ai la version 19 beta installé mais je vois pas l'option du live dans le dossier Tunisie

**Comment by joaopa00** [comment]
Ce n'est présent que dans GIT. Tu peux le télécharger à partir du site [git](https://codeload.github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/zip/refs/heads/dev) Ce sera présent dans la béta 20 qui devrait sortir courant la semaine prochaine.
