### ISSUE TITLE
6play ne fonctionne pas sur Catch Up TV (Firestick Kodi)

### ISSUE THREAD

**Issue by thibautfromibiza** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1086]
Bonjour,

Je ne sais pas pour quelle raison alors que toutes les autres chaines fonctionnent, pour 6play cela me met comme message :

"Cette sélection a déclenchée une erreur inattendue, souhaitez-vous nous partager votre journal d'erreurs afin que nous puissions essayer de résoudre ce problème ?​"​

​Je ne sais pas si ça à un rapport mais j'utilise un VPN

Un idée de la d'où vient le problème ?
​
​
Merci

### Content description

* Name:
* Type [e.g. TV channel, Catch-up TV, Website, Radio]:
* Website URL:
* Content language/country:

### Content access

- [ ] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [ ] This content is geographically restricted

### More information

If you want to add more information, put it here:

**Comment by Fatichti** [comment]
Bonjour,

J'ai exactement le même problème bien que je n'utilise pas de VPN.
J'ai une erreur : "Index error"

**Comment by joaopa00** [comment]
POur le rapporteur initial. S'il y a u canevas complet de rapport de bug, c'est pour ête utilisé. IL manque toutes les inforamtions necéssaires pour commencer à aider. Un rapport de bug du style "ca ne marche pas, aidez-moi" est complétement vide de sens. ..

**Comment by darodi** [comment]
@thibautfromibiza @Fatichti 

https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore#bugs-et-am%C3%A9liorations--bugs-and-improvements
> ⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️
> ⚠️Veuillez tester la dernière version beta avant de soumettre un bug.⚠️

M6 group 
Doublon, mettre à jour vers la dernière version beta


- #1042
- https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1039
- #1044 
- #1046 
- #1049

**Comment by Dada2201** [comment]
Toujours le souci en beta

**Comment by thibautfromibiza** [comment]
Moi ca a corrigé le problème, mais maintenant j'ai MyTF1 replay qui me dit 404 error Bad request for url.... par contre TF1 direct fonctionne

**Comment by joaopa00** [comment]
@Dada Sans log, on ne peut pas t'aidr. Attache ici un log complet avec le mode déboggage activé ainsi que les channels ccurl et video.

**Comment by VDenis29** [comment]
Bonjour,
Je viens d'installer Kodi & Catch-up TV & More.
Après avoir complété les informations de mon compte M6Play, les chaînes du groupe M6 ont un comportement particuliers !!!
Le replay fonctionne, mais le direct demande les informations de connexion à M6Play + (abonnement d'environ 3 € par mois ...

**Comment by joaopa00** [comment]
Vdenis Ton problème n'a rien à voir. Ouvre un nouveau rapport en remplissant convenablement et totalement le canevas de rapport.
