### ISSUE TITLE
Réglage Résolution Vidéo Chaines TV sous Kodi Nexus

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1089]
Cela concerne toutes plateformes.

Inventaire par exemple pour BFM TV.
Android : résolution 1280*720
Windows 10 : 1024*576
Linux Mint 20.3 : 1024*576 (pour avoir Ubuntu / Mint à jour, il faut istaller le PPA)
Flatpak sous Redhat : 1280*720
(les 4 ont le dernier inputstream.adaptive, autres chaines probleme aussi)

Averc Kodi 19.5 et Linux Mint 20.3 sur une autre machine : 1920*1080
Comment régler / débuguer cela ?

**Comment by enigma131** [comment]
Il y a encore beaucoup de commits après la dernière version : https://github.com/xbmc/inputstream.adaptive/commits/Nexus  (pas de selection de résolution sous GUI pour l'instant)
Mais j'ai trouvé un truc qui marche via l'interface : (en dur pour toutes les chaînes, le réglage par défaut n'est pas bon) : 
![inputstream](https://user-images.githubusercontent.com/31815445/217076714-5bee2756-16b1-42f3-a8cc-1966eaf7b556.png)
Là je récupère 1920 * 1080 pix

Il faudrait sticker ce fil tant que le module est en développement.

**Comment by Arias800** [comment]
C'est pas un bug.
Inpustream Adaptive ne donne une résolution supérieur à celle de l'écran.
C'est un comportement logique.

**Comment by enigma131** [comment]
En décochant la case à cocher j'ai bien une résolution supérieure. Il est rare que la diffusion colle à celle de mon écran 1366 * 768 . Je ne comprends pas bien cet automatisme qui réglé par défaut donne 1024 * 768 pix sur cet ordi!

**Comment by Arias800** [comment]
En fenêtré, il doit prendre la taille de la fenêtre/(je suppose, j'ai jamais testé).
Le but c'est de ne pas chargé et prendre en compte les flux qui n'ont pas d'importance (une fenêtres n'affichera pas plus de pixel que sa résolution le permet).
C'est des économies de performance pour les appareils dont les capacités sont limité, mais aussi ça évite que Inpustream Adaptive les prennent en compte avec le nouveau mode qualite adaptative.

**Comment by joaopa00** [comment]
Pas un problème (si c'est un problème...) de Catchuptvandmore. Je ferme.

**Comment by enigma131** [comment]
@Arias800 Comme précisé au dessus, le coportement par défaut était différent sous 19.x.
L'avoir activé par défaut part sans doute d'un bonne intention, mais force est des constater que cela ne donne pas les résultats escomptés.
Cela selectionne bien les flux correspondants à la taille de la fenêtre, mais les flux des opérateurs sont soit upscalés d'une réslution encore inférieure soit mal downscalé d'un flux de résolution supérieure. Sur smartphone cela ne se voit pas d'accord, mais essayes par toi-même sur un écran PC (Windows ou Linux c'est pareil) en réduisant la fenêtre à environs 1024 pix et tu pourra comparer entre les 2 modes (ignore screen résolution - ou pas) en utilisant les flux cités plus haut.
