### ISSUE TITLE
ImportError: No module named tzlocal.windows_tz

### ISSUE THREAD

**Issue by simonesneault** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#109]
Bonjour,

Je viens d'installer le plugin mais je n'arrive pas à accéder à la section France de la partie TV en direct, je reçois l'erreur suivante :
ImportError: No module named tzlocal.windows_tz

Voici le log :
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/2660926/kodi.log)

J'ai essayé de réinstaller l'extension sans succès ...
Merci !

**Comment by wwark** [comment]
Bonjour,

Merci pour la remonté de ce problème. On va regarder.

Pour contourner le problème il suffit de désactiver le guide TV dans les options du plugin.
![screenshot from 2018-11-28 08-10-47](https://user-images.githubusercontent.com/469461/49702028-31268480-fbf4-11e8-9e54-a39a2435e6bc.png)

Merci,
Wwark.

**Comment by simonesneault** [comment]
Bonjour,

Super, merci pour la solution de contournement, effectivement ça marche ...
Bon courage pour le débogage
Simon

**Comment by wwark** [comment]
Bonjour @simonesneault,

Est-ce qu'il serait possible de remplacer ce fichier "C:\Users\Simon\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\tzlocal\win32.py" par celui en attachement de ce ticket (décompresser avant de le remplacer)?

Il faut réactiver ensuite le Guide TV et vérifier si ça marche.

D'avance merci pour votre test.
Wwark.

[win32.zip](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/2662005/win32.zip)

**Comment by simonesneault** [comment]
Bonjour,

Cela semble fonctionner !
Merci

**Comment by wwark** [comment]
Merci pour ton test.
On va l'appliquer à la branche "dev" - 0.2.1~beta05

Wwark
