### ISSUE TITLE
LCP Hs

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1090]
Lien Dailymotion hs visiblement, dommage c'est important en ce moment.
Le site web est OK
https://lcp.fr/

**Comment by darodi** [comment]
Le code me semble fonctionnel. 
Le lien dalymotion est trouvé mais j'ai une restriction géographique.

**Comment by joaopa00** [comment]
Devrait être fixé dans GIT. La télévision par rattrapage ne fonctionne pas, mais c'est un autre problème. Je ferme.

**Comment by enigma131** [comment]
Le patch fonctionne pour le live, merci :+1:
