### ISSUE TITLE
Erreur replay TF1

### ISSUE THREAD

**Issue by atrjil** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1091]
### Describe the bug
Il est impossible de lancer un replay TF1, l'erreur HTTPError 400 est systématique dès l'accès à l'un des dossiers (TF1, TMC, etc ...)

### To Reproduce
Steps to reproduce the behaviour:
1. Télévision de rattrapage --> France --> MYTF1  --> TF1
2. Constater l'erreur HTTPError

### Expected behaviour
Les dossiers devraient s'ouvrir comme habituellement

### Actual behaviour
Les dossiers des chaines MYTF1 ne s'ouvrent même pas

### Your environment
 - [x] Windows

 - Operating system version/name: Windows 10
 - Kodi version: 20.0.0
 - Catch-up TV & More version:  0.2.39-beta19
 - Installation method: via le dépôt beta

### Debug log
  DEBUG <general>: [Catch-up-TV-&-More.support] Dispatching to route: '/resources/lib/channels/fr/mytf1/list_categories/'
2023-02-10 21:29:27.250 T:13992   DEBUG <general>: [Catch-up-TV-&-More.support] Callback parameters: '{}'
2023-02-10 21:29:27.250 T:13992   DEBUG <general>: [Catch-up-TV-&-More.route] Listitem Cache: Miss
2023-02-10 21:29:27.271 T:13992   DEBUG <general>: [urllib3.connectionpool] Starting new HTTPS connection (1): www.tf1.fr:443
2023-02-10 21:29:27.343 T:14496   DEBUG <general>: ------ Window Init (DialogBusy.xml) ------
2023-02-10 21:29:27.364 T:13992   DEBUG <general>: [urllib3.connectionpool] https://www.tf1.fr:443 "GET /graphql/web?id=83ae0bfb82e29a71ad00e07122cca81e840cf88f5d4595f65ffb171bdb701543&variables=%7B%7D HTTP/1.1" 400 34
2023-02-10 21:29:27.391 T:13992   ERROR <general>: [Catch-up-TV-&-More.support] 400 Client Error: Bad Request for url: https://www.tf1.fr/graphql/web?id=83ae0bfb82e29a71ad00e07122cca81e840cf88f5d4595f65ffb171bdb701543&variables=%7B%7D
Traceback (most recent call last):
  File "\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 306, in run_callback
    redirect = parent_ins(route, arg_params, self.callback_params)
  File "\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\route.py", line 196, in __call__
    session_data = self._process_results(results)
  File "\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\route.py", line 210, in _process_results
    listitems = validate_listitems(results)
  File "\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\route.py", line 39, in validate_listitems
    raw_listitems = list(raw_listitems)
  File "\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\channels\fr\mytf1.py", line 93, in list_categories
    json_parser = urlquick.get(URL_API, params=params, headers=headers, max_age=-1).json()
  File "\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 493, in get
    return request('get', url, params=params, **kwargs)
  File "\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 487, in request
    return s.request(method=method, url=url, **kwargs)
  File "\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 442, in request
    self._raise_for_status(response, raise_for_status)
  File "\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 415, in _raise_for_status
    response.raise_for_status()
  File "\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.tf1.fr/graphql/web?id=83ae0bfb82e29a71ad00e07122cca81e840cf88f5d4595f65ffb171bdb701543&variables=%7B%7D

**Comment by joaopa00** [comment]
Je confirme le problème.

**Comment by raydenxxx** [comment]
même problème ici pour toutes les chaines du groupe TF1, même config sauf windows 11 à la place de windows 10.

**Comment by zertyuio1** [comment]
Même problème avec une android TV (mibox 4) et sous linux mint.
L'OS n'est pas en cause

**Comment by sousouille** [comment]
Je confirme le problème sur Kodi 20 sur NVidia Shield

**Comment by mivdnber** [comment]
Same problem here on a Sony Bravia Android TV.

I briefly checked out the MYTF1 site, and it looks like the `id` parameters in the GraphQL calls may have changed.

**Comment by coolben54** [comment]
Même problème avec librelect 10.0.4 et11 beta sur un Raspberry Pi4 avec une connexion Fibre de chez Free
J'imagine que cela vient d'un changement dans api de MyTF1.
Que peut on faire pour aider ?

**Comment by joaopa00** [comment]
>Que peut on faire pour aider ?

Envoyer des patches à travers des pull requests.

**Comment by alpliar** [comment]
Same here (Android TV, Linux, Windows).

I did check mytf1.py for answers, found the graphql api endpoint https://www.tf1.fr/graphql/web but schema introspection is disabled here.

**Comment by Clem2602** [comment]
Même problème sur Amazon Fire stick 4k...

**Comment by remzouille** [comment]
Voici un patch qui résout le problème

`--- resources/lib/channels/fr/mytf1.py.orig	2023-02-12 12:07:30.586245845 +0100
+++ resources/lib/channels/fr/mytf1.py	2023-02-12 12:17:09.700005437 +0100
@@ -82,7 +82,7 @@
     - ...
     """
     params = {
-        'id': '83ae0bfb82e29a71ad00e07122cca81e840cf88f5d4595f65ffb171bdb701543',
+        'id': '909c68c0',
         'variables': '{}'
     }
     headers = {
@@ -160,14 +160,14 @@
 
 def handle_videos(video_items):
     for video_datas in video_items:
-        video_title = video_datas['title']
+        video_title = video_datas['decoration']['label']
         try:
             video_image = video_datas['decoration']['images'][1]['sources'][0]['url']
         except Exception:
             video_image = ''
         video_plot = video_datas['decoration']['description']
-        video_duration = video_datas['publicPlayingInfos']['duration']
-        video_id = video_datas['streamId']
+        video_duration = video_datas['playingInfos']['duration']
+        video_id = video_datas['id']
 
         item = Listitem()
         item.label = video_title
@@ -191,7 +191,7 @@
     """
 
     params = {
-        'id': '400be301099f781dbee5bf2641b3bfba74f9fb6c13a54a22cae1fde916e42c7a',
+        'id': '483ce0f',
         'variables': '{"context":{"persona":"PERSONA_2","application":"WEB","device":"DESKTOP","os":"WINDOWS"},"filter":{"channel":"%s"},"offset":0,"limit":500}' % item_id
     }
     headers = {
@@ -228,7 +228,7 @@
 def list_videos(plugin, program_slug, video_type_value, offset, **kwargs):
     plugin.add_sort_methods(xbmcplugin.SORT_METHOD_UNSORTED)
     params = {
-        'id': '6708f510f2af7e75114ab3c4378142b2ce25cd636ff5a1ae11f47ce7ad9c4a91',
+        'id': 'a6f9cf0e',
         'variables': '{"programSlug":"%s","offset":%d,"limit":20,"sort":{"type":"DATE","order":"DESC"},"types":["%s"]}' % (program_slug, int(offset), video_type_value)
     }
     headers = {
`

**Comment by remzouille** [comment]
Voici un patch qui résout le problème
[patch_mytf1.txt](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/10716540/patch_mytf1.txt)

**Comment by joaopa00** [comment]
Merci pour le patch. Je te laisse faire une pull request pour que je le pousse dans GIT.
Cepedant, peux-tu vérifier si les identités de la fonction recherche n'ont pas été modfiées non plus.

**Comment by remzouille** [comment]
J'ai essayé de créer une PR mais je n'y arrive pas.
Les identités de la fonction recherche ont aussi été modfiées, voici la nouvelle version du patch.
[patch_mytf1_v2.txt](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/10716649/patch_mytf1_v2.txt)

**Comment by joaopa00** [comment]
Merci remzouille. J'ai poussé ton patch dans GIT. J'ai modifé le titre de ton patch. Jette un oeil pour voir comment nommer un patch pour CATVHUPVANDMORE pour la prochaine fois ;)

Merci encore pour le boulot!

**Comment by joaopa00** [comment]
Problème fixé dans GIT. Je ferme.

**Comment by Clem2602** [comment]
Merci pour votre boulot ! Il y a une manip à faire du côté de Kodi ou de l'extension ? Car le problème d'accès au Replay mytf1 est toujours présent sur ma fire stick

**Comment by joaopa00** [comment]
Soit tu télécharges et installe la version git, soit tu attends que la version sorte (dans environ une semaine) ou tu attends que la version stable sorte (dans quelques mois)

**Comment by Clem2602** [comment]
La version GIT n'a rien a voir avec la version du dépôt officiel mentionné dans le tuto d'installation de l'extension j'imagine ? Je ne suis pas pressé je vais attendre la version officielle beta, la MAJ se fera toute seule du coup ? Désolé pour les questions c'est tout nouveau pour moi 😬

**Comment by chocho13** [comment]
> Les identités de la fonction recherche ont aussi été modfiées, voici la nouvelle version du patch. J'ai lancé une PR. [patch_mytf1_v2.txt](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/10716649/patch_mytf1_v2.txt)

Merci, ça fonctionne impeccable :)

**Comment by Rimtef** [comment]
Comment installe t on le patch ? Merci

**Comment by coolben54** [comment]
Super merci a vous pour ce correctif !
Ca fonctionne chez moi

**Comment by atrjil** [comment]
Pour l'installation : 

- Sélectionner "Code"(en vert), puis "Download ZIP"
- Ensuite dans KODI --> Extensions --> Installer depuis un fichier ZIP
- Sélectionner le fichier téléchargé --> l'extension est mise à jour

Enjoy !

**Comment by Clem2602** [comment]
Pour l'installation comme expliqué ci dessus, possible de le faire directement via Kodi sur une fire stick ? Ou dois-je attendre la MAJ de la version bêta ?
Merci

**Comment by Cecilou93220** [comment]
Je ne comprends rien à vos explications. C'est pas très clair pour qqn qui n'est pas informaticien. Je n'ai pas de code vert. J'ai tout tapé correctement mais il ne s'est pas installé. Et je ne sais pas comment faire pour le désinstaller.
Catch UP m'indique toujours le même message d'erreur qd je veux accéder au Replay de TF1 404 Bad request 
Si quelqu'un peut m'aider svp, ce serait français et si possible avec des captures d'écran.
D'avance merci

**Comment by raydenxxx** [comment]
> Pour l'installation comme expliqué ci dessus, possible de le faire directement via Kodi sur une fire stick ? Ou dois-je attendre la MAJ de la version bêta ? Merci

Non il faut le faire manuellement tant qu'une nouvelle version du plugin n'est pas release au moins en beta.

> Je ne comprends rien à vos explications. C'est pas très clair pour qqn qui n'est pas informaticien. Je n'ai pas de code vert. J'ai tout tapé correctement mais il ne s'est pas installé. Et je ne sais pas comment faire pour le désinstaller. Catch UP m'indique toujours le même message d'erreur qd je veux accéder au Replay de TF1 404 Bad request Si quelqu'un peut m'aider svp, ce serait français et si possible avec des captures d'écran. D'avance merci

C'est ici que ça se passe pour le téléchargement du plugin comme décrit plus haut

![Capture d’écran 2023-02-13 190126](https://user-images.githubusercontent.com/122745590/218536988-3fee22b3-adcb-4eca-a481-ae2053d86667.jpg)

**Comment by Cecilou93220** [comment]
C'est beaucoup trop compliqué pour moi.
Je vais attendre que ça se fasse automatiquement par kody.
J'espère juste pas avoir fait une boulette avec ce que j'ai fait.


Cécile Daunat
***@***.***
0749913345

Le lun. 13 févr. 2023 à 19:04, raydenxxx ***@***.***> a
écrit :

**Comment by remzouille** [comment]
> Pour l'installation comme expliqué ci dessus, possible de le faire directement via Kodi sur une fire stick ? Ou dois-je attendre la MAJ de la version bêta ? Merci

Si tu disposes d'un partage Samba (par exemple en branchant une clé Usb sur une box), tu peux le faire directement dans Kodi, voici la procédure :

* télécharger la dernière version Git à l'adresse suivante
[https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/archive/refs/heads/dev.zip](url)

* optionnel : renommer le fichier dev.zip en plugin.video.catchuptvandmore_dev.zip

* dans Kodi, Extensions -> Installer d'un fichier Zip -> Navigateur Zeroconf,
sélectionner le partage Samba, naviguer jusqu'au fichier Zip et l'installer

**Comment by Clem2602** [comment]
La version bêta a déjà été mise à jour via Kodi. Pour ceux qui utilisent Kodi sur leur fire tv, la maj est automatique ! Vérifier, normalement le problème est réglé 🙂
Merci a tout le monde pour votre boulot et la rapidité d'intervention 👍
