### ISSUE TITLE
Catch-up tv & more / my tf1 error

### ISSUE THREAD

**Issue by Oruspo09** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1092]
Bonjour depuis hier sur catch up, télévision de rattrapage, m'y tf1 code erreur impossible de rentré dedans HTTPError ( 400 client error bad request for URL https//:www.tf1.fr..........
Merci

**Comment by Clostor** [comment]
Pareil pour moi, depuis le début de cette semaine.
Kodi 19.1 LibreElec sur Raspberry PI 2.

**Comment by recombe** [comment]
Duplicate of #1091
