### ISSUE TITLE
TF1 replay ne fonctionne plus

### ISSUE THREAD

**Issue by Regis5704** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1094]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
Impossible de lire quelque chose en replay sur TF1. En essayant de sélectionner TF1 dans "TV de rattrapage" (replay), il y'a directement une erreur "BAD REQUEST URL". Impossible d'ouvrir le dossier donc. Autre chaines aucun soucis. Essayé sur firestick et mibox.

### To Reproduce
1. Se rendre dans TV de rattrapage
2. Essayer de voir quelque chose en replay pour TF1

### Expected behaviour
Accès au replay

### Actual behaviour
Erreur Bad Request pour TF1 (....graphql...)

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: MiBox
 - Kodi version: Kodi 20
 - Catch-up TV & More version: Testé avec la dernière release, et la dernière beta
 - Installation method: from repo

Merci !

**Comment by kevlare** [comment]
Même chose ici avec une Nvidia Shield 2019 TV. Pour la version stable et la dernière beta.
Le message d'erreur est "HTTPError, 400 Client Error: Bad Request for url: http://mytf1........."

**Comment by joaopa00** [comment]
Doublon de #1091
