### ISSUE TITLE
Chaines France TV, Pleins de coupures

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1095]
Constaté sous Nexus , avec Windows ou Linux.
Le problème vient-il de la source ou encore de l'évolution de inputstream.adaptive ?
J'ai la fibre avec un débit > 10 fois la source.
Je n'ai plus Kodi 19.x, est-ce pareil chez vous ?

**Comment by mac1202** [comment]
Idem sous Android tv depuis la mise a jour vers Kodi 20 catch-up tv est devenu inutilisable. Et pas seulement sur les chaînes France TV j'ai le flux qui freeze sur la plupart des chaînes.

**Comment by enigma131** [comment]
Merci pour le retour

**Comment by 19PineApple83** [comment]
Même problème ci... Deux maisons que ça soit sous matrix Leia ou Nexus..connexion 1.5g fibre... Catch-up lag /freeze au bout de quelques minutes. Je sorsrepars et ça replante après quelques minutes . Des fois ça saccade ... Aucun problème sur d'autres addon

**Comment by enigma131** [comment]
Sous Matrix sans commune mesure. En ce moment, je n'ai d'ailleurs plus de son pour ces chaînes.

**Comment by joaopa00** [comment]
J'ai regardé le replay de "la fin du crime parfait" sur France 2 sur un appareil AndroidTV nexus .

Pas une coupure.
Il faudrait préciser un programme qui coupe souvent chez vous.

**Comment by mac1202** [comment]
Le problème concerne les chaînes en direct pas les replay.

**Comment by joaopa00** [comment]
Où était-ce préciser?

**Comment by 19PineApple83** [comment]
Pour ma part ce sont les replay peu importe la chaîne. Que ça soit la Rai ou TF1 même combat..ça coupe dans les deux maisons de la même façon...quelques minutes ok ensuite freeze..impossible de regarder un programme .

**Comment by joaopa00** [comment]
Pour ceux qui ont des problèmes autres que sur FranceTV, ouvrir un autre rappport de bug.

**Comment by enigma131** [comment]
Oui pardon pas précisé erreurs sur lives FTV. Pas de son même en ce moment

**Comment by Marc80460** [comment]
Bonjour, 
Pour ma part, après avoir complétement réinstallé Kodi (20 Nexus) et CUTV&M (0.2.39~beta20) car depuis quelques temps je n'ai plus les chaines dans la rubrique TV, je constate une absence de son pour les chaînes de FTV.
Et toujours pas de chaines dans TV et un guide TV totalement vierge.
J'ai pourtant les informations des programmes présentes au niveau de chaque chaine dans TV en direct.
Si quelqu'un a une piste de recherche à m'indiquer ?
En vous remerciant

**Comment by joaopa00** [comment]
Concernant les coupures sur  live, j'espère que vous ne parlez des coupures du site de FranceTv pendant les publicités...
Pour le problème de son, c'est un problème de Inpustream adative

**Comment by Marc80460** [comment]
Bonsoir Joaopa00,

Merci de votre réponse.
Non, je ne parle pas des coupures de FTV pendant les pubs.

Pour le son, j'ai regardé, Inputstream adaptive, Inputstream FFmpeg Direct et RTMP Input sont bien installés.
Faut-il modifier un paramètre  ?

En vous remerciant encore.

**Comment by joaopa00** [comment]
Pour le son, il faut que les gens de Inputstream adaptive règle le problème. Cela peut prendre quelques jours, quelques semaines semaines, quelques mois, quelques années suivant la difficulté du problème.

**Comment by Nitano** [comment]
Temporairement je vous conseille de remettre la version 20.3.2 du plugin inputstream adaptive.
Sous Android/Nexus, cela règle le problème. A tester sur les autres configs.

**Comment by enigma131** [comment]
J'ai trouvé ce post, sous Linux on lance kodi avec la variable : KODI_AE_SINK=ALSA kodi, cela force alsa, je retrouve le son, mais les coupures sont toujours là. 
Sous Linux, la version 20.3.2 ne règle pas les coupures.

**Comment by Viald** [comment]
> Temporairement je vous conseille de remettre la version 20.3.2 du plugin inputstream adaptive. Sous Android/Nexus, cela règle le problème. A tester sur les autres configs.

Comment faire pour downgrader en version 20.3.2 ? Merci

**Comment by joaopa00** [comment]
Pas de problème de son pour moi pour France Info (mais ce n'est pas le sujet de ce fil)
France 2 utilise maitenannt le même système de chapitres que TF1, ce qui n'est pas pris en charge par Inputstream Adaptive. Je n'ai pas regardé pour France 3, France 4 et France 5. France Info et les chaînes premières n'utilisent pas ce système.

**Comment by Nitano** [comment]
> > Temporairement je vous conseille de remettre la version 20.3.2 du plugin inputstream adaptive. Sous Android/Nexus, cela règle le problème. A tester sur les autres configs.
> 
> Comment faire pour downgrader en version 20.3.2 ? Merci

Ici, on peut trouver la dernière version du plugin:
https://kodi.tv/addons/nexus/inputstream.adaptive

Il existe un lien par OS. Il suffit d'adapter l'adresse pour télécharger la précédente et puis de l'installer.

Entretemps, je vois que la 20.3.4 est disponible; je n'ai pas encore eu le temps de vérifier si celle-ci corrige les bugs.
Cette nouvelle version s'installera automatiquement, si l'option 'auto-update' est activée.

**Comment by Marc80460** [comment]
Bonjour,
Merci Nitano, son revenu après application de la mise à jour.

Si quelqu'un a une idée au sujet de mon autre problème : 
Si je passe par Extension->Catch-Up TV->TV en direct->France->J'ai bien toutes les chaînes avec le contenu des programmes
Dans TV et dans Guide TV c'est le désert complet.
J'ai suivi la procédure à la lettre à plusieurs reprises.

En vous remerciant de vos aides

**Comment by enigma131** [comment]
Via TV j'ai les guides mais concernant les PVR que j'ai d'installés et ne concernent pas Catchup.
Par contre, c'est vrai qu'en appuyant sur la touche "i" ou en cliquant dans le bandeau sur 'i' on n'as pas l'incrust du programme alors qu'ils sont énumérés en parcourant les programmes via l'extension.

**Comment by Viald** [comment]
Merci pour les explications d'upgrade.
Concernant le 20.3.4 j'ai encore quelques freezes (son + image) sur TF1. Et quasiment à chaque fois sur TF1 et France 2 dès que les pubs démarrent.
Aucune chaine n'apparait dans Kodi après avoir configuré IPTV

**Comment by enigma131** [comment]
Testé ce matin sur France 2, Nexus + Linux Mint 20.3 , durée  1H.
Kodi  planté 2 fois -> sudo kill - 9 kodi.bin
Toujours le figeage écran lors des coupures de pubs. (disconinuité dan le flux sans doute mais pourquoi cela plante la lecture qui suit ?)

**Comment by Ruitos** [comment]
Pour ma part TF1 coupe jusqu'à 10 fois par heure donc impossible a regarder ,
Sous android Kodi nexus avec
- Catch-up TV 0.2.39-beta20
- Inputstream Adaptative peak3d 20.3.4 
ce que je ne comprend pas c'est que c'est juste TF1 qui est comme ça les autres chaines du groupe ne posent pas de problème.

**Comment by francois-pasquier** [comment]
Est ce 

> J'ai regardé le replay de "la fin du crime parfait" sur France 2 sur un appareil AndroidTV nexus avec de connexion de 6Mb!!
> 
> Pas une coupure. Il faudrait préciser un programme qui coupe souvent chez vous.

Dans mon cas c’est n’importe quel programme sur tf1 qui se met en buffering. J’ai créé une issue mais pas de réponse pour le moment

**Comment by joaopa00** [comment]
Avec la dernière mise à jour de Inputstream Adaptive, le problème des couputes devrait être plus ou moins fixé

**Comment by enigma131** [comment]
Mis à jour sur Linux. Je testerai un peu ce WE.

**Comment by enigma131** [comment]
A part des gels provoqués par le lancement de la Pub sur France2, je n'ai plus de coupures à proprement parler.
Ftv provoque aussi de temps en temps le gel de Kodi 20.1, sans rapport avec la Pub. Ce n'est pas constaté sur les autres chaînes. Je pense que leur flux n'est vraiment pas propre.
A part de pouvoir debugger plus, je pense qu'on peut fermer ce tiquet.

**Comment by joaopa00** [comment]
Je ferme alors. Merci pour le retour.
