### ISSUE TITLE
404 error on MyTF1 replay

### ISSUE THREAD

**Issue by thedude4ever** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1097]
404 error MyTF1 replay channels

Steps to reproduce the behaviour:
1. Go to Replay section 
2. select MyTF1
3. Select TF1 or TMC

CUTV version 0.2.38

**Comment by joaopa00** [comment]
Doublon de #1091

La prochaine fis, lis le message au dessus du canevas de rapport de bug et mieux lis le wiki. Avant de rapporter un bug, toujours tester la dernière béta pour voir si le bug n'est pas déjà fixé. De plus, s'il y a un canevas de rapport de bug c'est pour être utilisé et pas que chacun rapporte à sa sauce son bug.
