### ISSUE TITLE
Erreur 400 quand j’essaie d’afficher la liste des vidéos TF1/TMC

### ISSUE THREAD

**Issue by gordielachance** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1099]
### Describe the bug
Depuis quelques jours, je n’arrive plus à lister les vidéos de TF1 et TMC.  J’ai une notice avec une erreur 400.  [Voici le debug](https://paste.kodi.tv/imaficezid).

### To Reproduce
Steps to reproduce the behaviour:
1. Chaines > MYTF1 > TF1
2. Pas d’accès au contenu + notice d’erreur.

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: LibreELEC 10.0.4
 - Kodi version: 19.5.0
 - Catch-up TV & More version: 0.2.38-matrix1
 - Installation method:

### Additional context
Je suis en Belgique.  Un rapport avec du géoblocking?

### Debug log
https://paste.kodi.tv/imaficezid

**Comment by joaopa00** [comment]
Déja résolu dans la dernière béta. Doublon de #1091
