### ISSUE TITLE
[Enhancement] Add Live "Direct" Streaming Channels

### ISSUE THREAD

**Issue by Mike-KL** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#11]
Any possibilty to add Live channels as well as current Catch-up to this Kodi approved addon.

From https://www.france.tv/ (Which currently does not require User login information)

https://www.france.tv/france-2/direct.html
https://www.france.tv/france-3/direct.html
https://www.france.tv/france-4/direct.html
https://www.france.tv/france-5/direct.html
https://www.france.tv/france-o/direct.html
https://www.france.tv/franceinfo/direct.html

And from https://www.tf1.fr/ (Which requires User login information)

https://www.tf1.fr/tf1/direct
https://www.tf1.fr/tmc/direct
https://www.tf1.fr/nt1/direct
https://www.tf1.fr/hd1/direct
https://www.tf1.fr/lci/direct

Appreciate work required to scrape streaming details from above webpages etc

**Comment by SylvainCecchetto** [comment]
Hi Mike,

It's in my plan to add a "Live" category inside each channel. But unfortunately I would have much time to work on my plugin...

Maybe when my Ph.D will be done I will have more time ;-)

But if you or any other people want to work on it I will be delighted to have some pull requests with lots of improvements for Catch-Up TV & More!

Thanks for your message!

**Comment by wwark** [comment]
For information, Direct FranceTV requires Login information.
Thanks

**Comment by wwark** [comment]
Hello @Mike-KL ,
In the dev branch, there is some improvement for Live TV.
Could you please try it and give some feedback ?

Thanks,

**Comment by wwark** [comment]
Pour Groupe M6, les flux Live TV sont protégés par #EXT-X-FAXS-CM
https://helpx.adobe.com/adobe-media-server/dev/configuring-content-protection-hls.html

**Comment by Mike-KL** [comment]
@wwark 

Performed quick test of dev branch on my rpi2 (libreelec) and played Live Streams of France 2 & 3 everything worked as expected and looking good from very short test. Will test some more in coming weeks and provide further feedback.  Thanks for adding feature

**Comment by wwark** [comment]
Thanks @Mike-KL 

Pour NRJ 12 et Cherie 25, nous avons besoin d'un token généré avec le login/mot de passe du site.

**Comment by wwark** [comment]
- [x] Live TV France TV (France 2, France 3, France 4, France 5, France Ô, France Info)
- [x] Live TV Groupe TF1 (TF1, LCI, TMC, HD1, NT1)
- [x] Live TV LCP Assemblée Nationale
- [x] Live TV Gulli
- [x] Live TV Arte
- [x] Live TV Numéro 23
- [ ] Live TV NRJ12/Cherie25 (Pré-requis ajouter le login/mot de passe du site NRJ)
- [ ] Live TV Groupe M6 (les flux Live TV sont protégés par #EXT-X-FAXS-CM)
- [ ] Live TV Groupe BFMTV (TODO)
- [ ] Live TV L'équipe TV (TODO)
- [ ] Live TV Itélé (TODO)
- [ ] Live TV C8/CStar (TODO)
- [ ] Live TV Canal+ (Login MyCanal avec protection DRM)

**Comment by Mike-KL** [comment]
@wwark & @SylvainCecchetto 

With the introduced Livestreams for France 2, 3, 4, 5 etc (Working well at the moment thank you very much) from a usage perspective it would be great if Live and/or Catch-Up were top key options. i.e.

FR -> Live
FR -> Catch-Up

And then when user selects FR-> Live (Streams) option they are provided with GUI selectable results for all available FR live channels, similar to method provided by TVPlayer addon http://kodi-addons.club/addon/plugin.video.tvplayer/0.2.8 as follows

![screenshot004](https://user-images.githubusercontent.com/16574667/28743700-c3bfeb24-7450-11e7-8e32-79bea6534cf8.png)

I also believe that it's important to retain channel identification i.e. "France 2" as key stream information, with current playing info as extremely useful additional information. (This would allow Live  streams provided by the addon to be utilsed within other addons such as TVGF https://forum.kodi.tv/showthread.php?tid=282157 where advanced Kodi users choose to build there own EPG and assign live streams to channels from a number of underlying addons)

Hope above usage thoughts and comments are helpful.

**Comment by SylvainCecchetto** [comment]
@Mike-KL 

Hi Mike-EL,

Thanks for your idea. What do think about this presentation:

* Live TV
    * Chaines Francaises
        * TF1
        * France 2
        * ...
    * Chaines Belges
    * ...

* Replay
    * Chaines Francaises
        * TF1
        * France 2
        * ...
    * Chaines Belges
    * ...

* Sites Web
    * Allociné
    * Tete à claque
    * ...

We will see in a second time for EPG ;-)

**Comment by Mike-KL** [comment]
Looks good, will be quicker to access into Live or Replay across various available channels..

**Comment by SylvainCecchetto** [comment]
Hi Mike-KL,
It's been a while but we are finally working on the new structure of the add-on. It's currently under development but if you want you can try this on the new_disposition2 branch.

For now only France 2 and France 3 works for Live-TV and the French labels are broken (only english strings.po works so you have to set Kodi in English language).

**Comment by Mike-KL** [comment]
@SylvainCecchetto OK will do, what is best way to include test version on a current build that has for example 0.1.10~beta003 installed? (i.e. could I run both or do i need to remove beta and repo whilst testing this version)  I notice that new_disposition2 branch version is currenly identified as 0.1.9

**Comment by SylvainCecchetto** [comment]
The new_disposition2 branch is based on 0.1.9 master version.
You can install this version on your Kodi with the "Install with ZIP" option in Kodi. The only thing you have to do is download the new_dispotion2 branch in zip format directly from GitHub.
But I think that Kodi will tell you that Catch-Up TV and More is already installed on your system.
So I think that you have two options:
1. Remove the current version of Catch up TV and install the new one by ZIP
2. Fork/Download the new_disposition2 version and modify the id in addon.xml file with for example plugin.video.catchuptvandmore2.

**Comment by SylvainCecchetto** [comment]
Hi,
Now, the new_disposition2 branch doesn't exist anymore, all the new stuff lives in dev branch since 0.1.10~beta005 version.
You can now test this version just by update the add-on from the Beta Catch Up TV & more repo (if you still don't use the "official" Catch-Up TV & More repo you can read instructions in the French forum thread of the add-on to find the correct URL).
Hope this new version can easily be upgraded from 0.1.9 version because there is a lot of changes in settings.xml ...

**Comment by Mike-KL** [comment]
@SylvainCecchetto been trying latest couple of beta release with no live playback success
(Note: Using latest nightly version of Leia build for rpi2)

With beta 006 was trying to access and then play Live France 2, Here is kodi.log https://pastebin.com/qZwtghew

https://i.imgur.com/B6wo6W6.jpg

Generally both stable and beta versions of addon are very slow navigating into and out off available options via a CEC remote.  (Krypton & Leia on rpi3 & 2)

In last couple of weeks live playback of france channels has generally stopped working for me on the rpi's, where i wondered if some internet environmental changes were causing my problem?  (Workiing ok on computer via browser)

**Comment by SylvainCecchetto** [comment]
Hi Mike-KL,
Since the 0.1.10~beta0014 (will be available on repo during the night) we use XMLTV guide to build the French live TV menu. Maybe it will work for you now?

Thank you for your feedback

**Comment by wwark** [comment]
Close ticket because the guide TV is present now and there is some works in progress for using PVR IPTV Simple followed in another ticket.
