### ISSUE TITLE
catchup et  replay

### ISSUE THREAD

**Issue by Lavabo68** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#110]
Bonjour je suis Canadien (un vrai pas un expat) et pour écouter Affaire Conclue (Émission que je trouve très divertissante) j'ai décider d'essayer un VPN .

C'est situer dans : Replay-France-F2-vie quotidienne-

Quand je vais avec le browser ca marche tres bien, mais avec Kodi et  catchupTV ca fonctionne 1 fois sur 10.

Jai penser que c'était les pub au début qui dure presque 1 minute, j’ai donc allongé le timeout (jessaye avec openvpn windows ) mais ca ne fonctionne pas vraiment mieux
je n'ai pas essayer d'autres sections voir si ca faisait pareil.

Est ce que c'est un problème  qui peut se régler dans Catchup-TV ?  Ou c'est plutot le VPN qui est en problème ?   

Précision Kodi 17.6 en windows 7 x64

**Comment by wwark** [comment]
Bonjour Lavabo68,

L'utilisation de VPN a un impact sur la vitesse de la connexion internet.
Le plugin essaye de récupérer la meilleur qualité et demande une bonne connexion internet et l'utilisation de VPN.

Le browser permet mieux de prendre en compte la vitesse de connexion que Kodi. Le plugin sert juste à recupérer le flux vidéo et de le proposer à Kodi pour le lire.

Au niveau des logs, est-ce que vous avez des timeout?
Au niveau de la configuration du timeout, Kodi propose cette configuration https://kodi.wiki/view/Advancedsettings.xml#network

Un autre possibilité est surement de limiter la qualité qui est possible en choisissant le niveau de qualité dans la configuration du plugin (Mode DIALOG)
![screenshot from 2018-12-10 21-54-18](https://user-images.githubusercontent.com/469461/49761284-e590db00-fcc6-11e8-8993-dc1ad24c802b.png)

Pour les replays de France Télévision, nous avons les qualitées SD et HD proposées avec le mode DIALOG choisie.
![screenshot from 2018-12-10 22-00-04](https://user-images.githubusercontent.com/469461/49761319-0ce7a800-fcc7-11e8-92e4-0b45373ebcaa.png)

Est-ce qu'il serait possible de tester avec le qualité SD pour voir si ça permet de regler ton cas ?

D'avance merci,
Wwark

**Comment by wwark** [comment]
Un autre test aussi possible serait de tester de lire le journal de 20h de France 2 qui n'est pas géolocalisé sans utiliser le VPN. Ce point permettra de vérifier si on a aussi le problème dans ce cas.

**Comment by Lavabo68** [comment]
Bonjour
Je vais fournir le log plus tard, mais juste ajouter:
-je regarde régulièrement le Journal 20h dans la même section et ça fonctionne très bien (hier encore)
-J'ai essayer avec le paramètre DIALOG en SD et ça na rien changer,

--> reste le timeout a tester comme suggéré , j’ai mis comme paramètre <curlclienttimeout>10</curlclienttimeout>
-->log a venir

J'aimerais ajouter que j'ai 2 kodi, un chez moi et un chez ma copine, donc pas le même fournisseur internet et portable différent (en win7 x64 cependant) et que  la même situation se répète aux 2 endroits.

**Comment by wwark** [comment]
Merci pour ces informations.
Il faudrait aussi tester sur Kodi 18 pour voir si ça permet d'aider à limiter ce cas d'erreur.

Le test sans le VPN montre que le problème est l'utilisation avec le VPN, je pense qu'on aura des erreurs de timeout dans les logs.
Le seul moyen sera donc d'ajouter l'option curlclienttimeout et l'augmenter jusqu'à que Kodi puisse lire la vidéo dans cette configuration.

Merci,
Wwark

**Comment by Lavabo68** [comment]
tester avec Kodi 18 sur win10 --> fonctionne parfaitement
tester avec kodi 18 sur Win 7 x64 --> ne fonctionne pas mieux

**Comment by Lavabo68** [comment]
**Log erreur dans kodi 18 os 7:**
	07:56:01.507 T:1068  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.catchuptvandmore/?action=replay_entry&module_path=%5B%27root%27%2C+%27channels%27%2C+%27fr%27%2C+%27pluzz%27%5D&next=play_r&id_diffusion=194820543&module_name=france2
	07:56:01.507 T:1068   ERROR: CCurlFile::Stat - Failed: Unsupported protocol(1) for plugin://plugin.video.catchuptvandmore/?action=replay_entry&module_path=%5B%27root%27%2C+%27channels%27%2C+%27fr%27%2C+%27pluzz%27%5D&next=play_r&id_diffusion=194820543&module_name=france2
	07:56:01.508 T:1780  NOTICE: Creating InputStream
	07:56:02.382 T:1780  NOTICE: Creating Demuxer
	07:56:32.436 T:1780   ERROR: CVideoPlayer::OpenDemuxStream - Error creating demuxer
	07:56:32.436 T:1780  NOTICE: CVideoPlayer::OnExit()
	07:56:32.465 T:1068  NOTICE: CVideoPlayer::CloseFile()
	07:56:32.465 T:1068  NOTICE: VideoPlayer: waiting for threads to exit
	07:56:32.465 T:1068  NOTICE: VideoPlayer: finished waiting

**Comment by wwark** [comment]
C'est une bonne nouvelle si on a un environnement qui fonctionne correctement.
Il faudrait ouvrir un ticket auprès de Kodi pour indiquer l'environnement qui ne fonctionnent pas.

Pour information il ne mettront pas à jour Kodi 17.6 et surement que Windows 7 n'est plus supporté à voir avec eux.

**Comment by Lavabo68** [comment]
Je crois qu'on peut fermer ce ticket et plutôt vivre avec le nouvel environnement Kodi 18 et Windows 10 !!

**Comment by wwark** [comment]
Ok merci !
Le ticket est fermé.
