### ISSUE TITLE
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug .         Make sure you are using the latest version; type  youtube-dl -U  to update. 

### ISSUE THREAD

**Issue by ltai0001** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1100]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
Started getting this error while trying to access Aljazeera Live stream. It used to work perfectly until a few days ago
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . 
       Make sure you are using the latest version; type  youtube-dl -U  to update. 

### To Reproduce
Steps to reproduce the behaviour:
1. Click on Aljazeera Live
2.Click on English option
3.
4.

### Expected behaviour
Live video should launch with no errors. It used to work a few days ago

### Actual behaviour
Get the following error
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . 
       Make sure you are using the latest version; type  youtube-dl -U  to update. 

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 20.0
 - Catch-up TV & More version:  0.2.39~beta20
 - Installation method: Windows

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment]
Thats's a problem from yt-dl (see [issue](https://github.com/ytdl-org/youtube-dl/issues/31530)) It is already fixed in the github of yt-dl. ONe just needs to ait the fix is backported  in Kodi

Not a Catchuptvandmore problem. I close this report. Thanks for the report anyway.
