### ISSUE TITLE
Live et replay C8 ne fonctionnent pas correctement ou pas du tout

### ISSUE THREAD

**Issue by staffly** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1102]
Gros souci de visionnage de C8 :
1) Le  live
 Lorsqu'on lance le live on a le choix entre Mycanal et C8. 
- Mycanal : on a beau attendre il ne se passe rien 
- Dailymotion : c'est hyper saccadé dès le début, avec un décalage systématique du son et de l'image.
2) Le replay
Télévision de rattrapage/France/Mycanal/C8 renvoie une erreur "Index Error (list index out of range)"

**Comment by enigma131** [comment]
Tu ne précise pas ta configration. Sous Dailymtion impecable ici, Nexus + Linux + Pc.
Avec le choix Canal, fonctionne pas non plus, dans la configuration du plugin on avait le choix avant ? Autant supprimer le choix dans le menu si Canal ne marche plus ou mettre Dailymotion en premier.

**Comment by joaopa00** [comment]
Le problème du lien Dailymotion semble venir du fait que ytdl choisit toujourl le lien en 1920p même si on choisit le lien SD

>2023-02-28 04:46:36.312 T:6479    debug <general>: ffmpeg[0x560590cecde0]: [hls] Opening 'https://stream-01.sv4.dailymotion.com/sec(3uHXKsK7_-J9YIYIiNPgOBILLCqEJq3ajnCwC9G6r_3MoPtWt2evqRNtgntYoxXd)/p/dm/3/x5gv5rr/d/live-4.m3u8' for reading

 mpv 'https://stream-01.sv4.dailymotion.com/sec(3uHXKsK7_-J9YIYIiNPgOBILLCqEJq3ajnCwC9G6r_3MoPtWt2evqRNtgntYoxXd)/p/dm/3/x5gv5rr/d/live-4.m3u8' 
 (+) Video --vid=1 (h264 1920x1080 50.000fps)
 (+) Audio --aid=1 (aac 2ch 44100Hz)
Cannot load libcuda.so.1


>Autant supprimer le choix dans le menu si Canal ne marche plus ou mettre Dailymotion en premier.
Il faut mieux que l'accès Mycanal soit corrigé. Ce ne sera pas moi car je n'ai pas accès à Mycanal.

**Comment by Arias800** [comment]
Je vais regarder ce week-end pour Mycanal.
Il y a surement encore un détail à la con qui bloque.

**Comment by Arias800** [comment]
Je viens d'ouvrir un pull requests pour Mycanal : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/1109

**Comment by Hir0-84** [comment]
Hi, would be possible to select mycanal or dailymotion in the settings of the addon, to not been asked while zapping within the PVR.simple? The reason for this request is:
- if from TV I click directly on C8 a pop-up windows is shown giving the choice. I select the source and the streaming starts without problems.
- if i am already streaming another channel and switch to the next one that is C8, i am asked to choose but as soon as I select one source Kodi crashes. Nothing in the debug log.

I am using Kodi 20.0 and most likely the bug is iptv.simple client

**Comment by joaopa00** [comment]
If it is a problem from iptv client, it is better to report an issue to iptv client.

**Comment by joaopa00** [comment]
Mainly fixed. So I close it. Difficulties with dailymotion links appear too with any ffmpeg player.
