### ISSUE TITLE
LCI (France) Replay doesn't work anymore

### ISSUE THREAD

**Issue by nmaster2042** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1108]
Can't Access LCI replay (France

A clear and concise description of what the bug is:

When I want to enter in LCI replay , I get an error "Unable to find requested section with tag of 'div' and attributes of {'id': 'ProgramList__Container-1"

### To Reproduce
Steps to reproduce the behaviour:
1. start kodi
2. go to extensions
3. start Catch Up TV & More
4. Select Replays
5. Select France
6. Select LCI

### Expected behaviour
I should get the list of replays avaliable from LCI

### Actual behaviour
I get the error message, and not he list of avaliable replays.

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [X ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: Kubuntu 22.04.2 LTS
 - Kodi version: 20
 - Catch-up TV & More version: 0.2.39Beta20
 - Installation method: from Catch Up TV & More Beta repository

See log file
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/10841598/kodi.log)

**Comment by joaopa00** [comment]
Merci pour ce rapport détaillé (dans les règles de l'art...) Je confirme le problème. Pas de solution en vue pour l'instant de mon côté.

**Comment by joaopa00** [comment]
Fixed in git.
