### ISSUE TITLE
Next stable release?

### ISSUE THREAD

**Issue by connesc** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1113]
The master branch is now far behind the dev branch.
Is there any plan to release a stable version soon?
BTW, thanks for your hard work on this fantastic plugin!

**Comment by connesc** [comment]
Alright, thanks for the detailed status! Hope the Kodi team will unlock the situation soon... 🤞

**Comment by connesc** [comment]
Side note: making the effort to support old versions is very (very) nice

**Comment by joaopa00** [comment]
HUrray! Krypton version 0.2.38 is merged in xbmc/repo. It remains one big problem with my5 for krypton and leia. When this problem is fixed, I will release the version 0.2.39.

**Comment by connesc** [comment]
Great, well done! :muscle: 
And thanks for the follow up! :+1:
