### ISSUE TITLE
Catchup not working on BVN

### ISSUE THREAD

**Issue by nzljohn** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1116]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
A clear and concise description of what the bug is:
I have done a factory reset and reloaded Kodi 20 and 2.39 beta 18 catchup
The catchup function will not work on BVN international

### To Reproduce
Steps to reproduce the behaviour:
1.click on catch-up TV
2.click international
3.click BVN
4.click the day of the week and then click any TV program

### Expected behaviour
A clear and concise description of what you expected to happen:
The TV program should play

### Actual behaviour
Tell us what happens instead: I get HTTPError 405

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [- ] Android
 

 - Operating system version/name:
 - Kodi version: 20
 - Catch-up TV & More version: 2.39 beta 18
 - Installation method: zip file

### Additional context
Add any other context about the problem here:

### Debug log
https://paste.kodi.tv/ifeyureban

**Comment by joaopa00** [comment]
Give a try to the latest beta (currently it is beta-20)

**Comment by nzljohn** [comment]
I did a fresh install of Kodi20. Still no go

**Comment by joaopa00** [comment]
GIve the log with catchuptvandmore beta 20 installed.

**Comment by joaopa00** [comment]
and do you have a Dutch  ip addrees?

**Comment by nzljohn** [comment]
No.
I also have 3 other people in my town in New Zealand that had the same problem at the same time.

**Comment by joaopa00** [comment]
You need an Dutch IP.

**Comment by nzljohn** [comment]
On my windows 10 computer I can use Firefox to go to https://www.bvn.tv/ to watch the archived programs.
Works fine.
On Kodi it will not work on my android box or kodi on my windows 10 computer.
I don't think it is an IP problem.

**Comment by joaopa00** [comment]
Can you give the link of a program that works for you in firefox but not in Kodi?

**Comment by nzljohn** [comment]
Go to catchup, international, BVN,Dinsdag 7 maart, 9:20-Ik vertrek
which is the same as https://www.bvn.tv/programma/ik-vertrek/AT_300003458/
You can do this with any of them. On Firefox win 10 no problem. On Kodi no go.
I am not using a VPN

**Comment by joaopa00** [comment]
OK! I see the problèm. In fact, on the site, the list of programs is empty ([problem](https://www.bvn.tv/uitzendinggemist/) )

**Comment by nzljohn** [comment]
Can you fix this?

**Comment by joaopa00** [comment]
Currently, no. But patches are always welcome

**Comment by joaopa00** [comment]
Should be fixed in GIT.
