### ISSUE TITLE
[Fr -LCI] : en retard de 4h / behind by 4h

### ISSUE THREAD

**Issue by khalistoo** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1118]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
LCI a un retard de 4h , pas de soucis ni avec TF1 ni TMC
LCI behind by 4h , works fine with TF1 & TMC
### Your environment
 - [x] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:  Ubuntu 22.04  & Android 9 (Mibox 4) , Kodi Nexus 
 - Catch-up TV & More version: 0.2.39 beta 17 / 18 / 19 / 20

![image](https://user-images.githubusercontent.com/1178270/223431429-1637c9c1-7275-469e-adb0-171b690e5784.png)

**Comment by joaopa00** [comment]
C'est le même problème que pour TF1. C'est un problème d'inpustream adaptive (IA). Il y  a des PR en attente sur IA. Par conséquent, je ne fait pas rajouter de méthode de contournement pour pallier à ce bug. Il suffit d'attendre quelques jours que les PR soient mergées dans IA.

**Comment by enigma131** [comment]
Recu une nouvelle version de inputstream à l'instant, ne règle pas le problème. A mon avis c'est la selection du flux qui n'est pas bonne, elle pointe sur du +4.

**Comment by joaopa00** [comment]
Les patches n'ont pas encore été merged....

**Comment by enigma131** [comment]
Ma version et toi ? :
kodi-inputstream-adaptive:
  Installé : 6:20.3.5-1~focal
  Candidat : 6:20.3.5-1~focal
 Table de version :
 *** 6:20.3.5-1~focal 500
        500 http://ppa.launchpad.net/team-xbmc/ppa/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by Nitano** [comment]
Effectivement la version 20.3.5 d' "input stream adaptive" ne règle pas le problème du retard sur LCI.
D'autre part, le flux finit toujours par se bloquer à un moment ce qui fait qu'il faut stopper kodi et le relancer (Android + Nexus).
C'est pour ça que je reste toujours avec la version 20.3.2 qui n'a pas ce problème.

**Comment by kmorinCL** [comment]
J'ai le même problème sur TFX, c'est la même cause ?

**Comment by joaopa00** [comment]
En effet.

**Comment by enigma131** [comment]
France 2 a rejoint la liste des chaînes décallées ...

**Comment by joaopa00** [comment]
J'ai poussé la méthode de contournement du bug de Inpustream dans la nouvelle béta pour LCI et TFX. Par contre pour France TV, je ne l'ai pas fait puisque le délai ne se produit pas tout le temps. En pleine nuit, il semble ne pas y en avoir.
