### ISSUE TITLE
Rmc decouverte replay : RUN Time error

### ISSUE THREAD

**Issue by guillaume68800** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#112]
Depuis quelques jours, impossible de voir les replay rmcdecouverte. J’ai aucun programme proposé et runtimerror d’affiché.

**Comment by wwark** [comment]
hello @guillaume68800,

Le site de la chaine de RMCDecouverte a changé on doit adapter le code.
Merci pour l'alerte.

Wwark

**Comment by wwark** [comment]
Je viens de corriger sur la branche de dev : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/tree/dev
Le correctif sera présent sur la version 0.2.1~beta06

Merci,
Wwark

**Comment by fg2000fr** [comment]
Bonjour
J ai rencontrė le même probleme aussi.
 J ai donc fait la mise a jour vers la version 0.2.1 et depuis je n ai plus aucun replay pour aucune chaine: le dossier catchup tv est vide...

 J utilise kodi v 17.6 sous android.
Doit on installer un plugin pour gerer le framework codequick??

Merci d avance
