### ISSUE TITLE
Numéro de la dernière version Catch Up

### ISSUE THREAD

**Issue by thibautfromibiza** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1122]
Bonjour, comment savoir le numéro de la dernière version de l'extension Catch Up TV ?
J'ai la version 0.2.39, est ce que c'est la dernière ?

Merci

### Content description

* Name: Thibaut
* Catch-up TV
* Website URL:
* Content language/country:  FR

### Content access

- [ ] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [ ] This content is geographically restricted

### More information

If you want to add more information, put it here:

**Comment by joaopa00** [comment]
Il suffit de fouiller dans le répertoire https://github.com/Catch-up-TV-and-More/repository.catchuptvandmore/tree/master/zips
