### ISSUE TITLE
Fréquence des releases ? La dernière datant du  28 aout 2022 - v0.2.38

### ISSUE THREAD

**Issue by MalibuKoKo** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1124]
Je vois que la dernière release date de plus de  7 mois, il s'agit de la version v0.2.38.
Est-ce qu'il est possible de faire des releases plus souvent, en releasant des petites versions régulièrement ?

Je possède une TV Philips avec Android TV, j'ai installé la seule version de Kodi disponible sur Google Play, à savoir la version 20.1.
Dans cette version Android TV il n'y a pas de menu "Gestionnaire de fichier", il est donc impossible d'appliquer la [procédure d'installation](https://catch-up-tv-and-more.github.io/installation/) qui d'écrit comment aller dans le menu pour ajouter une source comme on peut les voir sur les images suivantes :
![files_manager_fr](https://user-images.githubusercontent.com/13408634/226101447-c30525d7-3c51-45b2-bbe5-55a2e630ac16.jpeg)
![3_fr](https://user-images.githubusercontent.com/13408634/226101458-2a7163ae-7b04-422a-b991-2af6c95d6193.jpeg)

Du coup je ne peux bénéficier que de la dernière version v0.2.38 du repo stable accessible depuis la source "Kodi Add-on repository".
![Capture d’écran du 2023-03-18 12-08-44](https://user-images.githubusercontent.com/13408634/226101754-b275bdec-734c-4f3f-8dd7-2fe21c796a93.png)

C'est très frustrant, on ne peut pas bénéficier des fix réguliers de la branche de dev.
J'ai tout de même réussi à installer le repo beta mais c'est clairement pas accessible à tout le monde, voilà comment j'ai procédé :
1. sur mon ordinateur, Kodi installé j'ai suivie la procédure d'ajout de la source "Catch-Up TV & More source"
2. installation de Android Debug Bridge (adb) sur mon ordinateur
3. activation du mode debug sur Android TV
4. établissement de la connection ordinateur <=> tv : `adb connect 192.168.0.23:5555`    (à remplacer par l'ip de la TV)
5. upload du fichier sources.xml (généré à la 1ère étape) sur la TV :  `adb push ~/.kodi/userdata/sources.xml /sdcard/Android/data/org.xbmc.kodi/files/.kodi/userdata/sources.xml`

Je penses qu'une stratégie de releases plus régulier est à étudier et permettrai de bénéficier de version stables à jours (avec des fixs récents). Le communs des utilisateurs ne pourront pas faire ce que j'ai fais ou pas sans mal.

**Comment by darodi** [comment]
@MalibuKoKo 

https://catch-up-tv-and-more.github.io/fr/installation/#2-installer-le-d%C3%A9p%C3%B4t-officiel-de-catch-up-tv--more
>Le plugin est disponible par défaut dans la bibliothèque d’extensions de Kodi, cependant le processus de soumission des mises à jours auprès de l’équipe Kodi est assez longue. Ce délai engendre souvent un écart considérable entre la version disponible sur le dépôt officiel et la dernière version du plugin disponible sur GitHub.

>Pour vous permettre de toujours disposer de la dernière version disponible de Catch-Up TV & More nous mettons à la disposition des utilisateurs un dépôt officiel pour le plugin. Ce dépôt contient toujours la dernière version du plugin et permet à Kodi de mettre à jour automatiquement Catch-Up TV & More sans intervention de votre part.


Ceci n'est pas disponible non plus pour ajouter le zip du dépôt/repository beta?



![image](https://user-images.githubusercontent.com/4682830/226105619-760e685d-8ade-446d-ace4-2e72ccf58fe5.png)




![image](https://user-images.githubusercontent.com/4682830/226105597-5c5cf67c-fa8a-46c0-9b2d-a7a8b42eed51.png)

Si oui, le zip peut être n'importe où ton ton réseau et pas besoin de adb 

il est là
https://catch-up-tv-and-more.github.io/repo/Beta_channel/repository.catchuptvandmore.beta-0.0.6.zip

**Comment by MalibuKoKo** [comment]
@darodi : oui j'ai bien le menu pour installer une source depuis un zip.

Je cherchais le zip dans les [releases](https://github.com/Catch-up-TV-and-More/repository.catchuptvandmore/releases) du repo: [https://github.com/Catch-up-TV-and-More/repository.catchuptvandmore](https://github.com/Catch-up-TV-and-More/repository.catchuptvandmore)

Je ne sais pas pourquoi le menu "Gestionnaire de fichier" n'est pas accessible sur ma version de Kodi, cela ne facilite pas les choses.
Concernant le processus de soumission des mises à jours auprès de l’équipe Kodi je comprends mieux pourquoi des équipes comme vstream ni s'y sont pas frotés ... C'est trop contraingnant.

En tout cas merci pour toutes ces informations.

**Comment by darodi** [comment]
@joaopa00 

Je pense que cette issue peut être fermée du coup, la beta est fonctionnelle.
Le rythme de release non beta dans les dépôts officiels kodi dépend fortement du rythme de validation de Kodi et nous n'avons pas d'influence là dessus.

**Comment by joaopa00** [comment]
La version stable 0.2.29 est sortie sur le site de CUTVM. Comme d'habitude cela va prendre quelques semaines ((mois....) pour qu'elle soit disponible dans les repo officiels de Kodi.
