### ISSUE TITLE
Cache 0% tf1

### ISSUE THREAD

**Issue by francois-pasquier** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1127]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
When watching TF1 there is a lot of random caching.

I am wondering what you would suggest to prevent this behaviour.

It seems to be more common recently (my connection is strong)

i don’t know if it’s tied to the addon itself or inputstream.

### To Reproduce
Steps to reproduce the behaviour:
1. Watch TF1
2. Wait a few minutes

### Expected behaviour
A lot less caching

### Actual behaviour
A lot of random caching

### Your environment
 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: android TV 11
 - Kodi version: 20.1.0
 - Catch-up TV & More version: 0.2.39~beta21
 - Installation method: beta repo addon

### Additional context
Apart from setting the quality to best in the addon, I have not changed anything else

**Comment by joaopa00** [comment]
Même problème pour moi sur Android.

**Comment by francois-pasquier** [comment]
> Même problème pour moi sur Android et Linux. Je vais ouvrir un rapport de bug sur Inputstream Adaptive

N’hésite pas à référencer l’issue ici s’il te plaît 🙏

**Comment by joaopa00** [comment]
J'ai encore testé, mais sur un autre appareil (toujours la même connexion). PAs de problème (c'était pendant la diffusion des schtroumpfs ce matin :D :D )

**Comment by joaopa00** [comment]
Pour moi, le problème semble résolu avec les dernières versions de Inputstream Adaptive

**Comment by joaopa00** [comment]
Pas de nouvelles du rapporteur. Je suppose que le problème est régle. Si ce n'est pas le cas réouvrir avec un nouveau log.
