### ISSUE TITLE
Guide tv ko

### ISSUE THREAD

**Issue by monfiston** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1129]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
A clear and concise description of what the bug is:

### To Reproduce
Steps to reproduce the behaviour:
1.
2.
3.
4.

### Expected behaviour
A clear and concise description of what you expected to happen:

### Actual behaviour
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [x ] Other correlec 9.2.8

 - Operating system version/name:
 - Kodi version:18.9
 - Catch-up TV & More version: 0.2.39 beta 21
 - Installation method:

### Additional context
Add any other context about the problem here:
Good morning,
for a few weeks, there is no longer a tv guide
it's normal ?

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment]
Yes, it is normal for now. See issue #1123

Closing duplicate.
