### ISSUE TITLE
Replay TF1

### ISSUE THREAD

**Issue by rjousse18** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1131]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
Il y a quelques jours j'ai essayé d'accéder aux replays de tf1 et ça ne fonctionnait pas. J'avais une erreur quand je cliquait sur "tf1" dans la catégorie replay.

### To Reproduce
Steps to reproduce the behaviour:
1. Aller dans replay de tf1

### Expected behaviour
Normalement je suis censé accéder à un menu avec les différentes catégories de replay dispo sur tf1.

### Actual behaviour
Erreur au moment de cliquer sur "tf1". Ca reste sur le menu de sélection de chaines.

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ x] Raspberry-Pi 
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: Libreelec 10
 - Kodi version: 19
 - Catch-up TV & More version: j'ai pas vérifié mais ça doit être la dernière
 - Installation method: repository

**Comment by rjousse18** [comment]
Désolé, j'avais posté l'issue rapidement j'ai pas eu le temps de récupérer toutes mes infos.

Du coup je suis bien en version 0.2.38matrix

J'ai cette erreur quand je clique dans la partie "télévision de rattrapage > France > MYTF1 > TF1" :

400 client error : bad request

**Comment by joaopa00** [comment]
Le problème est déjà résolu ans la derninère version béta. Tu peux l'installer (voir [wiki](https://catch-up-tv-and-more.github.io/fr/installation/) ou attendre une mise à jour officielle. Je ferme cette issue.

**Comment by rjousse18** [comment]
Ho super j'avais pas vu désolé ! Merci beaucoup
