### ISSUE TITLE
Sud Radio, erreur Youtube-dl

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1134]
Constaté sur Linux et  Windows. Kodi 20.1 et Catchup à jour version beta

**Comment by joaopa00** [comment]
C'est le m^me problème que dans l'issue #1126
En mettant à jour localement youtube-dl, cela fixe le problème. Des PR ont été envoyées à xbmc repo-script

**Comment by joaopa00** [comment]
Fixé dans GIT. Merci pour le rapport. Je ferme.

**Comment by enigma131** [comment]
Merci
