### ISSUE TITLE
Plus de mise à jour de la liste des replay FranceTV->France5->C'est dans l'air

### ISSUE THREAD

**Issue by jbbriois** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1136]
Les replay de l'emissions quotidienne "c'est dans l'air" ne sont plus mis à jour depuis 1 semaine. Il est possible de regarder les émissions plus anciennes sans problème.
En version stable ou beta, même problème.

Testé sur linux, android. Kodi version 20.1
v 0.2.38

**Comment by joaopa00** [comment]
Sur le json de FranceTv, c dans l'air n'es pas mis à jour mais toutes les autres sont emissions le sont. On va attendre quelques jours avant de voir si FranceTV règle le problème ou pas.

**Comment by jbbriois** [comment]
ok merci

**Comment by joaopa00** [comment]
Elles sont disponibles dans la catégories Toutes les vidéos. En attendant...

**Comment by joaopa00** [comment]
L'émission de ce samedi est bien présente. Semble que FranceTV a eu connaissance du problème. Seulement, l'ordre des émissions est un peu aléatoire....

**Comment by funtravel1208** [comment]
Meme problème avec le journal de 13h ou 20h de France 2 depuis le 31 Mars mais présents dans « All videos »!

**Comment by joaopa00** [comment]
FranceTV a réglé le problème. Aussi bien pour C dans l'air que pour les journaux quotidiens. Je ferme. Si le problème persiste chez vous, n'hésitez pas à réouvrir.
