### ISSUE TITLE
Replay Catchup tv and more My canal

### ISSUE THREAD

**Issue by jackbubble** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1138]
### Describe the bug
A clear and concise description of what the bug is:

Erreur lors des replay des differentes chaînes du groupe myCanal "list index out of range"

### Your environment
 - [X ] Android

 - Operating system version/name: Android 11
 - Kodi version: 20.1
 - Catch-up TV & More version: 0.2.39-beta23

**Comment by darodi** [comment]
- Duplicate of #1133

**Comment by joaopa00** [comment]
Je ferme. Pour toute discussion voir #1133 .
