### ISSUE TITLE
Bug intégration guide tv

### ISSUE THREAD

**Issue by kbn53** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1140]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
A clear and concise description of what the bug is:
Impossible d'ajouter les chaines en intégration dans le guide TV Kodi (si je configure IPTV automatiquement, il met "connexion lost") Le refresh de chaines abouti mais n'ajoute rien dans le guide TV.

### To Reproduce
Steps to reproduce the behaviour:
1. 0.2.38 Beta Catchup and more
2. Intégration chaines dans guide TV Kodi via IPTV SIMPLE

 - Operating system version/name:
 - Kodi version: 20.1
 - Catch-up TV & More version: 0.2.39
 - Installation method: tuto github

**Comment by joaopa00** [comment]
Problème d'IPTVSIMPLE
[problème rapporté à IPTVSIMPLE](https://github.com/add-ons/service.iptv.manager/issues/107)
