### ISSUE TITLE
Dialogue Resolution Chaines

### ISSUE THREAD

**Issue by mmtest1** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1144]
Bonjour, 
j'utilise régulièrement catchuptv and more et actuellement mon réseau internet est dégradé (je suis passé de 9mb à 4mb, j'habite à la campagne et la connection fibre est encore bien loin....), avant, dans les options de l'extension j'activais la boîte de dialogue proposant le choix de la résolution de la chaîne quand cela était possible, depuis un certain temps les chaines francetv, par exemple sont d'office en 1080 et sans possibilité de selectionner une autre résolution, donc inutilisable chez moi et certainement chez toutes les personnes disposant d'une faible connection. 
Serait-il possible de remettre en place le choix de la résolution pour les chaînes proposant différents flux ?
merci

**Comment by joaopa00** [comment]
Rien n'a été modifié dans Catchuptvandmore; Vérie dans les paramètres de l'application, section inputstream que tu es bien en adaptive et dans qualité vidéo le mode dialogue est activé
