### ISSUE TITLE
Channel 4 not working 

### ISSUE THREAD

**Issue by slayerkodi** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1146]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
A clear and concise description of what the bug is:

### To Reproduce
Steps to reproduce the behaviour:
1. Open kodi
2. Select catch up TV and more
3. Select any programmes on channel 4
4. Click play

### Expected behaviour
A clear and concise description of what you expected to happen:
The program to play
### Actual behaviour
Tell us what happens instead:
Playback failed 
### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [v] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: Shield TV android 12
 - Kodi version: Latest
 - Catch-up TV & More version: Latest beta
 - Installation method: installed through repo

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment]
Live and replay work fine for me. 
"Kodi version: Latest" means nothing. You have to tell explicitly the version you use
Do you have a UK IP adress
And you have to attach a full log

**Comment by joaopa00** [comment]
No news from the reporter. I close.
