### ISSUE TITLE
Canadian Channel

### ISSUE THREAD

**Issue by BlueCyborg** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1147]
Hello,
I have Catch-Up TV on my raspberry pi 3 with Kodi.
When i try to go on direct Canadian Channel (like NTV), it give me this error : HTTPERROR 403 Client Error : Forbidden for url ...
For Tele-Quebec it give me an other error : 404 Client Error : Not found for url ...
May you help me find a solution ?

**Comment by joaopa00** [comment]
Do you have a Canadian IP address?

**Comment by BlueCyborg** [comment]
No, would it work with a vpn distributing a Canadian IP?
Why would he restrict their channels to their country?

**Comment by joaopa00** [comment]
Telequebec Live needs a Canadian IP address.
For NTV news, it looks like there is no live streaming.  Looks like it is named NTV+.

**Comment by BlueCyborg** [comment]
Indeed Canada applies the Geo Restriction so a Canadian IP is necessary. It works great with a VPN thank you!
