### ISSUE TITLE
Coupures fréquentes

### ISSUE THREAD

**Issue by wilfarte** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1148]
Version 0.2.39 beta 25
Kodi 20.1
nvidia shield
Inputstream adative 20.3.7

Coupures fréquentes quelle que soit la chaîne regardée. Parfois perte du son...

Solution: réinstaller la version 20.3.4 de InputStream Adaptive pour revenir à une situation normale

**Comment by joaopa00** [comment]
Il n'y a rien que CUTVM puisse faire. Je ferme donc.

**Comment by wilfarte** [comment]
Juste pour aider ceux qui auraient le même problème que moi :) même si le problème n'est pas lié directement à CUTVM

**Comment by joaopa00** [comment]
QUand c'est un proplème de Inpustream Adaptive, il est mieux d'écrire une issue sur le site de Inpustream Adaptive pour que les développeurs soient au courant et puissent regarder au probème. 

Quant à ce problème en particulier, il pouurat être relié à la [potentielle solution](https://github.com/xbmc/inputstream.adaptive/pull/1256)

**Comment by joaopa00** [comment]
J'ai ouvert un rapport de bug dans le github de Inputstream Adative [rapport de bug](https://github.com/xbmc/inputstream.adaptive/issues/1260))
