### ISSUE TITLE
Problème replay chaînes française

### ISSUE THREAD

**Issue by Uthicop** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1155]
Bonjour,

Depuis peu j'ai un nouvel ordinateur et j'ai installé Kodi avec Catchup tv pour regarder TV et replay. Tout fonctionne très bien sur ma tablette mais sur l'ordinateur c'est impossible de faire fonctionner un quelqconque replay.. J'ai en permanence "Echec de lecture d'un ou de plusieurs fichiers"
Kodi est à jour, catchup tv aussi je ne sais plus quoi faire...

Quelqu'un aurait un patch/mise à jour?

Merci à tous

**Comment by joaopa00** [comment]
Pas de nouvelles du rapporteur. On va fermer. Merci pour le réponse, Darodi.
