### ISSUE TITLE
Dysfonctionnement presque total de Catch UP TV sur Fire TV stick 

### ISSUE THREAD

**Issue by Cecilou93220** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1159]
### Content description

* Name: Kodi Catch-up TV
* Type [e.g. TV channel, Catch-up TV, Website, Radio]: Catch-up TV
* Website URL:
* Content language/country: France

### Content access Dysfonctionnement presque total sur le Replay de France TV sauf série Tandem de France 3 : "Erreur Local host Key"
Dysfonctionnement total en Replay sur les chaînes du Groupe My TF1.
Erreur 404 Croix rouge accès au site interdit.

Merci beaucoup d'avance pour l'aide et pour le nouvel Addon.

Merci beaucoup de m'expliquer comment faire pour le télécharger et l'installer sur mon application KODI.
Cécile 

- [ ] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [ ] This content is geographically restricted

### More information

If you want to add more information, put it here:

**Comment by Cecilou93220** [comment]
![IMG20230607125334](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/125290299/3084c93d-ef3a-4710-9b43-093ec143ee41)

**Comment by Cecilou93220** [comment]
![IMG20230607125407](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/125290299/5d45dc18-ea65-4551-bd4e-923f38ffc7f2)

**Comment by Cecilou93220** [comment]
![IMG20230607125423](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/125290299/aa983643-ee77-413b-9110-303853dffb58)

**Comment by Cecilou93220** [comment]
![Uploading IMG20230607125513.jpg…]()

**Comment by Cecilou93220** [comment]
![IMG20230607125513](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/125290299/9d84e59c-65b3-4402-941a-1ca9248d04f4)

**Comment by darodi** [comment]
Merci de fournir toutes les informations

 - Operating system version/name:
 - Kodi version:
 - Catch-up TV & More version:
 - Installation method:

**Comment by Cecilou93220** [comment]
Bonjour,

J'ai désinstallé Catch-up dont j'avais la version 0.2.38 qui ne voulait pas se mettre à jour sur la version plus récente et depuis tout fonctione de nouveau.
Sinon j'ai la version Kodi Matrix 19.4.

Merci

**Comment by darodi** [comment]
Il vaut mieux installer la dernière version
0.2.39~beta27

https://catch-up-tv-and-more.github.io/fr/installation/#ii-ajouter-le-d%C3%A9p%C3%B4t-officiel-de-catch-up-tv--more
choisir le mode d'installation avec le beta repository
