### ISSUE TITLE
Replays MyTF1 - Erreur - Le flux vidéo n'est pas disponible

### ISSUE THREAD

**Issue by raydenxxx** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1162]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
A clear and concise description of what the bug is: Impossible de lancer les replays des chaines MyTF1

### To Reproduce
Steps to reproduce the behaviour:
1. Aller dans Catch-up TV & More
2. Aller dans les replays FR
3. Aller dans les replays MyTF1
4. Aller dans TMC
5. Aller dans Infos, Mag & Sport
6. Cliquer sur Quotidien
7. Cliquer sur Replay
8. Lancer n'importe quel replay

### Expected behaviour
A clear and concise description of what you expected to happen: Le replay devrait se lancer

### Actual behaviour
Tell us what happens instead: Le replay ne se lance pas et une erreur s'affiche "Le flux vidéo n'est pas disponible" puis "Echec de lecture d'un ou plusieurs fichiers"

### Screenshots
If applicable, add screenshots to help explain your problem:
![IMG_9872](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/122745590/5bbd89cc-46f0-48e7-b8de-33b8a342c843)

![IMG_9871](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/122745590/792f5b81-0bb6-474a-a76f-828d662d6408)

### Your environment
 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Other

 - Operating system version/name: Windows 11 et Android TV
 - Kodi version: testé sur 20.1 et 19.5.0
 - Catch-up TV & More version: testé sur 0.2.39 beta 27 et sur 0.2.39 beta 20
 - Installation method: via le repo beta

### Additional context
Add any other context about the problem here: les lives ne marchent pas non plus.

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/11734623/kodi.log)

**Comment by raydenxxx** [comment]
une copie du log au moment de l'erreur
`
2023-06-13 14:02:06.897 T:3476     INFO <general>: initializing python engine.
2023-06-13 14:02:07.484 T:3476     INFO <general>: CPythonInvoker(18, C:\Users\coren\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\addon.py): script successfully run
2023-06-13 14:02:07.550 T:3476     INFO <general>: Python interpreter stopped
2023-06-13 14:02:08.345 T:15372    INFO <general>: initializing python engine.
2023-06-13 14:02:09.604 T:15372    INFO <general>: CPythonInvoker(19, C:\Users\coren\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\addon.py): script successfully run
2023-06-13 14:02:09.677 T:15372    INFO <general>: Python interpreter stopped
2023-06-13 14:02:11.906 T:15620    INFO <general>: initializing python engine.
2023-06-13 14:02:12.894 T:15620    INFO <general>: CPythonInvoker(20, C:\Users\coren\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\addon.py): script successfully run
2023-06-13 14:02:12.902 T:9352    ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/mytf1/get_video_url/?_pickle_=8004955d000000000000007d94288c075f7469746c655f948c1951756f74696469656e206475203132206a75696e2032303233948c08766964656f5f6964948c2464303661666464332d383065392d343239302d383064642d64646366663162303466616494752e]
2023-06-13 14:02:12.966 T:15620    INFO <general>: Python interpreter stopped`

**Comment by AntoninMartin** [comment]
Même problème sur la version MacOS ici

**Comment by raydenxxx** [comment]
Je pense que quelque chose a changer chez TF1, ça ne doit plus marcher pour personne

**Comment by AntM90** [comment]
> Je pense que quelque chose a changer chez TF1, ça ne doit plus marcher pour personne

Aucun doute là dessus je pense

**Comment by enigmathix** [comment]
Dans le json:
```
   "media":{
      "id":"13992886",
      "type":"video",
      "error_code":"PERMISSION_DENIED",
      "error_desc":"Permission insuffisante",
...
   "delivery":{
      "code":403,
      "error":"Permission insuffisante",
...
```

**Comment by sousouille** [comment]
Question : les replays sont accessibles depuis un navigateur. On obtient un jeton à l'aide d'un clientid. Voici un jeton : 
```
eyJhbGciOiJFUzI1NiIsImtpZCI6ImRlZmF1bHQiLCJ0eXAiOiJKV1QifQ.eyJhYlRlc3QiOnt9LCJleHAiOjE2ODY3ODQ4MjcsImZjZmEiOjAsImZ0Ijp7fSwiaWF0IjoxNjg2Njg0MDI3LCJpZGQiOjAsImlzcyI6ImdpZ3lhIiwibHZsIjoxLCJtc2NiIjpmYWxzZSwibm9BdWRpZW5jZSI6ZmFsc2UsIm5vQ3VzdG9taXphdGlvbiI6ZmFsc2UsIm5vUHJvZmlsaW5nIjpmYWxzZSwicGx0Ijoid2ViIiwic3ViIjoiNTg1ZjJmYTM3Mzk5NDQwMmFjNzM0ZjZjNjQzYTNmMmUifQ.2_iHxUNYD0MlZUtIFYCwBhbZpXfwmLOxoEszm-FRJZF788PpeLB0pu6tvhrD2zdcbtskSckvWMPbnANai71kGQ
``` 

Quelle est la difficulté rencontrée ?

**Comment by enigmathix** [comment]
La difficulté est de répliquer ça dans une app autre qu'un navigateur car le jeton expire au bout de 3 heures. D'après ce que j'ai pu voir, on peut obtenir le token et le refresh token par https://www.tf1.fr/token/gigya/web en fournissant un uid et une signature. Le refresh token est aussi sauvegardé dans les cookies et a une durée de vie de 6 mois, il sert à générer un nouveau jeton mais il y a des chances qu'il change aussi lors du refresh. Reste à trouver l'algorithme pour l'uid et la signature, qui doit certainement aussi nécessiter une clé. 

Même en trouvant une solution à ça, il reste le problème du DRM, qui est à mon avis insoluble sans être partenaire de TF1 (c'est le but du DRM).

**Comment by sousouille** [comment]
l'uid à l'air d'être fixe par utilisateur. La signature est lié au timestamp ☹: aucune idée d'où elle sort

**Comment by darodi** [comment]
> Même en trouvant une solution à ça, il reste le problème du DRM, qui est à mon avis insoluble sans être partenaire de TF1 (c'est le but du DRM).

Un DRM, c'est simplement donner la clé à quelqu'un pour faire une action sans lui dire comment on lui a donné la clé. (Ex: les clés de chiffrement DVD sont sur le DVD!)
Si l'action est faisable via le site, elle est faisable via Kodi/CUTVM.
Maintenant, je n'ai pas dit que ça serait facile.
token+refresh_token, il y a de grandes chances qu'on soit en oauth v2

**Comment by enigmathix** [comment]
Vu sur un autre github: si on supprime context=MYTF1 de l'url URL_VIDEO_STREAM dans le code, on évite le DRM et l'autorisation, et on obtient ça dans le json (hls pour moi mais c'est pareil pour dash):
`      "stream-id":"13970670_hls_nodrm_nomax"
`
Notez le "nodrm". Problème: ça semble ne marcher que sur les petites videos. Pour Quotidien par exemple, on peut voir les extraits mais pas toute l'émission. Dans ce cas, on obtient une "erreur de delivery".

**Comment by Florian-GM** [comment]
Je confirme, plus de live TF1 non plus. Erreur : géo-bloqué

Je n'utilise pas de vpn, aucun changement non plus sur quoi que ça soit.

TF1 a donc changé quelque chose.

**Comment by darodi** [comment]
Depuis la Belgique, tout semble bloqué, même avec un compte.

![image](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/4682830/cb1e2981-abb9-43a6-b222-c9ec3c37b9a1)

Difficile de vous aider pour l’implémentation dans ces conditions :/

**Comment by Jon01993** [comment]
Salut, même problème mais les extraits et exclus fonctionnent alors que ce n'était pas le cas il y a deux jours.
Merci d'avance pour votre aide!!

**Comment by Fabien07270** [comment]
Bonjour Même pb depuis quelques jours pour moi. Cela semble général ? Désinstall/réinstall Kodi, Catch up en version beta mais toujours sans succès.
Merci d'avance pour votre aide

**Comment by Jon01993** [comment]
Merci pour le tuyau mais je n'ai pas trouvé les replays de TF1 sur cette extension

**Comment by ludopotte** [comment]
Oui Jon01993 c'est normal car tu dois savoir le programme que tu veux rechercher.

**Comment by parer55** [comment]
I have the same problem. Kudos to anyone who can solve this.
J'ai le même problème. Félicitations à celui ou celle qui trouvera la solution.

**Comment by tcharlat** [comment]
Je pense qu'il faut ajouter tf1 à la liste des chaines requérant un compte, comme m6, nrj, etc.
Un exemple de comment on peut voir que le code .py pour m6 fonctionne :

https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/dev/resources/lib/channels/fr/6play.py#L380

Je pense qu'il faut ajouter la saisie des identifiants / password pour le plugin mytf1, et mettre à jour l'accès au stream une fois la requête signée analysée (obtention token, refresh, etc.)

Désolé de ne pouvoir aider, je suis très loin d'avoir un setup pour faire du dev sur ce plugin, bon courage et kudos aux maintainers 👍

**Comment by raydenxxx** [comment]
> Je pense qu'il faut ajouter tf1 à la liste des chaines requérant un compte, comme m6, nrj, etc. Un exemple de comment on peut voir que le code .py pour m6 fonctionne :
> 
> https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/dev/resources/lib/channels/fr/6play.py#L380
> 
> Je pense qu'il faut ajouter la saisie des identifiants / password pour le plugin mytf1, et mettre à jour l'accès au stream une fois la requête signée analysée (obtention token, refresh, etc.)
> 
> Désolé de ne pouvoir aider, je suis très loin d'avoir un setup pour faire du dev sur ce plugin, bon courage et kudos aux maintainers 👍

Compte tenu que sur MyTF1.fr quand on est logué on a accès au replay pendant 7 jours je pense que tu as tout à fait raison

**Comment by enigmathix** [comment]
Bon j'ai réussi à faire marcher la DRM, mais ça va pas vous aider. J'explique: je n'utilise pas ce plugin, mais j'ai écrit une app pour AppleTV. Elle a cessé de fonctionner comme vous tous, alors je me suis plongé dans la DRM qui est FairPlay chez Apple. Il y a en fait 3 étapes:

1. obtenir un certificat. facile, il est décrit dans le json des videos, c'est https://drm-fair.tf1.fr/certificate.der
2. trouver l'asset ID. facile aussi, il est dans le json des videos, par exemple 13994087
3. obtenir la clef de décryption. c'est là où vous aurez du mal

Pour obtenir cette clef, il faut 3 éléments: le certificat, l'assetID, et l'url pour obtenir la clef. Cet url est aussi dans le json. Pour fairplay, c'est https://drm-fair.tf1.fr/acquire?id=13994087... dans ce cas.
Et c'est la qu'est le problème: il faut aussi un bout de donnée qui est fourni par l'app ou l'OS: c'est le SPC (server playback context). Pour moi, c'est tvOS qui me le donne. Dans Safari, c'est l'extension EME du webkit qui le donne. Quand on le passe au serveur de TF1, on reçoit en échange une clef de décryption que l'on passe à l'OS pour décrypter la video. De ce que je comprends pour Fairplay au moins, c'est que l'algorithme de génération de ce SPC n'est pas public et la clef pas accessible autrement.

Il me reste encore à résoudre le problème  de l'obtention du token. Pour l'instant je le copie manuellement de Safari en allant sur mytf1.fr et il est valable quelques heures.

**Comment by darodi** [comment]
@enigmathix 

Merci pour ces infos.
Fairplay est spécifique au monde apple.

Sur mytf1, les autres browsers utilisent du mpeg-dash mpd et widevine drm, pas du fairplay.
Exemple: 
https://mediainfo.tf1.fr/mediainfocombo/13694d96-440a-45dc-86db-90c45c57ac63?pver=5010000&context=MYTF1&topDomain=unknown&platform=web&device=desktop&os=windows&osVersion=10.0&playerVersion=5.10.0&productName=mytf1&productVersion=2.59.1&browser=firefox&browserVersion=114

```
{
...
"delivery": {
    "code": 200,
    "url": "https://vod-das.cdn-0.diff.tf1.fr/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaXAiOiIyMTMuMjEzLjIwOS4xNzEiLCJjbWNkIjoiIiwiZXhwIjoxNjg2OTcxNTI1LCJnaWQiOiIxNmQ2OTQ5ZmIzMjU0NTUwODU3ZTg3MTA3MDQ2NGY2ZSIsImlhdCI6MTY4Njk1NzEyNSwiaXNzIjoiZGVsaXZlcnkiLCJtYXhiIjoyODAwMDAwLCJzdGVtIjoiLzIvVVNQLTB4MC8zMi84OC8xMzk5MzI4OC9zc20vMDVlMTBlNzEwNDI2NWZmMDRjYTJlYzJlNGJlMzY3OTMwYWE1OWUzYTBkZTVjZDQzM2YyMWM5NGMzMjU0NTQ4OS5pc20vMTM5OTMyODgubXBkIiwic3ViIjoiMTZkNjk0OWZiMzI1NDU1MDg1N2U4NzEwNzA0NjRmNmUifQ.js10jHKp7LxKpPtr2Mxx4YIq27FSF6N6miDStg89DMs/2/USP-0x0/32/88/13993288/ssm/05e10e7104265ff04ca2ec2e4be367930aa59e3a0de5cd433f21c94c32545489.ism/13993288.mpd",
    "country": "BE",
    "format": "dash",
    "drm": "widevine",
    "drm-server": "https://widevine-proxy-m.prod.p.tf1.fr/proxy?id=13993288&rn=1&ssc=1b281c65-fe77-416b-864d-628017f2e789&si=46549bb293595ba980b40caf12d965c903bb3a3f9ddcbb00e45449edeff56984&e=1686971525",
    "drms": [
      {
        "name": "widevine",
        "url": "https://widevine-proxy-m.prod.p.tf1.fr/proxy?id=13993288&rn=1&ssc=1b281c65-fe77-416b-864d-628017f2e789&si=46549bb293595ba980b40caf12d965c903bb3a3f9ddcbb00e45449edeff56984&e=1686971525"
      },
...
}
```

C'est ce que nous utilisons dans CUTVM aussi.
Inputstream adaptive, le plugin utilisé pour la gestion drm ne gère pas le fairplay
https://github.com/xbmc/inputstream.adaptive/wiki#supported-drm


J'ai commencé l'implémentation du login, j'essayerai de continuer ce we

**Comment by darodi** [comment]
_Originally posted by @ludopotte in https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1162#issuecomment-1593342069_
> En attendant la résolution du Problème, installer vStream sur Kodi (Dépôt + Extension ou Beta) au https://github.com/[SCRAMBLED]/vStream et ensuite aller dans les Rubrique "Rediffusions TV", "Rechercher (TV Replay)" et ensuite tapez votre recherche. Utiliser vStream avec un Débrideur disponible au [www.bit.ly/[SCRAMBLED]](http://www.bit.ly/[SCRAMBLED])


1. vStream n'est pas dans la liste officielle des addons Kodi, je vous laisse deviner pourquoi... en effet, ce n'est pas très légal
  https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons
2. Le repository habituel de vstream n'est pas celui là
   Je ne connais pas ludopotte mais, à votre place,  je me méfierais avant d'installer un repository sorti de nulle part avec uniquement 3 stars dans github. (qui pointe vers https://github.com/mr[SCRAMBLED]2/mr[SCRAMBLED]2.github.io qui a encore moins de stars) et des débrideurs qui sont certainement des liens sponsorisés


@joaopa00 
Je te poke si tu n'avais pas suivi dans la discussion
J'imagine que les guidelines ici sont les mêmes que la position officielle de Kodi? scrambler les urls de ce post?
https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons

**Comment by ludopotte** [comment]
Pour Infos, l'Extension vStream que je propose est bien réel sans risque car c'est une version de la Beta Officielle de vStream que je mets à disposition pour les gens et le dépôt de vStream est aussi l'officiel. Par rapport au débrideurs, c'est des débrideurs officiels que j'utilise pour Kodi sans risque. Au gens de faire leur choix !

**Comment by darodi** [comment]
@joaopa00  @ludopotte 

En effet, si des gens veulent utiliser des plugins utilisant des flux pirates, c'est leur choix. 
Si des gens veulent braquer une banque, si des gens veulent rouler à contre sens sur l'autoroute, c'est leur choix :)
Les gens peuvent faire n'importe quoi, mais il y a des aspects légaux.
Je préviens donc.

Vu ces aspects, c'est plutôt la promotion de ce genre de plugin dans le repo de CUTVM qui me pose problème.
J'admets qu'il n'y a pas de " Code of conduct " dans le repository de CUTVM. (à rajouter peut être?)
Je laisse donc @joaopa00 décider.

**Comment by ludopotte** [comment]
Je comprends @darodi mais moi je suis la pour partager, rien de plus. Donc @joaopa00 décider.

**Comment by darodi** [comment]
Bien sûr, et la marche à suivre ici est floue tant qu'il n'y a pas de "code of conduct".
Je propose que nous revenions au sujet du post, faire fonctionner myTF1 sur CUTVM

**Comment by joaopa00** [comment]
Bonjour à tous, concernant la politique de CUTVm. Elle est à toujours été de ne mettre de que des liens légaux. Les développeius n'ont pas envie de se retrouver au tribunal. Bonne idée de mettre un petit avertissement pour les utilisateurs.

**Comment by ludopotte** [comment]
Désolé pour mon Partage, je ne savais pas le Règlement de CUTVM.

**Comment by Arias800** [comment]
La gestion du DRM de Widevine n'a pas changé. Ce qui manque à Catchup TV c'est la connexion au compte MyTF1 (qui est maintenant obligatoire).
J'ai un code fonctionnel sur un projet perso, il ne me "reste plus" qu'à le porter sur Catchup.

**Comment by enigmathix** [comment]
Code pour obtenir les tokens:

```
import requests
import json

apiKey = '3_hWgJdARhz_7l1oOp3a8BDLoR9cuWZpUaKG4aqF7gum9_iK3uTZ2VlDBl8ANf8FVk'

tf1Session = requests.Session()

# bootstrap to set cookies
r = tf1Session.get('https://compte.tf1.fr/accounts.webSdkBootstrap?apiKey={}&pageURL=https%3A%2F%2Fwww.tf1.fr%2F&sdk=js_latest&sdkBuild=13987&format=json'.format(apiKey))

formData = {
'loginID': 'USERNAME', #TODO
'password': 'PASSWORD', #TODO
'sessionExpiration': 31536000,
'targetEnv': 'jssdk',
#'include': 'identities-all,data,profile,preferences,',
'include': '',
'includeUserInfo': 'true',
'loginMode': 'standard',
'lang': 'fr',
'APIKey': apiKey,
'sdk': 'js_latest',
'authMode': 'cookie', #TODO or token
'pageURL': 'https://www.tf1.fr/',
'sdkBuild': '13987',
'format': 'json',
}

# get login info
r = tf1Session.post('https://compte.tf1.fr/accounts.login', data=formData)
if r.status_code == 200:
    js = json.loads(r.content)

formData = {
'consent_ids': [ "1", "2", "3", "4", "10001", "10003", "10005", "10007", "10013", "10015", "10017", "10019", "10009", "10011", "13002", "13001", "10004", "10014", "10016", "10018", "10020", "10010", "10012", "10006", "10008"],
'signature': js['userInfo']['UIDSignature'],
'timestamp': int(js['userInfo']['signatureTimestamp']),
'uid': js['userInfo']['UID'],
}

headers = {
'Accept': '*/*',
'Accept-Encoding': 'gzip, deflate, br',
'Content-Type': 'application/json',
}

r = tf1Session.post('https://www.tf1.fr/token/gigya/web', json=formData, headers=headers)

if r.status_code == 200:
    js = json.loads(r.content)
    print(js)
```

**Comment by darodi** [comment]
je confirme, j'étais justement en train de tester tout ça :)

**Comment by Florian-GM** [comment]
Une mise à jour de prévu pour catchup ?

**Comment by darodi** [comment]
J'ai fait une pull request pour les replays.
Je ne peux pas tester pour les lives avec le blocage géographique en Belgique, mais la même technique devrait fonctionner 
(réutiliser la méthode resources.lib.channels.fr.mytf1.get_token)

**Comment by joaopa00** [comment]
J'ai testé la PR avec l'épisode de Mentalist sur TMC. Nom de l'épisode  "le tueur le plus fort". Malheureusement, cela ne fonctionne pas. De même pour d'autres vidéos. Le direct fonctionne quant à lui.

**Comment by joaopa00** [comment]
Bon j'ai rien dit. Ca se lance. SUr linux, ca freeze. Problème de inputstream adaptive certainement.

**Comment by darodi** [comment]
j'ai dev sur windows. Je vais essayer avec mon raspberry pi

**Comment by darodi** [comment]
Erreur aussi de mon côté sous rpi:

```
2023-06-18 19:39:52.285 T:1525    error <general>: AddOnLog: inputstream.adaptive: ParseManifest: Failed to parse the manifest file
2023-06-18 19:39:52.286 T:1525    error <general>: AddOnLog: inputstream.adaptive: Could not open / parse manifest (https://vod-hls.cdn-0.diff.tf1.fr/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjaXAiOiIyMTMuMjEzLjIwOS4xNzEiLCJjbWNkIjoiIiwiZXhwIjoxNjg3MTI0Mzg0LCJnaWQiOiIxNmQ2OTQ5ZmIzMjU0NTUwODU3ZTg3MTA3MDQ2NGY2ZSIsImlhdCI6MTY4NzEwOTk4NCwiaXNzIjoiZGVsaXZlcnkiLCJtYXhiIjoyODAwMDAwLCJzdGVtIjoiLzIvVVNQLTB4MC81OC83My8xMzkzNTg3My9zc20vYzc3YmZjZGVlMjU1NTM4YTE1NzZiZTI2NDhlOTVmY2RhYjY3M2IwMGVlNTU0MDFhMGQ4OTcyZmQ5ZWRlNGQyYS5pc20vMTM5MzU4NzMubTN1OCIsInN1YiI6IjE2ZDY5NDlmYjMyNTQ1NTA4NTdlODcxMDcwNDY0ZjZlIn0.9NU3Sdga7aXwzdQsuKOGkBnIuTPiwu1Zga9kBZtYyMY/2/USP-0x0/58/73/13935873/ssm/c77bfcdee255538a1576be2648e95fcdab673b00ee55401a0d8972fd9ede4d2a.ism/13935873.m3u8)
```

**Comment by darodi** [comment]
OK je pense avoir trouvé
quand le 
`web_utils.get_random_ua()`
renvoie 

```
{'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14',
...}
```


ça passe en fairplay on dirait

**Comment by darodi** [comment]
@joaopa00 
et ça marche sur mon rpi 😃
j'ai pushé

**Comment by sousouille** [comment]
Question : je suis sur le canal beta sur Android TV, comment installer d'ores et déjà la dernière #1164 : j'ai tenté de forcer la màj mais rien n'apparait : il faut attendre un build ?

**Comment by raydenxxx** [comment]
> Question : je suis sur le canal beta sur Android TV, comment installer d'ores et déjà la dernière #1164 : j'ai tenté de forcer la màj mais rien n'apparait : il faut attendre un build ?

Si tu ne veux pas attendre que le code soit poussé dans la bêta il faut l’installer à la main.

![Uploading 089C3B03-8F34-415D-9FD2-141DB0F18974.jpeg…]()

**Comment by raydenxxx** [comment]
Je viens de tester ça marche, merci à tous! ❤️

**Comment by enigmathix** [comment]
Une version simplifiée du code car il n'y a pas besoin du bootstrap si on restreint les paramètres du login:

```
apiKey = '3_hWgJdARhz_7l1oOp3a8BDLoR9cuWZpUaKG4aqF7gum9_iK3uTZ2VlDBl8ANf8FVk'

tf1Session = requests.Session()

formData = {
'loginID': 'USERNAME', #TODO
'password': 'PASSWORD', #TODO
'APIKey': apiKey,
}

# get login info
r = tf1Session.post('https://compte.tf1.fr/accounts.login', data=formData)
if r.status_code == 200:
    js = json.loads(r.content)

formData = {
'consent_ids': [ "1", "2", "3", "4", "10001", "10003", "10005", "10007", "10013", "10015", "10017", "10019", "10009", "10011", "13002", "13001", "10004", "10014", "10016", "10018", "10020", "10010", "10012", "10006", "10008"],
'signature': js['UIDSignature'],
'timestamp': int(js['signatureTimestamp']),
'uid': js['UID'],
}

headers = {
'Content-Type': 'application/json',
}

r = tf1Session.post('https://www.tf1.fr/token/gigya/web', json=formData, headers=headers)

if r.status_code == 200:
    js = json.loads(r.content)
    print(js)
```

**Comment by coolben54** [comment]
Merci beaucoup, le replay de TF1 refonctionne sur mon Raspberry Pi
Par contre, la liste des épisodes disponibles est maintenant réduite à 1 semaine comme c'est le cas sur l'interface web de MyTF1.
Et je me demandais qu'est ce qui permettait avant d'avoir accès avant à une liste plus large ?
Par exemple, on avait la possibilité de voir tous les épisodes de Koh Lanta jusqu'à 1 semaine après que le dernier épisode de la saison passe à la télé.

**Comment by raydenxxx** [comment]
> Merci beaucoup, le replay de TF1 refonctionne sur mon Raspberry Pi
> Par contre, la liste des épisodes disponibles est maintenant réduite à 1 semaine comme c'est le cas sur l'interface web de MyTF1.
> Et je me demandais qu'est ce qui permettait avant d'avoir accès avant à une liste plus large ?
> Par exemple, on avait la possibilité de voir tous les épisodes de Koh Lanta jusqu'à 1 semaine après que le dernier épisode de la saison passe à la télé.

TF1 a clairement changé son API et maintenant on est obligés d’être logués pour consulter leurs replays.
Sur un compte standard les replays sont dispos 7 jours.
Sur un compte Max (payant) on peut avoir une durée plus longue.

**Comment by Fabien07270** [comment]
Bonjour, ça fonctionne aussi très bien pour moi sur android tv en installant #1114 à la main et en renseignant le compte mytf1 dans les paramètres.
Merci à tous pour le travail et bonne journée.

**Comment by camherry** [comment]
Bonjour à tous,
Merci pour les infos et le correctif, j'ai également téléchargé et installé la version de la branche Dev.
En revanche, ce qui est dommage, mais qui se comprend, c'est qu'il a fallu créer un compte sur TF1 pour continuer à bénéficier des replays, mais il n'est plus possible d'avoir les replays issus du mytf1 max, puisque notre compte n'est pas un compte qui a souscrit à cette offre c'est ça ?

**Comment by lilie004** [comment]
Bonjour à tous 👋 
Comment faire sur fire tv svp?
Bonne journée 
Merci

**Comment by camherry** [comment]
Depuis le downloader, si vous entrez l'URL suivante : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/archive/refs/heads/dev.zip

ça devrait permettre d'importer le zip sur votre firetv, ensuite depuis l'application Kodi, vous devriez installer l'extension ZIP qui se trouve dans l'arborescence du firetv

**Comment by lilie004** [comment]
Merci beaucoup ça fonctionne 👍👍👍
Du coup on aura plus du tout accès au avantage de my tf1 max?

**Comment by darodi** [comment]
>Par contre, la liste des épisodes disponibles est maintenant réduite à 1 semaine comme c'est le cas sur l'interface web de MyTF1. Et je me demandais qu'est ce qui permettait avant d'avoir accès avant à une liste plus large ? 

Il est vrai que le code de CUTVM actuel fait le login avant de regarder une vidéo.
Si on change pour se loguer avant de faire la liste des contenus disponibles, ça pourrait peut être ramener une liste plus large et marcher avec plus de contenu.
Je n'ai pas de compte Max (payant) pour tester ça, désolé.

**Comment by kevlare** [comment]
J'ai installé la nouvelle beta et je peux lancer la vidéo mais j'ai seulement le son. Sur FranceTV j'ai son et vidéo. Je suis également connecté depuis la France. J'utilise une Shield TV.
![PXL_20230619_191203174 MP](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/99365449/34c4d25b-152a-4189-9177-1d3b2a3b5636)

**Comment by darodi** [comment]
@enigmathix 

Merci pour ces infos. 

> Le refresh token étant sauvegardé dans un cookie, il n'y a pas de paramètres à passer. La question peut se poser si le fait de décentraliser le refresh token dans le client comme ça peut empêcher l'accès simultané à plus d'un client (app ou appareil), mais non, ça marche quand même. Leurs serveurs doivent garder une liste de refresh tokens valides.

Oui c'est le principe en oauth v2. 
Le login se fait souvent en passant le login, mot de passe, et parfois un id de périphérique (ici le TCPID généré on dirait).
Ça génère un access_token avec une validité courte et un refresh_token avec une validité plus longue.
Le tout est stocké côté serveur.

On pourrait améliorer le code pour stocker le refresh_token et sa date de validité.
Si le refresh_token est expiré, on se relogue.
Si le refresh_token est presque expiré, on le refresh

Ça pourrait peut être aussi corriger les problèmes de contenu pour l'abonnement max.
On serait logué au moment de la demande de liste de contenu.

J'essayerai de trouver le temps de tester et d'implémenter ça.

**Comment by enigmathix** [comment]
Oui, j'ai un serveur qui repose aussi sur oauth2, mais je m'embête pas à envoyer les refresh tokens aux clients pour en garder une liste sur le serveur. J'en garde 1 par utilisateur, et tous les clients d'un utilisateur utilisent le même sans avoir besoin de le savoir ou de gérer son expiration.

L'autre truc qui m'intrigue est que leur code client récupère le token mais ignore le TTL (time to live) de 28h, il n'est sauvegardé nulle part (à moins qu'il soit hard-codé ailleurs mais ça serait moche). Du coup je me demande ce qui se passerait si leur client restait en mémoire pendant 28h sans se reconnecter. Est-ce qu'il redemande un token en cas d'erreur.? Ca ferait un peu bizarre. Catch-up (et mon app) pourrait faire ça plus proprement. Ce cas devrait arriver plus souvent qu'un refresh token qui expire, il faudrait ne jamais faire de refresh pendant 1 an, autant dire qu'on ne regarde jamais TF1.

**Comment by jeanmi-git** [comment]
> J'ai installé la nouvelle beta et je peux lancer la vidéo mais j'ai seulement le son. Sur FranceTV j'ai son et vidéo. Je suis également connecté depuis la France. J'utilise une Shield TV. ![PXL_20230619_191203174 MP](https://user-images.githubusercontent.com/99365449/246916093-34c4d25b-152a-4189-9177-1d3b2a3b5636.jpg)

C'est la même chose pour moi, le son sans l'image, depuis que j'ai entré mes identifiants MyTF1.
Il y a une solution à ce problème ?

**Comment by joaopa00** [comment]
Pour ce genre de bug, al démarche est toujours la même. S'assurer d'avoir la dernière version disponible de Inputstream Adaptive. Actuellement, c'est la version 2.3.9. Si IA est à juor et le problème persiste, il faut envoyer un rapport de bug à IA.

**Comment by kevlare** [comment]
Merci, pour la réponse [joaopa00](https://github.com/joaopa00)  j'ai vérifié, j'ai la version 20.3.9 de IA, j'ai donc soumis un bug avec IA. Voici le lien:
https://github.com/xbmc/inputstream.adaptive/issues/1299

**Comment by 0x0040** [comment]
Le problème est toujours présent malgré l'utilisation des dernières mises à jour pour certain Replay uniquement : Mask Singer, The Voice, Koh-Lanta...
Pour la série HPI, aucun problème avec les épisodes de la saison 2 à l'inverse de la saison 3 où on a le message d'erreur...

**Comment by enigmathix** [comment]
Tu as TF1 MAX? Si tu l'as pas, c'est normal que tu puisses pas voir tout ça, ce sont des programmes vieux de plus de 7 jours.

**Comment by jeanmi-git** [comment]
Le problème est encore là pour moi :'(

**Comment by darodi** [comment]
@jeanmi-git 

je viens de tester sous android avec mon téléphone. 
Kodi 20, dernière version pas de soucis.
Créer un nouveau ticket avec toutes les infos nécessaires (version de kodi, version de inpustream adaptive, ...) et les logs.
Merci

**Comment by Souan79** [comment]
Bonjour à tous,
Meri pour toutes ces astuces que même une mamie de plus de 70 ans a réussi à mettre en oeuvre et ça fonctionne  : l'accès au replay de tf1 sur 7 jours glissants est accessible de nouveau, mais simplement en visionnage.
Existe-t-il une possibilité d'enregistrement ? j'ai essayé 1000 manips sans succès.  Sur les autres chaines on a un bouton "télécharger", mais pour TF1 et M6 il n'y a pas.

**Comment by joaopa00** [comment]
M6 et TF1 interdisent le téléchargement des émissions par une protection numérique. Comme CUTVM est un logiciel légal, aucun moyen de contourner ces protections n'est et ne sera impléménté.

**Comment by Souan79** [comment]
Merci, je comprends.
