### ISSUE TITLE
Code of conduct on CUTVM repository ?

### ISSUE THREAD

**Issue by darodi** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1163]
### Content description

* Name: Code of conduct
* Type: Code of conduct on CUTVM repository
* Website URL: https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/community/code-of-conduct/new
* Content language/country: all

### More information

Following the discussion [here](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1162#issuecomment-1595696883), shouldn't CUTVM repository specify a `code of conduct` ?

Some subjects 
- issue requesting pirated content?
- PR of code with pirated content?
- promotion of pirated content?

template document here 
   https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/community/code-of-conduct/new?template=contributor-covenant

...or just forget it and YOLO!

**Comment by joaopa00** [comment]
C'est une bonne idée de préciser dans les instructions de rapport de bugs qu'aucun lien illégal est accepté dans CUTVM et que toute discussion à propos de cela est strictement interdite.
Je te laisse envoyer une PR ajoutant cela?
