### ISSUE TITLE
Artefacts on Video with TF1 and drm

### ISSUE THREAD

**Issue by CChalu** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1167]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️
Hello,
### Describe the bug
Since tf1 has DRM, the image has artefacts, very frequent pixelations. I had this bug on M6 at the beginning, but now it's no longer the case.

### To Reproduce
Steps to reproduce the behaviour:
1. Watch a video on tf1 Channel

### Expected behaviour
No more artefacts, same as M6

### Your environment
 - [ ] Android TV 9 ( TV Sony Bravia 4K UR2)
 - Kodi version: 20.1
 - Catch-up TV & More version: 0.2.39~beta28
 - Installation method: playstore 

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment]
Incapable de reproduire aussi bien sur LInux que sur Android. La meilleure chose que tu aies à faire est de faire un rapport de bug sur le site de Inpustream Adaptive?

**Comment by CChalu** [comment]
Merci pour votre retour. Est-ce que la gestion des drm est la même pour TF1 et M6 ?
Le problème vient des drm présents à la fois sur la vidéo et l’audio.
Ce qui m’étonne, c’est de ne plus avoir le problème de pixellisation avec M6, il n’y a plus des drm sur la vidéo et l’audio pour M6 ?

Pouvez-vous me confirmer que du côté de catch up TV, la gestion des drm est similaire pour TF1 et M6 ?
Merci

**Comment by joaopa00** [comment]
CUTVM ne gère pas les drms. C'est fait par Inputstream Adative. CUTVM ne collecte simplement que les liens.

**Comment by CChalu** [comment]
Bonjour,
Ayant plus de temps, j’ai fait d’autres essais.
Dans les paramètres de Catchup TV, j’ai désactivé inputstream.adaptive et activé ytdl.
Les lectures des vidéos sur TF1 et M6 se lancent quand même (malgré les drm ?) J’ai les mêmes artefacts sur TF1 et pas de problème pour M6. Est-ce que inputstream est quand même utilisé si on le désactive dans les paramètres de l’addon ? C’est pour le rapport de bug, je ne veux pas leur en faire un si ce n’est pas le cas.
Merci

**Comment by joaopa00** [comment]
Est-ce que le problème est encore présent avec Kodi Omega? Il y a eu des améliorations dans FFMPEG qui pourraient avoir aidé.

**Comment by CChalu** [comment]
Oui le problème est toujours présent.

**Comment by CChalu** [comment]
Bonjour,
Ma TV Sony a eu une mise à jour vers android TV 10 la semaine dernière et ça a réglé le problème !
Merci de votre attention et de vos réponses.

**Comment by CChalu** [comment]
Je clos donc cette issue.
