### ISSUE TITLE
Catch up tv « route missing »

### ISSUE THREAD

**Issue by Laurag02** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1168]
Bonjour,

Depuis aujourd’hui je n’arrive plus à accéder à catch up tv. 
J’ai supprimé l’extension et je l’ai réinstallée et rien n’y fais. J’ai télécharger la beta et la stable et aucune des deux fonctionne cela me met un message d’erreur « Routemissing »

Merci par avance

**Comment by tibouh** [comment]
Je confirme, j'ai aussi le message "unable to import route module: resources.lib.main" qui apparait dans la popup d'erreur.
J'ai tenté la réinstall IPTV Manager, IPTV Simple Client et Catchup-tv mais rien n'y fait.
Je ne sais pas si c'est lié, mais le problème est apparu après la màj CoreElec v20.1 -> v20.2.

**Comment by darodi** [comment]
@Laurag02 @tibouh 
logs?

**Comment by EnderEOC** [comment]
Comme vu dans un autre topic il faut dl ici http://mirrors.kodi.tv/addons/matrix/script.module.requests/script.module.requests-2.27.1+matrix.1.zip et remplacer dans les addons kodi
Il semble que la version 2.31 pose problème.
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1169#issuecomment-1625616724

**Comment by Cecilebub** [comment]
On fait comment (par où on passe) pour télécharger et installer ça sur une Box Android svp ?

**Comment by EnderEOC** [comment]
> On fait comment (par où on passe) pour télécharger et installer ça sur une Box Android svp ?

Le plus simple je pense c'est de télécharger le fichier sur une clé usb et dans kodi de faire installer à partir d'un fichier zip.
Ensuite pense bien à bloquer l'auto update de l'extension "requests"

**Comment by Spanish93** [comment]
Pas besoin de downgrader request, il faut plutot mettre à jour codequick.
J'ai mis à jour le plugin et testé (même modification que SecTOuch) et cela fonctionne.

Lien vers le plugin mis à jour 👍
https://we.tl/t-jAUq5KezpK

Le télécharger puis faire installer une extension depuis un fichier zip dans kodi (j'utilise send file to tv pour le transfert)

**Comment by Cecilebub** [comment]
> > On fait comment (par où on passe) pour télécharger et installer ça sur une Box Android svp ?
> 
> Le plus simple je pense c'est de télécharger le fichier sur une clé usb et dans kodi de faire installer à partir d'un fichier zip. Ensuite pense bien à bloquer l'auto update de l'extension "requests"

Ça a marché merci beaucoup !!

**Comment by manu8870** [comment]
Bonjour,j'ai donc mis le fichier sur une clé USB et quand je vais sur Kodi et ajouter depuis un zip, Kodi ne voit pas ma clé 😜

**Comment by JorgeMartinez2** [comment]
Ça a marché pour moi aussi. J'avais le meme probleme. Merci beaucoup.

**Comment by Cecilebub** [comment]
> Bonjour,j'ai donc mis le fichier sur une clé USB et quand je vais sur Kodi et ajouter 

J'ai vu sur un autre post une personne qui avait le même problème et a trouvé la solution apparemment. 

https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1169#issuecomment-1627153989

**Comment by darodi** [comment]
- Duplicate #1169
solution temporaire en attendant la mise à jour officielle dans le dépôt Kodi

https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1169#issuecomment-1631229816

**Comment by darodi** [comment]
@joaopa00 
peut être fermé
duplicate

**Comment by manu8870** [comment]
> Ça a marché pour moi aussi. J'avais le meme probleme. Merci beaucoup. J'ai une Xiomi Mi TV Box et j'ai utilizé Downloader pour télécharger le fichier http://mirrors.kodi.tv/addons/matrix/script.module.requests/script.module.requests-2.27.1+matrix.1.zip.

Salut, c'est quoi downloader? Je suis sur Chromecast.

**Comment by darodi** [comment]
@manu8870 
ceci ne fonctionne pas?

https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1169#issuecomment-1631342332

**Comment by joaopa00** [comment]
Résolu par une mise à jour de codequick.
