### ISSUE TITLE
unable to import route module

### ISSUE THREAD

**Issue by khalistoo** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1169]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
Hi, I am not able to use CUTVM anymore. Error message is saying Route Missing
I've tried beta 26 up until beta 28 and tried re installing IPTV Manager
I am facing this issue on both Ubuntu and Android, kodi build 20.0.0 

Salut, j ai un message d'erreur a chaque fois que j'essaye de lancer CUTVM: Route Missing 
J ai essaye les différentes beta 26 jusqu a 28, j ai essaye de re installer IPTV Manager rien n'y fait toujours le meme message.
J'ai regarde quelques tickets precedents mais je n'ai rien trouve comme solution dans les precedents threads pour 'unable to import route module: resources.lib.main'.
J ai le meme soucis sous ubuntu et android kodi build 20.0.0  

### Debug log
2023-07-07 00:16:52.190 T:352     error <general>: [Catch-up-TV-&-More.support] 'unable to import route module: resources.lib.main'
                                                   Traceback (most recent call last):
                                                     File "/home/khalistoo/.var/app/tv.kodi.Kodi/data/addons/script.module.codequick/lib/codequick/support.py", line 248, in get_route
                                                       importlib.import_module(module_path)
                                                     File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
                                                       return _bootstrap._gcd_import(name[level:], package, level)
                                                     File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
                                                     File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 883, in exec_module
                                                     File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
                                                     File "/home/khalistoo/.var/app/tv.kodi.Kodi/data/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 13, in <module>
                                                       import urlquick
                                                     File "/home/khalistoo/.var/app/tv.kodi.Kodi/data/addons/script.module.codequick/lib/urlquick.py", line 63, in <module>
                                                       from requests.adapters import HTTPResponse
                                                   ImportError: cannot import name 'HTTPResponse' from 'requests.adapters' (/home/khalistoo/.var/app/tv.kodi.Kodi/data/addons/script.module.requests/lib/requests/adapters.py)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/khalistoo/.var/app/tv.kodi.Kodi/data/addons/script.module.codequick/lib/codequick/support.py", line 300, in run_callback
                                                       route = self.get_route(self.selector)
                                                     File "/home/khalistoo/.var/app/tv.kodi.Kodi/data/addons/script.module.codequick/lib/codequick/support.py", line 250, in get_route
                                                       raise RouteMissing("unable to import route module: %s" % module_path)
                                                   codequick.support.RouteMissing: 'unable to import route module: resources.lib.main'
2023-07-07 00:16:52.191 T:352     error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'HTTPResponse' from 'requests.adapters' (/home/khalistoo/.var/app/tv.kodi.Kodi/data/addons/script.module.requests/lib/requests/adapters.py)
                                                   Traceback (most recent call last):
                                                     File "/home/khalistoo/.var/app/tv.kodi.Kodi/data/addons/plugin.video.catchuptvandmore/addon.py", line 23, in <module>
                                                       main()
                                                     File "/home/khalistoo/.var/app/tv.kodi.Kodi/data/addons/plugin.video.catchuptvandmore/addon.py", line 18, in main
                                                       main = importlib.import_module('resources.lib.main')
                                                     File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
                                                       return _bootstrap._gcd_import(name[level:], package, level)
                                                     File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
                                                     File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 883, in exec_module
                                                     File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
                                                     File "/home/khalistoo/.var/app/tv.kodi.Kodi/data/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 13, in <module>
                                                       import urlquick
                                                     File "/home/khalistoo/.var/app/tv.kodi.Kodi/data/addons/script.module.codequick/lib/urlquick.py", line 63, in <module>
                                                       from requests.adapters import HTTPResponse
                                                   ImportError: cannot import name 'HTTPResponse' from 'requests.adapters' (/home/khalistoo/.var/app/tv.kodi.Kodi/data/addons/script.module.requests/lib/requests/adapters.py)
                                                   -->End of Python script error report<--

**Comment by khalistoo** [comment]
possible duplicate https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1168

**Comment by wilfarte** [comment]
même comportement ce matin suite à des mises à jour notamment CodeQuick, urllib3 ...

**Comment by wilfarte** [comment]
En me basant sur les derniers packages mis à jour, j'ai téléchargé le package requests-2.27.1+matrix.1 en format ZIP et je l'ai installé. Tout est fonctionnel.
La version 2.30 semble poser problème

**Comment by Nectoux68800** [comment]
Bonjour, Ou avez vous téléchargé le package requests-2.27.1 dont vous parlez? cordialement

**Comment by chocho13** [comment]
ici : http://mirrors.kodi.tv/addons/matrix/script.module.requests/

**Comment by khalistoo** [comment]
Je confirme, le package http://mirrors.kodi.tv/addons/matrix/script.module.requests/script.module.requests-2.27.1+matrix.1.zip permet de regler le soucis. A voir s'il passera sur la 31 automatiquement ou nous.

For english readers:
The following package fixes the issues request issue http://mirrors.kodi.tv/addons/matrix/script.module.requests/script.module.requests-2.27.1+matrix.1.zip.

**Comment by Custardpowder** [comment]
Make sure auto updates on python are turned off as mine has stopped working twice after about 45 mins of installing the above

**Comment by Cecilebub** [comment]
> Merci @wilfarte et @chocho13
> 
> Je confirme, le package http://mirrors.kodi.tv/addons/matrix/script.module.requests/script.module.requests-2.27.1+matrix.1.zip permet de regler le soucis. A voir s'il passera sur la 31 automatiquement ou non.
> 
> For english readers: The following package fixes the request issues http://mirrors.kodi.tv/addons/matrix/script.module.requests/script.module.requests-2.27.1+matrix.1.zip.



> En me basant sur les derniers packages mis à jour, j'ai téléchargé le package requests-2.27.1+matrix.1 en format ZIP et je l'ai installé. Tout est fonctionnel. La version 2.31 semble poser problème

Excusez moi mais depuis une Bow Android il faut passer par où pour télécharger ça svp ?

**Comment by Cecilebub** [comment]
Excusez moi mais est-ce que quelqu'un peut m'expliquer comment on télécharge ça (par où il faut passer) avec une Box Android svp ? Est-ce qu'il faut aller dans la gestion des fichiers et ajouter une source de fichiers ?
Merci pour votre aide !

**Comment by khalistoo** [comment]
Pour la box Android, 

je telecharge le fichier sur mon ordi, je l'upload sur mon google drive. 
Depuis la box, Je me connecte au google drive en utilisant n'importe quelle app de transfert genre:
[File Commander](https://play.google.com/store/apps/details?id=com.mobisystems.fileman) 
[X-plore File Manager](https://play.google.com/store/apps/details?id=com.lonelycatgames.Xplore 
Je telecharge le fichier sur ma box. 

Ou alors si t'as un port disponible sur la box, tu passes par une clef USB 

Ensuite dans Kodi, je vais dans System > Add-ons > Install from zip file et la je cherche le fichier.. Et voila.

**Comment by joaopa00** [comment]
Le patch qui pose problème  dans a ib requests est:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>


  | Use urllib3 native chunking ability (#6226)
-- | --
Committer | GitHub<noreply@github.com>
Author | Levi<shadycuz@gmail.com>
Author date | 22/04/2023 13:32
Parent | Allow str/bytes subclasses to be used as header parts
Child | pin cryptography<40 on pypy 3.7 (#6421)
Branch | main (Add an Example for automatic retries to the Advanced Usag...)
Branch | origin/main (Add an Example for automatic retries to the Advanced Usag...)
Follows | v2.28.2 (v2.28.2)
Precedes | v2.29.0 (v2.29.0)


<pre style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:'Hack'; font-size:10pt;"><br /></pre>
<pre style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:'Hack'; font-size:10pt;">    Use urllib3 native chunking ability (#6226)</span></pre>
<pre style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:'Hack'; font-size:10pt;">    </span></pre>
<pre style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:'Hack'; font-size:10pt;">    * Fix #3844 </span></pre>
<pre style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:'Hack'; font-size:10pt;">    * Use urllib for chunked </span></pre>
<pre style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:'Hack'; font-size:10pt;">    </span></pre>
<pre style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:'Hack'; font-size:10pt;">    ---------</span></pre>
<pre style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:'Hack'; font-size:10pt;">    </span></pre>
<pre style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:'Hack'; font-size:10pt;">    Co-authored-by: James Pickering &lt;james.pickering@xml-solutions.com&gt;</span></pre>
<pre style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:'Hack'; font-size:10pt;">    Co-authored-by: Leon Verrall &lt;LVerrall@slb.com&gt;</span></pre></body></html>Use urllib3 native chunking ability (#6226)
Committer
GitHub<noreply@github.com>
Author
Levi<shadycuz@gmail.com>
Author date
22/04/2023 13:32
Parent
[Allow str/bytes subclasses to be used as header parts](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/7f694b79e114c06fac5ec06019cada5a61e5570f)
Child
[pin cryptography<40 on pypy 3.7 (#6421)](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/dfc3e2433836813fe6b93b8e182a761aa6c0ee05)
Branch
main ([Add an Example for automatic retries to the Advanced Usag...](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/cdbc2e271529f467b278b2760f12ee0b5d6930d3)) 
Branch
origin/main ([Add an Example for automatic retries to the Advanced Usag...](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/cdbc2e271529f467b278b2760f12ee0b5d6930d3)) 
Follows
v2.28.2 ([v2.28.2](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/61c324da43dd8b775d3930d76265538b3ca27bc1))
Precedes
v2.29.0 ([v2.29.0](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/87d63de8739263bbe17034fba2285c79780da7e8))


    Use urllib3 native chunking ability (#6226)
    
    * Fix #3844 
    * Use urllib for chunked 
    
    ---------
    
    Co-authored-by: James Pickering <james.pickering@xml-solutions.com>
    Co-authored-by: Leon Verrall <LVerrall@slb.com>

sha:26bea1e498d6e234fbc9ce8e07c0389bac73810b



**Mais l'énorme probème est que ce patch est correct:**

Le problème original provient de la librairie URLQUICK qui importe une fonction interne à ce fichier qui a été retirée par ce patch. C'est de très mauvaise pratique de programmation de faire cela. La peuve

ET une merde n'arrivant jamais seule, URLQUICK semble être abandonnée.

**Comment by Cecilebub** [comment]
> Pour la box Android,
> 
> je telecharge le fichier sur mon ordi, je l'upload sur mon google drive. Depuis la box, Je me connecte au google drive en utilisant n'importe quelle app de transfert genre: [File Commander](https://play.google.com/store/apps/details?id=com.mobisystems.fileman) [X-plore File Manager](https://play.google.com/store/apps/details?id=com.lonelycatgames.Xplore) Je telecharge le fichier sur ma box.
> 
> Ou alors si t'as un port disponible sur la box, tu passes par une clef USB
> 
> Ensuite dans Kodi, je vais dans System > Add-ons > Install from zip file et la je cherche le fichier.. Et voila.

Merci beaucoup je vais essayer comme ça 😊

**Comment by SecT0uch** [comment]
I found a fix without downgrading the requests module:
Remove the line 63 (`from requests.adapters import HTTPResponse`) in `/storage/.kodi/addons/script.module.codequick/lib/urlquick.py`

I've just submited PRs upstream:
- urlquick module: https://github.com/willforde/urlquick/pull/118
- codequick kodi addon (embeds `codequick.py`): https://github.com/willforde/script.module.codequick/pull/53

**Comment by Spanish93** [comment]
En effet, pas besoin de downgrader request, il faut plutot mettre à jour codequick.
J'ai mis à jour le plugin et testé (même modification que SecTOuch) et cela fonctionne.

Lien vers le plugin mis à jour 👍 
https://we.tl/t-jAUq5KezpK

Le télécharger puis faire installer une extension depuis un fichier zip dans kodi (j'utilise send file to tv pour le transfert)

**Comment by Cecilebub** [comment]
> Pour la box Android,
> 
> je telecharge le fichier sur mon ordi, je l'upload sur mon google drive. Depuis la box, Je me connecte au google drive en utilisant n'importe quelle app de transfert genre: [File Commander](https://play.google.com/store/apps/details?id=com.mobisystems.fileman) [X-plore File Manager](https://play.google.com/store/apps/details?id=com.lonelycatgames.Xplore) Je telecharge le fichier sur ma box.
> 
> Ou alors si t'as un port disponible sur la box, tu passes par une clef USB
> 
> Ensuite dans Kodi, je vais dans System > Add-ons > Install from zip file et la je cherche le fichier.. Et voila.

J'ai chargé sur une clé USB. Ensuite je suis allée dans Système-> Extensions -> Gérer les dépendances (je sais pas si c'est là qu'il faut aller !) -> Installer d'un fichier Zip -> Stockage externe et là.... aucun fichier zip !!! Je comprends rien...

**Comment by Cecilebub** [comment]
> Pour la box Android,
> 
> je telecharge le fichier sur mon ordi, je l'upload sur mon google drive. Depuis la box, Je me connecte au google drive en utilisant n'importe quelle app de transfert genre: [File Commander](https://play.google.com/store/apps/details?id=com.mobisystems.fileman) [X-plore File Manager](https://play.google.com/store/apps/details?id=com.lonelycatgames.Xplore) Je telecharge le fichier sur ma box.
> 
> Ou alors si t'as un port disponible sur la box, tu passes par une clef USB
> 
> Ensuite dans Kodi, je vais dans System > Add-ons > Install from zip file et la je cherche le fichier.. Et voila.

Super ça a marché j'y suis arrivée !! Merci beaucoup 😊

**Comment by Shasdo** [comment]
Le fichier zip n'est pas visible par Kodi quand je navigue dans le dossier.
J'ai essayé via clé USB ou en téléchargement direct sur la box Android via un utilitaire de dl.

Je rate un truc, mais quoi ?

Merci

**Comment by khalistoo** [comment]
Good work @SecT0uch , but as @joaopa00 mentioned earlier this am,  Urlquick seems to be abandoned, or at least no changes made since 2021 hence the downgrading option. 

Either that or pulling the file from @Spanish93 's we transfert (not ideal for long term). That won't solve the root issue until your PRs are merged which seems sadly unlikely.

Final option would be to clone Urlquick and update with your changes, but i am not too familiar on how to specify your new source instead of the current existing one.

**Comment by SecT0uch** [comment]
[willforde](https://github.com/willforde) (urlquick dev) was active this month, he may be able to merge a PR when he sees it.
If no reaction from him, I will try to submit a PR directly to https://github.com/xbmc/repo-scripts, but I don't have time or will to become the package maintainer.

An other solution would be to stop using urlquick and codequick as dependencies and replace them

**Comment by joaopa00** [comment]
>An other solution would be to stop using urlquick and codequick as dependencies and replace them

Would be a huge task.

**Comment by QuentinLf** [comment]
Bonjour,

J'ai le même problème (je suis sur Androïd TV), donc j'ai tout désinstallé puis réinstallé Kodi et Catch-up Tv. J'ai téléchargé le fichier donné par @SecT0uch mis sur une clé usb. Dans Kodi je suis allé dans System > Add-ons > Install from zip file. J'ai eu la pop-up qui indique que l'installation a réussie.

Mais quand je veux lancer un programme en replay ou en direct, rien ne se lance. Normalement il y a le petit cercle bleu qui tourne puis la vidéo se lance. Ici j'appuie sur Ok puis rien ne se passe (pas de petit cercle bleu ni de vidéo). 

Comment régler ce problème?

Merci

**Comment by Spanish93** [comment]
> [willforde](https://github.com/willforde) (urlquick dev) was active this month, he may be able to merge a PR when he sees it. If no reaction from him, I will try to submit a PR directly to https://github.com/xbmc/repo-scripts, but I don't have time or will to become the package maintainer.
> 
> An other solution would be to stop using urlquick and codequick as dependencies and replace them

PR have been merged 👍

**Comment by joaopa00** [comment]
@SecTouch. To avoid such a problem in the future, can you PR to urlquick and codequick to remove all the imports of private libraries: 

from requests.structures import CaseInsensitiveDict
from requests import adapters
from requests import *


should be useless

**Comment by Spanish93** [comment]
Pour le moment il faut appliquer le patch manuellement.

Cependant un merge request a été fait auprès de Kodi pour mettre à jour officiellement codequick.

https://github.com/xbmc/repo-scripts/pull/2484/

Donc si tout va bien d'ici quelques jours, le correctif sera disponible officiellement

**Comment by darodi** [comment]
En attendant, voilà la dernière version de codequick mise à jour le 11/07/2023
https://github.com/willforde/script.module.codequick/releases/download/v1.0.3/script.module.codequick-1.0.3+matrix.1.zip

pour installer 
- settings
- addons 
- install from zip file
- choisir le fichier

**Comment by Spanish93** [comment]
Oui bon à part le lien sur github ça ne change rien par rapport au lien que j'ai publié il y a quelques jours.

Donc ceux qui n'ont pas réussi avec le zip précédemment n'arriveront pas mieux en le téléchargeant ailleurs ...

Pour eux la seule solution reste d'attendre la mise a disposition officielle sur le repo Kodi

**Comment by darodi** [comment]
@joaopa00 

un ajout dans
https://github.com/Catch-up-TV-and-More/repository.catchuptvandmore
en attendant?

**Comment by darodi** [comment]
@Spanish93 
En attendant, j'ai créé une source temporaire pour ceux qui ne peuvent installer un zip local

- "Settings" --> "File manager" --> "Add source"
- Fill in the repository URL: https://darodi.github.io/repo/
- Fill in the source name: codequickrepo
- Click "OK"
- Go back to the settings root menu --> "System settings" --> Tab "Add-ons"
- Enable "Unknown sources" and click "Yes" during the warning dialog box
- Go back to the Kodi home menu --> Enter in tab "Add-ons"
- Enter the "Package Installer" icon in the top left corner
- "Install from zip file" --> codequickrepo --> script.module.codequick-1.0.3+matrix.1.zip

**Comment by Cecilebub** [comment]
Depuis que j'ai installé le patch et désactivé la mise à jour auto de requests (Python), Kodi m'indique une mise à en attente. Je suppose que c'est Requests mais je n'en suis pas sûre et comment savoir si c'est la dispo officielle de Kodi car si je réactive la maj auto, je risque de flinguer le patch. Est-ce que ça fait pareil à quelqu'un qui a installé le patch ??

**Comment by Spanish93** [comment]
Si le "patch" est le zip qui permet de mettre à jour codequick, alors pas besoin de bloquer la mise à jour de request.

**Comment by Cecilebub** [comment]
> Si le "patch" est le zip qui permet de mettre à jour codequick, alors pas besoin de bloquer la mise à jour de request.

Je ne pense pas... j'ai appliqué le patch suivant http://mirrors.kodi.tv/addons/matrix/script.module.requests/script.module.requests-2.27.1+matrix.1.zip

**Comment by Spanish93** [comment]
Ah oui dans ce cas pour le moment il faut laisser la MAJ automatique désactivée.

Dans quelques jours, codequick devrait être disponible pour mise à jour automatique

**Comment by darodi** [comment]
@Cecilebub 

Tu peux tout mettre à jour et installer
`script.module.codequick-1.0.3+matrix.1.zip`

cf. 
- https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1169#issuecomment-1631342332
- https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1169#issuecomment-1631229816

**Comment by Cecilebub** [comment]
> Ah oui dans ce cas pour le moment il faut laisser la MAJ automatique désactivée.
> 
> Dans quelques jours, codequick devrait être disponible pour mise à jour automatique

Merci beaucoup pour votre aide 😊

**Comment by CChalu** [comment]
Bonjour,
J’ai mis à jour codequick à l’aide du message utilisant le dépôt beta de catchup TV : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1169#issuecomment-1631342332 (merci pour cette initiative qui facilite la vie avec le Chromecast)
Lorsque Kodi sera mis à jour, est-ce que l’addon codequick re basculera automatiquement sur le dépôt officiel de kodi ou alors il y aura une manip à faire ?
Merci

**Comment by thedude4ever** [comment]
Bonjour, j'ai cette erreur "unable to import module : ressources.lib.main" quand je lance CUTVM.
J'ai pourtant la bonne version de codequick 1.0.3+matrix.1
Cela marchait très bien jusqu'à il y a 1 mois environ.
Est-ce qu'il faut mettre à jour un autre composant ?
Merci
