### ISSUE TITLE
Kodi 18 RC 3 - Issue with the settings / Problèmes avec les configurations

### ISSUE THREAD

**Issue by wwark** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#117]
![screenshot from 2018-12-22 15-35-06](https://user-images.githubusercontent.com/469461/50375636-f1529a80-0600-11e9-936b-00689cc4cb65.png)
![screenshot from 2018-12-22 15-27-09](https://user-images.githubusercontent.com/469461/50375637-f1eb3100-0600-11e9-9fbe-2ee7183eb04e.png)
![screenshot from 2018-12-22 15-27-12](https://user-images.githubusercontent.com/469461/50375638-f1eb3100-0600-11e9-9397-36ee1b95b00b.png)

Certains settings ne sont plus visibles / Some settings are not visible.

Un work-around a été commité ici en attendant un changement (https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/af8622388c9ac5b4df3eb3ea3b74732a2c2bbea5)

Merci,
Wwark.

**Comment by SylvainCecchetto** [comment]
Ce bug a été fixé ici https://github.com/xbmc/xbmc/pull/16773 mais le fix n'est pas backporté sur Kodi 18.
Kodi 18 sera donc (normalement) impacté par ce bug pour toujours.
Nous devons donc garder ton work-around pour le moment wwark.

**Comment by SylvainCecchetto** [comment]
Fixed by https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/eb4a6bb381645d67b0b5059dde8a9d554b4ecc5a
Will be available v0.2.17
