### ISSUE TITLE
Erreur lors de l'installation de la version stable sur Xbox one

### ISSUE THREAD

**Issue by BoobooOOS** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1170]
Bonjour, je me permets de poster car je n'ai pas trouvé la solution parmi les post déjà existants, en espérant que qqun pourra m'aider, merci 

### Describe the bug
A clear and concise description of what the bug is: tout se passe normalement lors de l'installation, sauf qu'on ne me propose pas "catch up tv and more Krypton release repository" au moment du dépôt mais juste "catch up tv and more release repository", mais après quand j'essaye de lancer n'importe quelle chaine ou programme, ça me met le message d'erreur "impossible de se connecter au dépôt"

### To Reproduce
Steps to reproduce the behaviour:
1.Installer la version stable en suivant les étapes décrites sur le site "justgeek"
2.lancer n'importe quelle chaine depuis catch up tv and more
3.
4.

### Expected behaviour
A clear and concise description of what you expected to happen: que le programme se lance

### Actual behaviour
Tell us what happens instead: message d'erreur "impossible de se connecter au dépôt"

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
Je suis sur une Xbox one, téléchargé Kodi depuis le store
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 20.2.0.70
 - Catch-up TV & More version: pas sure de savoir où trouver ça, dans les paramètres de l'extension j'ai ça dans l'onglet versions : Version 0.2.38+matrix.1
 - Installation method: installation de KODI via le store Xbox, puis j'ai suivi les étapes listées sur le site "justgeek"

### Additional context
Add any other context about the problem here: en voyant que ça ne marchait pas, j'ai tenté d'installer la version beta à la place, mais pas mieux d'autres bug, j'ai eu "route missing" donc j'ai suivi les étapes et j'ai téléchargé le fichier ZIP, ça a réglé ce message d'erreur mais après en essayant de voir n'importe quel programme, live ou replay, j'avais un nouveau message d'erreur me disant "la version windows store de kodi ne prend pas en charge widevine CDM" ... donc là j'ai abandonné !

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy): désolée mais ce tuto ne semble pas être fait pour les xbox et comme je suis totalement nulle je ne sais pas comment faire sans tuto

Voilà désolée pour le pavé et le manque d'info techniques par moment, si jamais une personne voit un début de piste pour mes problèmes, un énorme MERCI par avance

Bonne journée

**Comment by darodi** [comment]
procédure d'installation ici

https://catch-up-tv-and-more.github.io/fr/installation/#ii-ajouter-le-d%C3%A9p%C3%B4t-officiel-de-catch-up-tv--more

**Comment by darodi** [comment]
@BoobooOOS 
+ ceci:
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1169#issuecomment-1631342332

**Comment by BoobooOOS** [comment]
> procédure d'installation ici
> 
> https://catch-up-tv-and-more.github.io/fr/installation/#ii-ajouter-le-d%C3%A9p%C3%B4t-officiel-de-catch-up-tv--more

Bonjour, merci d'avoir pris le temps de me répondre, j'ai vérifié ce lien, c'est bien la même procédure que j'ai suivi pour installer KODI, merci aussi pour le lien du comm sur un autre sujet, dans le coup est-ce qu'il vaut mieux que j'essaye de faire la procédure "manuelle" ou est-ce que j'essaye de télécharger et installer le fichier zip proposé un peu plus haut dans le sujet "codequick updated 11/07/2023
https://github.com/willforde/script.module.codequick/releases/download/v1.0.3/script.module.codequick-1.0.3+matrix.1.zip" est-ce différent par rapport aux 2 fichiers ZIP que j'ai testé ? car l'un d'eux s'appelle pareil codequick 1.0.3 et ça n'a pas changé le message d'erreur que j'ai, mais peut-être que je ne comprends pas et qu'en faisant la manip en comm #1169 pour installer manuellement ça fonctionnera mieux ?

MErci en tout cas pour l'aide

**Comment by BoobooOOS** [comment]
Remoi !

Je viens de suivre la procédure indiquée pour installer le patch manuellement comm #1169 tout a bien fonctionné, tout s'est bien installé aucun message d'erreur, mais dès que j'essaye de regarder un replay ou un direct de n'importe quelle chaine française j'ai de nouveau le même message d'erreur " La version Windows Store de KODI ne prend pas en charge Widevine CDM. Veuillez utiliser le programme d'installation de kodi.tv à la place" .... je ne comprends pas trop ce que ça veut dire car je ne peux qu'installer KODI via le microsoft store sur ma Xbox non ?

Encore merci si qqun a une idée sur ce bug ? J'ai vu des messages de personnes qui arrivaient à regarder la tv sur leur console via KODI donc je pensais que c'était possible ...

**Comment by darodi** [comment]
> je ne comprends pas trop ce que ça veut dire car je ne peux qu'installer KODI via le microsoft store sur ma Xbox non ?

La version windows peut être installée via le microsoft store ou via l’exécutable.
Le message d'erreur est générique je pense.
La version xbox ne supporte pas widevine:
https://www.matthuisman.nz/2018/05/kodi-widevine-support.html

**Comment by BoobooOOS** [comment]
Merci pour l'article, dans le coup je peux essayer de réinstaller KODI via .exe si j'ai bien compris, mais le problème c'est que, je m'excuse par avance si c'est idiot mais pour l'installer via l'exécutable, ce n'est pas en allant sur le site pour télécharger un fichier et en le lançant par la suite via .exe, or j'avoue ne pas du tout savoir comment faire cela sur ma xbox, j'avais tenté de télécharger directement un fichier via un site sur Edge (seul navigateur présent sur xbox) mais le téléchargement ne se lançait jamais et je n'ai pas accès à ma liste de téléchargements comme sur ordi ...

**Comment by darodi** [comment]
Je ne pense pas qu'on peut installer un exe sur la xbox. 
Uniquement la version du microsoft store

**Comment by BoobooOOS** [comment]
Ah ok, comme c'était mentionné j'ai cru que ça pouvait être une solution à ce bug, bon j'imagine donc que pour le moment il n'y a rien à faire pour que catch up tv fonctionne sur notre console. Merci quand même d'avoir essayé

**Comment by darodi** [comment]
@BoobooOOS 
https://forum.kodi.tv/showthread.php?tid=349961&pid=2907271#pid2907271
>Inputstream is a binary add-on.
UWP runs in a sandbox & won't run external dll's for security purposes.
So the add-on needs to be included with the build for it to work.

>This is also the main reason Widevine DRM won't playback.
That needs to use a widevinecdm.dll which can't be included in kodi due to licensing. 

Bref, ce n'est pas vraiment lié à CUTVM

@joaopa00 
Je pense qu'on peut fermer cette issue
