### ISSUE TITLE
Catch-up tv ne fonctionne plus

### ISSUE THREAD

**Issue by Ricbla614** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1171]
### Content description

* Name:
* Type [e.g. TV channel, Catch-up TV, Website, Radio]:
* Website URL:
* Content language/country:

### Content access

- [x] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [ ] This content is geographically restricted

### More information

If you want to add more information, put it here:

**Comment by Ricbla614** [comment]
J'uiitilse l'url dans le répertoire de  Kodi, je suis avec Kodi Nexus 20.2 sur un appareil de type android. Lorsque j'essaie de me connecter je reçois le message suivant : Route manquante avec l'information suivante : Ressouces. lib.main

**Comment by darodi** [comment]
@Ricbla614 
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1169#issuecomment-1631342332
