### ISSUE TITLE
Erreur : enable to import route module : ressources.lib.main

### ISSUE THREAD

**Issue by crocketear** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1172]
Bonjour, 
Voici l'erreur que j'obtiens au lancement de CatchUpTV&More, même après désinstallation/ réinstallation du module : 
 enable to import route module : ressources.lib.main

Merci de votre aide

**Comment by darodi** [comment]
@crocketear 

- Duplicate #1169 

Comme spécifié dans la création d'une issue/d'un ticket, regarder s'il n'existe pas déjà une issue/un ticket pour le même problème

> ⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️


https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1169#issuecomment-1631342332

**Comment by darodi** [comment]
@joaopa00 @crocketear 

peut être fermé
