### ISSUE TITLE
Problem: LIVE TV

### ISSUE THREAD

**Issue by smellycat45** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1173]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
TV LIVE guide/epg won't show up using IPTV Simple Client.
I'm using the last beta version of CUPTV

### Your environment
 - Operating system version/name: Android TV (MIBOX)
 - Kodi version: MATRIX
 - Catch-up TV & More version: beta
 - Installation method:

**Comment by darodi** [comment]
- Duplicate https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1140

**Comment by willow3411** [comment]
Bonjour,
je me permet de reposter ici pour regrouper le post.
j'ai le meme soucis avec message d'erreur : connexion perdu...
je pense que cela est lier aux nouvelles mises à jours et les differents patchs.
mais bon je suis pas spécialiste :)
belle journée

**Comment by willow3411** [comment]
bonjour,
toujours le meme bug depuis les mise à jour.
la passerelle entre ip tv manager et catch up TV ne fonctionne plus.
connexion perdu.
merci d'avance
willow

**Comment by calvin4242** [comment]
Bonjour, même pb après nouvelle install du systeme.

**Comment by calvin4242** [comment]
Bonjour, j'ai fixé le pb.

**Concernant le message IPTV manager "connexion perdue":**
Il faut editer le fichier "addon.py" qui se trouve dans "addons/service.iptv.manager/resources/lib/modules/addon.py" de Kodi.

CHERCHER:
Ligne 254

CHANGER:
def _wait_for_data(self, sock, timeout=10):

EN:
def _wait_for_data(self, sock, timeout=None):

**Concernant le problème d'affichage de l'EPG:**
En fait j'ai essayé l'extension Pluto TV et l'EPG des chaines s'affiche correctement.
Donc il s'agit bien d'un problème EPG qui ne s'affiche pas concernant Catchup TV-IPTV Manager-IPTV simple client. 

Voici ce que j'ai fait:  

1. Activation de l'affichage des dossiers/fichiers cachés dans kodi: 
Kodi > Paramètres > Médiatheque > General > Afficher les dossiers et les fichiers cachés.

2.Définir manuellement le fichier de la liste des chaines m3u8 et le fichier EPG xml.
Kodi  > Paramètres > Extensions > Clients Enregistreur Vidéo > IPTV Simple client > Configurer > Editer "Migrated Addons" > 

Onglet "Général" :
-Sur la ligne "Emplacement", choisir "Chemin local"
-En dessous, cliquer sur "Chemin de la liste de lecture M3U" et aller à : 
"Dossier personnel \ .kodi \ userdata \ addon_data \ service.iptv.manager  
-Selectionner "playlist.m3u8"

Onglet "Guide electronique des programmes" :
-Sur la ligne "Emplacement", choisir "Chemin local"
-En dessous, cliquer sur "Chemin XMLTV" et aller à : 
 "Dossier personnel \ .kodi \ userdata \ addon_data \ service.iptv.manager 
-Selectionner "epg.xml"

**Comment by joaopa00** [comment]
Prolblème d'IPTVSIMPLE
[problème rapporté à IPTVSIMPLE](https://github.com/add-ons/service.iptv.manager/issues/107)

**Comment by ChristopherLF30** [comment]
Bonjour à tous. 
J'ai bien suivi la procédure si dessus mais je n'arrive pas à accéder aux dossier personnel.kodi. 
Sachant que j'ai bien activé l'option d'affichage des dossiers et fichiers cachés et que je peux accéder à ce dossier via les paramètre kodi. 
Avez-vous une idée svp ?

**Comment by calvin4242** [comment]
j'ai mis à jour la partie 2 au dessus merci de réessayer pour voir

**Comment by ChristopherLF30** [comment]
Merci beaucoup pour ce retour. 

Malheureusement même problème, je n’ai pas accès à « Dossier personnel ».

**Comment by ChristopherLF30** [comment]
Je ne comprends pas d’où vient le soucis. J’ai bien accès au dossier Master profil depuis les réglages général de kodi via la gestion des dossiers mais impossible d’y accéder depuis l’addon.

**Comment by calvin4242** [comment]
votre kodi est installé sous quel OS? android, windows,..?

**Comment by ChristopherLF30** [comment]
Sur Nvidia Shield sous android. Le tout aux dernières MAJ.

**Comment by calvin4242** [comment]
/internal/Android/data/org.xbmc.kodi/files/.kodi/userdata
essayez de trouver le dossier internal ou android ou data du chemin ci dessus pour aller jusqu'a .kodi/userdata

**Comment by ChristopherLF30** [comment]
J’ai essayé mais impossible de trouver depuis IPTV manager. J’ai tout passé en revu vraiment ça me dépasse.

**Comment by calvin4242** [comment]
la procedure sur laquelle je vous suis est sur IPTV Simple client et non iptv manager.
Concernant la modification des fichiers sur iptv manager il est fortement conseillé d'editer les fichiers depuis un pc connecté au reseau local pour avoir un pont avec le nvidia shield (à l'aide du protocole SAMBA à activer dans KODI).

**Comment by ChristopherLF30** [comment]
Oui pardon c'est bien IPTV simple erreur de ma part.

**Comment by calvin4242** [comment]
apparement il y un pb de MAJ concernant l'explorateur de fichiers sur nvidia shield ou kodi on ne sait pas trop c'est du ping pong. il y a un fix/ MAJ nvidia en 9.1.2 mais il parait que le support est dead.
essayez de voir  sur shield ceci:  Apps/Special app access/.... "Enable write access to mounted NAS for selected apps." Set Kodi to Allowed.   Je passe la main je ne connais pas shield, cordialement

**Comment by ChristopherLF30** [comment]
D’accord pas de soucis, merci beaucoup en tout cas pour le temps alloué à mon problème.
