### ISSUE TITLE
Replay 6 Play ne fonctionne plus error 403

### ISSUE THREAD

**Issue by Almeyric** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1175]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

Depuis un mois, le replay ne fonctionne plus. Erreur 403
J'ai essayé avec deux comptes fonctionnelles en web. Rien ne change. 

Les autres replay comme tf1 et france tv fonctionnent.

### Your environment
 - [x] Windows
 

 - Operating system version/name: 11 22H2 
 - Kodi version: 20.1
 - Catch-up TV & More version: 0.2.39 beta 28
 - Installation method: REPO

### Debug log

[kodi.old.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/12083437/kodi.old.log)

**Comment by joaopa00** [comment]
J'ai essayé les taîtres saison 2 Episode 1 pas de problème. Quel est le programme qui pose problème?

**Comment by Almeyric** [comment]
J'ai accès à aucune chaine. Le groupe de chaine s'affiche. Et lorsque l'on choisit la chaine error 403.
Je viens de m'apercevoir que le log que j'ai mis ne contient pas l'erreur :/

**Comment by Almeyric** [comment]
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/12091952/kodi.log)

**Comment by joaopa00** [comment]
Utillises-tu un vpn?

**Comment by Jaunattend** [comment]
Bonjour, j'ai également un échec d'authentification a mon compte M6, que ce soit pour le live ou le replay

**Comment by joaopa00** [comment]
Incapable de reproduire aussi bien avec le direct que la télévision pa rattrapage. 
![Screenshot_20230719_101623](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/13057733/db91cda8-b18f-459b-aa25-5081e1f24038)

**Comment by joaopa00** [comment]
>Please try the last beta version and check existing issues before issuing a bug. warning

**Comment by Jaunattend** [comment]
On both version, beta and stable, i've got issues with these Channels, i'm unable to watch M6, W9... Etc... 

On stable : index error
On beta : authentification fail

**Comment by joaopa00** [comment]
La version stable ne fonctionne pas pour le groupe M6: les liens ne sont pas à jour. Il faut utiliser la version béta. Pour le problème d'utilisation de la versin béta, utillisez-vous un vpn?

**Comment by Jaunattend** [comment]
Non, pas de VPN, je suis en IP fixe avec dns : 8.8.8.8, 8.8.4.4

**Comment by joaopa00** [comment]
Il faut attacher un log pour voir où se situe le problème chez vous.

**Comment by joaopa00** [comment]
Peux-tu essayer cette [version de test](https://drive.google.com/file/d/13PqXyYt5dIq8aBybiRUgErGvgMjfdfiv/view?usp=sharing)

**Comment by Jaunattend** [comment]
En essayant de l'installer a partir de kodi (installation d'un fichier zip) j'ai un message d'erreur : Échec de l'installation de l'extension. Je suis désolé, merci encore

**Comment by Almeyric** [comment]
Bonjour,

Je relance mon problème.

Donc, j'ai refait un test sous navigateur, les bloqueurs de pubs fonctionnent très bien et empêchent toutes lecteur via le sites web.

Donc sous Brave & FF qui sont sur le même OS que Kodi fonctionnent très bien. Ainsi que l'application 6play sous W11 qui passe par Brave.

Je remet un log avec le mode debug activé.

[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/12138419/kodi.log)

J'ajoute que sur France 2 lorsque le programme change pour des pubs depuis par exemple l'étape du jour ou autre, ça freeze pareil dans le sens inverse... Changement de chaine et retour sur la 2, ça règle le problème.

Je ne pense pas que ce soit la même source de problème.

**Comment by joaopa00** [comment]
L version 29 est sortie. Il faudrait déjà faire la mise à jour.

**Comment by Almeyric** [comment]
j'ai effectué une réinstallation le 18.07

Ca ne change rien....

![screenshot00000](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/40559789/1f2fc163-d2da-4f33-9fca-2215575409d9)

**Comment by joaopa00** [comment]
On peut avoir un nouveau log avec la version bera29?

**Comment by mmtest1** [comment]
ok je vais voir du côté de libreelec, mais c'est étonnant cela fonctionne avec les autres chaines nécessitant une authentification (tf1, rmc-bfm, nrj12)

**Comment by joaopa00** [comment]
Je suppose que c'est fixé. Si ce n'est pas le cas, réouvrir en postant le log complet.
