### ISSUE TITLE
IPTV manager don't add channel in kodi 

### ISSUE THREAD

**Issue by B4rabbas** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1178]
### Describe the bug
Iptv channel don't appear in TV section of Kodi

### To Reproduce
Steps to reproduce the behaviour:
1. Selecting channels inside catchup
2. Choose and refresh channels in iptv manager
3. Open TV list
4. See nothing inside

### Expected behaviour
A clear and concise description of what you expected to happen:
4. See the channels I have selected and add with iptv manager

### Actual behaviour
Tell us what happens instead:
4. It's empty

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 20.1 (20.1.0)
 - Catch-up TV & More version: v0.2.38 (manually) & beta v0.0.6
 - Installation method: from zip file & from repo -> exactly the same issue

### Additional context
Try at leat 50 times, relaunch  kodi etc

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by B4rabbas** [comment]
Here is any workaround to manually set up the tv integration ?

**Comment by B4rabbas** [comment]
I've just test on a fresh install of kody x64 from flathub, there is the same issue, error notification pop to tell iptv simple is deconnected

**Comment by B4rabbas** [comment]
This issue is closed, it's not a problem from catchup, but with missing lib. Iptv simple is not available on batocera and on ubuntu you have to manually install package from apt.

If some raspberry user read this, just use retropie, you ll be able to install iptv simple with apt

**Comment by Jaunattend** [comment]
Hello, problem still there on Android.

**Comment by B4rabbas** [comment]
> Hello, problem still there on Android.

Yes indeed, my bad, I re-open the issue.
Currently the workaround is to set up this on linux or windows kodi and manually export files from ./kodi in your device.

**Comment by joaopa00** [comment]
Problème d'IPTVSIMPE déjà connu
[problème rapporté à IPTVSIMPLE](https://github.com/add-ons/service.iptv.manager/issues/107)
