### ISSUE TITLE
Kodi Leia RC3 + 6play -> no video

### ISSUE THREAD

**Issue by fdubuisson** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#118]
Video tries to load but nothing happens. Example: "M6/Divertissement/La France a un incroyable talent/Saison 13"

Error visible in logs:
`
23:28:42.916 T:15684 WARNING: CPythonInvoker(9, C:\Users\Fred\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\addon.py): the python script "C:\Users\Fred\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\addon.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcgui::ListItem
23:28:42.991 T:10800  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/6play/get_video_url/?_pickle_=80027d71002855076974656d5f6964710158020000006d36710255075f7469746c655f7103581c00000046696e616c6520656e20646972656374202f20536169736f6e20313371045508766964656f5f69647105580d000000636c69705f3132323337313537710655096974656d5f6469637471077d7108285804000000696e666f71097d710a285804000000706c6f74710b5891050000417072c3a87320382073656d61696e657320646520636f6d70c3a9746974696f6e206427756e65207261726520696e74656e736974c3a92c204c61204672616e6365206120756e20496e63726f7961626c652054616c656e742c20736169736f6e2031332c206c6976726520636520736f697220736f6e2064c3a96e6f75656d656e742021200a0a496c7320766f7573206f6e7420626c756666c3a9732c2073636f746368c3a9732c20616d7573c3a9732c2073757270726973206f7520c3a96d7573e280a620706f7572206c65206772616e642066696e616c2c2031332061727469737465732c206c6573206d65696c6c657572732064652063652063727520323031382c20732761707072c3aa74656e7420c3a020746f757420646f6e6e657220706f75722074656e746572206427616a6f75746572206c657572206e6f6d2061752070616c6d6172c3a873206465206c27c3a96d697373696f6e2e0a0a417072c3a8732061766f69722066616974206c27696d706173736520737572206c65732064656d692d66696e616c65732c206c6573203520476f6c64656e2042757a7a65727320646573206175646974696f6e732072656a6f69676e656e7420636520736f6972206c657320382064656d692d66696e616c69737465732073c3a96c656374696f6e6ec3a97320706172206e6f747265206a75727920706f757220756e206465726e696572206e756dc3a9726f20696ec3a964697420656e206469726563742e20436520736f697220746f7573206c657320636f6d70746575727320736f6e742072656d697320c3a0203020210a0a436f6d6d65206c657320736169736f6e73207072c3a963c3a964656e7465732c206c65206a7572792c20c3a0206c276f726967696e652064652063652063617374696e672066696e616c2c206e276175726120636574746520666f697320717527756e2072c3b46c6520636f6e73756c74617469662e2043276573742064c3a9736f726d61697320c3a020564f5553206427656e747265722064616e73206c612064616e736520656e20766f74616e7420706f7572206c652074616c656e742071756520564f555320736f7568616974657a20766f69722073616372c3a9207661696e71756575722e200a0a4475206368616e7420c3a0206c612064616e73652c20656e2070617373616e7420706172206c6520636f6e746f7274696f6e6e69736d652c206475206d6174206368696e6f69732c206465206c2768756d6f75722c2064752062656174626f78696e67206574206365727461696e657320646573206469736369706c696e6573206c657320706c7573207375727072656e616e746573206465206c6120736169736f6ee280a620696c207920656e206175726120706f757220746f7573206c657320676fc3bb747320210a0a5175656c207365726120766f747265206661766f7269203f20417072c3a8732053616c61682c204a756e696f722c20416c65782c20c38963686f732d4c69c3a9732c204178656c20657420416c697ac3a9652c204d6172696e61204b6179652c20446965204d6f62696c65732c2053696d6f6e204865756c6c652c2042616761642064652056616e6e65732c204a756c696574746520657420436861726c69652c20416e746f6e696f206574204c61757261204c61756e652c207175692064657669656e647261206c6520313365207661696e71756575722064752054616c656e742053686f77206c6520706c75732064c3a96a616e74c3a9206465204672616e6365206574207265706172746972612061766563206c6120736f6d6d6520657863657074696f6e6e656c6c652064652031303020303030206575726f73203f200a0ac38020766f7573206465206a6f7565722021204d617264692031382064c3a963656d6272652c20656e2064697265637420c3a020323168303020737572204d362e710c55056169726564710d580a000000323031382d31322d3138710e55057469746c65710f581c00000046696e616c6520656e20646972656374202f20536169736f6e203133711058080000006475726174696f6e71114df721550479656172711258040000003230313871135504646174657114580a00000031382e31322e32303138711575580300000061727471167d711728580600000066616e6172747118582d00000068747470733a2f2f696d616765732e36706c61792e66722f76312f696d616765732f323031323434352f726177711958050000007468756d62711a582d00000068747470733a2f2f696d616765732e36706c61792e66722f76312f696d616765732f323031323434352f726177711b75580600000073747265616d711c7d711d58050000006c6162656c711e581c00000046696e616c6520656e20646972656374202f20536169736f6e203133711f5806000000706172616d73712063636f6465717569636b2e6c697374696e670a506172616d730a7121298171227d712355087261775f646963747124680073625807000000636f6e7465787471257d7126580800000070726f7065727479712763636f6465717569636b2e6c697374696e670a50726f70657274790a7128298171297d712a2868247d712b55095f6c6973746974656d712c6378626d636775690a4c6973744974656d0a712d2981712e756275752e
23:28:42.992 T:10800   ERROR: CCurlFile::Stat - Failed: Unsupported protocol(1) for plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/6play/get_video_url/?_pickle_=80027d71002855076974656d5f6964710158020000006d36710255075f7469746c655f7103581c00000046696e616c6520656e20646972656374202f20536169736f6e20313371045508766964656f5f69647105580d000000636c69705f3132323337313537710655096974656d5f6469637471077d7108285804000000696e666f71097d710a285804000000706c6f74710b5891050000417072c3a87320382073656d61696e657320646520636f6d70c3a9746974696f6e206427756e65207261726520696e74656e736974c3a92c204c61204672616e6365206120756e20496e63726f7961626c652054616c656e742c20736169736f6e2031332c206c6976726520636520736f697220736f6e2064c3a96e6f75656d656e742021200a0a496c7320766f7573206f6e7420626c756666c3a9732c2073636f746368c3a9732c20616d7573c3a9732c2073757270726973206f7520c3a96d7573e280a620706f7572206c65206772616e642066696e616c2c2031332061727469737465732c206c6573206d65696c6c657572732064652063652063727520323031382c20732761707072c3aa74656e7420c3a020746f757420646f6e6e657220706f75722074656e746572206427616a6f75746572206c657572206e6f6d2061752070616c6d6172c3a873206465206c27c3a96d697373696f6e2e0a0a417072c3a8732061766f69722066616974206c27696d706173736520737572206c65732064656d692d66696e616c65732c206c6573203520476f6c64656e2042757a7a65727320646573206175646974696f6e732072656a6f69676e656e7420636520736f6972206c657320382064656d692d66696e616c69737465732073c3a96c656374696f6e6ec3a97320706172206e6f747265206a75727920706f757220756e206465726e696572206e756dc3a9726f20696ec3a964697420656e206469726563742e20436520736f697220746f7573206c657320636f6d70746575727320736f6e742072656d697320c3a0203020210a0a436f6d6d65206c657320736169736f6e73207072c3a963c3a964656e7465732c206c65206a7572792c20c3a0206c276f726967696e652064652063652063617374696e672066696e616c2c206e276175726120636574746520666f697320717527756e2072c3b46c6520636f6e73756c74617469662e2043276573742064c3a9736f726d61697320c3a020564f5553206427656e747265722064616e73206c612064616e736520656e20766f74616e7420706f7572206c652074616c656e742071756520564f555320736f7568616974657a20766f69722073616372c3a9207661696e71756575722e200a0a4475206368616e7420c3a0206c612064616e73652c20656e2070617373616e7420706172206c6520636f6e746f7274696f6e6e69736d652c206475206d6174206368696e6f69732c206465206c2768756d6f75722c2064752062656174626f78696e67206574206365727461696e657320646573206469736369706c696e6573206c657320706c7573207375727072656e616e746573206465206c6120736169736f6ee280a620696c207920656e206175726120706f757220746f7573206c657320676fc3bb747320210a0a5175656c207365726120766f747265206661766f7269203f20417072c3a8732053616c61682c204a756e696f722c20416c65782c20c38963686f732d4c69c3a9732c204178656c20657420416c697ac3a9652c204d6172696e61204b6179652c20446965204d6f62696c65732c2053696d6f6e204865756c6c652c2042616761642064652056616e6e65732c204a756c696574746520657420436861726c69652c20416e746f6e696f206574204c61757261204c61756e652c207175692064657669656e647261206c6520313365207661696e71756575722064752054616c656e742053686f77206c6520706c75732064c3a96a616e74c3a9206465204672616e6365206574207265706172746972612061766563206c6120736f6d6d6520657863657074696f6e6e656c6c652064652031303020303030206575726f73203f200a0ac38020766f7573206465206a6f7565722021204d617264692031382064c3a963656d6272652c20656e2064697265637420c3a020323168303020737572204d362e710c55056169726564710d580a000000323031382d31322d3138710e55057469746c65710f581c00000046696e616c6520656e20646972656374202f20536169736f6e203133711058080000006475726174696f6e71114df721550479656172711258040000003230313871135504646174657114580a00000031382e31322e32303138711575580300000061727471167d711728580600000066616e6172747118582d00000068747470733a2f2f696d616765732e36706c61792e66722f76312f696d616765732f323031323434352f726177711958050000007468756d62711a582d00000068747470733a2f2f696d616765732e36706c61792e66722f76312f696d616765732f323031323434352f726177711b75580600000073747265616d711c7d711d58050000006c6162656c711e581c00000046696e616c6520656e20646972656374202f20536169736f6e203133711f5806000000706172616d73712063636f6465717569636b2e6c697374696e670a506172616d730a7121298171227d712355087261775f646963747124680073625807000000636f6e7465787471257d7126580800000070726f7065727479712763636f6465717569636b2e6c697374696e670a50726f70657274790a7128298171297d712a2868247d712b55095f6c6973746974656d712c6378626d636775690a4c6973744974656d0a712d2981712e756275752e
23:28:42.993 T:180  NOTICE: Creating InputStream
23:28:43.985 T:180  NOTICE: Creating Demuxer
23:28:44.190 T:180   ERROR: CDVDDemuxFFmpeg::Open - error probing input format, https://vod-m6w.global.ssl.fastly.net/usp/mb_sd3/7/5/0/La-France-a-un-incr_c12237157_Finale-en-direc/La-France-a-un-incr_c12237157_Finale-en-direc_drmnp.ism/Manifest.mpd
23:28:44.191 T:180   ERROR: CVideoPlayer::OpenDemuxStream - Error creating demuxer
23:28:44.191 T:180  NOTICE: CVideoPlayer::OnExit()
23:28:44.371 T:10800  NOTICE: CVideoPlayer::CloseFile()
23:28:44.371 T:10800  NOTICE: VideoPlayer: waiting for threads to exit
23:28:44.371 T:10800  NOTICE: VideoPlayer: finished waiting
`

Addon version: 0.2.2~beta09
Full logs;
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/2706353/kodi.log)

**Comment by wwark** [comment]
bonjour @fdubuisson,

Je viens de tester de mon côté et j'ai pu lire les 3 vidéos de M6/Divertissement/La France a un incroyable talent/Saison 13.
Est-ce qu'il serait possible de refaire un test avec les logs en mode debug ?
Est-ce que vous êtes en France, il y a beaucoup de contenus géolocalités?
Est-ce que vous avez à lire les contenus Netflix j'ai pu voir dans le logs que vous aviez ce plugin?

D'avance merci pour vos retours, et bonnes fêtes,
WWark

**Comment by fdubuisson** [comment]
Hi,

Here are the debug logs: 
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/2707028/kodi.log)

I'm in France and I can read these contents with the 0.2.1 "release" version (with a bad image quality). I installed the Netflix addon only as I read that it installed some useful dependencies. I don't have a Netflix account so I cannot test it.
Is there another way to check the DRM library ? maybe a way to uninstall/reinstall it ?

Thanks for your feedback (and great plugin) !

**Comment by fdubuisson** [comment]
Fyi, tried with a fresh new install (only kodi leia RC3 + catchup plugin beta) and got the same result.

**Comment by wwark** [comment]
Hi,

Ok do you have some popup propose to you to install so requirements during the first read on one content of M6/Divertissement/La France a un incroyable talent/Saison 13 ?

Yes 0.2.1 the plugin don't use DRM of 6play but with 0.2.2 we forced to use DRM in every content because the video has better quality.

Is it possible to test TF1 series to see if you can read grease anatomy for example ?

In the logs provided we blocked at the beginin but don't know why. What is your setup ?

Thanks,
Wwark.

**Comment by wwark** [comment]
maybe you need to add your 6play account in the configuration of the plugin. did you do that ?

**Comment by fdubuisson** [comment]
Just made a new test and this time, it worked fine :-o
I don't see anything that could have changed so I'll continue to test and get back to you if the issue comes back.

Thanks for your help !

**Comment by wwark** [comment]
ok I will close this ticket.
