### ISSUE TITLE
Passwords with special characters do not work

### ISSUE THREAD

**Issue by sancelot** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1184]
### Describe the bug
Trying to connect to tf1 using a password with "!" failed 
### To Reproduce
Steps to reproduce the behaviour:
1. use a password containing "!" character
2. try to watch tf1
3. it fails
4.

### Your environment
 - [x ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version:20
 - Catch-up TV & More version:beta
 - Installation method:

**Comment by joaopa00** [comment]
Besoin d'un log  pour voir le problème. Mieux encore, il serait utile de creer un compte qui pose problème.

**Comment by joaopa00** [comment]
Incapable de reproduire le problème. J'ai crée un compte  avec un mot de passe contenant un point d'exclamation.

Je ferme. Si le problème existe encore chez toi, crée un compte permettant de reproduire le problème et envoire moi les identifiants par mail. Et surotut explicite sur quel système le problème apparaît.
