### ISSUE TITLE
[FR-MYCANAL] DRM play - fix part2

### ISSUE THREAD

**Issue by darodi** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1185]
J'ai fixé un souci dans la lecture DRM dans la PR 
- #1160

Pour le debug/devel j'ai utilisé un nouveau fichier dans le projet  `catchuptvandmore-test`
`catchuptvandmore-test\utils\service_test.py`
C'est un serveur proxy avec la même implémentation que 
`plugin.video.catchuptvandmore\service.py`

Cependant, je remarque que si je lance un serveur proxy avec `service_test.py`
Le décodage DRM passe. J'ai le son et l'image dans Kodi.

Avec le proxy de `plugin.video.catchuptvandmore\service.py` la licence n'a pas l'air de ramener le même résultat, je n'ai que le son et pas d'image dans kodi en déployé.

Avez vous le même résultat?

J'ai dev sous windows, je vais tester sous rpi et android maintenant que la beta30 est disponible.

> toujours un problème avec la première entrée en replay
> https://www.canalplus.com/chaines/canalplus-en-clair
> 
> exemple
> ↪ Root menu (1) ➡ Catch-up TV (2) ➡ France (2) ➡ myCANAL (3)  ➡ Canal + (1) ➡ Theme - Chaines - CANAL+ en clair - CANAL+ en clair (1) ➡ Clique (1) ➡ Clique (1)
> 
> 
> drm_type 'DRM_MKPC_WIDEVINE_DASH'
> n'a plus l'air de fonctionner
> 
>_Originally posted by @darodi in https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1160#issuecomment-1664278447_

**Comment by darodi** [comment]
OK j'ai trouvé
ce n'est pas le proxy qui change le comportement.
C'est le DRM.

Canal n'accepte qu'une résolution limitée.
En dessous d'une certaine résolution choisie, l'image apparaît

**Comment by darodi** [comment]
je vais adapter mycanal pour utiliser 
`resources/lib/resolver_proxy.py`

**Comment by darodi** [comment]
Pouvez-vous me confirmer que vous avez également un souci lors du replay pour les vidéos avec DRM >= 720p?
Pour ma part, la vidéo se lance et j'ai le son mais pas l'image.

<720p pas de problème.

**Comment by joaopa00** [comment]
Sous linux, la qualité maximale est 960x540 (1499 kbs). La video et le son fonctionnent normalement pour cette qualité

**Comment by darodi** [comment]
> Sous linux, la qualité maximale est 960x540 (1499 kbs). La video et le son fonctionnent normalement pour cette qualité

Ok donc <720p aussi.
Par contre, je confirme que la qualité max fonctionne sous Android. Pas de restriction drm pour un périphérique certifié donc.
