### ISSUE TITLE
download replay / télécharger replay en video 

### ISSUE THREAD

**Issue by thinkrtx** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1186]
### Content description

* Name: where is Replay dowload video button ?
* Type [e.g. TV channel, Catch-up TV, Website, Radio] :Replay : Les traitres M6
* Website URL: Don't know
* Content language/country:FR

### Content access

Bonjour je voudrais savoir si c'est possible de télécharger une vidéo replay pour que je regarde plus tard en hors connexion si je veux svp .Si c'est possible on fait comment svp ? 
Si c'est pas possible pourriez vous penser à ajouter cette fonctionnalitée svp.MErci
### More information

If you want to add more information, put it here:

**Comment by darodi** [comment]
@thinkrtx 

Le groupe M6 possède des DRM, pas de download possible, uniquement du streaming

**Comment by joaopa00** [comment]
Comme remarqué par darodi, les vidéos sur M6 sont protégés par drm contre la lecture hors connexion au site. Comme CUTVM est un logiciel légal, il n'implémentera jamais des moyens non-légaux de contournement des drms.
