### ISSUE TITLE
vpn obligatoire ?

### ISSUE THREAD

**Issue by thinkrtx** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1187]
bonjour je souhaite savoir si catchup tv est entierement legal pour que je sache si je peux y aller dessus sans vpn quand je suis en france svp

**Comment by darodi** [comment]
@thinkrtx 

Oui, CUTVM est légal et dans le dépôt officiel de Kodi qui n’accepte que les plugins légaux.

CUTVM ne fait que diffuser les vidéos/flux présents sur les sites officiels.
Il faut un compte pour certaines chaînes.
Si la chaîne est geo bloquée, ça ne fonctionne pas sans VPN.

**Comment by darodi** [comment]
> est ce possible de télécharger des replay ?

Si les vidéos sont sans DRM, il est parfois possible de télécharger le replay via le menu de contexte.
C'est très rare.
