### ISSUE TITLE
[resolver_proxy.py] Syntax Error on line 122

### ISSUE THREAD

**Issue by nafralt** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1189]
Un simple bug à cause de ma version de Python (2.x)  et celle utilisée par les dev.

Dans le fichier resolver_proxy.py, ligne 122 : 

```python
def __set_ia_quality(plugin, video_url, bypass, headers, item, manifest_type) -> bool:
``` 
La spécification des types de variables à retourner n'est pas supporté pour les versions antérieurs à 3.5 de Python.

Merci de corriger simplement par :

```python
def __set_ia_quality(plugin, video_url, bypass, headers, item, manifest_type):
```

**Comment by darodi** [comment]
@nafralt 

merci d'avoir signalé
sera corrigé lors du prochain merge
