### ISSUE TITLE
for pc or android

### ISSUE THREAD

**Issue by thinkrtx** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1191]
Hi is there similar apps on pc or android (without using kodi) .Can you create an app for pc or android please.
Salut existe il des appli similaires à catchup tv and more pour pc ou android sans utiliser kodi svp. ? 
MErci de votre aide

**Comment by darodi** [comment]
>Can you create an app for pc or android please. 

Kodi is on pc, android, linux, ...
Personally, I don't see the point, and I won't.

> Hi is there similar apps on pc or android (without using kodi) 
> Salut existe il des appli similaires à catchup tv and more pour pc ou android sans utiliser kodi svp. ? 

Quel est le rapport avec CUTVM?
Google is your friend... captvty for example.

@joaopa00 
Peut-on fermer cette "issue"?
et les 2 autres "issues" de @thinkrtx tant qu'on y est.

**Comment by joaopa00** [comment]
Comme conseillé par darodi, sur PC il y a captvty sur PC. Comme il fonctionne bien avec Wine, utilise wine+captvty sur Android.
