### ISSUE TITLE
Live TF1 and Replay TF1 still Fail on beta31 (Raison: widevine est obligatoire dans le device Android)

### ISSUE THREAD

**Issue by CharlesLavie** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1199]
### Describe the bug
FAILURE to play LIVE TF1 channel and MyTF1 Replays

### To Reproduce
VPN FR is turned on
_Sequence in the log file:_ 
   Play TF1 channel Live => FAILED
   Play Replay MyTF1 Journal de 20H => FAILED
   Play Replay MyTF1 Meteo=> FAILED
   _(played FranceTv France2 journal de 20H => SUCCESS)_

### Your environment
 - [x] Android TV
 - Operating system version/name: ARM 32-bit 5.1.1
 - Kodi version: fresh 20.2.0
 - Catch-up TV & More version: v0.2.39~beta31 (also occuring with ~beta32)
 - Installation method: fresh from the CUTVM repo
 
### Additional context
 Fresh Install Kodi20.2 on Android TV, fresh install of CUTV&M beta31
 MyTF1 login/password added to settings
 Active VPN server in France (FYI tested website MyTF1.fr works well with vpn and login for Live TF1 and MyTF1 Replay on my mobile phone on the same WiFi network)
  (up until 2 months ago the previous versions of CUTV&M worked well for me on this TV until some issues started from MyTF1 side.)

### Debug log
Attached and labelled
[[Kodi Live TF1 and MyTF1 Replay FAIL.log.txt](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/12319849/Kodi.Live.TF1.and.MyTF1.Replay.FAIL.log.txt)](https://pastebin.ubuntu.com/p/cJnxgbb5Kw/)

Thank you and I remain available if require more data / testing

**Comment by joaopa00** [comment]
Le mode déboggage n'est pas activé. Les informations utiles ne sont pas présentes dans le log. Attache un nouveau log avec le mode debiggagae activé et les composantes libcurl ffmpeg et video activées.

**Comment by CharlesLavie** [comment]
> Le mode déboggage n'est pas activé. Les informations utiles ne sont pas présentes dans le log. Attache un nouveau log avec le mode debiggagae activé et les composantes libcurl ffmpeg et video activées.

Bonjour! J'ai mis a jour l'Issue avec un nouveau lien vers le log en mode debug et les composantes qui vont bien.

**Comment by joaopa00** [comment]
Il semble que vos certificats soient périmés. Et récemment  TF1 a changé son API, il est vraisemblable que TF1 verifie la validité des  certificats maintenant. Il faut mettre à jour vos certificats. Pour Android, cela dépend de chaque constructeur.

**Comment by sousouille** [comment]
Hello,
Je suis dans le même cas. Jusqu'à samedi inclus tout était OK pour les replays. Désormais, impossible de lancer la lecture d'un replay. Ça crash l'app Kodi et revient direct sur la home Android.

**Comment by darodi** [comment]
@CharlesLavie 
Je viens de tester sur un téléphone sous Android 13
Kodi version: 20.2.0
Catch-up TV & More version: v0.2.39~beta33 

La météo et le journal de 20h passent en replay.
Je ne peux tester le live, je suis géo-bloqué.

Quel est le résultat en testant une résolution plus basse en choisissant cette configuration qui fait apparaître le choix de résolution?

![image](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/4682830/98abec68-3991-420f-b231-186d94a61afe)

**Comment by sousouille** [comment]
Hello, j'étais confronté à un crash au lancement de la lecture d'un Replay sur TF1. Et en effet, c'est parce qu'il lançait la lecture sur une résolution full HD auquel mon compte n'a pas droit. Ceci depuis que je suis passé premium le temps des 7 jours gratuits et que j'ai résilié.
La lecture la plus haute permise est 1024.
Merci pour l'astuce.

**Comment by sousouille** [comment]
A noter que le PB ne se produisait pas sur Windows.

**Comment by CharlesLavie** [comment]
> @CharlesLavie Je viens de tester sur un téléphone sous Android 13 Kodi version: 20.2.0 Catch-up TV & More version: v0.2.39~beta33
> 
> La météo et le journal de 20h passent en replay. Je ne peux tester le live, je suis géo-bloqué.
> 
> Quel est le résultat en testant une résolution plus basse en choisissant cette configuration qui fait apparaître le choix de résolution?
> 
> ![image](https://user-images.githubusercontent.com/4682830/262111823-98abec68-3991-420f-b231-186d94a61afe.png)

Merci pour la réponse. Malheureusement en beta33, vpn fr et le changement du paramètre de choix de résolution, le problème persiste: l'erreur apparaît avant que la boîte de dialogue du choix de la qualité vidéo apparaisse. 
Idem en TF1 Live et MyTF1 Replay 😢

**Comment by joaopa00** [comment]
Si widevine n'est pas présent sur ta box, c'est foutu.

**Comment by CharlesLavie** [comment]
OK, je confirme que cela est du a Widevine qui doit être manquant sur la TV Android 5.1.1. J'ai testé sur une TV box Android 10 avec une copie exacte de la build Kodi avec CUTV&M et cela marche.
==> Ce bug report peut donc être fermé.
