### ISSUE TITLE
STV Player not working 

### ISSUE THREAD

**Issue by m1ctk** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1205]
Since about 2 weeks ago STV player catchup just won't run now. An error message shows 'object has no attribute...'

**Comment by joaopa00** [comment]
Can you give a try to this [test version](https://drive.google.com/file/d/1vmzpwPDVRLkJRx5YOukhtZgTYm0VXMA_/view?usp=sharing)

**Comment by m1ctk** [comment]
Ah yes working fine thanks a lot !

**Comment by m1ctk** [comment]
But unfortunately I can't download on my firestick with kodi, any
suggestions ?

**Comment by joaopa00** [comment]
I push a new beta. Just wait for it to be available for your device.

**Comment by m1ctk** [comment]
Ok how long does that take usually ?

**Comment by joaopa00** [comment]
Usually, less than 3 days.

**Comment by m1ctk** [comment]
No update so far

**Comment by m1ctk** [comment]
Still no update on my firestick 3 days later

**Comment by darodi** [comment]
Well, you should look better. 

committed on 16-08-23 at 09:23
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/d1b116db6ebc96b054cb8139b9f2fdcdaa53d871
