### ISSUE TITLE
NRJ12 / Gulli / 6ter / Chérie 25 -> display issue

### ISSUE THREAD

**Issue by B4rabbas** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1208]
### Describe the bug
Theses channels don't work anymore, maybe the same issue, I have "echec de lecture" error message and "(KEY ERROR -> #channelName"

### To Reproduce
Steps to reproduce the behaviour:
1. Choose channel

### Expected behaviour
Display the channel

### Actual behaviour
The channel isn't displayed, an error notification instead

### Your environment
 - [x] Android
 - [ ] iOS (not tested)
 - [x] Linux
 - [ ] OSX (not tested)
 - [x] Raspberry-Pi
 - [x] Windows
 - [x] Other (ARM devices)

 - Operating system version/name: Linux Mint 21.2 / Batocera 37 / Armbian / Android 11 & 13 / Windows 10
 - Kodi version: 20.1 - 20.2
 - Catch-up TV & More version: 0.2.39~beta32
 - Installation method: from zip / beta canal 

### Debug log
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/12356189/kodi.log)

**Comment by joaopa00** [comment]
Devrait être fixé dans la béta.
