### ISSUE TITLE
Canal + / CStar choose issue dailymotion / mycanal

### ISSUE THREAD

**Issue by B4rabbas** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1209]
### Describe the bug
Theses channels ask to choose beetween mycanal and dailymotion source, 90% of times choosing dailymotion make kodi crash, mycanal don't work at all. There is a workaround, just use cancel instead of choosing mycanal or dailymotion, and the channel is correctly displayed.

### To Reproduce
Steps to reproduce the behaviour:
1. Choose channel

### Expected behaviour
Display the channel

### Actual behaviour
A prompt ask to choose between mycanal & dailymotion. Cause kodi crash 90% time

### Your environment
 - [x] Android
 - [ ] iOS (not tested)
 - [x] Linux
 - [ ] OSX (not tested)
 - [x] Raspberry-Pi
 - [x] Windows
 - [x] Other (ARM devices)

 - Operating system version/name: Linux Mint 21.2 / Batocera 37 / Armbian / Android 11 & 13 / Windows 10
 - Kodi version: 20.1 - 20.2
 - Catch-up TV & More version: 0.2.39~beta32
 - Installation method: from zip / beta canal

**Comment by joaopa00** [comment]
Incapable de reproduire. Kodi crashes ne veut rien dire. Cela signifie-t-il que l'application kodi se ferme seule? Il faut attacher un log avec le mode débogage activé.

**Comment by joaopa00** [comment]
Doublon de l'issue 1213. Je ferme.
