### ISSUE TITLE
Simple IPTV auto configuration fail

### ISSUE THREAD

**Issue by B4rabbas** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1210]
### Describe the bug
During channel setup, the option to "automatically set up iptv simple" fail. I have to manually edit path inside iptvsimple options to make tv integration work

### To Reproduce
Steps to reproduce the behaviour:
Use "automatically set up iptv simple" in "IPTV manager"

### Expected behaviour
To set up the automatically the correct path in iptvsimple config

### Actual behaviour
Nothing is configured, a workaround is to manually add the path of .mp3u etc in iptvsimple
### Your environment
 - [x] Android
 - [ ] iOS (not tested)
 - [x] Linux
 - [ ] OSX (not tested)
 - [x] Raspberry-Pi
 - [x] Windows
 - [x] Other (ARM devices)

 - Operating system version/name: Linux Mint 21.2 / Batocera 37 / Armbian / Android 11 & 13 / Windows 10
 - Kodi version: 20.1 - 20.2
 - Catch-up TV & More version: 0.2.39~beta32
 - Installation method: from zip / beta canal

**Comment by dudusse** [comment]
Hello,
And what is the path of the m3u please ?

**Comment by B4rabbas** [comment]
> Hello, And what is the path of the m3u please ?
/.kodi/userdata/addon_data/plugin.iptv-manager

Not sure about exact name of "plugin.iptv-manager" but it the folder "iptv manager".

**Comment by B4rabbas** [comment]
You have to enable hidden files and folder in kodi's option if you are on an android devices. To see them you have to enable expert mode

**Comment by ltctceplrm** [comment]
> > Hello, And what is the path of the m3u please ?
> 
> `/.kodi/userdata/addon_data/plugin.iptv-manager`
> 
> Not sure about exact name of "plugin.iptv-manager" but it the folder "iptv manager".

I can confirm that this works, the folder is called `service.iptv.manager` and within it is `playlist.m3u8` and `epg.xml`

**Comment by joaopa00** [comment]
C'est un problème connu de IPTV simple pas de CUTVM.
[problème rapporté à IPTVSIMPLE](https://github.com/add-ons/service.iptv.manager/issues/107)
