### ISSUE TITLE
Catchuptv add on test / beta  version still not on Firestick after 3 days 

### ISSUE THREAD

**Issue by m1ctk** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1212]
??

**Comment by m1ctk** [comment]
So it was meants to show up in less tyan 3 days now 4 says on and nothing, how do you install this beta on a firestick manually ?

**Comment by darodi** [comment]
https://catch-up-tv-and-more.github.io/installation/#ii-add-the-official-catch-up-tv--more-repository

**Comment by m1ctk** [comment]
The link given there is dead

**Comment by darodi** [comment]
>1. Add the source to add the official repository
Go to the Kodi settings.
Then in File Manager.
Choose Add source and fill in the fields as shown in the image:
    URL: https://catch-up-tv-and-more.github.io/repo/
    Name: Catch-Up TV & More source


And no, the link is not dead.

**Comment by m1ctk** [comment]
I did all that like I have before for other add ons. I just get a message
box couldn't retrieve directory information

**Comment by darodi** [comment]
1. Check Internet Connection on your kindle stick
2. Check Your URL Information
The majority of the time, the Kodi Unable to Connect Error occurs because the URL has been typed incorrectly.

**Comment by m1ctk** [comment]
Net connation is fine the url is 100% correct but still get the error

**Comment by m1ctk** [comment]
The word up was missing ok all sorted now thanks

**Comment by darodi** [comment]
@m1ctk 
Good.
Can you close the issue?

**Comment by darodi** [comment]
@joaopa00 

can you close the issue instead then? Thanks
