### ISSUE TITLE
Display of C8 / Cstar channels is erratic

### ISSUE THREAD

**Issue by smax86** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1213]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
Display of C8 / Cstar channels is erratic: it works one time over 10 tries.
Most of the time, whatever choice is made (MyCanal or Dailymotion), the channel doesn't display (go back to Kodi menu) or Kodi is even crashing completely (simply closing).

### To Reproduce
Steps to reproduce the behaviour:
1. Try to display C8 or CStart with MyCanal or Dailymotion choice
2.
3.
4.

### Expected behaviour
A clear and concise description of what you expected to happen:
C8 and Cstar display is working and stability working.

### Actual behaviour
Tell us what happens instead:
Display of C8 or Cstar is erratic.

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 20.2
 - Catch-up TV & More version: 0.2.39~beta33
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by darodi** [comment]
logs please

**Comment by joaopa00** [comment]
Il y a du changement pour la lecture des flux dailymotion. Cela vaut le coup de tester la dernière beta (beta 35)

**Comment by joaopa00** [comment]
Je ferme. Si le bug persiste pour Dailymotion, n'hésite pas à réouvrir.
