### ISSUE TITLE
France 5 & Info out ?

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1219]

**Comment by enigma131** [comment]
Latest beta, Windows and Linux. Widewine up to date
France 2 and 3 are working

**Comment by joaopa00** [comment]
Je confirme le problème. J'ai rapidement regardé. Rien de bien évident aux premiers  abords. Le weekend approchant, j'aurai plus de temps pour enquêter sur le problème.

**Comment by joaopa00** [comment]
J'ai trouvé le problème. Ces chaînes n'acceptent pas un useer_agent qui possède la chaîne Kodi. Je me demande si c'est bien légal d'après la lègislation européenne d'interdire explicitement un appareil.

**Comment by joaopa00** [comment]
Ajouté une méthode de contournement pour Nexus. Si vous utilisez le dépot officiel Kodi pour Linux, vous avez la version Omega d'installée et la rustine implémentée ne fonctionne pas. Je ferme quand m^me car ce n'est pas à proprement parlé un bug de CUTVM.
