### ISSUE TITLE
No replay are available

### ISSUE THREAD

**Issue by fg2000fr** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#122]
Hello
I meet the issue around channel rmc decouverte and no replay available so
I recently updated my plugin to 0.2.1.
Since this update i have no replays for all channels.
I use kodi v17.6 with android.
Is it necessary to add a plugin for the new framework used by the plugin  (codequick)?
Thank you by advance.

**Comment by wwark** [comment]
Hello @fg2000fr,
RMC decouverte change his website and we fix it on the beta release of this plugin. You can install the beta release : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/wiki/Add-the-official-repository

For the issue no replays for all channels. Can we provide logs to understand this point?
What is the previous version you use before the 0.2.1?

Thanks,
Wwark

**Comment by fg2000fr** [comment]
Dear wwark. 
The plugin who works correctly ecxept for rmc decouverte is 0.1.14. I have reinstalled it to be dure.
[](url)Dear wwark. 
The plugin who works correctly ecxept for rmc decouverte is 0.1.14. I have reinstalled it to be sure
Attached is the log file for plugin 0.2.1 there is an error...
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/2751818/kodi.log)
re.

**Comment by fg2000fr** [comment]
Dear wwark
 i will do the test and give you the result this evening. I installed it from the zip file. So i upset for codequick...
Thank you for your help

**Comment by SylvainCecchetto** [comment]
Hi everyone,
Normally, even if you install a plugin from zip ; Kodi check for each dependency and install it before installing the plugin.
So in our case, Kodi had to install Codequick automatically.

The simple way, as Wark says, is to use our beta repo in order to keep Catch-up TV & More always updated ;-)

**Comment by fg2000fr** [comment]
Hi all
I tried the pluggin 0.2.2 beta 12 from the repository and i have the same issue
The folder catchup tv is empty...
Attached is the log file 
Thank you by advance
Is there a way to check if codequick is installed?
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/2752200/kodi.log)

**Comment by fg2000fr** [comment]
I try to clean the multitask and then the memory and then I reboot to be sure. Same issue
Codequick is intalled (0.9.7) i am able to see it.
Attached is the log [
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/2752317/kodi.log)
](url)

**Comment by SylvainCecchetto** [comment]
Oh :-/
Thank you for the log but we can't see any information of what caused the error.
Do you have the "debug logging" enable in the kodi setting?

**Comment by fg2000fr** [comment]
Oh yes it will be better
Attached the new file
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/2752383/kodi.log)

**Comment by SylvainCecchetto** [comment]
Thank you for the log but in my case I don't really understand why this error happen :-/.

Maybe you can try to uninstall the plugin ; restart Kodi ; install the plugin from the official repo.

Maybe @wwark have an idea about this issue? :-/

**Comment by fg2000fr** [comment]
Hello
Finally i removed kodi and reinstall it. I used the repository and now it works. I think something was corrupted due to the zip.

Many thanks for your help!!
