### ISSUE TITLE
M6 ne fonctionne plus

### ISSUE THREAD

**Issue by wixaw** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1221]
Bonjour,
M6 ne fonctionne plus depuis aujourd'hui, erreur 503 sur l'URL
Merci à vous

**Comment by darodi** [comment]
Même problème avec le live be-rtl
Je regarde ce qu'il se passe.

**Comment by MacCord** [comment]
Ok, ça me rassure : je suis pas le seul à avoir une erreur URL pour lancer 6play.
Merci

**Comment by darodi** [comment]
même le site web de rtlplay a l'air à moitié HS pour le moment
![image](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/4682830/c4c11ecc-509e-4f8a-ab8d-55b4184f1619)

**Comment by darodi** [comment]
ça fonctionne mieux maintenant. l'API a changé
je suis en train de faire les modifications.

**Comment by wixaw** [comment]
Merci beaucoup 🥳

**Comment by darodi** [comment]
fix pour RTLplay fait. 
demain j'adapterai M6
C'est le même principe, même (ancien) groupe, même plateforme

**Comment by darodi** [comment]
Pour information, depuis la mise à jour, les lives ne sont plus disponibles depuis la Belgique

![image](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/4682830/c366553d-f892-4e4b-bce3-5cefdcadbf01)

J'ai posté une pull request avec une correction possible de cette issue-ci mais je ne peux pas la tester.
Si une bonne âme en France peut tester #1223  il pourra être inclus dans la prochaine release beta

**Comment by joaopa00** [comment]
@Wiwax As tu une IP française? Car pour moi pas de problème aussi bien sous Linux que sur Android.

**Comment by darodi** [comment]
@wixaw  
un feedback?

**Comment by wixaw** [comment]
Salut désolé pour la réponse tardive, sur la beta ça fonctionne d'après madame , mais du coup je sais pas si c'est avec ou sans ta modification 💁

**Comment by darodi** [comment]
@wixaw 

La modification n'est pas encore incluse. Je pense que le site est encore en chantier. 
ça arrivera peut être à nouveau prochainement

**Comment by darodi** [comment]
Et le live fonctionne aussi à nouveau de la Belgique aujourd'hui 😆

**Comment by joaopa00** [comment]
Bonne nouvelle. Je ferme donc.
