### ISSUE TITLE
bein sports replay error

### ISSUE THREAD

**Issue by antho02** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1224]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
A clear and concise description of what the bug is: on opening bein sports section, error 403 client forbidden

### To Reproduce
Steps to reproduce the behaviour:
1.catchup
2.international
3.bein sports
4.

### Expected behaviour
A clear and concise description of what you expected to happen:

### Actual behaviour
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ X] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version:
 - Catch-up TV & More version:
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment]
Possible fix commited. Can not test because of geo-restriction.

**Comment by antho02** [comment]
I doubt it's geolocated because it happens on the main Being Sports menu Wich is subdivised in countries.
I guess maybe countries will be geolocated but not the main one ?

**Comment by joaopa00** [comment]
Your guess is not correct

**Comment by antho02** [comment]
Thanks for the information then.
Is there anything I can do or only développeurs will be able to work on it?

I tried it in different networks, the result is same 
And I'm able to open the api.beinsports.com/sites pages on a web browser without error 403

I try to give the most informations. If something else interesting let me know

**Comment by joaopa00** [comment]
You could give a try for the latest beta (37).

**Comment by antho02** [comment]
Oh thanks. Much more better now. I had a few error on some refreshes but been able to open the ones I wanted!
Thanks again

**Comment by joaopa00** [comment]
Considering fixed then. Thanks for the feedback.
