### ISSUE TITLE
Impossible d'avoir les chaine dans TV sur Kodi

### ISSUE THREAD

**Issue by Powerstreet** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1227]
Bonjour, 

J'ai installé KODI sur ma Nvidia Shield Pro, J'ai bien pu installer l'addon Catch-up TV, J'ai bien Installé IP TV Manager.
La TV Fonctionne très bien, mais malgré mes essaient, impossible d'ajouter les chaines à l'onglet TV de Kodi.

Si je fais plusieurs fois : Configure IPTV Simple automatically, et que je vais enssuite sur TV dans KODI, je reste bloqué sur un chargement : Demarrage du gestionnaire d'enregistreurs video : 0% 

J'ai bien suivi [ce tutoriel](https://catch-up-tv-and-more.github.io/fr/live_tv_installation/)

J'ai tout désinstallé, réinstallé, recommencer une multitude de fois, rien à faire...

### Your environment
 - [ ] Android TV (NVIDIA Shield Pro)

 - Operating system version/name: Android TV Version 11
 - Kodi version: 20.2
 - Catch-up TV & More version: Beta 0.2.39-Beta37

Merci par avance de votre soutient

**Comment by Metabaron1** [comment]
Meme probleme avec les memes version Kodi & Catch-up TV  sur Nokia Box 8000 (Android 10)

**Comment by dudusse** [comment]
Même problème sur mon téléviseur SONY sous android TV, et sur mon téléviseur XIAOMI sous android TV également.

Je fais ces deux actions :
“IPTV Simple” –> “Configure IPTV Simple automatically…”
“Channels” –> “Refresh channels and guide now…”

Mais c'est sans effet, l'onglet "TV" reste désespérément vide.

**Comment by B4rabbas** [comment]
Il y a un workaround ici https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1210


Vous aurez à mettre le chein vers les m3u et les epg depuis iptvsimple.

Une fois le chemin local réglé pour les chaines et les programmes tv vous n'aurez plus à la faire et les refresh de chaines fonctionneront normalement.

**Comment by joaopa00** [comment]
C'est un problème connu de IPTV simple pas de CUTVM.
[problème rapporté à IPTVSIMPLE](https://github.com/add-ons/service.iptv.manager/issues/107)

**Comment by Davbras** [comment]
Chez moi:
C:\Users\........\AppData\Roaming\Kodi\userdata\addon_data\service.iptv.manager\
