### ISSUE TITLE
MYTF1 pas dispo

### ISSUE THREAD

**Issue by Jon01993** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1231]
### Content description

* Name: MYTF1 off
* Type [e.g. TV channel, Catch-up TV, Website, Radio]: Catch-up TV 
* Website URL:
* Content language/country: France

### Content access

- [x] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [x] This content is geographically restricted

### More information

If you want to add more information, put it here:

Bonjour,
Je viens de réinstaller Kodi et Catch up tv en suivant toutes les étapes. Tous les replays fonctionnent, mais impossible de lire les replays de MYTF1 (malgré l'enregistrement des identifiants) 
On m'indique 'keyerror' (userinfo).
Je vous remercie d'avance pour votre aide

**Comment by Jon01993** [comment]
Merci ;) C'est fixed

**Comment by joaopa00** [comment]
Pour les autres utilisateurs qui auraient le même probleme, il serait bien que tu détailles comment tu as résolu le problème.
