### ISSUE TITLE
BE - Focus TV is no longer working // now requires login

### ISSUE THREAD

**Issue by maanwater** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1234]
### Describe the bug
The Belgian live channel Focus TV no longer works. Compared to the current production code, there are some changes in the Focus website:
- The URL of the stream has changed into: https://hls-origin01-focus-wtv.cdn01.rambla.be/main/adliveorigin-focus-wtv/_definst_/WqY7Y3.smil/playlist.m3u8
- Focus now requires logon in order to start streaming

### To Reproduce
Steps to reproduce the behaviour:
1. Navigate to Live TV > Belgium
2. Select Focus & WTV (West-Vlaanderen)

### Expected behaviour
The livestream of Focus starts playing

### Actual behaviour
Nothing happens when opening Focus TV.

### Screenshots
<img width="851" alt="image" src="https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/73558710/00e56424-02ea-47e6-99d5-c525ab0fc69e">

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [X] OSX
 - [] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: macOS 14.0
 - Kodi version: Kodi 20.2
 - Catch-up TV & More version: 0.2.38+matrix.1
 - Installation method: Official Kodi repo

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment]
Can you give the link of the webpage where one can watch live in a web browser? I am unable to find it. In this website, I feel like a French guy in Brugge :D 

Here, direct stream link is useless (empty data). One surely needs to do some before requesting the stream.

**Comment by joaopa00** [comment]
For me the link works without any sign-in. Can you confirm?
vlc 'https://hls-origin01-focus-wtv.cdn01.rambla.be/main/adliveorigin-focus-wtv/_definst_/WqY7Y3.smil/playlist.m3u8'



    Le mercredi 18 octobre 2023 à 08:49:57 UTC−10, maanwater ***@***.***> a écrit :  
 
 


Haha, metaphor of the day :)

The livestream can be found on this page: https://focus-wtv.be/focus

**Comment by joaopa00** [comment]
I implemented the link. I hope it can play in Kodi too with no registration. At least, that works for me.
If you can try that git works for you, it would be nice.

**Comment by maanwater** [comment]
Thanks! I would be more than happy to test, but can you point me to the git / instructions on how to? I would expect a zip with a new version - or am I wrong?

**Comment by joaopa00** [comment]
You are right. Here is a ZIP to test:
[zip to test](https://docs.google.com/uc?export=download&id=1Yj6H0j1eUGSZWl8gT7O3If496a40UQJL)

**Comment by maanwater** [comment]
I'm getting a 403 error on this link. Could you make the URL public?

**Comment by joaopa00** [comment]
Je supposue que le site doit garder en mémoire l'IP des inscrits puisque je n'arrive pas à produire l'erreur.
C'est embêtant pour reproduire...

**Comment by joaopa00** [comment]
This time it should be really fixed
Can you download and install the [test version](https://codeload.github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/zip/refs/heads/dev)

**Comment by joaopa00** [comment]
Bonne nouvelle. Je ferme alors
