### ISSUE TITLE
BE France 3 http error 422

### ISSUE THREAD

**Issue by wilfarte** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1235]
Catch-UP 0.2.39 beta 39
Nvidia Shield

http error when trying to look France 3 Live TV ( same issue with France 2 )
I can see CountryCode=BE in the URL. Perhaps a new Geo restriction ?
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/13051982/kodi.log)

**Comment by wilfarte** [comment]
All seems to work now... Strange

**Comment by joaopa00** [comment]
so I will close this ticket. If the problem reappears, please reopen.
