### ISSUE TITLE
Slovenian channels : outdated plugin

### ISSUE THREAD

**Issue by karlo2105** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1237]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
A clear and concise description of what the bug is: Slovenian channels are no more working. 

### To Reproduce
Steps to reproduce the behaviour:
1. https://365.rtvslo.si/vzivo/tvs1
    https://www.rtvslo.si/tv/vzivo/tvs1
2. https://365.rtvslo.si/vzivo/tvs2
    https://www.rtvslo.si/tv/vzivo/tvs2
3. https://365.rtvslo.si/vzivo/tvs3
    https://www.rtvslo.si/tv/vzivo/tvs3
4. https://365.rtvslo.si/vzivo/tvmb
    https://www.rtvslo.si/tv/vzivo/tvmb
5. https://365.rtvslo.si/vzivo/tvkp 
    https://www.rtvslo.si/tv/vzivo/tvkp
6. https://365.rtvslo.si/vzivo/tvmmc
    https://www.rtvslo.si/tv/vzivo/tvmmc
7.  https://www.rtvslo.si/tv/vzivo/tvs1a

Radios : 
1. https://prvi.rtvslo.si/
2. https://val202.rtvslo.si/
4. https://ars.rtvslo.si/
7. https://www.rtvslo.si/radio-si
9. https://www.rtvslo.si/radio-maribor
10. https://www.rtvslo.si/radio-koper
11. https://www.rtvslo.si/radio-capodistria
13. https://www.rtvslo.si/mmr

### Expected behaviour
A clear and concise description of what you expected to happen: Clicking on channel shall open it instead of displaying error. 
Channels are bound with cookies : 
https://cdn-live.rtvslo.si/hls/live/2095063/slo1_ott/playlist.m3u8?hdnts=exp=1698056227~acl=*~hmac=24197325ab3377ec21102e7c1ca476904dc348d9637119d31894f655c4409987

API : https://api.rtvslo.si/stats/logstream/liveplay/1/5934342110/0/?t=294&_=56629

### Your environment
 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: Android 10
 - Kodi version: 20.2
 - Catch-up TV & More version: Latest developing build
 - Installation method: https://catch-up-tv-and-more.github.io/repo/

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment]
Should be fixed in git.
Radio channels are implemented in CUTVM only if they have a video streaming. Why? Mainly because Inputstream Adaptive can not stream hls streams with no video. It will be implemented in Kodi 21. So, maybe we will accept radio with no video stream in CUTVM then.
