### ISSUE TITLE
Cannot access replay from L'équipe

### ISSUE THREAD

**Issue by fredgenin** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#124]
Hi,

I am using Catch-TV & More 0.2.1 on a RBPI2 with OSMC.
I cannot access replay from L'équipe since yesterday.

I get the following error message:
ValueError
time data '2019-00-20' doesn't match format u'%Y-%m-%d'

Live TV on the same channel works fine.

**Comment by wwark** [comment]
Hello @fredgenin ,

We are aware of this change in the website of l'equipe.
We made a fix on the beta release of the plugin. It is available in the beta repo. 0.2.2~betaxx.

Thank you,
Wwark.

**Comment by fredgenin** [comment]
Thank you very much!

**Comment by wwark** [comment]
Ok good we will close this ticket when the beta will be release.

**Comment by wwark** [comment]
The Kodi version 18 is out.
So the release of the plugin is also done. It contains the fix for l'équipe TV.

I will close this ticket.
Do not hesitate if you want to reopen it.

Thank you,
Wwark
