### ISSUE TITLE
Rmcbmplay is broken on leia with last beta version 

### ISSUE THREAD

**Issue by meeuuh92** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1240]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
A clear and concise description of what the bug is:
With the last  beta version, rmcbfmplay don't work on kodi leia... Is a bug on code or url modification ?

Regards,
### To Reproduce
Steps to reproduce the behaviour:
1.
2.
3.
4.

### Expected behaviour
A clear and concise description of what you expected to happen:

### Actual behaviour
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version:
 - Catch-up TV & More version:
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment]
J'ai testé sous Windows Kodi 18 puisqu'un utilisateur a dit que pour lui cela fonctionnait sous Leia indows. Et je le confirme. C'est donc un probème de Kodi ou IA sous Linux.
Il n'ya rien que CUTVM puisse faire dans ces conditions. Je ferme.
