### ISSUE TITLE
IPTV Recorder

### ISSUE THREAD

**Issue by bou-rat** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1241]
Bonjour,
Je ne parviens pas à installer IPTV Recorder en suivant ce guide : https://catch-up-tv-and-more.github.io/fr/live_tv_installation/#iv-enregistrement-des-directs-tv
Existe-t-il une autre méthode d'installation ou bien une alternative à cette extension dont le développement a l'air d'avoir été abandonné ?
Merci pour vos réponses

**Comment by joaopa00** [comment]
Report complètement inutile puisqu'il n'y a aucune information. IPTV fonctionne bien pour moi. Il n'a pas besoin d'être mis à jour. Si tu as un probleme ouvre un report de bug utile avec les informations qui sont demandées dans le canevas.
