### ISSUE TITLE
Accès à NRJ 12

### ISSUE THREAD

**Issue by velosolex** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1244]
Bonjour,
En lieu et place des programmes de la chaîne NRJ 12, j’ai une bande annonce des programmes de la chaine qui tourne en boucle et le message suivant en haut de l’écran “Le programme en cour de diffusion n’est pas disponible sur cette application et site web”.
Je crois que pour accéder à la chaîne il faut un compte, mais dans l’interface de configuration de Catch Up TV pas de compte NRJ 12 à paraméter.

Ma version de Catch UP TV => 0.2.39~beta39.

**Comment by joaopa00** [comment]
Pour NRJ12, le message est clair. NRJ12 n'a pas les droits de diffusion de certains programmes pour internet. DOnc pas de retransmisson par internet.
Si vous allez sur le site de NRJ12 pendant que le bandeau défile, vous aurez la même chose même si vous vous connectez avec un compte.

**Comment by joaopa00** [comment]
Pour France TV, c'estun problème connu de Inputstream adaptive. Peut-être que j'implémenterai une mthode de contournement. POur le moment, vous pouvez bidouillé avec la ligne de temps de diffusion de kodi lorque le programme est joué.

**Comment by velosolex** [comment]
Merci @joaopa00 pour le retour rapide :)
