### ISSUE TITLE
Auto update missing

### ISSUE THREAD

**Issue by karlo2105** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1245]
**Is your feature request related to a problem? Please describe.**
I installed developing build 0.23.9beta39 from this source : https://catch-up-tv-and-more.github.io/repo/ 
My addon hasn't been updated with last release 4 days ago. 

**Describe the solution you'd like**
Normally, when new stable or beta build is released, it shall update automatically from source address above. 

**Describe alternatives you've considered**
Alternative solution is to pick up latest addon manually, but in that case what's the purpose of repo address.

**Comment by joaopa00** [comment]
Devrait être fixé maintenant. Je ne promets pas que cela marchera pour la beta 40, mais pour la beta 41, cela devrait fonctionner.
