### ISSUE TITLE
Can't integrate Catch Up TV to IPTV simple

### ISSUE THREAD

**Issue by stemy2** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1246]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
I tried to integrate the TV channels from "Catch-up TV and more", but it doesn't work. I followed the instructions, but the channels i enabled still not appear in the TV section. I don't get what i did wrong.

### To Reproduce
1. Follow [these instructions](https://catch-up-tv-and-more.github.io/live_tv_installation/)

### Expected behaviour
Channels from catchuptvandmore  plugin visible at the TV section.

### Actual behaviour
No channel i selected is visible.

### Your environment
 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: linux mint 21.2
 - Kodi version: 20.2
 - Catch-up TV & More version: 0.2.39beta39
 - Installation method: third-party repository

**Comment by stemy2** [comment]
Yes, the extension is installed and active.

**Comment by joaopa00** [comment]
Did you  set up iptv simple to use local playlist instead of internet playlist?

**Comment by joaopa00** [comment]
Did you  set up iptv simple to use local playlist instead of internet playlist?

![Screenshot_20231121_144523](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/13057733/440024d9-7737-44a3-9e47-a863fc2143b5)

**Comment by stemy2** [comment]
Yes.

The m3u already contains an URL to a stream, but remains unchanged after i tried to add channels from Catchup TV.

**Comment by joaopa00** [comment]
Need a log with debug enabled in Kodi/system and libcurl channel enabled

**Comment by joaopa00** [comment]
C'est un problème connu de IPTV simple pas de CUTVM.
[problème rapporté à IPTVSIMPLE](https://github.com/add-ons/service.iptv.manager/issues/107)
