### ISSUE TITLE
Error when trying to watch some France5 replay

### ISSUE THREAD

**Issue by alexismorillo** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#125]
On some replay on France5, I get the following erro in the log :
`15:05:03.935 T:1382019840   FATAL: [Catch-up-TV-&-More.support] argument of type 'NoneType' is not iterable
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 282, in run_callback
                                                results = route.function(parent_ins, **self.callback_params)
                                              File "/home/pi/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/francetv.py", line 399, in get_video_url
                                                plugin, broadcast_id, item_dict, download_mode, video_label)
                                              File "/home/pi/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/resolver_proxy.py", line 276, in get_francetv_video_stream
                                                if 'cloudreplayfrancetv' in url_selected:
                                            TypeError: argument of type 'NoneType' is not iterable
15:05:03.936 T:1382019840 WARNING: ###### debug ######
15:05:03.936 T:1382019840 WARNING: [Catch-up-TV-&-More.support] Dispatching to route: '/resources/lib/channels/fr/francetv/get_video_url/'
15:05:03.936 T:1382019840 WARNING: [Catch-up-TV-&-More.support] Callback parameters: '{'item_id': u'france-5', 'item_dict': {u'info': {u'plot': u'Au Kirghizistan, pour livrer aux enfants des villages isol\xe9s les cl\xe9mentines offertes par le P\xe8re No\xebl, des chauffeurs routiers affrontent le massif du Pamir.', 'aired': u'2018-11-22', 'title': u"Les routes de l'impossible - Kirghizistan : les ravitailleurs du grand froid", u'mpaa': u'TP', u'tvshowtitle': u"Les routes de l'impossible", u'season': 7, u'director': u'Philippe Lafaix, Daniel Lain\xe9', u'cast': [], 'year': u'2018', 'date': u'22.11.2018', u'duration': 3120}, u'art': {u'fanart': u'http://api-front.yatta.francetv.fr/image/vignette_16x9/1024/576/0/4/2/a5b40380-d4c2df6205d743469e1d5ba87475a79685098e1fd715e87a1bf3dbd9bf462240.jpg', u'thumb': u'http://api-front.yatta.francetv.fr/image/vignette_16x9/400/225/0/4/2/32e52604-d4c2df6205d743469e1d5ba87475a79685098e1fd715e87a1bf3dbd9bf462240.jpg'}, u'stream': {}, u'label': u"Les routes de l'impossible - Kirghizistan : les ravitailleurs du grand froid", u'params': <class 'codequick.listing.Params'>({'item_id': u'france-5', '_title_': u"Les routes de l'impossible - Kirghizistan : les ravitailleurs du grand froid", 'id_yatta': 815631, 'item_dict': {...}}), u'context': {u'T\xe9l\xe9charger': 'XBMC.RunPlugin(plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/francetv/get_video_url/?_pickle_=80027d71002855076974656d5f6964710158080000006672616e63652d357102550d646f776e6c6f61645f6d6f6465710388550869645f796174746171044a0f720c00550b766964656f5f6c6162656c710558570000004672616e63652035202d204c657320726f75746573206465206c27696d706f737369626c65202d204b69726768697a697374616e203a206c657320726176697461696c6c65757273206475206772616e642066726f69647106752e)'}, u'property': <class 'codequick.listing.Property'>({})}, 'id_yatta': 815631}'
15:05:03.936 T:1382019840 WARNING: [urlquick] Requesting resource: http://api-front.yatta.francetv.fr/standard/publish/contents/815631
15:05:03.936 T:1382019840 WARNING: [urlquick] Request headers: {u'Host': u'api-front.yatta.francetv.fr', u'Accept-language': u'en-gb,en-us,en', u'Connection': u'keep-alive', u'Accept': u'*/*', u'Accept-Encoding': u'gzip, deflate'}
15:05:03.936 T:1382019840 WARNING: [urlquick] Requesting resource: http://sivideo.webservices.francetelevisions.fr/tools/getInfosOeuvre/v2/?idDiffusion=fdb0fce9-d58c-4b51-ad34-2a99d51bf5f4
15:05:03.936 T:1382019840 WARNING: [urlquick] Request headers: {u'Host': u'sivideo.webservices.francetelevisions.fr', u'Accept-language': u'en-gb,en-us,en', u'Connection': u'keep-alive', u'Accept': u'*/*', u'Accept-Encoding': u'gzip, deflate'}
15:05:03.936 T:1382019840 WARNING: [urlquick] Attempting to decode with default encoding: 'utf8'
15:05:03.936 T:1382019840 WARNING: ###### debug ######
`

**Comment by wwark** [comment]
Bonsoir @alexismorillo,

Si vous cliquer sur ce lien présent dans vos logs : http://sivideo.webservices.francetelevisions.fr/tools/getInfosOeuvre/v2/?idDiffusion=fdb0fce9-d58c-4b51-ad34-2a99d51bf5f4

C'est le fichier json utilisé pour récupérer cette vidéo. Dans les status la vidéo est "Offline" et le donnée URL est à null.

Ceci explique que nous ne pouvons pas lire la vidéo .... Nous allons voir pour ajouter une notification indiquant que la vidéo est non disponible.

Merci,
Wwark

**Comment by alexismorillo** [comment]
Cette video ne devrait donc pas apparaître dans les menus ?

**Comment by wwark** [comment]
Bonjour,
La notification a été ajoutée sur la version 0.2.3~beta03 du plugin.
Encore merci pour avoir remonté ce point.

Wwark.

**Comment by wwark** [comment]
Url sur France 5 de la video = https://www.france.tv/france-5/les-routes-de-l-impossible/saison-7/815631-kirghizistan-les-ravitailleurs-du-grand-froid.html
