### ISSUE TITLE
Impossible d'installer IPTV Recorder

### ISSUE THREAD

**Issue by bou-rat** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1250]
### Describe the bug
Impossible d'installer IPTV Recorder en suivant le [guide](https://catch-up-tv-and-more.github.io/fr/live_tv_installation/#iv-enregistrement-des-directs-tv).
La section "Vidéo Extensions" du dépôt primaeval n'apparait pas (seule la section "Add-on repository" est affichée)

### To Reproduce
1. Télécharger le fichier repository.primaeval-0.0.2.zip
2. Installer le fichier zip
3. Installer depuis un dépôt -> Ouvrir "primaeval's beta dev repository"

### Screenshots
![image](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/82725343/73e5af6d-55a8-4baf-9d68-89dfc2a6a85f)

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Other

 - Operating system version/name: Windows 10
 - Kodi version: 20.2 (Nexus)
 - Catch-up TV & More version: 0.2.39 beta40

**Comment by joaopa00** [comment]
Le plugin ne fonctionne pas sur Matrix et supérieur.
[problème reporté sur le github du plugin](https://github.com/primaeval/repository.primaeval/issues/4)
