### ISSUE TITLE
FR - TF1 ne fonctionne plus

### ISSUE THREAD

**Issue by Gwenbzh29** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1257]
Erreur lors du chargement du dossier TF1 depuuis quelques jours, un message d'erreur indique que le chargement du dossier est impossible. Les autres chaines (M6, France TV, etc ..) fonctionnent.

KODI 20.2 avec plugin beta 0.39 sur android TV

**Comment by EnderEOC** [comment]
Essaye ça
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1255\#issuecomment-1872915129

**Comment by joaopa00** [comment]
Patch dans git. 
Merci à SebMourlhou.

Je ferme.

**Comment by Gwenbzh29** [comment]
Merci 😊
