### ISSUE TITLE
FranceTV - Stream okoo au lieu des programmes normaux.

### ISSUE THREAD

**Issue by Shasdo** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1262]
### Describe the bug
Les chaînes FranceTv diffusent du okoo au lieu des programmes normaux.

### To Reproduce
Aucune idée.

### Expected behaviour
Avoir le direct, tel que visible sur le site FranceTV

### Actual behaviour
Stream okoo au lieu du live normal.

### Your environment
 - [X] Android 11 - Nvidia Shield Pro 2019
 - Kodi version: 20.2
 - Catch-up TV & More version: 0.2.40-beta00
 - Installation method: Depot Catch-up 

### Additional context
Bug ou fonctionnement normal ?
À midi le direct est remplacé par des stream Okoo.

Sur FR3 au lieu du JT "ICI" c'est okoo puis ça a repris le cours normal quand ça a basculé sur "le temps d'un détour".

Sur France 5  c'est que du okoo , encore jusqu'à 12h45 au moment où j'écris.

Sur France 4 idem.

Chaque programme okoo est différent d'une chaîne à l'autre.
Même problème hier.

### Debug log
Je regarde ce que je peux faire.

**Comment by enigma131** [comment]
Fonctionnent toutes ici, channel list 1.022. Linux Mint.

**Comment by joaopa00** [comment]
Pareil qu'Enigma. Il y a eu des problèmes, mais cela semble être résolu. Surement des tests du côté de FranceTV

**Comment by joaopa00** [comment]
Ne pas hésiter à réouvrir si le problème persiste chez quelqu'un
