### ISSUE TITLE
C8 not working

### ISSUE THREAD

**Issue by OoAnikioO** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1263]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
C8 not working (dailymotion and my canal) with no error message for dailymotion

### To Reproduce
Steps to reproduce the behaviour:
1. try to play c8
2.
3.
4.

### Expected behaviour
A clear and concise description of what you expected to happen: 

### Actual behaviour
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [X ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: last
 - Catch-up TV & More version: beta and dev
 - Installation method: zip

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by enigma131** [comment]
Is working here, latest beta and channel list 1.022

**Comment by OoAnikioO** [comment]
channel list 1.022 ?

**Comment by enigma131** [comment]
Clic on extensions, my extensions, then all. Update if need.

**Comment by joaopa00** [comment]
Refonctionne chez moi avec qualité défaut. J'avais le problème avec la qualité défaut. Mais en choissisant la qualité avec dialogue, cela fonctionnait. Maintenant tout refonctionne avec la qualité défaut.

Comme d'habitude je parle du flux dailymotion puisque les flux Mycanal sont complètement cassés.
