### ISSUE TITLE
error json

### ISSUE THREAD

**Issue by monfiston** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1269]
Other correlec 9.2.8

Operating system version/name:

Kodi version:18.9

Catch-up TV & More version: 0.2.40 beta 00

Installation method:

Additional context
hello
for a few days the live French channels as well as the replay no longer work, I have a json error

![20240128_185151](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/109015014/ac56d257-42c6-44dc-a576-e08187d9d55b)

**Comment by joaopa00** [comment]
Works fine for me. You have to give the steps to reproduce

**Comment by monfiston** [comment]
every time I want to watch a show or a replay, on my 2 devices while it was working last week

**Comment by joaopa00** [comment]
That is not enough. You have to say what channel, what show etc....

**Comment by monfiston** [comment]
I just reinstalled Windevin, and everything works again sorry for disturbing you
