### ISSUE TITLE
Rmc decouverte

### ISSUE THREAD

**Issue by valsim60** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#127]
Bonjour à tous

Tout d'abord je tiens à vous remercier pour le travail effectué je l'utilise au quotidien.

Etant un acharné d'histoire, je voulais savoir si il etait normal que la chaine RMC decouverte ne comporte aucun replay alors que l on peut en trouver sur leur site ou avec les box des FAI ?

Cordialement Valentin bricout

**Comment by wwark** [comment]
Bonjour @valsim60,

Le site web de RMC Découverte a changé. Nous venons de releasé la version 0.2.2 du plugin qui corrige le problème rencontré en version 0.2.1.

Pouvez-vous tester?

Merci,
Wwark

**Comment by wwark** [comment]
Bonjour,

Je ferme ce ticket. N'hésite pas à le rouvrir si le problème est encore présent.

Merci,
Wwark
