### ISSUE TITLE
[Replay france.tv] Accès au sous-titres ?

### ISSUE THREAD

**Issue by ppoi202** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1270]
Bonjour,

Est-il possible d'ajouter la fonction pour avoir accès au sous-titres des replay de France.tv ?
Exemple avec la série "coeurs noirs" de France 2 ?
Cette fonction est disponible sur l'application officielle Android ou sur le sur le site internet.

Merci

**Comment by joaopa00** [comment]
Incapable de trouver cette série sur le site de FranceTV.

**Comment by ppoi202** [comment]
Tu peux prendre n'importe quelle série, nous n'avons pas accès au sous-titres.
Exemple avec la série "In Her Car" en ce moment.

![Capture d’écran_2024-02-27_09-54-37](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/119431637/3f8f14cd-ce94-4ef1-a181-e3dc980d0c55)

PS: Catch-up TV avec le commit c97b80e9462936b0e5f48a5d5f5ec8c53844acb0.

**Comment by sebmourlhou** [comment]
Salut,
Toujours pas de sous-titres avec les replay de francetv ?
C'est bon chez moi

**Comment by ppoi202** [comment]
Oui impeccable ! une grand merci :+1:
