### ISSUE TITLE
impossible de se connecter au dépôt release catch up

### ISSUE THREAD

**Issue by fonkdoctor** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1272]
### Describe the bug
Lorque j'essaie d'installer la dernière version stable de catchup-tv (depuis le depot "https://catch-up-tv-and-more.github.io/repo/Stable_channel/repository.catchuptvandmore.stable-0.0.6.zip"), le message d'erreur suivant apparait : 
"impossible de se connecter au dépôt release catch up".
Même comportement testé sur la version android tv ou windows 10 de Kodi

### To Reproduce
Steps to reproduce the behaviour:
1. installation dernière version de kodi (Kodi v20.3 Nexus), 
2. suivre les étapes d'installation de l'add on catchp-tv (version stable) sur le site https://catch-up-tv-and-more.github.io/fr/installation/

### Expected behaviour
reussite de l'installation

### Actual behaviour
message d'erreur : impossible de se connecter au dépôt 

### Screenshots
![sshot_kodi_1](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/19936643/d124ae7d-2e49-41b6-b272-8123946dbcf4)
![sshot_kodi_2](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/19936643/ad5257c1-8c74-4b9d-9408-666e2b057a58)

### Your environment
 - [X ] Android
 - [ X] Windows

 - Operating system version/name:
 - Kodi version: v20.3 Nexus
 - Catch-up TV & More version: v0.2.39

Merci et bonne journée !

**Comment by joaopa00** [comment]
Je confirme le  problème

**Comment by joaopa00** [comment]
J'espère avoir réglé le problème. A tester dans quelques heures pour que le dépot se mette à jour.

**Comment by fonkdoctor** [comment]
Bonjour,
Le problème est résolu !
Un grand merci pour votre aide :)

Très bonne journée !
