### ISSUE TITLE
Les chaines FRANCE TV sont Décalées -RPI4 - Libreelec

### ISSUE THREAD

**Issue by willow3411** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1273]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
A clear and concise description of what the bug is:
Decalage des programmes France TV ( France 2 , France 3, France 4 , France 5 ) 
### To Reproduce
Steps to reproduce the behaviour:
1.
2.
3.
4.

### Expected behaviour
A clear and concise description of what you expected to happen:

### Actual behaviour
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: Leia
 - Catch-up TV & More version: vers.40
 - Installation method:

### Additional context
Add any other context about the problem here:
J'ai depuis quelques mois un decalage sur les chaines de FRANCE TV . Alors c'est un decalage de a peu pres 2 h sur les programmes. Je veux dire par là que si je veux regarder le programme de 21h , ben j'ai le programme de 19h ....
Tout les reste fonctionne parfaitement.
Avez vous le meme soucis .
JE suis sur RPI4 , libreelec derniere version et kodi LEIA 
merci d'avance
Willow

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment]
C'est un problème connu de Inpustream Adaptive qui est déjà réglé dans la version de développement de Kodi. Il sera offciellement réglé lors de la sortie de Kodi 21 (Omega)
