### ISSUE TITLE
Chaine du groupe M6 probleme authentification

### ISSUE THREAD

**Issue by Motopomp** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1277]
Toutes les chaînes fonctionne bien sauf celle du groupe M6 (m6/w9/gulli/6ter).
Le problème est apparus sans modification de quoi que ce soit.
Chaque fois que je sélectionne une de ces chaînes un popup et le précise ERROR  - 6play: Échec de l' authentification.
Du coup je suis aller directement sur le site web, impossible de me connecter avec mon compte, impossible d'effectuer une demande de nouveau mot de passe, impossible de créer un compte avec la même adresse mail.
J'ai donc créer un nouveau compte avec une autre adresse mail, le compte fonctionne sur le site web, j'ai rentree le noveau compte et mot de passe dans l'appli , et tjrs le même message ERROR - 6play: échec de l'authentification …

### Your environment
 - [x ] Android: Mi-Box
 - Operating system version/name: Android 9
 - Kodi version: 20.2 nexus
 - Catch-up TV & More version: V0.2.40-beta00
 
 LOG:  "pas tres verbeux" 
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/14392333/kodi.log)

Nouveau LOG: avec libcurl et ffmpeg et video activé:
[kodi-250224.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/14395746/kodi-250224.log)

**Comment by enigma131** [comment]
Cela fonctionne comme il faut ici. Peut être un problème de DRM, tu as la même erreur pour le groupe BFM, ex RMC découverte ?

**Comment by Motopomp** [comment]
Re. Uniquement le groupe M6, pour toutes les autres chaînes , aucun soucis. En plus c'est apparus du jour au lendemain, sans aucune modification ou mise a jours. Alors évidemment j'utilise la version Bêta de CatchUpTv depuis quelques mois sur les conseils trouver ici même, quand il y a eu des soucis l'an dernier, sinon depuis pas de soucis.
Je doit bien avoué que je n'ose rien touché, ce système de visionnage tv est très précaire, alors quand cela fonctionne , je ne touche a rien et me borne a l'utilisé comme tel ……  ;) .

**Comment by joaopa00** [comment]
Sans log complet (avec les canaux libcurl ffmpeg, video activés) il est quasi impossible de connaître le problème de to installation. Car chez moi aussi tout fonctionne correctement.

**Comment by Motopomp** [comment]
J'imagine, je cherche un moyen d'en sortir un de ce fichu boitier, mais en consultant celui de l'extension e n'y ai pas vue grand chose.
je le rajouterais a mon post des que je l'aurai…

**Comment by ycmp64** [comment]
> * J’ai la même version de Catch-up TV & More (V0.2.40-beta00) et le même problème que @Motopomp a décrit. Quelle version utilisez vous @enigma131 et @joaopa00 ?
@Motopomp, avez vous trouvé une solution ?

**Comment by Motopomp** [comment]
Voila , j'ai modifié le post originel pour y ajouté un log "durement acquit"  ;)

**Comment by joaopa00** [comment]
As tu activé les canaux de déboggages libcurl, ffmpeg video pour obtenir un log plus complet?

Le problème existe -t-il si tu lance M6 directement depuis CUTVM?

**Comment by Motopomp** [comment]
Ola!
Alors, dans l'ordre, je ne sais pas si "les cannaux de deboggages libcurl et ffmp……"  sont activés , et je vais chercher et les activés, je reposterais le log.
Pour la seconde question, oui le meme probleme directement depuis CUTVM.
je te ferais les deux essaies et j'espere qu'il seront dans le log …… 
Merci du suivi.

**Comment by Motopomp** [comment]
second log posté

**Comment by joaopa00** [comment]
Il faut faire un log en utilisant CUTVM et non IPTV simple. IPTV simple mange tous les messages d'erreur.

**Comment by Motopomp** [comment]
Oki Doki, vais voir se que je peut faire , merci

**Comment by Motopomp** [comment]
Re: Me revoila avec , donc un nouveau Log "sans IPTV Simple" que j'ai desactivé.
[kodi-280224.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/14429446/kodi-280224.log)

**Comment by Motopomp** [comment]
Re: Me revoila avec , donc un nouveau Log "sans IPTV Simple" que j'ai desactivé.
[kodi-280224.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/14429446/kodi-280224.log)

**Comment by joaopa00** [comment]
Tu n'as pas désactivé iptv manager

>2024-02-28 06:47:17.889 T:2634     info <general>: [service.iptv.manager] [resources.lib.service] Service started


>2024-02-28 06:47:36.975 T:2601    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/6play/get_live_url/?_pickle_=80049565000000000000007d94288c075f7469746c655f948c224d3620e2809420496e63726f7961626c6573207472616e73666f726d6174696f6e73948c08786d6c74765f6964948c14433131382e6170692e74656c6572616d612e6672948c076974656d5f6964948c026d3694752e]
2024-02-28 06:47:41.435 T:2601    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/6play/get_live_url/?_pickle_=80049551000000000000007d94288c075f7469746c655f948c0e573920e280942057616b65205570948c08786d6c74765f6964948c14433131392e6170692e74656c6572616d612e6672948c076974656d5f6964948c02773994752e]
2024-02-28 06:47:50.203 T:2601    error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/6play/get_live_url/?_pickle_=80049558000000000000007d94288c075f7469746c655f948c1247756c6c6920e280942047756c6c69207570948c08786d6c74765f6964948c14433438322e6170692e74656c6572616d612e6672948c076974656d5f6964948c0567756c6c6994752e]

>2024-02-28 06:48:05.731 T:2634     info <general>: [service.iptv.manager] [resources.lib.service] Service stopped




Si tu ne sais pas comment le désactiver, supprime le completement avec toutes ses données ou alors miex mieux, désinstalle kodi et refait une installation propre.

**Comment by Motopomp** [comment]
effectivement, juste iptv simple  comme précisé plus haut , je vous fait cela dans la soirée …

**Comment by Motopomp** [comment]
Voila c'est fait, sans iptv manager, et sans iptv simple
[kodi-280224-1.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/14439192/kodi-280224-1.log)

**Comment by joaopa00** [comment]
Les canaux de déboggage ne sont pas activés.

**Comment by Motopomp** [comment]
tu parle bein de la journalisation libcurl et ffmpeg ?

**Comment by joaopa00** [comment]
oui

![journalisation](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/13057733/2ab45a16-d1f3-405c-ac90-fd7751252ebd)

**Comment by Motopomp** [comment]
apparemment activer, mais je recommencerais demain, et je re posterais le log obtenus . merci bcp

**Comment by Motopomp** [comment]
Bon, après vérification, la journalisation de Libcurl et de FFmpeg était bien activé…
J'ai quand mème recommencé , j’espère que cela ne dérangeras pas j'y ai ajouter Smb , car le partage na jamais fonctionné , quitte à faire des Log… , si cela pose problème je recommencerais sans .
J'ai activer aussi la fonction de debogage, evidemment le log est beaucoup plus verbeux et pese plus lourd, j'espere que tu pourras y trouver ce que tu cherche.
Merci d'avance.
[kodi-290224.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/14445062/kodi-290224.log)

**Comment by Motopomp** [comment]
Re: Je ne sais pas si il y a un rapport, mais j'ai eu d'autre messages d'erreur, j'avais re-activer iptv-manager et iptv-simple, pour récupéré les fonctionnalités du programme tv , et lors d'un changement de chaine un message d'erreur est apparus.
Sachant que le Log continué à s' incrémentais, je l'ai sauvegardé , j'ai relancé kodi et essayer dessuite de re-creer la meme erreur, ce qui c'est passé , j'ai donc deux log que je te met en dessous, si cela peut aidé…
Peut être serait il plus, rapide et efficace de supprimer Kodi et tout ces fichier (si je les trouve) et de refaire à nouveaux toute l' instillation de Kodi et de CUTAM… 
Voir si cela résout mes problèmes, ainsi que la possibilité d’avoir un log de comparaison…… ? 
1er log: [kodi-290224-1.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/14449366/kodi-290224-1.log)
2nd: [kodi-290224-2.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/14449481/kodi-290224-2.log)
Je remarque, qu’après avoir récupéré les log, écrit ce post et uploadé les logs, quand j'ai relancé Kogi  la liste des chaines et le programme avais disparus, vide.  Il a fallut relancé Kodi plusieurs fois pour le récupéré .

**Comment by sebmourlhou** [comment]
J'ai la même erreur (échec de l'authentification) depuis ce soir, en tout cas je m'en suis apperçu tout à l'heure alors que ça fonctionnait cette semaine.
Essayé sur plusieurs postes (androidtv et windows)

Comme Motopomp, impossible de me connecter sur le site de 6play.
Avec le lien "Mot de passe oublié", je n'ai jamais reçu d'email malgré plusieurs essais.
Contrairement à Motopomp, j'ai pu recréer le compte avec la même adresse email, ce qui est bizarre...
Bref, il semble que mon compte a été supprimé.

Par contre, j'ai quand-même toujours la même erreur d'échec d'authentification avec CUTVM.

EDIT : il a fallu attendre quelques temps après avoir recréé mon compte mais ça remarche maintenant.

**Comment by joaopa00** [comment]
Merci de ne pas réutiliser des fils pour des problèmes qui ne sont pas liés.

Si tu as d'autres problemes, ouvre un fil par problème s'il te plaît.
