### ISSUE TITLE
Lecture replay lcp ne fonctionne pas

### ISSUE THREAD

**Issue by gwalarn** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1279]
Bonjour

Erreur lors de tentative d'accès au replay de la chaine française LCP (le direct fonctionne correctement , seul le replay ne fonctionne pas:

Environnement logiciel:  rasbberrypi os , paquet kodi (3:20.3-3~bookworm) , catch-up an tv more (0.20.40-beta00.

Voici le log:
[kodi-pb_lcp.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/14385571/kodi-pb_lcp.log)

Merci pour une aide

**Comment by joaopa00** [comment]
Devrait être résolu dans GIT.

**Comment by gwalarn** [comment]
Merci beaucoup, la correction corrige parfaitement le problème : on peut ainsi accéder au replay de LCP.
