### ISSUE TITLE
[UK - UKTVPLAY] Live - uktvplay live playback fails

### ISSUE THREAD

**Issue by nictjir** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1281]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
uktvplay lve channels fail to play
There is no longer a channelStreamId  parameter in (URL_LIVE % channel_uktvplay_id)

### To Reproduce
Steps to reproduce the behaviour:
1. Select Live TV
2. Select United Kingdom
3. Select one of the uktvplay channels (dave, yesterday, drama, watch)
4. 

### Expected behaviour
Channel should start playing

### Actual behaviour
Error, index out of range

### Your environment
 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [X] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 20.2.0
 - Catch-up TV & More version: 0.2.39
 - Installation method: Install from zip downloaded from github

### Possible Solution
I cannot find a way to programmatically get the channelStreamId so I have done a static match. Hoping somebody can point me in the correct direction

**Comment by nictjir** [comment]
[uktvplay.txt](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/14404581/uktvplay.txt)

I can only find the channel IDs after selecting the channel on the web interface

**Comment by sebmourlhou** [comment]
Hi,
You can find the channel IDs with a GET request to https://vschedules.uktv.co.uk/vod/now_and_next/
This URL returns a JSON in which "channel_stream_id" can be easily retrieved by channel

**Comment by nictjir** [comment]
Indeed thankyou @SebMourlhou I will work with that

**Comment by snoopymail** [comment]
Is the Blaze TV Catchup section working for you?

**Comment by nictjir** [comment]
Submitted pull request for a fix for uktvplay live. Here is the updated file
[uktvplay.txt](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/14433221/uktvplay.txt)


blaze catchup dose not work - the info returned by the url
https://watch.blaze.tv/stream/replay/widevine/219028
is missing things like a token etc now - I see a seperate bug for blaze

**Comment by snoopymail** [comment]
Many thanks for that... quick question, do you know if there's any way to get the UK Channel 4 channels working in Kodi 18.9?

**Comment by nictjir** [comment]
This version of channel4.py may still work on older kodi
[channel4.txt](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/14491016/channel4.txt)

**Comment by snoopymail** [comment]
You are an absolute LEGEND [nictjir](https://github.com/nictjir)! Works perfectly on Kodi 18.9 (Windows 10), for both Live TV playback and catchup. Thank you so much!!!

**Comment by marson53** [comment]
Thanks for the uktvplay.txt fix, do I replace this file in the kodi catchuptv folder ,  lib , channels, UK , uktvplay.py , also do I change  your file uktvplay.txt to uktvplay.py for it to work,Thanks

**Comment by joaopa00** [comment]
We try to keep some compatibility with Kodi 18.9. If a problem occurs with this version, please open a new ticket. Sure other people will have this problem then.
