### ISSUE TITLE
UK BLAZE TV CATCHUP ERROR

### ISSUE THREAD

**Issue by snoopymail** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1282]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
A clear and concise description of what the bug is:
When attempting to playback any content from Blaze TV Catphup, the following error occurs: 

keyerror u tokenizer 

### To Reproduce
Steps to reproduce the behaviour:
1. 
2.
3.
4.

### Expected behaviour
A clear and concise description of what you expected to happen:

Playback should start

### Actual behaviour
Tell us what happens instead:

keyerror u tokenizer 

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 18.9
 - Catch-up TV & More version: Current version including latest dev
 - Installation method:
GIT & REPO

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by nictjir** [comment]
Can you replace the current blaze.py file in your kodi addon directory (addons/plugin.video.catchuptvandmore/resources/lib/channels/uk)

with this one- download it and rename it to blaze.py and see if things work again.

[blaze.txt](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/14435950/blaze.txt)

**Comment by snoopymail** [comment]
Works perfectly. Thank you so much! Unfortunately though, none of the UK live 5 Channels load (Channel 5, 5 Star, 5USA 5 Action & 5 Select)... No errors, they just don't load...

**Comment by snoopymail** [comment]
Sorry, ignore the last message about the UK live 5 channels not loading... They started working after updating Widevine.
