### ISSUE TITLE
Replay C8

### ISSUE THREAD

**Issue by Cathami** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1287]
Bonjour,
Depuis l'avant-dernière mise à jour de catch up, je ne peux plus voir les replays de C8, normalement en vision libre.
La dernière mise à jour n'a pas réglé ce problème...
L'erreur notifiée est : 
JSONDecodeError
Expecting value: Line 1 column 2413 (char 2412)
Version Catch up 0.2.40-beta01
Version Kodi Nexus
Système Windows 7 (oui, j'utilise mon vieux portable pour regarder la téloche).
J'habite en France et j'ai même un compte pour canal, le site.
Une solution à proposer ?
Merci d'avance

**Comment by IceFreak66** [comment]
I found a fix that works in mycanal.py

there's a json paring issue on the main listing

Replacing react_query_state = REACT_QUERY_STATE.findall(resp.text)[0]
with react_query_state = REACT_QUERY_STATE.findall(resp.text)[0].replace("undefined","\"undefined\"") fixes the issue

**Comment by geoffde** [comment]
Hi,

I've tried and the error is now INVALID SYNTAX(MYCANAL.PY, LINE 253)

**Comment by IceFreak66** [comment]
So I wasn't paying attention, but in my comment, it seems the escape characters were removed

The line is

`react_query_state = REACT_QUERY_STATE.findall(resp.text)[0].replace("undefined","\"undefined\"")`

Same line repeats both at LINE 253 and LINE 319

**Comment by geoffde** [comment]
It works like a charm !!! Thank you !

If you have an idea to also fix the CNEWS replay chanel, it would be marvelous :-)

**Comment by IceFreak66** [comment]
> It works like a charm !!! Thank you !
> 
> If you have an idea to also fix the CNEWS replay chanel, it would be marvelous :-)

Well I saw your post and tried to check on it, I'm running the lastest beta version, but I haven't encountered an issue launching the video feed. But I had the C8 fix running already, so maybe they're tied ? Have you retried cnews ?

**Comment by geoffde** [comment]
I also have the C8 fix but I still have the error when I try to accesss the CNEWS replay (when I ask "emission").

The CNEWS chanel have it's own .py (cnews.py) so I think there is no link between C8 and CNEWS.

I don't understand why it work for you and not for me (error 403 means it's forbidden to access to the content). What is your country ?

**Comment by IceFreak66** [comment]
I'm in France.

OK, I see the error, I checked on the MyCanal CNEWS replay, not on the CNEW independant replay.
I'll check on it, see if I can find something

**Comment by Cathami** [comment]
Bonjour, merci IceFreak66, votre solution, corrigée grâce à geoffde, fonctionne bien.
Je donne le MO pour les non-geeks comme moi :
Faites une recherche dans Windows explorer pour trouver le fichier mycanal.py
Sélectionnez le plus récent et ouvrez-le avec Wordpad (impossible d'installer Python sur Windows 7 !)
Faites une recherche du mot "findall" dans Wordpad - il ne revient que 3 fois.
Les deux premiers sont suivis de (resp.text)[0] après quoi, il faut ajouter .replace("undefined","\"undefined\"") les deux fois 
Enregistrer le fichier et relancer Kodi et Catch UP. Ça marche ! Bon, ça a ajouté deux dossiers undefined, que je préfère ne pas toucher, mais j'ai accès au reste.
Pardon les gars, mais je suis analphabète en programmation...
Merci encore pour la soluce !

**Comment by Cathami** [comment]
Oh! Je vois que les slash ne sont pas sortis - faites un copier-coller de la deuxième version de Icefreak par mesure de sécurité !

**Comment by joaopa00** [comment]
Patch soumis avec la modification de Icefreaks66 en son nom. Merci pour le patch.
