### ISSUE TITLE
CNEWS replay KO

### ISSUE THREAD

**Issue by geoffde** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1290]
Bonjour,

Le replay CNEWS n'est pas fonctionnel chez moi depuis des mois. J'utilise la version 0.2.40 beta 01 (mais le problème est présent sur toutes les autres anciennes versions).

L'erreur suivante apparaît lorsque l'on sélectionne le menu "CNEWS/Nos émissions": 

403 CLIENT ERROR : FORBIDDEN FOR URL : HTTPS://WWW.CNEWS.FR/LES-REPLAYS

Avez-vous le même problème ?

Vous remerciant

**Comment by joaopa00** [comment]
Pas de problème pour moi.

Il y a un canevas à remplir quand on rapporte un problème.  Sans celui, il n'y a rien que l'on peut faire.

**Comment by geoffde** [comment]
### Describe the bug

Impossible d’accéder aux replay CNEWS

### To Reproduce
Steps to reproduce the behaviour:
1. Je lance le plug-in
2. Télévision de rattrapage
3. France
4. CNEWS
5. Nos émissions

### Expected behaviour

La liste des émissions proposées en replay

### Actual behaviour

Là apparait 403 CLIENT ERROR : FORBIDDEN FOR URL : https://www.cnews.fr/LES-REPLAYS

### Your environment

Kodi 19.5 sur NAS QNAP (Linux) ou Kodi 20.2 sur Android (j'ai la même chose sur les 2)

Version du plug-in : 0.2.40 beta 01

**Comment by IceFreak66** [comment]
So it's basically an anti scraping issue, cloudflare is refusing the request to cnews website. 
I've tried playing around with the request headers with no luck. Maybe someone will know a way to bypass cloudflare anti scraping measures

**Comment by IceFreak66** [comment]
So, after some experimenting, using cfscrape will solve the issue

`import cfscrape


scraper = cfscrape.CloudflareScraper()
print(scraper.get("https://www.cnews.fr/les-replays").content)`

Unfortunatley, I would need to make a PR to update the plugin to the extent of switching the requests from urlquick to cfscrape, and I need to setup a whole dev env for that. So it would take some time. 
So if someone has a ready to go env, that's the solution.

I've seen the same issue in a number of other channels and replays entries, so that solution could apply elsewhere

**Comment by geoffde** [comment]
Thanks for your reply even if I don't know what is a PR.

If I understand, there is no easy solution (it's not a simple change in a .py file) to solve the problem.

But it's quite strange that a user (joaopa00) seems to not have the problem... Maybe he tried like you to go in the cnews menu in MyCanal ?

**Comment by IceFreak66** [comment]
PR is a pull request, it means I would submit a potentiel change that would require a peer review and community testing before being made available through a plugin version update.

But yeah, it's not a simple change, I can't seem to import the cfscrape module into kodi (I'm a beginner in kodi plugin development and python, I was initially just trying to fix some of the issues I was having)

And yeah, I would assume like me he was looking into the wrong cnews replay.

**Comment by geoffde** [comment]
You have found many fixes...

Thanks for the time spent and your help is precious.

**Comment by IceFreak66** [comment]
So, that took f******** forever to get it to work, but here you go. Working cnews live and replay.

You will need to uninstall your current plugin and install from zip file with the one I'm providing, since I added a new dependency that will need to be resolved at install.

Thanks to the people on the official kodi forum and VeNoMous for the cloudscraper module.

Here you go 
[plugin.video.catchuptvandmore.2.40.beta-modif-IceFreak.zip](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/14508258/plugin.video.catchuptvandmore.2.40.beta-modif-IceFreak.zip)

**Comment by geoffde** [comment]
Hi IceFreak66,

I've tested your plugin and I get au error opening cnews : Future feature annotation is not defined (__init___.py, line 28).

And this plug-in don't include the rmcbfmplay.py fix you've made.

Regards

**Comment by IceFreak66** [comment]
I've only tested it on windows 11 and Kodi 20.4.

Do you have more details in the kodi.log ?

**Comment by geoffde** [comment]
I have Kodi 19.5 on a QNAP NAS (Linux).

I don't really know how to get the kodi.log on a QNAP NAS...

**Comment by IceFreak66** [comment]
Might be the kodi version then. 
future import annotation error means you're using a python version <3.7

And the issue is probably somewhere in the cloudscraper import.
Maybe try and see in the qnap app center if you can update your python version

**Comment by geoffde** [comment]
I think the python module is in kodi, not in the qnap app center.

Now the python module have many many dependencies.

The only dependency not up to date is the urlib3 (I have the 1.26 version instead of the 2.10) because Catch-up TV can't be lunched on my system with the last version.

**Comment by IceFreak66** [comment]
So I tried it from a fresh install of Kodi 19.5 with no plugin whatsoever, and it ran fine.

To me it confirms that it's just a matter of what python version you have installed (kodi onboards a certain version of python, but if a newer one is installed, it will use that one).

Aside from downgrading my whole computer, I can't do much more.

**Comment by geoffde** [comment]
I've just installed Kodi 20.2 and it's exactly the same error on my side.

Where can I find the kodi installed python version ?

**Comment by IceFreak66** [comment]
I don't have a QNAP myself, but I'm guessing either there's a web interface in place to install apps or run command lines, or you open an ssh command line from your computer and your run python –version command

I have confirmed there's a python 3 package for qnap available.

**Comment by geoffde** [comment]
I've just installed python 3 (see below) in the qnap and exactly the same error.

My question was where can I find the installed python version **in kodi** ?

![Capture](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/161850201/681e37db-bb3c-4867-8d3f-065a4baed453)

**Comment by joaopa00** [comment]
Cloudflare ne demande plus la vérification. C'était certainement une erreur de configuration du serveur.
