### ISSUE TITLE
France info KO

### ISSUE THREAD

**Issue by YannBrrd** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1296]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
A clear and concise description of what the bug is:

### To Reproduce
Steps to reproduce the behaviour:
1.launch France info live
2.http clnnecgion failure

### Expected behaviour
A clear and concise description of what you expected to happen:
Live stream on

### Actual behaviour
Tell us what happens instead:
Http failure

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - Android

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by timetofly06** [comment]
See this workaround : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues

**Comment by Forage** [comment]
@timetofly06 you are linking to the issue list instead of a specific issue and/or comment.

**Comment by emmaanuel** [comment]
I've send a pull request fixing this bug : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/1299

**Comment by CChalu** [comment]
Hi,
I have always this issue today with FranceTV, catch up beta and Kodi nexus 20.5 on Android tv

**Comment by emmaanuel** [comment]
Pull request still waiting for approval by an administrator…

**Comment by CChalu** [comment]
Ok , perhaps they work on next kodi release…

**Comment by timetofly06** [comment]
Hi ! Sorry here is the correct link. I applied the new resolver file, and it works now like a charm : 

https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1285#issuecomment-1974020904

**Comment by joaopa00** [comment]
Pas de problème pour moi avec 0.40-beta-05
Je ferme. Si le problème persiste, vous pouvez réouvrir.
