### ISSUE TITLE
TV Catchup ne fonctionne pas sur Kodi Leia / don't work on Leia

### ISSUE THREAD

**Issue by cmoulliard** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#130]
## Probleme/Issue

J'ai suivi vos instructions comme decrites ici - https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/wiki/Add-the-official-repository#how-to-add-the-repository-on-my-kodi pour installer a partir du zip Tv Catchup sur Kodi 18 (Macos) mais suite a l'installation l'icone de l'addon n'apparait pas et le log remonte les messages suivants

I followed your instructions as described here - https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/wiki/Add-the-official-repository#how-to-add-the-repository-on-my-kodi to install from the zip file TV Catchup on Kodi Leai (macos) but following the installation, then the addon icon of catchup don't appear. See screenshots here after

```
07:07:04.316 T:123145447944192 WARNING: Repository add-on catchuptvandmore.kodi.leia.drmtest uses plain HTTP for add-on downloads in path http://raw.github.com/Catch-up-TV-and-More/repository.catchuptvandmore/master/zips/leia_drmtest - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
07:07:04.319 T:4730373568  NOTICE:   load skin from: /Applications/Kodi.app/Contents/Resources/Kodi/addons/skin.estuary (version: 2.0.21)
07:07:04.524 T:123145447944192 WARNING: Repository add-on catchuptvandmore.kodi.leia.drmtest uses plain HTTP for add-on downloads in path http://raw.github.com/Catch-up-TV-and-More/repository.catchuptvandmore/master/zips/leia_drmtest - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
07:07:04.554 T:4730373568 WARNING: Previous line repeats 2 times.
07:07:04.554 T:4730373568 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
07:07:04.599 T:4730373568  NOTICE: Register - new keyboard device registered on application->keyboard: Keyboard (0000:0000)
07:07:04.599 T:4730373568  NOTICE: Register - new mouse device registered on application->mouse: Mouse (0000:0000)
07:07:04.601 T:4730373568  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
07:07:04.601 T:4730373568  NOTICE: Loaded playercorefactory configuration
07:07:04.602 T:4730373568  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
07:07:04.602 T:4730373568  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
07:07:04.604 T:4730373568 WARNING: Repository add-on catchuptvandmore.kodi.leia.drmtest uses plain HTTP for add-on downloads in path http://raw.github.com/Catch-up-TV-and-More/repository.catchuptvandmore/master/zips/leia_drmtest - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
```

<img width="1352" alt="screenshot 2019-02-08 07 19 05" src="https://user-images.githubusercontent.com/463790/52462074-de286980-2b71-11e9-8038-d9d704e2906b.png">
<img width="1240" alt="screenshot 2019-02-08 07 17 27" src="https://user-images.githubusercontent.com/463790/52462076-dec10000-2b71-11e9-942f-2557198f2314.png">

**Comment by wwark** [comment]
Bonjour @cmoulliard,

Le repo et le plugin "catchuptvandmore.kodi.leia.drmtest" sont dépréciés. Ils ont été créés pour cas de tests.

Le répo catchuptvandmore.kodi.krypton.release-0.0.4.zip peut être installé sur Kodi 17 et Kodi 18 (compatible kodi17 et version supérieur).
Pouvez-vous tester de nouveau avec ce plugin pour voir si le problème est aussi présent?

Merci,
wwark

**Comment by cmoulliard** [comment]
I did a new test where kodi leia 18 were reinstalled on my macbook and I experiment the same issue using release krypton

<img width="1805" alt="screenshot 2019-02-08 08 32 12" src="https://user-images.githubusercontent.com/463790/52464691-25b3f300-2b7c-11e9-8f75-dca1af8db2ab.png">

**Comment by wwark** [comment]
Ok I take a look again to your screenshot and for me the repository is well deployed.
After what you need to install the plugin in this repository.

The repository is used to update the plugin when a new version is available.

You need to go to this menu and you are able to install the plugin.

![screenshot from 2019-02-08 10-01-43](https://user-images.githubusercontent.com/469461/52468308-9eb94780-2b88-11e9-83f8-4d2552ff3268.png)

Thanks,
Wwark

**Comment by wwark** [comment]
You can also follow this website (described with screenshot how to install)
https://catch-up-tv-and-more.github.io/

**Comment by cmoulliard** [comment]
That works better now. Problem is resolved. Many thanks for your help
