### ISSUE TITLE
RTL-TVI PLUBRTL CLUBRTL URL not found error 404

### ISSUE THREAD

**Issue by wilfarte** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1303]
On nvidia Shield
Kodi 20.5
Catchup TV more 0.2.40

From TV guide or from Catchup menu, I got a 404 https error with url e.m6web.fr

**Comment by dmu7004** [comment]
Hello,

Have the same issue with kodi on RPi 4.
RTBF Audio doesn't work too.

**Comment by pokemaster974** [comment]
Yes, got a 404 too for https://e.m6web.fr/info?customer=rtlbe
I didn't find another link how RTLplay determines the device_id.

**Comment by darodi** [comment]
a random uuid seems ok for the device id, like with rtbf
