### ISSUE TITLE
replay broadcast forbidden zone/turbo on M6 France

### ISSUE THREAD

**Issue by monfiston** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1305]
⚠️hello

I work under kodi 18.9 or kodi 20.4 (coreelec)
the dates of the program prohibited zones in replay of M6 France, do not correspond to anything
there are several shows which have the same broadcast date, which is not normally possible, because there is 1 every 2 weeks

![Capture d'écran 2024-03-24 080917](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/109015014/08981447-b25e-4a4b-8888-14636d282613)

**Comment by monfiston** [comment]
it's also the same for the turbo emission on m6 fr

**Comment by joaopa00** [comment]
Pas de problème pour moi
![Screenshot_20240407_034758](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/13057733/71c11ff3-77f4-480d-a77f-056e7249fd04)

**Comment by monfiston** [comment]
bonjour
maintenant, oui, le pb a été corrigé
