### ISSUE TITLE
HttpError Error 400 

### ISSUE THREAD

**Issue by glenan** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1306]
### Describe the bug
All channels seem to be out,
Tried on Kodi Nexus last version and Catchuptvandmore last beta 
Same problem with Kodi windows Nexus last stable version

### To Reproduce
Steps to reproduce the behaviour:
Simply try to see any FranceTV channel for exemple

### Screenshots
![image](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/assets/31369452/2af41e67-783d-47ab-b70a-fca0fa850455)

### Your environment
 - [ X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 20.5 Nexus 
 - Catch-up TV & More version: 0.2.39 Beta 39
 - Installation method:

**Comment by CChalu** [comment]
Hello, 
I have this bug with FranceTV only. MyTF1 or 6play work fine.
An other addon France.tv has solved this issue with francetv channels but i don’t know if this is the same…

**Comment by enigma131** [comment]
Same here for France TV

**Comment by monfiston** [comment]
yes Same here for France TV

**Comment by glenan** [comment]
> Hello, I have this bug with FranceTV only. MyTF1 or 6play work fine. An other addon France.tv has solved this issue with francetv channels but i don’t know if this is the same…

Thanks a lot for this information !!! France tv works with it !

**Comment by CChalu** [comment]
Hello,
France TV with catch up is always ko with error HTTPError 404. 
On Android TV 9 (Sony TV) with Kodi 20.5 up to date and catch up tv 0.2.40~beta02 up to date.

**Comment by glenan** [comment]
> Hello, France TV with catch up is always ko with error HTTPError 404. On Android TV 9 (Sony TV) with Kodi 20.5 up to date and catch up tv 0.2.40~beta02 up to date.

Install separate France tv extension. It works with it.

**Comment by CChalu** [comment]
I have the same bug, only with France TV,  with kodi 20.5+catchup-tv 0.2.40~beta02 on flatpak +Linux
I know that France-tv, an other addon works but it's not catchup...

**Comment by enigma131** [comment]
Look my post in #1285 , solve issue here

**Comment by CChalu** [comment]
Thank you, but solve … except for … it’s not solve :)
On Android tv, copy, paste are hard. For example, i can’t copy a Kodi log on USB key.
Perhaps with Kodi 21, catch up work with France tv

**Comment by enigma131** [comment]
No kodi 21 will not solve the problem, catchup is a separate development. The Pull request is still at his place, and no admin have compiled a new version I agree.

**Comment by sebmourlhou** [comment]
It works with the last version 0.2.40~beta03 available on Android TV

**Comment by CChalu** [comment]
Yes, it works now. Thank you

**Comment by joaopa00** [comment]
closing then
