### ISSUE TITLE
SFR TV services not working

### ISSUE THREAD

**Issue by daufinsyd** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1307]
### Describe the bug
When I try to use the SFR TV services I get the errors shown in the attached file.

### To Reproduce
Steps to reproduce the behaviour:
1. enter sft tv credentials in the addon config
2. go to the live tv (or replay, or vod)

### Expected behaviour
Live TV channels are shown / can be played

### Actual behaviour
Nothing happen but a error message

### Screenshots
N/A

### Your environment
I tried with a Rasbperry and a Mac, having the same error.

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [x] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: MacOS Ventura 13.4.1 / OSMC 2024.02 (Raspberry pi 4)
 - Kodi version: 21.0-RC2 / 20.3
 - Catch-up TV & More version: 0.2.40 (both)
 - Installation method: Per official repo (both)

### Additional context
Using tv.sfr.fr and the same account from the PC I can watch content (eg liveTV).

I installed a new Kodi with only CatchUp TV Addon.

### Debug log
[catchup.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/14762186/catchup.log)

**Comment by daufinsyd** [comment]
This relates to https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/1248 (I guess)

**Comment by enigma131** [comment]
Pr make it working again, thanks!

**Comment by daufinsyd** [comment]
Thank you ! :D

**Comment by joaopa00** [comment]
Commited. Thanks for the patch.
