### ISSUE TITLE
Aljazeera English error

### ISSUE THREAD

**Issue by ltai0001** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1313]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
A clear and concise description of what the bug is: https://paste.kodi.tv/putalaneru

### To Reproduce
Steps to reproduce the behaviour:
1.launch aljazeera english
2.
3.
4.

### Expected behaviour
A clear and concise description of what you expected to happen:

### Actual behaviour
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:libreelec 11.95.1.12.0
 - Kodi version:
 - Catch-up TV & More version:0.2.40~beta02
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment]
Fixed in the latest beta.
