### ISSUE TITLE
erreur 403  catchup/RMC découverte

### ISSUE THREAD

**Issue by donbeaupapa** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1315]
⚠️

salut à tous,

 Depuis hier, quand je veux regarder la chaine RMC découverte j’ai une erreur 403 qui est signalé, j’ai ré installer catchup mais sa change rien! je suis sous Windows 10 et c'est fresh install de la dernière version de kodi

salut à tous,

Depuis hier, quand je veux regarder la chaine RMC découverte j’ai une erreur 403 qui est signalé, j’ai ré installer catchup mais sa change rien!

merci d’avance!!

**Comment by joaopa00** [comment]
Pas de problème pour moi.
Si le problème persiste, il faut remplir le canevas de bug comme proposé lors de la rédaction initiale du bug. C4est pour ça qu'il est là.

**Comment by donbeaupapa** [comment]
ha ok!! t'en mieux!!!

**Comment by joaopa00** [comment]
je ferme. Si ca continue à se produire, n'hésite pas à réouvrir avec les infos nécessaires.
