### ISSUE TITLE
Some French and Belgian live TV channels not playing

### ISSUE THREAD

**Issue by Stevyb** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1329]
Hi, Some live channels are not working on beta version :

**- Belgium playlist :**
RTL play
RTL Club
RTL tvi
LN24
Télé MB

**- French playlist :** 
France 5
TF1
RMC story

Thanks for updating !

**Comment by darodi** [comment]
@Stevyb 

RTL play and RTL channels are already fixed in 0.2.40~beta04 in 
- https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/1314  

This beta is not released yet but you can use the git code from branch dev

**Comment by joaopa00** [comment]
Je pars du principe qu'il faut mieux une issue par chaine (bug). En général, les problèmes ne sont pals liés.
SI des problèmes persistent, merci d'ouvrir un rapport de bug par chaine.
