### ISSUE TITLE
UKTV Play Catchup - 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by 43qcc2cn** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1335]
### Describe the bug
Unable to play anything on UKTV Play Catchup.

### To Reproduce
Steps to reproduce the behaviour:
1. Select any program from the menus.

### Expected behaviour
Program plays.

### Actual behaviour
Script errors.

### Screenshots
N/A

### Your environment
LibreELEC

 - Operating system version/name: LibreELEC 11.0.6
 - Kodi version: 20.3.0
 - Catch-up TV & More version: v0.2.40~beta04
 - Installation method: From repo

### Additional context
I'm guessing the web site has changed again.

### Debug log
https://paste.kodi.tv/tutumuyeme.kodi

**Comment by jeff2900** [comment]
Fix in Pull requests #1342

**Comment by 43qcc2cn** [comment]
Tested successfully. Many thanks.

**Comment by joaopa00** [comment]
Merged and beta released. Thanks at Jeff for his hard work.
