### ISSUE TITLE
Channel 4 Catchup - 'image16x9'

### ISSUE THREAD

**Issue by 43qcc2cn** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1344]
### Describe the bug
Unable to list anything for programs that have multiple seasons on Channel 4 Catchup.

### To Reproduce
Select any program from the menus which has multiple seasons.

### Expected behaviour
Seasons are listed.

### Actual behaviour
Script errors.

### Screenshots
N/A

### Your environment
LibreELEC

- Operating system version/name: LibreELEC 11.0.6
- Kodi version: 20.3.0
- Catch-up TV & More version: v0.2.40~beta04
- Installation method: From repo

### Additional context
Programs that only have a single season list the episodes correctly.

I'm no programmer but, having taken a look at the code and the website, I changed the following:

117c117

<                     item.art["thumb"] = item.art["landscape"] = datas['images']['image16x9']['src']

\---

\>                     item.art["thumb"] = item.art["landscape"] = datas['images']['hero']['landscape']['src']

and, while this prevents the script error, I'm not sure it is correct as the icon doesn't change for each season listed.

### Debug log
https://paste.kodi.tv/uqopeduzaf.kodi

**Comment by joaopa00** [comment]
As usual, please provide the full steps to reproduce the problem.

**Comment by 43qcc2cn** [comment]
1. Add beta repo.
2. Install addon.
3. Open addon.
4. Select "Catch-up TV".
5. Select "United Kingdom".
6. Select "Channel 4".
7. Select "comedy".
8. Select, for example, "8 Out of Cats". Script errors rather than listing seasons.
9. Select, for example, "8 Out of Cats Does Countdown". Episodes are listed successfully.

**Comment by joaopa00** [comment]
Should be fixed in git.
