### ISSUE TITLE
Ajouter la lecture de Paris Première pour les abonnés ayant un compte 6Play

### ISSUE THREAD

**Issue by khyinn** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#135]
Bonjour,

Tout est dans le titre, je souhaiterai savoir s'il est possible d'ajouter le direct et le replay de Paris Première si on est abonnés et qu'on a renseigné son compte 6Play.

**Comment by wwark** [comment]
Bonsoir @khyinn,

Ce point demande que nous prenions un abonnement pour pouvoir ajouter/tester Paris Premières et Téva.
Il faudra aussi vérifier si la partie DRM de Paris Première est similaire à celle de M6 et lisible via le Kodi.

Le même abonnement donne accès à Téva et Paris Première ou ce sont des abonnements différents?

On ne ferme pas cette requête, nous verrons si nous pouvons y répondre et ajouter ces contenus.

Merci,
Wwark

**Comment by khyinn** [comment]
Je peux vous dire que l'abonnement à Paris Première ne donne pas accès à Téva. Je penche davantage pour une sorte de flag sur le compte 6play qu'à une limitation par DRM mais je ne suis pas assez calé sur le sujet pour le vérifier.
