### ISSUE TITLE
Message d erreur lors du visionnage d un replay sur france 3

### ISSUE THREAD

**Issue by monfiston** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1352]
Bonjour 
Je suis sous kodi 21, sous coreelec 21.0 omega
Version catchup, 0.2.40-beta06
À chaque fois que l on veut visionner un épisode de plus belle la vie en replay, sur tf1, il y a un message d erreur 
En général après quelques essais, on arrive à lire l épisodes

**Comment by joaopa00** [comment]
Je ne trouve pas les replays de plus belle la vie our tester. Quelle est la démarche à suivre pour obtenir une de ces rediffusions?

**Comment by monfiston** [comment]
Oups, désolé, c est passé maintenant sur tf1

**Comment by joaopa00** [comment]
Certains épisodes sont regardables. D'autres non. Cela semble être du au fait que pour certains épisodes, la seul format disponible est avec DRM Fairplay que inpustream adaptive (et donc Kodi) ne supporte pas

**Comment by monfiston** [comment]
J arrive à tous les lires,
 mais lors du 1° essaie,  ça ne fonctionne pas, puis après si, dès fois après 5 tentatives

**Comment by joaopa00** [comment]
Devrait etre fixé dans la dernière beta (merci darodi)
Si le problème persiste, n'hésite pas à réouvrir ce fil.
