### ISSUE TITLE
TF1+ connection

### ISSUE THREAD

**Issue by Roimii** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1353]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
A clear and concise description of what the bug is:
When you try to access the replay of Replay/French/TF1+/Divertissement/Whatever series, it says that you need to have a TF1+ account. However, in the settings of the app, you can only fill in a myTF1 account. When you fill it in, the app doesn't recognize it as a TF1+ account.

### To Reproduce
Steps to reproduce the behaviour:
1. In the settings fill in a myTF1 account
2. Go on French and TF1+ replay videos.
3. Try to launch any replay 

### Expected behaviour
A clear and concise description of what you expected to happen:
Rename the myTF1 in the account setting section to TF1+. 

### Actual behaviour
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [X ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version:
 - Catch-up TV & More version:
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment]
Devrait être fixé dans Git
