### ISSUE TITLE
TF1+ KeyError

### ISSUE THREAD

**Issue by f28gin** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1359]
### Content description

* Name:
* Type [e.g. TV channel, Catch-up TV, Website, Radio]:
* Website URL:
* Content language/country:

### Content access

- [ ] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [ ] This content is geographically restricted

### More information

Bonjour,
Depuis le changement de TF1 à TF1+ malgré le login et mot de passe correct j'ai un message d'erreur sur n'importe quel film ou série : KeyError ... u'userInfo'

Peut être une petite mise à jour bientôt ;-)

bonne journée

**Comment by Masaju31** [comment]
Bonjour,
Je vois que le problème est résolu, mais je ne comprends pas comment fixer ce soucis.
Merci d'avance !

**Comment by Almeyric** [comment]
Bonjour,

J'ai le même problème. Et rien ne se lance. Malgré les identifiants OK.
Version en 0.2.40beta08
En beta 04 c'était fonctionnel.

**Comment by darodi** [comment]
@Masaju31 @Almeyric 
Le problème sera résolu quand 
- #1357 
sera inclus, dans la prochaine version beta
