### ISSUE TITLE
Clean xbmc objects ?

### ISSUE THREAD

**Issue by wwark** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#136]
Hi,

11:04:59.566 T:1194324720 WARNING: CPythonInvoker(245, /home/bob/.kodi/addons/plugin.video.catchuptvandmore/addon.py): the python script "/home/bob/.kodi/addons/plugin.video.catchuptvandmore/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui8ListItemE

https://trello.com/c/lovD9Lf7/257-cleanup-of-xbmcaddon

https://forum.kodi.tv/showthread.php?tid=307508

Thanks,
Wwark

**Comment by SylvainCecchetto** [comment]
Hello @wwark, tu obtiens ce message dans un menu en particulier ? Je n'arrive pas à reproduire.

**Comment by wwark** [comment]
Je ferme ce ticket je n'ai plus l'erreur.
ça du être corrigé entre temps !
