### ISSUE TITLE
Problem with Kodi version 21 (Flatpak)

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1365]
Kodi upgrades Flatpak on Linux to version 21.0.
On startup, Kodi hangs.
log file:
https://paste.kodi.tv/izoyomitab.kodi

**Comment by khalistoo** [comment]
Don't think this is an issue with this plugin.

Your Kodi log seems to indicate hanging because a missing table whilst loading whatever plugin using MyMusic83.db

2024-05-27 09:15:12.724 T:23      error <general>: SQL: [MyMusic83.db] SQLite error SQLITE_ERROR (no such table: version)
                                                   Query: SELECT idVersion FROM version

**Comment by enigma131** [comment]
Problem solved by:
Adding an environment variable MARIADB_AUTO_UPGRADE=1 in .bashrc
Then copy MyMusic82.db to MyMusic83.db in .var/app/tv.kodi.Kodi/data/userdata/Database folder
Perhaps it is need by standard Kodi installations (No Flatpak: Linux/Android/Windows) ?

**Comment by enigma131** [comment]
Tested today: Windows Kodi 21 is working without the trick
