### ISSUE TITLE
Identifiant tf1 perdu

### ISSUE THREAD

**Issue by monfiston** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1366]
Bonjour
Je suis sous kodi 21, sous coreelec 21.0 omega
Version catchup, la dernière beta
Ça fait 2 fois, que je dois remettre mes identifiants pour le compte tf1
1 fois il y a 3 semaines environ,  et 1 fois hier

**Comment by darodi** [comment]
Bonjour @monfiston 

C'est "normal". 
Le nom du paramètre où est stocké l'identifiant dans CUTVM a changé lors des 2 dernières version
ça ne devrait plus arriver.

**Comment by enigma131** [comment]
Vérifies s'il est bien enregistré dans .kodi/userdata/addon_data/plugin.video.catchuptvandmore/settings.xml
