### ISSUE TITLE
FranceTV low video quality

### ISSUE THREAD

**Issue by Forage** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1368]
### Describe the bug
Since a week or three the quality of basically all FranceTV are of a terrible quality. 
When looking at the video settings, only one srteam of h264 at 384x216 is available, while the Android app offers 4 streams, with SD and HD included.

### To Reproduce
Steps to reproduce the behaviour:
1. Take "France 3 - Meurtres à - Season 10 - épisode 9" for example.
2. Play and observe

### Expected behaviour
A clear and concise description of what you expected to happen:
Have a better video quality, or at least the choice to select a better one.

### Actual behaviour
Tell us what happens instead:
Only one h264 at 384x216 stream is available.

### Your environment
 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: LibreElec 12.0
 - Kodi version: 21
 - Catch-up TV & More version: 0.2.40~beta09
 - Installation method: CTM beta repository

**Comment by jeff2900** [comment]
Have you setting "Qualité et Contenu" of addon Catchup TV & More ?

My settings for "InputStream adaptive":
Stream selection = Fixed resolution
Maximum resolution = Auto
Maximum resolution for DRM videos = Auto

**Comment by Forage** [comment]
Spot on! Many thanks.

Mine was on adaptive instead of fixed.

Strange that the behaviour has changed all of a sudden. I did update from LE 11 to 12 (Kodi 20 to 21) two weeks ago, but, while not 100% sure, I do believe the problem already appeared before that. Maybe an InputStream add-on update at some point. 

Also not ideal that alternative streams can't be manually selected while playing an episode. Only one is available.
