### ISSUE TITLE
France TV invalid schema No connection adapters were found for {akamai…

### ISSUE THREAD

**Issue by CChalu** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1374]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
Play a video on France TV Channel 2, then I get this massage : InvalidSchema
No connection adapters were found for {akamai:’https://hdfauth.ftven.fr/esi/TA?format=json’}

### To Reproduce
Steps to reproduce the behaviour:
1. Play a video on France TV and the error message displays.

### Expected behaviour
Watch a video on France 

### Actual behaviour
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [x ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: Android TV 9 api level 28 (kernel linux 4.9.25)
 - Kodi version: 21 omega version 21.0.1
 - Catch-up TV & More version: 0.2.40~beta09
 - Installation method: repositories beta

### Additional context
I have the same issue on Chromecast HD with Google and Kodi 21 and catch up beta 0.2.40~beta09

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by dszczyt** [comment]
more info…
```
2024-06-13 08:51:20.839 T:106     error <general>: [Catch-up-TV-&-More.support] No connection adapters were found for "{'dai': 'https://api.ssai.ftven.fr/v1/session/c6f323e65336fbba9ea766d582216fd61ed74452/SSAIFrance2OTTEMTConfiguration/out/v1/3f5d86a548454a27ab9a06078aa68a03/index.m3u8', 'akamai': 'https://hdfauth.ftven.fr/esi/TA?format=json'}"
```
and when I curl the url:
```
curl https://api.ssai.ftven.fr/v1/session/c6f323e65336fbba9ea766d582216fd61ed74452/SSAIFrance2OTTEMTConfiguration/out/v1/3f5d86a548454a27ab9a06078aa68a03/index.m3u8
<UnknownOperationException/>
```

**Comment by dszczyt** [comment]
the program info seems to have changed its format, at list for its `.video.token` object, that was the url before:
```
{
  "video": {
    "token": {
      "dai": "https://api.ssai.ftven.fr/v1/session/c6f323e65336fbba9ea766d582216fd61ed74452/SSAIFrance2OTTEMTConfiguration/out/v1/3f5d86a548454a27ab9a06078aa68a03/index.m3u8",
      "akamai": "https://hdfauth.ftven.fr/esi/TA?format=json"
    },
    "url": "https://live-ssai-v2.ftven.fr/dai/v1/master/c6f323e65336fbba9ea766d582216fd61ed74452/SSAIFrance2OTTEMTConfiguration/out/v1/3f5d86a548454a27ab9a06078aa68a03/index.m3u8",
…
}
```
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/dev/resources/lib/resolver_proxy.py#L565-L568 should be fixed

**Comment by dszczyt** [comment]
here is a PR that fixed the issue on my side

**Comment by dszczyt** [comment]
there is still a freeze after a few seconds…

**Comment by dszczyt** [comment]
je viens de tester ce patch : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/1371/files il fonctionne à merveille

**Comment by nboullis** [comment]
> here is a PR that fixed the issue on my side

I just gave your PR a try but it did not work for me : the token object had no dai attribute, only the akamai attribute.

**Comment by dszczyt** [comment]
@nboullis try the patch #1371 : it changes the os to android, and it changes the way it fetches tokens, and I had a very stable video stream thanks to it.

**Comment by Syl-76** [comment]
Pour le simple utilisateur que je suis, comment on applique le patch #1371 ? Car j'ai le même problème d'InvalidSchema pour toutes les chaines du groupe France TV...

**Comment by jeff2900** [comment]
Bonjour,
Voici une archive de l'addon Catchuptvandmore version 0.2.40beta09 avec le fixe de FranceTV
[https://www.mediafire.com/file/kz4ygzt3zvueape/plugin.video.catchuptvandmore-0.2.40~beta09-fix-ftv.zip/file](https://www.mediafire.com/file/kz4ygzt3zvueape/plugin.video.catchuptvandmore-0.2.40~beta09-fix-ftv.zip/file)

**Comment by CChalu** [comment]
Bonjour,
Normalement le plug-in devrait être mis à jour quand le fix sera accepté.

**Comment by Syl-76** [comment]
> Bonjour, Voici une archive de l'addon Catchuptvandmore version 0.2.40beta09 avec le fixe de FranceTV [https://www.mediafire.com/file/kz4ygzt3zvueape/plugin.video.catchuptvandmore-0.2.40~beta09-fix-ftv.zip/file](url)

Merci beaucoup... mais France TV ne marche toujours pas, je n'ai juste plus le message d'erreur, et en plus je n'ai plus les chaines du groupe TF1...
Je vais attendre la mise a jour officielle.

**Comment by OoAnikioO** [comment]
Pour TF1, j'ai vu qu'il fallait retaper son compte

**Comment by daffy25** [comment]
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1374#issuecomment-2165398969


> je viens de tester ce patch : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/1371/files il fonctionne à merveille

Je suis novice. Pourriez vous m'indiquer comment installer ce patch svp???Merci par avance

**Comment by Shadoom88** [comment]
Bonjour, 
Début du problème depuis l'add-on 0.2.40~Beta09.
France TV : après installation de l'add-on je n'ai plus le message d'erreur comme syl-76. Mais ça ne fonctionne toujours pas. 
TF1 : routemissing - Unable to import route module 'resources.lib.channel.fr.mytf1'

Wait & see....

**Comment by lelkluk** [comment]
Pareil pour moi après la mise à jour d'avant-hier via le dépôt sur ma clé Amazon FireTV.
TF1 qui s'était mis à ne plus fonctionner non plus pour le direct fonctionne à nouveau
Par contre France TV ne fonctionne toujours pas, seul le message d'erreur a disparu

**Comment by jeff2900** [comment]
Bonjour,
Le fix #1378 corrige l'erreur "akamai" sur FranceTV.

**Comment by caywin25** [comment]
Bonjour,
Je confirme que le fix [#1378 ](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/1378) règle le soucis de Francetv.
Merci

**Comment by daffy25** [comment]
> Bonjour, Je confirme que le fix [#1378 ](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/1378) règle le soucis de Francetv. Merci

Comment faire svp????

**Comment by caywin25** [comment]
Hello @daffy25 
Tu récupères le fichier ici : 
> https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/eec057bd80d4d198c4396df8e4c0797612c1db2b/resources/lib/resolver_proxy.py

et tu le mets à la place du tien actuellement.

**Comment by CChalu** [comment]
Une mise à jour automatique de catch-up TV via le dépôt beta a réglé le problème chez moi sur ma TV Android. J’ai la version 0.2.40~beta10. Pensez à redémarrer Kodi, voire la TV, purger le cache de catch-up si le problème persiste peut-être ?

**Comment by lelkluk** [comment]
Bizarre chez moi j'ai 2 équipements TV (Android TV et Clé Amazon fire) et le problème n'est pas réglé.
J'ai retrouvé le groupe TF1 qui ne fonctionnait plus, mais concernant le groupe France Television j'ai toujours le même problème: Pas de message d'erreur, ça rend la main tel quel, sans aller sur la chaîne.
J'ai cette version 0.2.40 beta 10, vidé les caches, redémarrer Kodi et TV mais problèmes toujours présent.
Est-ce que ça pourrait être lié à la version de Koki lui-même ? 
Je n'ai plus en tête les versions utilisées

**Comment by jeff2900** [comment]
Bonjour,
J'ai soumis le PR #1378 qui corrige les erreurs "dai" et "akamai" sous kodi 20.
En attendant qu'il soit pris en compte voici un lien vers une archive zip de l'addon:
[https://www.mediafire.com/file/eg4dquevt3lju8q/plugin.video.catchuptvandmore-0.2.40%257Ebeta10-fix-ftv.zip/file
](https://www.mediafire.com/file/eg4dquevt3lju8q/plugin.video.catchuptvandmore-0.2.40%257Ebeta10-fix-ftv.zip/file
)

**Comment by lelkluk** [comment]
Bravo jeff, ça fonctionne  :)   avec ma clé Amazon. Pas de raison que ça ne fonctionne pas aussi sur la TV Android TV, mais le test sera pour demain
Merci  :)

**Comment by CChalu** [comment]
J’utilise effectivement la version 21 de Kodi. C’est la seule disponible dans le play store de ma TV android.

**Comment by Syl-76** [comment]
> Bonjour, J'ai soumis le PR #1378 qui corrige les erreurs "dai" et "akamai" sous kodi 20. En attendant qu'il soit pris en compte voici un lien vers une archive zip de l'addon: [https://www.mediafire.com/file/eg4dquevt3lju8q/plugin.video.catchuptvandmore-0.2.40%257Ebeta10-fix-ftv.zip/file ](https://www.mediafire.com/file/eg4dquevt3lju8q/plugin.video.catchuptvandmore-0.2.40%257Ebeta10-fix-ftv.zip/file)

Cet addon fonctionne à merveille pour France TV. Mais les chaînes du groupe tf1 donnent l'erreur "route missing", même après avoir ressaisi mes identifiants tf1+...

**Comment by jeff2900** [comment]
Bonjour,
Pour ma part les chaînes du groupe TF1 fonctionnent correctement aussi bien sous l'addon Catchuptvandmore que via la fonction TV de Kodi . 
Si vous utilisez la fonction TV de Kodi, il faut mettre à jour les chaînes et guide dans IPTV Manager.
Si vous utilisez votre propre fichier .m3u, il faut le mettre à jour en remplacent toute référence à mytf1 par tf1plus.

**Comment by lelkluk** [comment]
Moi pareil tout fonctionne à nouveau sans problème avec le zip de Syl-76

**Comment by Syl-76** [comment]
Effectivement, j'ai mis a jour les chaines dans IPTV Manager et tout fonctionne.
Merci !

**Comment by daffy25** [comment]
> Hello @daffy25 Tu récupères le fichier ici :
> 
> > https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/eec057bd80d4d198c4396df8e4c0797612c1db2b/resources/lib/resolver_proxy.py
> 
> et tu le mets à la place du tien actuellement.

Je dois vraiment être nul car je ne comprends pas comment remplacer ce fichier. Je n'ai pas d'accès à aux fichiers de l'application!!!

**Comment by daffy25** [comment]
> > Bonjour, J'ai soumis le PR #1378 qui corrige les erreurs "dai" et "akamai" sous kodi 20. En attendant qu'il soit pris en compte voici un lien vers une archive zip de l'addon: [https://www.mediafire.com/file/eg4dquevt3lju8q/plugin.video.catchuptvandmore-0.2.40%257Ebeta10-fix-ftv.zip/file ](https://www.mediafire.com/file/eg4dquevt3lju8q/plugin.video.catchuptvandmore-0.2.40%257Ebeta10-fix-ftv.zip/file)
> 
> Cet addon fonctionne à merveille pour France TV. Mais les chaînes du groupe tf1 donnent l'erreur "route missing", même après avoir ressaisi mes identifiants tf1+...

Merci Syl-76. ça fonctionne. Vous êtes trop fort dans ce groupe. Je suis admiratif. Merci encore

**Comment by Shadoom88** [comment]
Bonjour, 
pour TF1 et France TV, depuis le patch de Syl-76 tout fonctionne de nouveau (et même mieux pour France TV plus de lag).
Mais M6 fige maintenant au bout de  1 à 2 min....

Wait et see

**Comment by daffy25** [comment]
> Hello @daffy25 Tu récupères le fichier ici :
> 
> > https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/eec057bd80d4d198c4396df8e4c0797612c1db2b/resources/lib/resolver_proxy.py
> 
> et tu le mets à la place du tien actuellement.

Je crois que j'ai compris hahahaha. Je le remplace dans le fichier zip, c'est ça????

**Comment by Shadoom88** [comment]
> > Hello @daffy25 Tu récupères le fichier ici :
> > > https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/eec057bd80d4d198c4396df8e4c0797612c1db2b/resources/lib/resolver_proxy.py
> > 
> > 
> > et tu le mets à la place du tien actuellement.
> 
> Je crois que j'ai compris hahahaha. Je le remplace dans le fichier zip, c'est ça????

Bonjour,
il faut mettre ce fichier dans : 
/STORAGE/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/

Et remplacer l'ancien

**Comment by wawa79** [comment]
> > > Bonjour, J'ai soumis le PR #1378 qui corrige les erreurs "dai" et "akamai" sous kodi 20. En attendant qu'il soit pris en compte voici un lien vers une archive zip de l'addon: [https://www.mediafire.com/file/eg4dquevt3lju8q/plugin.video.catchuptvandmore-0.2.40%257Ebeta10-fix-ftv.zip/file ](https://www.mediafire.com/file/eg4dquevt3lju8q/plugin.video.catchuptvandmore-0.2.40%257Ebeta10-fix-ftv.zip/file)
> > 
> > 
> > Cet addon fonctionne à merveille pour France TV. Mais les chaînes du groupe tf1 donnent l'erreur "route missing", même après avoir ressaisi mes identifiants tf1+...
> 
> Merci Syl-76. ça fonctionne. Vous êtes trop fort dans ce groupe. Je suis admiratif. Merci encore

Bonjour,
Pour ma part, ce fix ne fonctionne pas avec toujours une erreur 403. J'ai tenté les différents relolver_proxy.py sans succès (au mieux j'ai le message d'erreur "Akamai")...
Plus de replay ou de direct sur FranceTV, et le groupe TF1 depuis hier donc : Kodi plante direct au lancement d'une vidéo.
Le PC tourne sous Windows 22h2 + Kodi 21 + CatchupTV 0.40beta10 (ou 0.40beta10-fix-ftv), fraîchement réinstallés en version "stock" (formatage disque dur et tout et tout). Le log retourne :

`2024-06-30 14:37:41.757 T:5660    error <general>: CCurlFile::XFILE::CCurlFile::Stat - <https://simulcast-p.ftven.fr/ZXhwPTE3MTk3NzI2NjF+YWNsPSUyZip+aG1hYz0zMjA3YmVhYzA2YzgzZTAzZGMxZDE5ODdjMDIxNTVmYzYxNzYzNjYwMzhkMGM2MmYxZGE3NzkyMzk5ODQ0YjMz/simulcast/France_2/dash_fr2/France_2.mpd?hdnea=exp=1719751661~acl=%2f*~hmac=3a6c451a22297e96b8f97c9e5227269f5c01e134d3c1741bbde3aadc9226b824> Failed: HTTP response code said error(22)
`
Puis une ligne reporte une erreur 403 (cf log [kodi_catchuptv crash_debugmore.log](https://github.com/user-attachments/files/16044704/kodi_catchuptv.crash_debugmore.log))

J'ai installé la même config sur Librelec et là, Catchup TV 0.40beta10 "de base" fonctionne nickel. Malheureusement, les manques de Librelec sont rédhibitoires (je rêvais pourtant de dégager enfin Windows...)

**Comment by jeff2900** [comment]
Bonjour,
1- La version plugin.video.catchuptvandmore-0.2.40~beta10.zip fonctionne sous kodi 21. Il n'est pas nécessaire d'installer le fixe.

2- Le crash de kodi21 sous Windows 11 est dû à la version 21.4.10 de l'addon inputstream.adaptive. Il faut installer la version 14.40.33810.0 de Microsoft Visual C++ Redistributable: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version

3- Pour résoudre l'erreur "Failed: HTTP response code said error(22)" j'ai activé le paramètre "disablehttp2" dans le fichier %appdata%\Kodi\userdata\advancedsettings.xml:
```
<advancedsettings>
    <network>
        <disablehttp2>true</disablehttp2>     <!-- Added in v19- Allows disabling HTTP2 for broken Curl / HTTP2 servers -->
    </network>
</advancedsettings>
```

**Comment by wawa79** [comment]
> Bonjour, 1- La version plugin.video.catchuptvandmore-0.2.40~beta10.zip fonctionne sous kodi 21. Il n'est pas nécessaire d'installer le fixe.
> 
> 2- Le crash de kodi21 sous Windows 11 est dû à la version 21.4.10 de l'addon inputstream.adaptive. Il faut installer la version 14.40.33810.0 de Microsoft Visual C++ Redistributable: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version
> 
> 3- Pour résoudre l'erreur "Failed: HTTP response code said error(22)" j'ai activé le paramètre "disablehttp2" dans le fichier %appdata%\Kodi\userdata\advancedsettings.xml:
> 
> ```
> <advancedsettings>
>     <network>
>         <disablehttp2>true</disablehttp2>     
>     </network>
> </advancedsettings>
> ```

Votre réponse met fin à mes errements du week-end : tout marche à nouveau parfaitement. Merci infiniment !
J'étais pas très optimiste vu les solutions "foisonnantes" de ce post...
Au moins, le sujet aura eu le mérite de m'obliger à tester LibreElec et à -enfin- faire une réinstall propre de Windows 10 et Kodi qui semble solutionner le pb que je trainais depuis des mois : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1161#issue-1751436207
