### ISSUE TITLE
BVN Live TV no longer functioning

### ISSUE THREAD

**Issue by bruggieinoz** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1384]
Hi,
Since yesterday, I’m unable to play BVN Live TV using CatchupTVandmore on Kodi.

Just learned that the URL https://www.bvn.tv/bvnlive is no longer active due to changes to the website
New start URL ishttps://www.bvn.tv/tv-gids/

Hoping someone could fix this. Thanks

**Comment by bruggieinoz** [comment]
I can confirm that changing the following value in BVN.py fixes the issue:

# LIVE :
URL_LIVE = URL_ROOT + '/tv-gids/'

**Comment by tidzerda** [comment]
agree with @bruggieinoz, this works for me as well.

**Comment by bruggieinoz** [comment]
It seems that BVN has put an URL redirect in place since, so no chance is needed. I will close this issue
