### ISSUE TITLE
fermeture de kodi apres avoir cliquer sur pour regarder une redif

### ISSUE THREAD

**Issue by donbeaupapa** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1386]
Quand j'utilise catch-up, t'en que je navigue tous se passe bien, par contre quand  je clique sur une émission pour la visionner, sa cherche et  ferme kodi immédiatement!!
j'ai le même problème avec l'addon de France tv, arte.
je suis sous la dernier versoin de kodi installer à partir du site de kodi.
pour catch-up, j'ai le même soucis avec la version stable et beta
Windows 10
voici le log:
https://paste.kodi.tv/iduzeworox

**Comment by jeff2900** [comment]
Bonjour,
Le crash de kodi21 sous Windows 10/11 est dû à la version 21.4.10 de l'addon inputstream.adaptive. Il faut installer la version 14.40.33810.0 de Microsoft Visual C++ Redistributable: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version

**Comment by donbeaupapa** [comment]
merci pour l'aide, sa ne change rien!!

**Comment by CyberloFr** [comment]
Bonjour,
Merci pour l'astuce cela refonctionne, alors que depuis plusieurs jours je galéré sur le bug (réinstallation de Kodi / des plugins version classique ou beta).
Vraiment merci beaucoup
L'équipe de Catch up est au courant pour l'intégrer dans les mises à jour ?
merci encore à la communauté !
Bonne journée

**Comment by donbeaupapa** [comment]
il y a qui on de la chance!!!!

**Comment by CyberloFr** [comment]
Bonjour, effectivement j'ai de la chance de trouver ce post. Mais j'ai vraiment galéré avant... Plusieurs désinstallations, réinstallations, suppression des fichiers dans le profil, nettoyage de la base de données.
bon courage à vous.
J'espère que vous allez trouver une solution.
Bonne journée

**Comment by donbeaupapa** [comment]
merci pour ton soutient

**Comment by raydenxxx** [comment]
nickel ça a bien réglé le souci de mon coté aussi. merci

**Comment by joaopa00** [comment]
Est-ce que quelqu'un rencontre encore ce problème?

Si oui, n'oubliez pas de mettre à jour Kodi à la version Omega avec le dernier inpustream adaptive  disponible.
