### ISSUE TITLE
épisode "plus belle la vie" en avant première inaccessible

### ISSUE THREAD

**Issue by monfiston** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1388]
Bonjour
Je suis sous kodi 21, sous coreelec 21.0 omega, ou sur windows
Version catchup, la dernière beta
quand on veux regarder les 2 épisodes en avant première de la série "plus belle la vie" de TF1, ça ne fonctionne pas

![Capture d’écran 2024-07-19 204529](https://github.com/user-attachments/assets/ad82a89c-3661-4f88-be93-3cc628c3e963)

**Comment by monfiston** [comment]
bonjour
ce rapport de bug est toujours d'actualité

**Comment by joaopa00** [comment]
Ces avant premières sont des avantages de TF1 premium. Es- ce que tu es abonné à ce service, qui est payant?

**Comment by monfiston** [comment]
non je ne suis pas abonné

**Comment by joaopa00** [comment]
Donc tu n'as pas accès à ces programmes. Tout est normal.
