### ISSUE TITLE
Replay video title appears but its folder is empty

### ISSUE THREAD

**Issue by mailpourregarderlatv** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1391]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
A clear and concise description of what the bug is:
In catch-up tv, france, france tv, series appears, like 'Vortex' or 'Bugarach'. If I select one of them, the folder 'Saison 1' appears but it is empty. 

### To Reproduce
Steps to reproduce the behaviour:
1. Add-ons
2. Cath_up TV & More
3. Cath_up TV
4. France
5. 'France TV'
6. Categories
7. 'Séries & fictions'
8. 'Series à binger'
9. 'Vortex'
10. 'Saison 1'
11. Notice that the folder is empty (see screenshot)

### Expected behaviour
A clear and concise description of what you expected to happen:
an access to the episodes of the different series
### Actual behaviour
Tell us what happens instead:
the folder 'saison 1' of the series is empty
### Screenshots
If applicable, add screenshots to help explain your problem:see attachments

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi (3B)
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: LibreELEC 12.0.0
 - Kodi version: 21
 - Catch-up TV & More version: 0.2.40 beta10
 - Installation method: Libreelec ('catch-up-tv-and-more.github.io/repo/', etc)

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):
I can't follow the method because folder 'storage' does'nt appear in my explorer window but I found a folder 'Logfiles' wich contains '01_KODI.log' (1357Ko), '01_KODI_CRASH.log', '01_KODI_OTHER.log', '02_System.log', etc .... 
[log-2024-08-03-11.26.54.zip](https://github.com/user-attachments/files/16479410/log-2024-08-03-11.26.54.zip)
![screenshot00001](https://github.com/user-attachments/assets/39972d31-3e85-41f6-9c85-d401a62cf32a)

**Comment by joaopa00** [comment]
Est-ce que le problèeme se passe encore? Si oui, est-ce que c'est seulement pour la série vortex ou pour n'importe quelle série?
Si le probème persiste, attache un log avec debug activé ainsi que les caneaux libcurl ffmpeg, audio video
