### ISSUE TITLE
Hang on Ubuntu 24 / Mint 22

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1394]
I've upgraded a PC to Mint 22 but I have same problem On live media.
It crash (closes) Kodi directly without a message and no relevant information in log file.
Other plugins are working (France TV, pvr addons), so I think its not an Kodi or Kernel issue.
Can someone reproduce, I've tested on 2 PCs ?
Is it a Pipewire problem for the addon (fist time it comes with Mint) ?

**Comment by joaopa00** [comment]
Kodi in ubuntu 24 is buggy completely. That's a well documented problem. Ubuntu 24 uses Python 3.12 that is not supporter by kodi 20.

Bug for Kodi 20 in Ubuntu 24(https://bugs.launchpad.net/ubuntu/+source/kodi/+bug/2063358l)

**Comment by enigma131** [comment]
Look here : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1412#issuecomment-2450564768
Mint 22 gets Python 3 update and now Catch Up Tv And More is working on Kodi 20.5 too.

**Comment by enigma131** [comment]
The only remaining problem is kodi_crashlog on exit.
