### ISSUE TITLE
mycanal replay (fr)

### ISSUE THREAD

**Issue by lit0t0** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1395]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
A clear and concise description of what the bug is:

### To Reproduce
Steps to reproduce the behaviour:
1.
2.
3.
4.

### Expected behaviour
A clear and concise description of what you expected to happen:

### Actual behaviour
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version:
 - Catch-up TV & More version:
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by lit0t0** [comment]
Hello,
Access to the mycanal replay (from the French IP) no longer seems to work
I have the following error:
error <general>: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/mycanal/mycanal_root/?_pickle_=80049539000000000000007d94288c075f7469746c655f948c076d7943414e414c948c08786d6c74765f6964944e8c076974656d5f6964948c076d7963616e616c94752e
I tested from 2 Desktop PC and the result is the same

**Comment by lit0t0** [comment]
hello,
today I tested the windows version of kodi with catchup tv and more plugin last beta version. When I try to load a C8 video replay, I have this error:
 error <general>: AddOnLog: inputstream.adaptive: adaptive::CSmoothTree::ParseManifest: Failed to get manifest <SmoothStreamingMedia> tag element.
2024-08-18 10:21:35.316 T:7956    error <general>: AddOnLog: inputstream.adaptive: Cannot parse the manifest (https://routemeup.canalplus-bo.net/redirect/v1/replay-hss2/playready/canalplus/d8/d8_1278208_495_D8/2700370/d8-1278208-495-D8.ism?token=eyJhbGciOiJFUzI1NiIsImtpZCI6InZvZDAwMSJ9.eyJhaWQiOiIxNzIzOTY5MjkyMDA5LTExMzY3NmQ1YmI5ZTowOjE3MjM5NjkyOTQwMDktZTViZTMyNGE4NjBjIiwiZXhwIjoxNzIzOTY5ODk0LCJkaWQiOiIxNzIzOTY5MjkyMDA5LTExMzY3NmQ1YmI5ZSIsImNpcCI6IjgzLjExNS45OS4yMjIiLCJzdWIiOiIvZDhfMTI3ODIwOF80OTVfRDgvIn0.EAqynBemiHIcRYXgLakzpUStHMOrZWEsgayksfWiWtmy6wrij5IXKYQzijjmghv0CMZ297ATkvMRkZUMvSpOpw/manifest)

**Comment by lit0t0** [comment]
so i downloaded the url manifest:

<?xml version="1.0" encoding="utf-8"?>
<smil xmlns="http://www.w3.org/2001/SMIL20/Language">
  <head>
    <meta name="clientManifestRelativePath" content="d8_1278208_495_D8.ismc" />
    <meta name="title" content="d8_1278208_495_D8" />
  </head>
  <body>
    <switch>
      <audio src="d8_1278208_495_D8$w1_a_aaclc_0_fra_0_1_64.isma" systemBitrate="64000" systemLanguage="fre">
        <param name="trackID" value="1" valuetype="data" />
        <param name="trackName" value="audio_fre" valuetype="data" />
      </audio>
      <video src="d8_1278208_495_D8$w1_v_avc_0_234_416_0_190.ismv" systemBitrate="189952">
        <param name="trackID" value="1" valuetype="data" />
        <param name="trackName" value="Video" valuetype="data" xmlns="" />
      </video>
      <video src="d8_1278208_495_D8$w1_v_avc_0_360_640_0_300.ismv" systemBitrate="299968">
        <param name="trackID" value="1" valuetype="data" />
        <param name="trackName" value="Video" valuetype="data" xmlns="" />
      </video>
      <video src="d8_1278208_495_D8$w1_v_avc_0_432_768_0_750.ismv" systemBitrate="749952">
        <param name="trackID" value="1" valuetype="data" />
        <param name="trackName" value="Video" valuetype="data" xmlns="" />
      </video>
      <video src="d8_1278208_495_D8$w1_v_avc_0_540_960_0_1100.ismv" systemBitrate="1099968">
        <param name="trackID" value="1" valuetype="data" />
        <param name="trackName" value="Video" valuetype="data" xmlns="" />
      </video>
      <video src="d8_1278208_495_D8$w1_v_avc_0_540_960_0_1500.ismv" systemBitrate="1499968">
        <param name="trackID" value="1" valuetype="data" />
        <param name="trackName" value="Video" valuetype="data" xmlns="" />
      </video>
      <video src="d8_1278208_495_D8$w1_v_avc_0_540_960_0_2100.ismv" systemBitrate="2099968">
        <param name="trackID" value="1" valuetype="data" />
        <param name="trackName" value="Video" valuetype="data" xmlns="" />
      </video>
    </switch>
  </body>
</smil>

**Comment by lit0t0** [comment]
here is the downloaded manifest

**Comment by lit0t0** [comment]
<?xml version="1.0" encoding="utf-8"?>
<smil xmlns="http://www.w3.org/2001/SMIL20/Language">
  <head>
    <meta name="clientManifestRelativePath" content="d8_1278208_495_D8.ismc" />
    <meta name="title" content="d8_1278208_495_D8" />
  </head>
  <body>
    <switch>
      <audio src="d8_1278208_495_D8$w1_a_aaclc_0_fra_0_1_64.isma" systemBitrate="64000" systemLanguage="fre">
        <param name="trackID" value="1" valuetype="data" />
        <param name="trackName" value="audio_fre" valuetype="data" />
      </audio>
      <video src="d8_1278208_495_D8$w1_v_avc_0_234_416_0_190.ismv" systemBitrate="189952">
        <param name="trackID" value="1" valuetype="data" />
        <param name="trackName" value="Video" valuetype="data" xmlns="" />
      </video>
      <video src="d8_1278208_495_D8$w1_v_avc_0_360_640_0_300.ismv" systemBitrate="299968">
        <param name="trackID" value="1" valuetype="data" />
        <param name="trackName" value="Video" valuetype="data" xmlns="" />
      </video>
      <video src="d8_1278208_495_D8$w1_v_avc_0_432_768_0_750.ismv" systemBitrate="749952">
        <param name="trackID" value="1" valuetype="data" />
        <param name="trackName" value="Video" valuetype="data" xmlns="" />
      </video>
      <video src="d8_1278208_495_D8$w1_v_avc_0_540_960_0_1100.ismv" systemBitrate="1099968">
        <param name="trackID" value="1" valuetype="data" />
        <param name="trackName" value="Video" valuetype="data" xmlns="" />
      </video>
      <video src="d8_1278208_495_D8$w1_v_avc_0_540_960_0_1500.ismv" systemBitrate="1499968">
        <param name="trackID" value="1" valuetype="data" />
        <param name="trackName" value="Video" valuetype="data" xmlns="" />
      </video>
      <video src="d8_1278208_495_D8$w1_v_avc_0_540_960_0_2100.ismv" systemBitrate="2099968">
        <param name="trackID" value="1" valuetype="data" />
        <param name="trackName" value="Video" valuetype="data" xmlns="" />
      </video>
    </switch>
  </body>
</smil>

**Comment by lit0t0** [comment]
so i downloaded the manifest at this url (attached file )
[d8-1278208-495-D8.ism.txt](https://github.com/user-attachments/files/16647689/d8-1278208-495-D8.ism.txt)

**Comment by lit0t0** [comment]
And I saw that there is an UTF-8 BOM at start of the manifest file .. Maybe this is the cause of the error?

**Comment by jeff2900** [comment]
Hello,
You can try this modded version. If it works, I will make a PR in the next days.
https://www.mediafire.com/file/14be5fwj34h26ei/plugin.video.catchuptvandmore-0.2.40%257Ebeta10-fix-ftv3.zip/file

**Comment by lit0t0** [comment]
Hello,
it works like a charm
you are the best
thank you very much

**Comment by jeff2900** [comment]
Fixed in PR #1399.

**Comment by geoffde** [comment]
Hi,

I have the same problem on a android device.

I have tried the "beta10-fix-ftv3.zip" and I can't even acces to "Canal +". The error is "unable to import route module : RESSOURCE.LIB.CHANNELS.FR.MYCANAL"

I have then tried the "beta10-fix-ftv2.zip" and I can acces to "Canal +" then "C8" then I can select a video but nothing happen when I lunch it...

Thanks by advance

**Comment by joaopa00** [comment]
Devarit être fixé dans GIT. Merci à JEFF.
