### ISSUE TITLE
Catch up video on ABC news not available

### ISSUE THREAD

**Issue by goduck777** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#140]
Although playing live TV of ABC news is working, catch up video is not. None of the videos can be played. On the website (abcnews.go.com), the videos within the last week require a cable account, but older videos do not.

**Comment by wwark** [comment]
Hi @goduck777,

I test on my side just "the view" show works now.....
if the last videos required a cable account we might need to remove in the future this content because we don't have cable account.

We will try to fix for old videos ...
thanks to bring this issue.

Thanks,
Wwark

**Comment by Arias800** [comment]
Hello @goduck777,
I have rewritten the code and every free video is playable.
Sadly, I can't fix the content that need a cable account.
