### ISSUE TITLE
TV Tokyo suddenly has no programs

### ISSUE THREAD

**Issue by KylanHaffie** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1408]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
TV Tokyo channel is only showing one program, whereas it used to be filled with tons and tons of programs.

### To Reproduce
Steps to reproduce the behaviour:
1. Catch-Up TV
2. Japan
3. TVER: テレビ東京

### Expected behaviour
Lots of programs appear

### Actual behaviour
Only one program appears

### Screenshots
![PXL_20240924_191504712](https://github.com/user-attachments/assets/5387ae13-76c0-4f8f-a0db-25644f0c4744)

### Your environment
 - [ x] Android Firestick
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 18.8.0
 - Catch-up TV & More version: 0.2.40 beta10

Maybe TV Tokyo just deleted all it's programs ?

**Comment by kalun85** [comment]
As a workaround, go to 

Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/dev/resources/lib/channels/jp/tver.py file.

In this line:

'tx': ['テレビ東京', 'TVh', 'ＢＳテレ東', 'ＢＳテレ東 ほか', 'TVQ九州放送'],

add 'テレ東' such that the line becomes:

'tx': ['テレビ東京', 'TVh', 'ＢＳテレ東', 'ＢＳテレ東 ほか', 'TVQ九州放送','テレ東'],

That will fix the issue.

To Dev, Tver recently change the label that causes this issue.

**Comment by joaopa00** [comment]
Fix committed. Thanks Kalun85 for the tip.
If the bug persists in beta 13, don't hesitate to reopen it.

**Comment by KylanHaffie** [comment]
Thanks ! I can confirm this is fixed. 

Back to watching some Japanese TV 📺

Thank you !!!
