### ISSUE TITLE
cherie25 gets a 403

### ISSUE THREAD

**Issue by robertandrewbain** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1410]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
Live TV->France->Cherie 25 - HTTP 403

### To Reproduce
Steps to reproduce the behaviour:
1. Navigate to Live TV
2. Navigate to France
3. Navigate to Cherie 25
4. Receive Exception message

### Expected behaviour
Shows channel

### Actual behaviour
Error popup

**Comment by joaopa00** [comment]
Incapable de reproduire le probleme. Pour moi, Cheri25 se lance (samedi 5 Octobre 6H41)

**Comment by robertandrewbain** [comment]
<img width="447" alt="Screenshot 2024-10-05 at 08 22 30" src="https://github.com/user-attachments/assets/7815eda0-ae60-4fd0-ae98-e87de5d37c12">

**Comment by joaopa00** [comment]
D'abord ce n'est pas le direct. C'est le rattrapage. J'arrive à reproduire le problème.  Mais le gros point d'achoppement est que j'arrive même pas à jouer le rattrapage sur le site de nrj-play à travers un navigateur (je suis sur linux).

Peux-tu confirmer?

**Comment by joaopa00** [comment]
Problème  résolu du côté de NRJ.
