### ISSUE TITLE
Channel 4

### ISSUE THREAD

**Issue by grapenose** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1416]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
A clear and concise description of what the bug is:
Channel 4 not longer loads Run Time Error, Item not found

### To Reproduce
Steps to reproduce the behaviour:
1.load Kodi
2.Go to Channel 4
3.Go to program 
4.Run Time Error 

### Expected behaviour
A clear and concise description of what you expected to happen:
Program will load
### Actual behaviour
Tell us what happens instead:
Program does not load with error message as above
### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android Sony TV and Amazon Fire TV Cube 3rd Gen both running latest Kodi
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version:20.3
 - Catch-up TV & More version:
 - Installation method: kodi add on library

### Additional context
Add any other context out the problem here:
Have tried Channel 4 on PC and Fire Cube and programs play OK
### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment]
Can you give a try?

[test version](https://docs.google.com/uc?export=download&id=1vrzpQPSD-3RgIiF_yk_44NnOwYCi49ac)

**Comment by grapenose** [comment]
That worked on my Fire Cube TV but I'm not sure it worked on my Sony Bravia.
Will check again as I might not have installed the above version. Too many USB dongles!!
Thanks for that.
 I thought that maybe Channel 4 now required you to have user and password.

**Comment by grapenose** [comment]
My mistake, didn't install the above version. Now working on Sony.
Thanks again

**Comment by joaopa00** [comment]
Thanks for testing. Patch committed in GIT. I am closing this issue.
