### ISSUE TITLE
France 24 OUT (Windows et Linux)

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1417]
### Your environment
 - [ ] Android
 - [ ] iOS
 - [x ] Linux Mint 20.3
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x ] Windows 10
 - [ ] Other

 - Kodi version: 21.1 (win) 20.2 Mint
 - Catch-up TV & More version: latest beta

**Comment by joaopa00** [comment]
Should be fixed in git. Thanks for the report.
