### ISSUE TITLE
LCP ne fonctionne pas - Android (Mi Box)

### ISSUE THREAD

**Issue by khalistoo** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1423]
En sélectionnant LCP j'ai un pop up mentionnant error key 'qualities'.

Je me doute que ce n'est pas une chaîne ultra utilisée, mais ca doit faire 2 voir 3 release que le problem persiste. 

Debug log:

https://paste.kodi.tv/enefeholuh

```
2024-11-05 18:44:22.198 T:6178    error <general>: [Catch-up-TV-&-More.support] 'qualities'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                       results = super(Resolver, self).__call__(route, args, kwargs)
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/lcp.py", line 183, in get_live_url
                                                       return resolver_proxy.get_stream_dailymotion(plugin, live_id, False)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/resolver_proxy.py", line 328, in get_stream_dailymotion
                                                       url = json_parser["qualities"]["auto"][0]["url"]
                                                             ~~~~~~~~~~~^^^^^^^^^^^^^
                                                   KeyError: 'qualities'
```

Si vous avez une idée, je suis preneur et je peux essayer de fixer

**Comment by caywin25** [comment]
C'est curieux je viens de tester chez moi ça fonctionne bien.
Tu es sous quel env ?
Tout est bien à jour ?

**Comment by joaopa00** [comment]
Chez moi aussi ca fonctionne très bien: Linux et Android.
C'est pour ça qu'il y a un canevas de  rapport de bug à remplir soigneusement. Ca permet de penser à certaines directions d'où pourrait provenir le problème.

**Comment by khalistoo** [comment]
Oui tout est a jour, je suis sur la Version 0.2.40-beta13

J'expliquais dans mon message que, cela faisait deux trois releases que c'est comme ca donc je ne pense pas que ce soit la version spécifique le problem. 

Ca me fait ca sur android TV (mi-box) uniquement mais pas sur Linux

**Comment by Realys-31** [comment]
Yo!
Aucun Pb pour LCP sur : LibreELEC 12.0.1 - Generic-legacy.x86_64(Linux x86 64-bit) - Kodi 21.1-Omega
La chaine fonctionne normalement.
Tchuss !

**Comment by Realys-31** [comment]
@khalistoo , as-tu toi aussi sur ta MiBox, une erreur "index out of range" pour les chaines spectacles-et-culture et paris-24 ?
c'est à la ligne 413 de francetv.py "broadcast_id = re.compile(r'videoId\"\:\"(.*?)\"', re.DOTALL).findall(resp.text)[0]"
il n'aime pas l'inex  [0] à la fin.
Merci ;-)

**Comment by joaopa00** [comment]
@khalistoo: Quelle version de Kodi utilises-tu?
Toute verion inférieure ou égale à Nexus n'est plus suportée par l'équipe de Kodi. En particulier, Inputstreamadaptive n'est plus mis à jour pour ces versions.

**Comment by khalistoo** [comment]
@Realys-31  je n ai pas ces chaînes, je vais voir pour les rajouter et confirmer

@joaopa00  comme tu peux le voir sur le log que j ai partage je suis sur Omega: 
Kodi (21.1 (21.1.0) Git:20240817-d00181569e). Platform: Android ARM 32-bit

https://paste.kodi.tv/enefeholuh

Et j ai eu une mise a  jour pour InputStream Adaptive (21.5.6) le 5 Novembre donc ca devrait être bon.

Mais comme dit plus haut, ca doit bien faire deux ou trois beta que j ai cette erreur uniquement pour cette chaîne et seulement, sur Android, et je suis a cours d’idée.

J’imagine que Public Sénat fonctionne sur le meme principe que LCP et ca marche très bien. 

Il reste toujours l'option de faire une clean install du plugin mais j'aimerai éviter d'en passer par la.

**Comment by joaopa00** [comment]
Un log avec les jounraux activés aiderit beaucou· Il faut activer les canaux  libcurl video audio ffmpeg

**Comment by khalistoo** [comment]
Laissez tomber, je semble être le seul a avoir un  soucis, le log avec les canaux actives c'est supérieur a 1 M donc je peux difficilement upload sur pastebin, je me débrouillerai c'est pas grave. Je ferme cette issue vu que ca ne semble toucher que moi. Merci pour votre aide a tous
