### ISSUE TITLE
Erreur replay + direct toutes les chaines

### ISSUE THREAD

**Issue by QuentinLf** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1426]
Bonjour,

Sur ma TV android, je viens d'installer Kodi omega v21.1 en suivant le tuto suivant: https://troypoint.com/install-kodi-on-android-box/
Puis j'ai Catch up TV an suivant ce tuto: https://catch-up-tv-and-more.github.io/fr/installation/
Puis j'ai installer IPTV manager avec ce tuto: https://catch-up-tv-and-more.github.io/fr/live_tv_installation/

J'ai bien entré mes identifiants et mot de passe (par exemple pour M6), quand je lance n'importe quel replay, j'ai une erreur indiquant: "url not found". Même chose avec des replay de chez France TV.

La télé en direct en passant par Catch up tv ne fonctionne pas non plus. Savez vous comment régler ce problème ?

Merci

**Comment by Sarah2734** [comment]
J'ai le même soucis depuis lundi avec m6, as tu trouvé une solution?

**Comment by Xilophon3** [comment]
Salut,

Quelle version de Catch up TV utilises-tu ?

j'avais un pb pour lire les replay M6 et en installant la version 0.2.40~Beta 15 je n'ai plus de pb.

**Comment by Sarah2734** [comment]
J'ai la version 0.0.6

**Comment by QuentinLf** [comment]
J’ai la version stable 0.2.39 + matrix.1 par SylvainCecchetto

**Comment by Sarah2734** [comment]
Je vais voir de changer si ça resoud mon problème. TF1 marche mais pas 6play

**Comment by Sarah2734** [comment]
J'ai fait l'update et ça ne marche toujours pas

**Comment by QuentinLf** [comment]
Je viens d'installer la version 0.2.40 beta 15 et live + replay de M6, TF1 et France TV fonctionnent.

**Comment by Xilophon3** [comment]
@Sarah2734 installe la version Beta 0.2.40 beta 15

**Comment by Sarah2734** [comment]
Est-ce que tu peux me donner le repo? Quand tu cherche pour une update j'ai rien qui sort

**Comment by Xilophon3** [comment]
Salut,

Suis cette procédure et selectionne le canal Beta.

https://catch-up-tv-and-more.github.io/fr/installation/

**Comment by daffy25** [comment]
Je confirme; L'installation de la version la version 0.2.40 beta 15 a tout résolu.
Merci.

**Comment by Sarah2734** [comment]
C'est ce que j'ai mais quand je cherche pour la version 0.2.40, je ne la trouve pas et j'ai seulement la version 0.2.39

Je vais co tinuer de patienter en espérant trouver une solution

**Comment by Xilophon3** [comment]
Qu'as tu lorsque tu restes cliqué 1 à 2 sec sur catch up tv and more ?
Dans informations/ version

![Screenshot_20241118_072805_Kodi](https://github.com/user-attachments/assets/1e391983-5bc7-4fe7-a6ce-749239055fb5)
![Screenshot_20241118_072813_Kodi](https://github.com/user-attachments/assets/164973fe-1141-40c3-aa0f-5926cb3ca80c)
![Screenshot_20241118_072826_Kodi](https://github.com/user-attachments/assets/fb687d19-9d70-4b36-9808-2713a74713be)
