### ISSUE TITLE
TF1 account not detected

### ISSUE THREAD

**Issue by tguillaume02** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1429]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

I downloaded and installed the latest beta version and it's impossible to watch TF1.
I get an error popup asking me to set up my tf1 account, but it's already set up.
The catch-up version is 0.2.40-beta15

To reproduce:

Just try watching TF1 live 

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 21.1
 - Catch-up TV & More version: 0.2.40-beta15

**Comment by joaopa00** [comment]
Have a look at the file
.kodi/userdata/addon_data/plugin.video.catchuptvandmore/settings.xml
and check your login and  password  are here for tf1plus.

**Comment by tguillaume02** [comment]
Yes the login and password are in this file

**Comment by joaopa00** [comment]
A log with libcurl ffmpeg video and audio channls could give some hints about the problem.

**Comment by tguillaume02** [comment]
it's work again, without modification
