### ISSUE TITLE
BFM TV, 2 * RMC et Regionales hs

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1431]
### Your environment
 - [ ] Android
 - [ ] iOS
 - [ x] Linux Mint 20.3
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x ] Windows  10
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 21.1 on Windows, 20.2 on Linux
 - Catch-up TV & More version: latest beta
 - Installation method: upgrade from previous

### Debug log partial
2024-11-19 14:09:59.670 T:1673    error <general>: GetItemsForPlayList: Unable to get playlist items for plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/rmcbfmplay/get_live_url/?_pickle_=8004955d000000000000007d94288c075f7469746c655f948c1642464d20545620e280942037204a6f7572732042464d948c08786d6c74765f6964948c14433438312e6170692e74656c6572616d612e6672948c076974656d5f6964948c0642464d20545694752e
2024-11-19 14:10:01.132 T:1719    error <general>: [Catch-up-TV-&-More.support] 'NoneType' object has no attribute 'group'

**Comment by jbbriois** [comment]
RMC Decouverte and RMC Story also

**Comment by enigma131** [comment]
Exactly .... and regional BFM's
Title changed .

**Comment by joaopa00** [comment]
Les problèmes non rien à voir entre eux. Pour BFMTV le direct sur le lien dailymotion qui est utilsé est interrompu.
Pour les autres chaînes de RMC, il y avait un moyen de contourner un bug avec Inputstream Adaptive qui est non seulement inutile maintenant mais en plus qui provoque un problème depuis un changement sur le site de RMC.

Pour BFMTV, je vais attendre quelques jours pour voir si le direct se rétablit sur dailymotion, sinon j'utiliserai les liens  du site de RMCplay.

Pour les autres chaînes de RMC, ca doit être résolu dans GIT.

**Comment by enigma131** [comment]
Merci, tout est revenu ce matin en modifiant manuellement le fichier .py . 
Donc BFM TV est revenu sur daily ....
Je ne ferme pas tant qu'une release n'est pas sortie.

**Comment by ssAxl** [comment]
Bonjour,

Quelles modifications et sur quel fichier .py tu as faite pour bfm?

Merci!

**Comment by enigma131** [comment]
Onglet code et regarder le dernier commit, c'est le principe de Github : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/cbc8b82fc1f6b196c0f0c2ffba04b933de1ae1ab

**Comment by ssAxl** [comment]
Ah OK pardon!
Merci beaucoup

**Comment by caywin25** [comment]
Le fix marche super bien.
@joaopa00 comment tu fais pour savoir quoi changer et fixer comme ça stp ? :)

**Comment by enigma131** [comment]
I did not get version beta 16, why ?
Edit : got it now

**Comment by ludovic-79** [comment]
Bonjour, chez moi le direct et le replay des chaines RMC ne fonctionne toujours pas avec la beta 16. J'ai le même message d'erreur que la béta 15 (403 Client error forbidden for url https://sso.rmcbfmplay.com/cas/services/rest/3.2/createToken.json?duration=86400).

**Comment by enigma131** [comment]
Quel OS ?

**Comment by ludovic-79** [comment]
Linux avec Kodi 21.1, lubuntu avec Kodi 21.1 et libreelec 10 avec Kodi 19.3.
Le problème est identique sur les 3.

**Comment by enigma131** [comment]
"Catch-up TV & More channel logos and artwork" est à jour ?  1.0.25 ici
Autre questions : depuis quel pays?   Vpn ?
Compte et mot de passe corrects ?
Cela fonctionne via un navigateur Internet ?

**Comment by ludovic-79** [comment]
"Catch-up TV & More channel logos and artwork" : est à jou
Je suis en france, pas de VPN
Compte et mot de passe ok, 
Oui cela fonctionne bien via navigateur.
