### ISSUE TITLE
date incorrect affiché sur l'émission zone interdite du replay de M6

### ISSUE THREAD

**Issue by monfiston** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1432]
Bonjour
les dates qui sont affichées dans dans le replay de m6 pour l'émission "zone interdite" sont incohérente

voici les dates qui sont affiché dans le plugin
![image](https://github.com/user-attachments/assets/304821a1-0d3b-4a25-a679-6f5056ca03a7)
ce qui est impossible car l'émission est diffusé toutes les 2 semaines le dimanche à 21h

exemple, cette vidéo a été diffusé réellement le 01/08/2023, mais dans le plugin la date est 16/11/2024
![image](https://github.com/user-attachments/assets/efe2393f-44f4-4381-8f31-25d51e0f6b10)

çà le fait sur la platorme windows et coreelec
je suis avec la dernière version béta du plugin

**Comment by joaopa00** [comment]
Ce sont les infos mises à jour fournies par M6 dans leur API. Pas grand chose que l'on puisse faire de notre côté.

**Comment by monfiston** [comment]
bonjour
c'est très étonnant, car mes dernières captures d'écrans avec la bonne date, proviennent du site m6 replay

**Comment by joaopa00** [comment]
>aired = clip_dict['product']['last_diffusion']

Dans le code de CUTVM le choix a été fait de donner la date de dernière diffusion de l'émission pas la date de première diffusion forunie sur le site.

On pourrait utiliser le paramètre first_diffusion. Question de goût. Au final, je vais garder la dernière diffusion.

**Comment by monfiston** [comment]
OK,
Par contre, c est peut être la date de dernière diffusion, mais ce n est pas le cas en réel,  il n y a jamais eu tous les jours zone interdite,  cette date ne veut rien dire sur le site m6, et ce n est pas la seul émission comme cela, de temps en temps, il y a capital aussi, mais ce n est pas systématique

**Comment by monfiston** [comment]
bonjour
je suis désolé d'insister, mais voici les émissions que j'ai trouvé qui ont une incohérence avec les dates
zone interdite
enquête exclusive
![image](https://github.com/user-attachments/assets/4381bad2-f580-4a96-a6c8-8ac083729d3b)
turbo
![image](https://github.com/user-attachments/assets/577286d9-dc9f-43a1-8a23-90ecf4497c6c)

et il y en a certainement d'autre
