### ISSUE TITLE
Impossible de mettre les chaînes RMCBFM et chaînes M6 En direct 

### ISSUE THREAD

**Issue by LucMrt** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1436]
Bonjour ! Je rencontre un problème sur Catch UP. Je n'arrive pas à mettre les chaînes RMCBFM et M6/W9 en direct, ça me met plusieurs messages d'erreurs.

Pour les chaînes M6 : Error Not Found the URL (url de 6play)

pour les chaînes BFM : NOne Type object has no attribute group

**Comment by joaopa00** [comment]
S'il ya un canevas de rapport de bug, ce n'est pas fait pour être effacé. Le remplir permet d'avoir des informations essentielles pour essayer de resoudre le bug.
Quel appareil, quel version de catchuptvandmore, quelle version de Inpustream adaptive
Ajouter un log avec les canaux libcurl, ffmpeg, video et audio activés est un gros plus pour le diagnostique.

Dans l'état, ton rapprt de problème est complètement inutile.

**Comment by LucMrt** [comment]
Donc je ne peux pas exprimer mes problèmes ? Je ne comprends pas le sens de ton message

**Comment by Xilophon3** [comment]
@LucMrt,

Quel version de CUTM tu as ?

**Comment by LucMrt** [comment]
@Xilophon3 ma version est : 0.2.39+matrix.1

**Comment by Xilophon3** [comment]
re,  suis exactement ce que j'ai écris [ICI](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1435)

**Comment by LucMrt** [comment]
J’ai ajouté la source pour permettre de mettre le fichier Zip mais on me dit que je peux pas récupérer les informations de la source (https://repo.cecchettosylvain.fr/zip)

**Comment by Xilophon3** [comment]
je te conseille de tout supprimer et de refaire une installe propre en suivant le tuto

**Comment by LucMrt** [comment]
J’ai suivi le Tuto! J’ai réussi, merci beaucoup de votre réponse et de votre aide !
