### ISSUE TITLE
M6+ Http Eror

### ISSUE THREAD

**Issue by Minepluie** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1439]
I have a 404 eror if i watch m6 or gulli

**Comment by Xilophon3** [comment]
Salut,

quel est ta version de Kodi et de Cutvm ?

**Comment by joaopa00** [comment]
Pas de nouvelles...

**Comment by Minepluie** [comment]
mais ca fonctionne avec tf1+ et avec francetv ca fonctionne pas

**Comment by Xilophon3** [comment]
@Minepluie tu n'as pas repondu a ma question

**Comment by Minepluie** [comment]
comment on voit sa version sur la version windows ?

**Comment by Xilophon3** [comment]
Clique droit sur cutvm et informations puis version.

**Comment by Minepluie** [comment]
0.2.39 pour cutvm et 21.1.0 pour kodi

**Comment by Xilophon3** [comment]
Ok essaie d'installer la version  bêta de Cutvm: 

Suis ce [tuto](https://catch-up-tv-and-more.github.io/fr/installation/) installes le canal beta, ensuite une fois tout installé sélectionne bien la dernière version bêta de cutvm.

**Comment by Minepluie** [comment]
c'est bon ca fonctionne mais le pvr est a 0 % de chargement et ca n'avance pas
j'ai configurer comme sur le site

**Comment by Xilophon3** [comment]
Essaie de tout supprimer et relancer une installation propre

**Comment by Minepluie** [comment]
desinstaller kodi ?

**Comment by Xilophon3** [comment]
Non juste cutvm

**Comment by Minepluie** [comment]
ca change rien

**Comment by Xilophon3** [comment]
désolé pour toi, je ne peux pas t'aider plus, ouvre un nouveau ticket avec capture d'écran et les logs.
