### ISSUE TITLE
[M6+] Impossible to stream replay (black screen)

### ISSUE THREAD

**Issue by sousouille** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1441]
⚠️ *Please try the last beta version and check existing issues before issuing a bug.* ⚠️

### Describe the bug
I try to watch "La france a un incroyable talent" S19E07 parts 1 and 2. Impossible to launch the stream, it launches black screen. When I relaunch, Kodi stucks.
I suppose DRM issue.

### To Reproduce
Steps to reproduce the behaviour:
1. In CatchUpTVAndMore, Go in Replays ➡ France ➡ 6play ➡ M6 ➡ Divertissement ➡ La france a un incroyable talent ➡ S19 ➡ E07 part 1 or part 2
2. Stream launch and stop on black screen
3. When I relaunch, Kodi stucks

### Expected behaviour
Stream should plays

### Actual behaviour
Black screen 

### Your environment
 - [X] Android on NVidia Shield TV Pro

 - Operating system version/name: Android TV on NVidia Shield TV Pro
 - Kodi version: 21.1
 - Catch-up TV & More version: last
 - Installation method: from beta repo

### Additional context
It works on Android 14 on smartphone
It works on Windows too
It works with other episods (S19E06part1 for example)

I try to uninstall catchuptvandmore and reinstall with dependance but same things.

TF1 replays is making the same things but when I relaunch it works (in M6+ it stucks Kodi).

### Debug log
https://mega.nz/file/R4tQlD5S#C3cj9jj_k26qo21WVVOMKtXNuhTPNsd7HseZ6TmoW0s

Step of the log : 
1- Launch the stream with the issue (S19E07 part2)

**Comment by Xilophon3** [comment]
Salut @sousouille,

Je viens de tester sur CUTVM version 0.2.40~Beta 16 pas de pb.

**Comment by sousouille** [comment]
Salut @Xilophon3 ,
J'avoue que ça fonctionne sur d'autres ptf.
Est-ce que les logs parleraient sur la source du pb ?

**Comment by Xilophon3** [comment]
Il faut que tu tests avec la dernière version bêta je suis sûr que c'est ça le pb.

**Comment by sousouille** [comment]
Dans la log : je suis bien dans la bonne version : plugin.video.catchuptvandmore v0.2.40~beta16 installed

**Comment by Xilophon3** [comment]
Envoi tes logs pour voir stp

**Comment by joaopa00** [comment]
Surtout dans les log, il faut que les canaux ffmpeg, libcurl video et audio soient activés. Il n(y a rien de probant dans le log attaché dans le premeir message.


Question idiote: tu es sûr de tes identifiants?
J'ai testé l'émission: pas de problème sur AndriodTv et linux.

**Comment by sousouille** [comment]
Hello, yes sûr de mes identifiants. En fait, le comportement réel (que je viens de découvrir) est que si j'attends longtemps avec l'écran noir (~4min), la vidéo se lance mais sans son et ça finit par freeze au bout de quelques secondes de lecture.
J'active les canaux demandés pour les logs et revient vers vous.
Et en effet, sur mes différentes autres ptf ça fonctionne bien (Windows ou Android). Je suppose que sur ma Shield, j'ai une config qui rend déconnant certaines lectures :
skin : Arctic Horizon 2
plugins principaux (en plus de CUTV&M): vstream, tmdb helper, trakt
conf : audio passthrough activé

**Comment by sousouille** [comment]
J'ai mis à jour la log avec les éléments nécessaires 🤞

**Comment by sousouille** [comment]
Je vois le lancement de la video au alentours de : 2024-12-14 14:07:18.132

**Comment by sousouille** [comment]
Je vois ça : 
```
2024-12-14 14:08:16.336 T:15534   debug <general>: Curl::Debug - TEXT: ipv6 connect timeout after 29998ms, move on!
2024-12-14 14:08:16.336 T:15534   debug <general>: Curl::Debug - TEXT: Failed to connect to par5-edge-08.cdn.bedrock.tech port 443 after 30029 ms: Timeout was reached
2024-12-14 14:08:16.336 T:15534   debug <general>: Curl::Debug - TEXT: Closing connection
2024-12-14 14:08:16.338 T:15534   error <general>: CCurlFile::CReadState::FillBuffer - (0x221c692390) Failed: Timeout was reached(28)
2024-12-14 14:08:16.338 T:15534   error <general>: CCurlFile::Open - <https://par5-edge-08.cdn.bedrock.tech/m6web/output/8/1/9/819315650b9228fcf946053627beaac0dcdc8e29/essence_ott-st1-mp4-aac-96000_t1_p1_20241205-101227_a7819ce4b9d3c7898e41aa08e2870e70-3_dash_unp_b062a8.ism/dash/essence_ott-st1-mp4-aac-96000_t1_p1_20241205-101227_a7819ce4b9d3c7898e41aa08e2870e70-3_dash_unp_b062a8-audio1=96000-0.dash> Failed with code 0:

```

**Comment by sousouille** [comment]
Eh bien, en désactivant l'IP V6 sur la box ça fonctionne désormais.
