### ISSUE TITLE
Chaine live/replay de rmc story, découverte,  et m6 hs

### ISSUE THREAD

**Issue by monfiston** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1446]
Bonjour 
Depuis quelque jours, les Chaines live/replay de rmc story, découverte,  et m6 hs
Erreur http, max connexion 
Je suis avec les dernières versions beta du plugin

**Comment by joaopa00** [comment]
Que veux tu que l'on fasse avec un tel rapport de bug. Il n'y a aucune information utile dedans. Ce n'est pas la première fois que tu fais cela.

**Comment by monfiston** [comment]
Tu as testé ?
Il est inutile de détaillé plus quand ça ne fonctionne sur plusieurs plate-forme !!!

**Comment by joaopa00** [comment]
![CUTVM8RMCBFMPLAY](https://github.com/user-attachments/assets/f8fdb44f-efd3-4f66-99cf-4e2aef701001)


Oui j'ai testé justement. Et ça fonctionne chez moi (Linux et Android)
