### ISSUE TITLE
Kodi freeze sur certaine video de replay groupe M6

### ISSUE THREAD

**Issue by Smanar** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#1449]
### Describe the bug
Kodi freeze sur certaine video de replay groupe M6

### To Reproduce
Steps to reproduce the behaviour:
1. Aller dans Télévision de rattrapage / france / 6 play / W9 / Serie réalités
2. Alors pour tester "les cerveaux"
3. Lancer Saison1/Ep4> pas de soucis
4. Lancer Saison1/Ep8 > Frezze.

### Expected behaviour
Voir la video

### Actual behaviour
Kodi freeze, onbligé de tuer la tache

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x ] Windows
 - [ ] Other

 - Operating system version/name: Win 10
 - Kodi version: 21.1
 - Catch-up TV & More version: 2.2.40 beta
 - Installation method:

### Debug log
(A venir)

**Comment by joaopa00** [comment]
Pas de probleme chez moi

**Comment by Smanar** [comment]
Tu as essayé sur les mêmes épisodes que moi ? J'ai essayé d'en trouver 2 spécifiques.
Sinon je vais passer les logs, mais j'ai essayé un peu tout les réglages avec le même résultat.

**Comment by joaopa00** [comment]
J'ai testé les mêmes émissions que toi.

**Comment by Smanar** [comment]
Ok, donc je viens de l'installer sur une autre machine et ca passe.
Je vais faire quelques comparaisons avant de passer des logs

**Comment by Smanar** [comment]
Bon ben désolé ^^.
Il y avait 2 options décochées, me demandez pas pourquoi, mais maintenant ca remarche sur toutes les videos.
- Utiliser InputStreams HLS
- Une autre directement dans l'extension InpustStream, mais la je ne me souviens plus

Les dernieres videos doivent avoir "plus de DRM"....

En tout cas merci pour les tests.

**Comment by joaopa00** [comment]
Bonne nouvelle
