### ISSUE TITLE
BVN uses DRM now

### ISSUE THREAD

**Issue by Forage** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#146]
It looks like non of the episodes on BVN work any longer, due to the introduction of DRM.
On Kodi it will just display a static screen saying "De opgevraagde uitzending is niet beschikbaar" ("The requested emission is not available"). Trying to watch the same in a desktop browser will display a notification (Firefox) asking you to enable DRM.

**Comment by wwark** [comment]
Hi @Forage,
Thanks for the update I will look into it.

**Comment by wwark** [comment]
Hi @Forage,
I push a commit to fix replay BVN (using DRM implementation)
Can you please test the 0.2.5~beta02 ?

Thanks,
Wwark

**Comment by Forage** [comment]
Darn you work fast! I only got round to analyzing the situation and came to the conclusion that a fix would be in the same lines as you already fixed it. I just didn't have the time to actually implement a fix myself yet.

It is working again, many thanks.

**Comment by wwark** [comment]
Thank you ! I understand a lot DRM stuff so it is mostly copy/paste from other channel :)

I closed this ticket !
