### ISSUE TITLE
Add NPO - Test live TV / Replay

### ISSUE THREAD

**Issue by wwark** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#149]
Hi @Forage,

I tried to add some Live TV from "https://www.npostart.nl/live" using code from bvn channel.
But I get HTTP 403 with calling this url https://www.npostart.nl/api/token (request this header "x-xsrf-token:" but I don't find how to get it.)
[plugin.video.catchuptvandmore-testnpo.zip](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/2923464/plugin.video.catchuptvandmore-testnpo.zip)

If you can take a look in this zip file, it will be helpfull ?

THanks for your help,
Wwark.

**Comment by Forage** [comment]
It is missing the header "X-Requested-With" with value "XMLHttpRequest"

**Comment by wwark** [comment]
good thank you I will test this evening.
With this change did you manage to play the live tv ?

**Comment by wwark** [comment]
I have HTTP 419 with this code

headers = {
        'X-Requested-With': 'XMLHttpRequest'
    }

    resp_token = urlquick.get(URL_TOKEN_API, headers=headers, max_age=-1)
    json_parser_token = json.loads(resp_token.text)
    token = json_parser_token['token']

how did you get this token ?

**Comment by Forage** [comment]
You need the other two headers you had before as well. So the three in total.

**Comment by Forage** [comment]
Simply with the following I get a token already: 

```
headers = {
        'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36',
        'X-Requested-With': 'XMLHttpRequest',
        'x-xsrf-token': 'eyJpdiI6InhXT3FcL244Y0hzRzFxdk45UlUrRmpBPT0iLCJ2YWx1ZSI6IkhMY3RCUExsMWZcL0pPUkhKTklpcWwyYmhHWDYwNEEzQVNEUWZYY2hEeWczYUtFQXFENW9wMXM5b1g1RzZSdXlrRlNuWk9BUWVENXRUdkdOUmRXaVBkZz09IiwibWFjIjoiYmJlYTY4MGJhNWY4NjE2MmY0YzM1ZGE1MTUyMGY5ZjNkYjFlYjJmMTkwNmI1YjQ2MDA1YTA2Yzg1NTU3Y2U4MyJ9'
    }
```

I did not change anything more in your provided add-on.
It is the subsequent `resp2 = urlquick.post(URL_TOKEN_ID % video_id, data=payload)` that results in the "HTTP Client Error 419" error. I have the feeling it is due to the `x-xsrf-token` no longer being valid, but I have not yet found a way to determine a new one each call.

**Comment by wwark** [comment]
Thank you for your test I have also HTTP 419.
"Not a part of the HTTP standard, 419 Authentication Timeout denotes that previously valid authentication has expired"
NPO Nieuws is not goelocalized.
I don't know how to generate or get this token also for live tv.
I will check if we can manage for replay.

**Comment by Forage** [comment]
I checked with a VPN, no difference.
I'm also not convinced that the string in the `x-xsrf-token` header has anything to do with it. Leaving it out of the request for a token will provide you with one just as well. It might not have any more purpose than it's original intent, preventing Cross-Site Request Forgery.

As for integrating NPO replay. I'd love to have that and I was planning on giving it a go, but I haven't found the time yet. Have a look at https://github.com/Opvolger/plugin.video.uzg for 'inspiration' ;)

**Comment by Forage** [comment]
After trying loads of different combinations again I don't see why the POST does not work. I'm starting to think the answer might be in the cookies.

**Comment by wwark** [comment]
Code NPO

```
headers = {
        'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36',
        'x-xsrf-token': 'TO_GET_OR_TO_BUILD'
    }

    **resp_token = urlquick.get(URL_TOKEN_API, headers=headers, max_age=-1)**
    json_parser_token = json.loads(resp_token.text)
    token = json_parser_token['token']

    resp = urlquick.get(URL_LIVE_ID % item_id, max_age=-1)

    video_id = re.compile(
        r'\"iframe\-(.*?)\"').findall(resp.text)[0]

    # Build PAYLOAD
    payload = {
        "_token": token
    }

    resp2 = urlquick.post(URL_TOKEN_ID % video_id, data=payload)
    json_parser = json.loads(resp2.text)
    token_id = json_parser['token']

    resp3 = urlquick.get(URL_STREAM % (video_id, token_id), max_age = -1)
    json_parser2 = json.loads(resp3.text)
```

Code BVN


```
resp = urlquick.get(video_url, max_age = -1)

    token_id = re.compile(
        r'start\-player\.npo\.nl\/embed\/(.*?)\"').findall(resp.text)[0]
    video_id = re.compile(
        r'\"iframe\-(.*?)\"').findall(resp.text)[0]

    resp2 = urlquick.get(URL_REPLAY_STREAM % (video_id, token_id), max_age = -1)
    json_parser = json.loads(resp2.text)
```

resp3 in NPO corresponding to resp2 in BVN.
The problem is on generate or build x-xsrf-token used in a get of this url https://www.npostart.nl/api/token (not a post) this token is not present in BVN side. It will help to get the token_id (second token). This token_id (bvn side) is find directly on the html page on the content.

**Comment by Forage** [comment]
The value comes from a cookie named `XSRF-TOKEN` set on access to the page. This is the value that needs to be repeated in all the subsequent requests.

**Comment by Forage** [comment]
In fact, it isn't until the initial token URL is called that the cookie is set, so the following gives you a xsrf_token and sets it for the final token post:

```
    headers = {
        'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36',
        'X-Requested-With': 'XMLHttpRequest'
    }

    resp_token = urlquick.get(URL_TOKEN_API, headers=headers, max_age=-1)
    xsrf_token = resp_token.cookies['XSRF-TOKEN']
    xbmc.log(xsrf_token, xbmc.LOGWARNING)
    
    json_parser_token = json.loads(resp_token.text)
    token = json_parser_token['token']
    xbmc.log(token, xbmc.LOGWARNING)
    
    resp = urlquick.get(URL_LIVE_ID % item_id, max_age=-1)

    video_id = re.compile(
        r'\"iframe\-(.*?)\"').findall(resp.text)[0]

    xbmc.log(video_id, xbmc.LOGWARNING)
    
    # Build PAYLOAD
    payload = {
        "_token": token
    }
    
    headers = {
        'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36',
        'x-xsrf-token': xsrf_token,
        'X-Requested-With': 'XMLHttpRequest'
    }

    resp2 = urlquick.post(URL_TOKEN_ID % video_id, headers=headers, data=payload)
    json_parser = json.loads(resp2.text)
    token_id = json_parser['token']
```

But as it turns out, again no luck.

It even confirmed my suspicion a bit more that we should not look for the answer in the x-xsrf-token token use:
1. Delete all your npostart.nl cookies
2. Go to https://www.npostart.nl/live/npo-nieuws in your browser directly
3. Monitor your network

The https://www.npostart.nl/api/token call will set the cookie, but the https://www.npostart.nl/player/LI_NEDERLAND1_221673 post after that won't even set the x-xsrf-token header, while it works all the same.

**Comment by wwark** [comment]
thank you I will continue to check.

**Comment by Forage** [comment]
Got it!

It was the `npo_session` cookie that we needed.
[npo.py.txt](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/2935929/npo.py.txt)

Attached you'll find the working code. I stripped it to its bare minimum in terms of headers. This was the final step to get your script working.

**Comment by wwark** [comment]
Yeahhhhhhhhhhhhhhhhhhhhh !!!!
Good work :+1: 
I will add the icon of each live tv and commit it !

**Comment by Forage** [comment]
Great :)
You might want to consider adding the geo-block check and error as well though. Not all of the channels will work in a foreign country.
I can't check at the moment, but I suppose the method should be the same as with BVN. Instead of a token/license/url whatnot I expect you'll get a html property in the json result of your final token call telling you you can't access the broadcast.

**Comment by wwark** [comment]
Yes it is the same. I put the check for foreign country.
It is updated for live TV.
Thanks a lot.

**Comment by wwark** [comment]
for info I commited a skeleton for the Replay of NPO.

**Comment by wwark** [comment]
1st version of catch-up tv of NPO is available in beta03. (need works)

**Comment by Forage** [comment]
Thanks for working on this, I still didn't get round making time for it to do it myself.
Why not use the JSON API directly (https://start-api.npo.nl) instead of parsing website pages though? It should be more efficient and stable.

**Comment by wwark** [comment]
I will take a look in the JSON API if I find a way to propose contents.
Thanks,
Wwark.

**Comment by wwark** [comment]
Done with the JSON API (catch-up tv OK)
