### ISSUE TITLE
Ajout du site ADN (Anime Digital Network)

### ISSUE THREAD

**Issue by bast69** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#152]
Bonjour,
Est-il possible d'ajouter ce site "https://animedigitalnetwork.fr/", il propose des vidéos sur des mangas de manière légale moyennant un compte avec abonnement ou pas.
Merci de votre travail

**Comment by wwark** [comment]
Bonjour Bast69,

Ce plugin est plutôt dédié replay et direct tv. Il n'existe pas de plugin Kodi pour animedigitalnetwork?
De plus, nous n'avons pas de contenus payant sur le plugin pour l'instant. (Il faudrait qu'on prenne un abonnement pour pouvoir l'implémenter)

S'il n'existe pas de plugin pour Kodi, il faudrait peut-etre demander sur ce forum pour voir si un développeur souhaiterais prendre en compte cette demande : https://forum.kodi.tv/forumdisplay.php?fid=154

Merci,
Wwark

**Comment by bast69** [comment]
Bonjour Wwark,
Merci pour ce retour, étant donné qu'il y a une partie "site internet", je me suis permis de poser la question :)

Je vais voir sur le forum que tu as mis en lien.

Merci
bast69

**Comment by wwark** [comment]
Merci !

Oui il y a quelques sites web (la grande majorité des sites webs sont des contenus déjà proposés sur des chaines télé)

J'espère que tu pourras trouver une personne voulant travailler sur l'implémentation de ce site web sur Kodi.

Merci,
wwark.
