### ISSUE TITLE
Le replay Cnews ne fonctionne plus...

### ISSUE THREAD

**Issue by gilles0606** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#155]
hello,

le replay de Cnews ne fonctionne plus chez moi ?
et vous ?

merci

**Comment by wwark** [comment]
Hello @gilles0606,

Je confirme que les contenus ne sont plus listés.
On regarde pour corriger ce point.

Merci,
Wwark.

**Comment by gilles0606** [comment]
de rien.
Si cela peut aider 4 jours avant la disparition du contenus.
le contenus étais dans le listing, mais il n'étais plus "playable", impossible de lire...

**Comment by wwark** [comment]
Ok je pense que c'était lié au problème de lire les vidéos hebergées par dailymotion.
Il y a eu un fix dans le framework Codequick que nous utilisons dans le plugin.
https://github.com/willforde/script.module.codequick/commit/dafcdeb0c181085cb6cbc00e1a4966041eca0fd2

Le framework a été mis à jour en version 0.9.8.

Il reste donc à corriger le listing !

**Comment by wwark** [comment]
Replay ok avec la version 0.2.5~beta08.

**Comment by wwark** [comment]
Fixé et suppression de la dépendance beautifulsoup

**Comment by gilles0606** [comment]
Hello,

je confirme tout remarche  ;-)

Super

MERCI
