### ISSUE TITLE
Le replay d'Arte ne fonctionne pas

### ISSUE THREAD

**Issue by bigboo3000** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#156]
Bonjour,
impossible d'accéder aux emissions d'Arte en replay

**Comment by wwark** [comment]
Bonjour @bigboo3000 
un correctif est disponible sur la version 0.2.5 beta pour Arte. Vous pouvez l'installer via le répository beta.
Ce correctif sera présent dans la prochaine release.

Merci,
Wwark.

**Comment by wwark** [comment]
Release 0.2.5 disponible je ferme ce ticket.

**Comment by bigboo3000** [comment]
Bonjour je viens d'essayer la nouvelle version et le replay d'Arte marche toujours pas, j'utilise Coreelec 9.01.

**Comment by wwark** [comment]
Bonsoir @bigboo3000,

Quelle est votre version installée? Est-ce bien la version 0.2.5?
Voici un tutoriel pour l'installer si ce n'est pas le cas :https://catch-up-tv-and-more.github.io/fr/installation/
Si vous êtes en version 0.2.5, pouvez-vous nous indiquer la video remontant une erreur ainsi que le log associé?

Merci,
Wwark

**Comment by bigboo3000** [comment]
Bonsoir désolé je n'avais pas vu toute cette procédure à faire pour obtenir la dernière version, j'utilise la version très ancienne du dépot officiel Kodi. Je vais donc suivre le tutoriel et je cloture le bug.

**Comment by wwark** [comment]
La version sur le dépôt officiel est très ancienne.
Nous avons poussé depuis quelques mois la version 0.2.0 du plugin mais elle n'a pas été encore accepté...
Tenez nous au courant si vous avez le moindre souci avec la procédure.

Merci,
Wwark

**Comment by bigboo3000** [comment]
Bonjour,
Je vous confirme que cela fonctionne maintenant!

Pour des suggestions de fonctionnalités puis_je les faire sur ce github en créant une issue ou  dois-je utiliser un autre moyen?

**Comment by wwark** [comment]
Bonjour,

Bonne nouvelle !
Oui le github est dédié pour remonté les issues et faire des requêtes d'ajout de contenus ou d'amélioration du plugin.
N'hesitez pas aussi à proposer des PR (pull request) !

Merci,
Wwark.
