### ISSUE TITLE
Live TV for French channels is not working...

### ISSUE THREAD

**Issue by funtravel1208** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#157]
Hello,

The Live TV French channels are not working anymore... The message errors "RunTime Error - Unable to resolve url" (TF1) or "Playback failed "One or more items failed to play. Check the log for more information about this message" (France 2, France 5) or nothing happens (France 3)... 
Hope you will be able to fix it quickly.

Thanks,

**Comment by wwark** [comment]
Hi @funtravel1208,

What is the version of the plugin you used?
Can you please share debug log of some tests you have issues?

Thanks for your return,
Wwark

**Comment by funtravel1208** [comment]
Hello Wwark,

Would you mind to let me know where I can find the version of the plugin and how to get the debug log?

Thanks!

Christine

**Comment by wwark** [comment]
Debug log : https://kodi.wiki/view/Log_file/Advanced#GUI_settings
Where to find log : https://kodi.wiki/view/Log_file/Advanced#Log_files

For the version of the plugin you can find it on the information of the add-on

**Comment by funtravel1208** [comment]
Hi Wwark,

 

It looks like the version is 0.2.5-beta07.

I did another way for the logs (see attached files). Hope that works for you.

 

 

 

 

 

Christine Lascols

**Comment by funtravel1208** [comment]
![TF1_DebugLog](https://user-images.githubusercontent.com/37758866/54492164-6c42ee80-489a-11e9-8704-f49a8901109a.jpg)
![France2_DebugLog1](https://user-images.githubusercontent.com/37758866/54492169-7ebd2800-489a-11e9-9859-b61137c4a83f.jpg)
![France2_DebugLog2](https://user-images.githubusercontent.com/37758866/54492170-8250af00-489a-11e9-86e8-d3f09a0133df.jpg)

**Comment by wwark** [comment]
The error is HTTP 403 (not authorized)
Do you use a french IP?

Thanks,
Wwark

**Comment by funtravel1208** [comment]
I usually do but it got disconnected. It's working again now... Thanks for your help!

**Comment by wwark** [comment]
good

**Comment by funtravel1208** [comment]
Unfortunately, we need to reopen this ticket. The France Televisions channels are still not working... however TF1 is fine. Have you heard of any current issue with France Televisions (France 2, 3, 5...etc)?
Please find below the logs for this issue
![France2_DebugLog1](https://user-images.githubusercontent.com/37758866/54526480-46c2ed00-494d-11e9-8697-5d4fc5d8b8bd.jpg)
![France2_DebugLog2](https://user-images.githubusercontent.com/37758866/54526487-4aef0a80-494d-11e9-976a-c56637dc37c1.jpg)
