### ISSUE TITLE
Live France Televisions channels are not working...

### ISSUE THREAD

**Issue by funtravel1208** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#158]
Unfortunately, we need to reopen this ticket #157 . The France Televisions channels are still not working... however TF1 is fine. Have you heard of any current issue with France Televisions (France 2, 3, 5...etc)?
Please find below the logs for this issue
![France2_DebugLog1](https://user-images.githubusercontent.com/37758866/54526559-8689d480-494d-11e9-819a-9f85374f9f7d.jpg)
![France2_DebugLog2](https://user-images.githubusercontent.com/37758866/54526563-8ab5f200-494d-11e9-8122-fc1ce5564d51.jpg)

**Comment by wwark** [comment]
Hi @funtravel1208,

The error are still the same HTTP 403.

If I understand correctly you use a VPN. So the IP is delivered by the VPN service.
Some websites have the ability to know if you use a IP provided by a VPN service, they can block this type of IP. 
The list of IP (delivered by VPN service) are well known and available freely.

If you use the same connection (VPN) are you able to play live tv directly in the website of France Télévision? If it is not the case we can't do anything for that ....

To be able to play without any issue, you need to be in France. The VPN can help to access some content but some issues can occured.

Thanks,
Wwark.

**Comment by funtravel1208** [comment]
OK, I am not sure if it was a channel blocking me or a VPN provider issue but I tried another VPN provider and it's working again.
Thanks for your help!

**Comment by wwark** [comment]
Ok. Thank you Wwark
