### ISSUE TITLE
Live TV Folder is not opening...

### ISSUE THREAD

**Issue by funtravel1208** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#164]
Hello,
For some reason, the Live TV folder cannot open anymore, and there is no error message. Nothing is happening.
Has anyone experienced this? Is there any known issue with Live TV right now?

**Comment by wwark** [comment]
Hello @funtravel1208,

Do you still have the issue ?
Can you please provide the debug log if the issue is still present?

Thank you,
Wwark

**Comment by funtravel1208** [comment]
Hi Wwark,

This is strange. It’s still doing it but the debug log is empty.
Thanks,

Christine

**Comment by wwark** [comment]
yes very strange. Normally you will have log.
Can you please set "debug log"? Stop and start again kodi try to reach the live tv and share the file kodi.log (full log - all the file).
Is is possible to make some screenshots also?
With the last release 0.2.5? we proposed a new way to play live tv, you can try it with this documentation https://catch-up-tv-and-more.github.io/live_tv_installation/ .

Thank you,
Wwark.

**Comment by funtravel1208** [comment]
Hi Marc,

I can’t figure it out!
I am installing PVR TV but can’t find the m3u files. I am using Amazon fire. Would you mind to help me out ?

Thanks!

Christine

**Comment by wwark** [comment]
Hi @funtravel1208,

We had a new update in the documentation related to the path of the m3u.
A person gives us an information related to Shield Android TV maybe it is the same path for Amazon Fire.
The path for the shield is "/internal/Android/data/org.xbmc.kodi/files/.kodi/addons"

Thanks,
Wwark.

**Comment by funtravel1208** [comment]
Hi Wwark,

Thanks for those details. It was very helpful as the path is very similar.
Here is the path for Amazon Fire:
« External storage/Android/Data/
org.xbmc.kodi/files/.kodi/addons »

It’s working great now! 

Thanks for your help!

Christine

**Comment by wwark** [comment]
Hi @funtravel1208,

Thank you for return.
We will add this path in the documentation.

Wwark

**Comment by funtravel1208** [comment]
Hi Marc,

I am trying to install PVR TV on my Mac but can’t find the m3u file. I am following the path up to resources but there is no m3u folder.
Files and directories are not hidden.

Please let me know if you can fix this issue.
Thanks!

Christine

**Comment by wwark** [comment]
HI @funtravel1208 
Sorry I don't have a mac. @SylvainCecchetto can you help?
Just to confirm you have installed the version 0.2.5 or above
Before the m3u files don't exist.

Thanks,
Wwark.

**Comment by wwark** [comment]
Ticket fermé - corrigé
