### ISSUE TITLE
[enhancement] when only one country folder is available 

### ISSUE THREAD

**Issue by sancelot** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#165]
When only one country has been setted up in settings, when browsing tv or other things, instead of showing the country folder (since there is only one), present directly available folder content.

This is a user experience enhancement for quicker access to content

**Comment by wwark** [comment]
Hi @sancelot 

We put it in the TODO.
I think it is will be a good experience enhancement ! Thank you for the report.

**Comment by SylvainCecchetto** [comment]
This feature was available in the past when we used SimplePlugin framework.
I can have a look ;-)

**Comment by SylvainCecchetto** [comment]
This commit https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/1ee775610ecc2c1a830624336ef283545c31d2f2 should do the trick, @wwark, can you test on your side to be sure that I do not break anything?
Thank you!

**Comment by wwark** [comment]
My first test is OK :+1: 
I will continue if I find something I will let you know.
Thanks !

**Comment by wwark** [comment]
Hi,
I found something if a country have juste one channel like Tunisia for exemple.
The plugins go directly to next step and don't show the icon of the channel. What do you think ?

**Comment by wwark** [comment]
0.2.6 is release
