### ISSUE TITLE
Erreur "List Index out of range" pour le replay de RTL-TVI (Belgique)

### ISSUE THREAD

**Issue by nazca974** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#167]
Bonjour,

Bravo pour cet extension.
J'essaye de visionner les replay de RTL-TVI (Belgique) mais une une erreur "List Index out of range" apparait.
---------------------
log :

    09:46:03.559 T:16248   FATAL: [Catch-up-TV-&-More.support] list index out of range
                                                Traceback (most recent call last):
                                                  File "C:\Users\XXX\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 282, in run_callback
                                                    results = route.function(parent_ins, **self.callback_params)
                                                  File "C:\Users\XXX\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\channels\be\rtlplaybe.py", line 401, in get_video_url
                                                    ).findall(resp.text)[0]
                                                IndexError: list index out of range
    09:46:03.559 T:16248 WARNING: ###### debug ######
    09:46:03.559 T:16248 WARNING: [Catch-up-TV-&-More.support] Dispatching to route: '/resources/lib/channels/be/rtlplaybe/get_video_url/'
    09:46:03.559 T:16248 WARNING: [Catch-up-TV-&-More.support] Callback parameters: '{'item_id': u'rtl_tvi', 'item_dict': {u'info': {u'duration': 1302, u'plot': u"La strat\xe9gie de Gary pour conqu\xe9rir Prune a des cons\xe9quences inesp\xe9r\xe9es, alors qu'Arthur d\xe9couvre une v\xe9rit\xe9 qui l'affecte \xe9norm\xe9ment. Quant \xe0 Eve, elle \xe9choue \xe0 trouver de l'argent.", 'title': u'Episode 169'}, u'art': {u'fanart': u'https://images.6play.fr/v1/images/2190039/raw', u'thumb': u'https://images.6play.fr/v1/images/2190039/raw'}, u'stream': {}, u'label': u'Episode 169', u'params': <class 'codequick.listing.Params'>({'item_id': u'rtl_tvi', '_title_': u'Episode 169', 'video_id': u'clip_12338807', 'item_dict': {...}}), u'context': {}, u'property': <class 'codequick.listing.Property'>({})}, 'video_id': u'clip_12338807'}'
    09:46:03.559 T:16248 WARNING: [urlquick] Requesting resource: https://pc.middleware.6play.fr/6play/v2/platforms/m6group_web/services/rtlbe_rtl_play/videos/clip_12338807?csa=6&with=clips%2Cfreemiumpacks
    09:46:03.559 T:16248 WARNING: [urlquick] Request headers: {u'Accept-language': u'en-gb,en-us,en', u'Accept-Encoding': u'gzip, deflate', u'Connection': u'keep-alive', u'Accept': u'*/*', u'User-Agent': u'<function get_random_ua at 0x00000238782670B8>', u'Host': u'pc.middleware.6play.fr', u'x-customer-name': u'rtlbe'}
    09:46:03.559 T:16248 WARNING: [urlquick] Attempting to decode with default encoding: 'utf8'
    09:46:03.559 T:16248 WARNING: [urlquick] Requesting resource: https://www.rtlplay.be/connexion
    09:46:03.559 T:16248 WARNING: [urlquick] Request headers: {u'Host': u'www.rtlplay.be', u'Accept-language': u'en-gb,en-us,en', u'Connection': u'keep-alive', u'Accept': u'*/*', u'Accept-Encoding': u'gzip, deflate'}
    09:46:03.559 T:16248 WARNING: [urlquick] Caching 200 OK response
    09:46:03.559 T:16248 WARNING: [urlquick] Requesting resource: https://www.rtlplay.be/client-ca48c70543.bundle.js
    09:46:03.559 T:16248 WARNING: [urlquick] Request headers: {u'Host': u'www.rtlplay.be', u'Accept-language': u'en-gb,en-us,en', u'Connection': u'keep-alive', u'Accept': u'*/*', u'Accept-Encoding': u'gzip, deflate'}
    09:46:03.559 T:16248 WARNING: [urlquick] Caching 200 OK response
    09:46:03.559 T:16248 WARNING: [urlquick] Attempting to decode with default encoding: 'utf8'
    09:46:03.559 T:16248 WARNING: ###### debug ######
    09:46:03.593 T:16248 WARNING: CPythonInvoker(20, C:\Users\XXX\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\addon.py): the python script "C:\Users\XXX\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\addon.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcgui::ListItem
    09:46:03.623 T:8988   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.catchuptvandmore/resources/lib/channels/be/rtlplaybe/get_video_url/?_pickle_=80027d71002855076974656d5f69647101580700000072746c5f747669710255075f7469746c655f7103580b000000457069736f64652031363971045508766964656f5f69647105580d000000636c69705f3132333338383037710655096974656d5f6469637471077d7108285804000000696e666f71097d710a2858080000006475726174696f6e710b4d16055804000000706c6f74710c58c30000004c61207374726174c3a9676965206465204761727920706f757220636f6e7175c3a9726972205072756e6520612064657320636f6e73c3a97175656e63657320696e657370c3a972c3a965732c20616c6f7273207175274172746875722064c3a9636f7576726520756e652076c3a9726974c3a920717569206c276166666563746520c3a96e6f726dc3a96d656e742e205175616e7420c3a0204576652c20656c6c6520c3a963686f756520c3a02074726f75766572206465206c27617267656e742e710d55057469746c65710e580b000000457069736f646520313639710f75580300000061727471107d711128580600000066616e6172747112582d00000068747470733a2f2f696d616765732e36706c61792e66722f76312f696d616765732f323139303033392f726177711358050000007468756d627114582d00000068747470733a2f2f696d616765732e36706c61792e66722f76312f696d616765732f323139303033392f726177711575580600000073747265616d71167d711758050000006c6162656c7118580b000000457069736f64652031363971195806000000706172616d73711a63636f6465717569636b2e6c697374696e670a506172616d730a711b2981711c7d711d55087261775f64696374711e680073625807000000636f6e74657874711f7d7120580800000070726f7065727479712163636f6465717569636b2e6c697374696e670a50726f70657274790a7122298171237d712428681e7d712555095f6c6973746974656d71266378626d636775690a4c6973744974656d0a712729817128756275752e
-----------------

J'utilise un VPN avec une adresse IP Belge.
Par avance merci.

**Comment by wwark** [comment]
Bonjour @nazca974,

Merci pour l'alerte.
Nous avons fixé les live TV de RTLPlay be il y a quelques jours et les replays aujourd'hui.
La version 0.2.6~beta10 qui sera disponible ce soir aura le correctif pour la partie replay.

Ces correctifs seront disponibles ensuite dans la version release mais pas encore de date pour celle-ci.

Merci,
Wwark

**Comment by nazca974** [comment]
Hello, merci beaucoup de votre réactivité.

**Comment by wwark** [comment]
0.2.6 est disponible.
