### ISSUE TITLE
Live TV Canada Tele Quebec - list index out of range

### ISSUE THREAD

**Issue by sonic1200** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#169]
The Live TV channel Tele Quebec is not working. Report an error : list index out of range

**Comment by wwark** [comment]
Hi @sonic1200,

Thank you for the report. The live TV is fixed and will be available in the next beta of the plugin 0.2.6~beta12 around 11pm (CET).

Thanks,
Wwark

**Comment by sonic1200** [comment]
Thanks.
It works perfectly with the latest beta version.
