### ISSUE TITLE
Ajout du compte RTL Play

### ISSUE THREAD

**Issue by scorpio686** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#172]
Salut :)

Merci pour la release, on me l'a faites découvrir récemment. J'ai un petit problème pour l'ajout du compte RTL Play dans kodi sur Nvidia Shield.

J'ai vu un message là dessus, mais je ne sais plus où, et là suite donnée à ce message.

Merci d'avance

**Comment by SylvainCecchetto** [comment]
Bonsoir Scorpio,

Pour l'ajout de ton login RTL Play tu dois simplement te rendre dans l'onglet "Comptes" des réglages du plugin ;-)

Nous restons dispo si besoin

**Comment by scorpio686** [comment]
Bonsoir Sylvain, merci pour la réponse très rapide :)

J'avais déjà chercher dans les paramètres, c'est le minimum avant de vous contacter :)

Mais dans les paramètres du compte, je peux seulement activer ou désactiver le compte pour la Belgique

https://i.imgur.com/ZjOMG3U.jpg

J'ai installé Kodi pour votre plugin, désolé si j'ai loupé un truc :)

**Comment by SylvainCecchetto** [comment]
Merci pour la photo, effectivement il y a un problème, on dirait que les règlages des différents onglets sont "mélangés".

Voilà ce que tu devrais avoir : https://i.imgur.com/pWCqPAy.png

Tu peux dans un premier temps essayer de réinitialiser les réglages "Par défaut" pour voir si cela règle le problème.

Par quelle méthode as tu installé le plugin ? En suivant notre tutoriel ? (https://catch-up-tv-and-more.github.io/fr/installation/)

**Comment by wwark** [comment]
Hello @scorpio686 et @SylvainCecchetto 

On a ce ticket qui a l'air de ressembler https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/134

Cette personne n'avait pas la dernière version du plugin.
Quelle est la version que vous utilisez?

Merci,
Wwark.

**Comment by scorpio686** [comment]
Coucou les gars, non en fait j'ai fais le con et j'étais parti sur l'installation via le fichier zip plugin.video.catchuptvandmore-0.1.10, du coup forcément... ça ne correspondait pas à la version actuelle, malgré les tentatives de mises à jours...

En suivant le tuto, ça résous évidemment le problème... :) ça m'apprendra à faire ça n'importe comment en plein milieu de la nuit...

Merci beaucoup les gars, pour le plugin et pour l'aide, et désolé du dérangement :)

**Comment by wwark** [comment]
Pas de soucis !
Je ferme donc ce ticket.
N'hésite pas à rouvrir un ticket si tu rencontres des erreurs.

Bonne journée,
Wwark
