### ISSUE TITLE
Question Integration JSON

### ISSUE THREAD

**Issue by annetube** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#173]
Bonjour, tout dabord un grand merci pour votre travail, je souhaiterai savoir s'il y est possible dexecuter ce plugin dans une console, j'ai teste la branche test mais les informations concerant les sites semblent aleatoires. 

Serait il possible de directement integrer un script permettant de retourner un json avec les liens et url corespondant au site en question. Car malheuresment, chacun fait ses propres extracteurs pour plus ou moins la meme finalite  (streamlink,youtube-dl,etc ...), le json permettrait d'uniformiser tout cela et deviter une redondance entre les projets, dans labsolu je souhaiterai integrer votre sript 6play dans youtube-dl (il manque le live), mais en plus de mes faibles conaissances en pyhton, je bloque face a lenvironement "kodi"

Merci et bravo ;)

**Comment by wwark** [comment]
Bonjour @annetube 
Merci pour votre interet pour cette extension de Kodi.

La branche test est utilisée pour tester automatiquement les différentes chaînes proposées par cette extension. On a un robot qui utilise cette branche et lance des tests tous les soirs et nous remonte les anomalies rencontrées.
Les informations visibles dans cette branche de test sont normalement identiques à ce que nous pouvons visualiser via l'extension dans Kodi.
Dans cette branche de test, nous pouvons lire le contenu extrait avec mpv pour lire la vidéo (direct tv ou replay)
Il y a cependant des limitations, nous ne pouvons pas lire les contenus protégés par DRM (mpv ne le supporte pas) et on n'a pas mis encore la partie authentification donc certains contenus ne sont pas accessibles.

Au sujet de votre demande du json, ces liens pourront ne plus fonctionner au bout d'un certain temps ou pas du tout. 
Je m'explique certains sont liés à une session http (requierant un cookie), certains sont liés à un token (validité dans le temps), certains sont protégés par DRM (requierant un lecteur gérant les DRM), etc ....

A ma connaissance, youtube-dl utilise mpv pour lire les vidéos et comme indiqué mpv ne gère pas les DRM. Les lives de 6play sont protégés par DRM (à part M6 Boutique, FunRadio et RTL2 qui proposent un lien non protégé par DRM). A l'heure actuelle, il faut donc passer par Kodi pour pouvoir lire ces live TV de M6, 6Ter et W9.

J'espère que j'ai pu répondre à vos questions.

Merci,
Wwark

**Comment by SylvainCecchetto** [comment]
Bonjour annetube,

Alors officiellement il n'est pas possible d'exécuter ce plugin dans une console car le code est fortement dépendant aux fonctions de l'API python proposé par Kodi (tu remarqueras les `import XBMC*` un peu partout).

Mais officieusement nous avons développé un "framework" de test afin d'exécuter le plugin directement depuis une console sans avoir à utiliser Kodi.
L'idée originale de ce framework était de pouvoir effectuer des tests plus ou moins automatique de plugin depuis un service d'intégration continue (nous avons tout juste commencé à utiliser Travis pour cela).
Le fonctionnement du framework est assez simple, en fait nous "mockons" les import XBMC ainsi que les fonction correspondante afin de simuler ce qu'aurait fait Kodi dans la vraie vie.
Pour avoir une idée du prototype des fonction Kodi c'est ici : https://github.com/romanvm/Kodistubs

Le principal avantage de ces mocks est de pouvoir tester le plugin sans en modifier la moindre ligne de code.

Le framework de test est présent ici : https://github.com/Catch-up-TV-and-More/catchuptvandmore-test par contre pas sûr que la doc soit à jour...

Avec wwark nous avions déjà évoqué l'idée de faire une séparation entre la partie scraping et la partie Kodi, ce qui permettrait effectivement de partager du code avec d'autres projets proposant des vidéos sur d'autres logiciels (applications iOS, adroid, Flex, ... whatever).

Je pense cependant à un point particulier mais wwark en parlera mieux que moi : les DRM, à voir pour ça !

En tout c'est question intéressante et à approfondir ;-)

Je reste dispo si besoin d'aide pour faire tourner le plugin sur la console.

Bonne journée !

**Comment by annetube** [comment]
Merci pour ces reponses completes, effectivement les liens expirent, il suffit alors de les "calculer" avant l'execution, ce que vous faites ou bien de les calculer en amont de maniere reguliere avant lexpiration, je me suis plonge dans votre code durant toute la journee pour essayer de comprendre comment vous arriviez a decoder les chaines du groupe NRJ et celle du groupe M6, pour NRJ c'est effectivement plutot simple et bien pense, cependant j'ai un probleme au niveau de la 2nd requete pour obtenir se logger et optenir une session permettant de recuperer l'url hls, je ne sais pas pour quoi mais mon curl ne semble pas fonctionner, en revanche en manuel (sans code), cela fonctionne , les liens sont semble t-il valable pour une semaine d'apres le timestamp... Juste pour confirmation cela fonctionne t-il toujours de votre cote car je nai pas kodi pour tester malheuresment et suis a l'etranger... 

En revanche pour M6, comme vous dites le contenu est protege, le HLS est illisible par FFPLAY et idem pour le mpd dash, ce que je comprends pas c'est apres avoir essayer d'interpreter votre code, il me semble que vous extrayez le JSON : https://pc.middleware.6play.fr/6play/v2/platforms/m6group_web/services/6play/live?channel=M6&with=service_display_images,nextdiffusion retournez l'url dash presentent : https://m6.live.6cloud.fr/out/u/m6_sd_p.mpd a Kodi, comment Kodi peut il alors decoder et lire ce lien ?

Merci pour votre retour et bonne journee a vous>


Desole pour les accents et fautes jutilise un qwerty australien ...

**Comment by wwark** [comment]
### Le principe de cette extension est la suivant.
Nous effectuons les même appels que peut faire un navigateur internet ou une application mobile.
Le but de ces appels et de pouvoir récupérer le lien video (certains requièrent des authentification (login/password), ...)
Quand nous avons récupérer ce lien vidéo. Il est transmit à Kodi sans le modifier. Kodi prend en charge ensuite la lecture. Mais on pourrait utiliser mpv ou vlc si on veut.
Ces flux vidéos sont de plusieurs type: m3u8, mp4, mpd, ....
Kodi est capable de prendre en charge tout ces types de vidéos.
Dans le cas du DRM, nous récupérons en plus sur le site web la licence DRM et nous la fournissons à Kodi via la librairie inputstream.adaptive. Ceci permet de lire les contenus protégés par DRM dans Kodi. (https://github.com/peak3d/inputstream.adaptive)

###  Les réponses à vos questions.
Nous ne modifions pas les liens vidéos récupérés. C'est-à-dire nous ne recalculons pas les token de temps. Je pense que ce n'est pas une bonne idée car le lien pourrait ne plus fonctionner ... 

Le direct TV de NRJ requiert une authentification (login/password). Pour cela nous crééons un session http qui est utilisé pour tous les appels jusqu'à l'obtention du lien vidéo. Le problème que vous devez rencontrer c'est que le session http doit être cassée. En python, vous pouvez utilisez la lib requests et créer une session ça devrait fonctionner.
Je n'ai jamais regardé combien de temps le lien était valable pour le cas de NRJ.

Kodi gère les DRM via la librairie inputstream.adaptive et il faut installer aussi la librairie wideline utilisé par les navigateur internet pour lire les contenus DRM.

Merci,
Wwark

**Comment by annetube** [comment]
Merci pour votre reponse,

Cela m'aide grandement,Je parviens  desormaisa recuperer tous les differents token et id pour m6, seulement je ne comprends pas les instructions concernant les DRM : 

> # URL_LICENCE_KEY = 'https://lic.drmtoday.com/license-proxy-widevine/cenc/|Content-Type=&User-Agent=Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3041.0 Safari/537.36&Host=lic.drmtoday.com&Origin=https://www.6play.fr&Referer=%s&x-dt-auth-token=%s|R{SSM}|JBlicense'
> URL_LICENCE_KEY = 'https://lic.drmtoday.com/license-proxy-widevine/cenc/|Content-Type=&User-Agent=Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3041.0 Safari/537.36&Host=lic.drmtoday.com&x-dt-auth-token=%s|R{SSM}|JBlicense'

avec 

```
                item.property[
                    'inputstream.adaptive.license_key'] = URL_LICENCE_KEY % token
```De ce que je comprends la chaine token est passe en parametre au niveau de %s de URL_LICENCE_KEY , mais comment cela se fait il que l'url est cette forme la ?

**Comment by wwark** [comment]
Cette url est de cette forme là pour être utitisé par inputstream.adaptive (lib of Kodi)
Tout est expliqué à cette url https://github.com/peak3d/inputstream.adaptive/wiki/Playing-multi-bitrate-stream-from-a-python-addon

Cette implémentation est pour fonctionner dans Kodi.

Wwark

**Comment by annetube** [comment]
Vraiment merci, je vais devoir malheuresement abandonner, je ne sais pas pourquoi , je reporduit les memes requetes HTTP vers drmtoday, que celles du navigateur (avec le nouveau token bien sur), mais je me retrouve avec un HTTP Status 412 – Precondition Failed, seul le payload contient quelques caracteres encodes, surement dans un base64 mais je ne sais a quoi cela correspond. Vraiment frustrant mais bon cest comme ca... En revanche pour nrj,cela foctionne plutot bien, le probleme etait que la connection n'etait pas maintenu de bout et qu'apres avoir utiliser une requete POST via curl, il fallait forcer la connection GET pour la derniere requete.
Bon dimanche et encore merci

**Comment by wwark** [comment]
Merci.
Je vais clore ce ticket
Wwark
