### ISSUE TITLE
Install Live TV on Raspberry ?

### ISSUE THREAD

**Issue by YannBrrd** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#174]
Hi,

When I try to install iptv on raspberry it misses a dependency 
```bash
kodi-pvr-iptvsimple : Depends: kodi-api-pvr (= 5.2.1)
```
Can this be solved  ? 

Thanks.

**Comment by wwark** [comment]
Hi @YannBrrd,

Which OS did you install on raspberry?
I think you need to ask the OS maintainer for this issue.

Thanks,
Wwark.

**Comment by YannBrrd** [comment]
Hi,

It's osmc install...

**Comment by wwark** [comment]
Maybe this post in the forum will help : https://discourse.osmc.tv/t/osmc-leia-18-on-rp3-no-pvr-iptv-simple-client-available/80161/2

**Comment by YannBrrd** [comment]
Oh! Feel stupid. 👍 Thanks
