### ISSUE TITLE
France 3 Régions

### ISSUE THREAD

**Issue by rican13** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#175]
Bonjour,
Est-ce que les liens vers les chaines régionales de France 3 sont publics ou privés ?
S'ils sont publics, auriez-vous l'amabilité de me communiquer le lien de la chaine régionale Provence-Alpes ?
Par avance, merci pour votre collaboration.
Cordialement.

**Comment by wwark** [comment]
Bonjour Rican13,

Tous les liens proposés sur cette extension sont publiques. Le plugin réplique le comportement d'un navigateur web. Si le contenu est accessible via le navigateur web, il est possible de l'ajouter dans cette extension.

Par rapport à votre question, les liens des chaines régionales de France 3 changent à chaque appel (token).

Les appels sont:

Récupérer ce json
http://france3-regions.francetvinfo.fr/webservices/mobile/live.json
id_sivideo = json_parser["provence-alpes"]["id_sivideo"].split('@')[0]
Récupérer l'id de la chaine provence-alpes

Appeler cette url
http://sivideo.webservices.francetelevisions.fr/tools/getInfosOeuvre/v2/?idDiffusion=%s
%s à remplacer par l'id de la chaine
Récupérer cette url dans le JSON
url = video['url']

Appeler avec l'url récupérer précédement (dans le %s) http://hdfauth.francetv.fr/esi/TA?format=json&url=%s
Récupérer le JSON
url finale = video['url']

L'url finale peut être lue. Elle est valable durant une certaine période.

Merci,
Wwark.


provence-alpes

**Comment by rican13** [comment]
Merci beaucoup,
Pour votre réponse rapide et précise !
Cordialement.
Ricardo

Le jeu. 16 mai 2019 à 11:35, Marc Roy <notifications@github.com<mailto:notifications@github.com>> a écrit :

Bonjour Rican13,

Tous les liens proposés sur cette extension sont publiques. Le plugin réplique le comportement d'un navigateur web. Si le contenu est accessible via le navigateur web, il est possible de l'ajouter dans cette extension.

Par rapport à votre question, les liens des chaines régionales de France 3 changent à chaque appel (token).

Les appels sont:

Récupérer ce json
http://france3-regions.francetvinfo.fr/webservices/mobile/live.json
id_sivideo = json_parser["provence-alpes"]["id_sivideo"].split('@')[0]
Récupérer l'id de la chaine provence-alpes

Appeler cette url
http://sivideo.webservices.francetelevisions.fr/tools/getInfosOeuvre/v2/?idDiffusion=%s
%s à remplacer par l'id de la chaine
Récupérer cette url dans le JSON
url = video['url']

Appeler avec l'url récupérer précédement (dans le %s) http://hdfauth.francetv.fr/esi/TA?format=json&url=%s
Récupérer le JSON
url finale = video['url']

L'url finale peut être lue. Elle est valable durant une certaine période.

Merci,
Wwark.

provence-alpes
