### ISSUE TITLE
Live TF1 Not Working - RuntimeError

### ISSUE THREAD

**Issue by RedBeardDev** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#176]
Bonjour,

Specs: 
Raspberry Pi 3
OS : OSMC 2019.04-1
Kodi : 18.2-RC1

Le live TF1 ne fonctionne plus depuis quelques semaines, 
Le message affiché au lancement est 'RuntimeError - Impossible de résoudre l'URL'.

Est-ce un problème connu ?
Si oui, quand pensez-vous pouvoir le résoudre ?

Merci encore et GG pour le travail accompli ! 👍

**Comment by SylvainCecchetto** [comment]
Bonjour RedBeardDev,

Merci pour le message ;-)

Quelle version du plugin utilises-tu ? Je viens de tester de mon coté, et je n'ai pas de problème avec le live TF1.

Si tu utilises la version proposée par défaut sur le repo Kodi, celle-ci n'est pas à jour et nous proposons la dernière version directement sur notre repo.
Je te propose de suivre ce tutoriel afin de l'obtenir : https://catch-up-tv-and-more.github.io/fr/installation/

Nous restons disponible ;-) Bonne journée

**Comment by wwark** [comment]
Bonsoir @RedBeardDev,

Tu pourrais me donner le retour de cette url via un navigateur depuis le même réseau que ton instance Kodi https://delivery.tf1.fr/mytf1-wrd/L_TF1?format=hls ?

Merci,
Wwark

**Comment by kdurand44** [comment]
Bonjour

J’ai installé l’extension depuis votre repo et la télé et les replays ne marchent pas ;(
Je suis sur Kodi 17.6 sur Recalbox...

Merciii

**Comment by wwark** [comment]
Bonjour @kdurand44,
Il n'est pas utile de commenter plusieurs tickets pour votre problème.
Quelle est déjà le retour si vous testez l'URL https://delivery.tf1.fr/mytf1-wrd/L_TF1?format=hls ?

Merci,
Wwark

**Comment by wwark** [comment]
Hello,

Je ferme ce ticket. @RedBeardDev n'hésite pas à le rouvrir si besoin.

Merci,
Wwark
