### ISSUE TITLE
Echec de lecture d’un ou plusieurs fichiers. Consulter le journal pour plus d’informations

### ISSUE THREAD

**Issue by Dan69320** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#178]
Bonjour

J'ai fait l'acquisition d'une ANDROID BOX HK1 Mini sous ANDROID 8.1.0

KODI 18.0 ALPHA1 était déjà installé et j'ai suivi le tuto pour installer « Catch-Up TV & More » ainsi que le guide TV.
Pour Catch-Up TV pas de souci ça fonctionne , je peux voir les chaines de télé.

Mais pour le “PVR IPTV Simple Client” ,  j’ai un message d’erreur au lancement des chaines : 
« Echec de lecture d’un ou plusieurs fichiers. Consulter le journal pour plus d’informations » 
A noter que je peux toujours visualiser la TV en passant par « Mes extensions/ Catch-up TV / TV en direct / France …etc … ) 

Ci-joint capture et log

Merci d’avance de votre aide précieuse 

Cordialement 

Daniel

![2019-05-21_11-20-01](https://user-images.githubusercontent.com/50884348/58164725-a8be0c80-7c86-11e9-9c6b-8b4a0103de3b.jpg)
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/3206740/kodi.log)

**Comment by wwark** [comment]
Bonjour Daniel,

Merci pour l'ouverture du ticket.
Je vais regarder tous ces éléments !

Wwark

**Comment by wwark** [comment]
J'ai identifié ce log:
08:43:41.596 T:18446744071700490608 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.catchuptvandmore/main/live_bridge/?item_id=france-2&item_module=resources.lib.channels.fr.francetv&item_dict={}
08:43:41.596 T:18446744071700490608   ERROR: CVideoPlayer::OpenInputStream - error opening [pvr://channels/tv/Toutes les chaînes/pvr.iptvsimple_2033015264.pvr]

Je pense que tu utilises une ancienne version de PVR iptv simple. (pvr.iptvsimple v3.3.1) et que le format du m3u fourni par l'addon ne fonctionne pas.
De mon côté j'ai la version 3.5.7 de PVR iptv simple.

Il faudrait voir pour migrer en version 18.2 de Kodi si ta box ANDROID BOX HK1 le permet.

Merci,
Wwark

**Comment by Dan69320** [comment]
Bonjour

1000 mercis 👍 tout fonctionne parfaitement avec la version 18.2 de Kodi
C'est top
Merci beaucoup pour le traitement rapide de ma requête et bravo pour le
travail que vous faites

Belle journée et excellent week-end

Cordialement

Daniel

_____________________________________________________________________________

**Comment by wwark** [comment]
Top ! 
Je ferme le ticket.
Bon weekend à toi aussi !

**Comment by jordanpires449** [comment]
kodi

**Comment by nenou123** [comment]
Salut je télécharge Codi 20 nexus avec catch-up tv Mai’s J’ai un problème sur catch-up tv Échec de lecture d'un ou plusieurs fichiers. Consulter le journal pour plus d'informations sur ce message.peut expliquer pourquoi ce error SVP
![E6BD7F33-2C8E-4F2E-A5D8-9A98000323B3](https://user-images.githubusercontent.com/122756457/213613374-74331511-e5c1-4658-9548-efeef14d54d1.jpeg)
![Uploading 60FFC1FB-C110-46C8-98DC-3118473B8693.jpeg…]()
