### ISSUE TITLE
RunTimeError

### ISSUE THREAD

**Issue by ReaperBe7062** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#179]
bonjour,
je viens d'installer Catch Up et impossible de lire TF1 j'ai une erreur impossible de resoudre le l'url et j'ai aussi des chaines belges qui me demandent des logins ...

savez vous m'aider ? merci

**Comment by wwark** [comment]
Bonjour @ReaperBe7062,

La pluspart des contenus sont géolocalisés. Il est fort probable que le direct TV de TF1 ne soit pas accessible depuis la belgique. Nous aurions besoin des logs en mode debug lors d'un test de lecture pour TF1.

Certains des contenus sont protégés par des logins dont certaines chaines belges. Il faut donc le créer auprès des sites web des chaines et les renseigner dans l'extension dans la partie configuration.
Dans la liste des chaines supportées par cette extension, il y a les url des chaines dans les cas où on doit créer un compte
https://catch-up-tv-and-more.github.io/channels/

Merci,
Wwark

**Comment by ReaperBe7062** [comment]
bonsoir @wwark 

Voici le log que j'ai de kodi :) 

merci a toi de ton aide 
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/3208909/kodi.log)

**Comment by wwark** [comment]
Tu pourrais me donner le retour de cette url via un navigateur depuis le même réseau que ton instance Kodi https://delivery.tf1.fr/mytf1-wrd/L_TF1?format=hls ?

Merci,
Wwark

**Comment by ReaperBe7062** [comment]
error | "Désolé, cette vidéo n'est pas accessible depuis votre zone géographique"
-- | --


tout simplement :(

**Comment by wwark** [comment]
Désolé sur ce point nous ne pouvons rien faire ...
J'espère avoir pu répondre à tes questions.

je ferme ce ticket n'hésite pas à le rouvrir si besoin.

Merci,
Wwark
