### ISSUE TITLE
[TF1] Add possibility to log in with MyTF1 account

### ISSUE THREAD

**Issue by SylvainCecchetto** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#18]
Add possibility to log in with MyTF1 account to be able to watching DRM movies like Grey Anatomy

(Test in progress)

**Comment by wwark** [comment]
- [ ] Add Account GROUPE TF1
- [ ] Add Account GROUPE M6
- [ ] Add Account NRJ12 / Cherie25

**Comment by ludoo0d0a** [comment]
With France 2 , it works well but with m6 and tf1, I got an "erreur de lecture".
Is the login/drm in cause for failure on all replay streams for these channels?

**Comment by ludoo0d0a** [comment]
I just saw the [french forum](https://forum.mpdb.tv/index.php/topic,35713.msg271496.html?PHPSESSID=781ad856ec089f1e1030e03b97d129c3#msg271496).
I confirm that only tvshows failed ; le quotidien (ex-petit journal) works.

I will try to test dev version.

**Comment by wwark** [comment]
DRM is playable with this plugin of test https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmoretestdrmkodi18
