### ISSUE TITLE
xmltv be guide issue : missing rtb auvio

### ISSUE THREAD

**Issue by eenbroleke** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#182]
hi, I created an issue related to ths xmltv depot : https://github.com/Catch-up-TV-and-More/xmltv/issues/1.
just in case it remains unnoticed there, i'm creating an issue here.

**Comment by wwark** [comment]
thanks for the ping.
I have answered directly to the other thread.

I close this one.
Wwark
