### ISSUE TITLE
TF1 replay not working

### ISSUE THREAD

**Issue by Youkier** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#185]
Bonjour,

Depuis peu quand j'essaie de lancer TF1 en replay j'ai l'erreur HTTPERROR 503 : Service Temporary unavailable.

Savez vous d'où ça peut venir ?
C'est la cas pour toutes les chaînes du groupe TF1 (uniquement)

Merci,

**Comment by wwark** [comment]
Bonjour @Youkier,

Merci pour l'alerte.
La nouvelle release 0.2.7 corrige ce problème.
Je ferme ce ticket. N'hésite pas à le rouvrir si tu as encore des erreurs.

Merci,
Wwark
