### ISSUE TITLE
TV en Direct C8

### ISSUE THREAD

**Issue by kaminsky9444** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#188]
Bonjour,

Tout d'abord, merci pour votre merveilleux travail. Malheureusement, je rencontre un problème avec la dernière version du plugin Catch up TV and More, et la dernière version de Kodi, en effet, il m'est impossible de lire une vidéo en direct sur la chaîne C8.

Version de InputStream Adaptive : 2.3.15.

Version de Catch-up TV & More : 0.2.8~beta01.

Version Kodi : 2:18.2-1~stretch.

Je tiens à préciser que je réside en France, j'ai donc une IP Française.

Suis-je le seul à avoir ce problème ?.

PS: Même problème constaté avec CNEWS.

En vous remerciant.

**Comment by kaminsky9444** [comment]
Ok, je pense avoir trouvé une solution, je vais essayer d'upgrade la version de InputStream Adaptative en version 2.3.21, je vous dirai quoi ce soir :).

**Comment by wwark** [comment]
Bonsoir @kaminsky9444,

Le live TV de C8 ou CNews n'utilise pas l'extension inputstream.adaptive.
Est-ce qu'il serait possible d'avoir l'erreur présente dans les logs de Kodi?

Merci,
Wwark.

**Comment by kaminsky9444** [comment]
Bonsoir, merci pour votre réponse @wwark, voici les logs : 

http://paste.debian.net/hidden/21652018/

En vous remerciant.

**Comment by wwark** [comment]
Le log n'indique pas la cause de l'erreur. Est-ce qu'il est possible d'arrêter Kodi, le relancer ensuite et activer les logs en mode debug effectuer un test et partager la log complète ?
Pour vérifier, quelle est la version de l'extension installée ? Avez-vous suivi la procédure d'installation https://catch-up-tv-and-more.github.io/fr/installation/ ?

Merci,
Wwark

**Comment by kaminsky9444** [comment]
Veuillez m'excuser @wwark, en effet le mode debug ne fut pas actif, c'est maintenant le cas, voici :

https://termbin.com/k7xx.

Oui, j'ai la version 0.2.8~beta01 de l'addon.

En vous remerciant.

**Comment by wwark** [comment]
Pouvez-vous suivre cette procédure?
https://catch-up-tv-and-more.github.io/fr/faq/#i-erreurs-li%C3%A9es-%C3%A0-youtube-dl

Les direct TV Cnews et C8 sont hébergés sur dailymotion.

Merci,
Wwark.

**Comment by kaminsky9444** [comment]
Ah ok très bien. C'est fait, voici ce que j'obtiens maintenant :

http://paste.debian.net/hidden/41ec3bdb/

En vous remerciant.

**Comment by kaminsky9444** [comment]
2019-06-11 22:00:34.768 T:1766114016   FATAL: [Catch-up-TV-&-More.support] No module named YDStreamExtractor

Je ne vois pas trop faire avec cette erreur :(.

**Comment by wwark** [comment]
Bonjour @kaminsky9444,

La procédure n'a pas été correctement suivie. Elle n'est pas simple. Il faut qu'on arrive à l'automatiser.
"/home/pi/.kodi/addons/script.module.youtube.dl/lib/youtube_dl" dans ce répertoire tu as quoi ?

C'est dans le repertoire que tu dois copier la nouveaux fichier de l'application youtube_dl comme détaillé dans la procédure.

J'espère que ça pourra t'aider,
Wwark

**Comment by kaminsky9444** [comment]
Salut,

En effet, je me suis planté, j'ai donc réinstallé l'addon youtube-dl, puis j'ai pu relire la procédure et la suivre, mais visiblement le problème persiste, voici les logs que j'obtiens maintenant :

https://termbin.com/f3cr.

Et :

pi@raspberrypi:~ $ ls /home/pi/.kodi/addons/script.module.youtube.dl/lib/youtube_dl/
aes.py   cache.py   compat.py   downloader  __init__.py   jsinterp.py   __main__.py  options.pyo    socks.py   swfinterp.py   update.py   utils.py   version.py   YoutubeDL.py
aes.pyo  cache.pyo  compat.pyo  extractor   __init__.pyo  jsinterp.pyo  options.py   postprocessor  socks.pyo  swfinterp.pyo  update.pyo  utils.pyo  version.pyo  YoutubeDL.pyo

Et désolé pour mon innatention.

**Comment by wwark** [comment]
Merci cette mise à jour.

Je pense que l'erreur posant problème est celle-ci qui se répète en boucle après que Kodi essaye de lire le flux video.
2019-06-12 12:42:12.564 T:1695539936 WARNING: CMMALVideo::GetPicture - ret(0) pics(0) inputs(0) slept(500) queued(-0.02) (0.44:0.46) full(0) flags(4000000) preroll(1) eos(0 2/-1)
2019-06-12 12:42:12.576 T:1596113632   ERROR: CMMALVideo::dec_control_port_cb Error (status=2 ENOSPC)
2019-06-12 12:42:12.679 T:1902175072   ERROR: Previous line repeats 5 times.
2019-06-12 12:42:12.679 T:1902175072    INFO: CheckIdle - Closing session to https://stream-15.dc3.dailymotion.com (easy=0x5dd3bf80, multi=0x70372668)

J'ai fait une recherche sur google.fr. 
Il y a un thread sur le forum officiel de Kodi pour ce problème (https://forum.kodi.tv/showthread.php?tid=258904)


> After googling "CMMALVideo::dec_control_port_cb Error (status=2 ENOSPC)" from the log I managed to get the file to play by disabling MMAL acceleration in Kodi.

> Not the right solution. Increase gpu_mem. 

> Fantastic! Increasing the gpu memory has fixed playback with MMAL acceleration enabled.
Thank you for the swift and decisive help. 

Il faudrait donc augmenter la gpu memory du RPI et voir si ça règle le problème.

Merci,
Wwark

**Comment by kaminsky9444** [comment]
merci à toi @wwark,

Alors, j'ai essayé en éditant le fichier /boot/config.txt, j'ai ajouté l'option :

gpu_mem=448 

Et bingo la vidéo se lance, mais malheureusement, la vidéo lag vraiment, c'est illisible, je doute que vous puissiez faire quelque chose :(.

**Comment by kaminsky9444** [comment]
Je ne vois pas trop quoi mettre comme valeur, en effet, gpu_mem=448 downgrade mon matériel. Et si j'augmente à 1380 (ayant déjà 1Go par défaut), bein mon PI 3B+ ne se lance plus.

**Comment by wwark** [comment]
Les Direct TV de mycanal sont en 1080p.

Est-ce que "MMAL acceleration dans les options videos de Kodi" est bien activée?

Quelle est la version du Rasberry PI ?
Durant mes déplacements j'utilise un RPI3 (anciennement) et un RPI3B+ (maintenant) et je n'ai pas de souci de saccade pour ces directs TV ou le problème avec LibreElec.

Dans les logs je vois que tu utilises un Raspbian. Il faudrait tester libreelec sur un autre carte SD pour voir si ça permet de pouvoir lire la vidéo. LibreElec propose un Kodi tuné pour les versions de Raspberry PI.

Dernier test, cette extension permet de changer la qualité du contenu vidéo si c'est proposé par la chaine. Il faut aller dans les options "Qualité et Contenus" -> Choisir Dialog.
Dans le cas de C8, au démarrage du direct TV il y a aura un popup demandant la qualité souhaitais.

Merci,
Wwark

**Comment by kaminsky9444** [comment]
Alors oui, j'avais bien activé l'accélération MMAL.

Je cherche dans les options Qualité et Contenus, mais je n'arrive pas à trouver où ça se trouve, pourrais-je avoir un screenshot de l'emplacement je te prie ?, en te remerciant.

Malheureusement, je n'ai aucun moyen de tester LibreElec dans l'immédiat, désolé.

**Comment by kaminsky9444** [comment]
Bonsoir,

Bon, j'étais en undervolt avec mon PI 3 B+, j'ai changé mon chargeur, et la vidéo passe parfaitement en 1080p sur C8, merci beaucoup pour ton aide @wwark.

**Comment by wwark** [comment]
Cool bonne nouvelle !
Je clos ce ticket
