### ISSUE TITLE
suggestion : avoir la liste de toutes les emissions d'une chaine classées par date

### ISSUE THREAD

**Issue by bigboo3000** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#194]
Bonjour,

Serait-il possible d'avoir un menu "dernières emissions" pour chaque chaine avec la liste de toutes les émissions de cette chaine classées par date, à la manière du menu par défaut de captvty?

![image](https://user-images.githubusercontent.com/16479698/59974813-9fd79800-95b0-11e9-9ca3-4cb88c51f2f6.png)

Cela éviterait une recherche par catégorie/émissions avec parfois beaucoup de sous-menu et de fait un peu fastidieuse.

**Comment by wwark** [comment]
Bonjour @bigboo3000,

Nous le proposons déjà pour les chaines le proposant (example France TV)

Cependant si le site ne permet pas d'avoir par ce classement, il faudrait rajouter des traitements supplémentaires (risque de bug, ...) qui serait pénalisant sur les petites configurations (RPI2, 3, ...)

Le fait de passer par les favoris ne serait pas une bonne solution dans ce cas pour les emissions qui t'interressent ?

De plus il est possible que des chaines le proposent mais qu'on est pas ajouter sur le plugin. C'est un point à rajouter bien sûr. 

Merci,
Wwark.

**Comment by SylvainCecchetto** [comment]
Je ferme cette issue pour inactivité.
Re-ouvrir si nécessaire ;-)
