### ISSUE TITLE
Replay et tv direct ne marchent pas

### ISSUE THREAD

**Issue by kdurand44** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#196]

**Comment by kdurand44** [comment]
Bonjour,
J'utilise catch tv sur Kodi Krypton 17.6 sur Recalbox,
Rien ne marche ;( une idée svp ?

**Comment by wwark** [comment]
Bonjour @kdurand44,

Avez-vous suivi cette procédure https://catch-up-tv-and-more.github.io/fr/installation/ pour installer ce plugin?

Si c'est les cas pouvez-vous nous envoyer les logs de kodi suite à un cas de test en erreur ?

Merci,
Wwak

**Comment by kdurand44** [comment]
Oui oui j’ai bien suivi la procédure... voici le log après l’échec de lecture d’un replay TF1...

**Comment by kdurand44** [comment]
Ou trouver l’url du log a vous envoyer ?

**Comment by wwark** [comment]
Bonjour @kdurand44,

Les logs kodi sont présents dans ce répertoire (diffère suivant les OS): https://kodi.wiki/view/Log_file/Easy#Copy_and_Paste
Il suffit de l'attacher en PJ à ton commentaire.

Quelle est la version installé de l'extension pour vérifier si l'installation est correcte?
Est-ce que vous avez une notification d'erreur lors du lancement du replay TF1? Si oui la quelle?

Merci,
Wwark.

**Comment by kdurand44** [comment]
Merci pour le retour,
Alors je navigue sans problème dans l’extension... la liste des chaînes et des replays s’affiche bien mais impossible de les lancer. Soit j’ai un message d’erreur « erreur de lecture d’un ou plusieurs fichiers... » soit rien du tout. Voici le log après avoir tenté de lancer des replays TF1 : https://paste.kodi.tv/mekasoyide  merci pour votre aide ;)

**Comment by kdurand44** [comment]
J’ai étonnamment le même problème sur l’extension Freplay...

**Comment by wwark** [comment]
Bonjour @kdurand44,
Kodi n'arrive pas à trouver des flux vidéos (peut être lié à la géolocalisation)

Est-ce qu'il serait possible de donner le retour de cette url https://delivery.tf1.fr/mytf1-wrd/L_TF1?format=hls  ?

Quelle est la version du plugin installé?

Pouvez-vous tester de lire le "Journal 20h" de France 2? Ce contenu n'est pas geolocalisé.

Merci,
Wwark.

**Comment by kdurand44** [comment]
Voici le retour que j’ai quand je tape l’URL 

{"code":200,"error":"","url":"https://tf1-hls-live-ssl.tf1.fr/tf1/1/hls/master_3000000.m3u8?e=1561815951&st=v-i7Lsljbrn0qVikqPTq7g","country":"FR","format":"hls"}

**Comment by kdurand44** [comment]
Le journal de 20h fonctionne parfaitement

**Comment by kdurand44** [comment]
Je suis sur la version 0.2.8 comment faire svp ?

**Comment by wwark** [comment]
Merci pour ces informations donc il y a des éléments qui fonctionnent :)
Pour le direct TV de TF1 n'est pas géolocalisé pour vous.
Il est possible que Kodi 17.6 n'arrive pas à lire les contenus de MyTF1 (Replay, Direct TV) si ce sont les contenus posant problème de votre côté. Est-ce que vous avez d'autres contenus posant problème?

Est-ce qu'il serait possible d'activer les logs en mode "Debug" et tester de lire le direct TV de TF1 et repartager les logs ?

Je vais essayer de prendre du temps ce week end pour tester aussi de mon côté.

Merci,
Wwark.

**Comment by kdurand44** [comment]
Je vais faire ça... quelle procédure dois je suivre pour le Debug et le partage des logs ?

**Comment by kdurand44** [comment]
Voici le log 

https://pastebin.com/uGauDZwV

**Comment by kdurand44** [comment]
J’ai donc essayé de lancer des replays puis le direct TF1

**Comment by wwark** [comment]
L'erreur est celle-ci et elle n'est pas lié au plugin mais au Kodi proposé dans Recalbox. On ne peut rien faire à notre niveau (mainteneur de Catchup TV & More)

Kodi utilise sa propre librairie FFMPEG pour lire les videos au format m3u8.
Les vidéos proposés par MyTF1 sont au format m3u8 via un appel en HTTPS.

FFMPEG compilé dans Recalbox ne permet pas de lire ces flux vidéos.

Il faut donc se rapprocher de la team Recalbox pour corriger ce point.
Tous les autres plugins utilisant des flux vidéos m3u8 en HTTPS poseront problème je pense.


Détail du log d'erreur:
**16:17:46.618 T:1694479328   DEBUG: ### ffmpeg[64FFB3E0]: https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.**
16:17:46.618 T:1694479328   DEBUG: **Error, could not open file** https://ios-q1-ssl.tf1.fr/2/USP-0x0/52/35/13645235/ssm/13645235.ism/13645235-audio_fra=128000-video=2502903.m3u8?e=1561817865&st=CHFMpDEwgj9DI0En1vJjEA
16:17:46.618 T:1694479328   ERROR: OpenDemuxStream - Error creating demuxer

Merci,
Wwark

**Comment by kdurand44** [comment]
Merci pour votre aide...

Il faudrait que j’utilise une autre version de Kodi du coup ? Sur une autre carte sd... ? Comment faire ?

**Comment by wwark** [comment]
Déjà demandé à Recalbox avec le log (en debug) pour voir s'ils peuvent corriger/modifier ou ils ont peut être d'autres versions de Recalbox avec FFMPEG compilé pour gérer le HTTPS.
Je n'ai jamais installé Recalbox mais peut être qu'il propose plusieurs versions.
Sinon installer une autre distribution comme libreelec par exemple, tu trouveras pleins de tutorial sur internet pour Libreelec.
