### ISSUE TITLE
Live TF1, FR2, FR3, FR5 ne fonctionne pas - RuntimeError

### ISSUE THREAD

**Issue by CrazyFox04** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#200]
# Erreur : Impossible de résoudre l'url
Bonjour,
Aujourd'hui, il m'est impossible de regarder les live des chaines : 
- TF1
- France 2
- France 3
- France 5
- Je pense que d'autre chaines ont le même problème

L'erreur m'étant reporté en tant que notification est la suivante : 
**RuntimeError**
Impossible de résoudre l'url

Voici le journal d'erreur : https://paste.kodi.tv/eqoyifexop
Info : 
- RaspberryPi 3B+ (RPI2.arm)
- LibreElec (official) 9.0.2
- Kodi 18.2
------------------------------------------------------------------------------------------

**Comment by wwark** [comment]
Hello @CrazyFox04,

Pourrais-tu nous donner le retour de cette url https://delivery.tf1.fr/mytf1-wrd/L_TF1?format=hls dans le même réseau que l'instance Kodi?
Une grande majorité des contenus vidéos sont géolocalisés.
Il faut avoir une IP française pour que ces flux vidéos fonctionnent correctement.

Merci,
Wwark.

**Comment by CrazyFox04** [comment]
Bonsoir @wwark,

Je viens de tester sur mon pc présent sur le même réseau que mon RP.
Voici les responses :
- Sans vpn
`{"code":403,"error":"Désolé,`` cette vidéo n'est pas accessible depuis votre zone géographique","url":"","country":"BE","format":"hls"}`
- Avec mon vpn  (BE -> FR)
`{"code":200,"error":"","url":"https://tf1-hls-live-ssl.tf1.fr/tf1/1/hls/master_3000000.m3u8?e=1564604850&st=bymur417wRGCGX2MjDgiqQ","country":"FR","format":"hls"}`

Je pense que mon vpn résout le problème...Je vais de suite tester.

Merci pour votre réponse rapide,
Crazy

**Comment by wwark** [comment]
De rien je ferme ce ticket !
Bon courage,
Wwark
