### ISSUE TITLE
Canal+ bloqué par drm

### ISSUE THREAD

**Issue by ddav33** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#202]
Bonjour impossible de voire quoi que se soit sur canal a cause des drm..

**Comment by wwark** [comment]
Bonjour @ddav33 ,

Nous avons déjà un ticket sur ce point https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/48

Nous arrivons à récupérer la clé de licence DRM de mycanal cependant le format n'est pas encore reconnu par la librairie de Kodi.
Il faut une évolution sur la librairie inputstream.adaptive (un ticket est ouvert de leur côté)

Merci,
Wwark

**Comment by wwark** [comment]
Je ferme cette issue suivi dans d'autre ticket (doublon)
