### ISSUE TITLE
widgets sous Catch up & More ne s'affichent

### ISSUE THREAD

**Issue by victore447** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#203]
Bonjour,
Avec le skin Eminence
(construction avec widgets et sous menus intégrer); les widgets sous addon Catch up & More ne s'affichent pas.
 De meme que avec les skin suivant:
Aeon nox,Amber,Embuary,Unity,Eminence,Fuse Neue etc..
Par contre Aucun problème avec le skin d'origine de kodi (Estuary).

**Comment by wwark** [comment]
Bonjour,
Je reouvre ce ticket.
Ou avez-vous vous avez trouvé une solution ?

Merci,
Wwark

**Comment by wwark** [comment]
+ andromeda (à valider)

**Comment by SylvainCecchetto** [comment]
C'est quoi exactement c'est "widgets" ? Je n'ai jamais utilisé ça je crois :-/

**Comment by victore447** [comment]
Bonjour,
Voici une video youtube de 5 minutes pour ce sujet en cliqaunt sur ce lien : https://www.youtube.com/watch?v=nv8FbLwUND4&t=109s
Pour plus d'infos dans la personnalisation de l'habillage de kodi avec des skins cliquer sur ce lien (s'abonné à la Chaine de peter Carcione) :
https://www.youtube.com/watch?v=ikTMpVza9vc&list=PL4IDggiGc-9jqhrxU0qbvU0ephmPrP5nI&index=23&t=0s

Et pour aller plus loin cliquer sur ces liens et s'abonné :
Liste des Skins compatibles avec Kodi 18
https://kodi.wiki/view/Skin_features_compatibility_list
Annuaire gratuit de kodiapps.com des plugins Videos (Tv,Films...)
https://kodiapps.com/addons-chart 
Annuaire Gratuit de kodi-addons.club des plugins Videos (Tv,Films..)
https://kodi-addons.club/?category=streaming&sort=newest&q=&page=1
                                                                                                                               
                                                                                                          Victor.e447

**Comment by victore447** [comment]
Bonjour, 
Teste de la derniere Version de catch-up via GitHub ce matin et tout fonctionne. 
Même les widgets avec le skin éminence pour la personnalisation de l'habillage dekodi  (pas le temps pour testé avec les autres skins).

**Comment by Psychoses** [comment]
Salut a tous,
Apres avoir eu quelques soucis avec les widgets et catch-up, j'ai fait quelques tests.
Tout mes tests on était fait sur le **skin embuary**.
J'en ai profité pour tester les favoris.

step 1)

j'en ai créer avec comme repertoire :

> ...
> replay
> france
> tf1
> series et fictions
> demain nous appartient

sur embuary quand vous creer le widget et que vous touché a rien dautres seul le dossier
"demain nous appartient" fonctionne. on clic sur une vidéo dans le widget ras ca se lance.

tous les autres dossiers ne fonctionne pas.

step 2)

on edite les widget et on selectionne un type. embuary propose :

> blank (a la creation seulement) => fail pour la plupart des dossiers
> images => ras
> musiques => ras
> vidéos => ras
> autres (qu'on devrait normalement séléctionner pour les dossiers ?) => fail pour la plupart des dossiers

donc pour moi le secret c'est de bien sélectionner dans les params du widget **"type : vidéos"** meme si c'est un dossier de catch-up.

niveau favoris, rien à signaler. on peut faire un widget des favoris de catch-up ca marche à merveille.

**du coup bravo tout fonctionne à merveille, chapeau.**

**Comment by SylvainCecchetto** [comment]
Hello tout le monde, merci pour les infos, je ne connaissais pas du tout ce système de Widget !

Du j'ai testé avec embuary, et effectivement ça fonctionne en sélectionnant comme type du Widget : Vidéos. Merci Psychoses pour le guide step-by-step.

J'avoue ne pas avoir poussé plus loins les investigations.

Je ferme ce ticket, si besoin ne pas hésiter à le réouvrir à tout moment !
