### ISSUE TITLE
Guide TV Belgique

### ISSUE THREAD

**Issue by Gaet81** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#205]
Hello,

il semble que le tv-programme.net ne propose plus d'API et donc lorsque dans les options on a le guide tv activé et qu'on essaie d'accéder au directe belge on obtient une erreur 404...

Désactivé le guide tv dans les options résouds le problème...mais hélas on ne peut pas le désactiver que pour la belgique

**Comment by wwark** [comment]
Hello @Gaet81,
J'ai désactivé dans le code.
Le fix sera présent dans la prochaine betâ on devrait préparer une release demain ou début de semaine.

Merci,
Wwark

**Comment by wwark** [comment]
La release 0.2.10 est disponible.
Je laisse ouvert ce ticket pour corriger le Guide TV Belgique (au moins sur la partie Kodi Mode TV à voir dans le plugin)

**Comment by SylvainCecchetto** [comment]
Hello @wwark,
ça me fait penser qu'on utilise parallèlement 2 sources différentes pour les guides TV :
* API pour les guides des live TV "dans" le plugin
* les XMLTV pour les live TV "kodi built-in" via ITV SimpleClient

A voir si c'est possible de supprimer l'utilisation des API pour le premier point avec un truc du genre :
1. Téléchargement du XMLTV en background depuis https://github.com/Catch-up-TV-and-More/xmltv
2. Récupération des infos des programmes depuis les XMLTV en local

A voir si c'est c'est pas trop couteux en temps d'abandonner les API et aussi si le téléchargement du XMLTV en arrière plan ne pose pas trop de problème...

**Comment by wwark** [comment]
ça serait top !
Merc.

**Comment by SylvainCecchetto** [comment]
Hello tout le monde, le commit https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/23269dea9a7f6ef82119ed30b91cf90a24936f8c permet de retrouver le Guide TV pour la Belgique, mais pour l'instant peu de chaines sont supportées.
Je vais essayer d'en ajouter un peu plus d'ici quelques temps.

Je ferme ce ticket. Ne pas éviter à l'ouvrir de nouveau si besoin ;-)
