### ISSUE TITLE
download  always starting download 0% 

### ISSUE THREAD

**Issue by greatAznur** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#208]
hi   if i donwload  a replay   catcg up lunch  ffmpeg and the donwload always at starting download 0% 
I wait a while and after time following the serie episode is download
but  no progression statut

**Comment by greatAznur** [comment]
oups  je la refait en français   quand je  vais faire un enregistrement d'un replay   ffmpeg et lancer  et tout fonctionne mais   en permanence on vois marqué starting download 0% donc on ne sais pas ou le Téléchargement en est   et après un certain temps je le voie apparaître la ou je le demande

**Comment by wwark** [comment]
Hello,
Ce comportement est normal. Il faut attendre et tu auras un popup indiquant que le téléchargement est terminé. C'est un comportement pour quelques type video. les videos hergégés par youtube par exemple on n'a pas le problème.

Merci,
Wwark.

**Comment by greatAznur** [comment]
ah ok  merci du renseignement

**Comment by wwark** [comment]
Suite à la réponse je ferme ce ticket.

@greatAznur n'hésite pas le rouvrir si besoin.

Merci,
Wwark
