### ISSUE TITLE
Live TV - NRJ 12 (fix)

### ISSUE THREAD

**Issue by Psychoses** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#209]
hi,

i have the v0.2.10

nrj12 Live TV is broken

change
``
URL_COMPTE_LOGIN = URL_ROOT + '/compte/login'
``
for
``
URL_COMPTE_LOGIN = URL_ROOT + '/compte/connexion'
``

seems do the job

;)

**Comment by wwark** [comment]
HI,
Thank you !
it is fixed and will be available in the next 0.2.11~beta01.
Regards,
