### ISSUE TITLE
favourites storage and thumb improvement

### ISSUE THREAD

**Issue by Psychoses** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#210]
favourites storage and thumb improvement

j'ai voulu éditer les favoris de catch-up a la main pour modifier certains thumb.
ca à l'air d'etre stocker dans un fichier "favourites.pickle"

qui n'a pas l'air facilement modifiable.

j'ai donc trouver deux workarround dans favourites.py

apres avoir demander le label
demander le thumb

```
...
    label_proposal = item_dict['label']
    if prefix != '':
        label_proposal = prefix + ' - ' + label_proposal

    # Ask the user to edit the label
    item_dict['label'] = utils.keyboard(
        plugin.localize(LABELS['Favorite name']), label_proposal)

    # new code start
    thumb_proposal = ''
    if 'art' in item_dict:
        if 'thumb' in item_dict['art']:
            thumb_proposal = item_dict['art']["thumb"]

    # Ask the user to edit the thumb
    item_dict['art']["thumb"] = utils.keyboard(
        plugin.localize(LABELS['Favorite name']), thumb_proposal)
    # new code end

    # If user aborded do not add this item to favourite
    if item_dict['label'] == '':
        return False

    # new code start
    if item_dict['art']["thumb"] == '':
        del item_dict['art']["thumb"]
    # new code end

    # Add this item to favourite db
    with storage.PersistentDict("favourites.pickle") as db:
...
```

quand le bouton renommer est presser
demander le label
demander le thumb

changer le bouton "rename" for "edit" ?

```
@Script.register
def rename_favourite_item(plugin, item_hash):
    """
    Callback function called when the user click
    on 'rename' from a favourite item
    context menu
    """
    item_label = utils.keyboard(plugin.localize(LABELS['Favorite name']),
                                xbmc.getInfoLabel('ListItem.Label'))
    item_thumb  = utils.keyboard(plugin.localize(LABELS['Favorite name']),
                                xbmc.getInfoLabel('ListItem.Thumb'))

    if item_label == '':
        return False
    with storage.PersistentDict("favourites.pickle") as db:
        db[item_hash]['label'] = item_label
        if item_thumb == '':
            del db[item_hash]['art']["thumb"]
        else:
            db[item_hash]['art']["thumb"] = item_thumb
    xbmc.executebuiltin('XBMC.Container.Refresh()')

```

![shot](https://user-images.githubusercontent.com/11153449/63128512-64a48480-bfb5-11e9-964d-4dffe4292721.png)

mais comme c'est fastidieux de tapé tout cela dans kodi...

il y aurais la posibilité de store les favoris autrement ? dans un xml ?

**Comment by SylvainCecchetto** [comment]
Bonjour Psychoses,
Si je comprends bien tu souhaiterais améliorer la fonctionnalité des favoris en offrant la possibilité d'éditer les favoris déjà existants c'est ça ?

A l'heure actuelle on peut déjà modifier le nom du favoris, mais tu souhaiterais pouvoir modifier le logo c'est ça ?

**Comment by Psychoses** [comment]
Bonjour @SylvainCecchetto
Parfait pour le #214 

> A l'heure actuelle on peut déjà modifier le nom du favoris, mais tu souhaiterais pouvoir modifier le logo c'est ça ?

```
    custom_item['info']['title'] = 'Zone interdite'
    custom_item['info']['plot'] = "Magazine d'actualit\xe9, Zone Interdite se compose de divers reportages et de plateaux o\xf9 sont accueillis des invit\xe9s ayant un rapport direct avec les th\xe8mes abord\xe9s dans les reportages."
    custom_item['art']['thumb'] = 'https://fusion.molotov.tv/arts/m2/446x588/Ch8SHQoUgEEpFbyHYxwjS7Lw91iS7veLLScSA2pwZxgB/jpg'
    custom_item['art']['fanart'] = 'https://images.6play.fr/v1/images/1794877/raw'
```
Je voudrai pouvoir modifier title, plot, thumb et fanart (titre, résumé, logo, background). En effet pour le titre c'est deja fesable avec le gui.
Et vu mon nombre de favoris, le faire via le gui m'interesse peu, j'aimerai avoir la possibilité de modifier un fichier regroupant l'ensemble des favoris. Comme par exemple le fichier "favourites.xml" de Kodi. Un fichier que j'ouvre avec un éditeur quelconque et ou je peux modifier les valeurs qui m'interessent.

**Comment by SylvainCecchetto** [comment]
Hum ok je comprends bien ton usage !
Il doit y avoir moyen qu'on utilise un XML pour stocker les favoris à la place du pickle. ça ne devrait pas trop impacter les performances ;-)
Je note ça et j'essaie de faire ça rapidement ;-)

**Comment by SylvainCecchetto** [comment]
Hello tout le monde,
Je viens de merger le PR https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/253, les favoris "version JSON" seront alors disponible pour tous à partir de la version 0.2.17~beta04.

Je ferme cette issue qui ne concerne que "l'improvement" mais ne pas hésiter à ouvrir une nouvelle issue si quelque chose tourne mal avec les nouvelles modifs.

Merci encore pour les tests et l'idée Psychoses, issue ouverte depuis déjà le 15 Aout mais tout arrive un jour, (et en plus c'est bientôt Noel :-P)

**Comment by Psychoses** [comment]
merci et joyeuse fete ! ;)
