### ISSUE TITLE
Canal 10 - Direct TV non disponible sur le site web - a vérifier.

### ISSUE THREAD

**Issue by wwark** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#211]

**Comment by SylvainCecchetto** [comment]
Je ne vois rien concernant le direct ici http://www.canal10-tv.com :-/

**Comment by wwark** [comment]
Le direct TV de Canal 10 supprimé du plugin.
On regarde pour mettre les replays.
Ticket fermé.
