### ISSUE TITLE
AttributeError: 'module' object has no attribute 'send_notification'

### ISSUE THREAD

**Issue by acolombier** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#217]
Bonsoir,

J’essaye de configurer OpenVPN, mais j'obtiens cette erreur:
```
2019-09-07 21:51:37.241 T:2086417264   FATAL: [Catch-up-TV-&-More.support] 'module' object has no attribute 'send_notification'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 292, in run_callback
                                                results = route.function(parent_ins, **self.callback_params)
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/vpn.py", line 260, in vpn_item_callback
                                                connect_openvpn(ovpn)
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/vpn.py", line 89, in connect_openvpn
                                                utils.send_notification(Script.localize(
                                            AttributeError: 'module' object has no attribute 'send_notification'

```

Après avoir regarde rapidement dans `codequick`, je ne trouve effectivement pas de fonction `send_notification` dans le package `utils`.

Aussi, je me demandais, est-ce que le VPN est connecté automatiquement lors du démarrage d'une chaîne ?

Merci

**Comment by algouye2802** [comment]
Hello,

Assez novice dans le domaine, mais j ai eu le meme souci. Aussi j'ai modifié le script vpn.py afin de toujours obtenir la notification dans kodi, et ne plus d'avoir d'erreur..
(evidement ne pas copier and coller les numeros de lignes :) )
[Kodi's User]/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/vpn.py

 line 89           utils.send_notification(Script.localize(
 line 90               LABELS['Started VPN connection']),
 line 91               title="OpenVPN",
 line 92               time=3000)

Changé avec:

line 89               Script.notify(                                                                                       
line 90                'OpenVPN',                                                                                       
line 91                Script.localize(LABELS['Started VPN connection']))                                               

La notification est toujours bien presente, et plus d'erreur du tout.



Al.

**Comment by wwark** [comment]
Hello @algouye2802,
Merci pour cette correction.
Si ça te dit tu peux proposer ce change via un PR sur la branche dev du plugin?

Encore Merci,
Wwark

**Comment by acolombier** [comment]
Salut a vous deux et merci du coup de main!

J'avoue n'avoir vraiment pas eu le temps de gratter plus que ça... Si
jamais, je peux aussi proposer une PR dès que je retrouve ma machine d'ici
une semaine !

Est-ce que cela permet une connexion automatique, ou est-ce que la
connexion reste manuel ?

Encore merci!

**Comment by wwark** [comment]
Hello @SylvainCecchetto,
Tu pourrais regarder pour adapter le code proposé ou le commiter s'il convient.
Le PR est à supprimer car il va casser l'historique.

Merci !

**Comment by SylvainCecchetto** [comment]
Hello !
Ça roule je vais regarder tout ça ;)

**Comment by SylvainCecchetto** [comment]
Bonsoir à tous,
Le commit https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/7221c9527c5c45f4834b82fb17d663bbaeba4f8c devrait résoudre le problème de `AttributeError: 'module' object has no attribute 'send_notification'` et aussi résoudre deux ou trois erreurs `No item found` qu'on avait lorsqu'on était dans import ou delete config.

Le prochaine version 0.2.14~beta03 contiendra cette correction.

Merci pour vos retours ! n'hésitez pas à ré-ouvrir cette issue si besoin ;-)
