### ISSUE TITLE
Missing channel from RTBF Auvio in m3u list for belgium.

### ISSUE THREAD

**Issue by mistertix** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#220]
Hi, thanks for the addon.
I Miss channel from RTBF Auvio in m3u list for belgium.
is it possible to add them?
Thanks a mil.
mistertix

**Comment by wwark** [comment]
Hi @mistertix,
It is not possible because RTBF Auvio propose just part of live TV.
These part live TV are available directly throught the plugin.

THanks,
Wwark
