### ISSUE TITLE
Problème de direct sur certaines chaines

### ISSUE THREAD

**Issue by guillaumer** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#224]
Bonjour,

Déjà félicitations pour ce travail qui doit nécessiter beaucoup de temps.

Je rencontre une erreur lors de la lecture de certains chaines en direct, notamment tout le groupe FranceTV, tandis que d'autres sont fonctionnelles, principalement TF1 et TMC.

Etant hors de France, j'utilise un VPN depuis un VPS privé (le monde étant bien fait, je suis obligé de regarder la TV Française pour voir l'intégralité des matchs d'un certain événement sportif mondial qui se déroule dans le pays dans lequel je vis, on marche sur la tête !). 

Le direct sur le site de FranceTV marche sans problème. En utilisant l'add-on Kodi france.tv, le direct est également fonctionnel.

Plateforme de test 1 : RPI3b+ /  Kodi 18.3
Plateforme de test 2 : Kubuntu 18.04 /  Kodi 18.4 (aussi essayé en 17.6)

Log, quasi identique sur les deux plateformes : https://pastebin.com/2g4JuXcq

`ERROR: ffmpeg[7F6C97793700]: Unable to open key file https://livefrancetv.akamaized.net/keys/hls.key
2019-10-04 11:48:43.194 T:140104374499072    INFO: ffmpeg[7F6C97793700]: [hls,applehttp] Opening 'crypto+http://live.francetv.fr/simulcast/France_2/hls/ZXhwPTE1NzAxNzg4OTB+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV8yJTJmaGxzKn5obWFjPTNiNjg2NjAyNWViYzcyYjVlMTQxMDZhZWFhZTIwOWIyNzcyNzYxMDE4NmY0YjFlZmE1MGY4NThjNTU5Y2Y3Mzk=/France_2-video=400000-15009434.ts' for reading
2019-10-04 11:48:43.195 T:140104374499072   ERROR: ffmpeg[7F6C97793700]: [crypto] Unable to open resource: http://live.francetv.fr/simulcast/France_2/hls/ZXhwPTE1NzAxNzg4OTB+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV8yJTJmaGxzKn5obWFjPTNiNjg2NjAyNWViYzcyYjVlMTQxMDZhZWFhZTIwOWIyNzcyNzYxMDE4NmY0YjFlZmE1MGY4NThjNTU5Y2Y3Mzk=/France_2-video=400000-15009434.ts
2019-10-04 11:48:43.195 T:140104374499072   ERROR: ffmpeg[7F6C97793700]: [hls,applehttp] Error when loading first segment 'http://live.francetv.fr/simulcast/France_2/hls/ZXhwPTE1NzAxNzg4OTB+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV8yJTJmaGxzKn5obWFjPTNiNjg2NjAyNWViYzcyYjVlMTQxMDZhZWFhZTIwOWIyNzcyNzYxMDE4NmY0YjFlZmE1MGY4NThjNTU5Y2Y3Mzk=/France_2-video=400000-15009434.ts'
2019-10-04 11:48:43.196 T:140104374499072   DEBUG: Error, could not open file (2) http://live.francetv.fr/simulcast/France_2/hls/ZXhwPTE1NzAxNzg4OTB+YWNsPSUyZnNpbXVsY2FzdCUyZkZyYW5jZV8yJTJmaGxzKn5obWFjPTNiNjg2NjAyNWViYzcyYjVlMTQxMDZhZWFhZTIwOWIyNzcyNzYxMDE4NmY0YjFlZmE1MGY4NThjNTU5Y2Y3Mzk=/index.m3u8?hdnea=exp=1570157890~acl=%2fsimulcast%2fFrance_2%2fhls*~hmac=3a5df6b4e4b8cadb244563800ec1c25ea3eae851e20600a73499cf6865a1b105
2019-10-04 11:48:43.196 T:140104374499072   ERROR: OpenDemuxStream - Error creating demuxer`

Il semblerait que le flux ne puisse être ouvert pour une raison inconnue (l'URL https://livefrancetv.akamaized.net/keys/hls.key me renvoie bien un fichier .key).

J'ai regardé par ci par là mais je n'ai rien trouvé de probant.

Merci d'avance.

**Comment by wwark** [comment]
Bonjour,
En regardant le code de l'add-on Kodi france.tv il semblerait qu'on puisse exclure des flux vidéos suivant sa geolocalisation.
On va regarder si on peut ajouter ce point dans Catch-up TV & More.

Merci,
Marc.

**Comment by wwark** [comment]
Après réfléxion, je pense que ma précédente réponse n'est pas suffisante.

Est-ce qu'il serait possible d'avoir une trace HAR de votre navigateur lors de la lecture d'un direct TV de France TV afin de voir si le hls.key apparait et avoir le lien du direct TV ?

Merci,
Wwark

**Comment by guillaumer** [comment]
Merci pour la réponse rapide !

L'URL du direct utilisée est : https://www.france.tv/france-2/direct.html
Voici le lien pour le HAR (12 Mo...) : https://we.tl/t-rbH5oo8MZ7

A priori rien ne concernant un hls.key.

**Comment by wwark** [comment]
Merci pour cette trace. Oui on passe par le format dash qui n'est pas très bien supporté par Kodi pour l'instant.

**Comment by guillaumer** [comment]
Pas de soucis. Merci encore pour avoir pris le temps de regarder.

**Comment by wwark** [comment]
Les différents flux de France TV proposent plusieurs type de format.
Pour l'instant on a mis en visible dans le plugin. Le flux direct tv géolocalisé car il propose la meilleur qualitée et de le multi-langue.
Pour un autre ticket on va devoir ajouter une lib de géolocalistation on pourra switcher sur le flux vidéo non géolocalisé.
Ce point peut être un bon point pour le plugin.

**Comment by wwark** [comment]
Bonjour @guillaumer,

Est-ce qu'il serait possible de tester la dernière béta (0.2.14~beta02)?
De mon côté via un VPN en changeant sur un autre Pays. l'addon France TV ou la modification effectuée ne permettent pas d'avoir accès à la ressource.

Merci,
Wwark

**Comment by guillaumer** [comment]
Bonjour,
Je viens d'essayer avec la 0.2.14~beta02, les flux France TV ne passent toujours pas. Toujours fonctionnel en revanche sur l'addon France TV.

Merci.

**Comment by wwark** [comment]
Bonjour,
Merci pour votre test.
Est-ce qu'il serait possible d'avoir un log en debug de Kodi avec le cas Catchup TV & l'addon de France TV ?
Merci,
Wwark

**Comment by guillaumer** [comment]
Bonjour,

Voici le log avec la 0.2.14~beta02 : https://pastebin.com/CRGmA0K9
Et voici avec l'addon France TV : https://pastebin.com/HPr5gtJx

Les deux essais ont été fait avec le même programme (France 2 live) et le même VPN.

Merci.

**Comment by wwark** [comment]
Bonjour,
Le code a été fait sans avoir besoin du VPN.
Si vous passez par le VPN vous allez appelé l'url que vous n'arrivez pas à lire.
Cette url propose le flux vidéo avec le multi langue. Il est important de le garder pour CatchUp TV&More.

Le plugin France TV propose l'autre flux vidéo dégradé.

Vous pouvez déjà vérifier sans passer par le VPN.

**Comment by guillaumer** [comment]
Bonjour,

Même erreur sans passer par le VPN : https://pastebin.com/jitQTPpM

**Comment by wwark** [comment]
Bonjour,

Merci donc c'est ce format qui n'est pas lisible que ce soit avec le flux VPN ou non surement lié à votre environnement/localisation.
Pour votre cas, nous devons proposer le flux video dégradé sans les multi-langues.
Il ne sera pas proposé en principal. Il faudra passer par une option pour l'activer.

On a aussi une nouvelle API pour les live TV (je vais regarder aussi dans ce sens aussi)

**Comment by wwark** [comment]
[plugin.video.catchuptvandmore.zip](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/3883636/plugin.video.catchuptvandmore.zip)
Test avec la nouvelle API de France TV pour les live TV.
Les changements ont été effectués que pour France2, 3 4 et 5.
Les autres live TV ne fonctionneront pas.

**Comment by guillaumer** [comment]
Bonjour @wwark,

Ça fonctionne en effet, un grand bravo et merci !

J'ignore combien de temps peut prendre l'ajout de l'option pour choisir son flux dans la branche principale, mais si je suis le "seul" à avoir ce soucis et à utiliser un VPN (ce qui n'est pas tout à fait légal j'en conviens), je m'en voudrai que cela vous donne trop de travail ou vous retarde au détriment de fonctionnalités plus importantes qui serviront un bien plus grand nombre de personnes.

Quoiqu'il en soit, félicitations pour cet add-on très utile et bien fait. S'il y a besoin de procéder à de nouveaux tests dans le futur, n'hésitez pas à me recontacter.

**Comment by wwark** [comment]
Bonjour @guillaumer 
Ce fichier ZIP est la nouvelle API qui propose juste un flux.
Vous avez testé via un VPN ? ça donne quoi sans VPN ?
Est-ce que vous avez bien le multi-langue maintenant ?

Je pense qu'on va basculer sur cette nouvelle API.

Merci,
Wwark

**Comment by guillaumer** [comment]
Bonjour,
Alors, l'ancienne 0.2.16-beta05 du .zip ne fonctionne plus avec VPN : https://pastebin.com/xq517dEQ
Idem avec la nouvelle 0.2.16-beta06 : https://pastebin.com/NLLxcePi

(Pareil sans VPN avec une erreur 403 à l'ouverture du flux mais c'est plutôt normal)

**Comment by wwark** [comment]
Nous n'avons pas encore ajouter ce changement dans version DEV.
On prévoit de le faire 0.2.17.
Est-ce qu'il est possible de refaire les tests dans le zip fourni précédement ?
Encore Merci !

**Comment by guillaumer** [comment]
Bonjour @wwark,

Désolé, ma carte SD a décidé de partir en vacances anticipées et j'ai du un peu tout réinstaller.

J'ai refais un test en 0.2.16-beta03 du précédent zip, avec le VPN : https://pastebin.com/1mJjzsag
Sans le VPN, j'ai une erreur 422 (Unprocessable entity) : https://pastebin.com/dYRVrf93

Merci (et bonnes fêtes).

**Comment by wwark** [comment]
Bonjour Guillaumer,

Désolé pour le retard de notre réponse .. est-ce que le problème est
toujours d'actualité ?

Merci,
Wwark

Le jeu. 26 déc. 2019 à 02:00, guillaumer <notifications@github.com> a
écrit :

**Comment by wwark** [comment]
Ticker fermé.
