### ISSUE TITLE
Décalage son sur RPI3B

### ISSUE THREAD

**Issue by LuNiKoFf** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#227]
Bonjour, j'utilise Catch-Up TV and more qui est vraiment formidable sur mon Raspberry PI 3B avec la distribution LibreElec, mais j'ai un gros problème de décalage de son qui rend impossible le visionnage au bout d'un moment.

Je l'utilise en 4G / 4G+ sur une antenne Free car là où je suis je ne peux pas capter la TNT … Mon débit est entre 20 mbits et 80 mbits selon si je suis en 4G ou en 4G+.

Tout fonctionne bien mais au bout d'un moment, le son commence à se décaler d'une seconde, puis de 2. Des fois j'ai carrément 20 secondes de décalage. Des fois ça coupe sans raison. Ça arrive plus fréquemment sur TF1. J'ai essayé avec et sans VPN, pareil.

J'ai testé de changer toutes les configs partout dans Kodi, j'arrive pas à faire mieux.
J'ai rien vu de foufou dans les logs de Kodi non plus ...

Mon impression (qui est peut-être fausse) est que Kodi ne bufferise pas assez.
J'ai donc modifié *advancedsettings.xml* avec :

```
<advancedsettings>
  <cache>
    <buffermode>1</buffermode>
    <memorysize>139460608</memorysize>
    <readfactor>1000</readfactor>
  </cache>
</advancedsettings>
```
Ça bufferise pour la lecture d'un fichier local, ou sur SAMBA, mais ça bufferise pas pour Catch UP TV ...

Quelqu'un aurait une solution ?

Merci.

**Comment by SylvainCecchetto** [comment]
Bonjour LuNiKoFf,

Merci pour votre retour !
Afin d'être certain qu'il s'agisse d'un problème de Catch-Up TV & More (ou non) avez vous eu la possibilité d'effectuer des tests avec d'autres plugins Kodi du même genre (Arte +7, FranceTV, ou autre) ?

Parce que malheureusement je ne pense pas que nous puissions faire grand chose pour ce problème (à voir ce que tu en penses @wwark). Car en réalité, le plugin ne sert qu'à récupérer l'URL du flux vidéo que l'utilisateur souhaite regarder, et après ce lien est donné Kodi qui gère toute ce qui est "bufferisation", décodage du flux video/audio, lecture et etc ...

Un autre test que vous pouvez peut être fait si cela est possible, c'est d'essayer sur votre ordinateur d'installer Kodi et Catch-Up TV & More afin de voir si le problème apparait aussi ici.

Nous restons disponible si besoin ;-)

**Comment by wwark** [comment]
Bonjour,
Merci ! Je confirme le message de @SylvainCecchetto.
https://kodi.wiki/view/Advancedsettings.xml#network

Il faudrait tester buffermode à 0 pour voir si ça améliore les choses.

Merci,
Wwark

**Comment by wwark** [comment]
Je ferme ce ticket suite à nos réponses.
@LuNiKoFf N'hésite pas à le rouvrir si besoin.
