### ISSUE TITLE
Replay RTL TVI (Belgique) HS

### ISSUE THREAD

**Issue by nazca974** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#231]
Bonjour,

depuis 3 jours le replay de RTL TVI (Belgique) ne fonctionne plus affichant les erreurs suivantes :
"Authentification impossible"
"Runtime Error : impossible de résoudre l'url"

Impossible d'accèder à la partie compte de l'extension.

[](https://paste.kodi.tv/afenamuvir)

Cordialement

**Comment by SylvainCecchetto** [comment]
Bonjour nazca974,

Merci pour ce retour.
Qu'entendez vous par "Impossible d'accéder à la partie compte de l'extension" ?
Voulez-vous dire que vous ne parvenez pas à paramétrer votre couple login/mot de passe de RTL-TVI dans les paramètres de Catch-Up TV & More?

Merci

**Comment by nazca974** [comment]
Bonjour SylvainCechetto,

il semble que mon VPN belge et mon compte RTLplay aient été blacklistés en fait, donc je passe actuellement via un VPN luxembourgeois (création d'un nouveau compte et reparamétrage de l'extension).

L'accès à la partie compte n'est pas possible via kodi sur windows. Même après installation impossible de paramétrer l'onglet "compte".

Par contre cela fonctionne bien sous android TV et téléphone.

Merci

**Comment by SylvainCecchetto** [comment]
> il semble que mon VPN belge et mon compte RTLplay aient été blacklistés en fait, donc je passe actuellement via un VPN luxembourgeois (création d'un nouveau compte et reparamétrage de l'extension).

Dac ça marche, du coup pas un problème de l'extension en elle même alors ;-)

> L'accès à la partie compte n'est pas possible via kodi sur windows. Même après installation impossible de paramétrer l'onglet "compte".

Ah bon ? Je ne sais pas si @wwark est au courant de cet issue mais je n'ai pas le souvenir que quelqu'un ai déjà remonté ce problème.
J'essaierai de faire un test à l'occasion avec Kodi 18.4 sous Windows ; merci pour le retour !

**Comment by wwark** [comment]
Hello,
Je n'ai pas Kodi sous windows aussi ... pour tester.
Tu pourrais nous faire des screenshots du comportement observé. Et nous fournir les logs en mode debug?
Est-ce que tu utilises le skin par défaut de Kodi ou un autre ?

Merci,
Wwark

**Comment by nazca974** [comment]
Bonjour,

Jai finalement réinstallé  Kodi et cela a résolu  le problème.

Cordialement

**Comment by wwark** [comment]
Ok cool. Je ferme donc ce ticket !
Bon replay,
Wwark
