### ISSUE TITLE
Plus de guide tv fr

### ISSUE THREAD

**Issue by mmtest1** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#233]

**Comment by mmtest1** [comment]
Bonjour,
J'utilise pvr iptv simple client avec catchuptv and more pour visualiser le direct directement dans kodi et depuis quelques jours le guide de programmes est vide
J'ai bien suivi le tuto et tout fonctionnait jusqu'il y a quelques jours
Mon install : raspberry 4 + raspbian buster + kodi 18  avec le lien pour le guide tv fr
Pourriez-vous contrôler le lien ?
Je vous remercie pour votre excellent boulot
Bonne soirée

**Comment by Psychoses** [comment]
Salut @mmtest1, j'ai le même soucis depuis quelques jours.

Je suppose que tu as suivi ce tuto:
https://catch-up-tv-and-more.github.io/live_tv_installation/

Et à un moment il faut renseigner "France: http://bit.ly/tvguidefr"

Le lien renvoi vers : https://raw.githubusercontent.com/Catch-up-TV-and-More/xmltv/master/tv_guide_fr.xml

Que tu peux retrouver ici: https://github.com/Catch-up-TV-and-More/xmltv

Et on peux y remarquer qu'il n'y a pas eu d'update depuis 8 jours.
Il va falloir patienté un peu pour que cela soit fix je pense.

**Comment by mmtest1** [comment]
Salut @Psychoses 
Je suivi la même procedure et refais une fresh install complète du système sans changement, il faut donc attendre un fix

**Comment by YannBrrd** [comment]
+1 depuis quelques jours...

**Comment by wwark** [comment]
Bonsoir,
Oui nous avons un souci pour la génération du guide TV.

On vous vous tient au courant quand c'est corrigé.

Merci,
Wwark

**Comment by mmtest1** [comment]
Bonsoir,
Le bug a l'air d'être corrigé, retour du guide tv fr, un grand merci pour votre suivi et votre réactivité 
Bonne soirée

**Comment by SylvainCecchetto** [comment]
Bonsoir tout le monde !
Désolé pour le guide TV, c'était de ma faute, j'avais sans le vouloir désactivé la mise à jour automatique (crontab) du fichier XMLTV contenant les informations des programmes.
Logiquement tout devrait rentrer dans l'ordre maintenant...
Merci d'avoir remonté l'info !
Bonne soirée

(Je ferme l'issue, si besoin ne pas hésiter à re-open ;-) )
