### ISSUE TITLE
Add France Inter video live stream

### ISSUE THREAD

**Issue by YannBrrd** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#238]
Hi,

Is it possible to add France Inter video live stream as present [here](https://www.franceinter.fr/direct)?

Thanks,
Yann

**Comment by wwark** [comment]
Hi,
Yes it is possible. It is a dailymotion live so no technical problem.
Thanks,
Wwark

**Comment by YannBrrd** [comment]
Hi,

Any place I can look at to see how I can contribute to this ? 

Thx.

**Comment by YannBrrd** [comment]
Looks like weo will be a good fit...

**Comment by wwark** [comment]
Implemented (https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/8c859fa995c7e92b6c9c0d5ac1ff25e92228dcb5)
Will be available in next beta (around 23pm CEST time)

**Comment by YannBrrd** [comment]
Works here. Thanks a lot. 

Should it appear upper in the list? It is not ordered yet.

**Comment by SylvainCecchetto** [comment]
It should appear in the last position in `Live TV/France` path.
You can move up or down any item by right clicking (or press key `c`) on it, then choose `Move up` or `Move down` ;-)

**Comment by YannBrrd** [comment]
It does yes. And work well. Can be released as dar as I'm concerned. ..

**Comment by YannBrrd** [comment]
Thanks 😃😃😃

**Comment by wwark** [comment]
Cool on ferme l'issue.
