### ISSUE TITLE
France.tv replay, certains contenus non disponible

### ISSUE THREAD

**Issue by nmaster2042** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#240]
Certains contenus de france.tv ne sont pas lisibles en replay, cela semble avoir commencé le 12 novembre.

Ex: je vais dans le replay, France 5, émission C à vous, je sélectionne une émission daté du 12 ou 13 novembre et je lance la lecture. Cela semble démarrer puis retour au menu, sans message d'erreur.

**Comment by wwark** [comment]
Bonjour,

Le problème vient de l'API utilisé de France TV.
Le flux HD sur certains des nouveaux replay remonte un HTTP 404. Elle n'existe pas ...

Cas du replay CàVous.
http://sivideo.webservices.francetelevisions.fr/tools/getInfosOeuvre/v2/?idDiffusion=4ac44053-787d-463c-8859-710aea45bc37

Workaround c'est d'activé la qualité en mode  DIALOG et choisir le flux SD. 
Avec le flux SD, le replay fonctionne mais pas en HD.

On va surement devoir migrer l'API si les données ne sont plus disponibles.

merci pour l'alerte.

**Comment by wwark** [comment]
Il y a bien une nouvelle API.
J'ai commencé à implémenter la nouvelle API.
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/archive/dev.zip

Il faudrait tester ce zip et m'indiquer si vous rencontrez des cas d'erreur.

Merci à toutes personnes voulant tester !

**Comment by wwark** [comment]
Pour ceux qui sont à l'étranger, https://geoftv-a.akamaihd.net/ws/edgescape.json
Pourriez-vous récupérer la valeur du country_code pour votre pays ?

Positionner le country code à cette url
https://player.webservices.francetelevisions.fr/v1/videos/f4cf9995-941e-4ced-98b5-00994b309dce?country_code=**Remplacer_Country_Code**&device_type=desktop&browser=chrome
Accéder à cette url et nous fournir les informations.

Merci

**Comment by nmaster2042** [comment]
Je viens de tester le zip, cela semble corriger le problème que je rencontrais.
Je suis en France donc je ne pourrai pas tester la géolocalisation par contre.
Y-a-til autre chose qu'il faudrait tester ?

**Comment by wwark** [comment]
Merci.
Il faudrait tester plusieurs vidéos voir s'il y en a qui ne fonctionnent pas. C'est un nouveau code et il manque de trouver une video protégé par DRM pour implémenter ce cas et surement d'autres cas.

**Comment by nmaster2042** [comment]
J'ai fais des tests sur france.tv, pour moi tout fonctionne désormais, aussi bien séries, actu, documentaires, sur les différentes chaines.

Serait-il judicieux de tester aussi en dehors de france.tv ?
Est-ce que le nouveau code est également utilisé sur d'autres services de replay ?

**Comment by nmaster2042** [comment]
Par contre problème sur BFM TV, j'ai une erreur lorsque je veux entrer sur le replay de la chaine avec un message d'erreur: No module named lib2to3.pgen2.parse

Cela se produit sur ma box équipée de CoreElec 9.2.0.
Mais pas sur mon kodi 18 de test sur mon pc à base Ubuntu 19.04.

J'ai envoyé le log via la QR code.

**Comment by wwark** [comment]
Merci pour vos tests.
Oui France TV, France 3 Régions, La 1ère, Spectacles et Culture (francetv), France tv slash, FranceTV Education (francetv), IRL (francetv), Studio 4 (francetv), France TV Sport (francetv)

Je vais regarder pour migrer les live TV sur la nouvelle API.

Pour BFM TV, pourriez-vous ouvrir un nouveau ticket avec le log Kodi en mode debug. Est-ce que vous avez le problème aussi dans la version release 0.2.13 ?

Merci,
Wwark

**Comment by nmaster2042** [comment]
Je viens de refaire des tests.

Problèmes sur Studio 4 et IRL, je ne peux entrer sur le replay, il y a une erreur, log envoyé via le QR code. Test depuis kodi 18 / Ubuntu 19.04.

Pour les autres replays france.tv, cela fonctionne bien.

OK pour un autre ticket pour BFM, par contre je ne saurais vous affrimer si le bug était présent en 2.13 avec certitude car je consulte rarement ce replay.

Il me semble que cela fonctionnaitil y a quelques semaines en tout cas.

**Comment by wwark** [comment]
Merci pour les tests le code semble stable. Cool !
Est-ce qu'il y a eu une mise à jour de Corelec dernièrement ?

**Comment by nmaster2042** [comment]
Non, pas de MAJ de coreelec d'autant que je suis en stable.

**Comment by nmaster2042** [comment]
Sur le PC, impossible d'entrer sur le replay RIL ou studio 4.

Sur la box, on peut y entrer, naviguer mais on a l'erreur (la même) de façon aléatoire lors de la tentative de lecture d'une vidéo.

**Comment by wwark** [comment]
Release 0.2.14 sortie.
@nmaster2042 je n'ai pas encore eu le temps pour regarder RIL et studio 4 pour ton PC.
Il est possible que les lectures sont KO de façon aléatoire. Ils utilises sur RIL et Studio 4 différents format de video (France tV, Youtube etc ..) Tu as des cas de vidéos en erreur que je regarde.

**Comment by nmaster2042** [comment]
J'ai mis à jour sur mon pc le plugin en version 2.15 depuis le dépot beta.

Sur studio 4  par exemple Dans Comédies > 3 dans la tête, en sélectionnant
cette entrée j'ai toujours l'erreur remontée le WE dernier.

**Comment by nmaster2042** [comment]
Aujourd'hui j'ai refait des tests avec le plugin en version 0.2.16beta2 du dépot beta.

Toujours impossible d'entrer sur studio 4 et IRL depuis mon pc. avec la même erreur.

Sur la box amlogic, je peux entrer dans ces 2 replays, naviguer mais à la lecteure de vidéos, c'est aléatoire: ça peut fonctionner mais parfois erreur, le même que sur le PC.

Tout ceci depuis la même connexion internet (PC en ethernet filaire, box en wifi).

En revanche je confirme que les replays France 2 et France 5 sont bien corrigés, plus aucune problème d'accès.

En espérant que cela puisse aider.

**Comment by wwark** [comment]
@nmaster2042, désolé je n'ai pas eu le temps de regarder.
On a fait quelques changement depuis ta dernière trace.
Est-ce que tu pourrais partager la log en debug sur ce ticket du problème d'accès studio 4 et IRL depuis ton PC ?

Merci,
Wwark

**Comment by wwark** [comment]
le comportement de 3 dans la tête est le même que sur le site web. On ne peut rien faire sur ce point.
![image](https://user-images.githubusercontent.com/469461/69482336-10156e80-0e1a-11ea-84a7-1e14092a4903.png)

**Comment by nmaster2042** [comment]
Voici le log du PC sur tentative d'accès au Studio 4 et IRL.
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/3882728/kodi.log)

**Comment by wwark** [comment]
si tu accèdes depuis ton PC à cette url https://irl.nouvelles-ecritures.francetv.fr/ ? ça donne quoi ?

**Comment by nmaster2042** [comment]
Depuis firefox, j'ai eu une erreur "La page n'est pas redirigée correctement." dans un premier temps.

Je l'ai refait une seconde fois et je suis arrivé sur le site sans erreur.

Et depuis je n'ai plus l'erreur.

Mais sous kodi, c'est toujours pareil.

**Comment by wwark** [comment]
bonjour @nmaster2042,
Ok j'ai fait une petite adaptation sur la branche Dev (0.2.16beta3) tu pourrais tester ?
Merci,
Wwark

**Comment by nmaster2042** [comment]
bonjour @wwark 

Cela ne change rien, j'ai toujours le même erreur.

**Comment by nmaster2042** [comment]
Il doit y avoir malgré tout un problème sur le site IRL car en testant l'url que tu m'as donné hier dans firefox, j'ai encore eu l'erreur suivante (cf copie d'écran). J'actualise la page et je peux y accéder sans erreur.

![Site IRL Firefox](https://user-images.githubusercontent.com/22748840/69493500-aa73c180-0eaf-11ea-9ad4-a1b47c0c2b52.png)

**Comment by wwark** [comment]
Ok il est possible de tester ce fichier.
[plugin.video.catchuptvandmore.zip](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/3883570/plugin.video.catchuptvandmore.zip)

Merci,
Wwark

**Comment by nmaster2042** [comment]
Oui, je viens de tester avec le zip proposé, l'erreur n'est plus la même.
Désormais, j'ai une erreur "no items found".
Ci-joint le log.
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/3883740/kodi.log)

**Comment by wwark** [comment]
ok je pense que j'ai testé tous les cas possibles de mon côté.
Il faudrait ouvrir un ticket d'issue aux personnes gérant la version de Kodi déployé pour comprendre.
Est-ce que pour ubuntu tu utilises le Kodi depuis les PPA ?
Il faudrait tester https://doc.ubuntu-fr.org/kodi (Kodi depuis les PPA) pour voir si ça marche mieux.

Si c'est ok on va fermé ce ticket.

**Comment by nmaster2042** [comment]
oui j'utilise le PPA pour ubuntu.

Tu peux fermer le ticket, je l'avais initialement ouvert pour les replays france 2 et france 5 qui fonctionnent désormais parfaitement.

Je testais à ta demande les autres replays france tv.

Encore merci pour ton aide et le dév que tu fais dessus, et merci aux autres dévs.

Très bon plugin, je ne pourrais pas m'en passer sur kodi.

**Comment by wwark** [comment]
@nmaster2042 Merci pour tous tes tests.
Merci !

**Comment by jordanpires449** [comment]
HTTPError
