### ISSUE TITLE
Replay TF1 inaccesible

### ISSUE THREAD

**Issue by benjidu67160** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#244]
Replay TF1 inaccesible erreur d'index "list index out of range".
Catch-Up TV  v0.2.13
Kodi 18.4 Leai
MiBox 3 Android TV 8.0.0

**Comment by wwark** [comment]
Bonjour,

Merci pour l'alerte.
Nous venons de corriger sur la version beta du plugin. Elle sera disponible ce soir vers 23h (CET time).
On va prévoir une release dans les prochains jours pour ce point

Merci,
Wwark.

**Comment by benjidu67160** [comment]
Merci
