### ISSUE TITLE
direct tfx / tmc

### ISSUE THREAD

**Issue by dragitpro** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#251]
Bonjour,
Tout d'abord MERCI pour votre superbe appli sur Kodi, c'est le must pour acceder a la tv francaise depuis l'etranger. 

Je voulais simplement vous signaler que depuis hier soir, les chaines TFX et TMC ne fonctionnent plus en direct.

bravo et merci d'avance

**Comment by davedevils** [comment]
Je confirme - de mon cotée ça fait un bout de film de 20 seconde (le buffer je suppose ?) et ça coupe (pour tfx et tmc)

**Comment by wwark** [comment]
Bonjour,
ESt-ce que le problème est toujours présent ?
Ce midi j'ai vu aussi des problèmes mais ça semble être stable maintenant.

Merci,
Wwark

**Comment by davedevils** [comment]
De mon coté ça a l'air bon , a voir avec l'auteur du poste.

merci :)

**Comment by dragitpro** [comment]
Cela fonctionne de nouveau.

Merci pour votre resolution extrement rapide.

**Comment by wwark** [comment]
Merci pour vos retours.
C'était un soucis du côté de TF1. On n'a rien fait de notre côté.
Je clos ce ticket.
