### ISSUE TITLE
ImportError No module named builtins

### ISSUE THREAD

**Issue by Psychoses** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#255]
### Describe the bug
A clear and concise description of what the bug is:

Nothing work because there is multiple line like "from builtins import xxx"

```
2019-12-02 05:22:03.835 T:8031   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named builtins
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 29, in <module>
                                                from builtins import str
                                            ImportError: No module named builtins
                                            -->End of Python script error report<--
```

problematic code seems be here:
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/245/commits/ccce58987bfae0fc424f0c87b9b5bc366c319d30

### To Reproduce
1. install Kodi 18.5
2. use commit #253 or probably any after https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/245/commits/ccce58987bfae0fc424f0c87b9b5bc366c319d30

### Expected behavior
A clear and concise description of what you expected to happen:
No more "No module named builtins" error.

### Actuel behavior
Tell us what happens instead:
Full addon don't work.

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [*] Android
 - [*] Windows

 - Operating system version/name: w10/androidtv
 - Kodi version: 18.5
 - Catch-up TV & More version: #253

**Comment by SylvainCecchetto** [comment]
Thank you for this report!
I never had this issue with Kodi 18.4 and 18.5 on macOS (And I think that Wwark plays with Linux and he does not have any problem also ...) :-/
I will try on Windows today ;-)

**Comment by SylvainCecchetto** [comment]
I just tested the `favourites_json` branch on Kodi 18.5/Windows 10 x64 and I have no problem to run the addon.

Maybe some dependencies are missing on your Kodi installation (I think of the `future` dependency...)? 

How did you install the `favourites_json` version of the addon? If you have just replace the `plugin.video.catchuptvandmore` folder then Kodi does not install missing dependencies. You need to manually install them OR completely remove the addon and doing a fresh install with `Install from zip file` (you can keep your profile folder during the uninstall step IIRC).

We are waiting for your news ;-)

**Comment by Psychoses** [comment]
first for your investigate. u are true. I just see: `<import addon="script.module.future" version="0.17.1"/>`

But i haven't it installed. Thx u a lot. Should be better now. I close ;)
