### ISSUE TITLE
Repo à jour?

### ISSUE THREAD

**Issue by meaz** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#260]
Bonjour,

dans l'aide à l'installation [ici](https://catch-up-tv-and-more.github.io/fr/installation/) il est indiqué d'utiliser ce repo: `https://repo.cecchettosylvain.fr/zip/`
Or, les dernières versions proposées datent d' avril 2019 alors que les dernières releases datent en fait de novembre.
Le repo est-il à jour? Ou alors existe-t-il une autre adresse, l'aide n'ayant pas été mise à jour?
Du coup, j'ai installé la dernière version en téléchargeant directement le zip. Mais à chaque mise à jour il faudra que je retélécharge le zip?

**Comment by wwark** [comment]
Bonjour,
Oui le répo ne se met pas à jour fréquement comme le plugin.
C'est vraiement rare.
Si vous avez installé le repo et le plugin ensuite. Le repo prend en compte les nouvelles versions du plugin et les installes automatiquement.
Il n'y a plus rien à retélécharger à la main.
Je ferme ce ticket à rouvrir si besoin.
Merci,
Wwark

**Comment by meaz** [comment]
Je viens d'essayer: en installant le repo comme expliqué, c'est le plugin 0.0.5 qui est téléchargé.

**Comment by wwark** [comment]
Le repo c'est différent du plugin.
Ici le plugin que vous avez installé sur votre environnement : plugin.video.catchuptvandmore v0.2.15 installed
Tout est correct.
