### ISSUE TITLE
Segmentation fault (core dumped) à répétition 

### ISSUE THREAD

**Issue by kaminsky9444** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#263]
Bonjour,

J'ai remarqué que mon kodi 18.4 crash relativement souvent avec Catchup TV And More, voici les logs : 

https://termbin.com/u3h0l.

Je tiens à dire que j'utilise le PVR.

En vous remerciant !.

**Comment by kaminsky9444** [comment]
Dans /lib/systemd/system/kodi.service mettre : 

[Unit]
Description = Kodi Media Center
After = remote-fs.target network-online.target
Wants = network-online.target

[Service]
User = pi
Group = pi
Type = simple
ExecStart = /usr/bin/kodi-standalone
Restart = on-abort
RestartSec = 5
Environment="LIRC_SOCKET_PATH=/var/run/lirc/lircd"

[Install]
WantedBy = multi-user.target

Puis sudo systemctl enable kodi.service ; sudo reboot

Et problème résolu.

**Comment by kaminsky9444** [comment]
Désolé, le problème persiste, je ne sais plus trop quoi faire.

**Comment by wwark** [comment]
Bonjour,

Si vous desactiver le PVR est-ce que le problème continu ?
Merci,
Wwark

**Comment by kaminsky9444** [comment]
Bonjour @wwark,

Oui si je n'utilise pas le PVR, mais directement votre application, je n'ai aucun segfault.

**Comment by wwark** [comment]
Merci pour cette confirmation.
Il faudrait ouvrir un ticket sur PVR IPTV Simple pour comprendre la cause.

Wwark

**Comment by kaminsky9444** [comment]
J'ai peut être une piste, visiblement ça serait un problème avec l'option ``gpu_mem``, j'ai augmenté la valeur, je vois si ça règle de manière définitive le problème.

**Comment by kaminsky9444** [comment]
Bonjour,

J'ai pu résoudre mon problème, alors il faut vraiment le savoir, mais dans ``Système`` -> `` Audio `` -> ``Dispositif de sortie du canal audio ``, quant on est en HDMI, il faut choisir ``ALSA: Default (bcm2835 ALSA bcm2835 ALSA)`` et non `` PI:HDMI``, puis il faut absolument activer le ``Passthrough``.
