### ISSUE TITLE
Replay TF1

### ISSUE THREAD

**Issue by BugProg** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#266]
Bonjour,

Depuis quelque temps il me met un message d'erreur, quand j'essaie de lire une video en replay. (uniquement sur le service de TF1)
Voici la photo du message : https://192.168.1.36/s/2xbtKrrHZ5YoQqa
J'ai cherché l'apps dans le store. Mais elle est introuvable.

Joyeuse fête !!

**Comment by SylvainCecchetto** [comment]
Bonjour BugProg,

Merci pour ce retour, cependant le lien de la photo semble pointer vers une IP locale et je ne parviens pas à y accéder.

Pouvez vous nous partager votre log Kodi svp ?

Bonnes fêtes de fin d’année également 😉

**Comment by BugProg** [comment]
Bonjour,

https://www.home-cloud.fr/s/2xbtKrrHZ5YoQqa
Désolé pour le lien :)
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/4005091/kodi.log)
[kodi_crashlog-20191226_174716.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/4005092/kodi_crashlog-20191226_174716.log)

Voici les logs.
Merci

**Comment by SylvainCecchetto** [comment]
Merci pour la photo. 

Comme indiqué, vous devez installer l’add on « inputstream.adaptive » sur votre Kodi. 
En effet, le flux auquel vous souhaitez accéder doit être protégé par DRM, et afin de le lire, le plugin inputstream.adaptive est nécessaire.

Je n’ai pas mon ordi sous la main, mais je pense que vous trouverez toutes les infos nécessaires sur internet. 

Nous restons disponible si besoin.

**Comment by BugProg** [comment]
Bonjour,

Après plusieurs recherche sur le web, j'ai installé le paquet manquant.
Mais voilà, un problème de résolue qu'un autre survient. :)
Toujours sur le service de TF1 mais uniquement sur le série "New Amsterdam" (en replay).
Il me met que les commandes "fdisk" et "parted" sont manquante, or elles ne le sont pas.
Voici une image du problème.
![IMG_20191228_124523](https://user-images.githubusercontent.com/54059521/71546026-8dd91680-2992-11ea-9f80-52ac14b466a3.

Et voici le message précédent, où j'ai répondue "OUI".
![IMG_20191228_124511](https://user-images.githubusercontent.com/54059521/71546047-ba8d2e00-2992-11ea-8372-52b5e17aee35.jpg)

Merci de votre aide.

**Comment by SylvainCecchetto** [comment]
Euh... jamais eu ce problème, peut être que @wwark à une idée ?

Sur quelle plateforme utilisez vous Kodi ? Un Linux ?

**Comment by BugProg** [comment]
:)
Oui moi aussi, oui j'utilise rasbian buster.

**Comment by SylvainCecchetto** [comment]
Avez vous essayé un `sudo apt-get install kodi-inputstream-adaptive` et après essayer d’activer le plugin dans les réglages de Kodi ?

**Comment by SylvainCecchetto** [comment]
Je viens de trouver ça sur internet : 

> If the helper throws the error "fdisk and parted not found on this machine," or something to that effect, run Kodi as root by typing sudo kodi in the terminal, then install the Netflix, Amazon, and/or Inputstream.adaptive addons as root.

**Comment by SylvainCecchetto** [comment]
Et encore quelques infos ici https://fiat-tux.fr/2019/08/19/installer-lextension-netflix-sur-kodi/

**Comment by BugProg** [comment]
Bonjour,
Merci beaucoup, tout marche parfaitement bien.
En effet il fallait lancer Kodi en root pour que cela fonctionne.
Il m'a fait l'installation de logiciel supplémentaire puis le film c'est lancé.

Merci.
Bonne vacance

**Comment by SylvainCecchetto** [comment]
Parfait alors ;-)
Bonnes vacances également et bon film ;)
