### ISSUE TITLE
Search option for tva catch-up tv

### ISSUE THREAD

**Issue by chamchenko** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#268]
**Is your feature request related to a problem? Please describe.**
The list of videos on catchup tv for TVA channel is very long and there for it's really hard to find what someone is locking for

**Describe the solution you'd like**
Implementing a search function using the api here is an exemple
https://videos.tva.ca/proxy/search?appId=5955fc5f23eec60006c951f1&uuid=27c1c05a-e164-40d6-b081-b280bd7b04f7&text=la%20voix&pageSize=16&pageNumber=1&sortBy=name&sortOrder=asc

Edit: that link won't work unless you use the header 'accept: application/json'

**Comment by SylvainCecchetto** [comment]
I'll try to take a look.

**Comment by SylvainCecchetto** [comment]
I added the search function in this commit https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/650b4862288936e5310b228b1d07e08361c723a2
If you use our official beta repository (see https://catch-up-tv-and-more.github.io/installation/#ii-add-the-official-catch-up-tv--more-repository) then you can try the 0.2.17~beta08 version of the plugin.

Let us know if it's ok for you ;-)

**Comment by chamchenko** [comment]
Thanks for your reply and for hard work on this addon it's working like a charm. :-)

**Comment by SylvainCecchetto** [comment]
Perfect if it’s ok for you :-D
Thank you for your message and for this feature request. 
Feel free to re-open this issue if needed or to open another one for another thing.
And happy new year ;P

**Comment by chamchenko** [comment]
Happy new year and best wishes for you too
