### ISSUE TITLE
Simpleplugin - errors

### ISSUE THREAD

**Issue by Condottiero1** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#27]
Bonjour. J'ai Android et Windows et vous me direz ce que vous avez besoin. J'ai une erreur avec la version du Master sur Android aussi.  Le log est ici
https://pastebin.com/Ei6mWB6D

Cordialement

Condottiero

**Comment by Condottiero1** [comment]
J'ai reinstalle la version 0.1.3. Elle a bien marche et je l'ai laissee sur l'installation windows allumee toute la nuit.  Ce matin j'ai regarde Cnews, LCI et BFMTV.  Quand j'ai essaye L'Equipe, c'est parti en erreur. Je vous joins le log de toute la matinee.  On voit que malgre  l'erreur youtube les autres canaux on bien marche.
Cordialement
Condottiero

https://pastebin.com/6TgLS1uB

**Comment by wwark** [comment]
Bonjour,

L'erreur pour l'équipe TV est différente, on n'arrive pas à recupérer le flux de la video.
Qu'elle est la vidéo remontant cette erreur ? Est-ce sur toutes les videos ? J'ai fait quelques tests sur des videos de l'équipe TV et j'ai pu les voir sans problème.

Wwark.

**Comment by Condottiero1** [comment]
Bonjour Wwark,
Mea culpa sur celui-la. Je suis aux USA et pour l'Equipe et quelques autres canaux il faut le VPN.  J'ai mis VPN France ce matin et ca marche.  Desole pour avoir cause le souci.
Cordialement,
Condottiero

**Comment by wwark** [comment]
Merci pour ce retour. Ce point montre qu'on a besoin de pouvoir remonter l'information si la video est localisée à une région spécifique mais je pense difficile à implémenter.

Je laisse ouvert le ticket au sujet du cache qui doit être vérifier. La reinstallation du plugin ne peut pas être la bonne réponse.

- [ ] Ajouter une option pour vider le cache

**Comment by wwark** [comment]
On a mis à jour la librairie sur la gestion du plugin et le mode pour le cache pour les sites web. Je pense que ça devrait limiter les problèmes rencontrés et avoir un effet bénéfique sur la vitesse d'exécution du plugin.

Il reste à ajouter une option pour vider le cache.

**Comment by Condottiero1** [comment]
https://pastebin.com/ywwbE5L1

Erreur avec version 0.1.4 et Kodi 17.5

Cordialement
Condottiero

**Comment by wwark** [comment]
Bonsoir Condottiero,

L'erreur me semble toujours identique. 
@SylvainCecchetto tu aurais une idée quel pourrait être la cause ?

Wwark,

**Comment by SylvainCecchetto** [comment]
Bonjour tout le monde,
Je regarde ça ;-)

**Comment by SylvainCecchetto** [comment]
Concernant l'erreur qui s'affiche pour YoutubeDL ce n'est pas ça qui bloque parce qu'en réalité c'est juste un warning (bon il faudra quand même fixer ça plus tard ..)
Mais là le problème semble lié à la fonction simpleplugin qui va chercher les mots dans string.po.

Tu as cette erreur exclusivement sous Android ?

**Comment by SylvainCecchetto** [comment]
Je viens de tester le plugin en version 0.1.4 depuis le repo Catch-Up TV & More sur un Kodi 17.4 just installed et aucun problème. (sous Mac OS).

Je vais essayer sur un Kodi 17.5

**Comment by Condottiero1** [comment]
Bonjour,

L'erreur que j'ai envoye est sous Windows 10. J'ai visiblement la meme chose sous Android mais je ne vous ai pas soumis l'erreur.

**Comment by SylvainCecchetto** [comment]
Ah d'accord, je n'ai pas de Windows sous la main pour essayer.

Ce que je vous propose de faire, si vous en avez la possibilité :

1. Sauvegarder le dossier Kodi quelque part (il se trouve ici : `%APPDATA%\kodi`)
2. Supprimer ce dossier qui contient l'ensemble des plugin et réglages Kodi
3. Là en démarrant Kodi il doit normalement être comme au premier jour (En anglais et sans aucun élément (plugin, films ou autre))
4. Installer le plugin par la méthode du dépôt officiel https://repo.cecchettosylvain.fr/url

Ce qui nous permettrait de voir si cette erreur est due à un réglage de Kodi ou alors une incompatibilité avec autre chose ...

Merci d'avance pour les tests ;-)

**Comment by Condottiero1** [comment]
J'ai un peu pense la meme chose et je viens de vous telecharger le log entier d'Android juste pour voir si vous voyez une incompatibilite.  Pour ma part je vais creer un nouveau dossier kodi sue Windows pour voir si ca change quelque chose.
https://pastebin.com/Z7XtZid9

**Comment by SylvainCecchetto** [comment]
Ah merci pour le log Android, l'erreur a l'air d'être différente.

Je vais essayer de voir si je ne peux pas me faire un petit émulateur Android TV pour faire des tests sur cette plateforme (je ne sais même pas si ça existe ...)

**Comment by Condottiero1** [comment]
J'ai kodi sur mon tlephone Android, sur tablette Android, sur boite Android, sur un ordi Windows, et un petit ordi Windows. Le petit ordi Windows et la boite Android font marcher les frand ecrans.  :-)
Avec Windows on a acces a des CPU qui marchent plus rapidement......en general

**Comment by Condottiero1** [comment]
Bonjour,

J'ai cree une version de Kodi sur Windows seulement avec Catch-up et ca a marche impeccablement.

Puis j'ai repris ma derniere version et j'ai elimine mon suspect numero 1 "Bob Unleashed".  Et puis j'ai elimine catch-up et le folder dans "addon data". J'ai reinstalle depuis le Kodi Repository. Pour l'instant tout marche meme dans cette version. Je vous ferai part des suites dans les jours a venir.

C'etait seulement Carch-up qui ne marchait pas.  Les autres addons avaient toujours marche.  Ils serait utile de savoir ou est le probleme.

Cordialement

**Comment by 3th0** [comment]
Suite à l'issue #32 : 
Après une désinstallation de l'ensemble des plugins et en supprimant tout ce qui ressemble à CatchupTv / YoutubeDlControl / Freplay dans .kodi/userdata/addon_data. Cela fonctionne avec succès ! 
 youtube-dl control en version 17.518.2 et Catchup-tv 0.1.5-beta011. 

Je suis disponible pour des tests.

**Comment by wwark** [comment]
Pour les informations utiles:
@3th0, 
le plugin avait fonctionné dans une ancienne version d'OSMC ? Si oui est-ce que le problème est présent depuis la mise à jour en version 17.5 de OSMC ?
Est-ce vous aviez beaucoup de plugins ?
Est-ce que vous vous rappeler de l'action effectuée quand le problème est arrivée ?

D'avance merci pour les retours,
Wwark

**Comment by Condottiero1** [comment]
Bonjour,

Apres plusieurs jours de fonctionnement, je continue a ne plus avoir les erreurs mentionnees ci-dessus.  La desinstallation de Bob Unleashed a remedie a tous les problemes. Je serais curieux de savoir pourquoi.

Cordialement,

**Comment by wwark** [comment]
Bonsoir,
Il faudrait voir si @3th0 avait aussi ce plugin sur son instance de Kodi.
Est-ce que le plugin a été reinstallé ensuite ?

Cordialement,
Wwark

**Comment by Condottiero1** [comment]
Bonsoir,

apres quelques jours de bon fonctionnement, l'addon a recommence a crasher.  La seule solution est de desinstaller, enlver le dossier dans  addon_data et reinstaller depuis le repository.  Ca marche un jour ou deux et cela recommence a crasher.

Je n'ai installer rien de nouveau pour qu'il y ait un nouveau conflit.

Cordialement,

**Comment by wwark** [comment]
Merci pour ce nouveau retour.
Je pense que nous allons devoir ouvrir une issue auprès de simpleplugin pour qu'il puisse nous aider sur le sujet.
Nous vous tenons au courant.
Wwark

**Comment by SylvainCecchetto** [comment]
Bonjour tout le monde,

Alors pour retrancher un peu toutes les infos qu'on a : le bug est présent (à priori) seulement sous Windows et Android peu importe la version de Kodi, la version de Catch-Up TV & More ou encore de la lib simpleplugin :-/

Et si je comprends bien l'erreur est toujours la suivante : 

```python
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                         - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'new_datetime'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 334, in <module>
                                                common.PLUGIN.run(window_title)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 779, in run
                                                result = action_callable(params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 260, in channel_entry
                                                return channel.channel_entry(params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/groupecanal.py", line 85, in channel_entry
                                                return root(params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 431, in inner_wrapper
                                                with self.get_storage('__cache__.pcl') as cache:
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 409, in get_storage
                                                return Storage(self.config_dir, filename)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 102, in __init__
                                                self._storage = pickle.loads(contents)
                                            AttributeError: 'module' object has no attribute 'new_datetime'
                                            -->End of Python script error report<--
```

Je vais me plonger un peu dans le code de simpleplugin pour voir ce qui se passe exactement, sinon je vais me charger de poser la question à l'auteur de la lib.

On va essayer de résoudre ce problème parce que c'est pas super de devoir faire un RàZ toutes les semaines.

Bonne journée à tous !

**Comment by SylvainCecchetto** [comment]
Bonsoir à tous,

Sur les conseils de Romanvm j'ai modifié le framework simpleplugin afin de se passer du module datetime qui serait le principal suspect concernant les crash aléatoires.

Les modifications sont présentes sur le commit c861e42192e2b6d556b6ab7d314f5c63a32e8587

En espérant que cette modif soit utile pour les personnes concernées. 

Je laisse l'issue ouverte en attendant vos retours !

**Comment by wwark** [comment]
Merci :)

**Comment by wwark** [comment]
Bonjour,

Est-ce que les dernières modifications sur le plugin ont permit de ne plus avoir ce comportement ?

D'avance merci pour votre retour :)

**Comment by Cna63** [comment]
Bonjour,
je ne sais pas si le bug est lié mais j'ai eu une erreur liée au simpleplugin storage en navigant dans les replays disponibles :
`19:20:28.902 T:1513092080   ERROR: GetDirectory - Error getting s:live|i:playlist/
19:20:36.737 T:1958920192   ERROR: Control 53 in window 10025 has been asked to focus, but it can't
19:20:42.722 T:1203762160  NOTICE: script.module.youtube.dl: youtube_dl core version: 2017.07.09
19:20:42.970 T:1203762160   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'hash'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 52, in <module>
                                                _ = common.ADDON.initialize_gettext()
                                              File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 757, in initialize_gettext
                                                raw_strings_hash != ui_strings_map['hash']):
                                              File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 187, in __getitem__
                                                return self._storage[key]
                                            KeyError: 'hash'
                                            -->End of Python script error report<--
19:20:43.378 T:1958920192   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/
19:20:43.381 T:1958920192   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/) failed
19:21:14.837 T:1596978160   ERROR: GetDirectory - Error getting
19:21:22.270 T:1958920192   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
`
C'est repartit après avoir supprimé :
/.kodi/userdata/addon_data/plugin.video.catchuptvandmore/*.pcl
/.kodi/userdata/addon_data/plugin.video.catchuptvandmore/cache/*

Pas ré installation du plugin.
En espérant que ça fasse avancer la résolution du problème.

Environnement:
Rasperry PI, OSMC, KODI 17.5, CatchUpTV v0.1.6

**Comment by wwark** [comment]
Bonsoir @Cna63,
Je viens de relire votre message et je n'avais pas vu que vous parliez de la version 0.1.6 de l'addon. Nous avons effectué des modifications sur le storage présentes sur la dernière release v0.1.7 qui devrait limiter ces erreurs.
Est-ce que le problème est de nouveau apparu avec la version 0.1.7 ?

Bien cordialement,
Marc Roy.

**Comment by lucsanteramo** [comment]
Bonsoir,

Même bug que Cna63. De mon côté l'erreur apparait dès l'ouverture du plugin.
Supprimer les fichiers règle le problème.
Environnement : 
Rasperry PI3, LibreElec8.1.2, KODI 17.6, CatchUpTV v0.1.8-beta005

Si je peux fournir d'autres infos, je suis dispo !
Merci
Luc

**Comment by wwark** [comment]
Bonjour,

Merci Luc pour ce retour donc le problème est encore présent même en version 0.17 et 0.1.8 ...

Est-ce qu'il est possible d'avoir les fichiers .kodi/userdata/addon_data/plugin.video.catchuptvandmore/*.pcl la prochaine fois que le problème survient ?

Quelle a été la dernière action avant que le problème arrive ?

D'avance merci,
Wwark

**Comment by lucsanteramo** [comment]
J'ai l'impression de ne rien avoir fait de spécial avant.
J'avais du regarder des emissions en replay et/ou direct, puis arrêter le raspi, puis je suis revenu sur catchup ou j'ai constaté le problème.
A noter que j'étais en version v0.1.7 quand ca s'est produit, puis que je suis passé en v0.1.8-beta005 pour voir si ca reglait le problème.
Il a fallut que je supprime les fichiers pour débloquer.... peut-etre un mauvais résidu de la version stable ?
Je te tiens au courant si ca se reproduit (c'était pas la 1ere fois, y compris sur un hote windows ou un autre hote linux, avec la version stable), et je partage les pcl.

Merci à toi !
Luc

**Comment by wwark** [comment]
Bonjour,

J'ai une de mes instances remontant la même erreur.

Le fichier __gettext__.pcl ne contient que ces lignes:
`(dp1
.`

```
08:52:59.491 T:18446744071963932976   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'hash'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.catchuptvandmore/addon.py", line 28, in <module>
                                                from resources.lib import vpn
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.catchuptvandmore/resources/lib/vpn.py", line 25, in <module>
                                                from resources.lib import utils
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.catchuptvandmore/resources/lib/utils.py", line 33, in <module>
                                                _ = common.ADDON.initialize_gettext()
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 757, in initialize_gettext
                                                raw_strings_hash != ui_strings_map['hash']):
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 187, in __getitem__
                                                return self._storage[key]
                                            KeyError: 'hash'
                                            -->End of Python script error report<--
```

**Comment by wwark** [comment]
J'ai poussé un fix sur la branche de dévelopement avec ces tests:
* \_\_gettext\_\_.pcl n'existe pas
* hash n'est pas présent dans le fichier \_\_gettext\_\_.pcl 
* hash avec une valeur différente

Je pense qu'on a tous les cas possibles de tests. Dans tous ces cas, le fichier est recréé.

Wwark

**Comment by diaagi** [comment]
Bonjour,
J'ai ce bug avec la manip suivante, c'est reproductible.
Kodi sous Windows.
Depuis CatchUp TV and more, j'ajoute 2 liens en Favoris (si je ne mets qu'un lien ça marche).
Je vais dans Favoris sous Kodi, et je clique sur le premier lien mis en favori. Ca plante!
Et le dernier lien mis en favori fonctionne parfaitement!

**Comment by wwark** [comment]
Bonjour @diaagi,

Est-ce qu'il est possible d'installer la dernière version du plugin 0.1.7 ?
Pouvez-vous tester de nouveau si le problème est toujours présent ? si c'est le cas pourriez vous nous founir les logs de kodi pour avoir l'erreur ?

Les favoris ils sont mis sur les chaînes ou sur des vidéos ou sur des emissions ?

Merci d'avance, 
Wwark.

**Comment by diaagi** [comment]
Bonjour
J'ai teste avec la version sous le repo kodi. La v0.1.7 ne marche pas sous kodi windows. Le bug apparait avec des emissions. J'ai rajoute dora sous jeunesse tf1 et peppa pig sous jeunesse france5!

**Comment by wwark** [comment]
Ok est-ce qu'il est possible d'avoir les logs d'erreur obtenus pour la version 0.1.7 sous Windows ?
Il y a eu plusieurs améliorations depuis la version 0.1.7 et surement que les favoris fonctionnent mieux.
Je vais tester de mon côté les favoris cités pour voir comment ça fonctionne de mon côté.
Merci d'avance pour votre retour.

**Comment by wwark** [comment]
Pour information, j'ai pu reproduire le cas avec dora sous jeunesse tf1 et peppa pig sous jeunesse france5 sur la version 0.1.8.
Nous allons regarder pour voir comment corriger ce cas. Merci pour la remonter du problème.
Cependant, la correction apportée sera sur la version 0.1.9 ou supérieur. J'aurai besoin du log d'erreur lors de l'installation de la version 0.1.7 ou supérieur survenu sur votre environnement.
 
Trace de l'erreur.
`12:25:10.057 T:139717165184768   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'last_channel_name'
                                            Traceback (most recent call last):
                                              File "/home/****/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 412, in <module>
                                                common.PLUGIN.run()
                                              File "/home/****/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 1050, in run
                                                result = action_callable(params)
                                              File "/home/****/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 321, in channel_entry
                                                channel = get_channel_module(params)
                                              File "/home/***/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 289, in get_channel_module
                                                channel_name = storage['last_channel_name']
                                              File "/home/***/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 300, in __getitem__
                                                raise KeyError(key)
                                            KeyError: 'last_channel_name'
                                            -->End of Python script error report<--`

**Comment by diaagi** [comment]
Bonjour,
J'ai réussi à installer la v0.1.7 sous Windows et ça marche nickel, sauf ce leger pb sur la mise en place des raccourcis en favoris.
Ci-dessous le log:

00:50:24.324 T:19256   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
00:50:28.961 T:2348  NOTICE: script.module.youtube.dl: youtube_dl core version: 2017.07.09
00:50:29.963 T:2348   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: argument of type 'NoneType' is not iterable
                                            Traceback (most recent call last):
                                              File "C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\addon.py", line 412, in <module>
                                                common.PLUGIN.run()
                                              File "C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\simpleplugin.py", line 1042, in run
                                                result = action_callable(params)
                                              File "C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\addon.py", line 324, in channel_entry
                                                return channel.channel_entry(params)
                                              File "C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\channels\fr\tf1.py", line 74, in channel_entry
                                                return list_videos(params)
                                              File "C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\simpleplugin.py", line 685, in inner_wrapper
                                                return self._get_cached_data(cache, func, duration, *args, **kwargs)
                                              File "C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\simpleplugin.py", line 637, in _get_cached_data
                                                data = func(*args, **kwargs)
                                              File "C:\Users\***\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\channels\fr\tf1.py", line 386, in list_videos
                                                if 'meteo.tf1.fr/meteo-france' in params.program_url:
                                            TypeError: argument of type 'NoneType' is not iterable
                                            -->End of Python script error report<--
00:50:30.099 T:19256   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/?action=channel_entry&fanart=http%3a%2f%2frefonte.webservices.francetelevisions.fr%2fimage%2freferentiel_emissions%2f169045107%2f1513536771%2f480%2f0%2ffrance5%2f0%2fimg.jpg&id_programme=6093&next=list_videos_1&page=0&search=False&window_title=Oui-Oui
00:50:30.103 T:19256   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/?action=channel_entry&fanart=http%3a%2f%2frefonte.webservices.francetelevisions.fr%2fimage%2freferentiel_emissions%2f169045107%2f1513536771%2f480%2f0%2ffrance5%2f0%2fimg.jpg&id_programme=6093&next=list_videos_1&page=0&search=False&window_title=Oui-Oui) failed
00:51:00.928 T:19256   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
00:51:05.592 T:20212  NOTICE: script.module.youtube.dl: youtube_dl core version: 2017.07.09

**Comment by wwark** [comment]
Merci pour ce nouveau log. 
La gestion des favoris n'est pas testé. 
Nous allons prévoir pour la 0.1.9 des tests sur cette partie et des corrections.

**Comment by SylvainCecchetto** [comment]
Je ferme cette issue (à re ouvrir si besoin).
La gestion des favoris (built-in Kodi je parle) doit maintenant fonctionner (0.1.10 il me semble)
