### ISSUE TITLE
Widevine installing issue

### ISSUE THREAD

**Issue by wwark** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#273]
Hi @caguiclajmg and @wnnahoj,
I saw your exchange on the PR.
I opened this ticket.

@wnnahoj, could you please use this issue for your problem. If you can't add a file to this ticket. Can you please send us an url we can download them.

Thanks,
Wwark

**Comment by wnnahoj** [comment]
Hi guys, I have tried on both a 16GB and 32GB sd card on my Pi4 4GB running Kodi 18.6 with the LibreElec OS, to update Widevine on UKTV Play but it gives a error message and does not extract or install the crome OS recovery image even on the latest ver 0.2.21-beta01! Space does not seem to be the issue.When I ask for the paste url, it gives this message, sorry sharing your error log failed, unable to  to retrieve the paste url. Also on this version the channels works for a while and then it cuts out and it takes about 3-4 clicks before channel opens! Thanx for a great addon, and keep safe!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wnnahoj** [comment]
Hi,when i ask to paste url it gives this message, sorry sharing your error log failed, unable to retrieve paste url!
Regards

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wnnahoj** [comment]
Hi I have tried probably more than 20 times to download widevine  on UKTV Play and it still does not download it on my Pi4 4gb ram running the LibreElec OS! And it still does not paste the barcode url, sorry sharing your error logged failed, unable to retrieve paste url! Please help and stay safe, regards.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wwark** [comment]
Hi @wnnahoj,
Sorry I didn't see your previous messages ...

If you can't retreive this url.
You could use the addon named Kodi Logfile Uploader https://kodi.wiki/view/Add-on:Kodi_Logfile_Uploader

You could provide the url on your next message.
Before to use this addon. You need to reproduce one more time the issue.

Thanks,
Wwark

**Comment by wnnahoj** [comment]
Hi url is https://paste.kodi.tv/ojazawinib! Thank you! Stay Safe

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wnnahoj** [comment]
Hi, just tried to watch something now, got error message, url is: https://paste.kodi.tv/fovatubiye' on my Pi4 4gb ram LibreElec OS Thank you, stay safe

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wnnahoj** [comment]
Hi also not working on windows 10, https://paste.kodi.tv/ihuzezirek. Thanx

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wnnahoj** [comment]
Hi ignore the last two emails, it was a vpn server issue, all channels and catchup working well! Sorry! Only need widevine UKTV Play issue to work! Thank You

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wwark** [comment]
Hi @wnnahoj,

Yes it is better not to mix different issues we will try to focus on the issue to install Widevine on your device.

You have the same issue and a fix is this PR https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/330
The best way is to see when it will be merged to inputstreamhelper.
When it will be merged there will be a new release and you will be possible to install widewine

We used the plugin inputstreamhelper to help us to install all dependencies to make DRM worked on Kodi. 

Regards,

**Comment by wnnahoj** [comment]
Thank you appreciate it stay safe!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wnnahoj** [comment]
Hi, just to confirm, i must wait for new release of catch up tv and more addon before downloading widevine? Stay safe thanx

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wwark** [comment]
No it is not of catch up tv and more side.
I saw an update of inputstream helper maybe your issue is fixed.

Regards,

**Comment by wnnahoj** [comment]
Hi UKTV Play still not downloading widevine, same issue! Stay safe thank you

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wwark** [comment]
ok needs to wait.
we can't do anything on our side.
Regards,

**Comment by wnnahoj** [comment]
Hi on the latest catchup tv and more, catchup not working! Gives http error code 403! Tried various uk ip address, live works great! Regards, Stay safe!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wnnahoj** [comment]
Hi not sure my message went through!
Hi on the latest catchup tv and more, catchup not working! Gives http error code 403! Tried various uk ip address, live works great! Regards, Stay safe!


Get Outlook for Android<https://aka.ms/ghei36>


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wwark** [comment]
Hi,
It is better to open a new issue.
We can't follow more than one topic by issue. It is important.
Regarding your issue and using the VPN we could have this type of issue HTTP 403 not authorize.
For that we can't do anything because the serveur may see you have a VPN connection and block it.

regards,

**Comment by wnnahoj** [comment]
Ok thanx

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wnnahoj** [comment]
Hi just updated to the new inputstream helper and UKTV Play gives an error past url https://paste.kodi.tv/otodibadup. Thanx be safe

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wwark** [comment]
Hi,
You have timeout error maybe related to your VPN or your network connection. The main point is if you're not in UK you can have issue to play content.

I think the widewine is fixed I'm right ? If it is the case we can close this ticket.

Thanks,
Regards,

**Comment by wnnahoj** [comment]
Hi widevine still not fixed! Regards

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wnnahoj** [comment]
Hi Mark, thank you so much for a great addon! I have been able now to download widevine on my Pi4 4gb ram running kodi on the LibreElec OS! UKTV Play working perfectly! Thanx again for your support! Regards and stay safe!!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wwark** [comment]
great ! thank you for this information :)
ticket closed

**Comment by wnnahoj** [comment]
Hi hope you well and staying safe! I get this error when trying to open UKTV Play: https://paste.kodi.tv/wefozobafu. Regards

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wnnahoj** [comment]
Hi please ignore previous UKTV Play issue!
I have however noticed that STV Catchup has not worked for awhile on both kodi 18.6  windows 10 and Pi4 4gb ram with kodi 18.6 running on the LibreElec OS!  Live is great! I have connected to a variety of uk ip addresses, but nothing is working! Will appreciate some help! Regards and stay safe!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wnnahoj** [comment]
Hi please ignore my last email it seems to be a vpn issue! Thank you stay safe!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wnnahoj** [comment]
Hi, hope you are in good health and staying safe! I have never been able to watch stv catchup on my android. Live and UKTVPlay works well and have always worked well. Hope this logfile will help you fix the issue for me: https://paste.kodi.tv/idoriwimex .Regards

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by wnnahoj** [comment]
Hi since my email before this one there has been 2 updates and I thought this would solve my android issue. STV catchup on my android still not working. I sent this url paste link https://paste.kodi.tv/idoriwimex in the previous email not sure if you saw it. Regards and stay safe!!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by wnnahoj** [comment]
Hi Mark since yesterday morning i am not able to stream STV catchup, live and UKTVPlay works great! I have installed Kodi 18.7 on my Windows 10 OS url paste is https://paste.kodi.tv/ojibijujin. I have posted the issue on Catchup tv abd more kodi forum which seems to be the wrong platform! Can you please help. Thanx and stay safe

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by wwark** [comment]
Hi,
Sorry I don't respond to you because you continue to post on an issue already closed.
If you have new issue it is better to open a new one.

Regarding your issue HTTP 403 we can't do nothing. It is a vpn issue.
Like already said, the channel website can detect you used a VPN and blocked the stream.
Sorry for that but we can't do nothing.

Thanks,

**Comment by wnnahoj** [comment]
Ok thank you for your help. Stay safe

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by wnnahoj** [comment]
Hi Marc I have noticed that STV has added another 4 channels, the pet collective, failarmy, qello concerts by stingray and dust. Regards and stay safe!!

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by wnnahoj** [comment]
Hi Marc, thanx for adding those channels they work great! Can I ask about the catchup tv and more addon on the android, i have not been able  to get stv catchup to work. Everything else works fine. Regards and stay safe!

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by wnnahoj** [comment]
Hi Marc, I just want you to know that I manually configured a vpn connection on my android with the same server I configured on my windows 10 OS! My android has the same  ip address as my windows 10 OS  but unlike on windows STV catchup does not work on my android phone. Regards and stay safe!

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by wwark** [comment]
Hi, @wnnahoj 
Could you please stop write in this issue already closed ?
We don't provide support for VPN. You need to see with the person sold it to you.

Thanks,

**Comment by wnnahoj** [comment]
HI Marc, I am sorry to harper on this issue,  what I am trying to establish is if STV catchup on windows 10 is worrking on a specific vpn server and my android is configured  to that same server why is STV catchup not working on my adroid? To me it does not seem to be a vpn issue. Regards stay safe.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________
