### ISSUE TITLE
Ajout des direct TV de ICI Télé par région

### ISSUE THREAD

**Issue by wwark** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#274]
Ticket pour suivre ces ajouts dans le plugin.

**Comment by Miciello** [comment]
ICI Télé région Québec (Ville de Québec)
Si ce fichier est correct, je te produirai les autres villes par la suite.
J'attends de tes nouvelles.
Merci.
:-)

[ici.radio-canada.ca.har_Quebec.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/4278094/ici.radio-canada.ca.har_Quebec.log)

**Comment by vonloschz** [comment]
ICI Télé région Montréal

[ici.radio-canada.ca_Archive [20-03-02 21-35-12].zip](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/4278940/ici.radio-canada.ca_Archive.20-03-02.21-35-12.zip)

**Comment by wwark** [comment]
Bonjour,

Pourriez-vous tester la dernière beta ?

Merci,
Wwark

**Comment by wwark** [comment]
Hello,
Je ferme ce ticket car test ok.
Merci,
Wwark
