### ISSUE TITLE
impossible d'installer le plugin master ou dev.

### ISSUE THREAD

**Issue by gilles0606** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#275]
Bonjour,

Sur un kodi libreelec raspbery.
impossible d'installer les dernière version du plugin.

j'ai dans les logs
2020-03-11 07:25:34.792 T:3011530768   ERROR: Failed to read 'zip://%2fmedia%2fdev.zip/plugin.video.catchuptvandmore-dev/addon.xml'

pareil avec la branche master ou la branche  dev.

par contre les zip que j'ai télécharger début février marche parfaitement.

même chose sur un autre kodi raspbian libreelec.

merci

**Comment by SylvainCecchetto** [comment]
Bonjour Gilles,

Je suppose que tu essaies d'installer le ZIP que tu as directement téléchargé depuis GitHub ?
Si c'est bien le cas, alors c'est "normal" que cela ne fonctionne plus.
En effet, nous avons changé la disposition des fichiers sur le dépôt GitHub et nous avons placé tous les fichiers relatifs au plugin dans un sous dossier `plugin.video.catchuptvandmore` et non plus directement à la racine du dépôt.

Plusieurs solutions sont envisageable pour installer le plugin :

* Depuis notre dépôt officiel : https://catch-up-tv-and-more.github.io/fr/installation/
* En téléchargeant les ZIP directement sur la page release de GitHub (il n'y a pas les versions beta) : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/releases
* En téléchargeant les ZIP sur le dépôt GitHub de notre repo :
    * Release (branche master) : https://github.com/Catch-up-TV-and-More/repository.catchuptvandmore/tree/master/zips/krypton_release/plugin.video.catchuptvandmore
    * Beta (branche dev) : https://github.com/Catch-up-TV-and-More/repository.catchuptvandmore/tree/master/zips/krypton_beta/plugin.video.catchuptvandmore

Le plus simple, pour une utilisation quotidienne, étant quand même d'utiliser notre dépôt officiel 😉 

J'espère avoir répondu à ta question ?

**Comment by gilles0606** [comment]
parfait, j'ai reziper le répertoire  nikel....
j'installerais le repos ce soir  :-)

Une fois de plus, GRAND MERCI
