### ISSUE TITLE
6play video doesn't start

### ISSUE THREAD

**Issue by Simon-G** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#278]
Hi!
Here are the logs when I try to start a 6 play video:

> 2020-03-20 20:22:46.484 T:1489941376  NOTICE: [Catch-up-TV-&-More] [import_needed_module] Import module resources.lib.channels.fr.6play on the fly
> 2020-03-20 20:23:01.514 T:1336804224  NOTICE: Previous line repeats 4 times.
> 2020-03-20 20:23:01.514 T:1336804224   ERROR: EXCEPTION: Invalid setting type
> 2020-03-20 20:23:02.241 T:1936945168   ERROR: Previous line repeats 1 times.
> 2020-03-20 20:23:02.242 T:1936945168  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/6play/get_video_url/?_pickle_=80027d71002855076974656d5f6964710158020000006d36710255075f7469746c655f71035816000000c3897069736f64652035202f20536169736f6e20313171045508766964656f5f69647105636675747572652e74797065732e6e65777374720a6e65777374720a7106580d000000636c69705f313235393539363571078571088171097d710a62752e
> 2020-03-20 20:23:02.624 T:1479537536  NOTICE: Creating InputStream
> 2020-03-20 20:23:02.625 T:1479537536   ERROR: ADDON: Could not locate inputstream.adaptive.so.2.3.22
> 2020-03-20 20:23:02.625 T:1479537536   ERROR: IAddonInstanceHandler::CreateInstance: inputstream.adaptive returned bad status "Permanent failure" during instance creation
> 2020-03-20 20:23:02.625 T:1479537536   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/6play/get_video_url/?_pickle_=80027d71002855076974656d5f6964710158020000006d36710255075f7469746c655f71035816000000c3897069736f64652035202f20536169736f6e20313171045508766964656f5f69647105636675747572652e74797065732e6e65777374720a6e65777374720a7106580d000000636c69705f313235393539363571078571088171097d710a62752e]
> 2020-03-20 20:23:02.625 T:1479537536  NOTICE: CVideoPlayer::OnExit()
> 2020-03-20 20:23:02.833 T:1936945168  NOTICE: CVideoPlayer::CloseFile()
> 2020-03-20 20:23:02.834 T:1936945168  NOTICE: VideoPlayer: waiting for threads to exit
> 2020-03-20 20:23:02.834 T:1936945168  NOTICE: VideoPlayer: finished waiting

Actual behavior
Video simply don't start, no error displayed

environment Raspberry-Pi
 - Operating system version/name: libreelect 9.2.1
 - Kodi version: Kodi 18.6
 - Catch-up TV & More version: 0.2.18-beta09 and 0.2.17

Hope it helps!

**Comment by wwark** [comment]
Hi @Simon-G,

The error is "ERROR: ADDON: Could not locate inputstream.adaptive.so.2.3.22"
Inputstream.Adaptive is required to play DRM content.

Can you please verify if inputstream adaptive is correctly install and activated on your Kodi instance?
Do you have some popup indicating this issue ?

Regards,
Wwark

**Comment by Simon-G** [comment]
Hi Wwark,
InputStream Adaptative 2.4.3.1 installed and activated with the default configuration. Do you think I should downgrade to 2.3.22 as asked by catch up TV?
Thanks

**Comment by wwark** [comment]
Hi @Simon-G,
Not sure it is a good idea.
I used also the version 2.4.3 on my setup.

I find this case : https://discourse.coreelec.org/t/missing-inputstream-adaptive-so-version-symlink/5915 (it is for corelec) or (https://github.com/Sandmann79/xbmc/issues/175) libreelec

It is a linking problem you need to check with libreelec.
Do you follow step of libreelec to activate or install this Inputstream.adaptive library ?

**Comment by Simon-G** [comment]
Hi Wwark,
I have uninstall and reinstall inputstream adaptive library from the libreelect repo. It seems the symlink has been updated, error disappears and video is working.
However, I still have some error in logs when I start a video:

> 2020-03-23 22:49:14.226 T:1789887360  NOTICE: [Catch-up-TV-&-More] [import_needed_module] Import module resources.lib.channels.fr.6play on the fly
> 2020-03-23 22:49:22.500 T:1482511232  NOTICE: Previous line repeats 2 times.
> 2020-03-23 22:49:22.500 T:1482511232   ERROR: EXCEPTION: Invalid setting type
> 2020-03-23 22:49:23.267 T:1936715792   ERROR: Previous line repeats 1 times.
> 2020-03-23 22:49:23.267 T:1936715792  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/6play/get_video_url/?_pickle_=80027d71002855076974656d5f6964710158020000006d36710255075f7469746c655f71035816000000c3897069736f64652035202f20536169736f6e20313171045508766964656f5f69647105636675747572652e74797065732e6e65777374720a6e65777374720a7106580d000000636c69705f313235393539363571078571088171097d710a62752e
> 2020-03-23 22:49:23.653 T:1519383424  NOTICE: Creating InputStream
> 2020-03-23 22:49:23.670 T:1519383424   ERROR: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
> 2020-03-23 22:49:26.409 T:1519383424  NOTICE: Creating Demuxer
> 2020-03-23 22:49:26.410 T:1519383424  NOTICE: Opening stream: 1001 source: 256
> 2020-03-23 22:49:26.559 T:1519383424  NOTICE: Creating video codec with codec id: 27
> 2020-03-23 22:49:26.571 T:1519383424  NOTICE: Creating video thread
> 2020-03-23 22:49:26.572 T:1789887360  NOTICE: running thread: video_thread
> 2020-03-23 22:49:26.573 T:1519383424  NOTICE: Opening stream: 1002 source: 256
> 2020-03-23 22:49:26.593 T:1519383424  NOTICE: Finding audio codec for: 86018
> 2020-03-23 22:49:26.595 T:1519383424  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
> 2020-03-23 22:49:26.595 T:1519383424  NOTICE: Creating audio thread
> 2020-03-23 22:49:26.595 T:1448940416  NOTICE: running thread: CVideoPlayerAudio::Process()
> 2020-03-23 22:49:26.890 T:1448940416  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
> 2020-03-23 22:49:26.890 T:1448940416  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)

Tell me if I should close this issue or investigate more.

**Comment by wwark** [comment]
Hi,
Good if the video played we can close this ticket.
These errors are not importants.

regards,

**Comment by dagwieers** [comment]
Related to https://github.com/xbmc/inputstream.adaptive/issues/454
