### ISSUE TITLE
No multiple audio streams

### ISSUE THREAD

**Issue by radtriste** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#281]
### Describe the bug
On live TV or Catch-up TV, I am not able to toggle the audio stream.
Seems there is not different audio streams, even on series like Brokenwood, already mention in issue https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/160

Does not work with Live TV as well ...

### To Reproduce
2 repoducers (one direct and one with widevine)
1. CU-TV => Replay TV => France 3 => Series & Fictions => Brokenwood
2. CU-TV => Replay TV => TF1 => Series & Fictions => Grey's Anatomy

### Actual behavior
1. `Toggle audio stream` does not work. In audio settings, `Audio settings -> Audio stream` is disabled => no choice.
2. `Toggle audio` stream shows `fre` but does not work. `Audio settings -> Audio stream` is also disabled => no choice.

### Expected behavior
I would expect the `Toggle audio stream` to work as the different websites are providing this option.
Also `Audio settings -> Audio stream` should be enabled and show at least 2 streams.

### Your environment
 - Raspberry Pi 4
 - Librelec 9.2.1
 - Kodi version: 18.6
 - Catch-up TV & More version: 0.2.19-beta00
 - Installation method: Catch-Up TV & More's Krypton Beta repository

### Additional context
I just updated Libreelec but the problem was also happening on version 9.2.0 (Kodi 18.5)

### Debug log
Tell me which component you want. I attached also the kodi and system logs.
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/4398782/kodi.log)
[system.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/4398783/system.log)

**Comment by wwark** [comment]
Hi,
Thank you opened this issue.
It depends on the player of kodi not the plugin.
I tried again Brokenwood proposed previously multi audio but it is not the case now.

Maybe the structure of the m3u8 changed for Brokenwood and Kodi are not able to propose more audio stream....

The plugin do just the work to get the stream and proposed to Kodi.
Kodi parse the m3u8 file or mpd (for DRM stream) and proposed the video (multi quality) and audios.

**Comment by radtriste** [comment]
ok for France 3, will try to find another example ...
for TF1, there is the choice on mytf1 for Greys Anatomy (fre or eng) but I don't have it on CU-TV

**Comment by wwark** [comment]
Like I said it is an issue on the Kodi Player.
We don't touch the m3u8 file or mpd file.

**Comment by radtriste** [comment]
ok now I get it... sorry I misread the first comment ...
will check on Kodi's side then. thx

**Comment by wwark** [comment]
the structures of the m3u8 file is like below:

######## M3U8
- Audio 1
- Audio 2
- Video 1 - 1080p
- Video 2 - 480p

The kodi player needs to handle those files.

For France 3, it worked sometimes previously but maybe the format changed and required update on kodi player.

**Comment by wwark** [comment]
Thank you.
I will close this ticket.

The main problem is it can work for sometimes and stop working and Kodi needs to implements the change.
