### ISSUE TITLE
Pas de paramètres du plug in sur XBox one 

### ISSUE THREAD

**Issue by MasseThree** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#282]
Bonjour,

j'ai téléchargé l'add on hier. Il fonctionne bien mais je ne peux pas accéder aux paramètres, notamment pour enregistrer les comptes M6 play et NRJ.
Est ce que ce problème s'est déjà produit ?
Y a-t-il une solution ? dois je essayer de ré-installer ?

**Comment by SylvainCecchetto** [comment]
Bonjour MasseThree,
Je n'ai personnellement jamais rencontré ce problème.
Par curiosité, est-ce que l'accès aux paramètres fonctionne avec d'autres plugins ?

**Comment by wwark** [comment]
Bonjour,

Est-ce que tu utilises un skin particulier ?
Pour info, les replay et live TV de M6 ne fonctionneront pas sur XboX One car XBox ONe ne gère pas la lib widewine utilisé pour lire les DRM.

**Comment by MasseThree** [comment]
OK, du coup ça n'apporterait rien d'avoir accès aux paramètres. :) Merci wwark.
Pour l'accès aux extensions d'autres plug ins, en effet je n'arrive pas à les afficher. 
J'ai réinstallé mais c'est toujours pareil. Du coup ce n'est pas lié à l'extension.
Merci les gars. :)
