### ISSUE TITLE
TeleGrenoble replay

### ISSUE THREAD

**Issue by fdy** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#283]
### Content description

* Name: TeleGrenoble
* Type [e.g. TV channel, Catch-up TV, Website, Radio]: Catch-up TV
* Website URL: http://www.telegrenoble.net/replay.html
* Content language/country: France

### Content access

- [ ] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [ ] This content is geographically restricted

### More information

If you want to add more information, put it here:

**Comment by wwark** [comment]
Bonjour,

Nous venons de rajouter le replay avec cette modification https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/b7662b52bcce7e02cd33b6b53cffe51cc7973924

Elle est disponible dans la version 0.2.21 beta02.

Je ferme ce ticket à rouvrir si besoin.

Merci,
Wwark.
