### ISSUE TITLE
Antenne Centre TV

### ISSUE THREAD

**Issue by JerryCrazy** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#286]
### Content description

* Name: Antenne Centre TV
* Type: TV channel and Catch-up TV
* Website URL: https://antennecentre.tv
* Content language/country: French/Belgium

### Content access

- [ ] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [ ] This content is geographically restricted

### More information

If you want to add more information, put it here:

**Comment by wwark** [comment]
Hello @JerryCrazy,

J'ai commencé à travailler pour ajouter le Live TV cependant pour l'instant je n'ai pas de son.
On a cette erreur dans le player de Kodi.

> 2020-05-31 10:46:04.977 T:139867979073280 WARNING: ActiveAE - large audio sync error: -5013.005541
2020-05-31 10:46:05.026 T:139867979073280 WARNING: ActiveAE - large audio sync error: -5011.974922
2020-05-31 10:46:05.076 T:139867979073280 WARNING: ActiveAE - large audio sync error: -5012.953348
2020-05-31 10:46:05.125 T:139867979073280 WARNING: ActiveAE - large audio sync error: -5012.948949
2020-05-31 10:46:05.174 T:139867979073280 WARNING: ActiveAE - large audio sync error: -5012.925449
2020-05-31 10:46:05.223 T:139867979073280 WARNING: ActiveAE - large audio sync error: -5012.937178

Il y a surement une confirguration pour régler ce cas ...

**Comment by wwark** [comment]
POur information le son n'est plus présent sur le site web https://actv.fcst.tv/player/embed/3083132
Il va falloir attendre qu'il corrige le son de leur côté.

**Comment by SylvainCecchetto** [comment]
Merci à wwark d'avoir ajouté cette chaine.

Je viens de l'activer (elle sera disponible dans la version 0.2.22~beta10 du plugin).
Par contre, de temps en temps il n'y a pas de son avec la vidéo ; mais ça semble indépendant ne notre volonté car sur le site officiel il n'y a pas de son non plus ...

Merci pour cette proposition d'ajout 😉

**Comment by JerryCrazy** [comment]
Merci à tous pour le travail !
