### ISSUE TITLE
ICI RDI (Canada)

### ISSUE THREAD

**Issue by SylvainCecchetto** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#290]
### Content description

* Name: ICI RDI
* Type [e.g. TV channel, Catch-up TV, Website, Radio]: TV channel (live)
* Website URL:
* Content language/country: Canada

### Content access

- [ ] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [ ] This content is geographically restricted

### More information

From this request: https://forum.mpdb.tv/index.php/topic,35713.msg283117.html#msg283117

**Comment by wwark** [comment]
Hello,

Elle est déjà présente dans le menu international.

Merci,
Wwark

**Comment by SylvainCecchetto** [comment]
Salut !
Je suis nul, je n'ai même pas vérifié xD
Merci !
