### ISSUE TITLE
RTBF auvio missing channels

### ISSUE THREAD

**Issue by doczico** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#291]
Hello,
As mention in the release notes 'duplicate auvio channels have been removed' unfortunately now most the rtbf auvio channels are missing.
Only few channels left and not the main ones

### To Reproduce
Update to latest version : 0.2.19~beta4

### Your environment
Corelec

 - Operating system version/name:
 - Kodi version: latest corelec
 - Catch-up TV & More version: 0.2.19~beta4
 - Installation method: official catch-up beta repo

Thank you very much for your awesome work !!
Merci pour ce taff de dingue ;)

**Comment by SylvainCecchetto** [comment]
Hello,

Oh it’s not a good news. What channels are missing?

La Une, La Deux and La Trois should be present in the Live TV/Belgium section. 

Thank you for your report!

**Comment by doczico** [comment]
I'm sorry my bad!
I was used to find them in the auvio folder and didn't think to scroll down
the list 😅

Sorry and thank you again for your awesome work!
Federico

**Comment by SylvainCecchetto** [comment]
No problem 😉 
Thank for your message!
I close the issue then. 🇧🇪
