### ISSUE TITLE
Pas d'EPG

### ISSUE THREAD

**Issue by Phigen** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#292]
Bonjour,
Addon vraiment super mais : tout fonctionne nickel sur un RPI4. Sur un PC sous Linux Mint, avec les mêmes paramètres, j'ai l'EPG vide avec l'adresse "http://bit.ly.tvguidefr". J'ai testé avec l'adresse longue du github, mais même problème. Désolé, je ne maîtrise pas l'anglais. Merci pour l'aide.

**Comment by SylvainCecchetto** [comment]
Bonsoir,
Vous parlez bien de l’EPG dans la section TV de Kodi avec l’utilisation du plugin IPTV Simple et des fichiers M3U ?

**Comment by Phigen** [comment]
Oui, c'est bien ça.
Excusez-moi pour la coquille dans le 1er message, je saisis bien la bonne adresse dans "IPTV Simple" avec "/" et non pas ".".
Ce que je ne comprends pas, c'est que sur 2 versions PC, l'une fonctionne et pas l'autre. Je vais désinstaller tout Kodi et réinstaller. On verra, je vous tiens au courant. Merci pour le retour.

**Comment by Phigen** [comment]
Après réinstallation, ça fonctionne. Mais je ne sais pas où était le problème.
Merci.
