### ISSUE TITLE
TV en direct : Cette sélection a déclenché une erreur inattendue

### ISSUE THREAD

**Issue by MikaOpenFile** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#293]
Bonjour,

Tout d'abord merci pour le superbe travail que vous faites !

J'utilise Kodi 18.6 et catchup TV sur TV android SONY, sur shield et sur mecool M8 ProW et tout fonctionne sans souci depuis de nombreux mois pour la TV en direct sauf RTS un et deux. J'ai à chaque fois une erreur.

Aujourd'hui j'ai installé avec beaucoup de difficulté Kodi 18.6 et Catchup TV sur windows 10 x64.
Et là aucune chaîne en direct ne fonctionne. A chaque fois j'ai ce message "Cette sélection a déclenché une erreur inattendue".

J'ai parcouru le net a la recherche de solution mais en vain, je sèche.

Voici le lien de description : https://paste.kodi.tv/arinicesep

Je précise que j'ai essayé aussi avec la version installée de Kodi et le problème reste le même qu'avec la version portable.

Edit : je me suis focalisé sur la TV en direct mais même les replay ne fonctionnent pas.

Une idée ?

Merci par avance !

**Comment by SylvainCecchetto** [comment]
Bonjour Mika,

Merci pour les encouragements 😉 

En parcourant le log que vous avez fourni (et merci d'ailleurs !) on remarque que toutes les erreurs sont dues à des timeout. Le Kodi de ce Windows 10 arrive bien à accéder à internet ?

**Comment by MikaOpenFile** [comment]
Oui kodi a bien accès à internet sur ce PC.
J'ai d'ailleurs installé Catchup TV directement depuis le depot.

Je n'utilise pas de vpn.

Merci.

**Comment by SylvainCecchetto** [comment]
Hum c'est étrange.
Je vois également que vous utilisez une version "portable" de Kodi ? (Je ne savais même pas que ça existait...). Je me demande si ce n'est pas un problème entre cette version de Kodi et URLQuick ...

Avez vous installer Kodi depuis leur site officiel ? https://kodi.tv/download

**Comment by MikaOpenFile** [comment]
Oui c'est bien la version de Kodi téléchargée ce jour même sur le site officiel. Il suffit de la renommer en zip de l'extraire et d'ajouter -p au raccourci qui pointe vers Kodi.exe et cela fait une version portable. Quoi qu'il en soit j'ai bien essayé aussi avec une installation normale de Kodi. Dans les deux cas j'ai exactement les mêmes problèmes.

Précédemment j'utilisais la version 17.6 de Kodi que j'avais aussi installée en version portable et sur ce même ordinateur. Avec catch up TV cela fonctionnait sans aucun problème.

**Comment by SylvainCecchetto** [comment]
J'aurais appris quelque chose aujourd'hui 😛 

Pour le coup je ne vois vraiment pas d'où peu venir le problème alors ...
A tout hasard pouvez vous essayer d'activer le mode Debug et de fournir à nouveau un log qui met en évidence le problème ?
Merci

**Comment by MikaOpenFile** [comment]
Voici le log en mode debug :

https://paste.kodi.tv/ipumivijaw

**Comment by MikaOpenFile** [comment]
Ne perdez pas de temps avec le log précédent, j'ai trouvé. Quelqu'un a le même problème ici : https://forums.comodo.com/antivirus-help-cis/cis-antivirus-slows-down-kodi-exception-exe-and-path-wont-work-t115211.0.html

C'est l'antivirus qui ralenti Kodi. Et pourtant il fonctionnait parfaitement avec la 17.6 ce matin avant que je n'installe la 18.6. Étrange...

Du coup ça fonctionne pour TF1 et FR2 mais avec C8 ça génère une erreur dont voici le log : https://paste.kodi.tv/epowahesus

Ce la ne fonctionne pas non plus pour RTS un et deux : https://paste.kodi.tv/ibacuvagof

**Comment by SylvainCecchetto** [comment]
Ah parfait alors pour le problème de Timeout !

Pour C8, c'est un problème tout récent du à la mise à jour de Youtube-DL. Vous régler le problème installer la version 0.2.20 du plugin (soit en utilisant notre dépôt : https://catch-up-tv-and-more.github.io/fr/installation/) ou bien attendre la mise à jour provenant du dépôt officiel de la Team Kodi (la version 0.2.20 a été acceptée aujourd'hui sur leurs dépôts, donc je pense que d'ici demain elle devrait apparaître chez tous les utilisateurs).

Pour RTS je ne sais pas trop par contre, @wwark a peut être une idée ?

**Comment by wwark** [comment]
Hello,

RTS est suvi sur ce ticket https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/139

Merci,
Wwark

**Comment by MikaOpenFile** [comment]
Merci je vais jeter un œil à ce sujet.

Mais chez moi je n'ai pas ce flux d'une minute. Je n'ai rien du tout. L'erreur arrive dès que je clique sur RTS un ou deux.

Et encore une fois merci pour votre travail ! Elle est vraiment au top cette extension !!!!

**Comment by wwark** [comment]
RTS Couleur 3 fonctionne ? car lui n'utilise pas de DRM

**Comment by MikaOpenFile** [comment]
> Pour C8, c'est un problème tout récent du à la mise à jour de Youtube-DL. Vous régler le problème installer la version 0.2.20 du plugin (soit en utilisant notre dépôt : https://catch-up-tv-and-more.github.io/fr/installation/) ou bien attendre la mise à jour provenant du dépôt officiel de la Team Kodi (la version 0.2.20 a été acceptée aujourd'hui sur leurs dépôts, donc je pense que d'ici demain elle devrait apparaître chez tous les utilisateurs).
> 

J'ai déjà la version 0.2.20. Elle était effectivement disponible dès ce matin sur le dépôt officiel de Kodi.

**Comment by MikaOpenFile** [comment]
> De rien !
> 
> RTS Couleur 3 fonctionne ? car lui n'utilise pas de DRM
> Le flux est géolocalisé pour RTS 1, RTS 2, etc ...

Oui couleur 3 fonctionne.

**Comment by wwark** [comment]
OK merci pour le test.
Il faut trouver une application sous android qui ferait la même que sur PC. Il y a pleins d'infos sur google.

**Comment by MikaOpenFile** [comment]
Ah ok, je pensais que ça devait être un addon dans kodi. En appli android j'ai effectivement vu des solutions.

Et encore merci pour votre support !!!!!!!
