### ISSUE TITLE
Erreur au lancement de catch-up TV

### ISSUE THREAD

**Issue by matthieuv67** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#297]
### Describe the bug
Impossible d'ouvrir l'extension Catch-UP TV : Kodi indique KeyError 'root'

### Your environment
Testé sur Raspberry Pi 3, distribution LibreElec 9.2.1 (Kodi 18.6)
Catch-up TV 0.2.20 et 0.2.21Beta4, même résultat
J'utilise l'apparence par défaut de Kodi (Estuary)

Sauriez-vous d'où peut venir ce problème ?

**Comment by SylvainCecchetto** [comment]
Hello,
Par quelle méthode avez vous installé le plugin ?
Un debug log pourrait nous aider 😉

**Comment by matthieuv67** [comment]
Bonjour, j’ai suivi la méthode d’installation décrite sur GitHub (ajout de source, installation du repo depuis le zip). Mais depuis, j’ai refait une installation clean sur une autre SD et là ça fonctionne, le problème doit venir de mon install LibreElec ou de ma carte SD je pense :/
Du coup, le problème est réglé, désolé pour cette fausse alerte

**Comment by SylvainCecchetto** [comment]
Parfait alors si tout fonctionne 😉 
Juste pour information, nous avons également un site internet avec les explications détaillées et des images si besoin : https://catch-up-tv-and-more.github.io/fr/
Nous restons disponible si besoin.
Je ferme l'issue.
