### ISSUE TITLE
probleme widevine

### ISSUE THREAD

**Issue by sapiensdebase** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#298]
bonjour, 

Tout d abord merci de vos effort et du travail offert à la communauté.
Je me permets de vous soumettre mon cas:

je viens de faire une installation fraiche de windows 10 pro.
Installation de kodi depuis le site officiel,  leila stable. ( et non depuis le store)
La lecture de videos fonctionne.

J installe Catch Up depuis le depot kodi officiel. version 0.2.20.
tout fonctionne parfaitement sauf pour le groupe M6 ( en live et replay)
L add on me demande d installer widevine, je valide et j obtiens un message d erreur: 
"_cannot importe name link_" .

j ai desinstallé l add on, essayé les versions beta 0.2.21 depuis le depot github, puis la version 0.2.18 toujours le meme probleme.

Idem avec reinstalle de kodi. 
Pour info: Je lance kodi en mode administrateur. pas de probleme de droits.
Dans chrome, je parviens sans probleme à lire le stream 6play avec mes identifiants.

Jai installé l add on video test stream, qui m installe correctement widevine.
puis je  teste le imputStream Adaptive avec widevine. tout fonctionne en toutes qualité. 
Je retourne dans catch up, cette fois, il me dit que widevine necessite une mise a jour.. toujours le meme message lors de la tentative d installation.
J ai essayé avec plusieurs versions de widevine, toujours cette demande de mise a jour.

Y a t il un fichier quelconque ou configurer la version de widevine que doit attendre Catch up?

Voilà où j en suis. Espérant un coup de pouce de votre part, merci
Ju.

**Comment by wwark** [comment]
Bonjour,

Merci pour l'intérêt pour ce plugin.

Oui nous sommes au courant.
Suivi dans ce ticket : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/273

Cette dépendance que nous utilisons doit être corrigé de leur côté.

Merci,
Wwark.

**Comment by sapiensdebase** [comment]
re-
je pensais que le billet #273  ne concernait que des versions arm , pi etc.
je viens d installer la version 0.4.7.
tout fonctionne parfaitement, en live et replay.
Je vous remercie, pour votre aide et quelle reactivité!
cordialement, ju

**Comment by wwark** [comment]
merci pour votre retour.
Je ferme ce ticket.
