### ISSUE TITLE
Installation sous Kodi 19

### ISSUE THREAD

**Issue by Phigen** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#301]
Bonjour,
J'ai tenté d'installer la version de dépôts Release et Beta, mais à chaque fois c'est un échec avec un message par rapport à la version de Python.
Test sous Windows 10, sous Linux et sous RPI4.
Pourtant, j'ai cru comprendre que le plugin était compatible Matrix.
Merci.

**Comment by SylvainCecchetto** [comment]
Bonsoir,
Le plugin n'est actuellement pas officiellement compatible avec Kodi Matrix :
Bien que le plugin soit compatible Python 3, certains modules dont le plugin est dépendant ne sont pas encore disponible sous Matrix donc nous ne pouvons pas encore proposer notre plugin sur le dépôt Matrix de Kodi.

Matrix n'est toujours pas en stade beta et beaucoup de plugin ne sont pas encore compatible avec ce dernier.

**Comment by Phigen** [comment]
Ok, merci.

**Comment by romainreignier** [comment]
Bonjour @SylvainCecchetto 
Est-il possible de connaître les plugins nécessaires encore non compatible avec la version 19 de Kodi ?
Je ne connais pas encore le développement pour Kodi mais il y a peut-être moyen que je puisse essayer de donner un coup de main pour accélérer le support.
J'utilise Kodi à travers de LibreElec sur des cartes utilisant des SoC Allwinner donc le canal nightly est le seul disponible sur ces cartes car leur support est encore en développement. Donc forcément la version 19 pour les images récentes.
Le plugin Catch-up-TV-and-More est celui que j'utilise le plus. J'en profite pour vous remercier pour votre travail sur celui-ci !

**Comment by SylvainCecchetto** [comment]
Bonjour Romain,

Merci pour votre proposition d'aide.
En réalité nous avons une repo en interne sur lequel nous avons "patché" les dépendances non encore compatible avec Kodi 19.
Normalement à cette heure-ci il ne reste plus que Youtube-DL qui n'est pas encore disponible sur le dépôt Matrix de la team Kodi (voir ici : https://github.com/ruuk/script.module.youtube.dl/issues/54).
En réalité il ne reste plus à Ruuk qu'à soumettre Youtube-DL sur le repo Matrix car ce dernier est compatible Python 3 depuis que ce PR a été accepté : https://github.com/ruuk/script.module.youtube.dl/pull/52.

D'un autre coté, nous envisageons dans peut de temps de supprimer la dépendance Youtube-DL afin de l'intégrer directement dans notre plugin en version "light".

En attendant, vous pouvez sans trop de difficulté installer notre plugin sous Kodi 19 en effectuant les quelques modifications suivantes :

1. Installer notre version patchée de Youtube-DL : https://github.com/Catch-up-TV-and-More/script.module.youtube.dl/tree/kodi19
2. Télécharger la dernière version de notre plugin ici : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/tree/dev et modifier le fichier `addon.xml` pour passer `xbmc.python` en version 3.0.0 afin qu'il soit installable sur Matrix.

Nous restons dispo si besoin 😉

**Comment by romainreignier** [comment]
Bonjour Sylvain,

Merci beaucoup pour cette réponse détaillée.
J'ai réussi à installé le plugin. Merci beaucoup.

Pour plus de détails sur l'installation au cas où d'autres personnes tombent dessus:
1. J'ai cloné le dépôt youtube.dl et copié tout le dépôt dans le dossier `~/kodi/addons`
2. J'ai cloné Catch-Up TV and More
3. J'ai modifier le fichier `addon.xml`
4. J'ai copié le dossier `plugin.video.catchuptvandmore` se trouvant à l'intérieur du dépôt git dans le dossier `~/.kodi/addons`
5. Dans l'interface l'interface de Kodi, je suis allé dans le gestionnaire d'extensions, mes extensions et dans l'extension youtube.dl, je l'ai activée
6. Dans l'extension Catch-Up TV, je l'ai activé mais j'ai eu une erreur. Dans les logs, il était question de modules Python manquants.
7. Dans l'extension Catch-Up TV, je suis allé dans les dépendances et j'ai installé toutes les manquantes en cliquant dessus
8. Cela fonctionne ! :)

**Comment by SylvainCecchetto** [comment]
Parfait alors Romain 😉 

Par contre, pour les personnes voulant tester cette méthode sur Kodi 19, il faut bien garder en tête que nous avons augmenté le numéro de version du plugin Youtube-DL que nous proposons sur le dépôt. Ce qui a pour conséquence que si le développeur de YouTube-DL propose une nouvelle version de son plugin sur le repo de Kodi mais que ce numéro de version est inférieur ou égal à la version de notre Youtube-DL patché alors Kodi ne mettra pas à jour le Youtube-DL de votre installation.

Cette méthode ne devrait être utiliser qu'en dernier ressort, sous entendu, que dans el cas où la seule version de Kodi que vous pouvez installer sur votre appareil est la version 19 (comme sur tvOS par exemple). En effet, si vous avez le choix, restez en Kodi 18 qui est à l'heure actuelle bien plus stable que le version 19.

Nous allons faire le nécessaire pour proposer officiellement et dès que possible une version officielle de Catch-Up TV & More pour Kodi 19 sur les repos officiels mais pour l'instant Kodi 18 doit rester LA version à utiliser par les utilisateurs finaux et pour une installation en "prod".

**Comment by romainreignier** [comment]
Merci pour les précisions Sylvain.
Une fois la version officielle de youtube.dl avec le support de Kodi 19 sortie, si jamais tu penses à le signaler ici, ça peut être pratique ;)
