### ISSUE TITLE
Catch-up videos aired on the same day are not sorted correctly

### ISSUE THREAD

**Issue by thombet** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#302]
### Describe the bug
When several episodes of the same show were aired on the same day, the catch-up TV episodes are sorted in the wrong order. This use case is pretty uncommon so I don't know if it occurs for several channels but at least I encountered the bug on France 2.

### To Reproduce
Go in Replay TV -> France -> France 2 -> Jeux & Divertissements -> N'oubliez pas les paroles -> Replay. For each day there are 2 episodes.

### Expected behavior
When sorting by date, the order follows the original aired date and time.

### Actual behavior
When sorting by date, the first episode listed is always the one that was aired last.

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: OSMC
 - Kodi version: Kodi Leia v18.3
 - Catch-up TV & More version: 0.2.20
 - Installation method: Catch-up TV & More repo

### Additional context
I wanted to submit a pull request to fix the issue but I was not able to find a solution...
Here is what I have found:

I think the issue comes from [this line](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/eb5595cb7881425022d5e45e4bd7388f1f07c829/plugin.video.catchuptvandmore/resources/lib/channels/fr/francetv.py#L489): the date saved in `item.info.date` contains only the date and the time is stripped.
Actually it was probably done like this because it seems Kodi does not support a date which includes time as per [the documentation](https://codedocs.xyz/xbmc/xbmc/group__python__xbmcgui__listitem.html#ga0b71166869bda87ad744942888fb5f14).
I think `item.info.date` is provided by CodeQuick and since I am not familiar with this library I can't tell if it offers a way to deal with this issue.

Maybe a solution then would be to retrieve the list of videos with the sort criteria `begin_date:asc` instead of `begin_date:desc` to ensure the video that was aired first is also processed first. I was not able to make it work though (I don't know if it is because "asc" is a wrong value or because the sorting simply does not work) so I cannot tell if it is bad idea :)

And one improvement idea: maybe it would be better to use `video['content_has_medias'][0]['media']['begin_date']` for the date rather than `video['first_publication_date']` to ensure the date used is the actual aired date (in case the video is not published the same day as it was aired for instance).

**Comment by SylvainCecchetto** [comment]
Thank you very munch for this **complete** bug report!
i will try to reproduce this issue shortly and will try your idea to fix the bug.

**Comment by SylvainCecchetto** [comment]
Commit https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/49836de91d92c3af19a5cccfc0fe5c0a1d5335f0 should fix your issue.

This commit will be available in 0.2.22~beta04, can you try this modification to confirm or not that this is what you want?

Thank you 😉

**Comment by thombet** [comment]
I confirm it works, thanks!

I don't understand how it works though :) You use `video['content_has_medias'][0]['media']['begin_date']` if it exists but only the year, the month and the date are extacted which means 2 items will have the same value. How are they eventually sorted in the right order? Is it thanks to the Kodi sort method `xbmcplugin.SORT_METHOD_UNSORTED`?

**Comment by SylvainCecchetto** [comment]
Yes it works thanks to the Unsorted method. 
With this one, Kodi sorts vidéo in the same order of the JSON from France TV API. This is why the order is correct. 

Unfortunately, we can’t specify time for video date. Only the day 😕

**Comment by thombet** [comment]
Ok now I understand.
Thank you for the information and thank you again for fixing it 😉
