### ISSUE TITLE
Ajouter le/les URL pour accéder directement au listing des replays dans la documentation du plugin

### ISSUE THREAD

**Issue by Dobi-Dev** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#304]
Bonjour,

J'ai installé depuis un petit moment ce plugin qui est pas mal du tout.
Je souhaiterais cependant pouvoir avoir accès directement à partir du menu principal de kodi à la liste des replays (FR dans mon cas) sans devoir faire passer par tous les menus intermédiaires.
Pourriez-vous indiquer (et me donner au passage) l'URL commençant par plugin://plugin.video.catchuptvandmore/[?????] ?
Il pourrait être intéressant d'avoir la liste pour le live TV (même si cela fonctionne déjà avec IPTV Recorder pour cela).

Bon weekend !

**Comment by SylvainCecchetto** [comment]
Bonjour Dobi-dev 😉 

Je ne sais pas si ma solution peut vous convenir, mais si vous n'utilisez pas les Replay des autres pays vous pouvez les masquer un à un (sauf la France). Pour masquer un menu il suffit de faire clic droit et "Masquer". Normalement, s'il ne reste plus que le Menu "France" dans Replay TV, alors Kodi va automatiquement ouvrir le menu "France" quand vous ouvrirez le menu "Replay TV".

A confirmer mais normalement on avait cette fonctionnalité avant ;-)

Si cette solution n'est pas la bonne, je vais regarder pour l'URL de Replay FR ;-)

**Comment by Dobi-Dev** [comment]
Je n'ai pas testé cela car je souhaiterais pouvoir lancer la liste des replays directement depuis le menu principal (et donc sans devoir passer par le menu des extensions, puis aller chercher le plugin "CatchUp TV And More" puis cliquer sur Replay).
J'ai fini sans trop de difficulté par trouver un lien valide pour afficher cet écran : 
`plugin://plugin.video.catchuptvandmore/resources/lib/main/generic_menu/?item_id=fr_replay`
Pour tester, il suffit de mettre la ligne suivante dans service.py : 
`xbmc.executebuiltin('ActivateWindow(10001, "plugin://plugin.video.catchuptvandmore/resources/lib/main/generic_menu/?item_id=fr_replay", return)')`
à la place de la ligne existante qui sert à lancer le plugin au lancement de kodi.

Cela affiche bien la liste des replays FR directement, cependant si on fait back pour revenir en arrière, j'obtiens l'erreur : 
`FATAL: [Catch-up-TV-&-More.support] generic_menu() takes exactly 2 arguments (1 given)
                                            Traceback (most recent call last):
                                              File "C:\Users\EugenSystems\Desktop\Kodi\portable_data\addons\script.module.codequick\lib\codequick\support.py", line 292, in run_callback
                                                results = route.function(parent_ins, **self.callback_params)
                                            TypeError: generic_menu() takes exactly 2 arguments (1 given)`

Pensant que j'avais mal rempli les paramètre de ActivateWindow, j'ai activé le skin `skin.aeon.nox.silvo` puis je me suis bêtement rendu compte qu'il permettait de générer automatiquement le lien vers la page des replays et j'obtiens alors :
`plugin://plugin.video.catchuptvandmore/resources/lib/main/generic_menu/?_pickle_=80027d71002858070000006974656d5f69647101580900000066725f7265706c6179710255075f7469746c655f710358060000004672616e63657104752e`
Dans le menu principal, je clique sur mon menu Replay, ça m'affiche correctement les replays FR mais si je fais back, j'obtiens de nouveau la même erreur.

Ne connaissant pas du tout codequick, je suis pour le moment bloqué ^^

**Comment by SylvainCecchetto** [comment]
Ah pour le problème du `takes exactly 2 arguments (1 given)` je vais faire un essai. J'avoue que je n'avais jamais essayé de lancer le plugin directement avec execbuiltin.

Sinon en solution native vous pouvez ajouter le dossier "Replay FR" aux favoris de Kodi ?

**Comment by Dobi-Dev** [comment]
Effectivement, en ajoutant Replay FR aux favoris de Kodi, j'obtiens un accès plus direct au Replay (et sans avoir d'erreur).

**Comment by SylvainCecchetto** [comment]
Chez moi, en mettant `xbmc.executebuiltin('ActivateWindow(10025, "plugin://plugin.video.catchuptvandmore/resources/lib/main/generic_menu/?item_id=fr_replay", return)')` dans le fichier `service.py` j'ai bien le replay FR qui s'ouvre au démarrage de Kodi.

Ce n'est pas votre cas ?

**Comment by Dobi-Dev** [comment]
Si, mais le soucis est quand je fais "back" (ou les 3 petits points sur le skin par défaut). Dans ce cas, j'ai l'erreur mentionnée.

**Comment by SylvainCecchetto** [comment]
Hum, je n'ai pas ça.

Voici mon fichier `service.py`:

```python3
from kodi_six import xbmcaddon
from kodi_six import xbmc

def autorun_addon():
    if xbmcaddon.Addon().getSettingBool("auto_run"):
        xbmc.executebuiltin('ActivateWindow(10025, "plugin://plugin.video.catchuptvandmore/resources/lib/main/generic_menu/?item_id=fr_replay", return)')
    return

autorun_addon()
```

Quand je lance Kodi, j'arrive directement sur le menu des Replay FR (avec les items TF1, France 2, France 3, etc).
Mais je n'ai pas les 3 petits points (je suis avec le skin par défaut) et si je fais back je reviens simplement sur l'accueil de Kodi.

**Comment by Dobi-Dev** [comment]
Alors, c'est étrange, je viens de voir que quand je fais back en utilisant un des boutons de la souris, je n'ai pas d'erreur.
Par contre, quand je clique sur les 2 petits points qu'on peut voir en haut du screen, j'ai bien l'erreur :
![image](https://user-images.githubusercontent.com/65083048/83058268-65943780-a058-11ea-849c-2009c7c7f2db.png)

**Comment by SylvainCecchetto** [comment]
Ah étrange ; je n’ai pas les petits points moi. 
C’est quelle version de Kodi et du plugin ?

**Comment by Dobi-Dev** [comment]
Kodi 18.6
Plugin 0.2.20 (installé depuis Kodi directement).

**Comment by SylvainCecchetto** [comment]
Je n'arrive pas à avoir ces 3 petits points ... C'est sur quel OS ?

**Comment by Dobi-Dev** [comment]
Windows 10 !

**Comment by SylvainCecchetto** [comment]
Peut être que cela explique la différence... je ne sais pas. Perso je suis sous macOS.
@wwark est sous Linux je crois, peut être pourra-t-il tester à l'occasion ?

Dans tous les cas, je ne vois pas trop comment faire autrement pour afficher les Replay FR au démarrage de Kodi que de remplacer la ligne 

```python
xbmc.executebuiltin('RunAddon(plugin.video.catchuptvandmore)')
```

par

```python
xbmc.executebuiltin('ActivateWindow(10025, "plugin://plugin.video.catchuptvandmore/resources/lib/main/generic_menu/?item_id=fr_replay", return)')
```

**Comment by Dobi-Dev** [comment]
J'ai pu tester sous Librelec (mais pas avec le skin de base) et j'ai reproduit le problème avec le skin que j'utilise et qui permet de mettre facilement le replay FR sur l'écran d'accueil : Aeon Nox: SiLVO

A noter que le problème est le même avec ce skin sous Windows.

Pour reproduire le soucis, il suffit d'installer le skin, d'aller dans les réglages -> Interface -> Configurer l'habillage -> Configurer le menu principal -> faire le "+" sur une ligne à gauche, aller à droite, cliquer sur la première ligne et aller chercher l'emplacement du menu de replay FR, puis renommer la seconde ligne en "Replay".
Valider tout ça et retourner sur le menu principal.
Cliquer sur le menu de replay qui a été créé puis cliquer sur les petits points pour revenir en arrière.

**Comment by SylvainCecchetto** [comment]
Merci pour la procédure, je viens de le faire sur mon mac et je n'ai toujours pas les petits points :-/
(voir le GIF)

![Jun-02-2020 11-43-26](https://user-images.githubusercontent.com/11562279/83505616-4ec16b00-a4c6-11ea-82fe-d6ada4f7d371.gif)

**Comment by Dobi-Dev** [comment]
Ok, j'ai cherché un peu et il y a une option (peut être désactivée par défaut sur Mac) qui permet d'afficher/masquer les petits points : 
Settings -> media -> general -> disable show parent folder items

**Comment by SylvainCecchetto** [comment]
Hello !
Merci pour les recherches, c'était bien ça. Je pense que j'avais touché à ce réglage peut être un jour ...

Du coup pour revenir au problème initial, avez-vous la possibilité d'essayer avec le commit https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/4d40f742ee96745bc59e6bd7a97c39fbd6f3545c si le problème disparait ?

Merci

**Comment by Dobi-Dev** [comment]
Oui, ce commit fix bien le problème.

Merci beaucoup !

Sinon, dois-je fermer le ticket ou sera t-il fermé lorsque ce commit sera mergé dans la branche master ?

**Comment by SylvainCecchetto** [comment]
Ah super alors !
Je vais le fermer. Ce fix sera disponible dans la version 0.2.22 du plugin.
