### ISSUE TITLE
Chaine de TV Ethiopienne

### ISSUE THREAD

**Issue by Cebyll** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#305]
### Content description

* Name: Ethiov
* Type [e.g. TV channel, Catch-up TV, Website, Radio]: TV channel
* Website URL: https://ethiov.com/live-channels
* Content language/country: Anglais/Ethiopie

### Content access

- [ ] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [ ] This content is geographically restricted

### More information

Bonjour,
Merci pour tous le travail que vous réalisez.
Serait-il possible de rajouter ces chaines issues du site Ethiov ?

**Comment by SylvainCecchetto** [comment]
Merci Cebyll et merci pour cette proposition,

Ces chaines sont elles également diffusées à la télévision ou bien seulement sur internet ? (Je veux dire, doivent-elles plutôt être placées dans la catégorie "Website" ou bien plutôt "Live TV" --> "Ethiopie".

Merci

**Comment by Cebyll** [comment]
Bonjour,
Ce sont des chaînes qui sont diffusées à la télévision.

Merci d'avance de la part de toute la communauté éthiopienne française car aujourd'hui c'est vraiment compliqué de regarder ces chaînes (a part sur les sites web).

J'ai aussi trouvé cette sources, où on retrouve les même chaîne que l'autre site, sauf qu'il y a en plus cette chaîne Kana TV, https://www.ethiovisit.com/videos/kana-tv/5767/
S'il y a possibilité de la rajouter  aussi.

**Comment by SylvainCecchetto** [comment]
Mais si je comprends bien ces deux sites ne sont pas les sites "officiels" des différentes chaines ?
N'y a t'il pas moyen d'accéder au Direct TV des différentes chaines directement sur leurs sites respectifs ? (Comme France.tv pour les chaines francetélévision en France ?)

Je pose cette question car nous ne souhaitons pas, à travers ce plugin, mettre à disposition des chaines TV par exemple payantes, de façon gratuite. Comme je ne connais pas du tout les chaines Ethiopiennes ...

**Comment by martindoublem** [comment]
Le live stream pour cette dernière ne semble pas être disponible pour l'instant:
[https://kanatelevision.com/en/kana-tv-live-stream)](https://kanatelevision.com/en/kana-tv-live-stream)

**Comment by wwark** [comment]
Hello,
Tu peux te baser sur les pages wiki https://en.wikipedia.org/wiki/Television_in_Ethiopia
Par exemple https://en.wikipedia.org/wiki/Fana_TV tu as le lien vers le site web officiel, le live TV est présent https://www.fanabc.com/%e1%89%80%e1%8c%a5%e1%89%b3-%e1%88%b5%e1%88%ad%e1%8c%ad%e1%89%b5/

Merci,

**Comment by Cebyll** [comment]
J'ai regardé pour faire le lien avec le site des chaines et le site ethiov.com: la sources de la vidéo est la même. 

Par exemple pour **ECTV**, le site web officiel avec la page du live : http://www.yeethiopialijoch.com/live.php#content
Si on cherche dans la source de la pages, dans le flux réseau on arrive à retrouver la source de la vidéo : http://video2b.vixtream.net/tv/v/ectv
Pour le site Ethiov https://ethiov.com/single-channel/629 , en regardant de nouveau  la source et le flux réseau, on retombe sur le même fournisseur de contenu : https://video2b.vixtream.net/tv/v/ectv

Si je fait la même chose pour la chaîne suivante: **Amhara TV** 
Site web de la chaine : https://amharaweb.com/english/live/
Flux vidéo : https://video2b.vixtream.net/tv/v/amma
Sur le site Ethiov : https://ethiov.com/single-channel/113
Flux vidéo : https://video2b.vixtream.net/tv/v/amma

Chaîne suivante : **FANA TV**
Site web de la chaîne : https://www.fanabc.com/%E1%89%80%E1%8C%A5%E1%89%B3-%E1%88%B5%E1%88%AD%E1%8C%AD%E1%89%B5/
Flux vidéo : https://video2b.vixtream.net/tv/v/fbctv&noauto
Sur le site Ethiov : https://ethiov.com/single-channel/114
Flux vidéo : https://video2b.vixtream.net/tv/v/fbctv

Chaîne suivante : **Walta TV**
Site web de la chaîne : http://waltatv.et/livestreaming/
Flux réseau : affiche ERROR: TV channel walta not found
Sur Ethiov https://ethiov.com/single-channel/567
Flux réseau : ERROR: TV channel walta not found
Et si je rentre l'adresse du flux réseau qui devrait être : https://video2b.vixtream.net/tv/v/walta on obtient le même message d'erreur ERROR: TV channel walta not found

Chaine suivante : les chaines **EBC**, pas trouver le site officiel
Flux video sur le site Ethiov : https://video2b.vixtream.net/tv/v/etvz

Ce que j'en conclu : 
Les sites officiels des chaines diffusent à partir d'un même fournisseur de contenu http://video2b.vixtream.net/
Ethiov ce fournit au même endroit.
Donc j'imagine que Ethiov fait le même travail que **Catchup TV And More**, il centralise les flux vidéo et met à disposition de manière centralisé.

Et pour Kana TV https://kanatelevision.com/en/kana-tv-live-stream où le live n'est pas encore mis a disposition, j'imagine qu'il n'ont pas encore mis à jours vers le flux du site http://video2b.vixtream.net/ qui se trouve à https://video2b.vixtream.net/tv/v/kana

Dites moi ce que vous en penser.

**Comment by SylvainCecchetto** [comment]
Wah quel boulot ! Merci pour toutes ces recherches. On va regarder tout ça

**Comment by SylvainCecchetto** [comment]
Je viens d'ajouter les chaines du site ethiov.com ; il manque encore les différents logo mais ça viendra après.

Les changements devraient être disponible dans la version 0.2.22~beta07 du plugin. A l'occasion pourrez vous faire un petit test pour voir si ça fonctionne bien ?

Bien entendu, j'ai ajouté toutes les chaines mais les chaines qui ne sont pas dispo sur le site ne le sont pas non plus dans Kodi...

Commit : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/3a2408e033a982eb8329443f05e10f7410056748

**Comment by Cebyll** [comment]
J'ai essayé, et ça fonctionne :)
Il y a des heures ou ça lag bien et d'autre ou c'est un peu mieux. Ça doit venir de ma connexion ou du flux vidéo car j'ai fait le test en parallèle sur le PC, et ça se bloque au même moment.

En tous cas merci et bravo encore pour la réactivité.

**Comment by SylvainCecchetto** [comment]
Parfait alors ! Merci pour les tests et pour la proposition d'ajout 😉
