### ISSUE TITLE
Can't play any UKTV play content

### ISSUE THREAD

**Issue by LuckyEddie47** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#306]
Steps to reproduce the behaviour:
1. Install from https://repo.cecchettosylvain.fr/zip
2. Configure with UN & PW created on UKTV play website.
3. Browse to any video under UK > UKTV and select play.

### Expected behaviour
Content should play.

### Actual behaviour
Kodi 'wait' spinner runs until I exit the plugin by going Home.

### Your environment
 - [ ] Linux

 - Operating system version/name: OSMC 2020.03-1 (current)
 - Kodi version: 18.6 2020.03.20
 - Catch-up TV & More version: 0.2.21
 - Installation method: From repo https://repo.cecchettosylvain.fr/zip

### Additional context
Content from other providers within plugin plays OK.

### Debug log
Full debug log at https://paste.osmc.tv/pikowohaha

**Comment by wwark** [comment]
Hi,

You have an issue with the configuraiton of the VPN.

> 2020-05-25 11:55:19.653 T:2745414368   FATAL: [Catch-up-TV-&-More.support] 'Connect/Disconnect VPN'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/codequick/support.py", line 319, in run_callback
                                                redirect = parent_ins._process_results(results)
                                              File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/codequick/route.py", line 95, in _process_results
                                                raw_listitems = validate_listitems(raw_listitems)
                                              File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/codequick/route.py", line 34, in validate_listitems
                                                raw_listitems = list(raw_listitems)
                                              File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/main.py", line 129, in generic_menu
                                                item_infos=item_infos)
                                              File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/menu_utils.py", line 260, in add_context_menus_to_item
                                                add_vpn_context(item)
                                              File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/vpn.py", line 270, in add_vpn_context
                                                item.context.script(vpn_item_callback, Script.localize(LABELS['Connect/Disconnect VPN']))
                                            KeyError: 'Connect/Disconnect VPN'

**Comment by LuckyEddie47** [comment]
Hi Wwark, 
Thanks for the quick response. I have the vpn feature disabled as I'm in the UK and only trying to access UK content.

**Comment by wwark** [comment]
OK did you have some settings on VPN meanwhile it is desactivated ?
Could you please try to activated and leave blanck the configuration ?
Wwark

**Comment by LuckyEddie47** [comment]
I didn't change any vpn settings from install. Only the path was set to /usr/bin. I've just tried setting it to /dev/null and using the Delete OpenVPN settings file option. Then tried with vpn enabled and again with it disabled. No difference.

**Comment by wwark** [comment]
Strange .... Could you please try another replay for another channel and share the logs if you have also the same issue ?

**Comment by LuckyEddie47** [comment]
Not sure if I made this clear, I'm talking about catch up, not live TV.
Under UK, Quest OD, STV & Bristol TV all play OK. Others show 'Resource no longer available' but only UKTV Play hangs.

**Comment by wwark** [comment]
Ok thank you for the confirmation. I talked about catchup-tv (replay in french sorry).
Maybe the error is not correct ....
Could you please activate the debug log in Kodi ? (Options -> system -> Logging -> Enable Debug Logging)
Reproduce the issue and share the new logs.

**Comment by LuckyEddie47** [comment]
Hi Marc, I enabled debug logging and rebooted. At first the issue seemed the same. For some reason I decided to time the 'waiting spinner'. I've found that playback does start if you wait between 1-2minutes (never less than a minute). This means my error report is null. Is this sort of playback delay typical?

**Comment by wwark** [comment]
Yes it can take more time we made different call to access to the content.
Thanks,
