### ISSUE TITLE
Plus d'accés au chaines du groupe M6

### ISSUE THREAD

**Issue by babagoul** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#307]
Bonjour,

Je n'ai plus aucun accès au chaines du groupe M6 depuis plus d'un mois alors qu'avant tout marchait parfaitement, j'utilise un raspberry pi 2 avec librelec et j'ai testé également sur windows en créant des nouveaux identifiant 6 play mais rien n'y fait je n'est plus accès au direct. Auriez vous connaissance de ce problème ?

Merci d'avance :)

**Comment by SylvainCecchetto** [comment]
Bonjour, malheureusement le problème vient du groupe M6 qui a récemment effectué des changements au niveau de leur architecture.
On en parle ici : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/300

**Comment by babagoul** [comment]
Ha d'accord merci de l'information, bon le problème vient pas de mon coté sa m'évitera de me prendre la tête pour savoir d'ou vient le problème, reste plus qu'a attendre et se tenir informé :)
