### ISSUE TITLE
Slovenian TV channels

### ISSUE THREAD

**Issue by martindoublem** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#308]
### Content description

* Name: SLO1, SLO2, SLO3, etc
* Type [e.g. TV channel, Catch-up TV, Website, Radio]: TV channels on m3u feeds
* Website URL: https://4d.rtvslo.si/zivo/tvs1
* Content language/country: Slovenian / Slovenia

### Content access

- [ ] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [ ] This content is geographically restricted

### More information

If you want to add more information, put it here:

I am available to help as I myself develop in python, it is just I am not sure what goes where in your plugin and therefore thought that opening a feature request would be a better call

**Comment by SylvainCecchetto** [comment]
Thank you for your request.

We added some RTVSLO channels in commit https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/0a9ca85ada3536623927351e3a86004cad2abff8.
The modification will be available in version 0.2.22~beta05 of the plugin.
Please can you check that everything is ok? (Missing channels, wring label, etc...) Slovania language is hard to understand for French people 😛 

Thank you!

BTW, we will add logo later.
