### ISSUE TITLE
M6 et W9 écran noir

### ISSUE THREAD

**Issue by crocketear** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#310]
Bonjour,
J'ai installé CatchUpTV&More + paramétrer mon compte 6Play + accepter l'installation de Widevine CDM et pourtant lorsque je lance M6 ou W9, j'ai bien le type de programme (info, durée, ...) mais l'écran reste désespérément noir, puis se déconnecte au bout de 30 secondes.
Je précise que je viens de complètement redémarrer mon instal de kodi sur mon Raspberry, donc pour l'instant les seuls addons sont ceux nécessaires à CatchUp.
Une soluce?
Merci d'avance,

**Comment by wwark** [comment]
Bonjour,

SI c'est le même problème que ce ticket alors pour l'instant on ne peut rien faire.
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/300

Merci,
Wwark

**Comment by crocketear** [comment]
Oui, oui, c'est exactement ça.

**Comment by wwark** [comment]
Merci pour votre confirmation.
Je clos ce ticket suivi dans l'autre ticket.
