### ISSUE TITLE
Replays videos donwloaded from France TV have no audio track

### ISSUE THREAD

**Issue by jmzambon** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#312]
### Describe the bug
A clear and concise description of what the bug is:
*All my attempts to download a replay video from France TV end with a video file without any audio track.
The same video can be played from the plugin directly without any trouble.*

### To Reproduce
*1. Go to plugin page -> Replay TV -> France -> France 3 -> Actualités & Sociétés -> Météo -> Replay
2. Pick up any show listed there
3. Press 'C' and choose "Download" ("Télécharger") and wait for download to finish
4. Play the downloaded file -> no sound.*

### Expected behavior
A clear and concise description of what you expected to happen:
*Video should be downloaded with audio track.*

### Actuel behavior
Tell us what happens instead:
*Video is downloaded without audio track. No sound at all.*

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: *Linux Mint 19.3*
 - Kodi version: *Kodi 18.7*
 - Catch-up TV & More version: *0.2.21*
 - Installation method: *official CUTV&M repository*

### Additional context
Add any other context about the problem here:
*french environment*

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):
*[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/4792710/kodi.log)*

**Comment by wwark** [comment]
Hi,
We are aware of this issue.
We used youtube-dl to download stream. The version is very old.
Could you please follow this procedure to see if the issue is still present.
https://catch-up-tv-and-more.github.io/fr/faq/#i-erreurs-li%C3%A9es-%C3%A0-youtube-dl
Sorry I haven't test it on my side for the moment.

Thanks,

**Comment by jmzambon** [comment]
Hi,
Thank you very much for your response.
I've tried the workaround, but it didn't solve the bug.
I found out the download link in the log and try "youtube-dl -F" on it. The output shows one "audio only" file and four "video only". Here is the full output, if it helps:
```shell
jmzambon@liliamint ~ $ youtube-dl -F https://cloudreplayfrancetv.akamaized.net/80c04da8c7ee5/231083247_monde_TA.ism/ZXhwPTE1OTI0Mzk5ODF+YWNsPSUyZjgwYzA0ZGE4YzdlZTUlMmYyMzEwODMyNDdfbW9uZGVfVEEuaXNtKn5obWFjPWRlMWE1ZDFmZGMwNzkzZGY4OWYyOTAxYjNiYzViNTM4Mzc1NjVhZGQzM2QyZmM2NGQ3OGNlMjg1MzI2YTdkNmM=/master.m3u8?hdnea=exp=1592418981~acl=%2f80c04da8c7ee5%2f231083247_monde_TA.ism*~hmac=de87575da2603d50048a4d7044762b5a33073cb296e59354419d8889a2e740f6
[generic] master.m3u8?hdnea=exp=1592418981~acl=/80c04da8c7ee5/231083247_monde_TA: Requesting header
[generic] master.m3u8?hdnea=exp=1592418981~acl=/80c04da8c7ee5/231083247_monde_TA: Downloading m3u8 information
[info] Available formats for master.m3u8?hdnea=exp=1592418981~acl=/80c04da8c7ee5/231083247_monde_TA:
format code                   extension  resolution note
audio-aacl-96-Audio_Français  mp4        audio only [fr] 
522                           mp4        384x216     522k , avc1.42C01E, 25.0fps, video only
1105                          mp4        640x360    1105k , avc1.4D401F, 25.0fps, video only
1582                          mp4        960x540    1582k , avc1.4D401F, 25.0fps, video only
2218                          mp4        1280x720   2218k , avc1.64001F, 25.0fps, video only (best)
```
Thank again for your help.

**Comment by wwark** [comment]
For the moment we don't a solution for this issue sorry.
If you download the video with youtube-dl do you have the sound or not ?
If we don't have a sound we will need to open a ticket on youtube-dl github.

**Comment by jmzambon** [comment]
It works fine with youtube-dl (without any option flag).

**Comment by SylvainCecchetto** [comment]
We use this snippet code to download a video:

```python
import YDStreamUtils
import YDStreamExtractor
YDStreamExtractor.disableDASHVideo(True)

url = "http://www.youtube.com/watch?v=_yVv9dx88x0"
vid = YDStreamExtractor.getVideoInfo(url,quality=1)
path = "/directory/where/we/want/the/video"

with YDStreamUtils.DownloadProgress() as prog: #This gives a progress dialog interface ready to use
    try:
        YDStreamExtractor.setOutputCallback(prog)
        result = YDStreamExtractor.downloadVideo(vid,path)
        if result:
            #success
            full_path_to_file = result.filepath
        elif result.status != 'canceled':
            #download failed
            error_message = result.message
    finally:
        YDStreamExtractor.setOutputCallback(None)
```

Source: https://forum.kodi.tv/showthread.php?tid=200877

Maybe the sound issue come from here

**Comment by jmzambon** [comment]
Hi (maybe we can continue in french if possible ? ;) ),

I think the problem lies in the last lines of YoutubeDLWrapper.py:
```python
    fd = downloader.get_suitable_downloader(info)(ytdl, ytdl.params)
    for ph in ytdl._progress_hooks:
        fd.add_progress_hook(ph)
    return fd.download(name, info)
```
By calling directly the *download* method of the downloader, the script bypass the merge mechanism implemented in *YoutubeDL.download*. There's no problem when the video file is unique. But when video and audio are splitted, that merge mechanism is needed.
This works fine because it doesn't bypass *YoutugeDL.download*:
```python
  [catchup download.py]
  [...]
  qualities = {0: 'worstvideo+bestaudio/worstvideo',
                 1: 'bestvideo[height<=720]+bestaudio/best[height<=720]/bestvideo+bestaudio/best',
                 2: 'bestvideo[height<=1080]+bestaudio/best[height<=1080]/bestvideo+bestaudio/best',
                 3: 'bestvideo+bestaudio/bestvideo'}
    params = {'format': qualities[get_quality_YTDL(download_mode=True)], 'outtmpl': outtmpl}
    bg = Script.setting.get_boolean('dl_background')
    if bg:
        downloader = YDStreamUtils.DownloadProgressBG
    else:
        downloader = YDStreamUtils.DownloadProgress
    try:
        with downloader(line1='Starting download...') as prog, YoutubeDLWrapper.YoutubeDLWrapper(params) as ydl:
            YoutubeDLWrapper._CALLBACK = prog.updateCallback
            ydl.add_progress_hook(ydl.progressCallback)
            ydl.add_default_info_extractors()
            res = ydl.extract_info(video_url, download=False)
            current_filepath = ydl.prepare_filename(res)
            ydl.process_ie_result(res)
  [...]
```
I dived into script.module.youtube.dl trying to understand how it works (takes time, as all this is absolutely new for me). Changes don't seem straightforward...

Thank again for your help.

**Comment by SylvainCecchetto** [comment]
Merci pour ce travail d'investigation !!

Ce serait donc `script.module.youtube.dl` qui utilise "mal" `youtube-dl` 😕 

Je vais essayer de mettre le nez dans le code rapidement 😉

**Comment by jmzambon** [comment]
Merci :D .
Si je peux aider d'une manière ou d'une autre, ce sera volontiers !

**Comment by wwark** [comment]
@SylvainCecchetto, si tu vois avec rukk ce point. Il faudrait lui parler aussi d'ajouter la possibilité de positionner le path du binaire ffmpeg pour pouvoir le positionner directement dans la configuration du plugin.
Il faudra aussi une évolution côté codequick.

Merci !

**Comment by SylvainCecchetto** [comment]
Hello wwark, j'avais complètement oublié cette issue, tu fais bien de le rappeler.

Il y a une option `--ffmpeg-location` dans youtube-dl, je ne pense pas que ce soit compliqué d'ajouter un paramètre lors de l'appel à `script.module.youtube.dl` afin de lui passer le chemin de ffmpeg ;-) (il faut juste ajouter ce support dans `script.module.youtube.dl`).
Je vais essayer cette semaine de regarder ces deux choses (le path de ffmpeg ainsi que le problème qu'a débusqué jmzambon afin de pouvoir (dans la mesure du possible) faire un seul PR à ruuk.

**Comment by jmzambon** [comment]
Bonjour,

Si ça peut aider, j'ai un code bêta fonctionnel ici : https://github.com/jmzambon/script.module.youtube.dl/tree/add_merge_capability.
J'ai testé pas mal, mais je manque quand même de "cas difficiles".
L'api actuelle fonctionne toujours, mais les changements proposés permettent une utilisation simplifiée, par exemple comme ceci pour le fichier download.py de CUTV&M :
```python
from __future__ import unicode_literals

from codequick import Script
from resources.lib.addon_utils import get_quality_YTDL
from resources.lib.kodi_utils import get_selected_item_label


def download_video(video_url):
    """Callback function of the 'Download' context menu

    Args:
        video_url (str): URL of the video to download
    """

    #  print('URL Video to download ' + video_url)

    #  Now that we have video URL we can try to download this one
    YDStreamExtractor = __import__('YDStreamExtractor')

    video_name = ''    
    if Script.setting.get_boolean('dl_item_filename'):
        video_name = get_selected_item_label()

    info = {'url': video_url, 'quality': get_quality_YTDL(download_mode=True)}

    path = Script.setting.get_string('dl_folder')
    result = YDStreamExtractor.handleDownload(
        info, bg=Script.setting.get_boolean('dl_background'), path=path, filename=video_name)
    if result:
        if result.status == 'canceled':
            error_message = result.message
            Script.log('Download failed: %s' % error_message)
        else:
            full_path_to_file = result.filepath
            Script.log('Download success: %s' % full_path_to_file)
            download_ok = True
    return False
```

**Comment by SylvainCecchetto** [comment]
Hello !
Hey mais tu as déjà fait tout le boulot alors 😜 
Si ton code fonctionne tu peux largement le proposer à ruuk via un PR request ?

**Comment by jmzambon** [comment]
Ok, je peaufine un peu et je le soumets. Merci ;-) .
Pour info, il sera également très aisé de passer le chemin vers ffmpeg le cas échéant.

**Comment by SylvainCecchetto** [comment]
Merci à toi !

Pour ffmpeg, feel free to implement it if you want 😜 💪

**Comment by jmzambon** [comment]
Voilà, c'est fait.

**Comment by SylvainCecchetto** [comment]
Super ! Merci beaucoup pour ton aide dans l'amélioration de CUTV en tout cas.
Par contre il faut juste être patient avec ruuk avant d'avoir des nouvelles ;-)

**Comment by wwark** [comment]
Merci Beaucoup !

**Comment by jmzambon** [comment]
Merci à vous surtout pour cet outil, dont je ne peux plus me passer ;) .
Je prends bonne note pour ruuk, c'est bon à savoir.

Si par ailleurs vous avez des petites choses à fixer qui ne sont pas trop complexes (je ne connais pas le monde de la vidéo), type "easy hacks", je contribuerais avec plaisir... :blush:

**Comment by wwark** [comment]
Hello @jmzambon, 
Maintenant la plupart des flux France TV sont au format DASH (certain DRM, d'autres non)
On va pouvoir tester l'évolution dans yt-dl pour vérifier si la donnée peut être télécharger avec un format dash (mdp).

Merci,

**Comment by joaopa00** [comment]
Est-ce que le problème est résolu?

**Comment by jmzambon** [comment]
Je viens de tester, ça me paraît en ordre.

**Comment by joaopa00** [comment]
Merci pour le retour. Je ferme alors.
