### ISSUE TITLE
No sound for Cameroun CRTV online TV

### ISSUE THREAD

**Issue by toonemastic** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#313]
### Describe the bug
No sound with Online TV Cameroun CRTV or CRTV-News. 

### To Reproduce
1. Select "TV en direct"
2. Select "Cameroun"
3. Select "CRTV"
4. Video streaming OK but no sound

### Expected behavior
Have sound
### Actuel behavior
No sound
### Screenshots
N/A
### Your environment
 - OSX
 - Raspberry-Pi

 - Operating system version/name:
 - Kodi version: 18.6
 - Catch-up TV & More version: 
latest beta from your repo, also tested with official Kodi repo 
 - Installation method: from Kodi repo (release) and from your repo (beta)

**Comment by SylvainCecchetto** [comment]
Hi. Thank you for your bug report. 
Can you try if you have sound on the same Live TV directly on the official website of the channel? (Currently on my cellphone). 
If there is no audio on the official website we can’t do anything, else we will check that 😉

**Comment by toonemastic** [comment]
Hello,

Thanks for the top. There is also no sound on the web site : http://www.crtv.cm/live-crtv/ and http://www.crtv.cm/live-crtvnews/

Regards,

Pierre
