### ISSUE TITLE
ERROR: ffmpeg[7FA69347A700]: [hls,applehttp] Error when loading first segment

### ISSUE THREAD

**Issue by koanya** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#314]
### Describe the bug
Plusieurs chaînes FR ne fonctionnent pas en replay et en direct. Aucune vidéo ne se lance et aucun message d'erreur n'apparaît dans l'interface de kodi. J'ai le même message d'erreur dans le fichier log en replay et en direct : ERROR: ffmpeg[7FA69347A700]: [hls,applehttp] Error when loading first segment 
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/4810018/kodi.log)

J'ai testé plusieurs chaînes : 
- TF1, FR2, FR3, FR4, FR5, Arte, TFX ne fonctionnent pas
- C8, l'equipe, public senat et M6 (uniquement replay) fonctionnent

Comme je ne regarde vraiment pas souvent la télé, ça doit faire au moins plusieurs mois que je n'avais pas utilisé ce plugin. Je ne sais donc pas depuis quand j'ai ce bug, la dernière fois que je l'avais utilisé tout fonctionnait.

Dites-moi s'il vous faut plus d'info.
Merci

### Your environment
 - Operating system version/name: Archlinux
 - Kodi version: 18.7.1
 - Catch-up TV & More version: 0.2.23~beta00 (j'ai testé également avec la version 0.2.22 et j'ai le même problème)
- ffmpeg : 4.3

**Comment by wwark** [comment]
Bonjour,
ON pourrait avoir les logs pour les autres chaines ?
Si possible avoir le log en mode debug pourrait aider.

Merci,
Wwark

**Comment by koanya** [comment]
Bonjour Wwark,
 
Voici le log pour d'autres chaînes en direct. Dans l'ordre : TF1 (NOK), FR2 (NOK), C8 (OK), TMC (NOK), l'equipe (OK); Public Senat (OK), TFX (NOK) et Gulli (NOK). J'ai activé les debug Ffmpeg, Video, et PVR.
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/4810196/kodi.log)
Si y a besoin de tester plus de chaînes, dites-le moi.
Merci

**Comment by wwark** [comment]
Merci pour ces tests et logs.
Le problème est au niveau du lecteur video de Kodi. Il faudrait ouvrir un ticket de support pour Kodi de votre distribution linux et fournir le log.

**Comment by koanya** [comment]
Je vais voir du côté de Kodi alors. Merci pour l'investigation.
