### ISSUE TITLE
Grille TV qui ne se met pas à jour

### ISSUE THREAD

**Issue by Lilynette** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#316]
### Describe the bug

La Grille TV est bloquée au 21/06/20 à 21h et la description des chaînes ne se met pas à jour. 

### To Reproduce

1. Démarrer Kodi
2. Dans l'onglet "TV" : aucune information présente

### Expected behavior

Normalement les informations devraient remonter automatiquement

### Actuel behavior

Rien ne s'affiche

### Screenshots

[Menu chaîne TV](http://image.noelshack.com/fichiers/2020/26/1/1592827940-menu-chaines-tv.jpg)
[Menu Guide TV](http://image.noelshack.com/fichiers/2020/26/1/1592827944-menu-guide-tv.jpg)

### Your environment

 - Raspberry-Pi : LibreELEC ver.9.2.1 (RPi4.arm)
 - Operating system version/name:
 - Kodi version: Leia v18.6
 - Catch-up TV & More version: 0.2.22
 - Youtube-dl control  : 20.324.0
 - Pvr Iptv Simple Client : 3.9.8.1
 - Installation method: suivi de la procédure d'installation sur votre site. Tout fonctionnait normalement avant ce matin

### Additional context

J'ai vérifier toutes les mise à jours, l'accès au dossier m3u et au site pour récupérer les ifnormations du programme TV est fonctionnel.
Lorsqu'on sélectionne une chaîne, elle se lance bien avec le bon programme. Il n'y a juste plus d'affichage du contenu des chaînes en direct.

**Comment by SylvainCecchetto** [comment]
Bonjour et merci pour l'ouverture de ce ticket.

En effet c'est une erreur de ma part, il y a eu des problèmes avec le script qui génère les programmes TV XMLTV dernièrement. J'avais normalement fixé ce problème avant le week end mais j'ai oublié de décommenter dans le scrip l'appel à la fonction qui synchronise les guides TV sur GitHub -_-'.

Logiquement cela devrait rentrer dans l'ordre dans les 2/3 jours à venir.

Je laisse ce ticket ouvert en attendant 😉

**Comment by Lilynette** [comment]
Parfait ! merci beaucoup pour l'info ^^

Bonne journée ! 😄

**Comment by SylvainCecchetto** [comment]
Pas de problème, bonne journée également !

Note à moi-même : https://github.com/Catch-up-TV-and-More/xmltv/issues/5

**Comment by SylvainCecchetto** [comment]
Bonjour Lilynette,
Normalement le guide TV devrait fonctionner à nouveau, vous confirmez ?

**Comment by SylvainCecchetto** [comment]
Parfait alors. Merci beaucoup. Et n'hésitez pas à ouvrir une issue à nouveau si besoin, j'avoue que je ne contrôle pas souvent les guides TV ... 😛
