### ISSUE TITLE
Impossible d'installer le plugin

### ISSUE THREAD

**Issue by ticmaroc** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#318]
### Describe the bug
Bonjour, 
Il m'est impossible d'installer le plugin sur SPMC ( Kodi Jarvis)
Quand je clique sur video's addons via le dépôt officiel, je ne trouve aucun add-on à installer.
Quand j'essaie d'installer directement le plugin depuis Github (https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/releases/tag/v0.2.22) , une notification s'affiche et disparaît tout de suite après.

Dans le Log des événements, je trouve :
The dependency on resource.images.catchuptvand more version 1.0. could not  be satisfied.
Add-on is incompatible or has been marked broken in repository.
Dependencies not met. Please contact add-on author.

**Comment by SylvainCecchetto** [comment]
Bonjour,

Cela fait un bon moment que le plugin n'est plus mi à jour pour Jarvis. La dernière version stable de Kodi est Kodi Leia (Kodi 18). Jarvis c'est Kodi 16 O_O.

Je vous conseil de mettre à jour votre Kodi plutôt, car la dernière version dispo du plugin pour Jarvis existe bien mais il ne doit plus y avoir beaucoup de chaines qui fonctionnent...

**Comment by SylvainCecchetto** [comment]
Je ferme le ticket, on peut ré-ouvrir si besoin 😉
