### ISSUE TITLE
Low resolution during TV watching

### ISSUE THREAD

**Issue by Vdauphin** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#319]
### Describe the bug
Direct streaming and replay are in low resolution (looks like in 240p). 

### To Reproduce
1. select "TV en direct" or Replay TV
2. select France 
3. select "France 5" or any other

### Expected behavior
I expect to watch in full resolution (like 720p)

### Actuel behavior
Low resolution

### Screenshots
![Capture d’écran de 2020-07-01 20-15-11](https://user-images.githubusercontent.com/14364400/86277796-9deae080-bbd7-11ea-98b2-e9ce5f73473e.png)

### Your environment
 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: Ubuntu 20.04
 - Kodi version: 18.6 Debian package version: 2:18.6+dfsg1-2ubuntu1 Media Center Kodi from Debian
 - Catch-up TV & More version: 0.2.22
 - Installation method: from Kodi Add-On repository

### Additional context
This issue doesn't appear on my Windows 10 (dual boot)
This issue didn't appear in my previous Ubuntu 18.04.
The issue appear just after installing Ubuntu 20.04 (fresh install). 

### Debug log
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/4859720/kodi.log)

**Comment by wwark** [comment]
Hi,

During playing the stream, could you please verify you can choose bitrate maybe you can choose better qualify like below

![Screenshot from 2020-07-01 21-00-23](https://user-images.githubusercontent.com/469461/86281538-ff15b280-bbdd-11ea-85a6-8a384325af04.png)
![Screenshot from 2020-07-01 21-00-28](https://user-images.githubusercontent.com/469461/86281549-0472fd00-bbde-11ea-869c-d6cca2d2ab00.png)

Thanks,

**Comment by Vdauphin** [comment]
Thank you, it is working
Didn't know you can select the bitrate :/
My bad
Thanks again!

**Comment by wwark** [comment]
Not all stream provide it. It depends of the stream.
Some can provide also different languages like the live stream of France TV good for abroad contents.
