### ISSUE TITLE
Erreur au lancement de catch-up tv 

### ISSUE THREAD

**Issue by 3th0** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#32]
Bonjour,

Tout d'abord merci pour ce plugin, il s'avère très utile !

Néanmoins il ne veut plus se s'éxécuter. L'erreur extraite des logs est la suivante : 

`14:29:02.282 T:3885757424  NOTICE: script.module.youtube.dl: youtube_dl core version: 2017.05.18.1
14:29:02.362 T:3885757424   ERROR: /home/osmc/.kodi/addons/script.module.youtube.dl/lib/YDStreamExtractor.py:453: UserWarning: External use of disableDASHVideo() is deprecated. It is now handled by module settings
                                              warnings.warn("External use of disableDASHVideo() is deprecated. It is now handled by module settings")
14:29:02.365 T:3885757424   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'hash'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 49, in <module>
                                                _ = common.ADDON.initialize_gettext()
                                              File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 756, in initialize_gettext
                                                raw_strings_hash != ui_strings_map['hash']):
                                              File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 187, in __getitem__
                                                return self._storage[key]
                                            KeyError: 'hash'
                                            -->End of Python script error report<--
14:29:02.606 T:4113506304   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/
14:29:02.607 T:4113506304   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/) failed
`

J'ai la même erreur sur la 0.1.3 et les releases de dev (0.1.5-beta09 / 0.1.5-beta011). J'ai essayé de downgrader le module youtube-dl control afin d'être sur la version 17.518.2 et j'ai testé avec plusieurs releases de CaptchupTv et je constate toujours le même problème avec youtube-dl control en version 17.709.0 :

`
14:37:07.026 T:3482842096  NOTICE: script.module.youtube.dl: youtube_dl core version: 2017.07.09
14:37:07.123 T:3482842096   ERROR: /home/osmc/.kodi/addons/script.module.youtube.dl/lib/YDStreamExtractor.py:453: UserWarning: External use of disableDASHVideo() is deprecated. It is now handled by module settings
                                              warnings.warn("External use of disableDASHVideo() is deprecated. It is now handled by module settings")
14:37:07.127 T:3482842096   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'hash'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 49, in <module>
                                                _ = common.ADDON.initialize_gettext()
                                              File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 756, in initialize_gettext
                                                raw_strings_hash != ui_strings_map['hash']):
                                              File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 187, in __getitem__
                                                return self._storage[key]
                                            KeyError: 'hash'
                                            -->End of Python script error report<--
14:37:07.363 T:4113506304   ERROR: GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/
14:37:07.364 T:4113506304   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/) failed
`

Mon installation d'osmc est en version : 17.5

Comment puis-je contourner ce problème ? 
Cordialement

**Comment by wwark** [comment]
Bonjour,

Merci et c'est cool que ce plugin est utile !
Le problème a été remonté dans l'issue #27 et il y a un contournement décrit dans les échanges.

Nous n'avons pas encore trouvé la cause de ce problème lié à la librairie "simpleplugin" utilisé dans ce plugin. 

Nous aurons besoin d'informations qui permettraient de pouvoir reproduire le problème pour le corriger.

Cordialement,
Wwark

**Comment by wwark** [comment]
Je ferme cette issue comme identique à #27.
