### ISSUE TITLE
Récupération de flux francetelevisions après expiration du délai de disponibilité

### ISSUE THREAD

**Issue by abolibibelot1980** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#320]
Je viens de découvrir cette extension en faisant une recherche sur l'adresse de chargement de la liste des émissions disponibles via l'interface dite de rattrapage des chaînes francetelevisions.fr.

J'utilise actuellement Captvty pour charger la liste des émissions disponibles, et youtube-dl pour télécharger les flux (car Captvty enregistre au format TS, nécessitant une étape supplémentaire de conversion en MP4). Si je tarde trop, il arrive qu'une émission affichée dans la liste de Captvty ne soit plus disponible, et le téléchargement échoue ; mais dans ce cas les flux vidéo sont encore accessibles, souvent pendant plusieurs semaines après la fin de la disponibilité officielle, le tout étant de parvenir à reconstituer les liens supprimés. Jusqu'à récemment, c'était relativement facile : 
– youtube-dl affichait lors de l'analyse du lien le code de la page JSON contenant les informations sur l'émission ;
– En consultant cette page, même si les liens avaient été supprimés, j'ai découvert que la partie variable du lien vidéo M3U8 correspond aux deux premiers codes des liens de sous-titres, tandis que les valeurs Sxx et Jx correspondent respectivement au n° de la semaine et au n° du jour de la semaine.
Ainsi par exemple pour l'émission "C'est à dire" sur F5 du 25/06/2020 (laquelle n'est plus disponible), à la page JSON :
http://sivideo.webservices.francetelevisions.fr/tools/getInfosOeuvre/v2/?idDiffusion=c4104091-2a68-45ba-820b-7c57d02bb278
on trouve ce lien de sous-titres :
http://static.francetv.fr/sous-titres//2020/06/25//231505795-5ef4c6faf2db4-1593100151.vtt
Les liens M3U8 étant de la forme :
http://replayftv-vh.akamaihd.net/i/streaming-adaptatif/2020/Sxx/Jx/xxxxxxxxx-xxxxxxxxxxxxx-,standard1,standard2,standard3,standard4,.mp4.csmil/master.m3u8
Si on remplace Sxx par S26 (26ème semaine de l'année), Jx par J4 (jeudi), et xxxxxxxxx-xxxxxxxxxxxxx par 231505795-5ef4c6faf2db4 (voir lien sous-titres), on obtient le lien correct encore valide :
http://replayftv-vh.akamaihd.net/i/streaming-adaptatif/2020/S26/J4/231505795-5ef4c6faf2db4-,standard1,standard2,standard3,standard4,.mp4.csmil/master.m3u8
Parfois il faut "streaming-adaptatif_france-dom-tom" au lieu de "streaming-adaptatif", d'après mes observations c'est toujours la même valeur pour une même émission (donc pour "C à dire" c'est toujours "streaming-adaptatif").

Mais c'est devenu plus compliqué depuis quelques semaines, car désormais, à l'issue de la période de disponibilité, non seulement les liens vidéo sont supprimés de la page JSON, mais de plus le code "videoId" de la forme xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx est supprimé de la page HTML de l'émission, et n'est donc plus affiché par youtube-dl. Il est parfois possible de retrouver ce code dans le cache Google, mais celui-ci est actualisé au bout de quelques jours, et il n'est pas possible d'accéder à des versions plus anciennes. La question est donc : y aurait-il un moyen de retrouver ces codes, ou de les déduire à partir des informations qui restent disponibles ? À défaut, est-ce que par hasard quelqu'un aurait conservé des fichiers journaux contenant ces codes pour les émissions F2 / F5 diffusées ces derniers mois ? Je pourrais éventuellement fournir une liste d'émissions que je souhaiterais tenter de récupérer en priorité. Je pourrais de mon côté fournir des liens encore accessibles d'émissions diffusées durant cette même période.

Merci.

**Comment by wwark** [comment]
Hello,

Merci pour votre message.
Il me semble difficile de tenir une table de correspondance par programme (si je comprend bien votre message).
Si on adapte l'url m3u8 il y a des risques que ça ne marche plus si la chaine change cette table de correspondance.

Quelle est l'erreur rencontré quand le lien est devenu invalide ? Est-ce qu'on obtient un HTTP 422 ?

Merci,
Wwark

**Comment by abolibibelot1980** [comment]
Je précise que je n'ai pas testé l'extension "CatchUpTVAndMore", mais j'ai pensé que j'aurais de meilleures chances d'obtenir une réponse à une question aussi atypique sur un forum dédié à un outil spécialisé, par rapport à un forum plus généraliste. Mais si vous connaissez un forum susceptible d'apporter des réponses pertinentes à cette requête, merci de me le signaler.

La question principale est : y a-t-il moyen de retrouver les codes des pages JSON des émissions francetelevisions.fr une fois le délai de disponibilité expiré ? Je veux parler du code de la forme "c4104091-2a68-45ba-820b-7c57d02bb278" dans l'exemple ci-dessus. Ce code n'est plus présent dans le code source de la page HTML d'origine :
https://www.france.tv/france-5/c-a-dire/c-a-dire-saison-13/1764899-emission-du-jeudi-25-juin-2020.html
Mais comme je l'ai montré, il est possible de déduire le lien m3u8 à partir des liens de sous-titres encore présents dans la page JSON après expiration du délai de disponibilité.

> « Quelle est l'erreur rencontré quand le lien est devenu invalide ? Est-ce qu'on obtient un HTTP 422 ? »

Quel lien ? Le lien HTML d'origine ? Et à quoi correspond un "HTTP 422" ?
Avec youtube-dl désormais quand une émission n'est plus disponible j'obtiens le message suivant :

> « [FranceTVSite] 1764899-emission-du-jeudi-25-juin-2020: Downloading webpage
> ERROR: Unable to extract video ID; please report this issue on https://yt-dl.org/bug. Make sure you are using the latest version; type  youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. »

Mais c'est parce que le code "VideoID" est désormais supprimé de la page HTML ; avant (jusqu'à la mi-Mai) on pouvait le trouver même lorsque les liens des flux étaient supprimés, et youtube-dl parvenait au moins à afficher ce fameux code à 8-4-4-4-12 caractères, à partir de quoi je parvenais à reconstituer les liens vidéo. Désormais je vais régulièrement sauvegarder les listes accessibles via ce lien :
```
http://api-front.yatta.francetv.fr/standard/publish/taxonomies/france-2/contents/?size=900&page=0&filter=with-no-vod,only-visible&sort=begin_date:desc
http://api-front.yatta.francetv.fr/standard/publish/taxonomies/france-3/contents/?size=900&page=0&filter=with-no-vod,only-visible&sort=begin_date:desc
http://api-front.yatta.francetv.fr/standard/publish/taxonomies/france-5/contents/?size=900&page=0&filter=with-no-vod,only-visible&sort=begin_date:desc
```
Mais j'aurais souhaité récupérer certaines émissions diffusées en Mai-Juin que j'ai loupées et dont les flux vidéo sont peut-être encore accessibles.

Pour le reste j'expliquais ma méthode, en suggérant qu'elle puisse éventuellement être automatisée, mais ce n'est nullement impératif, ça va au delà de ce que ces outils sont censés permettre.

Pour ce qui est des chaînes changeant leur interface de téléchargement, c'est assez régulier de toute façon, raison pour laquelle les logiciels ou extensions permettant de récupérer les flux doivent constamment être mis à jour...

Merci en tout cas pour ce retour rapide.

**Comment by wwark** [comment]
Merci pour votre retour.

Nous avons des HTTP 422 au niveau du plugin sur certaines vidéos et je me suis rendu compte en allant sur le site que la vidéo n'était plus disponible.

Pour récupérer des aciennes vidéos (Mai-Juin), je ne sais pas trop comment faire il faudrait parcourir le site pour voir déjà ce qui est récupérable et voir aussi du côté des sites qui archive les pages des sites.

SInon au niveau du plugin, on se base sur cette url et les paramètres dont des filtres ("with-no-vod,only-visible"), il faudrait jouer sur ces filtres pour afficher plus de chose.
# URL example: http://api-front.yatta.francetv.fr/standard/publish/taxonomies/france-2_cash-investigation/contents/?size=20&page=0&sort=begin_date:desc&filter=with-no-vod,only-visible

**Comment by abolibibelot1980** [comment]
Oui, l'émission ci-dessus n'est "normalement" plus disponible, mais comme vous pouvez constater le lien M3U8 est encore actif, c'est donc un bon exemple pour illustrer ce que j'ai décrit.

Sur le site, comme je l'ai indiqué, désormais les codes "videoID" sont supprimés dès la fin de la période de disponibilité. Pour ce qui est des services d'archivage, comme je l'ai également indiqué, on peut effectivement trouver ce code dans la page enregistrée sur webcache.googleusercontent.com (c'est d'ailleurs comme ça que j'ai pu récupérer l'émission citée en exemple), mais dès qu'une nouvelle version est enregistrée la précédente n'est plus accessible. Archive.org conserve de multiples versions mais ne semble pas archiver ces pages.

J'ai tenté de télécharger la liste en enlevant le paramètre "only-visible", le fichier obtenu est un peu plus gros (14,3Mo au lieu de 13,4Mo) donc il y a certes plus de choses (difficile de savoir quoi exactement, si je compare les deux fichiers avec WinMerge, comme le format JSON regroupe tous les champs sur une seule ligne de texte ça affiche tout en orange, et si on compare en mode binaire, dès la première différence les parties identiques qui suivent ne sont plus synchronisées, je ne connais pas de méthode adaptée pour comparer de tels fichiers), mais les émissions plus anciennes et supprimées ne semblent pas y figurer.

Est-ce que je peux trouver quelque part une liste des liens http://api-front.yatta.francetv.fr/... avec une description du rôle de chaque paramètre ?

**Comment by wwark** [comment]
Nous n'avons pas la liste complète de l'api juste ceux que nous utilisons dans notre code.
Vous pouvez utilisez Filder ou Charles pour capturer le traffic du site web et de l'application android/IOS de France TV.
De ces captures, vous pouvez extraires les différents appels de l'API et déterminer certaines options de l'API.

**Comment by abolibibelot1980** [comment]
Petite mise à jour : j'ai retenté de télécharger une liste http://api-front.yatta.francetv.fr/..., cette fois en enlevant tous les filtres et en mettant "size=5000", et là j'ai obtenu un fichier nettement plus volumineux (55-65Mo), contenant les informations recherchées concernant des émissions supprimées.

En outre j'ai posé la même question sur le [forum VideoHelp](https://forum.videohelp.com/threads/397970-[pluzz]-Retrieve-JSON-or-M3U8-links-when-streams-availibility-has-expired), quelqu'un m'a indiqué (en message privé) que les liens http://sivideo.webservices.francetelevisions.fr/... fonctionnaient aussi bien avec le long code "videoId" à 8-4-4-4-12 caractères, qu'avec le code "Id" que l'on trouve au début de chaque page JSON, et qui est également le même que l'on trouve dans les liens M3U8. Autrement dit, ces deux liens sont équivalents :
http://sivideo.webservices.francetelevisions.fr/tools/getInfosOeuvre/v2/?idDiffusion=2140b31f-49e9-4cd2-a4b0-5d942a87542f
http://sivideo.webservices.francetelevisions.fr/tools/getInfosOeuvre/v2/?idDiffusion=231501352
Et le code "231501352" est bien celui qui figure dans le lien M3U8 déjà indiqué plus haut :
http://replayftv-vh.akamaihd.net/i/streaming-adaptatif/2020/S26/J4/**231505795**-5ef4c6faf2db4-,standard1,standard2,standard3,standard4,.mp4.csmil/master.m3u8

En procédant comme décrit dans mon premier message, j'arrive (au 09/07) à visionner ou enregistrer certaines émissions remontant à mi-Mai, mais c'est très aléatoire. Par exemple [l'émission "Histoires courtes" du 11/05](https://www.france.tv/france-2/histoires-courtes/1438013-emission-du-lundi-11-mai-2020.html) [est encore accessible](http://replayftv-vh.akamaihd.net/i/streaming-adaptatif_france-dom-tom/2020/S20/J1/228745801-5ebaaf296a972-,standard1,standard2,standard3,standard4,.mp4.csmil/master.m3u8), alors que [celle pourtant plus récente du 18/05](https://www.france.tv/actualites-et-societe/emissions-culturelles/1531929-histoires-courtes.html) semble ne plus être accessible.
J'aimerais tester les flux HLS également, mais ceux-ci échouent aussi bien en lecture (avec VLC Media Player) qu'en téléchargement (avec youtube-dl ou ffmpeg). Est-ce qu'il y a une astuce que j'ignore ? Il semble pourtant que ce soient ces liens que Captvty utilise, car lorsque je lance la lecture d'une émission via "le lecteur embarqué", je trouve ensuite dans "Temporary Internet Files" des fragments correspondant à l'URL du flux HLS (commençant par "https://cloudreplayfrancetv.akamaized.net/"). Il y a également un fichier "crypt.key", semblant indiquer que ces flux sont cryptés, mais indiquer l'emplacement de cette clef de décryptage dans la commande de lecture ou d'enregistrement ?

> Nous n'avons pas la liste complète de l'api juste ceux que nous utilisons dans notre code.
Vous pouvez utilisez Filder ou Charles pour capturer le traffic du site web et de l'application android/IOS de France TV.
De ces captures, vous pouvez extraire les différents appels de l'API et déterminer certaines options de l'API.

Y a-t-il l'équivalent pour PC ?

**Comment by wwark** [comment]
@sy6sy2 a fait évoluée le code de France TV surement que tu peux retrouver des éléments supplémentaires.
Pour les contenus DRM il faut que le player soit DRM compliante. Kodi le permet mais je ne connais pas d'outil en ligne de commande le permettant.
Pour tester les flux tu as aussi ces outils qui peut donner des indications sur le flux en lui même et les erreurs https://github.com/add-ons/best-practices/wiki/Streaming-issues

**Comment by wwark** [comment]
Hello,
Je ferme ce ticket.
A rouvrir si besoin.
Merci !
