### ISSUE TITLE
Chaines TV Hors service

### ISSUE THREAD

**Issue by Che-debarras** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#327]
Chaines belges  (LaUne, LaDeux, LaTrois et bien d'autres)
Chaines suisses (RTS Un , RTS Deux... )

Ces chaînes ne fonctionnent toujours pas.
Et il n'ont pas le besoin d'un compte

Peuvent il être corrigé pour qu'ils fonctionnenent?

**Comment by wwark** [comment]
Hello @Che-debarras,

https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/139 -> Les Live TV suisses sont protégés par les DRM qui ne sont pas pris correctement en charge.
Les replays ont été corrigés dans la dernière release 0.2.23.

Pour les chaines LaUne, LaDeux, LaTrois, nous aurions besoin des logs ?

Il faut prendre en compte que les chaines en générales sont géolocalisés. Il faut avoir une IP du pays en question.

Merci,
Wwark

**Comment by Che-debarras** [comment]
@wwark 
Donc les chaines suisses ne seront jamais fonctionnelles?

Je pensais que les logs s'envoyaient automatiquement ?

Le souci c'est que changer d'IP a chaque fois qu'on change de chaines c'est pas pratique.
Si on veut regarder chaine suisse puis une chaines belge puis une chaines française , on devra sortir de kodi , changer l'ip et revenir sur kodi.

Donc est ce que le log est bien envoyé automatiquement ?
Sinon il suffit de tester par vous-même que aucune chaine belge ne se lance

C'est dommage c'est un bon addon mais au final ya que les chaines gratuites de la TNT qui fonctionne et encore il faut pour les chaines de m6 avoir un compte. 

Je ne critique pas mais j'ai du mal a saisir l'intérêt de cette addon si faut soit des comptes pour voir les chaines mais surtout changer l'Ip des qu'on zappe (et dont des chaines intéressants sont sous drm).

Je vois bcp de maj de cette addon en beta ou master mais ya rien qui change si c'est geolocalisé ou drm , il reste peu de chaine et ils sont plus facilement accessibles par la voie officielle de l'antenne tv.

Merci quand même pour ta réponse.

**Comment by wwark** [comment]
Merci pour ton retour.
Les DRM et la géolocalisation sont présentes il faut faire avec.

Le but est de donner l'accès aux personnes de chaque pays.

Après oui, les services proposés par les FAI ou les chaines elle même seront toujours un meilleur service que le plugin si on est dans le pays.

J'avais testé que LaUne (qui était non protégé par DRM) cependant ils proposent maintenant des contenus DRM et La deux et La trois sont en erreur. On regarde pour ajouter le support des DRM pour les live TV de RTBF.

**Comment by wwark** [comment]
On fait de nombreuses mise à jour car les chaines effectues des changements.

**Comment by wwark** [comment]
Je viens d'apporter un fix les live TV DRM de RTBF (LaUne, LaDeux, ...) sont maintenant fonctionnel sur la beta 0.2.24~beta01

**Comment by Che-debarras** [comment]
> Je viens d'apporter un fix les live TV DRM de RTBF (LaUne, LaDeux, ...) sont maintenant fonctionnel sur la beta 0.2.24~beta01

Bizarre car tu a corrigé LaUne et elle fonctionne mais LaDeux LaTrois ne marche pas

**Comment by wwark** [comment]
Hello @Che-debarras,
Nous aurions besoin des logs.
Les Live TV de RTBF ont des live protégés par DRM et d'autres non. Ce point dépend du contenu je pense.
RTS Un et RTS Deux il y a une correction à apporter au niveau des DRM de Kodi pour les faire fonctionner correctements.

V Télé, Youpa et TVA fonctionnent avec un IP canadienne.
Télé quebec il y a un soucis on va regarder pour corriger.

Merci,

**Comment by wwark** [comment]
Télé Quebec corrigé sur la version betâ 0.2.24~beta02.

**Comment by Che-debarras** [comment]
> Hello @Che-debarras,
> Nous aurions besoin des logs.

Ce n'est pas envoyé directement ces logs?
Comment vous les trouvez et les envoyez ?

**Comment by wwark** [comment]
On a un mode pour recevoir les logs si une erreur apparait mais je n'ai pas eu de mail de votre part.
Sinon pour récuperer les logs vous pouvez les récupérer en suivant ce wiki https://kodi.wiki/view/Log_file.
L'emplacement peut différé suivant les OS/Version de Kodi etc ...

Il faut s'assurer que vous êtes bien en version 0.2.24~beta02 et utilisé une IP du pays proposant le contenu vidéo.

Merci,
Wwark

**Comment by wwark** [comment]
N'ayant pas eu de retour depuis plus d'un mois nous nous permettons de fermer ce ticket.
N'hésite pas à le rouvrir si besoin.
