### ISSUE TITLE
Impossible d'installer la version 0.2.23

### ISSUE THREAD

**Issue by caywin25** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#328]
Bonjour, 

Tout d'abord, merci pour votre travail.

Depuis la version 0.2.22 je n'arrive plus à installer le plugin.
Sur kodi j'ai un message qui parle de dépendance mais le message est trop court pour que je le vois entièrement.
Ou puis-je avoir d'avantage de log s'il vous plait pour vous les faire parvenir ?
Merci

**Comment by SylvainCecchetto** [comment]
Bonjour et merci pour votre message !

Voici les indications nécessaires afin de pouvoir nous fournir le log. Ce sera plus simple pour nous d’identifier le problème 😉


https://kodi.wiki/view/Log_file

**Comment by caywin25** [comment]
Bonjour
Je répond un peu tard, désolé.
Finalement j'ai refais une installation fraiche, du coup je n'ai plus de soucis pour installer la dernière release de catchuptvandmore.

Je clos cette issue.
Merci
