### ISSUE TITLE
Impossible d'accéder aux chaines

### ISSUE THREAD

**Issue by Vdauphin** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#33]
**Windows Version:** `10` (stable)
**Kodi Version:** `17.5` (stable)
**Catch up TV:** `0.1.3` (stable)

**Description:**
- Lors de la sélection de la chaîne France 2, France 3 etc (toutes les chaines) le menu ne s'affiche pas et un message m'indique qu'une erreur est survenue consulter le journal pour plus d'information.

**Steps to reproduce:**
- Ouvrir l'application
- Chaines Francaises
- sélectioner une chaine
- rien ne se passe et le message: une erreur est survenue consulter le journal pour plus d'information apparaît.

**log file:**
- Dans ce log l'erreur a été obtenue deux fois [kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/1434403/kodi.log).

**Pistes:**
- j'ai  déployé ce plugin sur trois machines (une Ubuntu et deux Windows 10). J'ai seulement eu une erreur sur l'une des machines Windows 10. La cause évidente donnée par le log est que kodi est exécuté sous l'utilisateur Hervé et il semble exister une erreur d'encodage de l'accent d'où l'erreur `Error Contents: (2, 'No such file or directory')`.

Merci pour cet add-on très utile!
Bonne journée.

**Comment by wwark** [comment]
Bonjour,

Merci !
Est-ce que l'autre Windows 10 où le plugin fonctionne a un caractère accentué dans le nom de l'utilisateur ?
Est-ce que vous avez essayé de désintaller le plugin, supprimer les données %APPDATA%\kodi\userdata\plugin.video.catchuptvandmore\ et reinstaller le plugin ?

Bonne journée,
Wwark

**Comment by Vdauphin** [comment]
Bonjour,

> Est-ce que l'autre Windows 10 où le plugin fonctionne a un caractère accentué dans le nom de l'utilisateur ?

Malheureusement je n'ai pas d'utilisateur avec un nom utilisateur accentué sur cette machine désolé.

 > Est-ce que vous avez essayé de désintaller le plugin, supprimer les données %APPDATA%\kodi\userdata\plugin.video.catchuptvandmore\ et reinstaller le plugin ?

Je viens de le faire, est l'erreur persiste.

Bonne journée.

**Comment by wwark** [comment]
Merci je n'ai pas pour l'instant d'environnement similaire pour tester ce cas.
Est-ce qu'il serait possible d'activer les logs de kodi en mode debug et nous fournir les logs du problème ?

Autre point, nous avons une version stable 0.1.4 avec des mises à jour présente sur ce dépot:
https://repo.cecchettosylvain.fr/zip/
Elle est en cours d'acceptation sur le dépot de Kodi.
On pourrait voir si le problème persiste avec cette nouvelle version.

Bonne journée,
Wwark

**Comment by Vdauphin** [comment]
Bonjour,

> Est-ce qu'il serait possible d'activer les logs de kodi en mode debug et nous fournir les logs du problème ?

Voici le log demandé : [kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/1437769/kodi.log)


J'ai installé sur un 4ème ordinateur kodi et l'extension Catch TV. J'ai deux utilisateur, l'un sans accent et l'autre avec. Malheureusement, l'utilisateur avec un accent dans son nom ne peut regarder les chaînes qu'il désire.

J'ai rapidement lu le fichier de log présenté en début de cette issue et l'erreur apparaît ici : [addon.py#L245-L247](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/master/addon.py#L245-L247) car le [channel_path](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/master/addon.py#L240-L243) est incorrect. Je n'ai malheureusement pas les modules python/xbmc pour tester différent type de chemin possible.

Bonne journée.

**Comment by wwark** [comment]
Bonsoir,

Merci pour les logs.

Est-ce qu'il possible de faire une modification sur le fichier addon.py ?

**Remplacer:**
channel_path = common.sp.xbmc.translatePath(
        common.sp.os.path.join(
            LIB_PATH,
channel_module.replace('.', '/') + '.py'))
**Par:**
channel_path = common.sp.xbmc.translatePath(
        common.sp.os.path.join(
            LIB_PATH,
channel_module.replace('.', '/') + '.py').encode('UTF-8'))

Si le test est concluant, je testerai cette modification sur mes environments et commiterai cette modification.

Merci,
Wwark.

**Comment by Vdauphin** [comment]
> channel_module.replace('.', '/') + '.py').encode('utf-8'))

Je vois mais je pense que c'est plutôt du ISO-8859-15. Je teste cela demain.
Bonne soirée.

**Comment by Vdauphin** [comment]
> ```
> channel_path = common.sp.xbmc.translatePath(
> common.sp.os.path.join(
> LIB_PATH,
> channel_module.replace('.', '/') + '.py').encode('utf-8'))
> ```

Cela ne fonctionne pas voici le log : [kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/1440713/kodi.log)

> Je vois mais je pense que c'est plutôt du ISO-8859-15. Je teste cela demain.

Cela ne fonctionne pas mieux non plus x)

**Comment by wwark** [comment]
Merci pour les tests et les nouveaux logs indiquant un problème d'encodage.

Est-ce qu'il est possible de rajouter ces lignes, 
print LIB_PATH
print LIB_PATH.decode('utf-8')
print LIB_PATH.encode('utf-8')
avant le code modifié précédement et mettre les logs en mode debug.
Ce point permettrait de voir les caractères affichés.

Je n'ai pas de windows sous la main désolé ...

Wwark

**Comment by SylvainCecchetto** [comment]
J'ai une VM Windows, je vais essayer.
Il faut un nom d'utilisateur windows avec un accent pour maximiser les chances d'avoir un bug c'est ça ?

**Comment by SylvainCecchetto** [comment]
Bon c'est cool, j'arrive à reproduire l'erreur à tout les coups avec un Windows 7 et Kodi 15.5. Il s'agit bien d'une erreur d'encodage du chemin :

```
10:50:53.441 T:2180   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: (2, 'No such file or directory')
                                            Traceback (most recent call last):
                                              File "C:\Users\Test� T�t�\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\addon.py", line 376, in <module>
                                                common.PLUGIN.run(window_title)
                                              File "C:\Users\Test� T�t�\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\simpleplugin.py", line 1041, in run
                                                result = action_callable(params)
                                              File "C:\Users\Test� T�t�\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\addon.py", line 298, in channel_entry
                                                channel = get_channel_module(params)
                                              File "C:\Users\Test� T�t�\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\addon.py", line 288, in get_channel_module
                                                channel_path)
                                            IOError: (2, 'No such file or directory')
```

Je regarde si un encode(utf-8) bien placé peut régler le problème ...

**Comment by SylvainCecchetto** [comment]
Bon ok je crois bien qu'il y avait deux problèmes : l'encodage mais aussi les \ et /

Voici la fonction à remplacer dans addon.py (je vais pusher ça tout de suite)

Attention il faut importer le module sys au début du fichier !!

Je pense qu'il va falloir faire cette modif partout dans l'addon quand on se sert des PATH sinon on va avoir des problèmes.

Je n'ai pas testé cette modif sur système unix pour le moment

```
def get_channel_module(params):
    if 'channel_name' in params and \
            'channel_module' in params and \
            'channel_id' in params and \
            'channel_category' in params:
        channel_name = params.channel_name
        channel_module = params.channel_module
        channel_id = params.channel_id
        channel_category = params.channel_category
        with common.PLUGIN.get_storage() as storage:
            storage['last_channel_name'] = channel_name
            storage['last_channel_module'] = channel_module
            storage['last_channel_id'] = channel_id
            storage['last_channel_category'] = channel_category
    else:
        with common.PLUGIN.get_storage() as storage:
            channel_name = storage['last_channel_name']
            channel_module = storage['last_channel_module']
            channel_id = storage['last_channel_id']
            channel_category = storage['last_channel_category']

    params['channel_name'] = channel_name
    params['channel_id'] = channel_id
    params['channel_category'] = channel_category

    channel_path = common.sp.xbmc.translatePath(
        common.sp.os.path.join(
            LIB_PATH,
            *(channel_module.split("."))
        )
    )
    channel_filepath = channel_path + ".py"
    channel_filepath = channel_filepath.decode(
        "utf-8"
    ).encode(
        sys.getfilesystemencoding()
    )

    return imp.load_source(
        channel_name,
        channel_filepath
    )
```

**Comment by wwark** [comment]
Testé sous débian pas d'erreur. J'ai l'impression que le plugin est plus réactif avec cette modification !

Pour Android, on a cette erreur,
Called action "channel_entry" with params "<Params {'channel_module': 'channels.fr.tf1', 'channel_id': 'channels.fr.tf1.tf1', 'channel_category': 'fr', 'next': 'root', 'channel_name': 'tf1', 'action': 'channel_entry', 'window_title': 'TF1'}>"
12:35:00.546 T:18446744071886645552   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: encode() argument 1 must be string, not None
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc17/files/.spmc/addons/plugin.video.catchuptvandmore/addon.py", line 386, in <module>
                                                common.PLUGIN.run(window_title)
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc17/files/.spmc/addons/plugin.video.catchuptvandmore/resources/lib/simpleplugin.py", line 1041, in run
                                                result = action_callable(params)
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc17/files/.spmc/addons/plugin.video.catchuptvandmore/addon.py", line 308, in channel_entry
                                                channel = get_channel_module(params)
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc17/files/.spmc/addons/plugin.video.catchuptvandmore/addon.py", line 292, in get_channel_module
                                                sys.getfilesystemencoding()
                                            TypeError: encode() argument 1 must be string, not None
                                            -->End of Python script error report<--
12:35:00.546 T:18446744072349944112   DEBUG: ------ Window Init (DialogNotification.xml) ------

Wwark

**Comment by SylvainCecchetto** [comment]
Merci pour le test sous debian

Arf ; sous Android la fonction getfilesystemencoding() retourne Nono -_-'

Je regarde ça ! Merci pour le test

**Comment by wwark** [comment]
Test Ok Android ! et Debian aussi!
Merci

**Comment by SylvainCecchetto** [comment]
Cool ! Merci ! Plus qu'à testé sur un "vrai" windows

**Comment by Vdauphin** [comment]
Bonjour,

Testé et c'est parfait !

Merci beaucoup !

**Comment by SylvainCecchetto** [comment]
Parfait ! Merci d'avoir remonté ce bug et d'avoir testé ;-)
