### ISSUE TITLE
Les Chaînes du Groupe M6 ne sont plus accessibles

### ISSUE THREAD

**Issue by Philippe77144** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#330]
Lors de la sélection d'une chaîne du groupe M6 (M6, W9...), aucune image ne s'affiche, pas de son non plus et au bout d'un moment, retour à l'écran de sélection sans aucun message d'erreur.
Le problème se produit sur Raspberry Pi 3B +,LibreElec 9.2.1, Kodi 18.6, Catch-Up TV 0.2.23 mais également sur Windows 10, Kodi 18.7, Catch-Up TV 0.2.23.

**Comment by SylvainCecchetto** [comment]
Bonjour Philippe,

Ce problème est connu depuis quelques temps, je vous invite à suivre la situation ici: https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/300 mais pour le moment nous devons attendre la mise à jour de Kodi/Inputstream adaptive :-/

**Comment by Philippe77144** [comment]
Bonjour Sylvain,Merci pour ta réponse. Je vais suivre l'incident. Cordialement. Le 10 juil. 2020 10:03, Sylvain CECCHETTO <notifications@github.com> a écrit :

Bonjour Philippe,

Ce problème est connu depuis quelques temps, je vous invite à suivre la situation ici: #300 mais pour le moment nous devons attendre la mise à jour de Kodi/Inputstream adaptive :-/
