### ISSUE TITLE
Equidia

### ISSUE THREAD

**Issue by chamchenko** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#331]
### Content description

* Name: Equidia
* Type  TV channel
* Website URL: https://www.equidia.fr/direct
* Content language/country: France

### Content access
- [x] This content is geographically restricted

### More information
The stream url fetching could be done using these api
https://equidia-vodce-players.hexaglobe.net/mf_data/20200712.json // the json file name changes every day, you can see that it points to today's date
then you can get the stream info url
exemple:
https://equidia-live2-p-api.hexaglobe.net/fbea6f367d1d30450a5f9805ec46c1c3/5f0aa6e0/equidia/equidia-website-web-1/live2/stream_info.php
to which you shoud add ?format=hls or ?format=dashwidevine for the drm protected link

**Comment by wwark** [comment]
Hi @chamchenko,
Thank you for those research.
Equidia Live TV is added on the plugin with 0.2.24~beta07.

Thanks,

**Comment by wwark** [comment]
Présent dans la release 0.2.24.
Ticket clos.
