### ISSUE TITLE
M6 et W9 ne marchent pas

### ISSUE THREAD

**Issue by spctoma** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#332]
Bonjour à tous,

Je n'arrive pas à avoir les chaînes M6 et W9 en TV direct. Je précise que je suis sur RPI3 avec LibreElec, tout à jour. J'ai bien une IP en France et j'ai rajouté mon compte M6 dans les paramètres. J'arrive à accéder aux replay mais pas à la TV en direct. J'ai désactivé le VPN dans les options Catchup-TV.
Je n'ai aucun message d'erreur, juste la petite roue bleue qui tourne qqes secondes et qui revient à la liste des chaînes (que ce soit dans l'addon ou dans TVR).

Si ça peut vous aider j'ai le lien vers le fichier de log Kodi : http://ix.io/2rza ou encore http://ix.io/2rz9

Merci d'avance pour votre aide

**Comment by wwark** [comment]
Hello @spctoma,
Ce problème est déjà suivi par ce ticket.
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/300

Le problème se situe au niveau de l'addon binaire inputstream.adaptive. Il a été fixé mais pas encore de release. Vous pouvez le compiler depuis le source code de inputstream.adaptive (kodi 18-leia).

Je me permet de fermer ce ticket !
Merci,
Wwark
