### ISSUE TITLE
Add X-Forwarded-For header for AB3 and AB Xplore

### ISSUE THREAD

**Issue by chamchenko** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#337]
I was checking the AB 3 and AB Xplore live streams and it seems that Geo restriction is only applied to resolving the live url and it can be bypassed by simply adding the x-forwarded-for header to the requests header
I tested it by adding to line 94 of abbe.py and it works
session_requests.headers.update({'x-forwarded-for' : '172.111.148.6'})

**Comment by joaopa00** [comment]
API changed. Does this trick still works?

**Comment by chamchenko** [comment]
@joaopa00  No this does not apply any more. You can close this issue.

**Comment by joaopa00** [comment]
Thanks for the feedback. I close this issue then.
