### ISSUE TITLE
Euronews (FR) : SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by slax57** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#338]
### Describe the bug
Lancer la chaîne Live **Euronews (FR)** génère une erreur **SSL: CERTIFICATE_VERIFY_FAILED** (plus de détail dans les logs ci-dessous).

Je suis localisé en France métropolitaine.

J'utilise le plugin en version `0.2.25~beta01`, mais le problème se produit aussi sur la version stable `0.2.24`.

J'utilise Kodi Kypton v17.5.

### To Reproduce
1. Aller dans 'Live TV' / 'International'
2. Cliquer sur 'Euronews (FR)'

### Expected behavior
Lecture de la chaîne TV

### Actuel behavior
Une popup d'erreur s'affiche (SSL: CERTIFICATE_VERIFY_FAILED), impossible de lire l'item sélectionné.

### Screenshots
![kodi-ssl-error](https://user-images.githubusercontent.com/14542336/89058547-c47b7300-d35f-11ea-9d6e-3062cd0b08f9.PNG)

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Other

 - Operating system version/name: **Windows 10 64 bits**
 - Kodi version: **Kodi Kypton v17.5**
 - Catch-up TV & More version: **0.2.25~beta01**
 - Installation method: **Catch-Up TV & More official repository (beta)**

### Debug log

Logs en niveau ERROR (si besoin des logs en niveau DEBUG, me les demander) :

```
18:47:19.771 T:4616   FATAL: [Catch-up-TV-&-More.support] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)
                                            Traceback (most recent call last):
                                              File "C:\Users\jbkai\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 314, in run_callback
                                                results = route.function(parent_ins, **self.callback_params)
                                              File "C:\Users\jbkai\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\main.py", line 275, in live_bridge
                                                return module.live_entry(plugin, item_id, **kwargs)
                                              File "C:\Users\jbkai\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\channels\wo\euronews.py", line 46, in live_entry
                                                return get_live_url(plugin, item_id, **kwargs)
                                              File "C:\Users\jbkai\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\channels\wo\euronews.py", line 71, in get_live_url
                                                max_age=-1)
                                              File "C:\Users\jbkai\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 1427, in get
                                                return session.request(u"GET", url, params=params, **kwargs)
                                              File "C:\Users\jbkai\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 1021, in request
                                                raw_resp = self.make_request(req, timeout, verify, max_age)
                                              File "C:\Users\jbkai\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 520, in make_request
                                                return self.connect(req, timeout, verify)
                                              File "C:\Users\jbkai\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 547, in connect
                                                response = self.send_request(conn, req)
                                              File "C:\Users\jbkai\AppData\Roaming\Kodi\addons\script.module.codequick\lib\urlquick.py", line 572, in send_request
                                                raise SSLError(e)
                                            SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)
18:47:19.771 T:4616 WARNING: ###### debug ######
18:47:19.771 T:4616 WARNING: [Catch-up-TV-&-More.support] Dispatching to route: '/resources/lib/main/live_bridge/'
18:47:19.771 T:4616 WARNING: [Catch-up-TV-&-More.support] Callback parameters: '{u'item_id': u'euronews', u'item_module': u'resources.lib.channels.wo.euronews'}'
18:47:19.771 T:4616 WARNING: [Catch-up-TV-&-More.support] Attempting to import route: resources.lib.main
18:47:19.771 T:4616 WARNING: [urlquick] Cache location: C:\Users\jbkai\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.catchuptvandmore\
18:47:19.771 T:4616 WARNING: [urlquick] Requesting resource: http://fr.euronews.com/api/watchlive.json
18:47:19.771 T:4616 WARNING: [urlquick] Request headers: {u'Accept-language': u'en-gb,en-us,en', u'Accept-Encoding': u'gzip, deflate', u'Host': u'fr.euronews.com', u'Accept': u'*/*', u'User-Agent': u'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1', u'Connection': u'keep-alive'}
18:47:19.771 T:4616 WARNING: [urlquick] Redirecting to = https://fr.euronews.com/api/watchlive.json
18:47:19.771 T:4616 WARNING: [urlquick] Attempting to decode with default encoding: 'utf8'
18:47:19.771 T:4616 WARNING: [urlquick] Requesting resource: https://euronews-fr-p-api.hexaglobe.net/447600d64c6fbac61ab824eb62368bb9/5f244ae9/euronews/euronews-euronews-website-web-responsive-2/fr/stream_info.php?format=hls
18:47:19.771 T:4616 WARNING: [urlquick] Request headers: {u'Accept-language': u'en-gb,en-us,en', u'Accept-Encoding': u'gzip, deflate', u'Host': u'euronews-fr-p-api.hexaglobe.net', u'Accept': u'*/*', u'User-Agent': u'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1', u'Connection': u'keep-alive'}
18:47:19.771 T:4616 WARNING: ###### debug ######
18:47:19.820 T:12768   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.catchuptvandmore/resources/lib/main/live_bridge/?_pickle_=80027d71002858070000006974656d5f6964710158080000006575726f6e657773710255075f7469746c655f7103580d0000004575726f6e65777320284652297104580b0000006974656d5f6d6f64756c65710558220000007265736f75726365732e6c69622e6368616e6e656c732e776f2e6575726f6e6577737106752e]
```

### Additional info

Je profite de cette occasion pour vous remercier pour ce plugin par ailleurs très pratique et très bien réalisé. J'apprécie beaucoup votre travail ! ☺️

**Comment by SylvainCecchetto** [comment]
Hello !

Tout d'abord merci beaucoup pour votre message d'encouragement 😃 

Concernant le bug, je viens à l'instant de tester sous Leia ainsi que sous Krypton et pas de problème de mon coté pour Euronews en FR.

Pouvez-vous essayer de vider le cache du plugin (Catch-Up TV & More --> Settings --> Advanced settings --> clear cache) ; à tout hasard... :-/

**Comment by slax57** [comment]
Merci pour votre réponse rapide.

J'ai tenté de vider le cache mais ça ne semble pas avoir d'effet 🙁

**Comment by SylvainCecchetto** [comment]
Hum étrange, je n'ai jamais eu ce genre de problème. Seulement cette chaine est concernée ?
@wwark ça te dit quelque chose ? Tu as un Windows sous la main pour tester ?

**Comment by slax57** [comment]
En parallèle j'ai fait un autre test, avec **Kodi Leia** sous **Android**, et là en effet pas de problème avec Euronews FR 😬 

Sur mon **Kodi 17 Windows**, les autres chaînes fonctionne correctement (par exemple **France 24 FR** juste en dessous)

**Comment by SylvainCecchetto** [comment]
Bon c'est déjà bon signe que ça fonctionne sur une autre appareil/Kodi.

Après je suis incapable de dire si c'est au niveau de l'OS ou de Kodi 17 :-/
J'imagine que restart de Kodi ou de Windows ne change rien ? (Quand on tape `CERTIFICATE_VERIFY_FAILED  Kodi` sur google y'a quelques posts mais je ne vois rien de fou fou pour régler le problème par magie)

**Comment by slax57** [comment]
Merci pour votre réponse.

Au final c'est un peu elle qui m'a mis sur la voie : j'ai réalisé que c'était sans doute plutôt un problème avec mon installation de Kodi plutôt qu'avec votre plugin.

Et en recherchant l'erreur exacte avec le numéro de ligne précis (`ssl.c:661`), je suis tombé sur [cette page](https://github.com/gdomenici/plugin.video.pcloud-video-streaming/issues/20), qui proposait comme solution de définir la variable d'environnement : `PYTHONHTTPSVERIFY=0`.

J'ai testé et comme cela ça fonctionne ! 🙂 

J'imagine que cela a dû être corrigé directement dans les versions ultérieures de Kodi. 
(Je suis forcé d'utiliser une version ancienne car mon environnement cible est un [SteamLink](https://support.steampowered.com/kb_article.php?ref=8082-YJBN-9141), qui possède une version de Kodi mais non maintenue et qui s'est arrêté à la v17.6).

Quoiqu'il en soit, j'imagine qu'on peut considérer que cette Issue est résolue 🙂 

Désolé de vous avoir fait perdre un peu de temps avec ça.
Encore bravo et merci pour ce plugin ! ☺️

**Comment by SylvainCecchetto** [comment]
J'aurais au moins appris l'existence des SteamLink 😉 
Tant mieux alors si ça fonctionne avec ce petit hack, ça sera peut être utile à d'autres !

Aucun problème, c'est fait pour ça les issue. Bonne soirée et merci à vous d'utiliser le plugin surtout !
