### ISSUE TITLE
Catchup TV and more - M6, W9, etc.

### ISSUE THREAD

**Issue by ZePhteven** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#341]
Bonjour,

Il m'est impossible de visualiser les chaines du groupe M6 et ce même en ayant mes login/mdp du m6 replay. Pas de message d'erreur, juste une longue attente et je reviens sur la liste des chaines.

Je précise que j'ai du installer "InputStream adaptive" manuellement, si jamais.

Auriez-vous une idée ? (ou un path vers des logs éventuels que je pourrais vous transmettre)

Cordialement,

**Comment by Fernando35** [comment]
Bonjour, je rencontre le même soucis remonté. J'ai également soumis les informations pour me connecter sur 6play.
Je joins des logs en pièce jointe.
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/5023235/kodi.log)

On y voit plein de 404 lors de mes tentatives d'accès à la chaine.

Cordialement

**Comment by sy6sy2** [comment]
Bonjour à vous deux. 
Si le problème est le même alors il y a déjà un ticket pour les Live du groupe M6 avec une solution ici https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/300#issuecomment-667508278 😉

**Comment by Fernando35** [comment]
Bonjour Sylvain,

C'était bien çà le soucis. Merci pour la résolution du problème, çà marche nickel.

Merci pour le travail fourni
Coridalement,
