### ISSUE TITLE
LiveTv-Can-TVA stop working

### ISSUE THREAD

**Issue by boxkim14** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#343]
Bonjour,

J'aimerais vous avertir que dans LiveTV, section Canada, la chaine TVA ne marche plus.

Encore merci pour ce merveille add-on.

**Comment by wwark** [comment]
Hello @boxkim14,

I have the same behavior (HTTP 404) as you.
I tried the website of the channel and there is the same issue HTTP 404.
https://video.tva.ca/page/direct

Can you confirm the direct is not working also your side?
If it is the case we need to wait the channel fixed it.

Thanks,

**Comment by boxkim14** [comment]
Hi @wwark ,

Yesterday, I could see TVA direct on the browser but not with the add-on.
Today, I can see TVA on both platform 👍 then the "bug' is fixed.

Thank for your answer.
