### ISSUE TITLE
Plusieurs questionnement pour 6play/RTLPlay

### ISSUE THREAD

**Issue by Europe57** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#344]
Hello

J'avais plusieurs questions, peut-être déjà traiter mais je n’ai pas trouvé les réponses.

Pour 6play et RTLPlay en replay, je me demandais pourquoi les vidéos sont uniquement en SD (720x406), alors que 6play, RTLPlay propose du 720p, voir du 1080p vu mes dernières constations de qualité vidéo meilleurs directement sur leurs sites respectifs.

Concernant Téva et Paris Première, depuis un certain moment si on se connecte via son compte Free ou Bouygues Télécom, on peut rattacher les chaine Téva et Paris Première à 6play gratuitement (si abonné bien sûr au chaîne via sont FAI, par exemple chez Free proposer dans Freebox TV by Canal)

![Téva et Paris Première avec Free](https://www.zupimages.net/up/20/33/7baa.png)

Je me demandais puisque, pour accéder au vidéo de 6play sur l’extension, on devait fournir ces identifiants, ce n’est pas possible d'ajouter Téva et Paris Première ? Il suffirait de signaler qu'il faut un compte avec abonnement pour voir les vidéos de Téva et Paris Première, et pas besoin que vous ayez à fournir des comptes comme j'ai pu lire.

Pour finir, je me demandais, vous avez intégré les différentes pistes audios, par contre aucun sous-titre ? Un peu difficile de voir une série en VO si on galère avec l'anglais parler.

En tout cas merci pour votre extension, voir du replay sans pub, ça mérite tous les remerciements du monde 👍 

Merci pour la prise de temps de lecture et de réponse.

A bientôt.

**Comment by wwark** [comment]
Bonjour,

Merci pour votre message de toute l'équipe CUTV &More !

Il faudrait qu'on regarde au niveau de l'API si on peut proposer des meilleurs contenus mais la dernière fois on n'avait que ces formats disponibles.

Le problème des contenus payants est de pouvoir vérifier que ça fonctionne avant de le dire et le tester dans la continuité mais sans comptes TEVA ou Paris Premières. On ne sera pas capable de faire du support.
Il est possible aussi que le DRM soit différent pour ces vidéos donc impliquerait une modification du code pour lire les vidéos.
Si on prend des comptes pour les chaînes payantes présentes dans le plugin, il faut voir comment nous le finançons (Patréon, etc ...) Si les personnes y participent ils voudront une correction rapidement ce qui est normal car il paye (à réfléchir aussi)
Du moins on y réfléchis depuis 1 à deux ans sans trop avancer sur le sujet.
Le fait qu'on nous passe un compte (avec les accès aux cartes de crédits etc ...) je ne trouve pas ça très sécurisé. Il faudra aussi que la personne nous donne son compte à chaque test que nous devrons faire.

Les sous-titre sont normalement disponibles pour les vidéos le proposant cf screenshot ci-dessous.
![Screenshot from 2020-08-13 18-31-52](https://user-images.githubusercontent.com/469461/90161424-63a65e80-dd93-11ea-8de6-edd3ad0f73a9.png)
![Screenshot from 2020-08-13 18-32-01](https://user-images.githubusercontent.com/469461/90161446-6b660300-dd93-11ea-84ca-0bb866c3808b.png)

Merci,
Wwark

**Comment by Europe57** [comment]
Concernant les contenus payants, ceux qui ont un abonnement avec Free ou Bouygues ne fournit aucune info confidentielle, 6play va sur le site du FAI et c'est le FAI qui communique si oui ou non les droits sont accordés (session valable plusieurs semaines avant devoir refaire la manipulation). Donc si vous avez besoin d'un compte, juste pour voir comment et fait Téva et Paris Première, si c'est pareil que les chaînes gratuites, dite le moi en privé.

Concernant les sous-titres, je ne dois pas avoir de bol alors, Reef Break (S01E12) à bien du sous-titrage sur 6play :

![6play](https://www.zupimages.net/up/20/33/kwjp.png)

Mais pas sur l'extension :

![Extension](https://www.zupimages.net/up/20/33/l0xx.png)

Merci pour vos réponses clair.

A bientôt.

**Comment by wwark** [comment]
C'est pareil on aura accès au compte de la personne chez free (par exemple) donc surement accès à plus d'informations que 6play. C'est aussi surement lié à mon travail dans la sécurité informatique d'avoir cette position.

J'ai oublié de demander est-ce que l'option dans les configurations du plugin est bien activée ?
![Screenshot from 2020-08-13 20-17-16](https://user-images.githubusercontent.com/469461/90171770-46c55780-dda2-11ea-8784-9b75978045a6.png)

Merci,
Wwark

**Comment by Europe57** [comment]
Ça marche pour les sous-titres, totalement passer au travers de ce paramètre. Merci pour les sous-titres, c'est bien mieux avec.

Pour Free, y aura accès a rien, justement c'est comme pour myCanal, aucune info ne filtre, je sais que Free était intransigeant pour ça avec Canal à l'époque de la création de leurs offre myCanal, alors je doute qu'ils on été cool en sécurité avec M6.

Les seules infos qui passent sont les infos mis pour créer le compte 6play au départ (modifiable avec de fausses infos, au besoin)

![Info qui passe](https://www.zupimages.net/up/20/33/w9ks.png)

![Procédure de connexion](https://www.zupimages.net/up/20/33/52uh.png)

La connexion entre Free et 6play reste quelques semaines, je ne sais pas combien de temps exactement, sûrement pour obliger à revérifier si les droits d'accès sont encore valables.

Bref j'en parle plus, je reste ouvert en privé pour le(s) codeur(s) de 6play 😉

A bientôt.

**Comment by wwark** [comment]
Merci pour ta valation sur la fonctionnement des sous titre.

Je viens de vérifier de nouveaux les flux vidéos disponibles sur le site web que nous propoposons dans le plugin.
La qualité est encore en SD. Si on regarde la vidéo sur le site web on n'a que de la qualité SD.

![image](https://user-images.githubusercontent.com/469461/90217341-60e25280-de01-11ea-87db-9e088ce0b439.png)

**Comment by Europe57** [comment]
Merci pour ta réponse.

Je me demande comment Captvty arrive a choper un 720p sur les vidéos non DRM, si dans le MDP la qualité est brider au SD sur le site web, les mystères de l'informatique j'ai envie de dire.

En tout cas merci pour toute ces réponses clairs.

A bientôt.

**Comment by wwark** [comment]
Captvty doit utiliser une autre source video (autre API ou d'autres options de l'API que nous ne connaissons pas). 
Le code source de Captvty n'est pas ouvret si je ne dis pas de bêtise donc difficile de dire.

Merci,
Wwark

**Comment by Europe57** [comment]
Ok, merci pour tout.

A bientôt.

**Comment by Europe57** [comment]
Désolée pour la réouverture, mais je reviens encore pour quelques choses 😊

D'après le MDP de Zone interdite (http://www.6play.fr/zone-interdite-p_845/un-ete-dans-le-monde-secret-des-forains-c_12074555)

Il y a bien tes 3 formats, sur le m3u8 idem, mais...

`#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=40000,CODECS="avc1.42001E",RESOLUTION=400x226,URI="keyframes/Zone-interdite_c12074555_Un-ete-dans-le-monde_drmnp-video_eng=301000.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=106000,CODECS="avc1.42001E",RESOLUTION=640x360,URI="keyframes/Zone-interdite_c12074555_Un-ete-dans-le-monde_drmnp-video_eng=800000.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=199000,CODECS="avc1.42001E",RESOLUTION=720x406,URI="keyframes/Zone-interdite_c12074555_Un-ete-dans-le-monde_drmnp-video_eng=1500000.m3u8"`

Si on fait un test simple, si je met à format 720x406 - 1500000 sur sont DASH

`https://th2-edge-01.cdn.m6web.fr/usp/mb_sd3/6/7/4/Zone-interdite_c12074555_Un-ete-dans-le-monde/Zone-interdite_c12074555_Un-ete-dans-le-monde_drmnp.ism/dash/Zone-interdite_c12074555_Un-ete-dans-le-monde_drmnp-video_eng=3000000.dash`

Ça donne une erreur site inexistant, mais si je met 3000000 là il me dit vidéo de 1248x702.

`https://th2-edge-01.cdn.m6web.fr/usp/mb_sd3/6/7/4/Zone-interdite_c12074555_Un-ete-dans-le-monde/Zone-interdite_c12074555_Un-ete-dans-le-monde_drmnp.ism/dash/Zone-interdite_c12074555_Un-ete-dans-le-monde_drmnp-video_eng=3000000.dash`

(J'ai téléchargé le fichier de quelque ko, puis mediainfo pour avoir le format vidéo)

Et si je fais 3150000.dash là c’est une vidéo en 720p.

`https://th2-edge-01.cdn.m6web.fr/usp/mb_sd3/6/7/4/Zone-interdite_c12074555_Un-ete-dans-le-monde/Zone-interdite_c12074555_Un-ete-dans-le-monde_drmnp.ism/dash/Zone-interdite_c12074555_Un-ete-dans-le-monde_drmnp-video_eng=3150000.dash`

Pas trouver plus haut (pas tout tester, tester dans les 5000000 et 6000000.

Alors je n’y connais pas grand-chose, ni si ça sera utile, mais je préfère partager que de garder pour moi.

A bientôt.

**Comment by wwark** [comment]
Hello,

Les deux assets (type vidéos) proposés sur le site web de 6play sont un MPD et un M3U8.

* Cas M3U8 que nous n'utilisons pas dans les replays car ce M3U8 est protégé par le DRM SAMPLE-AES non géré par le moteur Vidéo de Kodi.

>#EXTM3U
#EXT-X-VERSION:5
## Created with Unified Streaming Platform(version=1.9.6)
#EXT-X-SESSION-KEY:METHOD=SAMPLE-AES,URI="skd://clip_12648959?keyId=936d8f18a32da3b73320f864c461d77c",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"

# AUDIO groups
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio-aacl-93",NAME="LV",LANGUAGE="fr",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="2"

# variants
#EXT-X-STREAM-INF:BANDWIDTH=419000,CODECS="mp4a.40.2,avc1.42001E",RESOLUTION=400x226,FRAME-RATE=25,AUDIO="audio-aacl-93",CLOSED-CAPTIONS=NONE
Zone-interdite_c12648959_Changer-de-vie-tout-_drmnp-audio1=93468-video_eng=301000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=949000,CODECS="mp4a.40.2,avc1.42001E",RESOLUTION=640x360,FRAME-RATE=25,AUDIO="audio-aacl-93",CLOSED-CAPTIONS=NONE
Zone-interdite_c12648959_Changer-de-vie-tout-_drmnp-audio1=93468-video_eng=801000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1691000,CODECS="mp4a.40.2,avc1.42001E",RESOLUTION=720x406,FRAME-RATE=25,AUDIO="audio-aacl-93",CLOSED-CAPTIONS=NONE
Zone-interdite_c12648959_Changer-de-vie-tout-_drmnp-audio1=93468-video_eng=1501000.m3u8

# keyframes
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=40000,CODECS="avc1.42001E",RESOLUTION=400x226,URI="keyframes/Zone-interdite_c12648959_Changer-de-vie-tout-_drmnp-video_eng=301000.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=107000,CODECS="avc1.42001E",RESOLUTION=640x360,URI="keyframes/Zone-interdite_c12648959_Changer-de-vie-tout-_drmnp-video_eng=801000.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=199000,CODECS="avc1.42001E",RESOLUTION=720x406,URI="keyframes/Zone-interdite_c12648959_Changer-de-vie-tout-_drmnp-video_eng=1501000.m3u8"

**Comment by Europe57** [comment]
Salut,

Ok merci pour l'information. Dommage quand même que l'API de 6play ne montre que les formats SD alors que des vidéos HD existent. Enfin bref, merci pour toute les explications, je suis moins "bête" aujourd’hui 😉

Je mis connais pas suffisamment pour essayer de choper les informations sous Android, car sur Android TV, l'application 6play (choper d'une box Bouygues) fournit bien de la HD (qualité vidéo supérieur à 6play web, moins de pixellisation et débit internet visible sur la Freebox plus grand que sur 6play web).

A bientôt (sujet pouvant être clôturer si besoin)

**Comment by wwark** [comment]
Est-ce que c'est une application 6play dédié à la box Bouygues ou elle a été récupérée sur le playstore d'android ?

**Comment by Europe57** [comment]
C'est une application dédié pour la box de Bouygues (Miami si je ne me trompe pas), trouver sur le internet en .apk qui marche sur tous les boitier Android TV officiel (exemple : Xiaomi Mi Box, nVida Shield...)

Lien : https://www.sendspace.com/file/wtuxlv

**Comment by wwark** [comment]
So this application required an account from bouygues ?

**Comment by Europe57** [comment]
Non aucun compte n'est requis de Bouygues.

**Comment by wwark** [comment]
Ok en quoi cette application est dédiée à la box de Bouygues alors ?
Quelles sont les différences avec l'application présente sur le store offciel de Google ?

**Comment by Europe57** [comment]
6play ne veut pas d'application sur Android TV (comme myTF1 et encore récemment France.tv), alors les box sous Android TV ont dû avoir une application dédier pour leur box. Ce qui diffère c'est la compatibilité télécommande sous Android TV, le type de droit (je pense) car il y a le replay dit "premium" pour uniquement les FAI.

Après je ne sais pas si la qualité des flux est identique entre la version smartphone/tablette disponible uniquement sur le Play Store puisque je ne regarde pas la TV/Replay via un téléphone/tablette.

Par contre la dernière fois que je l'ai utilisé sur la TV via cette apps pour voir en replay du Paris Première, la qualité vidéo était de très bonne qualité (après je sais c'est subjectif, mais quand je compare au flux 6play web ou au 6play via l'extension la vidéo est meilleure).

Je parle de la version Android TV car je connais que celle-là qui propose de la belle qualité et donc sûrement un accès API/Manifest avec les flux HD.

Comme dit, la version smartphone/tablette a peut-être aussi cet accès, je ne peux pas le dire, je n’ai jamais regardé et même si je regarderais, sous un écran de smartphone ce n’est pas trop facile de dire si vraiment en HD.

**Comment by wwark** [comment]
Ok je comprends merci pour toutes ces informations.
Nous allons regarder avec ce APK pour voir ce qu'on peut trouver.

**Comment by Europe57** [comment]
En complément d'information :

Exemple pour : https://www.6play.fr/pekin-express-p_945 sur PC = 5 vidéos dispo, pour renvoie vers le FAI (bande annonce).

https://www.6play.fr/pekin-express-p_945/6-saisons-mythiques-en-integralite-dans-vos-offres-tv-c_12616123

Sur Android TV (via l'apk) : 

![6play sur Android TV](https://www.zupimages.net/up/20/33/h4b1.png)

Qualité sur Android TV :

![Qualité Android TV](https://www.zupimages.net/up/20/33/xn0n.png)

Qualité sur 6play.fr :

![Qualité 6play.fr](https://www.zupimages.net/up/20/33/7hv4.png)

**Comment by Che-debarras** [comment]
Le problème vient de l'addon qui est mal foutu.
J'utilise hola vpn sur android box tv
Et j'ai regardé la nouvelle saison de bull sur rtlplay en 720p
Donc c'est pas un souci de la chaine ou des applications 
C'est justz cette addon qui est mal fait
Sauf que avec Hola Vpn vous aurez un souci de maxrequest exceeded que les devs ne savent pas résoudre ou ne veut pas résoudre 

D'après @wwark il veut pas toucher l'addon car il a peur que ça ne marche plus pour lui et je parle de la version beta censé corrigé ou amélioré donc la version release risque de ne pas corriger votre souci de résolution. 

Avec hola vpn sur android box tv j'ai bien une résolution de 720p pour le replay

**Comment by sy6sy2** [comment]
Bonjour @Che-debarras,

> Le problème vient de l'addon qui est mal foutu.

Gardez à l'esprit que cet add-on est développé sur notre temps libre et sans aucune rémunération.
Nous ne sommes pas le Groupe M6, nous n'avons pas accès à la documentation de leur API donc un gros travail de "reverse" est nécessaire pour chaque chaine afin de comprendre comment la liste des vidéos et les flux vidéos sont distribués sur les sites et applications officiels. Ce n'est pas aussi simple que ça et surtout ça prend du temps !

Nous faisons tout notre possible pour garder une structure du code propre afin d'encourager d'autres personnes à participer au développement et proposer des améliorations via les pull request.
Si vous trouvez le plugin "mal foutu" alors n'hésitez pas à proposer des améliorations, nous les étudierons avec plaisir.

Encore une fois, ce plugin est maintenu et évolue seulement car nous en avons envie, rien n'y personne nous y oblige.

> D'après @wwark il veut pas toucher l'addon car il a peur que ça ne marche plus pour lui et je parle de la version beta censé corrigé ou amélioré donc la version release risque de ne pas corriger votre souci de résolution.

Euh, je ne crois pas avoir vu dans la conversation en amont que wwark souhaite "ne pas toucher au code" par peur de "tout casser". Au contraire, nous essayons de faire le nécessaire pour proposer toujours plus de contenu et avec la meilleur qualité possible.


Je trouve personnellement que c'est assez facile de critiquer le développement d'un plugin qui utilise des sources gratuites de façon légal alors qu'en regardant un peu votre profil GitHub vous participer activement à des issues d'un plugin vidéo Kodi dont les sources sont plus que douteuses...

À bon entendeur.

**Comment by Che-debarras** [comment]
Désolé mais sortir le coup du temps libre  n'est pas une excuse.Vous avez décidé de partager cette addon et de demander des retoursEt quand on fait un retour vous chercher une excuse pour pas résoudre le problèmeComme dit MacRoy ça marche pour lui alors inutiles de changer le code.Je dis pas que c'est simple mais on voit clairement le manque de volonté pour résoudre le problème et de connaissance du problemeDonné des explications avant meme d'avoir lu le log ou avoir reproduit le probleme montre que vous n'avez pas la volonté d améliorer l'addon.Le bug du maxirequest n'est en rien lié a la connexion ou vpn, il avoue lui meme que ce maxirequest est limité sur le plugin testPlutot que de dire des le début que c'est une limitation du plugin il m'a fait perdre mon temps avec les logs et des msg inutileDésolé mais j'ai pas l'impression qu'il connait le code de l'addon pour ne pas savoir ce qu'est le maxirequest.Autrement dit, s'il n'est pas l'auteur de cette addon qui fasse preuve d'humilité et qu'il ne complique pas les choses avec son ignoranceJe suis venu justement dire le souci sur l'addon et apres c'est a vous de chercher la cause et la solutionEt si wwark à ecrit qu'il veut pas toucher car ça marche sans vpnBref, c'est facile a critiquer quand ya aucune volonté de votre part a resoudre les vrais bugs.J'ai mentionné le problème et je n'ai pas vu de motivation pour resoudre le problème Maintenant on se demande s'il faut utiliser un vpn ou non si c que sur android ou pc que votre addon fonctionne La moindre des choses c'est de tester par vous meme avec le même matériel pour voir le bug car visiblement wwark utilise pc et il est sûrement de belgique vu qu'il utilise pas de vpn ou alors faut expliquer comment on peut regarder les chaines sans vpn Etc. Etc.etc Ça a l aire confus vos explications.En tout cas j'ai voulu tester votre addon et je peux dire qu'il est inutile sauf pour vous puisque cela marche pour vous et pas pour la majorité des  utilisateursPrenez exemple sur l'addon Vstream qui cherche vraiment a resoudre tout les bugs même pour l'ensemble de la communauté.J'ai plus l'impression que vous chercher des beta testeurs pour améliorer vos versions personnels de l'addon pour votre unique utilisation JE VOUS CONSEILLE DE PRENDRE DU RECUL ET DE CORRIGER LES BUGS DE BASE C'EST A DIRE LANCER LES CHAINES ET REPLAY EN DEHORS DES PAYS DE LA CHAINE ET DE FOURNIR UN TUTO ET OUTILS NÉCESSAIRES POUR QUE L'UTILISATEUR FINAL SUR ANDROID PUISSENT L'UTILISERMALHEUREUSEMENT VOTRE ADDON NE REPOND PAS A CETTE OBJECTIVE.VOUS CRITIQUEZ VSTREAM MAIS COMME VOUS DITE LA CRITIQUE EST FACILE ET LA SOURCE N'EST PAS PLUS DOUTEUSES QUE LE VOTRE.JE PENSE PAS QUE VOUS PAYER UNE REDEVANCE OU UN DROIT DE PARTAGE DE CES CHAINES QUE VOUS PIRATER POUR LE DIFFUSER EN DEHORS DE LEUR PAYS OU SANS ABONNEMENT.VSTREAM EST JUSTE UN ANNULAIRE COMME GOOGLE YAHOO BING QUI AFFICHE DES SITES INTERNET SANS LES HÉBERGER DONC LA SOURCE EST UNE SOURCE LEGAL QU'ON APPELLE INTERNET.VOS CHAINES TV NE PROVIENT PAS D'INTERNET MAIS DES CHAINES TV QUE VOUS DÉTOURNEZ.DONC EVITER DE CRITIQUER QUAND C'EST VOUS QUI ETES DOUTEUX
-------- Message d'origine --------De : Sylvain CECCHETTO <notifications@github.com> Date : 17/09/2020  10:10  (GMT+01:00) À : "Catch-up-TV-and-More/plugin.video.catchuptvandmore" <plugin.video.catchuptvandmore@noreply.github.com> Cc : Che-debarras <bledyfate@me.com>, Mention <mention@noreply.github.com> Objet : Re: [Catch-up-TV-and-More/plugin.video.catchuptvandmore] Plusieurs
  questionnement pour 6play/RTLPlay (#344) 

Bonjour @Che-debarras,



Le problème vient de l'addon qui est mal foutu.



Gardez à l'esprit que cet add-on est développé sur notre temps libre et sans aucune rémunération.

Nous ne sommes pas le Groupe M6, nous n'avons pas accès à la documentation de leur API donc un gros travail de "reverse" est nécessaire pour chaque chaine afin de comprendre comment la liste des vidéos et les flux vidéos sont distribués sur les sites et applications officiels. Ce n'est pas aussi simple que ça et surtout ça prend du temps !

Nous faisons tout notre possible pour garder une structure du code propre afin d'encourager d'autres personnes à participer au développement et proposer des améliorations via les pull request.

Si vous trouvez le plugin "mal foutu" alors n'hésitez pas à proposer des améliorations, nous les étudierons avec plaisir.

Encore une fois, ce plugin est maintenu et évolue seulement car nous en avons envie, rien n'y personne nous y oblige.



D'après @wwark il veut pas toucher l'addon car il a peur que ça ne marche plus pour lui et je parle de la version beta censé corrigé ou amélioré donc la version release risque de ne pas corriger votre souci de résolution.



Euh, je ne crois pas avoir vu dans la conversation en amont que wwark souhaite "ne pas toucher au code" par peur de "tout casser". Au contraire, nous essayons de faire le nécessaire pour proposer toujours plus de contenu et avec la meilleur qualité possible.

Je trouve personnellement que c'est assez facile de critiquer le développement d'un plugin qui utilise des sources gratuites de façon légal alors qu'en regardant un peu votre profil GitHub vous participer activement à des issues d'un plugin vidéo Kodi dont les sources sont plus que douteuses...

À bon entendeur.

**Comment by MajesticTM** [comment]
Bonjour,

Si vous avez besoin de quelqu'un pour tester avec 6play et un abondement direct teva ou paris première (sans lien à free, bouygues...), je me propose. Je peux prendre l'abonnement déjà 1 mois pour faire un test.

**Comment by wwark** [comment]
Bonjour @MajesticTM ,

Comme indiqué dans les messages au dessus, nous devons être autonome sur le compte pour implémenter ces nouvelles chaines et les tester dans la durée.

Nous devons trouver un moyens pour financer cet abonnement (ainsi que les futurs) tout en gardant une autonomie du temps que l'on veut passer à travailler sur le plugin.

On avait pensé à un patréon mais ceux qui vont y participer demanderons surement des modifications et des corrections etc ... 

L'autre problématique si la chaine ne fonctionne plus sur le plugin et qu'on ne trouve pas de solution des personnes vont utiliser de l'argent sans pouvoir y accéder depuis le plugin ....

Merci,
Wwark

**Comment by MajesticTM** [comment]
Bonjour,

OK je n'avais pas compris votre souhait d'indépendance le dessus. Je comprends qu'effectivement pour vous, ca serait plus facile. 

En tout cas, si jamais vous changez d'avis, n'hésitez pas!!!

Bon courage pour la suite. Cette extension est top!

**Comment by gromez** [comment]
@Europe57 pour info je viens de faire une PR pour améliorer un peu la qualité du replay 6play : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/399

Je n'ai pas testé tous les programmes, mais sur ceux que j'ai testé ça passe en 720p. Si jamais tu connais des sources pour lesquelles tu es sûr qu'elles sont en 1080p je pourrais faire le test :)

**Comment by Europe57** [comment]
@gromez merci, par contre pour les 1080p c'est une supposition car a un moment quand j'utilisais l'app 6play sur Android TV, le débit que la box débitais pour 6play était supérieur au débit 720p et la qualité avait l'air bien meilleur. Je ferais des tests pour voir si je trouve une vidéo qui demande plus de débit, mais de mémoire c'étais surtout sur les séries inédites. Si je peut je fait des essai ce soir ou demain.

Encore merci pour ce PR, les vidéos vont être de meilleures qualités :)

**Comment by Europe57** [comment]
@gromez désolé, j'en ai pas trouvé, peut être un test ou alors une mise en cache plus important ce jour là vu le début utilisé. Après 720p c'est déjà bien mieux que le SD qui est proposé. Merci beaucoup.

**Comment by wwark** [comment]
Merci @gromez ! Le PR a été mergé je vais préparer la nouvelle beta !

**Comment by wwark** [comment]
@Europe57 ce sont les API d'android qui sont utilisés maintenant

**Comment by gromez** [comment]
@wwark pas de problème, si je peux aider autant le faire 🙂
J'ai aussi une autre version qui simule la bbox mais par contre j'ai l'impression que la résolution est inférieure mais que le bitrate est quant à lui supérieur, il faut que je fasse davantage de tests.

**Comment by Europe57** [comment]
@wwark @gromez Merci à vous deux !

**Comment by joaopa00** [comment]
Est-ce que le problème est résolu maintenant?

**Comment by Europe57** [comment]
Pour la qualité 720p oui, depuis longtemps, pour Téva/Paris Première, 6play à enlever cette possibilité depuis quelques mois. Je pense que le sujet peut être clôturer, tout a été évoquer/régler/expliquer. Merci.

**Comment by joaopa00** [comment]
Merci pour le retour. Je ferme.
