### ISSUE TITLE
Problème avec TF1

### ISSUE THREAD

**Issue by Deep-Core** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#35]
Bonjour,

J'ai essayé de regarder le dernier match de l'équipe de France en replay sur TF1 (Allemagne/France) et au final on tombe sur le LiveTV de TF1 !

J'utilise Kodi Krypton et la dernière version de la branche dev.

Merci pour cet add-on.

**Comment by wwark** [comment]
Bonjour @Deep-Core,

Merci pour avoir remonter ce cas. J'ai testé et je reproduis bien ce compotement.
Nous regardons pour voir comment corriger ce cas.

Encore merci,
Wwark

**Comment by wwark** [comment]
Un fix a été commité sur la branche de développement. (https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/d8646d223dc8eeb441cdb5a08295a09a7a598bbe)
J'ai testé plusieurs Replay du groupe TF1 et pour l'instant ça à l'air de bien se comporter.
@Deep-Core, pourriez-vous tester ?

Wwark

**Comment by Deep-Core** [comment]
Désolé pour le retard.

Je viens d'essayer sur le replay du match en question et j'ai maintenant un message d'erreur qui s'affiche "Playback failed One or more items failed to play. Check the log for more information about this message".

J'ai essayé également le dernier replay de Koh-Lanta, celui du 24 novembre, et c'est la même chose. Même message.

S'agit-il d'un problème de DRM ?

Je suis avec une NVidia Shield et je sais pas où sont les logs donc malheureusement je peux pas trop vous aider...
Testé avec la version 0.1.8~beta002.

**Comment by wwark** [comment]
Je confirme que ce n'est pas un problème de DRM ces vidéos ne sont pas protégées par DRM.

J'ai aussi une Nvidia Shield avec SPMC 17.6 alpha1 et SMPC 16.7.1 et les tests sont positifs sur les deux cas.

Nous allons avoir besoin des logs si le problème est toujours présente. Dans ce lien http://kodi.wiki/view/Log_file/Advanced, il y a l'emplacement des logs.

Est-ce que vous avez Kodi installé sur un autre environnement (Windows, etc ...) pour voir si le problème est aussi présent ?

Wwark

**Comment by Deep-Core** [comment]
Alors voilà un log...
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/1504042/kodi.log)

**Comment by wwark** [comment]
Est-ce que la version de kodi a été mise à jour depuis l'ouverture de ce ticket ?

J'ai installé la version Kodi 17.6 sur Nvidia Shield et j'ai eu le même genre de log et après vérification je n'avais pas activé dans les addons les input stream adaptive. 
Après avoir activé les deux options de l'image, le replay est de nouveau fonctionnel.
![screenshot at 2017-11-26 18-52-00](https://user-images.githubusercontent.com/469461/33242826-0ba0374e-d2db-11e7-868d-8f4e1a68c4c8.png)

**Comment by Deep-Core** [comment]
Effectivement depuis l'ouverture du ticket, la Shield s'est mise à jour ainsi que Kodi (de la version 17.5 vers 17.6).

En activant l'InputStream Adaptive, tout est rentré dans l'ordre !

On peut fermer le ticket. Merci.

**Comment by wwark** [comment]
Cool ! Le comportement a surement changé sur Kodi entre la version 17.5 et 17.6.
Je pense qu'on risque d'avoir des personnes dans ce cas.

Je ferme donc ce ticket merci pour les tests !

Wwark

**Comment by DIDIERBZH78** [comment]
Bonjour a tous,
je suis nouveau sur le blog et je ne sais pas si mon probleme a deja etait vu.
j'ai installé KODI 16 et 17 sur mon QNAP251 et ainsi que sur mon PC.. j'ai installé Catchup TV & More et sur toutes mes installes et j'ai toujours les memes problemes;
1 j'ai pas toutes les chaines ... par exemple y a pas M6
2 Sur l'ensemble des chaines tres peu fonctionnent, pas une chaine de France TV ne marchent  , TF1 et LCI marchent... bizarre !!
Y a t il qq'un qui peut me dire comment regler ca ?
au fait pour info je suis a Lisbonne Portugal

**Comment by wwark** [comment]
Bonjour,
Es-ce qu'il possible d'ouvrir un ticket sur une nouvelle issue celle ci est déjà fermé ?
Je pense que vous parlez des directs TV.
Les direct TV du groupe M6 ne sont pas disponibles car bloquer par DRM.
Autre point, une majorité des direct TV et des replays sont géolocalisés. Il faut donc utiliser une IP du pays pour accéder à certains contenus.
Le faite que vous soyez au portugal implique que certains contenus ne sont pas disponibles.

Merci,
Wwark

**Comment by DIDIERBZH78** [comment]
Bonjour,
Merci pour votre réponse rapide donc si je comprends bien y a pas de solution sauf peut être utiliser un vpn ,
Lequel vpn pour Kodi suggérez-vous dans mon cas ? Pour pouvoir avoir toutes les direct TV française accessible depuis le Portugal.
Merci

**Comment by wwark** [comment]
Il existe des VPN gratuit, des VPN où vous pouvez tester gratuitement durant quelques jours.
cela peuvent être testé. 
Il est difficile de prévoir si le VPN marchera pour tous les directs.
Tu peux aussi soucrire pour un VPS en france et avoir un IP française dédié à l'utilisation personnel

**Comment by DIDIERBZH78** [comment]
J'ai pris un abonnement d'un mois chez PrivateVPN et l'ai installé comme j'ai pu dans KODI...!! pas sur d'avoir fait tout ce qu'il faut mais le résultat n'est pas probant ... les direct tv de France TV ne marchent toujours et sauf France Info mais avec une qualité d'image tres mauvaise..!!
Entre la setting de OpenVPN, le setting de Catch-Up TV partie VPN et le setting systeme de kODI vpn je n'y perds un peu !! Y a t il un tuto la dessus ?? ci joint qq photos ou j'essaie de voir France 2 et mes settings VPN... si qq un a une solution.. 
Au fait c'est quoi un VPS ?? comment ca marche ? ou peut on en acheter ?
Merci

![img_20180509_161534](https://user-images.githubusercontent.com/39096423/39824817-2a8f55d8-53a8-11e8-880c-625c98da1907.jpg)
![img_20180509_161732_1](https://user-images.githubusercontent.com/39096423/39825248-3e0673f2-53a9-11e8-8a1c-dce46b59790b.jpg)
![img_20180509_162311_1](https://user-images.githubusercontent.com/39096423/39825364-8978a026-53a9-11e8-8e2a-6203485447e8.jpg)

**Comment by wwark** [comment]
Pour le VPS je ne donnerais que le lien wiki https://en.wikipedia.org/wiki/Virtual_private_server
c'est une solution difficile à mettre en place.

1er point point la configuration du deuxième screenshot n'est pas utile. Il faut la supprimer.
2ème point, le plugin VPN Manager indique une erreur sur l'exécutable openvpn. L'exécutable openvpn est un pré-requis pour utiliser ce plugin. Vous utilisez quoi comme OS (Android?) sur la télé pour exécuter Kodi ? 

Le test simple est déjà à effectuer en dehors de Kodi.
- Sur votre PC (windows ?) installer l'application proposée par PrivateVPN (https://privatevpn.com/fr/pourquoi-privatevpn/voir-notre-logiciel)
- Choisir une IP française dans l'application
- vérifier qu'on est bien en france avec https://whatismyipaddress.com/
- Tester sur le site web de FranceTV que le direct TV de France2 fonctionne.
- Si ce point marche, il suffit sur le même PC avec l'application de PrivateVPN connecté en France de lancer Kodi et tester le Direct TV de France2 via le plugin.

Si ce test est passant, nous regardons pour faire fonctionner VPN Manager dans un second temps.

Merci,
marc.
