### ISSUE TITLE
Replay du Canada hors service

### ISSUE THREAD

**Issue by Europe57** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#354]
### Describe the bug
A clear and concise description of what the bug is: Plusieurs replay ne ce lance plus du tout (sous adresse IP Canadienne)

- Télé-Québec
- TVA
- ICI Télé (Montréal), celui là n'ouvre plus aucune page, message d'erreur

### To Reproduce
1. Lancement de la lecture de n'importe quel vidéo des services citez ci-dessus
2.
3.
4.

### Expected behavior
A clear and concise description of what you expected to happen: La lecture des vidéos

### Actuel behavior
Tell us what happens instead: Aucune lecture ne ce lance (sans aucune erreur en info)

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Other

 - Operating system version/name: Android 9.0 / Windows 10
 - Kodi version: 18.8 / 18.8 (version bureau)
 - Catch-up TV & More version: 0.2.25
 - Installation method: Reposite officiel

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by wwark** [comment]
Hello,

TVA et Télé Quebec fonctionnent chez moi. Si vous passez par un VPN il se peut qu'il y ait des soucis.
Le VPN ne veut pas dire que ça va fonctionner. Ce point dépend du serveur et du fournisseur et ça peut marcher une jour et pas l'autre.
Pour ICI Télé (Montréal) il y a un soucis de parcours de la chaine. Nous allons regarder pour corriger.

Cordialement,

**Comment by Europe57** [comment]
Salut @wwark 

Bah en faite c'est bizarre car j'utilise normalement l'extension Télé-Québec sous le même VPN, les vidéos passent. Possible que l'extension Télé-Québec récupère autrement les vidéos, qui passe sous mon VPN.

Pour TVA, j'ai tester via le navigateur web sous le même VPN, les vidéos ce lancent.

J'ai pensé tout naturellement à un soucis.

Merci pour votre réponse, et désolé du dérangement.

**Comment by Europe57** [comment]
Complément d'info pour Télé-Québec, ça serais uniquement les nouveaux épisodes.

Exemple :

De gardes 24/7 - Épisode 001 - Covid, le calme avant la tempête (premier épisode de la saison 6), ne ce lit pas
De gardes 24/7 - Épisode 052 - La dernière ligne (dernier épisode de la saison 5), ce lit sans soucis

Idem sur l'extension Télé-Québec

**Comment by wwark** [comment]
Merci pour ces nouveaux tests. 
Pour la vidéo De 24/7 Episode 001 - COvid xxx. On a un HTTP 404 (non disponible) 
CCurlFile::**Open failed with code 404** for https://mnmedias.api.telequebec.tv/m3u8/55859.m3u8

Sur le site web je n'arrive pas à la lire (https://zonevideo.telequebec.tv/media/55859/covid-le-calme-avant-tempete/de-garde-247)

Pour TVA, il faut du temps pour avoir le flux on peut tomber sur des timeout suivant la vitesse de la connexion avec le VPN. Il y a des options pour modifier ce timeout.

**Comment by Europe57** [comment]
Y a pas de quoi.

Pour Télé-Québec il faudrait quoi comme information ? N'ayant pas trop de compétence là-dedans, je peux toujours essayer de trouver des infos, vu que j'arrive a lire les vidéos.

J'ai aussi vu qu'Hola VPN arrive à lire aussi les vidéos (tester sous une petite VM, je sais qu'il on pas bonne réputation, d'où le test sous VM).

Désolé de pas trop aider.

Pour TVA, je vais voir ça en détail, merci pour l'astuce.

**Comment by wwark** [comment]
Il faudrait partager les log en mode debug de Kodi.

Merci !

**Comment by Europe57** [comment]
La lecture des vidéos c'est via leur site web, donc hors de Kodi, mais si y a des logs du site web à récup ou autre et si il y a une procédure à suivre pour le fournir.

J'ai un peu fouiller les entrée "Network" seul API que je trouve c'est sur le player (https://mnmedias.api.telequebec.tv/api/v4/player/55859) qui est lancer par Tq_VideoPlayer.js (https://player.telequebec.tv/Tq_VideoPlayer.js) avec une playlist.

Playlist : https://bcovlive-a.akamaihd.net/86e93a0ab79047e1b216e2b0a1ac5363/us-east-1/6150020952001/playlist.m3u8

Après honnêtement, je sais pas si ça peut être utile, là je navigue sans connaître et sans GPS.

**Comment by wwark** [comment]
Juste pour confirmer, vous arrivez à lire "De gardes 24/7 - Épisode 001 - Covid, le calme avant la tempête" depuis le site internet  de telequebec ?
Moi je n'y arrive pas via le navigateur et j'ai un HTTP 404 "contenu indisponible" via Kodi.

Merci,

**Comment by Europe57** [comment]
Oui, je confirme la lecture vidéo ce fait bien sur le navigateur.

![Épisode 0001](https://nsa40.casimages.com/img/2020/09/12/200912015531580108.png)

**Comment by wwark** [comment]
Merci il faut que je trouve comment faire fonctionner cette vidéo pour corriger.
Sinon ICI Télé a été corrigé et la correction sera disponible dans la prochaine bétâ.

**Comment by Europe57** [comment]
Merci pour la correction d'ICI Télé.

Pour Télé-Québec, je sais que c'est pas très bien comme VPN mais Hola VPN fonctionne pour la lecture de cette vidéo. Par contre je conseil de cloisonner l'extension pour navigateur, utilisation d'une VM par exemple, marche sous un mini Linux sans soucis.

Sinon en VPN j'utilise actuellement NordVPN en serveur "Obfuscated" ca1208, ça peut presque tout lire comme site géobloqué.

**Comment by Europe57** [comment]
J'ai un log Kodi avec la lecture de Télé-Québec avec l'épisode "De gardes 24/7 - Épisode 001 - Covid, le calme avant la tempête"

[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/5214171/kodi.log)


Via l'extension de Télé-Québec parler ultérieurement ça remarche, surement un soucis de VPN le jour du test, mais là ça tourne via cette extension.

Lien de l'extension si ça peut aider : https://github.com/dualB/plugin.video.telequebec

**Comment by wwark** [comment]
Une correction pour téléquebec a été apportée dans la dernière béta.
Merci pour toutes ces informations.

**Comment by Europe57** [comment]
Merci beaucoup à vous pour cette correction rapide.

Pour TVA problème résolut chez moi, je doit juste lancer 2x la vidéo pour que ça passe.

**Comment by wwark** [comment]
Cool je ferme le ticket !
N'hésite pas le rouvrir si besoin :)
