### ISSUE TITLE
Tv replay "Maxredirect"

### ISSUE THREAD

**Issue by Che-debarras** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#356]
### Describe the bug
When I click to see a replay ex season 4 of Bull (RTLplay) after one épisode I cannot watch the 2nd épisode and a message appears :" max repeat exceeded.

Normally a replay can be watcg for one week not only one episode

### To Reproduce
1. Go to tv replay 
2. Choose Belgium/rtlplay
3. Select Serie/Bull /season 4
4. Play one episode 

### Expected behavior
It should play another episode without issue 

### Actuel behavior
Unable to play another episode neither after the previous one nor a day after like today. It plays only one episode and we have a message of max repeat exceed

### Your environment
 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: Android 7.1
 - Kodi version: 18.8
 - Catch-up TV & More version: latest beta
 - Installation method: from repo

**Comment by wwark** [comment]
Hi @Che-debarras,

Are you in Belgium ? Did you use a VPN or a proxy ?
I can't manage to reproduce this issue.
Could you please share the debug log of Kodi ?

Thanks,

**Comment by Che-debarras** [comment]
No but I use a vpn to change location (hola vpn)https://paste.kodi.tv/ebilefecabIs it enough ?
-------- Message d'origine --------De : Marc Roy <notifications@github.com> Date : 16/09/2020  12:54  (GMT+01:00) À : "Catch-up-TV-and-More/plugin.video.catchuptvandmore" <plugin.video.catchuptvandmore@noreply.github.com> Cc : Che-debarras <bledyfate@me.com>, Mention <mention@noreply.github.com> Objet : Re: [Catch-up-TV-and-More/plugin.video.catchuptvandmore] Tv replay
  "Maxredirect" (#356) 
Hi @Che-debarras,
Are you in Belgium ? Did you use a VPN or a proxy ?
I can't manage to reproduce this issue.
Could you please share the debug log of Kodi ?
Thanks,

**Comment by wwark** [comment]
Sorry the paste bin is empty.
Meanwhile, your issue maybe be link to your connection throught the VPN.

Thanks,
Wwark

**Comment by Che-debarras** [comment]
I never have issue with my connection through vpn.It is advised to use vpn hence the issue is not from vpnIt plays a tv show if I delete cache from my vpn app + addon cache and restart vpnIf it plays one episode why it wont play another or need to delete caches from addon and vpn?To me the issue is from your addon.You can reproduce this issue by used a android device and launch kodi from hola vpn app (choose belgium) and then select replay tv untii Bull tv show and you will see the notification of "max request exceeded"Thank you anyway
-------- Message d'origine --------De : Marc Roy <notifications@github.com> Date : 16/09/2020  19:27  (GMT+01:00) À : "Catch-up-TV-and-More/plugin.video.catchuptvandmore" <plugin.video.catchuptvandmore@noreply.github.com> Cc : Che-debarras <bledyfate@me.com>, Mention <mention@noreply.github.com> Objet : Re: [Catch-up-TV-and-More/plugin.video.catchuptvandmore] Tv replay
  "Maxredirect" (#356) 
Sorry the paste bin is empty.
Meanwhile, your issue maybe be link to your connection throught the VPN.
Thanks,
Wwark

**Comment by wwark** [comment]
I said may.
Me I used another VPN and I can't reproduce your issue.
@jmzambon, do you manage to reproduce this issue with your connection without VPN ?
The log will help to get the url of the stream which implied this issue.
With this url we might test it to another program or outside the plugin in Kodi with your connection.

**Comment by Che-debarras** [comment]
I am in France . Without vpn I havent accessI will send you the log made by kodi if you tell me where to find it Thanks 
-------- Message d'origine --------De : Marc Roy <notifications@github.com> Date : 16/09/2020  20:33  (GMT+01:00) À : "Catch-up-TV-and-More/plugin.video.catchuptvandmore" <plugin.video.catchuptvandmore@noreply.github.com> Cc : Che-debarras <bledyfate@me.com>, Mention <mention@noreply.github.com> Objet : Re: [Catch-up-TV-and-More/plugin.video.catchuptvandmore] Tv replay
  "Maxredirect" (#356) 
I said may.
Me I used another VPN and I can't reproduce your issue.
@jmzambon, do you manage to reproduce this issue with your connection without VPN ?
The log will help to get the url of the stream which implied this issue.
With this url we might test it to another program or outside the plugin in Kodi with your connection.

**Comment by wwark** [comment]
You can use this link https://kodi.wiki/view/Log_file/Easy#Copy_and_Paste. You will find the place of the log for each OS.

Android | Note: The first folder might be different on various devices: /data/org.xbmc.kodi/cache/temp/kodi.log /sdcard/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log
-- | --

**Comment by Che-debarras** [comment]
https://slexy.org/view/s20OwYNGdX
I use the tools from Vstream it is a lengthy log but you may find what you need non?
-------- Message d'origine --------De : Marc Roy <notifications@github.com> Date : 16/09/2020  20:47  (GMT+01:00) À : "Catch-up-TV-and-More/plugin.video.catchuptvandmore" <plugin.video.catchuptvandmore@noreply.github.com> Cc : Che-debarras <bledyfate@me.com>, Mention <mention@noreply.github.com> Objet : Re: [Catch-up-TV-and-More/plugin.video.catchuptvandmore] Tv replay
  "Maxredirect" (#356) 
You can use this link https://kodi.wiki/view/Log_file/Easy#Copy_and_Paste. You will find the place of the log for each OS.



Android
Note: The first folder might be different on various devices: /data/org.xbmc.kodi/cache/temp/kodi.log /sdcard/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log

**Comment by Che-debarras** [comment]
https://paste.kodi.tv/acopohuhex

-------- Message d'origine --------De : Marc Roy <notifications@github.com> Date : 16/09/2020  20:47  (GMT+01:00) À : "Catch-up-TV-and-More/plugin.video.catchuptvandmore" <plugin.video.catchuptvandmore@noreply.github.com> Cc : Che-debarras <bledyfate@me.com>, Mention <mention@noreply.github.com> Objet : Re: [Catch-up-TV-and-More/plugin.video.catchuptvandmore] Tv replay
  "Maxredirect" (#356) 
You can use this link https://kodi.wiki/view/Log_file/Easy#Copy_and_Paste. You will find the place of the log for each OS.



Android
Note: The first folder might be different on various devices: /data/org.xbmc.kodi/cache/temp/kodi.log /sdcard/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log

**Comment by wwark** [comment]
The issue is on this url: http://pc.middleware.6play.fr/6play/v2/platforms/m6group_web/services/rtlbe_rtl_tvi/folders?limit=999&offset=0
This url permits to show all categories of each channel.

Could you please try this url in this tool https://reqbin.com/ ?
You need to set this header "x-customer-name: rtlbe" like the screenshot below.
![image](https://user-images.githubusercontent.com/469461/93381360-d5753a80-f860-11ea-80a0-d164b212c4bb.png)

The test needs to be done with your VPN and without your VPN.
Could you please also confirm you don't have this issue "max_repeat_redirects exceeded" without VPN meanwhile you can't play the stream without the VPN?

**Comment by wwark** [comment]
For information, the framework we used for this plugin test the number of redirect (4 times) and raised the issue. 
var int max_repeats: Max number of repeat redirects. Defaults to `4`

It means in your case (with VPN) to request this url http://pc.middleware.6play.fr/6play/v2/platforms/m6group_web/services/rtlbe_rtl_tvi/folders?limit=999&offset=0 there is more than 4 repeat redirect which is not good.

**Comment by Che-debarras** [comment]
You mean with the other version of plugin there is more than 4 of repeat possible?What it is the link between 6play and rtbf? I never see 6play replay.Can you allowed more than 4 repeats on this version test? ?
-------- Message d'origine --------De : Marc Roy <notifications@github.com> Date : 16/09/2020  21:27  (GMT+01:00) À : "Catch-up-TV-and-More/plugin.video.catchuptvandmore" <plugin.video.catchuptvandmore@noreply.github.com> Cc : Che-debarras <bledyfate@me.com>, Mention <mention@noreply.github.com> Objet : Re: [Catch-up-TV-and-More/plugin.video.catchuptvandmore] Tv replay
  "Maxredirect" (#356) 
For information, the framework we used for this plugin test the number of redirect (4 times) and raised the issue.
var int max_repeats: Max number of repeat redirects. Defaults to 4
It means in your case (with VPN) to request this url http://pc.middleware.6play.fr/6play/v2/platforms/m6group_web/services/rtlbe_rtl_tvi/folders?limit=999&offset=0 there is more than 4 repeat redirect which is not good.

**Comment by wwark** [comment]
For the first question I didn't know it depends how the plugin implement that part.

RTLPLay and 6Play share the mostly the same code. If you check both website, you will see similarity.

I prefer not changed code what work correctly without VPN but you can adapt the code of the framework on your side.

For that, you need to edit this file "urlquick.py" present in this directory "<DEPENDS_OS>/.kodi/addons/script.module.codequick/lib".
You searched this line "self.max_repeats = kwargs.get("max_repeats", 4)". You can increase up to 4 and test again until you find the correct value. I didn't know.
If the framework is updated you might have to redo this change.

Thanks

**Comment by Che-debarras** [comment]
I dont understand  you aim with this addonFirst you advice to use proxy or vpn and now you say it works without vpnYou are not clear or you dont care if we experience issues because it works for you.Now let's be honest: your addon is a shit because we need to be in the country of the tv channel but with iptv we dont need vpn or proxy When we have a issue , you are not able to find a solution or modify the addon because it works for you.You bored me with your messages and waste my time moreover with one message where you talked about copy and paste the log file with my pc.But you dont understand that we used box tv android and application for android and we only have vpn application like hola vpnYou have to optimise your addon for the most of us who use android device and but you are a bad déveloper if you are afraid to change the code because you fear it wont work without vpn.Your first msg asked me if I use vpn if i said no you would tell me this is  the issue and now i use vpn you said it worls without vpn ?A total lack of logical senseAnyway i will close this issue and remove you shitty addon
-------- Message d'origine --------De : Marc Roy <notifications@github.com> Date : 16/09/2020  22:44  (GMT+01:00) À : "Catch-up-TV-and-More/plugin.video.catchuptvandmore" <plugin.video.catchuptvandmore@noreply.github.com> Cc : Che-debarras <bledyfate@me.com>, Mention <mention@noreply.github.com> Objet : Re: [Catch-up-TV-and-More/plugin.video.catchuptvandmore] Tv replay
  "Maxredirect" (#356) 
For the first question I didn't know it depends how the plugin implement that part.
RTLPLay and 6Play share the mostly the same code. If you check both website, you will see similarity.
I prefer not changed code what work correctly without VPN but you can adapt the code of the framework on your side.
For that, you need to edit this file "urlquick.py" present in this directory "<DEPENDS_OS>/.kodi/addons/script.module.codequick/lib".
You searched this line "self.max_repeats = kwargs.get("max_repeats", 4)". You can increase up to 4 and test again until you find the correct value. I didn't know.
If the framework is updated you might have to redo this change.
Thanks

**Comment by sy6sy2** [comment]
Ah ok, je pense que j'ai répondu un peu vite sur l'issue #344 avant de voir votre joli message ici !

Je vais essayer de ne pas répéter ce que j'ai déjà dis dans le message https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/344#issuecomment-694072306 mais :

En grand merci pour ce beau et gentil message, c'est vraiment plaisant d'essayer de résoudre les problèmes des utilisateurs pour être remercié comme ça. Je ne sais pas si vous êtes dévelopeur ou si vous savez développer (en regardant un peu votre GitHub j'en doute fortement mais bon ...) mais dans tous les cas je pense que vous n'avez rien compris à l'esprit du logiciel libre et à l'entraide des utilisateurs et des développeurs.

Si vous ne trouvez pas votre bonheur ici, prenez une semaine pour apprendre le Python et développez vous même votre plugin ou bien continuez à utiliser les dizaines de plugin pirates qui existent pour Kodi.

Heureusement que la majorité des utilisateurs de ce plugin ne sont pas comme vous parce que sinon je pense que ce dépôt serait déjà archivé depuis un bon moment....

**Comment by Che-debarras** [comment]
Pathétique,  parce qu'on est pas développeur alors notre avis ne compte pas? Pas étonnant que votre addon n'avance pas mdrLogiciel libre? Mdr libre mais inutilisable et douteux donc je vois pas trop l'intérêt Vous recommencez avec le mot pirate hors le seule addon pirate c'est le votre car vous navez aucune autorisation pour diffuser des chaines sans le consentement de la chaine tVous pirater leur chaine pour avoir accès au lien et les diffuser sur le net c'est la définition meme de piratageEncore une fois vstream ne pirate rien, ce n'est qu'un annuaire de site tour comme google bing yahoo elle héberge aucun film serie tvChez vstream TOUT EST PUBLIC ET SUR INTERNET.Votre addon pirate les sites internets des chaines tv et meme les chaines tv elles mêmes sans le consentement des chaines ni abonnements ni payer le droit de diffusion.Persofaut reconnaître ses limites et vu votre addon vos reponses et absence de solution et de résolution et d'avancement je dirais que vous n'avez pas plus de connaissance en python que moi.Bref, utiliser votre temps libre pour réétudier python lol au lieu de lire 2 ou 3 phrases sur le sujet et vous lancer aveuglément et avec orgueil dans le développement de plugin.Sur ce ne repond plus car ça ne sert a rien
-------- Message d'origine --------De : Sylvain CECCHETTO <notifications@github.com> Date : 17/09/2020  10:27  (GMT+01:00) À : "Catch-up-TV-and-More/plugin.video.catchuptvandmore" <plugin.video.catchuptvandmore@noreply.github.com> Cc : Che-debarras <bledyfate@me.com>, State change <state_change@noreply.github.com> Objet : Re: [Catch-up-TV-and-More/plugin.video.catchuptvandmore] Tv replay
  "Maxredirect" (#356) 

Ah ok, je pense que j'ai répondu un peu vite sur l'issue #344 avant de voir votre joli message ici !

Je vais essayer de ne pas répéter ce que j'ai déjà dis dans le message #344 (comment) mais :

En grand merci pour ce beau et gentil message, c'est vraiment plaisant d'essayer de résoudre les problèmes des utilisateurs pour être remercié comme ça. Je ne sais pas si vous êtes dévelopeur ou si vous savez développer (en regardant un peu votre GitHub j'en doute fortement mais bon ...) mais dans tous les cas je pense que vous n'avez rien compris à l'esprit du logiciel libre et à l'entraide des utilisateurs et des développeurs.

Si vous ne trouvez pas votre bonheur ici, prenez une semaine pour apprendre le Python et développez vous même votre plugin ou bien continuez à utiliser les dizaines de plugin pirates qui existent pour Kodi.

Heureusement que la majorité des utilisateurs de ce plugin ne sont pas comme vous parce que sinon je pense que ce dépôt serait déjà archivé depuis un bon moment....

**Comment by sy6sy2** [comment]
Je me permets de répondre également à votre réponse https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/344#issuecomment-694106120 sur ce fil pour éviter de diverger.

> Vous avez décidé de partager cette addon et de demander des retours. Et quand on fait un retour vous chercher une excuse pour pas résoudre le problème. Comme dit MacRoy ça marche pour lui alors inutiles de changer le code.

En effet nous proposons aux utilisateurs de nous donner des retours car nous ne sommes que 2 ou 3 personnes à travailler sur ce plugin et il n'est pas toujours possible pour nous de tester toutes les chaines de tous les pays avec toutes les combinaisons différentes (matériel et pays d'utilisation).

> Désolé mais j'ai pas l'impression qu'il connait le code de l'addon pour ne pas savoir ce qu'est le maxirequest. Autrement dit, s'il n'est pas l'auteur de cette addon qui fasse preuve d'humilité et qu'il ne complique pas les choses avec son ignorance

Wwark connait très bien le code de l'addon car c'est lui qui apporte depuis pas mal de temps le plus de contributions à ce projet (je vous invite à faire un tour du coté des commits du plugin pour vous en rendre compte par vous même).
En effet vous avez raison, il n'est pas l'auteur initial de cet add-on, pour autant il y participe maintenant depuis plusieurs années et je peux vous assurer avec certitude qu'il connait mieux que moi le code de la majorité des chaines présentes dans ce plugin.

> Maintenant on se demande s'il faut utiliser un vpn ou non si c que sur android ou pc que votre addon fonctionne La moindre des choses c'est de tester par vous meme avec le même matériel pour voir le bug car visiblement wwark utilise pc et il est sûrement de belgique vu qu'il utilise pas de vpn ou alors faut expliquer comment on peut regarder les chaines sans vpn Etc. Etc.etc

Ce plugin n'a à la base pas été pensé pour être utilisé avec un VPN. En effet, une bonne partie des chaines son geo-bloquée (comme c'est le cas sur leurs sites officiels). L'idée de base est la suivante : Je suis français, j'habite en france, je veux le replay de M6 --> ça fonctionne. Je suis Belge, j'habite en Belgique, je veux le replay de RTL-TVI --> ça fonctionne. L'idée c'est de regroupé dans un seul plugin une solution simple permettant aux utilisateurs d'accéder aux direct TV et aux replay de LEUR pays de façon facile.
Après si vous voulez le direct d'une chaine USA depuis la France et qu'elle n'est pas géo-bloqué alors tant mieux, mais si elle l'est alors soit vous abandonné l'idée, soit vous vous débrouillez avec un VPN.
En effet, un petit disclaimer indiquant ce que je viens de dire ne serait pas de trop, nous allons peut être y réfléchir.

> Vous recommencez avec le mot pirate hors le seule addon pirate c'est le votre car vous navez aucune autorisation pour diffuser des chaines sans le consentement de la chaine tVous pirater leur chaine pour avoir accès au lien et les diffuser sur le net c'est la définition meme de piratageEncore une fois vstream ne pirate rien, ce n'est qu'un annuaire de site tour comme google bing yahoo elle héberge aucun film serie tvChez vstream TOUT EST PUBLIC ET SUR INTERNET [...]

Notre plugin fonctionne exactement sur le même principe que Captvty, nous mettons à disposition du public des liens permettant d'accéder plus facilement aux contenus proposés GRATUITEMENT et LÉGALEMENT par les différents groupes TV. (voir ici https://captvty.fr/faq#legal). C'est à dire que le plugin agit en quelque sorte comme un navigateur qui va interroger les différents site web des groupes TV afin d'afficher le résultat dans Kodi.
Permettez moi d'insister mais, en effet, Vstream est considéré par la team Kodi comme un add-on dit "pirate". En effet vous avez raison, les dev de Vstream n'hébergent aucun contenu illégal, cependant ils mettent à disposition du public des vidéos qui ELLES, sont hébergées sur des sites de streaming illégales. (c'est même écrit sur ce site: https://blog-iptv.com/comment-installer-vstream-sur-kodi#Cet_addon_de_Kodi_est-il_illegal ( _Vstream est-il illégal ? Oui, l'addon Vstream sur Kodi est illégal. C’est pour cela que ses utilisateurs utilisent un VPN. Ils évitent les retours de leurs fournisseurs d’accès internet et TV, les enregistrements automatiques des données de navigation et les risques de hacking. Leur adresse IP étant cachée, ils restent totalement anonymes sur le web._).
Au passage, Vstream est bien présent dans la liste des repo blacklistés : https://kodi.wiki/view/Official:Forum_rules/Banned_add-ons

> Bref, utiliser votre temps libre pour réétudier python lol au lieu de lire 2 ou 3 phrases sur le sujet et vous lancer aveuglément et avec orgueil dans le développement de plugin

Concernant mes compétences en dev (ou celles de Wwark), nous ne prétendons pas être des "experts" mais je pense qu'une simple visite de nos profils GitHub permet de justifier à elle seule le fait qu'on sait au moins un peu se débrouiller sur le sujet, sinon ce plugin ne serait pas là...

Je voudrais quand même rappeler que nous ne prétendons pas "être les meilleurs" ou proposer "le meilleurs add-ons Kodi français" et que je sais-je encore.
Quand j'ai démarré ce projet, à la base exclusivement pour le replay des chaines francophones, c'était effectivement pour mon utilisation personnelle et je l'ai laissé sur GitHub afin d'en faire profiter les autres sans pour autant assurer aucune garantie quant à son fonctionnement.
Aujourd'hui le projet a grandit, proposant toujours plus de chaines, de pays et de fonctionnalités. Pour autant la philosophie du projet est restée la même : "Ce plugin est un logiciel libre, il est à la disposition de tous mais pour autant il n'y a aucune garantie de fonctionnement". Nous ne vendons pas un service.

**Comment by Che-debarras** [comment]
@sy6sy2 
Tu commence a devenir con et tu harcèles 
Les utilisateurs n'utilisent pas de vpn 
En aucun cas le vpn est obligatoire 
Donc quand on sait pas de quoi on parle on ferme sa gueule 
C'est du streaming via internet tout comme tes chaines tv 


Je commence a devenir vulgaire alors arrete de repondre 
Si jai fermé le sujet c'est pas pour rien
Jai pas lu tout ton msg de merde mais assez pour voir ton hypocrisie 

Car il me semble que pour utiliser votre addon faut un proxy et vpn mais pas vstream
J'utilise le vpn poir contourer la limitation de uptobox sinon ya pas besoin.
Et je suis sur que tu utilise vstream donc fait pas style que tu l'utilise pas

Vstream aussi agit comme un navigateur donc cesse d'être hypocrite car ya aucune oeuvre fourni avec vstream cest juste navigateur 
Est ce que google est illégal car il affiche des sites internet de streaming ou ddl? NON

C'est pas parce Kodi bloque un addon que l'addon est illégal,  Kodi na aucune autorité pour dire si c'est legal ou pas. Donc apprend a connaitre la loi avant de dire c legal ou non

Donc vstream est un navigateur qui nécessite pas de vpn ni proxy qui ne sert pas a télécharger et qui cache pas les ip et que Kodi ne bloque pas les addons mais les rends non officiel.

Pour infos on peut toujours installer les addons soit disans bloqué donc meme kodi sais que c'est legal la liste d addon bloqué.
Maintenant si on suis ta logique,Apple a bloqué Kodi sur son app store est ce que ca fait de Kodi une application illégal ?

J'avoue par moment que les conneries que vous débitez me faire ptdr


PEUT ON CLORE CE SUJET ET ARRETER DE ME REPONDRE ?
