### ISSUE TITLE
Télésambre

### ISSUE THREAD

**Issue by JerryCrazy** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#357]
### Content description

* Name: Télésambre
* Type: TV channel and Catch-up TV
* Website URL: https://telesambre.be
* Content language/country: French/Belgium

### Content access

- [ ] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [ ] This content is geographically restricted

**Comment by wwark** [comment]
Bonjour @JerryCrazy,

Nous venons de rajouter le Live TV dans la dernière betâ du plugin.
Il reste à rajouter le replay.

Merci

**Comment by JerryCrazy** [comment]
Merci à vous ! (désolé pour le temps de réponse, je ne reçois plus les notifications de GitHub)
