### ISSUE TITLE
Replay Auvio : error 400

### ISSUE THREAD

**Issue by eenbroleke** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#360]
Error 400 while selecting some replay from Auvio

If name of the show starts with "#" : "#Investigation" -> then fails
Elif it starts with alphanumeric char : it loads and starts to display 
src: https://paste.kodi.tv/ohifewipiv

**Comment by wwark** [comment]
Hi,
Thank you for the report. We reproduce the issue.
We will take a look to fix it.

**Comment by eenbroleke** [comment]
Thanks !
Were you able to reproduce the issue ?
It seems that there are various problem with replay too (try a RTBF evening news for instance).
