### ISSUE TITLE
[solved] Kodi Matrix Alpha 1 - Catchup TV and More not working on CentOS

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#361]
Can't play via the plugin

![catchup_Matrix](https://user-images.githubusercontent.com/31815445/94345519-b9bf2080-0026-11eb-8452-0c1d3689f6f2.png)

 - Operating system version/name: Linux CentOS 8.2
 - Kodi version: Matrix alpha 1
 - Catch-up TV & More version: 0.06 , can't upgrade
 - Installation method: via zip method (web site)

Question : is the plugin ready for Matrix, as it loads via interface ?

**Comment by enigma131** [comment]
Same via Leia Flatpak 18.7

**Comment by wwark** [comment]
Hi,
The addon is not ready for Matrix for the moment.
Could you please share the logs of Kodi for your test in Leia Flatpak 18.7 ?

Thanks,

**Comment by enigma131** [comment]
Fichier log pour la version Flatpak
https://paste.kodi.tv/kibiyubaqo.kodi
Remarque, il reste en version 0.06 quand je le mets à jour

**Comment by enigma131** [comment]
https://paste.kodi.tv/gusocuhuho.kodi

**Comment by wwark** [comment]
Ok. Je comprends mieux.
Il n'y a que le repository d'installer qui lui est en version 0.0.6.
Il faut aller dans le repository => Videos => Plugin CUTV&More et l'installer.
Est-ce que c'est à ce niveau que vous avez une erreur ?

**Comment by enigma131** [comment]
Il n'y est pas ...

**Comment by wwark** [comment]
Sous Matrix c'est normal car il n'est pas compatible.
Vous pouvez faire une capture d'écran de ce que vous avez pour Leia.
Sinon le plugin est aussi disponible sur le répo officiel de Kodi. Est-ce que vous le trouvez ?
![Screenshot from 2020-09-27 13-48-37](https://user-images.githubusercontent.com/469461/94364258-3ce48300-00c8-11eb-9f02-417f29111bab.png)

**Comment by enigma131** [comment]
Je n'ai rien dans la catégorie catégorie Video add-ons  (Mis en anglais).
J'ai fait search mot clé "Catch" et la il me l'as trouvé et installé sous flatpak 18.7.
Je vais continuer avec inputstream et tout tester en flatpak.

Sous Matrix, je dois faire aussi search, il me le trouve mais effectivement il ne s'installe pas.
Une nouvelle trace au cas ou, mais s'il n'y a pas moyen... https://paste.kodi.tv/acenageruz.kodi 
Le plugin hts plugins marche sous Matrix.

**Comment by wwark** [comment]
Et dans le repository officel de Kodi ?

**Comment by enigma131** [comment]
Avec Flatpak, toutes les chaines fonctionnent sauf celles du fameux groupe. J'ai installé le zip inputstream de l'autre fil pour linux mais visiblement ne fonctionne pas. Tu pense que je dois le recompiler ?

Avec Matrix, repository officiel ? En tous cas je suis candidat pour le faire fonctionner et tester, la version flatpak je voudrais m'en débarasser et le pire c'est qu'elle ne se met pas à jour, elle devrait être en version 18.8.

**Comment by enigma131** [comment]
edit.
Après reboot toutes les chaînes fonctionnent avec la version Flatpak.

Reste le développement avec Matrix, sachez que je suis la pour tester , vu qye j'ai compilé la version Matrix alpha 1 avec tous ses PVR.

**Comment by wwark** [comment]
Ok donc ça marche Leila. Cool !
Matrix le plugin n'existe pas car il n'est pas encore compatible on est entrain de bosser sur ce sujet. C'est normal que vous ne le voyer pas.
Centos a déjà basculer sur matrix ? Cette version est toujours en alpha. Il n'y a pas une version officiel de Leila dans le repo centos ?

L'addon inputstream adaptive est un addon binaire donc il faut prendre celui de de sa distribution. Flatpak l'a surement dans sa liste.
Il y a des distributions qui l'intègre directement et demande juste à être activer dans la liste des addons.

**Comment by wwark** [comment]
Oui s'il n'existe pas c'est à vous de le compiler en suivant la compilation de kodi de votre distribution.

Autre solution est de tout compiler Kodi et Inputstreamadaptive en suivant les indications du build kodi du wiki officiel.

**Comment by enigma131** [comment]
La version Matrix alpha 1 + PVRs  je l'ai compilé depuis les sources, les PVR fonctionnnent à un détail près: ils sont stockés dans le répertoire lib au lieu de lib64. J'ai cré un ticket chez kodi et sur le forum de kodi pour cela.

Donc je vous laisse bosser le sujet Matrix, je suis là pour les tests éventuels :+1:   sachant qu'à terme je veus ripper flatpak.
Ne reste plusque le problème Fedora, système pourtant proche de CentOS.

**Comment by sy6sy2** [comment]
Hello, pour information, le plugin fonctionne "déjà" sous Kodi 19 ; le problème c'est que notre plugin dépend du plugin Youtube-DL qui lui n'est pas encore disponible officiellement sur le repo de Kodi 19.
En faisant deux trois modifications il est possible de faire fonctionner le plugin sous Kodi 19 (je le fais actuellement sur mon Apple TV) :

1. Installer cette version de Youtube-DL: https://github.com/ruuk/script.module.youtube.dl/tree/master-kodi19
2. Installer toutes les dépendances nécessaires à Youtube-DL et à notre plugin (vous pouvez récupérer les ZIP depuis le mirror de Kodi)
3. Installer notre plugin depuis la branche dev de GitHub en remplaçant dans `addon.xml` la version de `XBMC.python` de 2.25.0 en 3.0.0

**Comment by enigma131** [comment]
Merci sy6sy2
Je viens de faire ce qui est écrit par  romainreignier commented on 24 May  ici : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/301
Il me dit que la dependance script.module.codequick n'est pas disponible..
![codequick](https://user-images.githubusercontent.com/31815445/94418658-f81d2280-0181-11eb-93b6-556027eb698c.png)
Les autres dépendances se sont installées
Quand je veux charger le plugin, j'ai une erreur qui me dit 
2020-09-28 10:06:59.838 T:7109     INFO <general>: initializing python engine.
2020-09-28 10:06:59.879 T:7109    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'codequick'
                                                   Traceback (most recent call last):
                                                     File "/home/gilles/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 24, in <module>
                                                       from codequick import run
                                                   ModuleNotFoundError: No module named 'codequick'
                                                   -->End of Python script error report<--

**Comment by enigma131** [comment]
Téléchargé depuis ici : https://mirrors.kodi.tv/addons/krypton/script.module.codequick/
Le zip ne s'installe pas, problème de dépendance
CAddonInstallJob[script.module.codequick]: La dépendance de xbmc.python version 2.25.0 n'a pas pu être satisfaite.

**Comment by sy6sy2** [comment]
Hello ! Ah oui c'est vrai ....
Comme je pense que de plus en plus de personnes vont vouloir installer le plugin sous Matrix, je vais faire un petit post avec les explications pas à pas que j'essaierai de tenir à jour. 
Ça sera plus simple en attendant le support officiel. Je poste le lien ici dès que c'est fait ;-)

**Comment by enigma131** [comment]
Bon j'ai dézippé codequick dans addon et modifié aussi la version de python en 3.0.0 dans son addon.xml:
<import addon="xbmc.python" version="3.0.0"/>
Maintenant il a l'air chargé dans l'interface graphique , mais toujours l'erreur : 
2020-09-28 12:12:32.808 T:12692    INFO <general>: Loading skin file: DialogAddonSettings.xml, load type: KEEP_IN_MEMORY
2020-09-28 12:12:56.666 T:12801    INFO <general>: initializing python engine.
2020-09-28 12:12:56.712 T:12801   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'codequick'
                                                   Traceback (most recent call last):
                                                     File "/home/gilles/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 24, in <module>
                                                       from codequick import run
                                                   ModuleNotFoundError: No module named 'codequick'
                                                   -->End of Python script error report<--

**Comment by sy6sy2** [comment]
Voici le guide : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/363

Pour Codequick il faut peut être l'activer manuellement depuis les Réglages --> Addon --> Dépendances

**Comment by enigma131** [comment]
J'ai du modifier support.py comme dans le tuto.
Il se charge maintenant, mais les chaines à drm ne fonctionnent pas , ex C8.
J'ai pas modifié les scripts. Por mettre les nouveaux, je dois d'abord retirer les anciens scripts de addons ?

**Comment by sy6sy2** [comment]
Alors pour les DRM c'est une autre histoire...
Si tu as une petite notification en haut à droite disant une truc du genre "DRM protected" c'est que pour le moment Kodi ne sait pas gérer ce type de DRM.
Par contre si c'est une erreur alors il faudrait voir le debug log pour comprendre où ça coince (l'idéal serait de pouvoir comparer avec une install correcte de Kodi 18 pour savoir si le problème vient de Kodi 19 ou bien si tout simplement c'est le plugin qui n'arrive pas à gérer tel ou tel cas).

Comment ça pour "mettre les nouveaux" ? Qu'est ce que tu entends par "scripts" ?

**Comment by enigma131** [comment]
Bah dans le tuto il fallait installer les scripts via zip, moi je l'ai fait via l'interface catchup tv , boutton "i" dépendances ... je ne sais pas s'il y a une différence....
Les chaines en clair marchent. Pas celles avec drm
Par exemple pour M6, j'ai : (en ayant renseigné mon compte 6play) : 
2020-09-28 14:08:35.056 T:18620    INFO <general>: CPythonInvoker(2, /home/gilles/.kodi/addons/plugin.video.catchuptvandmore/addon.py): script successfully run
2020-09-28 14:08:35.077 T:18499    INFO <general>: VideoPlayer::OpenFile: plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/6play/get_live_url/?_pickle_=80049565000000000000007d94288c075f7469746c655f948c224d3620e2809420496e63726f7961626c6573207472616e73666f726d6174696f6e73948c08786d6c74765f6964948c14433131382e6170692e74656c6572616d612e6672948c076974656d5f6964948c026d3694752e
2020-09-28 14:08:35.260 T:18775    INFO <general>: Creating InputStream
2020-09-28 14:08:35.260 T:18775   ERROR <general>: CInputStreamAddon::Supports - 'inputstreamaddon' has been deprecated, please use `#KODIPROP:inputstream=inputstream.adaptive` instead
2020-09-28 14:08:35.263 T:18499   ERROR <general>: SetPriority: error No such process
2020-09-28 14:08:35.608 T:18775    INFO <general>: Creating Demuxer
2020-09-28 14:08:35.616 T:18775   ERROR <general>: Open - error probing input format, https://live.quortex.bedrock.tech/6play/short/enc/m6/sd/index.mpd

**Comment by sy6sy2** [comment]
Ah oui. Normalement pas de différences pour les add-ons qui sont déjà dispo pour Matrix sur le repo officiel. Pour Codequick et Youtube-DL du coup ça ne marche pas normalement, obligé de passer par une installation manuelle via ZIP ou via copier/coller du dossier dans `addons`.

Ah oui exacte, il y a eu quelques modifications de iputstream adaptive avec Kodi 19. On doit rajouter un if pour gérer ce cas avec Kodi 19. Je l'ajoute dans notre TODO pour proposer un patch.
En attendant tu peux directement modifier le fichier en remplaçant les occurrences de `item.property['inputstreamaddon']` par `item.property['inputstream']` si je ne me trompe pas...

**Comment by enigma131** [comment]
J'ai fait un grep -r , c'est dans plusieurs fichiers .py cette occurence ... faut remplacer partout ?

**Comment by sy6sy2** [comment]
Oui c'est dans les fichiers de toutes les chaines qui utilisent du DRM.
Tu peux oui, sinon seulement dans les chaines que tu souhaites utiliser.

**Comment by enigma131** [comment]
Groupe M6 marche, mais pas nrj ... le string n'est pas dedans... ca doit être autre chose Canalplay pareil marche pas

**Comment by sy6sy2** [comment]
Ah, c'est le même problème que pour CodeQuick...
Dans Kodi on a récemment retiré la constante `xbmc.LOGNOTICE`, et Youtube-DL semble l'utiliser par moment car on a cette erreur dans ton log: `AttributeError: module 'kodi_six.xbmc' has no attribute 'LOGNOTICE'`.

* Solution 1 : Chercher dans Youtube-DL et/ou dans kodi-six les fichiers qui contiennent le mot `LOGNOTICE` et remplacer par `LOGDEBUG`.
* Solution 2 : Utiliser la version Kodi 19 - Alpha 1 qui permet encore l'utilisation de `xbmc.LOGNOTICE`.

**Comment by enigma131** [comment]
hum je sais pas si c'est ici : 
~/.kodi/addons grep -r LOGNOTICE 
Fichier binaire script.module.youtube.dl/lib/yd_private_libs/__pycache__/util.cpython-36.opt-1.pyc correspondant
script.module.youtube.dl/lib/yd_private_libs/util.py:    xbmc.log('script.module.youtube.dl: {0}'.format(msg), xbmc.LOGNOTICE)
script.module.youtube.dl/lib/yd_private_libs/util.py:    xbmc.log(traceback.format_exc(), xbmc.LOGNOTICE)
script.module.codequick/lib/codequick/script.py:    #: Critical logging level, maps to "xbmc.LOGNOTICE".

**Comment by enigma131** [comment]
Il ne charge pas le script qui est dans addon, pas la bonne version : 
__version__ = "1.14.0"   dans addon , quand je clique sur i (bouton dépendances ce catchup il me met 1.11.0

**Comment by enigma131** [comment]
fait les modif ici : script.module.youtube.dl/lib/yd_private_libs/util.py
maintenant une autre erreur :

**Comment by sy6sy2** [comment]
> Il ne charge pas le script qui est dans addon, pas la bonne version pour kodi six:
> version = "1.14.0" dans addon , quand je clique sur i (bouton dépendances ce catchup il me met 1.11.0

1.11.0 c'est certainement la version min requise. Donc si tu as la 1.14.0 c'est parfait.

> ModuleNotFoundError: No module named 'AddonSignals'
Tu peux essayer d'installer ça via le zip: https://mirrors.kodi.tv/addons/matrix/script.module.addon.signals/script.module.addon.signals-0.0.6+matrix.1.zip

**Comment by enigma131** [comment]
C8 fonctionne maintenant, on avance :)
Nrj 12 maintenant : 
ERROR <general>: [Catch-up-TV-&-More.support] 'unable to import route module: resources.lib.channels.fr.nrj'
                                                   Traceback (most recent call last):
                                                     File "/home/gilles/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 260, in get_route
                                                       importlib.import_module(module_path)
                                                     File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
                                                       return _bootstrap._gcd_import(name[level:], package, level)
                                                     File "<frozen importlib._bootstrap>", line 994, in _gcd_import
                                                     File "<frozen importlib._bootstrap>", line 971, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 678, in exec_module
                                                     File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
                                                     File "/home/gilles/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/nrj.py", line 36, in <module>
                                                       import htmlement
                                                   ModuleNotFoundError: No module named 'htmlement'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/gilles/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 318, in run_callback
                                                       route = self.get_route(self.selector)
                                                     File "/home/gilles/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 262, in get_route
                                                       raise RouteMissing("unable to import route module: %s" % module_path)
                                                   codequick.support.RouteMissing: 'unable to import route module: resources.lib.channels.fr.nrj'

**Comment by sy6sy2** [comment]
Cool !

Pour NRJ 12 il te manque htmlement --> https://mirrors.kodi.tv/addons/matrix/script.module.htmlement/script.module.htmlement-1.0.0+matrix.1.zip

**Comment by enigma131** [comment]
C'était bien cela. J'ai passé en résulo, je ne sais pas enlever le bug en rouge.

Merci en tous cas pour la réactivité, me reste plus que mon problème avec Fedora.

**Comment by enigma131** [comment]
Ahh un petit dernier pour la route sur France TV : 
2020-09-28 16:24:01.328 T:26254    INFO <general>:   msg: libdvdnav: Using dvdnav version 6.0.0
                                                   
2020-09-28 16:24:01.328 T:26254    INFO <general>:   msg: libdvdread: Can't stat 
                                                   
2020-09-28 16:24:01.328 T:26254    INFO <general>:   msg: libdvdread: Could not open

**Comment by sy6sy2** [comment]
Bon c'est déjà une très bonne avancée !

Malheureusement ça va être difficile d'avoir un résultat 100% positif car Kodi 19 est encore bien frais ! Et puis il en est de même pour pas mal de dépendances, que ce soit les plugin Python ou les plugin binaires que Kodi utilise pour la lecture par exemple.
Grâce à toi on a déjà une petite idée de tous les petits problèmes qu'il va falloir gérer avec Kodi 19 😋 Merci.

Je ferme le ticket, n'hésite pas à ré-ouvrir si besoin.

**Comment by grisonb** [comment]
Bonjour à tous, je déterre le sujet car ce matin Kodi s'est mis à jour en version 19 Matrix sur ma nvisia shield et du coup j'ai perdu Catch Up et je ne parviens pas à le réinstaller et j'avoue être largué aves les différentes explications données plus haut .....

Merci d'avance.

**Comment by wwark** [comment]
Hello @grisonb 
On a ces deux ticket relatant le sujet dont vous parlez.

https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/363
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/425

Le premier permet d'installer à la main le plugin sous Kodi 19 et il y a dans le deuxième le suivi du sujet et des liens pour downgrader Kodi si vous le souhaitez.

Merci,

**Comment by grisonb** [comment]
Un grand merci, je vais regarder ça.

Bastien



Le 23 févr. 2021 à 11:07, à 11:07, Marc Roy <notifications@github.com> a écrit:
