### ISSUE TITLE
Replay Suisse et TV direct 

### ISSUE THREAD

**Issue by Che-debarras** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#365]
Derniere tentative:
Je suppose que vous n'avez toujours pas régler le probleme du replay suisse?
Index error : List index out of range

**Comment by wwark** [comment]
Bonjour @Che-debarras,
Je vois qu'on prend encore de votre temps !

Pour le cas du Replay RTS, je ne reproduis pas le index out of range. J'ai testé quelques vidéos.

Pourriez-vous nous indiquer comment le reproduire ? Pourriez-vous aussi nous fournir le log en mode debug quand l'erreur survient ?

Merci.

**Comment by Che-debarras** [comment]
C'est très simple

Je ne suis pas se Suisse alors j'utilise Hola Vpn qui change l'ip pour un ip suisse
J'utilise aussi un hola fake gps qui change ma localisation avec une ville de suisse

Donc pour votre plugin , il doit me croire en suisse et là je lance le replay et j'ai a peine cliqué sur un episode que ce message apparaît

Pour infos le problème de viens pas de mon kodi ou mon vpn ou ma localisation car :
1: j'ai testé avec un browser internet et il affiche bien un ip suisse
2: j'ai testé le replay belge avec un ip belge , le replay marche
(Avec le replay belge le fake gps est inutile 

Et si tu lis les ancien probleme de l'addon,  c'est un problème qui est deja apparu et réparé donc voila.

**Comment by wwark** [comment]
Si vous voulez que je continu à vous répondre je prèfère que vous arrêtiez de dire ce genre de chose.
"le souci avec votre addon c'est que vous le développez pas pour ma majeur partie des utilisateurs c'est a dire appareil android et en dehors des pays de ma chaine."

Ce n'est pas parce que vous avez un soucis que ça impacte d'autres personnes et il est possible que ce soit lié à votre environnement.
Nous devons reproduire le problème pour pouvoir le corriger à part si vous avez la solution qu'on pourra ajouter dans le plugin.

De mon côté je n'ai pas de VPN Hola et j'utilise une android TV (où je n'ai pas le soucis que vous decrivez) donc oui de mon côté je ne pourrais pas me mettre completement dans votre cas de figure.

Mon test de mon côté  a été effectué sur la vidéo RTS > Kids > C'est quoi la déclaration universelle des droits de l'homme avec mon Android TV. Je n'ai pas reproduis et la vidéo est lue sans problème.
Est-ce que vous avez le soucis aussi sur cette vidéo ?
Est-ce qu'il serait possible d'avoir les logs en mode debug ?

Merci.

**Comment by Europe57** [comment]
Salut,

Même soucis sous NordVPN, par contre ce sont les vidéos DRM qui sortent un "index out of range", par exemple en série TV Hawaii 5-0 ou MacGyver.

Chez RTS depuis une coupe de mois, dès fois ça DRM certaine série, dès fois pas, par exemple la série 9-1-1 est non DRM, donc y a aucune logique chez la RTS dans le choix de quoi je DRM et de quoi pas, constations faite sur les 3 série Chicago cette été, 2 des 3 série était DRM, et la 3ème non, pourquoi ? Mystère.

**Comment by wwark** [comment]
Merci @Europe57 Je reproduis sur les vidéos Hawaii 5-0.
On récupère un token et ça doit bloquer à ce point là.
Nous allons regarder la cause pour voir si on peut corriger.

**Comment by Europe57** [comment]
Merci @wwark

**Comment by Che-debarras** [comment]
Tout a fais ça @Europe57 c'est ce que j'attendais une reponse claire meme si c'est pas un bug de l'addon mais un problème de la chaine tv. Au moins c'est claire et précis.

Effectivement, je parle des épisodes Hawaii 5-0 mais les 2 premieres episodes de la reprise j'ai pu les voir sur replay sur catchup avec mon vpn donc je trouve bizarre que depuis c'est sous DRM.

question: meme sous DRM les gens en suisse ne peuvent pas lire un replay sur kodi?

**Comment by Europe57** [comment]
L'extension "officiel" de RTS d'un codeur Suisse ne marche plus depuis presque un an, après je pense qu'il a pas suivi les nouveauté question DRM et a abandonner.

https://github.com/goggle/plugin.video.rtsplaytv

Alors les Suisse peuvent-ils lire le replay sur Kodi, je pense pas actuellement vu que y a plus d'extension qui le propose et qui marche, ou qui marche complètement.

Après comme dit, la RTS, DRM vraiment bizarrement leur replay, dépendant des séries et même des périodes, je sais plus quel série française était non DRM durant 2 épisodes puis DRM. Après quand il DRM, y a jamais de HD alors que si non DRM y a souvent (pour pas dire tout le temps) du 1080p disponible.

Vraiment j'arrive pas a comprendre la logique.

**Comment by wwark** [comment]
@Che-debarras Le fait de donner le nom du replay où vous avez des soucis peut aider à l'analyse.
Le problème DRM n'est pas lié à la géolocalisation.
RTS n'est pas la seule chaine a faire des contenus DRM et non DRM sur le même programme.

Est-ce que le problème de tv direct est le même que le replay ? J'ai testé RTS1 et RTS2 sans soucis de mon côté. @Europe57 Avez-vous des soucis sur les direct TV de RTS ?

Merci

**Comment by wwark** [comment]
Le code RTS n'a la gestion des DRM que pour les direct TV ce qui n'est pas le cas des replays.
Ce point explique qu'on n'arrive pas à lire les contenus protégés par DRM.

**Comment by Che-debarras** [comment]
Non 
Pour le replay j'ai le message IndexError List out of range
Pour la tv direct : j'ai le chargement indéfiniment 
Le petit rond bleu qui tourne mais ne lance pas la chaine , pas d'image ni son

Mais je répète ce n'est que pour la suisse car pour la belgique tv directe ou replay tout va bien avec un vpn (hola vpn)

**Comment by wwark** [comment]
Pourriez-vous fournir le log en mode debug du direct TV afin de vérifier si on ne tombe pas sur un timeout ?
Kodi propose des options pour jouer sur le paramètre curlclienttimeout qui pourrait surement aider. 
https://kodi.wiki/view/Advancedsettings.xml#network
Il faudrait tester de mettre 30 secondes ou plus si le problème persiste.
 
Merci.

**Comment by wwark** [comment]
l'ajout du support des DRM pour les replays est présent sur la version 0.2.27 beta04.
Pouvez-vous tester ? 

Merci,

**Comment by Europe57** [comment]
Pour le direct aucun soucis. Pour le replay je test dès que la version beta04 est dispo via le Repository beta. Pour le moment j'ai la version beta02.

**Comment by Europe57** [comment]
Pour moi c'est tout bon, replay tester sur Hawaii 5-0 et MacGyver.
Merci @wwark pour la correction.

**Comment by Che-debarras** [comment]
Je confirme pour le replay suisse ça fonctionne 
Mais pas le tv direct : Erreur Timeout

**Comment by wwark** [comment]
Bonjour @Che-debarras, 
Avez-vous pu tester ma proposition de configurationqui pourrait aider aux erreurs timeout que vous rencontrez ?

**Comment by Che-debarras** [comment]
> Bonjour @Che-debarras,
> Avez-vous pu tester ma proposition de configurationqui pourrait aider aux erreurs timeout que vous rencontrez ?

Je vais essayer avec un addon de modifier ce fichier xml et je vous tiens au courant

**Comment by wwark** [comment]
C'est le même code utilisé pour RTS1 et pour RTS2.
Si vous indiquez qu'il y a une différence. Ce point peut venir de l'etat du serveur RTS aux moments de votre teste ou une différence au niveau du moteur vidéo de Kodi (les logs pourrait aider à voir l'erreur)
Les problèmes rencontrés de RTS2 semblent être des problèmes de buffering.

Au niveau du plugin on a fait notre travail. Le soucis semble être présent au niveau du player Kodi.

**Comment by Che-debarras** [comment]
> C'est le même code côté plugin utilisé pour RTS1 et pour RTS2.
> Si vous indiquez qu'il y a une différence. Ce point peut venir de l'etat du serveur RTS aux moments de votre test ou une différence au niveau du moteur vidéo de Kodi (les logs pourrait aider à voir l'erreur)
> Les problèmes rencontrés de RTS2 semblent être des problèmes de buffering.
> 
> Au niveau du plugin on a fait notre travail. Le soucis semble être présent au niveau du player Kodi.

C'est ce que je trouve dommage dans vos réponses de toujours rejeter la faute sur kodi alors que j'ai bien précisé que ca n'a rien a avoir avec le buffering puisque kodi lit parfaitement les chaines tv Full HD ou HD avec votre propre addon.

Donc si kodi a du mal a lire du 544p expliquez moi pourquoi il lit bien les 720p ou 1280p avec votre addon et ceux des autres.

Bref merci quand même bye

**Comment by wwark** [comment]
Je viens de penser à un élément.
De mon côté, j'ai installé cette version de Inputstream Adaptive de mon côté (pour M6) https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/300#issuecomment-667508278
Cette nouvelle version de InputStream Adaptive a plusieurs corrections pour la lecture des DRM dans Kodi. On est attente que cette version soit releaser.

Si vous n'avez pas installer cette version, elle pourrait apporter surement des améliorations de votre côté.

**Comment by Che-debarras** [comment]
> C'est le même code côté plugin utilisé pour RTS1 et pour RTS2.
> Si vous indiquez qu'il y a une différence. Ce point peut venir de l'etat du serveur RTS aux moments de votre test ou une différence au niveau du moteur vidéo de Kodi (les logs pourrait aider à voir l'erreur)
> Les problèmes rencontrés de RTS2 semblent être des problèmes de buffering.
> 
> Au niveau du plugin on a fait notre travail. Le soucis semble être présent au niveau du player Kodi.

Non pour RTS2 ca na rien a voir avec le buffering.
J'ai bien précisé que Kodi lit parfaitement sans problème des chaines TV Full HD et HD sans sacade ni freeze donc lire des chaines tv SD ça ne devrait pas avoir de problème.

Le problème vient bien de l'addon.

Pour Rts1 pareil le problème vient de l'addon car si elle affiche l'image de RTS1 alors ca devrait afficher une image aussi pour Rts1 si même code.

Conclusion: le bug doit etre dans le code pour ces chaines suisses puisque les chaines belges eux n'ont aucun souci.
