### ISSUE TITLE
Gulli ne fonctionne plus

### ISSUE THREAD

**Issue by babagoul** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#372]
Bonsoir,

En voulant mettre la chaine Gulli pour les enfants je me suis rendu compte que celle ci ne fonctionnait plus, que sa soit sur mon raspberry ou sur mon pc, avez vous connaissance de ce problème ? ou ce problème vient il uniquement de chez moi ? Je vous envoie le log de kodi par la même occasion.
Merci d'avance pour votre aide
[Log.txt](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/5425288/Log.txt)

**Comment by Dobi-Dev** [comment]
Bonsoir,
Je viens de tester sur mon rpi4 et j'ai le même soucis, donc je confirme que cela ne vient pas de chez vous.

**Comment by wwark** [comment]
Le direct TV de Gulli a été corrigé sur la dernière version bétâ du plugin.
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/9ad735d46ed0c06085f78fc6091b1d664ab340a7

**Comment by babagoul** [comment]
Merci, tout refonctionne a nouveau avec la nouvelle version beta, vous etes au top 😉

**Comment by tails101** [comment]
bonjour,c est pour quand la mise a jours dans la version finale?

**Comment by babagoul** [comment]
Bonjour tails101, le mieux pour vous serait de passé au versions bêta,  je n'est jamais eu de problèmes particuliers avec 😀

**Comment by wwark** [comment]
@sy6sy2 On lance une nouvelle release ? !
