### ISSUE TITLE
RTL BE Live TV KO

### ISSUE THREAD

**Issue by wwark** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#375]
Les Live TV RTL BE protégés par DRM sont KO.
BEL RTL est toujours OK par exemple (non DRM)

**Comment by JerryCrazy** [comment]
Bonjour, je ne parviens pas à reproduire le problème chez moi, ça a l'air d'aller, est-ce que les flux ont des DRM tout le temps ?

L'extension a été mise à jour il y a peu dans mon cas.

**Comment by wwark** [comment]
Hier ça ne fonctionnait plus mais là ça remarche !
Je clos le ticket !
