### ISSUE TITLE
TV Lux en direct ne fonctionne plus

### ISSUE THREAD

**Issue by JerryCrazy** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#376]
Bonjour,

Le flux en direct de TV Lux ( https://tvlux.be/live ) ne fonctionne pas sur la dernière version (et la précédente non plus), le flux a probablement changé d'URL
Le lien actuel est : https://tvl-live-prp.fl.freecaster.net/live/tvlux/tvlux-audio_fre=128000-video=5200000.m3u8

Merci pour tout le temps passé à faire évoluer cette extension !

**Comment by wwark** [comment]
Bonjour @JerryCrazy,

TV Lux a été corrigé dans la dernière version beta (https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/aec53110b345dc4a820fbd8665c8479a9cf6927f)

Merci,

**Comment by JerryCrazy** [comment]
Merci à vous

**Comment by wwark** [comment]
de rien.
Je clos le ticket.
