### ISSUE TITLE
Tipik : logo de la chaîne absent

### ISSUE THREAD

**Issue by JerryCrazy** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#377]
Bonjour,

Juste pour signaler que le logo de la chaîne Tipik de la RTBF n'apparaît pas dans le guide TV de Kodi, en effet, il semble que dans le paquet resource.images.catchuptvandmore, l'image ne soit pas présente mais l'ancien logo (La Deux) l'est encore !

Merci d'avance

**Comment by wwark** [comment]
Bonjour @JerryCrazy,
On vient de l'ajouter (https://github.com/Catch-up-TV-and-More/resource.images.catchuptvandmore/blob/0de4bc2f4fcec1f234301668332789a4f7b74d64/resource.images.catchuptvandmore/resources/channels/be/tipik.png) je l'avais oublié.
Il sera présent dans la prochaine release des ressources images.

Merci

**Comment by JerryCrazy** [comment]
Génial ! Merci pour votre boulot !
