### ISSUE TITLE
Cannot access replay @RTBF

### ISSUE THREAD

**Issue by eenbroleke** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#378]
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/b87c8fac1aa7d1c57439dbd5a15ad07e5cdd8f93/plugin.video.catchuptvandmore/resources/lib/channels/be/rtbf.py#L431

see the pastbin (end of file)
https://paste.kodi.tv/kiwugosado

The issue is related to a missing check (if url_hls in video_datas[url_streaming], fine, else use "url", not "url_hls".
Tested with this fix for the various places where it was needed and it works.

**Comment by eenbroleke** [comment]
The issue is related to a missing check (if url_hls in video_datas[url_streaming], fine, else use "url", not "url_hls".
Tested with this fix for the various places where it was needed and it works.

**Comment by eenbroleke** [comment]
[rtbf.txt](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/5525634/rtbf.txt)

**Comment by wwark** [comment]
Merci @eenbroleke je vais tester ce fix !

**Comment by eenbroleke** [comment]
I believe there still might be some issues with the Live stream.

**Comment by wwark** [comment]
I tested La Une, Tipik and La Trois without issues.
What is your issues ? Do you have logs or test cases ?

**Comment by eenbroleke** [comment]
Sorry, no log or test-cases, I was just trying to watch the "Journal du 19h30" on La Première and it failed.
But this might have been because the stream was not ready (the way Live is working is akward for RTBF Auvio).
If it happens again, I'll create a new issue and report there.
Thanks for your effort in maintaining and enriching this plugin.

**Comment by wwark** [comment]
ok no problem. do not hesitate to open new issues !
The fix proposed is available in the last beta version of this addon.
So i closed the ticket !
Thanks again for the fix :+1:
