### ISSUE TITLE
LIVE TV-Canada-TVA

### ISSUE THREAD

**Issue by sviet2k** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#379]
Bonjour,

Le TVA ne marche plus avec sa nouvelle plateforme :(.
Veuillez vous corriger le add-on SVP?
Et si possible, ajoute aussi la chaine LCN. :)

Encore merci

**Comment by wwark** [comment]
Hello @sviet2k,

Les live TV de TVA et LCN (reajouté) sont fonctionnels dans la dernière beta du plugin.
Il reste à corriger la partie replay.

Merci,

**Comment by boxkim14** [comment]
Bonjour @wwark,

Ça marche très bien. 
Merci beaucoup et bonne fin de semaine
