### ISSUE TITLE
catch up tv and more

### ISSUE THREAD

**Issue by Ponchofruit** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#38]
les videos ssur m6 n'ouvre pas. ca me dit check the log . je ne comprends pas!

**Comment by wwark** [comment]
Bonsoir,

Nous allons essayer de comprendre !

Premier point, vous êtes en quelle version de Catch-up TV and More et de Kodi ?
Quelles sont les vidéos remontant des erreurs ? Est-ce que vous avez des erreurs sur "La nouvelle star" par exemple. 

Est-ce qu'il est possible de poster les logs lors de l'erreur sur un pastebin pour l'analyse ?

Wwark

**Comment by wwark** [comment]
Bonjour,

Avez-vous pu récupérer les logs ?

Wwark

**Comment by wwark** [comment]
Bonjour,

N'ayant pas eu de retour je me permet de fermer ce ticket. Vous pouvez le rouvrir si besoin.
Wwark
