### ISSUE TITLE
Adding new content : Radiofreccia Web TV

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#385]
url : https://www.radiofreccia.it/radiovisione/       (need to remove blokers)

Content : International music rock. Channel is present on satellite too in FTA.

**Comment by enigma131** [comment]
Hi, Any news ?
Second link, (first from December post is always valid) : https://play.rtl.it/live/17/radiofreccia-radiovisione/
I've extract all direct m3u8 addresses from Live's browser, (from 1920 down to 320p)
I've put them in VLC , are OK

**Comment by enigma131** [comment]
Hi, yes multi resolutions https://play.rtl.it/live/17/radiofreccia-radiovisione/ , here the 1088p one grabbed with firefox's console (ctrl + shif+ j), is working with Vlc:
https://streamcdnb11-dd782ed59e2a4e86aabf6fc508674b59.msvdn.net/live/S3160845/0tuSetc8UFkF/chunklist_b2816000.m3u8

**Comment by joaopa00** [comment]
Fix in dev. Darodi, could have a look to implement the replay? Thanks in advance.

**Comment by darodi** [comment]
I'll have a look asap

**Comment by enigma131** [comment]
Is working for fixed resolution 1088p thanks. Tested with 0.2.38 beta00. Autodetect lower resolution will not possible I presume ?

**Comment by joaopa00** [comment]
Can you give a try?
I receive error 502 gateway, but I already receive it in web browser

**Comment by enigma131** [comment]
It's still working, I just saw multi resolution, waiting next beta to test

**Comment by joaopa00** [comment]
What are blockers?

**Comment by darodi** [comment]
I'll try to reimplement this today using input stream adaptative for multi resolutions instead of just 1080p

**Comment by joaopa00** [comment]
Thank you darodi.
@Enigma121: You can test the latest version of development:
https://codeload.github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/zip/refs/heads/dev

**Comment by enigma131** [comment]
@ joaopa00 blockers are for example ublock origin.
The dev version give me no choice for resolution, setup is dialog and dialog is working for other channels as Cstar.

**Comment by joaopa00** [comment]
You have to configure inputstream.  in stream selection chose Manually select video stream. Then when playing radiofreecia. press OK. At the botton right of the screen, you see a wheel. Press it. Choose video. At the most first item, if my patch is correct, you should be able to chose the resolution.

**Comment by enigma131** [comment]
I don't use inputstream adaptive, because conflicts with Hts.pvr and dbvviewer.pvr. . In Italy live category, if i click on radiofreccia, no menu for quality selection, and no choice if i right click on channel.

**Comment by joaopa00** [comment]
@darodi. I think for this kind of situation, that is inpustream not available, we should a fallback, something like this:

is_helper = inputstreamhelper.Helper("mpd")
    if is_helper.check_inputstream():
         .........
   else:
         .........

What do you think?

**Comment by enigma131** [comment]
I have installed latest dev in addon directory, resolution is still not modifiable. It is not at max, I want choose max on PC and a lower one on smartphone. With .xspf file and VLC, all resolutions are working

**Comment by enigma131** [comment]
I've installed latest beta3. Video resolution is only 576p , as 1088p stream is always available via Firefox. Can this be fixed (have multi video resolution choice) ?

**Comment by joaopa00** [comment]
Devrait être fixé in git. Merci Darodi. Je ferme.
