### ISSUE TITLE
TVA Replay/Live TV - Index out of range dans live Tv 

### ISSUE THREAD

**Issue by Ricbla614** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#386]
### Content description

* Name: Ricbla614
* Type [e.g. TV channel, Catch-up TV, Website, Radio]:lors de la connexion a catchuptvand more dans live tv Canada spécifiquement le réseau TVA le message ''index out of range apparait. Comment faire pour résoudre le problème
* Website URL:
* Content language/country: Canada Françaix. 

### Content access

- [ ] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [ ] This content is geographically restricted

### More information

If you want to add more information, put it here:

**Comment by wwark** [comment]
Bonjour,

TVA a pas mal changé son site web.
Une première correction est présente dans la dernière béta du plugin.

Merci,

**Comment by JustBeta** [comment]
Effectivement, cela marche plutôt bien avec la beta. Je n'ai pas constaté de problème sur le replay.

**Comment by wwark** [comment]
Dans la nouvelle release !
