### ISSUE TITLE
[Arte] - Accessible depuis FR et DE en flux direct

### ISSUE THREAD

**Issue by watchix** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#387]
Bonjour,

Arte étant dans la liste des chaines internationales, pourquoi ne pas la retrouver à la fois dans la liste France et Allemagne ?

En installant Catchup hier chez un ami celui-ci m'a dis "c'est dommage y a même par Arte".
En recherchant ce matin j'ai vu que la chaine n'était accessible quand dans la partie internationale ... c'est dommage 😃 

Pareil pour la chaine "RT" par exemple,.

[https://i.ibb.co/BTdnZYG/arte.jpg](url)

**Comment by wwark** [comment]
Bonjour @watchix,

Merci pour votre demande.

On met les chaines ayant plusieurs contenus de langues dans internationales comme Arte et RT.
Nous n'avons pas prévu de changer ce point.

Cependant en utilisant cette procédure "https://catch-up-tv-and-more.github.io/fr/live_tv_installation/", on a construit des fichiers en m3u8 pour les chaines française et on a rajouté Arte (FR) et RT (FR) dans ce cas.

Merci,

**Comment by watchix** [comment]
Hello @wwark ,

Merci pour l'info je vais me débrouiller avec cette manip.
Je ne proposais pas de changer l'emplacement des chaines mais qu'elles soient accessibles (en doublon) à la fois côté internationnal et dans la partie pays aussi. :smile:

Après si c'est à l'utiliateur de s'adapter à l'interface ... pouquoi pas.
