### ISSUE TITLE
download: add file name feature

### ISSUE THREAD

**Issue by diaagi** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#39]
Hello,
Is it possible to choose a name to the file if I choose to download it?
I was asked for the path to download, but a default strange long name was given to the file.
I would like to have a filename corresponding to the title of the video, to be used with tvDB scrapper.
For example, if I download France5 / Replay / Peppa Pig - Les jeux gonflables, I would like to have a filename indicating season and episode (S05E30 - Peppa - Les jeux gonflables.mp4) rather than the default mysterious name: master-master.m3u8caption=2017_50_169045108-1513409332.mp4

Thanks,

**Comment by wwark** [comment]
Bonjour,

C'est déjà dans la TO DO de cette issue dans un des commentaire.
[https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/19](url)

Je ferme donc cette issue. Je vais rajouter votre point sur le format attendu.

Merci d'avance,
Wwark

**Comment by SylvainCecchetto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [YouTube DL - Il faut dire à Youtube-DL de donner comme nom à la vidéo téléchargée le label de la vidéo qui est affichée dans Kodi](https://trello.com/c/wuEY7qmc/93-youtube-dl-il-faut-dire-%C3%A0-youtube-dl-de-donner-comme-nom-%C3%A0-la-vid%C3%A9o-t%C3%A9l%C3%A9charg%C3%A9e-le-label-de-la-vid%C3%A9o-qui-est-affich%C3%A9e-dans-kodi)
