### ISSUE TITLE
Problème Replay mycanal

### ISSUE THREAD

**Issue by sephirothnight** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#391]
Bonjour,
Impossible d'accéder aux Replay mycanal, j'ai pourtant vérifier si catch UP était bien à jour ainsi que Kodi (Leia). Merci.

**Comment by wwark** [comment]
Bonjour,

Quelle est l'erreur rencontrée ? Pourriez-vous nous transmettre les logs Kodi au niveau debug ?

Merci,
Wwark

**Comment by sephirothnight** [comment]
Bonjour, je n'ai pas trouvé comment envoyer les logs sur mi box ? J'envoi cela dès que j'ai trouvé, merci.

**Comment by wwark** [comment]
Bonjour,
Vous pouvez suivre ce wiki.
https://kodi.wiki/view/Log_file/Easy

**Comment by JustBeta** [comment]
Voici un log du problème: https://paste.kodi.tv/finuqahasa

**Comment by wwark** [comment]
@JustBeta Merci pour le log.
Vous pouvez me dire pour quel replay vous avez cette erreur ?
Il n'arrive pas à trouver l'image.

**Comment by JustBeta** [comment]
Bonjour @wwark,
Pour les replays de la chaine C8.

**Comment by wwark** [comment]
Bonjour @JustBeta,
Je viens de corriger dans la dernière béta du plugin.

Merci,

**Comment by JustBeta** [comment]
Merci, je vais tester dans la journée.

**Comment by JustBeta** [comment]
J'ai fait le test avec la version 0.2.28-beta09 et ce n'est pas bon.
Voici le log : https://paste.kodi.tv/ezuruyahin
Toujours le replay de C8, je suis allé sur "les téléfilms de noel" pour le test.

**Comment by wwark** [comment]
La dernière version beta est la beta11.
SI elle n'est pas disponible au téléchargement vous pouvez la récupérer ici : https://github.com/Catch-up-TV-and-More/repository.catchuptvandmore/blob/master/zips/krypton_beta/plugin.video.catchuptvandmore/plugin.video.catchuptvandmore-0.2.28%7Ebeta11.zip

**Comment by JustBeta** [comment]
Effectivement, c'est ok avec la version 0.2.28-beta11. Le replay C8 fonctionne sur les programmes ne contenant pas de DRM.
Merci.

**Comment by wwark** [comment]
Merci @JustBeta pour ton retour.
Oui la partie DRM n'est pas encore supporté par Kodi surement un jour ....
