### ISSUE TITLE
Adaptation du plugin pour télé connectée.

### ISSUE THREAD

**Issue by joaopa00** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#392]
Bonjour à tous

**Is your feature request related to a problem? Please describe.**
Bonjour, ma télé connectée TCL est sous Linux, avec le vieux framework opera. Evidemment Kodi n'a pas été portée sur ce matériel. J'essaie par conséquent de creer un petit script (en javascript,le serveur que j'utilise ne connaît que ça, pas le php )qui se lancerait à partir du navigateur opera présent (veille version 40)
Pour ce faire, je teste la chaîne RMCSTORY. En regardant le code source (resource/lib/channels/fr/rmc.py et 
resource/lib/resolver_proxy.py), j'arrive a recupérer l'adresse de master.m3u8
Mais je n'arrive pas à récupérer le fichier lui-même. 
**Describe the solution you'd like**
Quelqu'un sait-il les options à passer dans ma requête du fichier pour le récupérer?

Merci d'avance

Cordialement

**Comment by wwark** [comment]
Bonjour @joaopa00,

Le HTTP 403 indique que l'accès à la ressource n'est pas authorisé.
Est-ce que vous pouvez lire RMCSTORY sur un navigateur Web avec la même connexion ?
Il arrive aussi que les flux récupérer m3u8 sont valides que quelques minutes (token, etc ..)

Merci,
WWark

**Comment by joaopa00** [comment]
Merci pour le retour. J'ai réussià faire la requête et lancer la chaîne. Evidemment j'ai le problème de CORS à regler mais le principe est trouvé. Je partage le code pour ceux qui pouraientt être intéressés.
`"use strict";

const axios = require('axios');


async function get_live_url () {  

  var a,b;
  var data_account, data_player, data_video_id, policykey;  
  var url = 'https://rmcstory.bfmtv.com/mediaplayer-direct'

  const response = await axios({
    url,
    method: 'GET',
    responseType: 'text',
    header:{ 'Access-Control-Allow-Origin': null}
  });
  
  a = 14 + response.data.indexOf('data-account');
  b = response.data.indexOf('data-player')-2;
  data_account = response.data.substring(a,b);
  
  a = response.data.indexOf('data-player')+13;
  b = response.data.indexOf('data-embed')-2;
  data_player = response.data.substring(a,b);
  
  a = response.data.indexOf('data-video-id')+15;
  b = response.data.indexOf('autoplay')-2;
  data_video_id = response.data.substring(a,b);
  
  url = 'https://players.brightcove.net/'+data_account+'/'+data_player+'_default/index.min.js';

  const response_policy_key = await axios({
    url,
    method: 'GET',
    responseType: 'test'
  });

  b = response_policy_key.data.indexOf('platformVersion:');  
  a = response_policy_key.data.indexOf('policyKey:',b)+11;
  b = response_policy_key.data.indexOf('j("touchActive")')-4;
  policykey = response_policy_key.data.substring(a,b);
  
  url = 'https://edge.api.brightcove.com/playback/v1/accounts/'+data_account+'/videos/'+data_video_id;
  
  const resp = await axios({
    url,
    method: 'GET',
    responseType: 'text',
    headers:{
        'Accept': 'application/json;pk='+policykey
    }
  });
    
    var json_parser=resp.data;
    
    url = '';
    a = json_parser.sources[0].src;
    if(a.search('m3u8')!=-1)
    {
        url = a;
    }
    if (url == '')
        return false;
  
  const response2 = await axios({
    url,
    method: 'GET',
    responseType: 'text',
  });

  a = response2.data.indexOf('848x480');
  b = response2.data.length;
  url = response2.data.substring(a+39,b);

  var options = {
    html5: {
      hls: {
        overrideNative: true
      }
    },
  };
   
  var myPlayer = videojs('my_video',options);

  myPlayer.src({type: 'application/x-mpegURL', src: url});
  myPlayer.play();
}

get_live_url();

`

**Comment by wwark** [comment]
Ticket fermé
