### ISSUE TITLE
No subtitles on live tv

### ISSUE THREAD

**Issue by naifmeh** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#393]
### Describe the bug

The subtitles are enabled in the settings and while the live video is running, but no subtitle is displayed, at least on the french channels (TF1, M6...).

### To Reproduce

1. Enable subtitles in the settings
2. Launch any french live canal
3. Verify that subtitles are enabled

### Expected behavior

Subtitles should be showing.

### Actuel behavior
No subtitles

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi 4B
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: Leia 18.x
 - Catch-up TV & More version: 0.0.6
 - Installation method: 

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by wwark** [comment]
Hi,
I think we add subtitles just for lives of France TV.
TF1, M6 don't provide subtitles.
We add subtitles if present.
Thanks.
