### ISSUE TITLE
Unable to watch "TV Com", the belgian channel give an error.

### ISSUE THREAD

**Issue by echo-five** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#394]
### Describe the bug
The belgian channel "TV Com" give an error.

### To Reproduce
1. Select "TV Com" in the channels list. 

### Expected behavior
I expect to be able to watch this channel...

### Actuel behavior
I got the following message, then nothing.
"_Index Error
list index out of range_"

### Your environment
 - Raspberry-Pi 2
 - Operating system version/name: LibreElec (Leia) 9.2.6
 - Kodi version: 18.x
 - Catch-up TV & More version: Master branch on github (31/12/2020);
 - Installation method: Manual plugin install, following your tutorials.

**Comment by wwark** [comment]
Bonjour @echo-five,

Le Live TV ne semble plus fonctionner sur le site web aussi : https://www.tvcom.be/live#
Est-ce le même comportement pour vous ? Si c'est le cas, il faut attendre que le live soit accessible de nouveau sur le site web.

Merci,

**Comment by wwark** [comment]
Bonjour @echo-five,

Le Livet TV fonctionne de nouveau sur le site web.
Une correction a été apportée sur la beta 14.

Merci,
Wwark

**Comment by wwark** [comment]
Dans la nouvelle release
