### ISSUE TITLE
Lecture Arte ko

### ISSUE THREAD

**Issue by damienveau** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#395]
La lecture d’Arte est impossible depuis qq jours.

Depuis l’onglet tv de kodi ou via l’extension lorsque l’on sélectionne Arte rien ne se passe le programme ne se lance pas mais pas d’erreur affichée.

Sur Raspberry-Pi
> LibreElec 9.2.6
> Kodi version: 18.9
> Catch-up TV & More version: 0.2.27

**Comment by babagoul** [comment]
Bonsoir,  oui même problème pour moi, sur raspberry 4 avec la distribution Libreelec.

**Comment by Phigen** [comment]
Idem sur RPI4 et Libreelec.

**Comment by enigma131** [comment]
Idem ici :  DEBUG: Error, could not open file (2) https://artelive-lh.akamaihd.net/i/artelive_fr@344805/master.m3u8

**Comment by Phigen** [comment]
J'ai testé la branche Dev du plugin et cela fonctionne bien sur le RPI4 avec Libreelec. Pas testé sur Linux PC.

**Comment by babagoul** [comment]
Ne fonctionne toujours pas sur android TV,  avec la version beta du plugin , je testerai sur le rpi4 et libreelec tout taleur pour voir.

**Comment by Phigen** [comment]
Ça fonctionne toujours sur RPI4 aujourd'hui et j'ai remarqué que la bascule sur Arte est beaucoup plus rapide, avec l'ancienne version, j'avais plusieurs secondes de latence avant l'apparition de la chaîne.

**Comment by wwark** [comment]
La beta12 a été release avec le fix sur le Live TV Arte.
Oui on a du faire un hack car le fichier M3U8 contenant les flux de Arte contenait des flux repondant HTTP 404.
Si Kodi trouve un flux remontant une erreur dans le m3u8 il arrête la lecture du live ...
On fera un revert quand Arte aura corrigé ce point.
On récupère le flux de meilleur qualité mais les autres ne sont plus proposés ....

Merci,
Wwark.

**Comment by babagoul** [comment]
> La beta12 a été release avec le fix sur le Live TV Arte.
> Oui on a du faire un hack car le fichier M3U8 contenant les flux de Arte contenait des flux repondant HTTP 404.
> Si Kodi trouve un flux remontant une erreur dans le m3u8 il arrête la lecture du live ...
> On fera un revert quand Arte aura corrigé ce point.
> On récupère le flux de meilleur qualité mais les autres ne sont plus proposés ....
> 
> Merci,
> Wwark.

Bonjour, 
La beta 12 ne m'est toujours pas proposé, je suis sous Android tv et pour l'instant on ne me propose que la beta 11 (celle qui est deja installer ) merci d'avance.

**Comment by enigma131** [comment]
Fonctionne ici Linux, merci ;)

**Comment by enigma131** [comment]
Par contre, le correctif semble ne pas être appliqué pour Kodi 19

**Comment by pouilld** [comment]
Même problème avec OSMC LEIA 18 et dernière version beta Catch-Up TV & more.

**Comment by wwark** [comment]
Arte a corrigé son flux Live TV.
J'ai appliqué un revert sur le hot fix apporté.

Je ferme ce ticket.

Merci,
Wwark
