### ISSUE TITLE
Je reçois le message suivant: Index out of range

### ISSUE THREAD

**Issue by Ricbla614** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#398]
### Content description

* Name:RICBLA614
* Type [e.g. TV channel, Catch-up TV, Website, Radio]:
* Website URL:
* Content language/country:Canda. francais - Appareil Android
### Content access

- [ ] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [ ] This content is geographically restricted

J'ai dû réinstaller catchup tv and more en raison de problème avec mon appareil. J'ai utilisé la version bêta proposé : URL : https://repo.cecchettosylvain.fr/zip.  Cela m'a permis d’installer la version 02.27. Lorsque j'essaie d'ouvrir la TV (en direct) Canada français poste TVA. Je reçois le message suivant: List index out of range. 

Je n’arrive pas à installer la version 02.28 comme je l’avais fait préalablement. Comment puis-je faire accéder à TVA?

Merci et bonne journée

If you want to add more information, put it here:
****

**Comment by wwark** [comment]
Bonjour @Ricbla614,

Il y a déjà une issue présente ici de votre problème : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/386
Ce point est corrigé dans la dernière béta.

Merci,
Wwark

**Comment by wwark** [comment]
Je ferme ce ticket.
