### ISSUE TITLE
disableDASHvideo

### ISSUE THREAD

**Issue by diaagi** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#40]
Bonjour,
Je suis sous Kodi Windows.
Quand je regarde le log, j'ai l'erreur suivante de nombreuses fois:

22:56:34.738 T:7392  NOTICE: script.module.youtube.dl: youtube_dl core version: 2017.07.09
22:56:34.805 T:7392   ERROR: C:\Users\xxx\AppData\Roaming\Kodi\addons\script.module.youtube.dl\lib\YDStreamExtractor.py:453: UserWarning: External use of disableDASHVideo() is deprecated. It is now handled by module settings
                                              warnings.warn("External use of disableDASHVideo() is deprecated. It is now handled by module settings")

En effet, dans le fichier settings.xml, je retrouve bien l'option:
<setting id="disable_dash_video" value="true" />

Pourquoi j'ai cette erreur dans le log?
Comment je contourne?
Merci !

**Comment by wwark** [comment]
Bonjour,

Vous êtes quel version du plugin ? Ce message d'erreur a été corrigé en v0.1.5 et la dernière version du plugin est la version 0.1.7.

Nous avons notre propre répository. 
[https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/wiki/Add-the-official-repository](url)
Sur le repository de Kodi nous avons la version 0.1.4. L'acceptation de nouvelle version du plugin prend du temps.

Le plus simple si c'est possible est d'utiliser notre repository.
Merci d'avance,
Wwark.

**Comment by diaagi** [comment]
Bonjour
Je suis sur la 0.1.4 du repo kodi.
J'ai teste la version 0.1.7 en release et en beta mais ca plante avec kodi sous windows. Erreur sur le format timestamp et float de memoire.

**Comment by wwark** [comment]
Est-ce qu'il est possible d'avoir le log en question sur un paste bin ?
Quelle est la version de Windows utilisé ?
Merci d'avance,
Wwark.

**Comment by wwark** [comment]
Comme vous avez réussi à installer la 0.1.7 cette erreur n'est donc plus visible.
Je ferme donc cette issue à rouvrir si besoin.
Merci,
Wwark.
