### ISSUE TITLE
Catch Up TV : JSON Decode Error

### ISSUE THREAD

**Issue by berkhornet** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#403]
### Describe the bug
When selecting "Catch Up TV" from the main menu a "JSONDecodeError" occurs.

### To Reproduce
1. Open Catch Up TV & More addon
2. Select Catch Up TV
3.
4.

### Expected behavior
The Catch UP TV options should appear

### Actuel behavior
Error message displayed and Catch Up TV remains on the main menu.

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X ] Windows
 - [ ] Other

 - Operating system version/name: Windows 10 20H2
 - Kodi version: Kodi 19 RC
 - Catch-up TV & More version: 0.2.28 beta 15
 - Installation method: As per Kod1 19 instructions (issue #363)

### Additional context
This has previously worked on Kodi 19 Alpha and Beta releases

### Debug log
If you can, please add your debug log information :
https://paste.kodi.tv/elovebagih

**Comment by wwark** [comment]
Hi @berkhornet,

I saw the issue when you tried to open uktvplay catchup TV.
Is the issue remains on your side ?

Thanks,

**Comment by berkhornet** [comment]
Hi.

Yes, I still have the error message when using UKTVPlay Catch Up TV. Do you need any further information to help fix the issue?

Thank you.

**Comment by wwark** [comment]
What is the content shows of this url : https://vschedules.uktv.co.uk/vod/categories/ on a web browser in the same network of your kodi device ?

thanks,

**Comment by berkhornet** [comment]
Hello

When i type in the URL i get the following


{"categories":[{"name":"Comedy","slug":"comedy","id":1,"subcategories":[{"name":"Classic Comedy","slug":"classic-comedy","id":1,"channels":[{"4646":"Drama"},{"3858":"GOLD"},{"3854":"Dave"},{"3866":"Yesterday"}],"brand_count":30},{"name":"Sitcom","slug":"sitcom","id":2,"channels":[{"3858":"GOLD"},{"4646":"Drama"},{"3854":"Dave"},{"3866":"Yesterday"}],"brand_count":35},{"name":"UK Comedy","slug":"uk-comedy","id":4,"channels":[{"3854":"Dave"},{"3858":"GOLD"},{"4646":"Drama"},{"3866":"Yesterday"}],"brand_count":72},{"name":"Panel Shows","slug":"panel-show","id":6,"channels":[{"3854":"Dave"},{"3858":"GOLD"}],"brand_count":22}]},{"name":"Drama","slug":"drama","id":2,"subcategories":[{"name":"Crime Drama","slug":"crime-drama","id":7,"channels":[{"4646":"Drama"},{"3856":"Alibi"}],"brand_count":40},{"name":"Medical Drama","slug":"medical-drama","id":10,"channels":[{"4646":"Drama"},{"3856":"Alibi"}],"brand_count":13},{"name":"Period Drama","slug":"period-drama","id":11,"channels":[{"3856":"Alibi"},{"4646":"Drama"}],"brand_count":32},{"name":"Soaps","slug":"soaps","id":13,"channels":[{"4646":"Drama"}],"brand_count":5},{"name":"UK Drama","slug":"UK-Drama","id":35,"channels":[{"4646":"Drama"},{"3856":"Alibi"}],"brand_count":25},{"name":"Best of Drama","slug":"best-drama","id":71,"channels":[{"4646":"Drama"},{"3856":"Alibi"}],"brand_count":18}]},{"name":"Entertainment","slug":"entertainment","id":3,"subcategories":[{"name":"Motoring","slug":"motoring","id":14,"channels":[{"3854":"Dave"},{"3866":"Yesterday"},{"3858":"GOLD"}],"brand_count":31},{"name":"Real Lives","slug":"real-lives","id":23,"channels":[{"3854":"Dave"},{"3866":"Yesterday"},{"3858":"GOLD"}],"brand_count":10},{"name":"Factual Entertainment","slug":"factual-entertainment","id":51,"channels":[{"3854":"Dave"},{"3866":"Yesterday"},{"3858":"GOLD"},{"3844":"Eden"},{"3850":"Good Food"}],"brand_count":60},{"name":"Movies","slug":"movies","id":56,"channels":[{"3854":"Dave"},{"3858":"GOLD"},{"4646":"Drama"}],"brand_count":1},{"name":"Music","slug":"music","id":57,"channels":[{"3866":"Yesterday"},{"3854":"Dave"},{"4646":"Drama"}],"brand_count":8},{"name":"Best Of Dave","slug":"best-dave","id":70,"channels":[{"3854":"Dave"},{"3858":"GOLD"},{"3866":"Yesterday"}],"brand_count":15}]},{"name":"Documentaries","slug":"documentaries","id":4,"subcategories":[{"name":"History","slug":"history","id":17,"channels":[{"3866":"Yesterday"}],"brand_count":71},{"name":"Military & War","slug":"military-war","id":18,"channels":[{"3866":"Yesterday"}],"brand_count":38},{"name":"Natural History","slug":"natural-history","id":20,"channels":[{"3844":"Eden"},{"3854":"Dave"},{"3866":"Yesterday"},{"3858":"GOLD"}],"brand_count":13},{"name":"Engineering","slug":"engineering","id":68,"channels":[{"3866":"Yesterday"},{"3854":"Dave"},{"3858":"GOLD"},{"3844":"Eden"}],"brand_count":22}]}]}


Regards Mick

________________________________

**Comment by wwark** [comment]
I understand you are on Kodi 19 RC1.
I'm still on Kodi 18 ...
It might have an issue with the json lib to parse this json on Kodi 19 RC1.

**Comment by berkhornet** [comment]
Yes I am on Kodi 19 RC1. Catch Up TV function did work ok on the earlier Alpha versions

Regards Mick

________________________________

**Comment by wwark** [comment]
Sorry the support of Kodi 19 RC1 is not well on CUTV & More.
We waiting some tiers addons used by CUTV & More to be available to Kodi 19 RC1.

**Comment by berkhornet** [comment]
No worries. Thanks for your help.

I reinstalled CUTV 0.2.28 beta 15 as per the Kodi 19 instructions, but this time deleted the addon and settings first. Everything is now working again.



Regards Mick

________________________________
