### ISSUE TITLE
TF1 Replay error

### ISSUE THREAD

**Issue by marcteyssier** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#405]
Hi,

I want to display a TF1 replay, the direct is ok, the list is ok, but when I click on a video there is no action.
I see in log an error with a 403. I am in France.
So I don't know why.
Kodi 18.9
Catchup 0.2.27

Can you help me ?

Thanks
Marc

> 2021-01-20 20:58:27.323 T:3011919888  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/mytf1/get_video_url/?_pickle_=80027d71012855075f7469746c655f7102584e00000039303231302042657665726c792048696c6c73203a204e6f7576656c6c652047c3a96ec3a9726174696f6e202d2053303520453137202d204c6120666f6c696520646573206772616e64657572735508766964656f5f6964710358080000003133363536313338752e
2021-01-20 20:58:27.460 T:3011919888   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for https://ios-q1-ssl.tf1.fr/2/USP-0x0/61/38/13656138/ssm/13656138.ism/13656138.m3u8?e=1611173307&max_bitrate=4000000&st=rRnMxYkbd3cbEKdIBEyPyg
2021-01-20 20:58:27.463 T:2555376496  NOTICE: Creating InputStream
2021-01-20 20:58:27.532 T:2555376496   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
2021-01-20 20:58:27.532 T:2555376496   ERROR: CCurlFile::Open failed with code 403 for https://ios-q1-ssl.tf1.fr/2/USP-0x0/61/38/13656138/ssm/13656138.ism/13656138.m3u8?e=1611173307&max_bitrate=4000000&st=rRnMxYkbd3cbEKdIBEyPyg:
2021-01-20 20:58:27.533 T:2555376496  NOTICE: Creating Demuxer
2021-01-20 20:58:27.571 T:2555376496   ERROR: OpenDemuxStream - Error creating demuxer

**Comment by wwark** [comment]
Hi @marcteyssier,

The content is blocked. Do you have a proxy or a VPN ?
If you try to play this content in a web browser on the same network of Kodi, it is work ?

**Comment by detourbr** [comment]
Hey,
Same here, it doesn't looks like a network related issue.
Seems like TF1 put some authentication to access their content...

**Comment by marcteyssier** [comment]
I don't have any proxy and when I copy/paste the link in my web browser (on my computer) is the same 403 from nginx.
:-(

**Comment by wwark** [comment]
Un fix est disponible dans la dernière beta 17 du plugin.
Pourriez-vous le tester ?
Merci,

**Comment by detourbr** [comment]
Works like a charm :+1: 

That was a quick fix ! Thanks !

**Comment by wwark** [comment]
On se basait sur un contenu pour vérifier si le contenu était protégé par DRM ou non.
Ce point ne fonctionnait plus donc on a basculer tous les replays en mode de lecture avec la gestion des DRM.

**Comment by marcteyssier** [comment]
Tout fonctionne avec la beta.
Merci beaucoup :-)
Et super rapide en plus. Beau travail.

**Comment by marcteyssier** [comment]
Corrigé dans la beta

**Comment by wixaw** [comment]
Bonjour @marcteyssier 
La dernière c'est bien la beta15 ? Auquel cas cela ne fonctionne toujours pas
Merci

**Comment by hlesueur** [comment]
Hello
Le fait de simplement installer la version beta depuis le repo catch up n'a pas résolu le problème chez moi mais par contre ça m'a affiché l'erreur qui se produisait: " inputstream.adaptive not available "

j'ai résolu sur mon rasp. pi3, en installant inputstream en ligne de commande
sudo apt-get install kodi-inputstream-adaptive
