### ISSUE TITLE
Les liens de MyTF1 replay ne fonctionnent plus

### ISSUE THREAD

**Issue by zygolux** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#406]
### Describe the bug
Les liens de MyTF1 replay ne fonctionnent plus

### To Reproduce
1. CUTVM, France, MyTF1, TMC, Info, Quotidien
2. Aucun lien ne fonctionne
3.
4.

### Expected behavior
La replay se lance

### Actuel behavior
La video ne se lance pas

### Your environment
 - [ ] Android
 - [ ] iOS
 - [x] Linux - Problème sur Ubuntu 20.04
 - [ ] OSX
 - [x] Raspberry-Pi - Problème aussi sur 2 Pis/Raspbian
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 18.06
 - Catch-up TV & More version: 0.2.27
 - Installation method: Repo

### Additional context
Fonctionnait encore hier soir

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by Mattt1438** [comment]
Bonjour,

Même problème chez moi.
Il semblerait que MyTF1 oblige à être connecté pour pouvoir accéder aux vidéos maintenant.
Je vois des erreurs 403 quand j'essaye de lancer une vidéo.

`2021-01-20 19:24:11.394 T:2147135696   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
2021-01-20 19:24:11.394 T:2147135696   ERROR: CCurlFile::Open failed with code 403 for https://ios-q1-ssl.tf1.fr/2/USP-0x0/16/69/13761669/ssm/13761669.ism/13761669.m3u8?e=1611189250&max_bitrate=4000000&st=r6gBA3MAAzTzcKAFzCr0Qw:`

**Comment by wwark** [comment]
Bonjour,

Ce point a été corrigé dans ce ticket https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/405
Le fix est disponible dans la dernière bétâ.

Merci,

**Comment by zygolux** [comment]
Merci

**Comment by prisca56** [comment]
Bonjour,
Est ce que quelqu'un peux m'explique comment réparer l'erreur?
Merci

**Comment by zygolux** [comment]
Bonjour,
Je ne sais pas s'il y a plus simple, mais j'ai enlevé l'addon et ré-installé la version Beta, depuis le repo.
Suivre les instructions ici: https://catch-up-tv-and-more.github.io/installation/
Merci.

**Comment by hlesueur** [comment]
Hello 
j'ai eu le même souci, 
Le fait de simplement installer une version (beta) depuis le repo catch up n'a pas résolu le problème mais par contre ça m'a affiché l'erreur qui se produisait: " inputstream.adaptive not available "

et je décris [ici ](https://forum.mpdb.tv/index.php/topic,37998.msg284757.html#msg284757) comment j'ai résolu sur mon rasp. pi3

**Comment by wwark** [comment]
La nouvelle release est disponible.
Je ferme le ticket !
