### ISSUE TITLE
MyTF1 - ERROR 404 Live TV - Catchup TV / Fix beta versionb 0.2.29beta01

### ISSUE THREAD

**Issue by zygolux** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#407]
### Describe the bug
A clear and concise description of what the bug is:
None of the MyTF1 replay links work. Error is "HTTP Error code 404: This resource is no longer available". I have tried to access the same resource from a web browser and it worked.
  
### To Reproduce
1. Click any link from MyTF1 Replay
2.
3.
4.

### Expected behavior
A clear and concise description of what you expected to happen:
Video starts
### Actuel behavior
Tell us what happens instead:
Video won't start
### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [x] Linux Ubuntu 20.04
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 18.6
 - Catch-up TV & More version: 0.2.29 Beta / 0.2.28 both versions give the error 
 - Installation method: From CUTV Repo Release/Beta

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):
2021-01-25 10:52:31.851 T:139710160140032   ERROR: [Catch-up-TV-&-More.support] HTTP Client Error 404: Not Found
                                            Traceback (most recent call last):
                                              File "/home/julien/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 325, in run_callback
                                                results = route.function(parent_ins, *arg_params, **self.callback_params)
                                              File "/home/julien/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/mytf1.py", line 294, in get_video_url
                                                max_age=-1)
                                              File "/home/julien/.kodi/addons/script.module.codequick/lib/urlquick.py", line 1427, in get
                                                return session.request(u"GET", url, params=params, **kwargs)
                                              File "/home/julien/.kodi/addons/script.module.codequick/lib/urlquick.py", line 1049, in request
                                                resp.raise_for_status()
                                              File "/home/julien/.kodi/addons/script.module.codequick/lib/urlquick.py", line 1358, in raise_for_status
                                                raise HTTPError(self.url, self.status_code, self.reason, self.headers)
                                            HTTPError: HTTP Client Error 404: Not Found

**Comment by TheToto** [comment]
I can confirm the issue, on my ArchLinux laptop and Android TV with a working MyTF1 account

**Comment by ayoub-benali** [comment]
Same issue with live TV

**Comment by Zord97** [comment]
Same problem with kodi on my pi4 Librelec and kodi on win10.
can't watch mytf1 channels and 6plays enven update 0.2.29

**Comment by rjousse18** [comment]
Same for me on librelec pi4

**Comment by wwark** [comment]
A fix is available on 0.2.29Beta01.
Thanks,

**Comment by rjousse18** [comment]
when it will be available on "official" release ?

**Comment by wwark** [comment]
I don't know for the moment.
Wait maybe three or four days to be sure it is stable.

**Comment by zygolux** [comment]
Works great ! Thank you.

**Comment by bast69** [comment]
In parameters, does it have a section to insert login and password for MYTF1 ?

**Comment by wwark** [comment]
MYTF1 doesn't require a login/password for this plugin.

**Comment by FredericKruger** [comment]
Hi everyone, how can I retrieve the latest beta on Kodi so as to be able to watch TF1 again ? My Kodi is still on 0.2.29~beta00

**Comment by Zord97** [comment]
It work on my pi4
thank you for your speed

**Comment by Zord97** [comment]
> Hi everyone, how can I retrieve the latest beta on Kodi so as to be able to watch TF1 again ? My Kodi is still on 0.2.29~beta00

install with this repository

**Comment by raspi57** [comment]
Hi, now with the 0.2.29~beta02 some replay from TF1 like "DOC" are in original language (spanish)

**Comment by raspi57** [comment]
Hi,
how to install a beta from repository
https://github.com/Catch-up-TV-and-More/repository.catchuptvandmore   ?

**Comment by wwark** [comment]
https://catch-up-tv-and-more.github.io/fr/installation/
Il faut choisir le repo béta.
Merci.

**Comment by tidus84000** [comment]
Bonjour,
Merci pour cette superbe application la dernière version corrige le problème de lecture de vidéos sur TF1
Merci aux développeurs et aux contributeurs

Hello,
Thanks for this awesome application the last beta version works on TF1 replays streaming video
Thanks to all devellopers and contributors

**Comment by wwark** [comment]
The release is available with MyTF1 fixes.
La nouvelle version est disponible avec les corrections pour MyTF1.

**Comment by Ykwily** [comment]
Bonjour, j'ai installé hier soir la beta 0.2.30 et cela fonctionne correctement.

**Comment by eva19291989** [comment]
Bonjour
Le replay de TF1 ne propose que la langue originale de la série on n’a donc plus de série en français comment faire ?

**Comment by wwark** [comment]
Bonjour @eva19291989 ,

Vous pouvez suivre la configuration présente ici : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/417

Merci,
