### ISSUE TITLE
Problème avec Arte

### ISSUE THREAD

**Issue by DidierMasse** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#408]
Bonjour à tous !

Je viens reporter un problème relatif à Arte. 
Depuis quelques jours il n'est plus disponible. 

Quelqu'un a une solution ou il fait attendre une mise à jour ?

Merci

**Comment by wwark** [comment]
Bonjour @DidierMasse,

Un hack (fix) a été apporté à la 0.2.29beta02.

Merci,
Wwark

**Comment by DidierMasse** [comment]
> Bonjour @DidierMasse,
> 
> Un hack (fix) a été apporté à la 0.2.29beta02.
> 
> Merci,
> Wwark

Ok, mais je ne l'ai pas dans les mises à jour, la dernière pour moi est la 0.2.28.
On peut avoir les bêta ?

**Comment by wwark** [comment]
Oui vous pouvez suivre cette procédure et choisir le repo béta. 
https://catch-up-tv-and-more.github.io/fr/installation/

**Comment by wwark** [comment]
La release est disponible.
Je ferme le ticket.
