### ISSUE TITLE
404 not found sur TF1 replay

### ISSUE THREAD

**Issue by Fourfour06** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#409]
Bonjour,

Depuis quelques jours lorsque j'essaye d'accéder à un programme en replay sur TF1 (exemple Les 4400) j'obtiens un 404 not found alors que la série semble bien être toujours dispo en replay sur le site MyTF1.

Auriez-vous des suggestions ?

Merci

**Comment by rjousse18** [comment]
Duplicate of #407
