### ISSUE TITLE
TF1/TMC ne fonctionnent plus

### ISSUE THREAD

**Issue by Michael-A-D** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#415]
### Describe the bug
CatchupTV ne trouve plus les replay TF1/TMC depuis quelques jours. Pour être exact, la liste des émissions semble correcte, mais une erreur 404 est levée quand on essaie de les lire

### To Reproduce
1. Naviguer jusqu'à la liste des replay d'une émission sur TF1/TMC
2. Lancer une vidéo (dernier clic avant que la vidéo soit jouée), et constater une erreur 404

### Expected behavior
On attend que la vidéo se joue.

### Actuel behavior

Une erreur "This ressource is not avaulable s'affiche" avec une notification "HTTPClientError: 404 not found".

dans kodi.log on peut lire:

>2021-01-29 09:22:05.158 T:1025450208   ERROR: [Catch-up-TV-&-More.support] HTTP Client Error 404: Not Found
>                                           Traceback (most recent call last):
>                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 325, in run_callback
>                                                results = route.function(parent_ins, *arg_params, **self.callback_params)
>                                             File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/mytf1.py", line 294, in get_video_url
                                                max_age=-1)
>                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 1427, in get
>                                                return session.request(u"GET", url, params=params, **kwargs)
>                                             File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 1049, in request
>                                                resp.raise_for_status()
>                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/urlquick.py", line 1358, in raise_for_status
>                                                raise HTTPError(self.url, self.status_code, self.reason, self.headers)
>                                            HTTPError: HTTP Client Error 404: Not Found
>2021-01-29 09:23:08.701 T:1536065760  NOTICE: ES: Client  from ::ffff:192.168.1.10 timed out
>2021-01-29 09:24:07.619 T:1915806640   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/mytf1/get_video_url/?_pickle_=80027d71012855075f7469746c655f7102582e00000051756f74696469656e2c207072656d69c3a8726520706172746965206475203238206a616e7669657220323032315508766964656f5f6964710358080000003133373633313732752e]
`
### Your environment
 - Raspberry-Pi

 - Operating system version/name:
 

>osmc@lady:~ 
>$ lsb_release -a
>No LSB modules are available.
>Distributor ID:	Debian
>Description:	Debian GNU/Linux 10 (buster)
>Release:	10
>Codename:	buster
>osmc@lady:~ 
>$ grep VERSION_ID /etc/os-release
>VERSION_ID="2020.11-1"
 
- Kodi version:
`
18.9 Media Center Kodi
`
 - Catch-up TV & More version: 0.2.28

**Comment by rjousse18** [comment]
Duplicate of #407
