### ISSUE TITLE
TF1 Original language in replay

### ISSUE THREAD

**Issue by Thomas-Houtrique** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#417]
### Describe the bug
When I watch a replay of a series or a movie that is not produced in French but have a translation the original language is set by default is it possible to change the language somewhere?

### Your environment
 - [x ] Raspberry-Pi

 - Kodi version: 18.9
 - Catch-up TV & More version: 0.2.29-beta03

**Comment by wwark** [comment]
Hi @Thomas-Houtrique ,

You can change with this option during the content is playing in Kodi.
![Screenshot from 2021-01-29 18-35-00](https://user-images.githubusercontent.com/469461/106308354-e008fd00-6260-11eb-8350-89688eb382b0.png)

I need to find how to set french by default.
I will let this ticket opened until we find a way.

Thanks,

**Comment by wwark** [comment]
If you set this option to french in kodi settings -> player -> language. The replay will start directly in French
![Screenshot from 2021-01-29 18-40-15](https://user-images.githubusercontent.com/469461/106308765-79381380-6261-11eb-8cb1-8e2d014562fd.png)

**Comment by Thomas-Houtrique** [comment]
It's working ! Thanks for your time 👍
