### ISSUE TITLE
Bug lors de l'ajout de l'add on

### ISSUE THREAD

**Issue by Guillaumeexc** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#418]
Bonjour,

Lors de l'installation de l'add on dans kodi, en suivant le tutoriel j'arrive au moment où il faut installer les add on.

Néanmoins lors que je clique sur installer, cela ne fonctionne pas et m'affiche en haut à droite fichier "The dependency for script.module.idna could not be found".
![image](https://user-images.githubusercontent.com/48689108/106357888-447f9700-6309-11eb-83f5-714645f8a517.png)

Je crois avoir suivi la procédure décrite à la lettre mais n'arrive pas a faire fonctionner le programme.

Cordialement

**Comment by wwark** [comment]
Bonjour @Guillaumeexc,
Oui cette dépendance est requise (installé automatiquement)
Quelle est votre version de Kodi ? Est-ce une Kodi custom n'ayant pas accès au dépot officiel de Kodi ?

Merci,
Wwark

**Comment by Guillaumeexc** [comment]
Merci pour votre réponse très rapide !
J'ai testé avec deux version de kodi, la 18.9 (disponible sur leur site officiel ) et la version 18.0 disponible dans leurs archives. J'ai également tester sur deux différents ordinateurs découlant sur le meme probleme.

Cordialement

**Comment by wwark** [comment]
Ok Kodi a surement un soucis ...
Vous pouvez la récupérer ici https://mirrors.kodi.tv/addons/leia/script.module.idna/
Il faut installer manuellement le zip via "Install from zip file" dans les installateur des addons.

**Comment by Guillaumeexc** [comment]
Merci pour cette réponse qui fonctionne (partiellement).
En effet afin de faire fonctionner le programme j'ai du aussi manuellement ajouter les dépendances :
script.module.pytz
script.module.future

Bonne fin de journée & merci encore.
