### ISSUE TITLE
how back to the 0.2.28? (0.2.29 can't be installed)

### ISSUE THREAD

**Issue by ahahahaah** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#419]
hello
i dont know why but when i download/install kodi (windows os), yesterday i could install catchup and today there is a message
"the dependency on script module .... version 2.6 could not be satisfied"
i have noticed that it is now the 0.2.29, so i wanted to install the 0.2.28 because this one can be installed.
thanks

**Comment by wwark** [comment]
Hi,
We have the same behaviour here https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/418
I think it might be an issue on kodi side ...
Could you please try in one or two hours to see if the issue remains ?
Thanks,

**Comment by ahahahaah** [comment]
re,
Je me rends compte qu'on peut parler français donc je continue en Francais

alors, en fait le problème reste le même. Au pire si le probleme vient de kodi, moi ca me gene pas de remettre la version 0.2.28. Je sais qu'elle fonctionne parce que hier j'ai pu l'installer, c'est le passage à la 0.2.29 qui bloque.
As tu un lien qui puisse m'amener à l'ancienne version?
merci

**Comment by wwark** [comment]
Vous pouvez tester cette release https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/releases/tag/v0.2.28 mais le soucis sera le même. Ce n'est pas lié à la version.
Vous pouvez suivre le contournement du ticket #418 

Merci,

**Comment by sy6sy2** [comment]
Hello, il y a un actuellement un problème avec un miroir Kodi qui contient les plugins et scripts officiels. Du coup quand Kodi essaye d'installer les dépendances à CUTV&M il échoue 😕.
Il faut soit attendre que la Team Kodi règle le problème ou bien à la main télécharger l'ensemble des dépendances de CUTV&M depuis https://mirrors.kodi.tv/addons/ et les installer.
Désolé 😕

**Comment by ahahahaah** [comment]
d'accord merci pour les infos.
je ne suis pas sûr de savoir faire les installations manuelles, donc je vais attendre un peu que le bug soit résolu
merci

**Comment by wwark** [comment]
Normalement ça devrait être bon là.
Il semblerait que c'est corrigé.

**Comment by ahahahaah** [comment]
oui je confirme, là c'est reparti. ;)

**Comment by wwark** [comment]
Cool je ferme le ticket !
Bon replay :)
