### ISSUE TITLE
TF1 live tv do not work any more

### ISSUE THREAD

**Issue by sergio49** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#420]
### Describe the bug
A clear and concise description of what the bug is:

Can't access TF1 french tv live.

### To Reproduce
1.
2.
3.
4.

### Expected behavior
A clear and concise description of what you expected to happen:

### Actuel behavior
Tell us what happens instead: error 404 http client.

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: leia 18.9
 - Catch-up TV & More version: latest
 - Installation method: kodi repo

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by wwark** [comment]
Hi @sergio49,

If you are not in version 0.2.29 of the plugin CUTV&More it is normal. You need to upgrade the version of CUTV & More.
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/407

Thanks,

**Comment by sergio49** [comment]
The new version is not available to download from catchup repo or kodi repo. I will try thrugh githup addon thanks

**Comment by sergio49** [comment]
I got it from tvaddons. It works fine thankyou very much, it's a great addon 👍👍
