### ISSUE TITLE
Route missing gulli

### ISSUE THREAD

**Issue by rjousse18** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#422]
### Describe the bug
A clear and concise description of what the bug is:

### To Reproduce
1.aller dans tv
2.essayer de lancer gulli

### Expected behavior
Quand j'essaie de lancer gulli, j'ai une erreur "route missing unable To import route..." qui apparaît 

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: libreelec avec leia 18.9
 - Catch-up TV & More version: 0.2.29

**Comment by wwark** [comment]
Hi @rjousse18 ,
Do you have issue with other Live TV ?
If it is not the case, could you please "clear cache" on settings of CU TV&More ?

Thanks,

**Comment by rjousse18** [comment]
There is no changes

**Comment by wwark** [comment]
Ok bizarre ... est-ce que le cas persiste si vous desinstaller le plugin et le reinstaller ?
Merci,

**Comment by rjousse18** [comment]
Aucun changement non plus :p

**Comment by wwark** [comment]
Ok pourriez-vous refaire un log en mode debug et le poster ici ?

Merci,

**Comment by rjousse18** [comment]
Le problème est résolu! J'explique ce qu'il s'est passé: 
J'ai fait un fichier m3u qui cumule des chaînes de catchup tv avec des chaînes de mon abonnement iptv. Depuis la dernière mise à jour vous passez par 6play pour avoir gulli donc le lien vers gulli à changé et moi je ne l'avais pas modifié d'où le route missing. Maintenant que je l'ai changé tout fonctionne parfaitement. (Sauf les chaînes de France tv mais ce problème à déjà été report)
