### ISSUE TITLE
chaines tunisiennes aucune ne fonctionne?

### ISSUE THREAD

**Issue by ahahahaah** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#423]
salut,
j'ai voulu tester les 3 chaines tunisiennes mais aucune ne fonctionne.
est ce que vous pouvez les tester et me dire si elles fonctionnent de votre côté?
merci

**Comment by wwark** [comment]
Bonjour @ahahahaah,

Pour Nessan, le contenu est géolocalisé et il est disponible que pour ces pays (la France n'est pas dans la liste)

This video is available in Saint Barthélemy, Togo, Western Sahara, Mexico, Seychelles, Zimbabwe, Iraq, Pitcairn, Heard Island and McDonald Islands, Ecuador, Niue, Malaysia, Anguilla, Burkina Faso, Myanmar, Micronesia, Federated States of, Canada, Afghanistan, Germany, Qatar, Svalbard and Jan Mayen, Congo, the Democratic Republic of the, Poland, Maldives, French Polynesia, Tanzania, United Republic of, Jamaica, Saint Vincent and the Grenadines, Cuba, Belgium, Turks and Caicos Islands, Norfolk Island, Namibia, Djibouti, Turkmenistan, Åland Islands, Luxembourg, United States, San Marino, Bermuda, Puerto Rico, American Samoa, United Kingdom, Estonia, Lebanon, South Sudan, Japan, Cape Verde, Fiji, Belarus, Haiti, Gambia, Botswana, Saint Lucia, Thailand, Czech Republic, Algeria, India, Ghana, Korea, Democratic People's Republic of, Croatia, Rwanda, Palestine, State of, Burundi, Romania, Argentina, Réunion, Swaziland, Vanuatu, Guatemala, Kiribati, Sweden, Bangladesh, Tajikistan, South Georgia and the South Sandwich Islands, Northern Mariana Islands, Guam, Mayotte, Lao People's Democratic Republic, Nepal, Albania, Cambodia, Netherlands, Antigua and Barbuda, Wallis and Futuna, Bulgaria, Jordan, Yemen, Uganda, Greenland, Macedonia, the Former Yugoslav Republic of, Comoros, Mauritania, Somalia, Suriname, Central African Republic, Libya, Viet Nam, Malawi, Tonga, Sri Lanka, Virgin Islands, British, Cayman Islands, Australia, Mongolia, Dominican Republic, Trinidad and Tobago, Monaco, Ireland, Mozambique, Uzbekistan, Cook Islands, New Caledonia, China, Italy, Bonaire, Sint Eustatius and Saba, Philippines, Greece, Montserrat, Equatorial Guinea, Cameroon, Sudan, Saudi Arabia, Faroe Islands, Guernsey, Austria, Grenada, Korea, Republic of, Egypt, Saint Pierre and Miquelon, Tunisia, Kenya, Hong Kong, Macao, Congo, Mali, Syrian Arab Republic, Latvia, Spain, Cyprus, Sao Tome and Principe, Liberia, Paraguay, Jersey, Oman, Holy See (Vatican City State), Venezuela, Bolivarian Republic of, Bahrain, Guinea, Armenia, Nigeria, Azerbaijan, Dominica, Saint Martin (French part), Angola, Guyana, Uruguay, Aruba, Costa Rica, Finland, Lesotho, Montenegro, Morocco, Iceland, Antarctica, Belize, Saint Helena, Ascension and Tristan da Cunha, Sierra Leone, Madagascar, French Guiana, Mauritius, United Arab Emirates, Timor-Leste, United States Minor Outlying Islands, Ethiopia, Lithuania, Chile, Singapore, Niger, Barbados, British Indian Ocean Territory, Moldova, Republic of, Honduras, Saint Kitts and Nevis, Bouvet Island, Serbia, Ukraine, Andorra, Nicaragua, Nauru, Indonesia, Sint Maarten (Dutch part), Bosnia and Herzegovina, Iran, Islamic Republic of, Israel, Kazakhstan, Norway, Benin, Slovakia, Liechtenstein, Georgia, Gabon, El Salvador, Hungary, Cocos (Keeling) Islands, Portugal, Kyrgyzstan, Papua New Guinea, Virgin Islands, U.S., Colombia, French Southern Territories, Solomon Islands, Peru, Switzerland, Zambia, Pakistan, Brazil, Bhutan, South Africa, Senegal, Panama, Taiwan, Province of China, Falkland Islands (Malvinas), Marshall Islands, Russian Federation, Isle of Man, Kuwait, Chad, Samoa, Tokelau, Tuvalu, Curaçao, Guinea-Bissau, Bahamas, Brunei Darussalam, Christmas Island, Gibraltar, Guadeloupe, Martinique, Palau, Slovenia, Côte d'Ivoire, Malta, Eritrea, Bolivia, Plurinational State of, Denmark, New Zealand.

Il y a un soucis pour les deux autres lives TV.

**Comment by wwark** [comment]
La beta 0.2.30beta02 contient le fix pour watania 1et 2.
Cependant, il faut suivre aussi cette procédure pour mettre à jour youtube-dl : https://catch-up-tv-and-more.github.io/fr/faq/#i-erreurs-li%C3%A9es-%C3%A0-youtube-dl

Le plugin youtube-dl n'est pas mis à jour suivant donc il faut prévoir le mettre à jour de temps en temps à la main.

Merci,
Wwark

**Comment by ahahahaah** [comment]
Merci pour les réponses.
J'ai suivi la procédure pas à pas expliquée dans le lien, mais aucune des 2 chaines ne fonctionne.
du coup après le message d'erreur, kodi me propose un log, j'ai récupéré le lien https://paste.kodi.tv/ecafunetit

de ton côté quand tu mets à jour youtube-dl tu parviens à recevoir les chaînes?

**Comment by wwark** [comment]
Votre version est "2021-02-02 20:42:09.724 T:7400  NOTICE: ADDON: plugin.video.catchuptvandmore v0.2.28 installed"
Il faudrait installer la version 0.2.30beta02 qui contient la correction.

**Comment by ahahahaah** [comment]
je sais que je pose plein de questions mais j'utilise le lien https://repo.cecchettosylvain.fr/zip/ pour installer catchup avec le menu "install from zip file". dans les choix proposés il n'y a pas de version 0.230beta02 ou alors je ne regarde pas au bon endroit?

**Comment by wwark** [comment]
Il faut suivre cette procédure et choisir ce repo.

    Si vous utilisez Kodi Krypton (17), Leia (18) ou Matrix (19) installez une des versions repository.catchuptvandmore.krypton-leia-matrix.XXXXXX.

Enfin, vous pouvez choisir entre la version release et beta du dépôt.

XXX = beta

**Comment by ahahahaah** [comment]
merci maintenant ca marche niquel!

Par contre pour la 3e chaine, pour la liste des pays de diffusion il y a tous les pays du monde sauf la France... lol ca fout les boules.
Pouvez vous me donner le lien de la page où vous avez récupérer cette liste svp? je vais essayer de chercher des infos sur la chaine. merci

**Comment by ahahahaah** [comment]
ah je vois, ca vient du message du log.
Du coup j'ai mis les informations d'un proxy en belgique que j'ai trouvé sur internet dans l'option "internet access". mais sans succes

**Comment by wwark** [comment]
Vous pouvez déjà tester votre configuration VPN/PRoxy sur un navigateur web à cette url https://www.nessma.tv/ar/live.
Quand vous avez une configuration réseau qui fonctionne vous pouvez ensuite l'appliquer sur Kodi.

Merci,

**Comment by ahahahaah** [comment]
avec les infos proxy ci-dessus ca fonctionne sur navigateur:
voici un screen [https://i.ibb.co/r6HZgjw/Sans-titre.jpg](url)

mais quand j'entre exactement ces mêmes infos sur kodi, ca ne passe pas.

**Comment by wwark** [comment]
Ok Kodi doit fonctionner différement pour ces infos du proxy ...
Je n'ai jamais configuré un proxy dans Kodi.

Après dans le plugin on ne recupère pas d'info de proxy (possible ?) pour les transmettre au player de Kodi.
Ce point aurait un refus sur la soumission du plugin dans le repo officiel de Kodi.

Merci,
Wwark

**Comment by ahahahaah** [comment]
Ce serait donc un problème du côté de kodi?

**Comment by wwark** [comment]
Je ne sais pas mais nous ne positions aucune configuration Proxy au niveau du plugin.
La configuration du Proxy dans Kodi je ne sais pas comment ça se fait et à quel niveau le proxy peut intervenir.

Si vous pouvez positionner le proxy au niveau de votre boxe internet, vous aurez tous les flux passant par ce proxy et vous permettra normalement d'accéder à cette ressource depuis votre navigateur et du kodi.

**Comment by ahahahaah** [comment]
Du coup, j'ai voulu testé sur tablette android en mettant la version beta de catchuptv, et en mettant la derniere version de youtube-dl mais sur tablette ca ne marche pas: voici le log http://paste.kodi.tv/dorakumedu
je me demande si le fichier youtube-dl de windows est aussi valable pour android

**Comment by wwark** [comment]
Le log indique que la procédure n'a pas été correctement effectuée.
Il faudrait reinstaller YT-DL pour remettre à zero et refaire la procédure.
Les fichiers à copier sont compatibles tout environnement.

Cordialement,

**Comment by ahahahaah** [comment]
Désolé j'ai effacé mon message au moment où tu as rédigé le tien. En fait jme suis aperçu que ce n'était pas le bon dossier que j'ai extrait du zip. Je m'en suis aperçu après coup. Après correction ca a fonctionné et j'ai retiré mon message.
Désolé

**Comment by wwark** [comment]
Cool !

**Comment by wwark** [comment]
Je ferme cette issue.
N'hésite pas à la rouvrir si besoin.

Merci !
