### ISSUE TITLE
Information concernant Kodi 19

### ISSUE THREAD

**Issue by Europe57** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#425]
Bonjour, j'ai vu que pour Kodi 19, l'Issues https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/363

Je me demandais, un portage native est-il prévu prochainement, vu que la sortie ne serais tarder et j'ai peur que les mises à jour auto sur mes équipements (Android) vont bloquer l'accès à l'extension.

J'ai tester sur Windows avec les Reposity dispo ici : https://github.com/Catch-up-TV-and-More/repository.catchuptvandmore/tree/master/repo_addons_src

Mais aucun ne veut installer l'extension.

Donc ça me posais cette interrogation, vu que Kodi 19 est passer en version RC, donc la version final devrais bientôt être disponible et être MAJ via les stores.

Merci pour vos éclaircissements.

**Comment by wwark** [comment]
Bonjour @Europe57 
On en attente de plugin tiers que nous utilisons dans CUTV&More pour pouvoir proposer une release officiel kodi 19.

Nous utilisons le plugin- youtube-dl pour lire les contenus YT, daylimotion, viméo et pour l'enregistrement. Il n'est pas encore dans le dépot officiel de Kodi 19.

Merci,
Wwark

**Comment by Europe57** [comment]
Bonjour @wwark 

Merci pour cette éclaircissement.

**Comment by enigma131** [comment]
Bonjour à vous 2. Le suivi de la version finale de Kodi 19 est ici : https://github.com/xbmc/xbmc/milestone/140
Sa sortie est effectivement pévue pour le 14 février, c'est bientôt.

**Comment by wwark** [comment]
Le YT DL a été proposé pour somission sur le repo officiel de Matrix.
Merci @sy6sy2 !
![image](https://user-images.githubusercontent.com/469461/106936772-438da180-671d-11eb-9f5f-68d2a8a6a970.png)

**Comment by enigma131** [comment]
Pour info, Fedora 33 a passé Kodi 19 en RC1

**Comment by lanzorg** [comment]
Avez-vous des nouvelles ?
Est-ce que ce sera prêt pour le 14 février ?
Comment connaître l'avancement ?

**Comment by sy6sy2** [comment]
Hello, Youtube-DL est toujours en cours de soumission.
Ruuk, le dev qui est à l'initiative du plugin YT-DL a annoncé qu'il n'était plus intéressé pour maintenant ce plugin et pour continuer à developper pour Kodi.
Il est d'accord pour nous "donner les rênes" donc cela sera plus facile pour nous de mettre à jour YT-DL sur le dépôt officiel de Kodi.

YT-DL devrait être accepté dans les heures/jours prochains, après cela il restera à willford de soumettre la version Kodi 19 de Codequick sur les dépôts officiels (il dépend lui aussi de Youtube-DL). Et enfin nous pourrons déposer CUTV&M.
Pas sûr qu'on soit prêt pour le jour de la sortie officielle de Kodi 19, mais les choses devraient aller assez vite maintenant (en espérant que d'ici 15 jours tout soit ok...).

**Comment by enigma131** [comment]
Kodi 19 final est sorti : 
https://github.com/xbmc/xbmc
Les repos de Ubuntu mettent déja les plugins à jour pour compatibilité V19, les compils finales ne vont pas tarder pour le différentes ditributions

**Comment by wwark** [comment]
Merci pour l'information.
Nous ne sommes pas prêt pour l'instant donc nous rendrons disponibles pour Kodi 19 quand nous pouvons le faire.
En attendant, il faudrait prévoir de bloquer les mises à jour.

Wwark

**Comment by Europe57** [comment]
Merci pour l'info.
Pour ma part les MAJ on été bloquer sur tous les appareils avec mise a jour automatique, bon seul contrainte c'est mettre a jour manuellement chaque applis qu'ils faut mettre a jour.

**Comment by wwark** [comment]
Merci désolé pour le désagrément mais ça fait plusieurs mois qu'on sollicite YT-DL pour être disponible sur le depôt de Kodi 19.
Il doit manquer aussi beaucoup de Plugin sur le dépot pour la sortie de Kodi 19.
Ce point devrait se résorber dans les prochaines semaines ...

**Comment by Europe57** [comment]
Pas grave, vaut mieux ça que de plus avoir accès à l'extension, on va être patient, je sais que tout le monde met de la volonté à passer à la 19. Merci a vous tous.

**Comment by enigma131** [comment]
Voila ce que cela donne pour Ubuntu 20 et dérivées à partir du ppa xbmc (j'applique les mises à jour manuellement, et comme Europe je les bloque, mais ce n'est pas le cas de tout le monde car ces packets sont noyés dans le flot de MAJ hebdomadaires):
![kodi19](https://user-images.githubusercontent.com/31815445/108587258-fb909080-7352-11eb-9793-c832728f3da9.png)
Je vais voir pour Fedora 33 qui as naturellement Kodi 19. J'avais installé le pluggin avec la methode du #363 . Aux derniers essais il manquait les dernières modifications pour France TV et Tf1, voir le fil en question. 
Je peux bien sûr tester les évolutions de cette version sur F33.

**Comment by Europe57** [comment]
Idem pour Android, pour le moment pas d'avertissement de nouvelle version, et pas encore disponible sur le Store (y a au moins 1, voir 2 semaines de battement avant la disponibilité complète partout sur le Store de Google)

**Comment by wwark** [comment]
Lien pour télécharger une version antérieure à Kodi 19 pour ceux qui cherchent à revenir à Kodi 18.9 : http://mirrors.kodi.tv/releases/

Merci,

**Comment by enigma131** [comment]
Merci pour le lien, mais celui-ci n'est pas valable pour Linux. Pour Linux il faut rester vigilant et trier les mises à jour de packets tant que le plugin n'est pas compatible avec Kodi 19. On ne peut pas bloquer toutes le mises à jour pendant des semaines.
Pour info mes plugins pvr fonctionnent sous Kodi 19 Rc1 + Fedora 33, le plugin catchup tv and more aussi sauf France TV et TF1 group, voir l'autre fil

**Comment by zertyuio296** [comment]
Bonjour à tous, pour information je viens de recevoir la mise à jour automatique de KODI 19 sur android (mi box). Je confirme que ça ne fonctionne plus... je creuse l'autre post sur kodi 19 pour essayer de faire fonctionner le plugin en attendant la dispo officiel.
Merci

**Comment by enigma131** [comment]
Message d'avertissement à l'instant en version Linux : 

![Kodi19avert](https://user-images.githubusercontent.com/31815445/108741232-c9d81f00-7536-11eb-95ae-06e3ecce1f97.png)

**Comment by zertyuio296** [comment]
ça refonctionne avec la procédure de Sylvain:

https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/363#issue-710233337

1. Download Youtube-DL Kodi 19 version zip file from this [URL](https://github.com/AnonTester/script.module.youtube.dl/archive/master-kodi19.zip)
2. Open Kodi, go to Add-ons --> Install from zip file and select the Youtube-DL zip file (if needed, allow "Unknown sources")
3. Close Kodi
4. Download Codequick Kodi 19 version from this [URL](https://github.com/willforde/script.module.codequick/archive/v19.zip) and unzip it.
5. Open the freshly unzipped folder and move script.module.codequick folder in your Kodi addons folder (see https://kodi.wiki/view/Kodi_data_folder for the location)
6. Move to plugin.video.catchuptvandmore folder in your Kodi addons folder and apply these patches:
    In addon.xml file 
replace `<import addon="xbmc.python" version="2.25.0"/> by <import addon="xbmc.python" version="3.0.0"/>`
7. Open Kodi

Merci

**Comment by enigma131** [comment]
Tu as les France TV aussi ?

**Comment by wwark** [comment]
Il est préférable de rester en version 18.9 de Kodi.
Le plugin a été très peu testé sur Kodi 19. (du moins de mon côté)
Merci,

**Comment by enigma131** [comment]
Sur Fedora 33 impossible de charger kodi 18.x (essaué x solution avec packets cassé) , c'est la version 19 qui est installée nativement

**Comment by wwark** [comment]
ok ...

**Comment by zertyuio296** [comment]
Bonsoir,
Je confirme que france TV fonctionne chez moi (test de 2-3 série sur France 2 et 3 + live Fr2). 
J'ai même l'impression que c'est un peu plus rapide dans les menus et chargement. 
J'ai fais la modification pour Kodi Matrix car j'avais la flemme de tout réinstaller en 18.9, mais c'est vrai que c'est pas super facile.

il est préférable pour ceux qui le peuvent de désactiver la mise à jour auto de Kodi en 19 (surtout sur android)

si besoin d'autres tests redites-moi

**Comment by lanzorg** [comment]
C'est quoi le soucis avec la version Android ?
Parlez-vous support de plugin.video.catchuptvandmore ou est-ce en général ?

**Comment by wwark** [comment]
La nouvelle version de Kodi 19 a migré la support de la version de python 2 vers la version python 3.
Les plugins tel que catchuptvandmore utilisent cette couche python.
Ce point demande une migration de tous les plugins en python 3 et que ces plugins soient autorisés par le dépots officiels de Kodi.
J'ai mis un de mes device à Kodi 19 et la moitié de plugins que j'utilise ne sont pas portés.
Pour catchuptvandmore, nous attendons l'autorisation du plugin youtube-dl, ensuite codequick qui utilise youtube-dl et nous pourrons proposer catchuptvandmore sur le repo officiel de Kodi 19.

Merci,

**Comment by wixaw** [comment]
Hello @wwark 
Cette nuit kodi à été mise à jour automatiquement en v19 sur android, et impossible de bloquer les updates, et donc CUTV ne fonctionne plus :/

**Comment by wwark** [comment]
Hello @wixaw,
Sous Android, il est possible de bloquer toutes les mises à jour mais surement impactant pour les autres applications.
Lien pour télécharger une version antérieure à Kodi 19 si tu veux revenir à revenir à Kodi 18.9 : http://mirrors.kodi.tv/releases/ en attendant que CUTV&More soit compatible.

Merci,

**Comment by enigma131** [comment]
J'ai reçu le message de mise à jour sous windows ce matin :( 
En attendant, y a - t - il moyen de mettre un popup d'avertissement pour Catchup TV (de ne pas mettre à jour pour l'instant ?)
Concernant la méthode manuelle pour kodi , j'ai effectivement récupéré toutes mes chaines en mettant le plugin à jour (manuellement) , y compris celles avec drm. Merci zertyuio296

**Comment by wwark** [comment]
@enigma131 Je crois que ce point devrait répondre à ta question https://forum.kodi.tv/showthread.php?tid=76600

**Comment by enigma131** [comment]
@wwark Oui bien sur pour l'utilisateur averti ..
Ce que je voulais dire, c'est que celui qui utilise le plugin au quotidien et qui ne passe pas x fois par jour ici n'aura pas fait ce setting. I va recevoir la notification pour la nouvelle version, et va naturellement charger la nouvelle version, surtout sous W10 où ils sont bombardés de MAJ au quotidien et qu'ils ont l'habitude de tout mettre a jour.

**Comment by wwark** [comment]
Oui nous allons aussi regarder pour ajouter une popup indiquant que le plugin n'est pas compatible Kodi 19 "Matrix".
Cependant comme une grande majoritée des systèmes mettent à jour automatiquement, il restera une action de la personne pour bloquer les mises à jour.

**Comment by wwark** [comment]
@enigma131 je viens d'ajouter un message au démarrage du plugin dans la dernière bétâ disponible sur le repo béta de Kodi 18.
Pourrais-tu tester si c'est bon je lancerait une release ?

Merci,

**Comment by enigma131** [comment]
Oui je veux bien tester. Je suis en beta3, je suppose qu'il intervenir manuellement pour tester la beta 4 ... j'ai perdu le lien

**Comment by wixaw** [comment]
Hello @wwark  j'ai reinstall leia sur mon android tv et maintenant apres ajout du path zip , pour installer le repo beta ( ou release ) il me dit failed to install structure invalide :/
Merci pour tes lumieres

**Comment by wwark** [comment]
@wixaw, si vous testez dans un premier temps d'installer CUTV&More depuis le repo officiel de Kodi est-ce que ça fonctionne ?
Pour votre erreur, il faudrait fournir les logs de Kodi en mode debug pour comprendre la cause.

Merci,

**Comment by wixaw** [comment]
Ok ca vient de inet pton
J'ai essayé depuis ici
https://mirrors.kodi.tv/addons/leia/script.module.win_inet_pton/ c'est
pareil même erreur.
Sinon je ne savais pas qu'on pouvait installer depuis le repo Kodi, si
j'avais su avant....

**Comment by McBacon1936** [comment]
> Hello @wwark j'ai reinstall leia sur mon android tv et maintenant apres ajout du path zip , pour installer le repo beta ( ou release ) il me dit failed to install structure invalide :/
> Merci pour tes lumieres
> 
> ![image](https://user-images.githubusercontent.com/7153125/109211525-a1f2f080-77ae-11eb-871b-3d199b7b8410.png)

Salut,
Comment as-tu fait pour réinstaller la version 18.9 sur Android TV ?
Je ne suis pas un grand bidouilleur...
Merci d’avance 😉

**Comment by wwark** [comment]
@wixaw as-tu pu corriger le soucis ?
@McBacon1936, voici le lien pour récupérer des apk des anciennes versions de Kodi : http://mirrors.kodi.tv/releases/

Thanks,

**Comment by wixaw** [comment]
Hello !!!
Ce matin les paquets ont l'air d'aller mieux , CUTV à pu s'installer =)
Désolé pour le dérangement 
Bonne journée

**Comment by enigma131** [comment]
Hello à tous, après les bases Linux Ubuntu et Debian, c'est au tour de Fedora 33 de recevoir la version finale Kodi 19. Tout fonctionne toujours parfaitement avec la méthode de l'autre post.

**Comment by wwark** [comment]
CUTV&More est compatible Kodi 19 depuis le repo bétâ pour ceux qu'ils veulent essayer.
Merci @sy6sy2 !!!

**Comment by enigma131** [comment]
J'ai laissé un commentaire dans l'autre fil, problème avec les drms. Oui merci à Sylvain et à toi wwark!

**Comment by wixaw** [comment]
Hello,
On a eu la mise à jour sur une autre box Android que j'avais pas downgrade
et ça fonctionne niquel sur Kodi 19
Merci

Le sam. 27 févr. 2021 à 11:59, enigma131 <notifications@github.com> a
écrit :

**Comment by SebMourlhou** [comment]
> CUTV&More est compatible Kodi 19 depuis le repo bétâ pour ceux qu'ils veulent essayer.
> Merci @sy6sy2 !!!

Hello
Désolé je débarque un peu mais c'est normal qu'il y ait des sources pour Jarvis et Krypton uniquement ?
https://catch-up-tv-and-more.github.io/repo/

**Comment by enigma131** [comment]
oui relire : https://catch-up-tv-and-more.github.io/fr/installation/
au milieu de la page, tu as : 
Sélectionnez la version de Kodi la plus proche de la votre (si vous utilisez Kodi Krypton (17), Leia (18) ou Matrix (19) choisissez le dossier Krypton_(Kodi_17)).

**Comment by McBacon1936** [comment]
Bonjour à tous,

tout d’abord, un grand merci à toute l’équipe d’avoir travaillé aussi fort pour remettre tout en marche.

Je me demandais si certains d’entre vous avez des problèmes avec M6.
Pour ma part impossible de lire le direct ou le replay.
Merci pour votre aide.

**Comment by SebMourlhou** [comment]
@McBacon1936 : j'ai le même problème.

Testé sous Android TV et aussi sous Windows, mêmes symptomes :
  - direct : pas de guide TV : "Une erreur s'est produite lors de l'obtention du guide TV"
  - replay : OK pour TF1 et France 2 mais HS pour M6 : "erreur inattendue". Mon compte 6play est bien paramétré.

Pour être sûr, j'ai fait un fresh re-install de Kodi 18.9, tout est OK puis je suis repassé sous Kodi 19 et j'ai de nouveau ces erreurs.

Dites-moi s'il est trop tôt pour faire des tickets ?

**Comment by wwark** [comment]
Oui le ticket suit le soucis pour 6PLay et RTLPlay (BE) https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/447
Il y a aussi des soucis pour les live TV de RTBF (BE) https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/444

**Comment by enigma131** [comment]
Fonctionne sous windows 10  et Android + Kodi 19, mais nouveau bug pour w10 et Android, pas d'infos programme, voir l'autre fil #460 . Remarque effacée du fil France TV car hors sujet

**Comment by wwark** [comment]
Kodi 19 est sorti depuis quelques semaines et le plugin est compatible maintenant.
Je ferme donc ce ticket.
Merci,
