### ISSUE TITLE
kodi n'accepte plus que j'ajoute https://repo.cecchettosylvain.fr/zip/

### ISSUE THREAD

**Issue by ahahahaah** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#428]
hello,
quand je veux ajouter la source https://repo.cecchettosylvain.fr/zip/ comme dit dans cette page https://catch-up-tv-and-more.github.io/fr/installation/ et bien ca ne marche plus.
ca marchait hier encore.
j'ai tout desinstaller et j'ai recommencé mais ca ne marche pas. que se passe t'il?

**Comment by sy6sy2** [comment]
Hello,
C’est de la faute, ma connexion internet merde depuis quelques jours donc mon serveur également 😕
J’essaie de rétablir ça.

**Comment by ahahahaah** [comment]
ah! ahah! 
merci :p

**Comment by sy6sy2** [comment]
Ça devrait être bon maintenant 😉

**Comment by ahahahaah** [comment]
c'est parfait merci!

**Comment by wwark** [comment]
Je ferme le ticket !
N'hésitez pas à le rouvrir si besoin.
Merci !
