### ISSUE TITLE
Replay L'equipe ne fonctionnent pas

### ISSUE THREAD

**Issue by EmmanuelR69** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#431]
Bonsoir, 
les replays ne fonctionnent pas pour le site l'Equipe.

Sur le json de l'equipe: https://www6.lequipe.fr/equipehd/applis/filtres/emissions/evenements-_1.json 

Pour la même entrée lien et lien_dm peuvent différer
lien         "video://x7z4vab"
lien_dm   "video://k65aR0I6m0u2F0wDAgH"

lien ne fonctionne pas, lien_dm fonctionne

Dans /resources/lib/channels/fr/lequipe.py
84      video_id = video_datas['lien'].split('//')[1]

remplacer lien par lien_dm ?

Merci

**Comment by wwark** [comment]
Bonjour @EmmanuelR69,

Merci pour la proposition de correction !

Wwark

**Comment by wwark** [comment]
Le fix est présent dans la version 0.2.30beta05.
Encore merci !

**Comment by EmmanuelR69** [comment]
C'est réglé, merci !

**Comment by w1llpeterson** [comment]
Est-ce que ce bug a été vraiment réglé ? Les replays de l'équipe restent bloqués au 24 janvier 2022 (constaté sur kodi stable et beta, avec cathup stable et beta à jour).

**Comment by EmmanuelR69** [comment]
Bonsoir,

Le bug signalé, à savoir que certains liens dans la liste des replays ne 
fonctionnaient pas, a bien été réglé.
Par contre, que la liste des replays ne soit plus mise à jour depuis le 
24 janvier 2022 est un autre bug.

Merci

Le 2022-12-17 15:23, w1llpeterson a écrit :

> Est-ce que ce bug a été vraiment réglé ? Les replays de l'équipe 
> restent bloqués au 24 janvier 2022 (constaté sur kodi stable et beta, 
> avec cathup stable et beta à jour).
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you modified the open/close 
> state.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/431#issuecomment-1356279964
[2]

**Comment by w1llpeterson** [comment]
ok merci https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1048
