### ISSUE TITLE
Tf1 stream non accessible

### ISSUE THREAD

**Issue by lecorossol** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#432]
Bonjour à tous, 

Je n'arrive pas à streamer TF1. J'ai l'erreur suivante : 
The ressource is no longer avaible

Mon fichier m3u ne doit pas avoir la bonne adresse de stream. Quelqu'un pour m'aider ? 

Version : 0.2.28

**Comment by wwark** [comment]
Bonjour @lecorossol,

Il faut migrer à la version 0.2.29, MyTF1 est corrigé à cette version.
Le repo officiel de Kodi ne doit pas encore être à jour.
Si vous souhaitez avoir les mises à jour plus rapidement vous pouvez installer notre répo : https://catch-up-tv-and-more.github.io/fr/installation/

Merci,

**Comment by lecorossol** [comment]
Super j'ai migré et rajouté le dépôt !

Génial tout est ok sur mon raspberry pi 3.

Malheureusement sur mon autre raspberry pi 1 il me dit qu'il manque une librairie non disponible dans ma version (seul TF1 ne fonctionne pas).

**Comment by wwark** [comment]
RP1 ne gère pas les DRM.
Donc TF1 ne pourra plus focntionner sur ce device.

J'aurai aussi une question, comment fonctionne le pi 1 avec le plugin ? Est-ce que c'est fluide ?

Merci,
Wwark.

**Comment by lecorossol** [comment]
Sur le RP1, l'installation était un peu catastrophique, ça prenait pas mal de temps et ai dû rajouter des add on a la main.

Sinon dans l'ensemble ca va, un peu plus lent que le RP3 mais au global je suis satisfait 🤗.

**Comment by lecorossol** [comment]
Y a til un plug-in PVR pr gérer les replay ? Sans avoir à rentrer et fouiller sur catch up ?

**Comment by wwark** [comment]
Non pas à ma connaissance pour le PVR pour gérer les replays.
Il n'y a pas d'autres solutions que de fouiller dans les replays.
Certains possèdent une fonction search mais ce n'est pas le cas de tous.
Merci,
Ww
