### ISSUE TITLE
Prendre en compte les parametres proxy de kodi

### ISSUE THREAD

**Issue by ahahahaah** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#433]
Bonjour,

Je voulais proposer cette idée pour optimiser l'efficacité du plugin catchuptv

**Pour motiver ma demande j'expose d'abord la situation.**
Tous les pays sont autorisés à voir la vidéo de cette page https://www.nessma.tv/fr/live mais pas la France.
Sur Firefox lorsque j'entre ces informations d'un proxy de Belgique 91.181.235.31:4145 protocol socks4, la vidéo est visible comme prévu.

Maintenant quand j'entre ces mêmes informations proxy dans kodi, le log erreur indique que la vidéo est interdite pour la France.
On m'a confirmé que le plugin ne gère pas les infos proxy de Kodi, ce qui confirme donc le message d'erreur.

**Du coup ma demande est de savoir s'il est possible d'ajouter la possibilité de prendre en compte les infos proxy entrées dans kodi?**

Mettre par moi meme des infos proxy sur l'ensemble de ma ligne internet (via la box par exemple) est handicapant au niveau du débit et le transit d'infos sensibles qu'on ne veut pas forcément faire passer par un serveur proxy ne constituent pas une bonne solution... l'utilisation ne serait que pour des données aussi peu sensibles que de regarder une vidéo^^

Voilà j'ai tout dit
merci

**Comment by wwark** [comment]
Bonjour @ahahahaah,

Le fait d'ajouter la gestion du proxy aurait un impact sur la soumission du plugin sur le repo officiel de Kodi.
Donc nous n'intégrons pas de gestion de proxy dans le code de CUTV & More.

Merci,
Wwark.

**Comment by ahahahaah** [comment]
Ok, pas de problème
merci

**Comment by wwark** [comment]
Merci pour la comprehension.
Wwark
