### ISSUE TITLE
Proposition d'ajout de chaîne

### ISSUE THREAD

**Issue by ahahahaah** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#434]
Salut,
Est il possible d'ajouter cette chaine à la catégorie chaines tunisiennes svp?

### Content description

* Name: Attessia TV
* Type: TV channel 
* Url vidéo: http://www.centraltv.fr/television-tunisienne/attessia-tv
* Content language/country: Tunisia

### Content access
Free access

merci

**Comment by joaopa00** [comment]
Le site offciel ne semble pas avoir de direct.
Sur youtube, le direct semble être ici https://www.youtube.com/watch?v=W7WoQzwonBk

Peux-tu donner le lien direct sur le site officiel du direct? Merci d'avance.

**Comment by joaopa00** [comment]
Pas de nouvelle. Je ferme. N'hésite pas à réouvrir si tu peux fournir les informations demandées.
