### ISSUE TITLE
Problème replay TF1

### ISSUE THREAD

**Issue by Laberi01** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#436]
### Describe the bug

Bonjour. Je n’arrive pas a lancer les replay des chaînes françaises, notamment TF1. J'ai Kodi Leila 18.6 et Catch-up TV version 0.2.30 beta05. J'ai essayé les version 29 et 28 et j'ai les mêmes problèmes. 

Lorsque je veux lancer un replay de TF1, j'ai un message d'erreur disant ERROR vidéo stream not available (avec la version beta05) et une erreur 404 not found avec les autres versions de Catch-Up. 

Est-ce qu'il existe une solution pour corriger ces bugs? 

### To Reproduce
1.installer Catch-Up version 0.2.30 beta05 sur Kodi Leila 18.6
2.Lancer un replay de TF1
3.
4.

### Expected behavior
Possibilité de lancer les replays

### Actuel behavior
Impossible de lancer les replays

### Your environment
 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: Leila 18.6
 - Catch-up TV & More version:0.2.30 beta05
 - Installation method:official source 

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by wwark** [comment]
Bonjour,

L'erreur 404 est présente pour la version 0.2.28 du plugin.
Elle a été corrigée en version 0.2.29 (+).
J'ai testé quelques replays et la lecture se passe bien pour moi.
Pourriez-vous tester de nouveau en 0.2.29 (+) et nous fournir le log en mode debug suite à votre test et le replay testé ?

Merci,
Wwark

**Comment by Laberi01** [comment]
Ok je m'y mets dans la journée et je vous reviens avec le log file.

**Comment by Laberi01** [comment]
[](https://paste.kodi.tv/wuxuqaluxo)

Voici mon log! Est-ce bien le format dont vous avez besoin?

**Comment by Laberi01** [comment]
https://paste.kodi.tv/wuxuqaluxo

**Comment by wwark** [comment]
Bonjour @Laberi01,

J'ai aussi testé "The Voice 2021, le Prime - Auditions à l'aveugle (Emission 1)" qui fonctionne chez moi.

Cependant chez vous on ne trouve aucun flux vidéo fonctionnant pour vous ...

2021-02-10 20:04:43.846 T:29238   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/mytf1/get_video_url/?_pickle_=80027d71012855075f7469746c655f7102583e00000054686520566f69636520323032312c206c65205072696d65202d204175646974696f6e7320c3a0206c2761766575676c652028456d697373696f6e2031295508766964656f5f6964710358080000003133373635343338752e]
2021-02-10 20:04:43.846 T:29238   DEBUG: Playlist Player: no more playable items... aborting playback

Pourriez-vous m'indiquer le retour de cette url dans le même réseau https://mediainfo.tf1.fr/mediainfocombo/13765438?context=MYTF1&pver=4008002&platform=web&os=linux&osVersion=unknown&topDomain=www.tf1.fr que votre Kodi instance ?

Merci,
Wwark

**Comment by Laberi01** [comment]
C'est super bizarre ça me donne une erreur de zone géographique alors que je n'ai jamais eu ce problème avant. Je n'ai jamais utilisé de VPN et ça fonctionnait. 

Pour reproduire le problème j'avais utilisé le lien de replay pour The Voice mais j'ai le même problème sur tous les replay TF1.
 ![image](https://user-images.githubusercontent.com/78818745/107638380-81b72380-6c3d-11eb-83c7-c5eb7e9a9166.png)

**Comment by wwark** [comment]
Nous avons changé d'API car la précédente ne fonctionnait plus.
La nouvelle semble plus restrictive.

Merci,
Wwark

**Comment by tom2411** [comment]
Le problème est réglé
