### ISSUE TITLE
Carré noir transparent sur France TV uniquement

### ISSUE THREAD

**Issue by bertrandsar** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#437]
### Describe the bug
Sur une TV android 4K, on aperçoit un léger rectangle transparent noir dans le quart en haut à gauche, mais uniquement sur la chaîne France 2. 
Est ce que je suis le seul ?

### To Reproduce
1. Module TV dans kodi (via Catch up)
2. Ouvrir France 2
3. Observer le coin en haut à gauche en fonction des couleurs on aperçoit un léger rectangle noir.

### Your environment
 - [X] Android TV 7.0
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version:18.9.0
 - Catch-up TV & More version: 0.2.30beta07

**Comment by wwark** [comment]
Bonjour,

Je 'n'ai pas le soucis. Est-ce que vous avez une capture d'écran ?
Le plugin ne peut rien faire à ce niveau. Il faudrait peut être en parlé sur le Forum de Kodi pour voir si ce soucis est visible pour d'autres personnes ayant votre télé 4K.
Le direct TV est en 720p donc il est possible que le scaler de votre TV n'arrive pas à gérer ce format fournie par France 2.

Merci,
Wwark

**Comment by bertrandsar** [comment]
voici un exemple de couleur où c’est particulièrement visible :

![3BCD585D-1AF5-486B-BD00-C8DB561BAB8C](https://user-images.githubusercontent.com/78982244/108135628-b7825f00-70b8-11eb-8801-edb7045ae507.jpeg)

**Comment by wwark** [comment]
C'est surement du à l'encodage de la vidéo.
Sur ce point le plugin n'intervient pas à ce niveau.
Il faudrait en parler sur le forum de Kodi pour voir si ça peut être arrangé par des réglages.

Merci,
Wwark
