### ISSUE TITLE
Arte

### ISSUE THREAD

**Issue by joaopa00** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#439]
Bonjour,
je n'ai pas vu la chaîne Arte de disponible. Serait-il possible de l'ajouter?
https://artelive-lh.akamaihd.net/i/artelive_fr@344805/master.m3u8

**Comment by wwark** [comment]
Bonjour @joaopa00,

Elle se trouve dans les chaînes internationales.

Merci,
Wwark

**Comment by joaopa00** [comment]
Merci,

mais ce n'est pas très pratique. Serait-il possible de dupliquer l'entrée dans  les chaînes françaises?

**Comment by wwark** [comment]
Cette chaîne est présente dans l'international car elles possèdent plusieurs langues.
Pour le live TV vous pouvez l'avoir dans la liste des chaines française en suivant cette procédure : https://catch-up-tv-and-more.github.io/fr/live_tv_installation/
Merci,
Wwark

**Comment by wwark** [comment]
Bonjour,

Je me permet de fermer ce ticket suite à notre réponse.
Merci,
Wwark
