### ISSUE TITLE
Lecture impossible sur TF1

### ISSUE THREAD

**Issue by lolo7791** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#44]
Bonjour,
Dabord merci pour ce plugin super pratique !
J'ai plusieurs erreurs de lecture sur des vidéos en replay par exemple TF1 Automoto.
Lorsqu'on lance la vidéo on a le logo de chargement puis plus rien et la vidéo ne se lance pas.
voici les logs. Ce sont des vidéos qui ne nécessitent pas d'avoir un compte MyTF1. J'ai la dernière version du plugin (0.1.8) et je suis sur un Rasberry Pi 3 avec OSMC.
Merci pour votre aide

> 18:37:32.748 T:1717564400   ERROR: COMXImageFile::ReadFile http://photos2.tf1.fr/172/97/automoto-une-incroyable-collection-automobile-9eaa45-0@2x.jpg m_image_size zero
18:37:33.449 T:1717564400   ERROR: Previous line repeats 1 times.
18:37:33.449 T:1717564400  NOTICE: LoadJpeg: unable to load http://photos2.tf1.fr/172/97/automoto-une-incroyable-collection-automobile-9eaa45-0@2x.jpg
18:37:40.085 T:1938813936  NOTICE: script.module.youtube.dl: youtube_dl core version: 2017.12.31
18:37:50.290 T:1959178240  NOTICE: VideoPlayer: Opening: https://www.tf1.fr/tf1/auto-moto/videos/jaguar-land-rover-classic-paradis-terre.html
18:37:50.290 T:1959178240 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
18:37:50.516 T:1451226096  NOTICE: Creating InputStream
18:37:52.880 T:1451226096  NOTICE: Creating Demuxer
18:37:53.867 T:1451226096   ERROR: Open - error probing input format, https://www.tf1.fr/tf1/auto-moto/videos/jaguar-land-rover-classic-paradis-terre.html
18:37:53.868 T:1451226096   ERROR: OpenDemuxStream - Error creating demuxer
18:37:53.868 T:1451226096  NOTICE: CVideoPlayer::OnExit()
18:37:53.869 T:1959178240   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.catchuptvandmore/?action=channel_entry&program_id=https%3A%2F%2Fwww.tf1.fr%2Ftf1%2Fauto-moto%2Fvideos%2Fjaguar-land-rover-classic-paradis-terre.html&next=play_r]
18:37:53.876 T:1959178240  NOTICE: CVideoPlayer::CloseFile()
18:37:53.876 T:1959178240  NOTICE: VideoPlayer: waiting for threads to exit
18:37:53.876 T:1959178240  NOTICE: VideoPlayer: finished waiting
18:37:53.876 T:1959178240  NOTICE: CVideoPlayer::CloseFile()
18:37:53.877 T:1959178240  NOTICE: VideoPlayer: waiting for threads to exit
18:37:53.877 T:1959178240  NOTICE: VideoPlayer: finished waiting

**Comment by wwark** [comment]
Bonjour,
Je pense que le problème "InputStream Adaptive" n'est pas activée.
Pouvez-vous aussi vérifier si l'option "InputStream Adaptive" de Kodi est bien activée, elle est souvent nécessaire avec  les dernières versions de Kodi? Il existe des tutoriels sur internet si besoin.

Merci pour votre retour,
Wwark

**Comment by lolo7791** [comment]
Bonjour,
dans mes add-on j'ai bien InputStream Adaptive il est activé.
J'ai fait de nouveaux tests et ca fonctionne à présent. Je n'ai rien changé si ce n'est un redémarrage du raspberry ...
Merci pour votre aide !!

**Comment by wwark** [comment]
Bonjour,
Il est possible que le site de TF1 n'était pas disponible aussi (si vous avez des erreurs, n'hésitez pas à tester le site pour voir si vous avez une erreur aussi)
Je ferme donc ce ticket.
Bon replay,
Wwark
