### ISSUE TITLE
Chaînes décalées

### ISSUE THREAD

**Issue by joaopa00** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#440]
Serait-il possible d'avoir les chaines en décalé (-1Heure, -2Heures, etc)

Pour les expatriés comme moi qui ont un grand décalage horaire avec la métropole, ce serait vraiment un gros plus.

Merci d'avance.

**Comment by wwark** [comment]
Bonjour,

Ce point n'est pas possible car les sites web des chaines ne le proposent pas et Kodi ne le supporte pas à ma connaissance.
Merci,
Wwark

**Comment by wwark** [comment]
Bonjour,

Je me permet de fermer ce ticket suite à notre réponse.
Merci,
Wwark
