### ISSUE TITLE
CUTV ejection de l'application lors de la sélection de RTL tv (chaine belge)

### ISSUE THREAD

**Issue by sisi69** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#441]
Bonjour,
après une réinstallation complète de Kodi et de CUTV (kodi 19 ne permettant pas faire fonctionner CUTV sur android tv) je rencontre le problème suivant:
lors de la sélection des chaines de RTLplay en live, je suis éjecté de Kodi et me retrouve sur la page d'acceuil de Android TV.
Ce souci n'est rencontré que avec RTL pas avec la RTBF qui fonctionne.
Le Catch up différé de RTL fonctionne aussi contrairement au live ce qui signifie que mon compte RTL est bien reconnu.

merci pour votre aide.

**Comment by wwark** [comment]
Bonjour @sisi69,
Il semblerait que le Kodi plante.
Pourriez-vous récupérer le log kodi en mode debug pour comprendre la cause. (https://wiki.mpdb.tv/go/Debug-Log) ?

Il faudrait vérifier aussi si vous n'avez pas des logs kodi avec crash présent dans le nom. Je ne sais pas où ils pourraient se situer mais si vous en voyez on pourrait avoir plus d'informations.

Est-ce que ce problème était présent avant la mise à jour Kodi 19 et le retour sur Kodi 18.9 ?

Merci,
Wwark

**Comment by sisi69** [comment]
Bonjour,
merci pour votre réaction super rapide. Entretemps j'ai résolu le problème en installant kodi v18.9 à la place du v18.0.
Peut être que le soucis venait de la version de kodi v18.0

désolé pour le dérangement et encore bravo et merci pour le support!
