### ISSUE TITLE
Catchup tv

### ISSUE THREAD

**Issue by eva19291989** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#442]
Catch-up TV ne veut plus s’installer sur Kodi version 19

**Comment by wwark** [comment]
Bonjour @eva19291989,

Nous avons ces deux tickets suivant le soucis avec Kodi 19.
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/363
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/425

Vous pouvez installer à la main le plugin dans Kodi 19 ou revenir à la version Kodi 18.9.
Nous travaillons sur le support de Kodi 19.

Je me permets de fermer ce ticket.
Merci,
