### ISSUE TITLE
Repo HS

### ISSUE THREAD

**Issue by Demgien** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#443]
Hello, le repo semble inaccessible, une mise à jour est en cours ?

**Comment by wwark** [comment]
Bonjour @Demgien,

Oui ça arrive de temps en temps qu'il soit inacessible.
Nous hébergeons ce repo.
ça devrait revenir bientôt.

Merci,
Wwark

**Comment by sy6sy2** [comment]
Hello, le repo est de nouveau disponible, désolé...

(il semblerait que ce soit lui le coupable de mes problèmes de débit ADSL à la maison, "trop" de personnes l'utilisent ce qui sature mon upload et ça fait écrouler mon download également... J'ai fixé un nombre max de connexion ainsi qu'une limite de vitesse pour le download, je pense que ça devrait le faire maintenant !)
