### ISSUE TITLE
[MyCanal] Replay KO

### ISSUE THREAD

**Issue by wwark** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#445]
Les replays non protégés par DRM ne sont plus lus.
Ce ticket suit ce sujet.

**Comment by elbartoolamuerte** [comment]
Bonjour! Y'a t il des progrès sur ce ticket

**Comment by wwark** [comment]
pour l'instant on n'a pas trouvé de solution ... désolé ...

**Comment by elbartoolamuerte** [comment]
> pour l'instant on n'a pas trouvé de solution ... désolé ...

Ok merci pour la réponse ! Et pas besoin d'être désolé, un grand merci pour le boulot !

**Comment by joaopa00** [comment]
Le replay en libre accès est disponible. Je ferme cette issue. Une autre est disponible pour le replay pour les personnes ayant souscrit un abonnement à MyCanal.
