### ISSUE TITLE
Error "web_utils" with 2.33 & 2.32 (Kodi Matrix)

### ISSUE THREAD

**Issue by sebsty** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#446]
Hi, i have update to Kodi Matrix and i have always the same error "web_utils" is not defined?
i've try catch up 2.32 & 2.33 (beta) it's the same....
I am under android and with and without VPN
In kodi Lea all is in orde.
Thanks
Sebsty

**Comment by sy6sy2** [comment]
Hi, can you provide a debug log please?
