### ISSUE TITLE
Catch-up-TV does not working in KODI 19 with Android 6.01

### ISSUE THREAD

**Issue by claudiosa** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#448]
Sylvain

Congratulations for your job to keep this addon active,
I am from Brazil and enjoy to watch french TV, and all the steps I followed from 
here: https://catch-up-tv-and-more.github.io/live_tv_installation/
but this time under KODI 19, I had a  problem.

### Describe the bug
A clear and concise description of what the bug is:
When installed the Catchup ... in this directory
Android: /sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons
the  m3u folder can not showed !!!!

plugin.video.catchuptvandmore/resources/m3u
It has not presented ...

### To Reproduce
I followed the steps from here
https://www.kulturechronik.fr/2017/10/28/regarder-les-cha%C3%AEnes-tv-fran%C3%A7aises-et-europ%C3%A9ennes-gratuitement-en-direct-et-en-replay-avec-kodi-et-l-addon-catch-up-tv-more/

### Expected behavior
A clear and concise description of what you expected to happen:
The directory m3u does not appear either the installation of Catch-up does not apper as an addon

### Actuel behavior
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [X ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 19
 - Catch-up TV & More version:  > 0.06
 - Installation method: manually based in https://catch-up-tv-and-more.github.io/installation/

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by wwark** [comment]
Hi @claudiosa,
What are the directories available in this directory "/sdcard/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/ if you check with a file browser ?

Thanks,

**Comment by sy6sy2** [comment]
Hi, thank you for your message but @wwark does most of the work here 😉

Concerning your issue, wwark is the best person to try because I don't have any Android device. 

The feature is not documented yet but you can also use the new IPTVManager integration for the Live TV feature. You will find this in the Live TV integration tab of the plugin settings.

**Comment by wwark** [comment]
Yes I forgot this new feature need to propose it next time !

**Comment by enigma131** [comment]
Is working on Android but my version is 10 . Need correction for programm infos, see #460

**Comment by wwark** [comment]
@enigma131 the issue here is different the person can't get the m3u8 file. no need to mix issues.
Thanks

**Comment by enigma131** [comment]
Oops yes i've deleted comment above

**Comment by wwark** [comment]
@claudiosa, we depreciated the use of m3u file.
The new solution is IPTVManager integration.

So we closed this ticket.
Thanks
