### ISSUE TITLE
Nrj12 programme en cours non disponible

### ISSUE THREAD

**Issue by durguy** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#449]
### Describe the 

Bonjour, 

J'ai ajouté mon compte nrj et malgré ça je n'ai pas accès au contenu.
Il y a un message qui dit : contenu indisponible sur cette application ou site web.

Comment y remédier svp?

![20210227_195806](https://user-images.githubusercontent.com/79764898/109397308-608d4d00-7936-11eb-8b4d-c6fcccf7c714.jpg)

### Expected behavior
A clear and concise description of what you expected to happen:

### Actuel behavior
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version:
 - Catch-up TV & More version:
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by wwark** [comment]
Bonsoir @durguy,

Oui certaines chaines comme NRJ12, Arte ne proposent pas tous les contenus de la télévision sur leur site Web souvent à cause des droits de diffusions qui peuvent être limité à de la diffusion sur la télé.

Pour ces cas, les chaines proposent de la pub sur leur site Web en attendant le prochain programme diffusable sur internet.

Le plugin CUTV&More récupère le flux vidéo comme sur un navigateur donc on reproduit le même cas.

Nous ne pouvons rien faire sur ce sujet.

Merci,
Wwark
