### ISSUE TITLE
Write access on FTP server (for Youtube-DL folder path)

### ISSUE THREAD

**Issue by Pirlouit78** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#45]
I have tried to set the download path to be a ftp on my local network. I can see some location but not my FTP.
I can add and see my FTP on the file manager in Kodi but not in the download path of catch up TV.

**Comment by wwark** [comment]
![screenshot at 2018-01-25 21-43-40](https://user-images.githubusercontent.com/469461/35411407-edcd1288-0218-11e8-9ba1-c42c52cb2eb1.png)

Hello,
Je viens de tester on peut remonter dans les choix "(=>) ...." et j'ai pu accéder à des partages samba.
Est-ce que le FTP apparait dans ce choix ?

Merci pour votre retour,
Wwark

**Comment by Pirlouit78** [comment]
Bonjour
Un certain nombre de choses apparaissent dont les stockages locaux ainsi que les partages samba. Mais pas le FTP local qui apparaît pourtant dans le gestionnaire de fichier.

**Comment by SylvainCecchetto** [comment]
Hey @Pirlouit78 !
J'arrive très certainement après la guerre mais pour que le FTP apparaisse ici ; est ce qu'il ne faut pas au préalable, en passant par les réglage de Kodi, ajouter le serveur FTP au "Sources".
Un peu comme quand on ajoute une source HTTP pour installer des addons via fichier zip ?

Je vais essayer de monter rapidement un ftp en local pour faire le test sinon

**Comment by SylvainCecchetto** [comment]
Ah mince... 
Bon ça m'intrigue, je ne sais pas si @wwark a testé de son coté ? Je vais essayer de reproduire le problème dès que possible.

**Comment by SylvainCecchetto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Problème FTP avec Youtube-DL](https://trello.com/c/0S9LXutl/94-probl%C3%A8me-ftp-avec-youtube-dl)

**Comment by SylvainCecchetto** [comment]
@Pirlouit78 
* Si tu es sous Mac/Windows, est ce que tu as bien les droits en écriture sur ce FTP (en se connectant au serveur FTP depuis un client comme FilleZilla est ce que tu peux créer un nouveau dossier sur ce serveur par exemple ?)
* Si tu es sous linux, est ce que l'user qui exécute Kodi a bien les droits en écriture sur ce FTP

Parce que je viens de faire un test entre mes deux PCs, si je lance le FTP avec seulement les droits en lecture alors il n'apparait pas dans les réglages de Catch-Up TV (normal car sinon quand Youtube-DL voudra enregistrer la vidéo téléchargée il ne pourra pas).
Par conte si j'active les droits en écriture je n'ai aucune problème pour pouvoir sélectionner mon serveur FTP

**Comment by Pirlouit78** [comment]
Ç est sous Android avec un petit serveur FTP sous raspberry. Avec un logiciel FTP sous Android, j arrive à créer des fichiers sur le FTP.

**Comment by SylvainCecchetto** [comment]
Ah ..

Je te propose un petit test pour savoir si le problème vient de nous (enfin de Catch-Up TV & More et/ou Youtube-DL) ou alors s'il vient de Kodi :

Si tu es sous Kodi 17 Krypton :
Réglages --> Gestionnaire de fichiers --> Ajouter une source --> parcourir --> Ajouter un emplacement réseau --> FTP (et ton adresse ip et login/mot de passe) --> Tu valides tout ça --> Tu donnes un nom à ta source --> Ok

Là normalement ta source soit apparaitre à gauche, tu rentres dedans. Là tu dois voir les fichiers/dossiers de ton serveur FTP normalement.
Tu te mets sur n'importe quel fichier/dossier, tu appuis sur la touche "c" ou alors clic droit si tu as une souris ou alors context menu sur une télécommande.
Si tu ne vois pas "Créer un nouveau dossier" alors c'est Kodi n'est pas en mesure d'écrire sur ton FTP. Et à ce moment là le problème ne vient pas du plugin (enfin je ne pense pas xD)

**Comment by Pirlouit78** [comment]
Sur la box Android avec kodi, le FTP n apparaît pas dans catchup. Sur le téléphone non plus. Sous windows non plus.
Je viens d essayer sur mon tél avec un logiciel FTP tierce et je peux créer un fichier sur le FTP.
Je fais ton test plus tard. Vie familiale oblige...
J avais cr

**Comment by SylvainCecchetto** [comment]
Bizarre que tu n'es pas accès à ton serveur FTP depuis windows avec une simple client FTP :-/

Pas de problème, bonne soirée ;-)

**Comment by Pirlouit78** [comment]
Non ç est sous windows avec kodi. J essaierais plus tard avec fillezila.

Mais comme je disais, avec FTP express sous Android. Je peux créer un fichier sur le FTP.

**Comment by Pirlouit78** [comment]
Bon j' ai trouvé 5 minutes...
Sous windows avec fillezila je peux créer fichiers et dossiers.

**Comment by SylvainCecchetto** [comment]
Du coup le prochain suspect c'est Kodi :-P . Reste à voir si Kodi te laisse créer un nouveau dossier sur ton FTP depuis le "Gestionnaire de fichiers"

**Comment by Pirlouit78** [comment]
Via le gestionnaire de fichiers de Kodi sous Android ou windows, en appuyant sur la touche du clavier, je n' ai pas "créer un dossier".
Pourtant que ce soit sous Android ou windows, je peux créer un fichier sur le FTP. Je ne comprends pas...

**Comment by Pirlouit78** [comment]
Ha je ne suis pas fou. 😀
Il me semble aussi que cela vienne de Kodi.

Ç est une bonne idée. Mais je ne suis pas certain que cela soit faisable sous Android.

**Comment by SylvainCecchetto** [comment]
En cherchant un peu sur le forum de Kodi je suis tombé sur ça :

https://forum.kodi.tv/showthread.php?tid=154506&highlight=FTP+write
https://forum.kodi.tv/showthread.php?tid=251702&highlight=FTP+write+access

Il semblerait bien que ce soit une limitation de Kodi effectivement. Je vais faire un up sur ces deux sujets, à tout hasard un dev de Kodi répondra peut être ...

**Comment by Pirlouit78** [comment]
Hum si ils sont au courant de la chose,  ils  ont peut être l intention de laisser comme ça. 
Je pense que je peux toujours m asseoir sur la possibilité d enregistrer sur mon FTP. J en ai bien peur. ;)

**Comment by SylvainCecchetto** [comment]
Oui c'est fort possible :-/
Si tu en as la possibilité peut être que tu peux contourner le problème en changeant de protocol ? SFTP, SMB, etc ... Par contre il faut voir si le problème n'est pas le même ; je n'ai pas fait de test de ce coté là.

**Comment by Pirlouit78** [comment]
Oui je pense que le problème est contournable. Ma box  peut partager via samba un port USB et je le vois dans catchup. J imagine que du coup il doit être possible d écrire dessus si je branche quelque chose...

**Comment by SylvainCecchetto** [comment]
Une personne de la team Kodi a répondu. Si je comprends bien son message ce n'est pas implémenté et c'est à nous de le faire :-P 

https://forum.kodi.tv/showthread.php?tid=154506&pid=2715830#pid2715830

**Comment by Pirlouit78** [comment]
Bah j ai l impression. ;)
Le message d origine date de 2013... :P

**Comment by SylvainCecchetto** [comment]
Oui effectivement ! Donc ça n'a pas l'air d'être dans leurs priorités :-P

A moins que tu sois motivé à mettre les mains dans le code source de Kodi je pense que tu auras plus vite fait de switcher vers un protocole de partage que Kodi supporte en lecture/écriture xD

Je me permets de fermer ce ticket étant donné qu'il n'est pas lié au plugin. A réouvrir si besoin.

Si d'autres personnes sont concernées par ce problème ; le truc à tester sous linux serait de monter le FTP coté OS afin que Kodi voit le point de montage comme un dossier local ce qui devrait résoudre le problème d'écriture (non testé). Par contre pour Android et Windows .... aucune idée !

Merci d'avoir soulevé le problème @Pirlouit78 ;-)

**Comment by Pirlouit78** [comment]
De rien! ;)
