### ISSUE TITLE
M6 STREAMING REPLAY 

### ISSUE THREAD

**Issue by lecorossol** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#451]
### description of the bug
Bonjour, 

Arrivez vous à récupérer le flux 6play, je cherche ce matin à streamer un replay de m6 impossible. 

### Attente 
Le loader de kodi se ferme brutalement et rien ne se passe. 

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ x] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: Leia
 - Catch-up TV & More version: 0.2.32
 - raspberry 3

**Comment by wwark** [comment]
Bonjour @lecorossol,

SI vous êtes en Kodi 19 il y a ce ticket : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/447
Si vous êtes en Kodi 18. Il faudrait le log en mode debug suite à la lecture d'un replay pour comprendre le soucis.

Merci,
Wwark

**Comment by Psychoses** [comment]
I drop a direct link to the code fix here. Maybe this can help some people for this temp issue on urlquick.py.

https://github.com/willforde/urlquick/commit/c3fc0e78be7b08ba18ba36d272fcf13af1f5a6c9#diff-50a1cdbcadfcc17aa93c8df3942f6d789713d854155bca8a7fd7aeb4780a61ce

**Comment by lecorossol** [comment]
> I drop a direct link to the code fix here. Maybe this can help some people for this temp issue on urlquick.py.
> 
> https://github.com/willforde/urlquick/commit/c3fc0e78be7b08ba18ba36d272fcf13af1f5a6c9#diff-50a1cdbcadfcc17aa93c8df3942f6d789713d854155bca8a7fd7aeb4780a61ce

Thank you, but I won't execute python script. I'll wait the official fix.

**Comment by wwark** [comment]
I will close this ticket because issue follow by the other ticket.
I change the title and add the channels impacted.
