### ISSUE TITLE
Ajout de Tahiti Nui télévision

### ISSUE THREAD

**Issue by joaopa00** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#452]
Bonjour,

est-il possible d'ajouter la chaine polynésienne TNTV a Catchuptvmore?
Merci d'avance

Lien de la chaine: https://www.tntv.pf/direct/

**Comment by joaopa00** [comment]
Bonjour,

c'est impossible à ajouter?

**Comment by wwark** [comment]
Bonjour @joaopa00,
Pour l'instant on attend de stabiliser le plugin avant d'ajouter de nouveaux contenus.

Merci,

**Comment by joaopa00** [comment]
Pas de nouvelles?

**Comment by ppiotr3k** [comment]
@joaopa00  I believe this has been addressed in https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/e0a461627adafad90118757360a34b618e242326 and be part of next minor release, right? :slightly_smiling_face:

**Comment by joaopa00** [comment]
Good catch. I forgot this issue. Thanks for the remainder.
I close this issue.
