### ISSUE TITLE
France TV Live TV (France 2, France 3, ..) - KO

### ISSUE THREAD

**Issue by wwark** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#453]
Hello,
Les Live TV de France TV sont KO.
Nous regardons.
Merci,

**Comment by wwark** [comment]
Il y a une correction sur la gestion du cache dans la prochaine version du FrameWork CodeQuick qui corrige ce point.
La version 1.0.2 a été proposé à Kodi hier.
La correction devrait être présente rapidement.

**Comment by enigma131** [comment]
Pas toutes les France TV sont HS. France 3 , 4 et 5 sont OK, France 2 et France Info KO . Testé sur Kodi 18.9 Linux

**Comment by enigma131** [comment]
Pas toutes les France TV sont HS. France 3 , 4 et 5 sont OK, France 2 et France Info KO . Testé sur Kodi 18.9 Linux, Catchup TV 0.2.33 beta1 , codequick 0.9.13
A noter que sour Window 10 pro , avec les mêmes versions, toutes les France TV sont OK, bizarre ..

**Comment by wwark** [comment]
Depuis quelques jours, les Live TV de France TV sont valides que quelques minutes.
Au niveau du code du plugin on force pour ne pas utiliser le cache quand on requête le flux vidéo.
Si on ne force pas, il y a du cache pour accélerer la vitesse des traitements mais si le flux est valide que quelques minutes on peut récupérer un vieux flux vidéo et avoir un HTTP 403.

Il y a ce fix au niveau de codequick sur la gestion du cache : "https://github.com/willforde/urlquick/commit/c9709605aa2dca9b564707b24d3bb2e7ee9a603c" 

Merci,
Marc.

**Comment by enigma131** [comment]
Ok pigé. Au fait on ne voit toujours pas l'upgrade de codequick venir (automatiquement) pour Kodi 19 ?

**Comment by wwark** [comment]
Il doit refaire une nouvelle version car on s'est rendu compte que codequick n'était pas compatible Kodi 17.
On doit attendre un petit peu plus de temps.

Merci,
Wwark

**Comment by enigma131** [comment]
Je viens de faire des tests d'endurance avec LM 20.1 , Kodi 19 + Catchup tv. Je confirme que la version patchée de codequick prise de son github est la seule qui fonctionne pour l'instant pour France  TV.

**Comment by wwark** [comment]
CodeQuick 1.0.2 a été ajouté sur le repo Kodi 19 (Matrix)
https://github.com/xbmc/repo-scripts/pull/1902

La version pour Kodi 18 Leia est toujours en cours de review.

**Comment by enigma131** [comment]
Fonctionne sous windows 10 + Kodi 19, mais nouveau bug pour w10 , pas d'infos programme, voir l'autre fil #460

**Comment by wwark** [comment]
Merci @enigma131
On va attendre la mise à jour de CodeQuick sur Kodi 18 et on fermera ce ticket.

**Comment by wwark** [comment]
CodeQuick 1.0.2 est disponible maintenant sur Kodi 18.
On fermera ce ticket début de semaine prochaine le temps que tout le monde puisse récupérer cette nouvelle version.

**Comment by Grouickman** [comment]
Hello,

Je viens de faire l'update sur un Kodi 18.9 (osmc) sur raspberry Pi3b, et je n'arrive toujours pas à avoir les flux france TV (testé sur F2 et F3)

Curieusement si je retourne dans les add-ons je peux refaire (et re-re-...-re-re-refaire) l'update du plugin en 0.2.32 et à chaque fois il me dit que le pugin est correctement mis à jour... et à chaque fois il va me re-proposer la MAJ en 0.2.32

**Comment by enigma131** [comment]
Pour vérifier les versions de plugins (surtout sur Kodi 19 où c'est visiblement plus compliqué) je passe par système, extensions, gérer les dépendances

**Comment by theoden11** [comment]
Bonsoir. 
Mise à jour ce soir de codequick en version 1.0.2 suite au problème que je vous ai remonté il y a quelques jours avec la 1.0.1. Les chaînes TV du groupe M6 posent cependant toujours le même problème sur mon raspberry pi avec OSMC et la nouvelle version de codequick. Le retour à la version 0.9.14 résout immédiatement le souci.

**Comment by wwark** [comment]
Il est important de ne pas mélanger les problèmes.
Ici on ne doit parler que du soucis des Live TV France TV.
@theoden11, est-ce que France TV fonctionne pour vous avec la 1.0.2 ?

Merci,

**Comment by theoden11** [comment]
> Il est important de ne pas mélanger les problèmes.
> Ici on ne doit parler que du soucis des Live TV France TV.
> @theoden11, est-ce que France TV fonctionne pour vous avec la version CodeQuick 1.0.2 ?
> 
> Merci,

Bonjour. Pardon si je me suis trompé de post; vous avez fermé l'autre jour celui que j'avais ouvert et fusionné avec un autre dont je ne me souviens plus. Pour France TV j'avoue ne pas savoir, je testerai plus tard, là ça ne m'est pas possible. Mais ça ne retire en rien ce que j'ai écrit plus haut.

**Comment by wwark** [comment]
Merci !
C'est ce ticket : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/447
Il faudrait poster le log en mode debug de Kodi dans ce ticket comme ça on aura tous les plugins utililsés de votre côté et l'erreur.

**Comment by Grouickman** [comment]
Hello,

Kodi 18.9 sur Raspberry PI3b

Avec la 0.2.32 et CodeQuick 1.0.2 France TV fonctionne (et, ce n'est pas le sujet, mais M6 également).

Par contre si j'installe le plugin IPTV proposé dans la config de CatchupTv&More, effectivement France TV ne fonctionne plus.

**Comment by wwark** [comment]
@Grouickman est-ce que ça impact d'autres Lives ou juste France2, France 3 ?
Il faudrait nous transmettre les logs en mode debug.

**Comment by Grouickman** [comment]
> @Grouickman est-ce que ça impact d'autres Lives ou juste France2, France 3 ?
> Il faudrait nous transmettre les logs en mode debug.
> Il faut aussi penser à forcer le refresh des chaines dans l'option du plugin.
> 
> Si vos chaînes n’apparaissent toujours pas dans la section “TV” de Kodi vous pouvez effectuer les étapes suivantes dans les réglages d’IPTV Manager :
> 
> ```
> “IPTV Simple” –> “Configure IPTV Simple automatically…”
> “Channels” –> “Refresh channels and guide now…”
> ```

J'ai installé IPTV et fais la mise à jour des chaines.

Alors voila ce que ca donne : https://pastebin.com/win7H5GC
(Il n'y a que le log entre le moment ou je lance la lecture et le moment ou je l'arrête).

Le comportement est que, quand on lance la lecture, l'écran dévient bleu/turquoise avec en bas le descriptif du programme en cours, une barre de lecture et une vignette, mais l'image n'arrive jamais.


Par contre, si  je reviens à l'écran précédent (sélection des chaines) avec la touche retour arrière de la télécommande (Kore) là je vois en arrière plan que le flux a bien démarré et si je switch sur France 3 la lecture se lance normalement et si je reviens sur France 2 enfin ca marche.

je ne rencontre pas le soucis sur d'autres chaines (TF1 ou M6 par exemple).

**Comment by sy6sy2** [comment]
Hello, pour moi ton problème semble provenir de Kodi et pas du plugin, d'autant plus si France 2 et France 3 fonctionnent bien depuis la section "Live TV" du plugin.

J'ai aussi des fois ce "problème" de vidéo qui n'apparait pas, par contre il me semble que j'ai le son depuis le début et qu'au bout de quelques secondes la vidéo arrive.

**Comment by enigma131** [comment]
Ou j'ai ça aussi des fois sur les France TV, je fais 1 fois échap et l'image apparait tout de uites

**Comment by wwark** [comment]
Nouvelle version qui corrige ce point.
