### ISSUE TITLE
Problème d'installation de Catchup sur Kodi19/ShieldTV (corrigé) - gestion du @ dans le clavier Virtuel de Kodi (A corriger)

### ISSUE THREAD

**Issue by kaioh31** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#454]
Bonjour,

Ci-joint la description de mon problème.

### Describe the bug
Impossible d'installer les repository (étape 2 du guide https://catch-up-tv-and-more.github.io/installation/)

### To Reproduce
Dérouler le guide pas à pas jusqu'au moment où l'on choisi le repository à installer.

### Expected behavior
L'affichage des quatre dernières versions :
- Jarvis
- Krypton
- Leia
- Matrix

### Actuel behavior
Seules les versions Jarvis et Krypton sont disponibles. C'est d'ailleurs le cas si l'on se rend à l'url https://catch-up-tv-and-more.github.io/repo/

Merci beaucoup, Catchup me manque énormément :)

**Comment by wwark** [comment]
Bonjour,

dans le site web, vous avez ce message:

Sélectionnez la version de Kodi la plus proche de la votre (si vous utilisez Kodi Krypton (17), Leia (18) ou Matrix (19) choisissez le dossier Krypton_(Kodi_17)).
Le dossier Kodi 17 est à selectionner pour Kodi 19.

Merci,
Wwark

**Comment by sy6sy2** [comment]
Hello, ma faute j'ai pas mis à jour l'impression d'écran...
Je vais essayer de le faire pour éviter les confusions comme celle-ci.

**Comment by kaioh31** [comment]
Je suis désolé, j’avais fait l’installation chez un pote il y a quelques semaines et ils étaient toujours présents. Je ne me suis pas posé la question...
Par contre j’ai un problème de dépendance non satisfaite avec le paquet xbmc.python 2.26.0.
Je vais check si d’autres ont eu le problème. 
Merci pour votre réponse rapide et bonne soirée !

**Comment by sy6sy2** [comment]
No problème :wink:

Hum pour la dépendance c'est un autre problème...
C'est le repo qui ne veut pas s'installer ou bien le plugin ?

Si possible merci de fournir un debug log ;-)

**Comment by kaioh31** [comment]
Bonsoir,

Je viens de réussir. Pour une raison obscure les différentes dépendances ne se mettaient pas à jour automatiquement.

A chaque tentative d'installation de Catchup, il y avait un échec sur une dépendance : le paquet concerné apparaissait dans la listes des mises à jour possible (toujours des paquets python).

Après 5 à 6 aller/retour Catchup s'est installé.

J'ai une dernière petite question, comment je renseigne le caractère "@" sur nvidia shield dans les login de comptes pour les replay ?

Voulez-vous que j'ouvre un nouveau ticket sur le sujet ?

Je vous remercie encore pour votre aide.

Bonne soirée.

**Comment by wwark** [comment]
Cool !

Pour le caractère "@", tu peux surement connecter un clavier usb sur la shield TV et tu devrais avoir accès à ce caractère.
Sinon il faudrait naviguer dans les menus du keyboard de la shield (lettre, nombres et caractères spéciaux pour trouver le @) 

Merci,
Wwark

**Comment by kaioh31** [comment]
Je n'avais pas pensé à connecter un clavier sur la shield, bonne idée je vais essayer !
Après il me semble vraiment que ce n'est pas dépendant du menu du clavier virtuel de la shield : le "@" est présent dans d'autres zone de saisie de kodi par exemple. J'ai vraiment l'impression que c'est la text box du login dans Catchup qui n'est pas correctement typée, du coup le clavier virtuel qui apparait n'est pas adapté.

Bonne journé !

**Comment by wwark** [comment]
Ok on va regardé ce point.
On laisse le ticket ouvert pour ce cas.
Merci !

**Comment by Cedeline** [comment]
Bonjour,
Je me permets de reprendre ce post. Je souhaite, sur Catch-Up, saisir les infos nécessaires via une tabelle Android pour activer le 6play et autres mais les caractères spéciaux ne sont pas présents sur le clavier Shield ( @,*,%,#,...). 
Auriez vous une solutions, svp?

**Comment by joaopa00** [comment]
Un commentaire précédent conseille de brancher un clavier usb. Ou sinon écrire au développeurs de Shield d'ajouter la fonctionnalité des caractère spéciaux. Ce n'est pas un problème de Catchptvmore. Il n'y a pas grand-chose que l'on peut faire. Désolé Je ferme ce rapport de bug.

**Comment by darodi** [comment]
le clavier virtuel de kodi comprend le caractère @ quand on appuie sur shift
