### ISSUE TITLE
6PLAY KO

### ISSUE THREAD

**Issue by osmoze06** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#457]
Plus de lancement de replay 6PLAY depuis la nouvelle installation KODI MATRIX (propre) avec la dernière version de CATCH-UP TV.
Les vidéos ne se lancent pas.

Android - Clé XIOAMI MI STICK

**Comment by wwark** [comment]
Hello @osmoze06,
Ce problème est suivi ici : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/447

Merci,
Wwark !
