### ISSUE TITLE
Nihon television News24 cassé

### ISSUE THREAD

**Issue by joaopa00** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#459]
Bonjour,

 Lorsque je lance le live de Nihon Telebi News24 avec Kodi 19 Matrix (androidtv), je reçois le message
<<Type error decoding str is not supported>>

Avec Kodi 18 Leia sous Linux, je n'ai pas ce problème.

Merci d'avance.

**Comment by wwark** [comment]
Bonjour,

Je ne reproduis pas.
Il faudrait nous transmettre les logs de Kodi en mode debug.

Merci,
Wwark

**Comment by joaopa00** [comment]
[toto.txt](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/6093020/toto.txt)
Comme demandé.

Merci encore pour le boulot effectué!!

**Comment by joaopa00** [comment]
[toto.txt](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/6093582/toto.txt)
Avec l'option debug activée dans Kodi.

**Comment by wwark** [comment]
@joaopa00 merci pour le log.
De mon côté, je ne reproduis pas même avec les même lib et sous android aussi.

Voici un fix qui pourrait aider à votre cas, il faudrait tester la dernière version beta 0.2.33~beta02.

Merci,
Wwark

**Comment by joaopa00** [comment]
Merci pour la tentative de correction, malheureusement, elle n'a pas corrigée le problème.

**Comment by joaopa00** [comment]
Problème résolu. Même si c'est décevant puisque je n'ai pas réussi à trouver la cause du problème. J'ai simplement désinstallé Kodi et réinstaller. Et tout fonctionne correctement.

**Comment by wwark** [comment]
C'était surement une lib mal mise à jour ou autre chose ...
Je ferme le ticket.
Merci !
