### ISSUE TITLE
No programm infos for Kodi 19 on Windows and Android

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#460]
### Describe the bug
No programm info for Kodi 19 on Windows, on Linux is ok

### To Reproduce
1.Download Kodi 19 for Windows from web site 
2.Install it, and let it update installed Kodi 18.9
3.Wait it convert all plugins
4.Shut down Kodi, resart it an play Catchup TV and more

### Expected behavior
Have programm info like for Windows Kodi 18.9 or linux Kodi 19

### Actuel behavior
Tell us what happens instead:
No programm infos

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x ] Windows
 - [ ] Other

 - Operating system version/name: Windows 10 Home 20H2
 - Kodi version: 19.0
 - Catch-up TV & More version: 0.2.33 beta1
 - Installation method: via exe

**Comment by sy6sy2** [comment]
Hi enigma,
Are talking about the Live TV integration or about the Live TV folder of the plug-in?

**Comment by enigma131** [comment]
I don't use Live TV integration because it's reserved here for Pvr plugins when server is on. So it's concerning Live tv mode of the plugin itself of course.

**Comment by enigma131** [comment]
Same error on android, 'erreur lors de l'obention du guide des programmes' as message. Updade migration was automatic on it

**Comment by sy6sy2** [comment]
Hi, sorry for the delay. I will try to reproduce the issue on macOS today.

**Comment by sy6sy2** [comment]
Can not reproduce on macOS.
I will try on Windows.

**Comment by sy6sy2** [comment]
This commit https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/28a53110832fda205813fde3a3d851b489de6fa0 should fix your issue on Windows devices.
Can you try 0.2.33~beta04 when it will be available on the repo please?

**Comment by enigma131** [comment]
I've try to upgrade but no beta 04 available  ... how to get it ?

**Comment by sy6sy2** [comment]
You need to fetch Kodi repos.

Do to add-ons --> My addons --> Add-on repository --> right click on CUTV&M repo and choose Checks for update.
Now go to add-ons --> My addons --> Video add-on --> CUTV&M --> Versions --> Choose beta4

**Comment by enigma131** [comment]
This way i got beta 5 but it works quasi at all.
C8 is missing, perhaps source problem ?
Works also same on android 10 . Welldone !
I can't test other channels as French ones, if someone can test them too ...

**Comment by sy6sy2** [comment]
Yes you have beta5 because wwark did another update after mine ;-)

Don't know for C8, that's another issue.
My fix apply on all countries so no need to test for other countries.
Thank you for submitting this issue!
