### ISSUE TITLE
CLUB RTL - HTTP 403 en récupérant la licence DRM pour les contenus présents dans la section Sport

### ISSUE THREAD

**Issue by wwark** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#461]
### Describe the bug
HTTP 403 en récupérant la licence DRM pour les contenus présents dans la section Sport

### To Reproduce
1. RTL CLUB
2. Section Sport
3. Lire une video
4.

### Expected behavior
A clear and concise description of what you expected to happen:
Lecture la vidéo

### Actuel behavior
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: Linux / Android
 - Kodi version: Kodi 18 et 19
 - Catch-up TV & More version: 0.2.33~beta02
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):
2021-03-06 09:03:16.947 T:139636290610944   ERROR: CCurlFile::Open failed with code 403 for https://lic.drmtoday.com/license-proxy-widevine/cenc/:
                                            <!doctype html><html lang="en"><head><title>HTTP Status 403 – Forbidden</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 403 – Forbidden</h1></body></html>

**Comment by joaopa00** [comment]
Est-ce encore un problème avec la version de développement? Il y a eu du travail de fait pour ce fournisseur de contenu

**Comment by darodi** [comment]
semble ok pour moi

- Belgium
- RTLplay
- CLUB RTL
- RTL sport
- Champions league
- les matches

![Clipboard01s](https://user-images.githubusercontent.com/4682830/155836187-b76906c9-d25e-4b5d-91a1-54f29dfcbe7b.png)
![Clipboard02s](https://user-images.githubusercontent.com/4682830/155836188-2da74fe8-4966-43d0-a6ad-6880989ff3a5.png)

**Comment by joaopa00** [comment]
Super!! Je ferme ce rapport de bug. S'il reste des problèmes, merci d'ouvrir un nouveau rapport et d'y attacher le log.
