### ISSUE TITLE
"Lucky Jack" : ERROR: [Catch-up-TV-&-More.support] list index out of range

### ISSUE THREAD

**Issue by Grouickman** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#465]
### Describe the bug
Lancer la lecture (live-tv) de "Lucky Jack" génère une erreur "Cette sélection a généré une erreur inattendue....." 

### To Reproduce
1. Live TV
2. France
3. "Lucky jack"

### Your environment
 Raspberry-Pi

 - Operating system version/name: OSMC 2020.11-1
 - Kodi version: 18.9
 - Catch-up TV & More version: 0.2.32
 - Installation method: koddi add-on installe

### Debug log
Log en debug disponible ici :
https://nopaste.ml/#XQAAAQCiHgAAAAAAAAAZDAKSNIQ/MlgeD1MvlKpsFMJzCCj0e15rNuC61o4ilUjdR/P1GiDUgACJ5b59eBYE5NC8Tztuhce3n97HfRxTTjlyJhfWbwsyJRgotSX/4b+axrNQQi0GD1NHaFY1GX7P19WlUmx0FTzF3/v83mzWkx65uVeC3yLoSnW8CXbl3XbduTS62AAQFJjIvVOg2ycjGqjAaxD5lzn5gfXUaHjYBUnGHEH8VjcAxZE2YY3tGGHpGNEx6s/ZK2ziErlFjXY7Ve6mI+sHMhVtzPMSEB8cbLO+wK8nzM5W+VY6PpbmXrOo9UwtWFhOVxPDVP1zrOukcs6OHskyxuWCBOOpbQy6l2KuViVaBqydKuSNvP9ctXq8DSxHVRBDYdNuM2ZBob0nLRxDL7s0jrLnXXrmIteKfggGta7FRnxeOygaeFxRrOIXbg5a646GDwJ4DOAmnUsy52WTbNO/PhvQCRLw4n12a+lxTL0xjXN1AcRjBHwuD8MhScNRKz03i3tyaAVNjzEAdILePZEengISDBK9b2kXVnn2I9e+JXH2M1RIWMRv1Xqjc6sPQuiad9PiMYr4JAJlrCFA3w1agj4C+MUZTpj8sePTS4a+HlDNHanwdkqmTOCvljOAY6FftJjt0rQIEYBkYFzcrnk7yREHQBdw5r1Z7ws0dZpQAySit+V9E89N1CDSZgsEFRppRTGMShtW4UH3MMoqckwfjsSIlDy3FaeGrvuNDFwq7plCnjLmUUjAYBRyfJ/0X1l/ukQSyAzji55M7rXrHSzrykVsVlQyWGdzKko9AD16uX0gUgWZWGJ6OPC/NhKvlB9CIFEaraggBIE1WlWRhC65EBLqDw9KcWkVWlK2sGYMgj1YH90kgjF51GDroyxqiSOVgQIP4FigkVfZakXhd/nev7Wok27gruWT0YeCoT8az2Omh9BTcfCXEY0Suw5ml0SCrevkDhIOe5jBNUDTyV15+I3Srbu0AIITFJu/0ZSfXiwxmpvv/f4XZrhvCRkwdD9xtympxo/FqodIL9L+F7/tcr+botrgvn1sMFXUIq1gy9XJFZLblwSZuZBJtUCQlI98RD7YJlJUyzj/LhgoEvEvYFAEVyTfICPSFK9PFHCr2AkP1TSdfD9H0bq+1HKuoQNLFqkm1fAPfUXk8s5iCtLtfytDtK4KEsosSUh+mzUMdNv7ejpn/Yt3Mrc7Go3Oc+1GznglMV4zDtJ6Dv8nwzOdQK06GYAEc2qUjvfY/HmJQNus8k9n0ycxiKjFJVN56FSCPgXG4KEgkuZKY+/w9SL9ca1nA4BWqf7NTHk9B5MawdI0pAgQT5sqL3AeqjhWpdYz4S8xH+UNyQ/C5dSYzugo1EYpIi4jv1NASIf2ejMAmJ2FqCB2rkhZ9KLZ27a5EpDwcVYhiq6nMFq261rKQGsRibXdnsIF9akAcPN9NbBix+/zKWsD4sH7gvwu1/jHFfNgk/sylSYgx2qXRm4Dcozy5S3UqDMOuOXXALjdFmliV3iIETCabsssXHuorW28sw5E6rIwNMZBQgUZN8MUDdLXoCsfM2ed8gTaPFnYa/nUtNB0dRwVzw2IZXYDEvXQgzeT3qFh+FWb8Hw21uxMnvOeFNPzIuF/mYPjLoFXBsdPQhyx4Q/NQzScYXCZQXrnDjCum0nbYQs9JV1bmelR6LRZvJr7rB2FKqjH4PBXUbYbJH4Z0UI/Tgzexpq78lscNkm0STnoj4Phbd4qJHehtNXxA4hZ4OnRyPT1NUoo6R7odnvCObivJQW5jUMYe251VLJRN3fqSdhYCyw3w10dLdVCAyWif0aLl9lccv+0qdvwUquUmQufJ9/dDp3z/bcUxGw2y1BL0EqSowOZIDwhFpFgzO+AFo47uqWSL+5holgcevAT+Cd+QLlgO8B4+LFbyJHlYKP3fgek5Zw90U6yC6Kqx0mJrANW3T+9x/EhO56IB8EbQY08xJdWFtcGjusHsZkxW3MIBB7eR0PQZiOu/C6m7VjDO4s8RbBl08VieuFACUcyFBLJLUxsxeIegpT3fAUbbpaXkxPdyvxVvlwizXTB7gJhXFVV7HR2ZVf/sI9dLM1Kgy9v8qHE32CPQYOSBNx/CKfJuaHeC9dqRfBcnbK6XCZcp5ZEuDz5jeBltQKW7nZJL/jvj2UWTtjrgHmzY1QDqFoGClAro3D0p19qloIYA6d8GmRQTVsoKCRzyh6eOt8PfwM0oqOEIStwalAkXDj83jVOABR5DHv2LBTMsc5QOXHwKY+DQpmopAVBKAZvlIcZolN8G2gWf5XMmqsN7H0D8F/YWnJGqWUX2v4ETwyuq3gZgTcxRaxTDcWvpE2Trj1zkw5srdt0p4QqoGQ2ONY8AaCpNVtHa8IXlA9rlmu10AAZalO6AJsV5cz/+l4N7A==

extrait du log :

`2021-03-08 21:39:20.303 T:1793061088   ERROR: [Catch-up-TV-&-More.support] list index out of range
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                redirect = parent_ins(route, arg_params, self.callback_params)
                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/resolver.py", line 67, in __call__
                                                results = super(Resolver, self).__call__(route, args, kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                return route.function(self, *args, **kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/abweb.py", line 124, in get_live_url
                                                resp3.text)[0]
                                            IndexError: list index out of range`

**Comment by wwark** [comment]
Yes Lucky Jack change owner lately need some fixes

**Comment by chamchenko** [comment]
The changes now concerns AB3 and AB Xplore

**Comment by wwark** [comment]
@chamchenko thank you to report this issue - I'm not checking it for the moment if I reproduce it.
But I think this report needs to be done on a dedicated issue because AB3 and AB Xplore are still part of AB channels that is not the case for Lucky Jack so I think the issue might be different. Thanks !

**Comment by chamchenko** [comment]
lucky jack is still part of ab sat they have just changed the domain name, and implemented a new api
lucky jack can be accessed from 
https://www.bistvonline.com/ - https://app.auth.digital.abweb.com/signin
it using the same credential that were used on https://abweb.com (which now is redirecting to https://www.bistvonline.com)

**Comment by wwark** [comment]
I'm checking again and I didn't find lucky jack TV on https://www.bistvonline.com/ and I don't find Lucky TV on the list of Live TV.
Do you have some screenshots to see how to find it ? Have an account with paid channels ? I have an account without any paid channel on my side.

 in this website http://www.luckyjack.tv/offre-live.aspx it proposed to download an application.
Thanks,

**Comment by Grouickman** [comment]
It is supposed to be free (no paid account needed, just a standard account) but it does not work ("Une erreur est survenue, veuillez nous excuser."). 
I managed to watch some live some days ago, from abweb, so the change is recent.
And bistvonline does not list "lucky jack" in their channels.

In fact i'm not sure it's still alive, or it might just be a temporary issue related to the domain change.

**Comment by chamchenko** [comment]
I Was just checking and you are right @wwark  lucky jack is only available with paid account on bistvonline.

**Comment by wwark** [comment]
ok maybe with the application it will not work also. I will test it.
We may have to remove this channel until it will be available freely again.

**Comment by wwark** [comment]
My test is not ok for luckyjack. The channel is removed until it was available freely.
