### ISSUE TITLE
IPTV Simple Client : DATABASE ERROR

### ISSUE THREAD

**Issue by osmoze06** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#467]
Bonjour,

Malgré avoir suivi le tutoriel de configuration pour IPTV Simple Client,
J'obtiens une erreur sur n'importe quelle chaines importées depuis le plugin IPTV MANAGER.

Lors du lancement d'une chaine, j'obtiens le message "DATABASE ERROR : database disk image is malformed".

J'ai tout réinstallé : KODI + CATCHUP TV + IPTV MANAGER et préalablement rétabli les paramètres d'origine de IPTV Simple Client.
J'ai également supprimer les BD TV32.db précédemment généré pour réinitialiser mais rien n'y fait.

J'ai le même problème sur les replay.

J'ai deux autres Clés MIStick Android où tout fonctionne bien en ayant fait le même processus.

En vous remerciant pour votre aide.

Environment :
 - Android

 Operating system version/name:
 - Kodi version 19 MATRIX (Fresh Install)
 - Catch-up TV & More version BETA05

**Comment by osmoze06** [comment]
Apres une énième réinstallation de la version Catch-Up BETA 5, tout est OK.

**Comment by nirolfa** [comment]
j'ai le problème pour la première fois
-> reinstall catchup (update), clear cache catchup
-> l'erreur reste -> est il possible de faire un reset db sans perdre les autres reglages ? ?
