### ISSUE TITLE
Replay W9 kodi crash et redémarre 

### ISSUE THREAD

**Issue by marvin88-dev** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#469]
kodi version : 18.9 sur un raspberry pi 4
catch-up TV & more : 0.2.33 beta 05

bonjour voici mon problème, 
quand je lance un replay W9 celui-ci crash et kodi redémarre
le direct fonctionne parfaitement 
les replay de toutes les autres chaines fonctionne aussi parfaitement
j'ai vérifié mon compte 6play tout est ok  

si vous avez une solution je suis preneur merci

**Comment by wwark** [comment]
Bonjour @marvin88-dev,

Nous aurions besoin des  logs en mode debugs suite à un crash pour le comprendre et voir s'il est déjà référencé dans le forum de Kodi et peut être une solution.
Vous avez aussi des logs crash*kodi* de généré sur disque mais je ne sais pas où ils sont sur RPI4.

Merci,

**Comment by wwark** [comment]
Bonjour @marvin88-dev,

Désolé je n'avais pas revu les anciens tickets.
Je pense que votre soucis est similaire à celui-ci : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/476
Est-ce que les replays W9 à partir du 24/03/2021 sont ok pour vous ?

Merci,

**Comment by wwark** [comment]
lié au #476 à rouvrir si ce n'est pas le cas.
