### ISSUE TITLE
Live BFMTV : KODI crash (à la pub)

### ISSUE THREAD

**Issue by osmoze06** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#470]
Bonjour,

La chaine BFMTV fait crasher KODI dès que celle-ci diffuse la publicité (chaine lancée à partir de IPTV Simple Client).
Ce problème existait déjà dans les précédentes versions du plugin et de KODI.

N'ayant pas trouvé de solution sur Google, peut-être y a t'il un ticket d'ouvert ici ?

En vous remerciant pour votre aide,
-----------------------------------------------
 - [x] Android (MiStick)
 - [x] Raspberry-Pi (LibreElec)

 - Kodi version: MATRIX 19
 - Catch-up TV & More version: Beta5

**Comment by wwark** [comment]
Bonjour @osmoze06,
Ce live demande d'être redémarré quand on arrive à la pub et dans certains cas cela fait crasher Kodi.
Ces pubs sont insérés dans le direct TV comme sur le site web.
Il faudrait extraire le log en mode debug suite à un test et ouvrir une issue après de Kodi sur leur GitHub pour voir s'ils peuvent y faire quelque chose ...

Merci,
Wwark

**Comment by chamchenko** [comment]
Hi,
To avoid that problem I guess you could use their live from dailymotion
https://www.dailymotion.com/BFMTV

**Comment by wwark** [comment]
Hi @chamchenko,
Thank you for this information. I will test it.

**Comment by wwark** [comment]
The change is done on the last 0.2.34~beta 04.
Le changement a été appliqué sur la dernière 0.2.34~beta04. Il ne devrait plus avoir le soucis sur la pub.

**Comment by osmoze06** [comment]
Bonjour et merci pour cette mise à jour. 
Installation de la version 0.2.34beta 04 effectuée reste plus qu'à tester.

**Comment by wwark** [comment]
@osmoze06 sur ce point nous ne pourrions pas faire grand chose.
C'est au niveau du kodi player ...
