### ISSUE TITLE
radio in .m3u playlist

### ISSUE THREAD

**Issue by PowaBanga** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#474]
**Is your feature request related to a problem? Please describe.**
Tv playlists are very much used to watch tv in pvrdirectly in kodi 's tv tab , but radio tab stay empty.

**Describe the solution you'd like**
Why not to start by simply add web radio links in the .m3u files ?

**Comment by wwark** [comment]
Hi @PowaBanga,

Do you mean Web Radio TV (with video) or just Web Radio (with sound) ?

Thanks,

**Comment by dagwieers** [comment]
IPTV Manager also supports radio channels, so if the implementation was done including radio channels, I would expect them to be selectable in the settings and they should show up automatically in the PVR Radio section.

**Comment by dagwieers** [comment]
BTW There is already a good Radio add-on in Kodi, it probably make sense to add it there.

**Comment by PowaBanga** [comment]
@wwark webradio tv are already included in the TV tab no ? i think that what i speak about is radio without vidéo... accessible from radio tab in kodi.

**Comment by sy6sy2** [comment]
We don't have any "sound only" radio in the add-on, only video radio flux.
Maybe I'm wrong but I guess that the built-in Radio section of Kodi is only for "audio only" radio items, this is why we only use the TV section at the moment.
