### ISSUE TITLE
some M6 replay crash kodi - Kodi 18.x

### ISSUE THREAD

**Issue by oluc** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#476]
some M6 replay crash kodi. 

A few tried:
- Top Chef or Objectif Top Chef crashes
- Pekin Express plays

### To Reproduce
1. Launch one of this replay
==> the spiner spins, then black screen, then kodi restarts

### Your environment
 - Raspberry-Pi 3
 - libreelec 9.2.6 (?)
 - Kodi 18.9 (?)
 - Catch-up TV & More version: version latest beta installed as mentionned in issue #463 

### Debug log
enclosed: /storage/.kodi/temp/kodi_crashlog_20210319185038.log

[kodi_crashlog_20210319185038.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/6173382/kodi_crashlog_20210319185038.log)

**Comment by wwark** [comment]
Hi,
We are aware of that.
https://forum.mpdb.tv/index.php/topic,35713.msg285027.html#msg285027
No solution for the moment for Kodi 18.9.
It is working on Kodi 19.

Thanks,

**Comment by wwark** [comment]
I tested today the catchup TV of  24/03 of Top Chef in Kodi 18.
It works without close Kodi maybe 6play fixe this case I will check on the next catchup tv.

**Comment by oluc** [comment]
I tried the two last ones,
- Top Chef 17/03 : long wait then crash kodi 18
- Top Chef 24/03 : it works

**Comment by wwark** [comment]
I tested Pekin express 30/03 : it works

I proposed to close this ticket.

**Comment by oluc** [comment]
(from my initial testing, Pekin Express did not have issue, it was playing well.
Top Chef or Objectif Top Chef had issues.
Since last week, the latest Top Chef episode did play well, but older ones still failed.)

that being said, feel free to close the ticket

**Comment by wwark** [comment]
Thanks !
