### ISSUE TITLE
Please add CNA live news channel

### ISSUE THREAD

**Issue by bcptt** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#478]
### Content description

* Name: CNA
* Type [e.g. TV channel, Catch-up TV, Website, Radio]: TV channel / Website
* Website URL: https://www.channelnewsasia.com/news/livetv
* Content language/country: English (Singapore + International)

### Content access

- [ ] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [ ] This content is geographically restricted
- [x] It works without an account, it's tested in the United Kingdom

### More information

If you want to add more information, put it here:

**Comment by joaopa00** [comment]
Implemented in the dev branch. If you see bugs please open a new bug report and attach a log.
I close this issue.
