### ISSUE TITLE
Mycanal - DRM replay and Live TV

### ISSUE THREAD

**Issue by RasPsykk** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#48]
Bonjour,

le site Mycanal propose le live de ses quatre chaines TNT gratuitement malgré des DRM, si vous souhaitez les intégrer et savoir comment on arrive à les proposer sur Kodi n'hésitez pas. On est quelques uns à essayer de réaliser une extension pour ce site internet mais on a du mal à réaliser la partie "abonnés". En effet, nous sommes un peu bloqués malgré l'utilisation de inputstream.adaptive pour faire trouver le flux une fois l'abonné loggé sur le site. Pourriez-vous nous aider?

Si vous souhaitez discuter autours de cela rejoignez-nous sur le discord : https://discord.gg/NZqfP2V
Sinon je reste également ici pour répondre à vos questions.

Amicalement

**Comment by wwark** [comment]
Bonjour RasPsykk,

La gestion de certains DRM sera disponible à partir de Kodi 18 qui n'est pas encore sortie. 
Il est possible que l'implémentation dans Kodi change aussi et des impacts sur l'intégration des DRM. 
Je pense qu'on commencera à y bosser à partir de la sortie de Kodi 18 (peu de temps en ce moment).

J'ai aussi regardé pour les DRM utilisé dans les replays de TF1 et ils ne sont pas supportés par le inputstream.adaptive pour l'instant.

Un conseil si vous avez déjà des choses qui fonctionnent vous devriez le rendre disponible et des personnes viendrons vous aider c'est sûr (mycanal est sûrement très attendu par pas mal de personnes).

Merci,
Wwark

**Comment by RasPsykk** [comment]
Bonjour,

merci pour votre réponse, voici ce que nous avons fait dans un premier temps pour Kodi 18 (inputstream.adaptative étant inclus) :

https://mon-partage.fr/f/QlZHlNET/

Pour ce qui est du reste nous sommes bloqués, il y a quelques développeurs sur le discord mais beaucoup de monde est occupé également. Je ne pense pas qu'il nous manque grand chose puisque dans un premier temps je pense passer par sélénium histoire de ne pas trop galérer à trouver "le chemin" suivi par le site internet.
En effet, je pensais que cela intéresserait beaucoup de monde mais apparemment pas énormément de développeurs.

Merci encore pour votre aide.

Amicalement

**Comment by wwark** [comment]
Je viens tester et les direct tv fonctionnent. C'est top! 
Le but est d'avoir que les direct tv ou aussi les replay? Si vous voulez ajouter les replay n'hésitez pas utiliser ce code [https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/master/resources/lib/channels/fr/mycanal.py](url) 

Bon courage,
Wwark

**Comment by RasPsykk** [comment]
Oui c'est pour ça on se sent sur la bonne voie et ce serait un vrai plus d'avoir quelqu'un qui a déjà fait ça qui pourrait nous aider, on cherche "juste" à choper les liens vers les flux apres qu'ils aient été vérifiés par les noms d'utilisateur et mot de passe du compte.

Personne pour essayer de s'y pencher un petit peu?

Amicalement

**Comment by diapator** [comment]
Bonjour je n'arrive pas à accéder aux Replay de la série lucifer sur c8

**Comment by wwark** [comment]
Bonjour Diapator,

Il y a eu des changements sur le site de Canal+. Nous avons corrigé la navigation du plugin sur la branche de developpement du plugin (https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/tree/dev)
Cependant la majorité des contenus sont protégés par DRM maintenant donc non lisible pour l'instant. Ce point requiert Kodi 18 et des changements du plugin pour prendre en charge ce DRM.

Merci,
Wwark

**Comment by wwark** [comment]
DRM replay - Infos 

# TODO Add CODE DRM

        # Utile ?
        # https://secure-webtv-static.canal-plus.com/widevine/cert/cert_license_widevine_com.bin
        # Response
        # CsECCAMSEBcFuRfMEgSGiwYzOi93KowYgrSCkgUijgIwggEKAoIBAQCZ7Vs7Mn2rXiTvw7YqlbWYUgrVvMs3UD4GRbgU2Ha430BRBEGtjOOtsRu4jE5yWl5KngeVKR1YWEAjp+GvDjipEnk5MAhhC28VjIeMfiG/+/7qd+EBnh5XgeikX0YmPRTmDoBYqGB63OBPrIRXsTeo1nzN6zNwXZg6IftO7L1KEMpHSQykfqpdQ4IY3brxyt4zkvE9b/tkQv0x4b9AsMYE0cS6TJUgpL+X7r1gkpr87vVbuvVk4tDnbNfFXHOggrmWEguDWe3OJHBwgmgNb2fG2CxKxfMTRJCnTuw3r0svAQxZ6ChD4lgvC2ufXbD8Xm7fZPvTCLRxG88SUAGcn1oJAgMBAAE6FGxpY2Vuc2Uud2lkZXZpbmUuY29tEoADrjRzFLWoNSl/JxOI+3u4y1J30kmCPN3R2jC5MzlRHrPMveoEuUS5J8EhNG79verJ1BORfm7BdqEEOEYKUDvBlSubpOTOD8S/wgqYCKqvS/zRnB3PzfV0zKwo0bQQQWz53ogEMBy9szTK/NDUCXhCOmQuVGE98K/PlspKkknYVeQrOnA+8XZ/apvTbWv4K+drvwy6T95Z0qvMdv62Qke4XEMfvKUiZrYZ/DaXlUP8qcu9u/r6DhpV51Wjx7zmVflkb1gquc9wqgi5efhn9joLK3/bNixbxOzVVdhbyqnFk8ODyFfUnaq3fkC3hR3f0kmYgI41sljnXXjqwMoW9wRzBMINk+3k6P8cbxfmJD4/Paj8FwmHDsRfuoI6Jj8M76H3CTsZCZKDJjM3BQQ6Kb2m+bQ0LMjfVDyxoRgvfF//M/EEkPrKWyU2C3YBXpxaBquO4C8A0ujVmGEEqsxN1HX9lu6c5OMm8huDxwWFd7OHMs3avGpr7RP7DUnTikXrh6X0

        # https://player.mycanal.fr/one/prod/v2/bundle-api.js (contient les id des trois JS ci-dessous)
        # https://player.mycanal.fr/one/prod/v2/1.1.chunk-811df61222c423293fda.js
        # https://player.mycanal.fr/one/prod/v2/5.5.chunk-2dc4906a84344fcc4084.js
        # https://player.mycanal.fr/one/prod/v2/18.18.chunk-7e9778d8f6a9708b67f8.js
        # Info on the passToken on these three JS below not easy to build (????) = maybe need help ...

        # URL of the manifest
        # GET need the Pass Token (return 401 if calling directly)
        # https://secure-gen-hapi.canal-plus.com/conso/view/6f97b560-50ca-11e9-b127-4b12d86c665a/media

        # URL of the licence pour mycanal
        # POST to be used on URL_LICENCE_DRM normally
        # need the Pass Token (return 401 if calling directly)
        # https://secure-gen-hapi.canal-plus.com/conso/view/6f97b560-50ca-11e9-b127-4b12d86c665a/licence?drmType=DRM%20Widevine

**Comment by wwark** [comment]
Hi,
I made some steps but block to get the DRM licence HTTP 401 (maybe something not good in the headers not known)
Last commit https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/4b4a6bb7986a02421bc38584bbea41ada443b386
**if someone can take a second look**. after that we can have DRM content for catch-up tv of mycanal 
I have also a header i don't find where to get it ...
 'XX-DEVICE': 'pc 9d6b98c4-433a-4150-9778-b668cc980109',
So maybe for your tests you need to change this value.

Wwark.

**Comment by wwark** [comment]
Hi,
There is some update we have HTTP 200 when we call the licence server of mycanal.fr
Meanwhile, the response of the server can't be parsed (XML with key encoded base64) by inputstream.adaptive.
An update of inputstream adaptive can resolve this case.
Normally after the content will be playable !

Wwark

**Comment by wwark** [comment]
The value UUID of 'XX-DEVICE': 'pc UUID" is stored in the local storage of the browser for the domain "https://www.mycanal.fr"

**Comment by amidevous** [comment]
et maintenant que kodi 18 et sortie depuis un moment d’ailleurs ont et toujours sans nouvelle

pour la partie abonner je peux fournir des compte si besoin

y a tous sauf les chaines adulte

validité des compte 1 mois

c'est le moi gratuit enfaite l'astuce

vous utilisez utiliser une cb virtuel qui peux être supprimer

comme la revolut et bing un moi gratos

et prenez un abo avec engagement 2 ans

et canal vous offre le premier moi gratos

et ensuite une fois la cb supprimer il peuvent pas facturée les mois suivant

pour la validation numérique du contrat ben un num de service sms en ligne sa marche aussi

sa marcher aussi sur netflix mais vu qui ont enlever le moi gratos marche plus

deezer également compatible avec sa et en ce moment deezer propose 3 mois gratos

**Comment by wwark** [comment]
Hello @amidevous,
La clé DRM n'est pas capable d'être récupérer par la librairie DRM de Kodi.
Pour l'instant ce n'est pas possible. On a ouvert une issue pour ce point.
Merci,
Wwark

**Comment by saidnai** [comment]
Hello toutes et tous ! :)
J'ai un abonnement MyCanal et voudrais pouvoir l'utiliser depuis Kodi.
Je ne suis pas sûr d'être au bon endroit, mais ;
- Existe-t-il une extension dédiée MyCanal ?
- Puis-je utiliser Catch-Up TV & More avec mes identifiants MyCanal pour accéder aux contenus ?

Dans Catch-Up, je ne peux pas entrer les identifiants MyCanal. J'ai bien M6, NRJ, etc... Mais pas de Canal :/

Merci d'avance pour vos réponses :)

**Comment by mtr81** [comment]
Hi,
Do you still have a problem with live stream f.e. CSTAR and other live tv from MyCanal? I am asking because I found solution today.

**Comment by BenGost** [comment]
Hello,

Still no solution?

Thank you

**Comment by Arias800** [comment]
Hello,
I have implemented the code of @mtr81.
So now, the livestream will be taken directly from the official website.

For the catchup, nothing changed.
Inpustream is incapable to read the key.

**Comment by Arias800** [comment]
In the current beta, the site is fully usable (including drm protect content).

**Comment by thombet** [comment]
> In the current beta, the site is fully usable (including drm protect content).

I would like to use what you implemented even if it's only in beta. Is it possible?

**Comment by Arias800** [comment]
You can reuse the code if you want.
It's in beta at the moment, but it works very well on my side.

**Comment by thombet** [comment]
> You can reuse the code if you want.
> 
> It's in beta at the moment, but it works very well on my side.

Great! Where can I find it please?☺️
Is it on a specific branch? Or in your fork?

**Comment by darodi** [comment]
> > You can reuse the code if you want.
> > It's in beta at the moment, but it works very well on my side.
> 
> Great! Where can I find it please?☺️ Is it on a specific branch? Or in your fork?

https://catch-up-tv-and-more.github.io/installation/#ii-add-the-official-catch-up-tv--more-repository

And use the beta channel.

Or use this zip directly

https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/archive/refs/heads/dev.zip

**Comment by thombet** [comment]
I was not aware of the beta channel, thanks for the info!

I expected to find the paid channels of MyCanal in the live TV and to have a way to enter the credentials of my MyCanal account but I didn't find anything.
Did I understand wrongly? Only the free MyCanal channels are available?

**Comment by darodi** [comment]
>  Only the free MyCanal channels are available?

That's it. Can't help you there I'm afraid. I don't have a mycanal subscription to implement something.

**Comment by mac1202** [comment]
Bonjour je viens d'installer votre addon et kodi sur android TV. C8 et canal+ ne fonctionne pas. J'ai une erreur :




IndexError
list index out of range

**Comment by darodi** [comment]
@mac1202 
- voir #950
