### ISSUE TITLE
Catchup tv and matrix kodi 19

### ISSUE THREAD

**Issue by Che-debarras** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#482]
Hello,

Je souhaiterais savoir si catchup tv est fonctionnelle sur Kodi 19 matrix et quelles sont les bugs rencontrées pour savoir su cela vaut le coup de mettre à jour kodi.

Merci pour vos retours concernant l'addon sur Kodi 19.

**Comment by wwark** [comment]
Hello @Che-debarras,

Nous n'avons pas de bug connu lié spécifiquement à Kodi 19 (les bugs listés sont présents sur Kodi 18 et 19)
Kodi 19 permet cependant de lire les derniers replays de 6plays sans que Kodi crash. (cf ce ticket pour Kodi 18.9 : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/476)
Il y a des soucis sur Kodi19 avec certains skins et l'addon qu'on nous a remonté mais pour l'instant on n'a pas regardé ce point.

De mon point de vu, je pense qu'il vaut mieux attendre la version 19.1 qui va apporter son premier lot de correction.
Sur mon instance que j'ai migré en Kodi 19, la moitié de mes addons que j'utilisent ne sont pas disponibles (non compatible Kodi19).

Merci,

**Comment by enigma131** [comment]
De mon coté tous les PVRs fonctionnent en Kodi 19 ainsi que Youtube. Quant à Kodi 19.1 on risque d'attendre: no due date : https://github.com/xbmc/xbmc/milestone/141
