### ISSUE TITLE
Erreur avec C8 Cstar et Cnews Live TV

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#488]
Live TV hs, Kodi 19 && plugin version 0.2.34 beta6
Youtube-dl error

**Comment by wwark** [comment]
Hi @enigma131,

I can't reproduce this issue. Is the issue still present on your side ?
Could you please share the whole log after the issue appeared ?

Thanks,

**Comment by enigma131** [comment]
It's working this evening without understanding why. Got an update or was source out of order ?

**Comment by wwark** [comment]
No change done for this part in the last update.
Next time the whole log may help to understand the issue.
I close this ticket !

Thanks,

**Comment by enigma131** [comment]
Yes of course, I have forgot the log. I think perhaps on an update of youtube-dl.

**Comment by wwark** [comment]
Yest, you can check on your list addons updated if you have youtube-dl updated.
Also the issue from the channel is possible. It happens sometime.
