### ISSUE TITLE
Arte channel not working

### ISSUE THREAD

**Issue by pascalou95** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#49]
Bonjour à tous,

Depuis quelques jours, l'accès au replay d'Arte ne fonctionne plus. Il semble qu'il y a eu des modifications sur leurs serveurs.

Serait-il possible d'avoir une mise à jour ? Merci pour ce superbe plugin.

**Comment by wwark** [comment]
Hello,
Je confirme le Replay est KO. Le direct TV fonctionne encore.
Nous regardons pour corriger ce point.
Merci,
Wwark

**Comment by wwark** [comment]
Corrigé. Je ferme le ticket. 
Vous pouvez le rouvrir si besoin.
Merci,
wwark
