### ISSUE TITLE
No EPG on Arte and TV5Monde through IPTV Manager 

### ISSUE THREAD

**Issue by Rvhalewyn** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#490]
### Describe the bug
A clear and concise description of what the bug is:see title

### To Reproduce
1.open TV guide with IPTV Manager information on Libreelec device with kodi 18.9 
2. Belgian and French channels do show epg 
3.
4.

### Expected behavior
A clear and concise description of what you expected to happen:
EPG for Arte and TV5Monde should also show, as I  can open the live channels with French server VPN 
### Actuel behavior
Tell us what happens instead:
Guide stays blank  for those 2 channels 
### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - x Libreelec 

 - Operating system version/name:
 - Kodi version: 18.9
 - Catch-up TV & More version: 0.2.33
 - Installation method: Repository
 - 
 -  [Screenshot ](https://www.dropbox.com/sh/r0fefj30yz0vh3b/AABP7xKsLV6yNNq8VoQiqLlEa?dl=0) 

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by sy6sy2** [comment]
Hi!
Sorry that my fault I guess. 
Since the migration from "manual" M3U files to IPTVManager I only added partial support to multi lingual channels like Arte.
I will try to Dix this ASAP 😉

**Comment by Rvhalewyn** [comment]
That would be great.
By the way, I have another feature request.
Adding an account entry for NPO. As I have a premium account there, I now have to use the Retrospect add-on, because I can log in there and so get HD quality. Login to NPO is optional, but with a free account you only get SD quality. So  testing the account would be no cost for the developer.

**Comment by sy6sy2** [comment]
That should be good. This is the changes list:

* Concerning `Live TV` section of the plugin itself. If you have TV guide enable in CUTV settings, if you select Arte FR and finally if you go in `CUTV --> Live TV --> International` you should have current TV guide for `Arte (FR)`
* Concerning IPTV Manager. If you go in `TV Integration` tab of CUTV settings and if you select `Select channels to enable` you should be able to select Arte FR AND/OR Arte DE independently of the language choose in CUTV settings (this allow you to have both Arte FR and Arte DE in the bulot-in Live TV section of Kodi).
* Also, if you enable Arte FR with IPTV Manager you should be able to have the correct TV guide in build-in Iive tv section of Kodi. 

Related commits: 158da69b72784150b5d44693ccb5403630a09aab, 94504be69f0ebdd8f55e1e35cb96a7a6362ffa4f, d33a39201b5267988cea581ef1c433dd668ea039

Can you try these changes with 0.2.34~beta09 version of the plugin please (you can install it manually from zip or update from our beta repo channel). thank you very munch!

Concerning NPO, can you please open a second ticket with the "Add new content" issue template?

**Comment by Rvhalewyn** [comment]
Installed beta version, TV guide was already enabled.
Arte epg working now !
But TV5MONDE-FBS epg stays empty.

**Comment by sy6sy2** [comment]
Thanks for the test.

Concerning TV5 Monde EPG, I need to add it on https://github.com/Catch-up-TV-and-More/xmltv/ so it's not a plugin issue.

(issue needs to be closed after 0.2.34 release)
