### ISSUE TITLE
Changer flux video

### ISSUE THREAD

**Issue by bbodinier** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#496]
Hello, Je regarde majoritairement Arte et France.tv en replay sur kodi (Alpine linux sur Rpi4) avec votre plugin depuis de nombreuses années. Merci à vous !

Depuis peu, il n'est plus possible de changer le flux vidéo (malgré l'option DIAG). Le flux est imposé à 

`Undetermined (h264, 1280x720)`

Comme ma connexion adsl est lente, le flux est trop volumineux et le contenu est mis en pause régulièrement pour mise en cache. J'ai modifié les paramètres de mise en cache, sans régler le problème. La solution de repli est un download du contenu avec youtube-dl ou le visionnage depuis un explorateur internet, car sur Arte par exemple, j'ai toujours le choix de plusieurs qualité de flux.

Est-ce un comportement normal de Catch-Up TV ?

**Comment by wwark** [comment]
Bonjour @bbodinier,

Sur quel contenu exactement vous avez le cas Live TV et/ou Replay ?
Il est possible que la chaine TV en question ne propose plus qu'un flux de cette qualifité.

Si vous êtes en Kodi 18 et 19 durant la lecture vous pouvez aussi changer le bitrate si le flux vidéo le permet (différent entre les chaines).

Merci,
Wwark

**Comment by bbodinier** [comment]
J'ai le cas sur tous les contenus Replay de Arte et France.tv. J'utilise Kodi V18.9 avec Catch-Up TV V0.2.33.
Pour prendre un exemple concret, le téléfilm "Le passe muraille" en replay sur Arte est disponible avec plusieurs flux :

```
youtube-dl -F https://www.arte.tv/fr/videos/057874-000-A/le-passe-muraille/

[info] Available formats for 057874-000-A:
format code    extension  resolution note
HLS_XQ_3-61    mp4        audio only   61k , mp4a.40.2
HLS_XQ_4-61    mp4        audio only   61k , mp4a.40.2
HLS_XQ_5-61    mp4        audio only   61k , mp4a.40.2
HLS_XQ_6-61    mp4        audio only   61k , mp4a.40.2
HLS_XQ_2-61    mp4        audio only   61k , mp4a.40.2
HLS_XQ_1-61    mp4        audio only   61k , mp4a.40.2
HLS_XQ_3-351   mp4        384x216     351k , avc1.66.30, mp4a.40.2
HLS_XQ_4-351   mp4        384x216     351k , avc1.66.30, mp4a.40.2
HLS_XQ_5-351   mp4        384x216     351k , avc1.66.30, mp4a.40.2
HLS_XQ_6-351   mp4        384x216     351k , avc1.66.30, mp4a.40.2
HLS_XQ_5-888   mp4        640x360     888k , avc1.77.30, mp4a.40.2
HLS_XQ_3-901   mp4        640x360     901k , avc1.77.30, mp4a.40.2
HLS_XQ_6-901   mp4        640x360     901k , avc1.77.30, mp4a.40.2
HLS_XQ_4-902   mp4        640x360     902k , avc1.77.30, mp4a.40.2
HLS_XQ_5-1550  mp4        720x406    1550k , avc1.77.30, mp4a.40.2
HLS_XQ_3-1555  mp4        720x406    1555k , avc1.77.30, mp4a.40.2
HLS_XQ_4-1555  mp4        720x406    1555k , avc1.77.30, mp4a.40.2
HLS_XQ_6-1555  mp4        720x406    1555k , avc1.77.30, mp4a.40.2
HLS_XQ_5-2213  mp4        1280x720   2213k , avc1.77.30, mp4a.40.2
HLS_XQ_3-2224  mp4        1280x720   2224k , avc1.77.30, mp4a.40.2
HLS_XQ_6-2224  mp4        1280x720   2224k , avc1.77.30, mp4a.40.2
HLS_XQ_4-2225  mp4        1280x720   2225k , avc1.77.30, mp4a.40.2
HTTPS_MQ_3     mp4        384x216    VFAUD, Français (audiodescription)  300k
HTTPS_MQ_4     mp4        384x216    VA-STA, Allemand  300k
HTTPS_MQ_5     mp4        384x216    VA-STMA, Allemand (sourds et malentendants)  300k
HTTPS_MQ_6     mp4        384x216    VAAUD, Allemand (audiodescription)  300k
HTTPS_HQ_3     mp4        640x360    VFAUD, Français (audiodescription)  800k
HTTPS_HQ_4     mp4        640x360    VA-STA, Allemand  800k
HTTPS_HQ_5     mp4        640x360    VA-STMA, Allemand (sourds et malentendants)  800k
HTTPS_HQ_6     mp4        640x360    VAAUD, Allemand (audiodescription)  800k
HTTPS_EQ_3     mp4        720x406    VFAUD, Français (audiodescription) 1500k
HTTPS_EQ_4     mp4        720x406    VA-STA, Allemand 1500k
HTTPS_EQ_5     mp4        720x406    VA-STMA, Allemand (sourds et malentendants) 1500k
HTTPS_EQ_6     mp4        720x406    VAAUD, Allemand (audiodescription) 1500k
HTTPS_SQ_3     mp4        1280x720   VFAUD, Français (audiodescription) 2200k
HTTPS_SQ_4     mp4        1280x720   VA-STA, Allemand 2200k
HTTPS_SQ_5     mp4        1280x720   VA-STMA, Allemand (sourds et malentendants) 2200k
HTTPS_SQ_6     mp4        1280x720   VAAUD, Allemand (audiodescription) 2200k
HLS_XQ_2-352   mp4        384x216     352k , avc1.66.30, mp4a.40.2
HLS_XQ_2-888   mp4        640x360     888k , avc1.77.30, mp4a.40.2
HLS_XQ_2-1550  mp4        720x406    1550k , avc1.77.30, mp4a.40.2
HLS_XQ_2-2212  mp4        1280x720   2212k , avc1.77.30, mp4a.40.2
HTTPS_MQ_2     mp4        384x216    VOF-STMF, Français (sourds et malentendants)  300k
HTTPS_HQ_2     mp4        640x360    VOF-STMF, Français (sourds et malentendants)  800k
HTTPS_EQ_2     mp4        720x406    VOF-STMF, Français (sourds et malentendants) 1500k
HTTPS_SQ_2     mp4        1280x720   VOF-STMF, Français (sourds et malentendants) 2200k
HLS_XQ_1-351   mp4        384x216     351k , avc1.66.30, mp4a.40.2
HLS_XQ_1-901   mp4        640x360     901k , avc1.77.30, mp4a.40.2
HLS_XQ_1-1555  mp4        720x406    1555k , avc1.77.30, mp4a.40.2
HLS_XQ_1-2224  mp4        1280x720   2224k , avc1.77.30, mp4a.40.2
HTTPS_MQ_1     mp4        384x216    VOF, Français  300k
HTTPS_HQ_1     mp4        640x360    VOF, Français  800k
HTTPS_EQ_1     mp4        720x406    VOF, Français 1500k
HTTPS_SQ_1     mp4        1280x720   VOF, Français 2200k  (best)
```

Sur kodi, via Catch-Up TV, le seul flux possible (grisé) durant la lecture du téléfilm est :

`Undetermined (h264, 1280x720)`

Cela vient peut-être d'un autre réglage sur kodi ? Le flux 720x406 passe sur ma liaison ADSL, pas le 1280x720.

**Comment by joaopa00** [comment]
J'ai le même problème pour le direct de LCI.

**Comment by wwark** [comment]
Bonjour,

Pour Arte, on n'a jamais fait de flux basse qualité dans le menu DIAG (il permet d'avoir accès à différents contenus (langues différentes avec ou sans sous-titre) On va regarder pour voir si on peut récupérer des qualités différentes.
Il se peut que la chaine avant proposait pour son flux des qualités différentes dans le menu de lecture de Kodi.

Pour les autres chaines, type LCI, vous pouvez durant la lecture du flux vidéo changer le bitrate comme ceci :
![Screenshot from 2021-04-12 07-41-05](https://user-images.githubusercontent.com/469461/114345727-88d9af80-9b62-11eb-8331-bdbf0af9f73e.png)
Ce mode existe depuis Kodi 18 (video options durant la lecture.

Merci,
Wwark

**Comment by bbodinier** [comment]
J'ai solutionné en paramétrant InputStream Adaptive :

`Selection du flux : Manually select videao stream`

**Comment by joaopa00** [comment]
Pour moi, la ligne où il y a la qualité est grisée. Impossible de cliquer dessous. La capture d'écran es faite sous linux, mais j'ai le même problème sous AndroidTv
![Screenshot_20210412_153221](https://user-images.githubusercontent.com/13057733/114483806-c2cba580-9ba4-11eb-8622-b8a44601bbfd.png)

**Comment by wwark** [comment]
@joaopa00 pourriez-vous tester de positionner l'option "Manually select all stream" dans les options de Inputstream.adaptive ?
Merci,

**Comment by joaopa00** [comment]
Super. Ca marche. Merci pour l'astuce. Il fallait la connaître celle-là!!

**Comment by vabnou** [comment]
Merci beaucoup ça a fonctionné Je suis trop contents il m’a fallu de taper InputStream Adaptive et de modifier comme indiquer plus haut 👍🏻👍🏻
