### ISSUE TITLE
Probleme guide tv et iptv simple client

### ISSUE THREAD

**Issue by mmtest1** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#497]
bonjour,

depuis plusieurs jours je rencontre un problème avec la tv en direct, le pvr iptv simple client renvoie une page vide et le direct par l’extension renvoie une erreur d'obtention des programmes mais permet néanmoins de visualiser le direct.
J'ai tenté de re paramétrer l'extension avec la nouvelle procédure iptv manager, même résultat. J'ai tenté une fraîche install même résultat. Installation de Catch Up TV and More en version stable et beta même résultat.

Mon matériel : raspberry pi 4 avec raspberry pi OS buster et kodi 18.6 (dépôt officiel)

Par contre sur mon ordinateur (kubuntu 20.04 et kodi 19) aucun problème à première vue

Mon fichier log : 
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/6292740/kodi.log)

ce qui semble poser problème : ERROR: [Catch-up-TV-&-More] xmltv module failed with error: 'encoding' is an invalid keyword argument for this function

il y a aussi une erreur qui renvoie à mon skin Xonfluence, mais une fresh install avec skin de base provoque la même erreur

Pourriez-vous vérifier la situation, je vous remercie pour votre très bon travail
dites-moi s'il vous faut plus d'info ou besoin de test
merci

**Comment by caywin25** [comment]
Bonsoir, 

Je confirme avoir le même soucis.
La conf d'iptv manager n'a pas changé pourtant.

Merci

**Comment by mmtest1** [comment]
je n'en suis pas sur mais il me semble aussi que le problème est survenu suite à une mise à jour de l'extension

**Comment by sy6sy2** [comment]
Hello, merci d'avoir remonté ce problème. Je pense savoir d'où ça vient, je regarde ça.

**Comment by sy6sy2** [comment]
Re,
J'ai l'impression que le commit https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/1a68ce0c7edcbfc5d61783cbe8846356fcd72b3d regle le problème.

Pouvez à l'occasion tester la version 0.2.35~beta01 du plugin ? Merci

**Comment by mmtest1** [comment]
je viens de tester la version 0.2.35~beta01 du plugin, reboot, mêmes symptômes. J'ai relancé iptv manager, "refresh channels and guide now...." (qui renvoie une erreur) et "configure IPTV Simple automatically..." suivi d'un reboot et mêmes problèmes apparents, la fonction TV de Kodi renvoie une page vide et le direct france de l'extension n'affiche plus le guide mais cette fois n'affiche plus de message d'erreur au lancement

mon nouveau fichier log :
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/6299644/kodi.log)

merci pour le suivi

**Comment by sy6sy2** [comment]
Merci pour le test. 
Peux tu essayer de vider le cache depuis l'onglet "avancé" des settings du plugin stp ?

**Comment by mmtest1** [comment]
Après avoir vidé le cache le guide est à nouveau opérationnel dans l'extension mais la fonction Tv de kodi est toujours dans les choux....

**Comment by sy6sy2** [comment]
Dans le log il y a cette ligne :
`2021-04-12 22:23:05.059 T:2761306320   ERROR: AddOnLog: PVR IPTV Simple Client: Unable to load channels from file '/home/mmze/.kodi/userdata/addon_data/service.iptv.manager/playlist.m3u8':  file is corrupted.`. 

J'ai pas l'ordi sous la main mais peut être qu'en supprimant ce fichier et en demandant de nouveau à IPTV manager de rafraîchir ça peut peut être le faire ?
Sinon je testerai demain avec l'ordi.

**Comment by mmtest1** [comment]
je viens de supprimer le fichier, reboot, refresh, reboot et même soucis, section TV hs....

**Comment by mmtest1** [comment]
lorsque je re télécharge le fichier playlist et que je le renomme en.txt à l'ouverture j'ai : #EXTM3U
## Catch-up TV & More
le reste du fichier étant vide, expliquant l'absence de chaines dans l'onglet TV
Le fichier est à nouveau annoncé comme corrompu
Une erreur apparaît brievement concernant : UnicodeEncodeError
voici le lien : https://paste.kodi.tv/vovepetefi

encore merci pour le suivi et à demain certainement avec l'ordi ou si je peux faire d'autres test

**Comment by mmtest1** [comment]
à la fin du past : 

NOTICE: [service.iptv.manager] [resources.lib.modules.addon] Updating IPTV data for plugin.video.catchuptvandmore...
2021-04-12 23:19:32.717 T:2614571216  
NOTICE: [service.iptv.manager] [resources.lib.modules.addon] Requesting channels from plugin://plugin.video.catchuptvandmore/resources/lib/iptvmanager/channels/...
2021-04-12 23:19:32.809 T:2614571216  
NOTICE: [service.iptv.manager] [resources.lib.modules.addon] Executing RunPlugin(plugin://plugin.video.catchuptvandmore/resources/lib/iptvmanager/channels/?port=37623)...
2021-04-12 23:19:35.328 T:2614571216   
ERROR: [service.iptv.manager] [resources.lib.modules.addon] Something went wrong while calling plugin.video.catchuptvandmore: Something went wrong in plugin.video.catchuptvandmore
2021-04-12 23:19:35.329 T:2614571216  
NOTICE: [service.iptv.manager] [resources.lib.modules.addon] Requesting epg from plugin://plugin.video.catchuptvandmore/resources/lib/iptvmanager/epg/...
2021-04-12 23:19:35.330 T:2614571216  
NOTICE: [service.iptv.manager] [resources.lib.modules.addon] Executing RunPlugin(plugin://plugin.video.catchuptvandmore/resources/lib/iptvmanager/epg/?port=48003)...
2021-04-12 23:19:35.332 T:2551013584   
ERROR: [Catch-up-TV-&-More.support] 'ascii' codec can't encode character u'\xe9' in position 8: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/mmze/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                redirect = parent_ins(route, arg_params, self.callback_params)
                                              File "/home/mmze/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                return route.function(self, *args, **kwargs)
                                              File "/home/mmze/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/iptvmanager.py", line 270, in channels
                                                IPTVManager(int(port)).send_channels()
                                              File "/home/mmze/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/iptvmanager.py", line 166, in send
                                                sock.sendall(json.dumps(func(self)).encode())
                                              File "/home/mmze/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/iptvmanager.py", line 203, in send_channels
                                                json_stream['stream'] = PLUGIN_KODI_PATH + resolver + '/?' + urlencode(params)
                                              File "/usr/lib/python2.7/urllib.py", line 1345, in urlencode
                                                v = quote_plus(str(v))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 8: ordinal not in range(128)

**Comment by sy6sy2** [comment]
Hello !
Merci

**Comment by sy6sy2** [comment]
Hello !

Merci pour ces tests, il semblerait que la version urlencode de Python 2 n'aime pas l'unicode et ça pose problème dans le cas où on sélectionne une chaine avec une langue/région et des caractères non ASCII (typiquement France 3 Île de France).

Je viens de push la version 0.2.35~beta02, en espérant que ça résolve le problème...

(Vivement la mort de Kodi 18 et de Python 2 xD)

**Comment by mmtest1** [comment]
Bonjour,
je viens d'installer la nouvelle beta et rafraîchir iptv manager, au reboot la tv de kodi et le guide tv refonctionne, le bug semble résolu,
encore merci pour le suivi et la résolution du problème,
kodi 19 avec python 3 ne sont pas encore disponible dans les dépôts officiels de raspberry pi os sous rpi4, seul solution libreelec mais le raspberry a plusieurs utilisations chez moi et un os complet est plus polyvalent......

encore merci et bonne journée

**Comment by sy6sy2** [comment]
Cool merci beaucoup pour les test !!

> kodi 19 avec python 3 ne sont pas encore disponible dans les dépôts officiels de raspberry pi os sous rpi4, seul solution libreelec mais le raspberry a plusieurs utilisations chez moi et un os complet est plus polyvalent......

No problème, je ne blame aucunement les utilisateurs de Kodi 18 et je comprends que le processus de migration est (et surtout va être) lent. Il va falloir encore "vivre" quelques temps avec cette double comptabilité Python 2 et Python 3 😉 

Bonne journée également !
