### ISSUE TITLE
CUTVM - Website - National Film Board of Canada Runtime Error

### ISSUE THREAD

**Issue by missjane63** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#498]
Issue with playback with the National Film Board of Canada (NFB) (under CUTM-Website menu).  It is giving a Runtime Error (YouTube-DL).  This is happening both in Leia and Matrix.

Windows 7
 - Kodi version: Leia and Matrix
 - Catch-up TV & More version: 0.2.35 beta02

**Comment by sy6sy2** [comment]
Hi,
Thank you for this bug report.
Can you try version 0.2.36~beta04 of the plugin? It should solve this issue.

Thank you!
