### ISSUE TITLE
Problème avec l’intégration IPTV manager pour les canaux ayant un accent 

### ISSUE THREAD

**Issue by Daedan17** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#499]
Bonjour, je suis nouveau dans Kodi et j’ai suivi votre tutoriel pour l’installation de Catch-Up mais j’ai un problème lorsque je tente l’intégration avec IPTV manager. Lorsque je sélectionne dans les paramètres de Catch-Up des canaux ayant des accents et que je mets à jours les canaux dans IPTV manager, j’ai une erreur : UnicodeEncodeErreur - ASCII codec can’t encode character u’\xe9’ in position 2: ordinal not in range (128). Lorsque je sélectionne que des canaux sans accents je n’ai pas ce message d’erreur. Le seul problème c’est que la majorité des canaux canadien français comporte des accents donc je me retrouve à ne pouvoir qu’intégrer deux canaux.. est-ce qu’il existe une solution? Merci à l’avance!

**Comment by michaelarnauts** [comment]
It's probably an encoding issue somewhere. IPTV Manager accepts UTF-8 strings fine, as we have a Channel één on the VRT NU add-on.

**Comment by sy6sy2** [comment]
Hello et bienvenue dans l'aventure !

En effet c'est une erreur que j'ai corrigée récemment (voir https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/497).
Je suppose que tu utilises la version 0.2.34 de l'add-on ? Si c'est bien le cas, peux tu essayer la version beta 0.2.35 afin de vérifier qu'il s'agit bien de ce problème ?

Merci d'avance.

**Comment by Daedan17** [comment]
Oui en effet ça règle le problème, désolé du double post j’avais pourtant fait une recherche avant de poster et je ne l’avais pas vu. Merci beaucoup!

**Comment by sy6sy2** [comment]
No problème, merci pour le test rapide et le retour !
