### ISSUE TITLE
error android kodi krypton

### ISSUE THREAD

**Issue by karabounga** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#50]
Bonjour et merci pour ce super plugin,

 
ci joint une erreur lors du lancement de catchup tv. Le plugin fonctionnait correctement jusqu'à il y a environ 15 jours. J'ai désinstallé, réinstallé, installé la dernière beta depuis le dépôt officiel, le message d'erreur est toujours identique. ... mes autres plugins fonctionnent normalement.

pas de remarque désobligente su ma méthode de post des logs :)

![20180324_132103](https://user-images.githubusercontent.com/37739066/37864076-c6f1b776-2f69-11e8-8970-879edb1bbf95.jpg)

**Comment by SylvainCecchetto** [comment]
Bonjour Karabounga,

Tout d'abord merci pour ton retour ! Et merci aussi pour le log, c'est parfait :-P

Wwark connait mieux ce problème que moi mais je pense que tu peux le régler comme ça :

Si tu peux (je ne suis pas trop familier avec Android) supprimer le fichier __gettext__.pcl qui doit être présent dans le dossier userdata/addon_data/plugin.video.catchuptvandmore.

Après ça relance Kodi et le plugin et ça devrait le faire normalement ;-)

**Comment by karabounga** [comment]
Baziiiiinga ! aussitôt dit aussitôt fait !!!! 
Merci pour cette extrême réactivité, problème réglé.

**Comment by SylvainCecchetto** [comment]
"Baziiiinga" O_O ! Connaissais pas xD

De rien, bon week end ! ;-)

Ce commit 2809ab665ddb6d6057817dc0db0e86edb0f079a7 devrait éviter ce problème maintenant (mais @wwark avait déjà fait un fix pour ça avant qu'on fasse l'upgrade de simpleplugin ; je le laisse vérifier que mon fix suffit)

**Comment by wwark** [comment]
Hello,

J'avais écris ce code pour fixer.
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/49a65d80af61c4c5d2620d8fec2ce8ea2666676d

Si j'ai un peu de temps je regarde demain.

Merci,
Wwark.

**Comment by SylvainCecchetto** [comment]
Hey!

Ah j'avais pas retrouvé ton commit ! Merci ; mais en fait la modif que tu as fait dans le commit 49a65d8 est bien la même que je viens de faire à l'instant dans le commit 2809ab6 .

Ce qui confirme que la dernière version de simpleplugin ne résous pas ce problème.

**Comment by wwark** [comment]
Cool ;) Une chose de moins à vérifier.
On devrait ouvrir une issue à l'auteur de simple plugin ?
Merci,
Wwark

**Comment by SylvainCecchetto** [comment]
Yes j'y pensais aussi ! C'est chose faite : https://github.com/romanvm/script.module.simpleplugin/issues/11
