### ISSUE TITLE
unable to open the channel "sport en france" 

### ISSUE THREAD

**Issue by houdini-fr** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#501]
### Describe the bug
Error "impossible de résoudre l'url" when accessing the channel "sport en france"

### To Reproduce
1. open addon Catchup
2. click "TV en direct"
3. click "France"
4. open the channel "sport en France"

### Expected behavior
The channel is correctly displayed

### Actuel behavior
An error "impossible de résoudre l'url" is displayed and the channel is not opened

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ X] Raspberry-Pi 3b+
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 19
 - Catch-up TV & More version: last
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by wwark** [comment]
Hi @houdini-fr,

It is fixed in this commit https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commit/c778dbd4208cf0a06a5397bd0dba8d54ccbff2e4 and available in the next beta version of the plugin.

Thanks,
