### ISSUE TITLE
RuntimeError replay tf1

### ISSUE THREAD

**Issue by tom2411** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#503]
J'ai un problème avec les replay de tf1,
Une RuntimeError sur les replay avec un no item found 
Je suis sur osmc 18.9 
Je suis sur la version 0.2.34

**Comment by wwark** [comment]
Bonjour @tom2411,

Tu aurais un exemple de replay où tu as le soucis.
Je n'arrive pas à reproduire de mon côté.
Pour info ces contenus sont géolocalisés donc ça pourrait être le soucis rencontré.

Merci,

**Comment by tom2411** [comment]
Le remplaçant

**Comment by wwark** [comment]
Merci pour l'information.
Sur le site il est listé mais ne propose aucune  : https://www.tf1.fr/tf1/le-remplacant
Le plugin reproduit ce que l'on voit sur le site web.

Wwark

**Comment by tom2411** [comment]
ok, merci je me disait bien aussi
