### ISSUE TITLE
Nouvelles chaines Belges : TipikVision et Tarmac 

### ISSUE THREAD

**Issue by wwark** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#504]
### Content description

* Name:TipikVision et Tarmac

**Comment by darodi** [comment]
je n'ai pas vu de lien live vidéo pour Tarmac? uniquement un lien pour écouter en direct, sans vidéo.

**Comment by joaopa00** [comment]
Puisque Tarmac est introuvable, je vais fermer cet rapport. Si l'auteur le souhaite, il peut ouvrir un fil dédié à Tarmac.
