### ISSUE TITLE
Move App to SD card

### ISSUE THREAD

**Issue by JLMontignie** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#505]
feature request related to a problem : 
attempting this authorized move, 
Kodi marix crash at startup...
I cannot post a log: "Unable to retrieve the paste URL"

**Comment by wwark** [comment]
Hi,

You mean the move to SD Card affect the plugin ?
Do you have the debug log ?

Thanks,

**Comment by JLMontignie** [comment]
Difficile d'attribuer avec certitude 
la trace suivante avec le passage à la mémoire externe SD...
Après redémarrage de pvr.iptvsimple Creating the PVR IPTV Simple add-on
, et vu la taille que prend Kodi je n'utilise de toute façon plus que le stockage externe

[service.iptv.manager] [resources.lib.modules.addon] Updating IPTV data for plugin.video.catchuptvandmore...
[service.iptv.manager] [resources.lib.modules.addon] Requesting channels from plugin://plugin.video.catchuptvandmore/resources/lib/iptvmanager/channels/...
[service.iptv.manager] [resources.lib.modules.addon] Executing RunPlugin(plugin://plugin.video.catchuptvandmore/resources/lib/iptvmanager/channels/?port=34743)
 [service.iptv.manager] [resources.lib.modules.addon] Something went wrong while calling plugin.video.catchuptvandmore: Timout waiting for reply on port 34743
ERROR <general>: [Catch-up-TV-&-More.support] [Errno 111] Connection refused
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/iptvmanager.py", line 270, in channels
                                                       IPTVManager(int(port)).send_channels()
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/iptvmanager.py", line 164, in send
                                                       sock.connect(('127.0.0.1', self.port))
                                                   ConnectionRefusedError: [Errno 111] Connection refused

PVR Manager: Stopped
ADDON: Dll Destroyed - PVR IPTV Simple Client

l'IPTV manager gère de tout façon le redémarrage du PVR Simple Client...

**Comment by wwark** [comment]
le connexion refused semble venir de plusieurs instances de IPTV Manager surement lié aux déplacement.
Il faudrait demander à iptv manager https://github.com/add-ons/service.iptv.manager/issues

Merci,
Wwark

**Comment by joaopa00** [comment]
Ce n'est pas un problème de Catchuptvandmore selon WWark. Je ferme.
Si le problème persiste aprèsque IPTV manager soit fixé,n'hésite oas à ouvrir une nouvelle issue.
