### ISSUE TITLE
Issue on France info channel 

### ISSUE THREAD

**Issue by MrPatate87** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#506]
### Describe the bug

Using catchup tv and more on kodi and iptv manager, many of my interested channel work pretty well but when i want to change it to France info, nothing happen the stream only close and left me here. 
If i use any other channel before or after all work well, only France info channel seems not working. 
I just try France tv plugin to see if this plugin have the Same problem and here this channel work great.... 
Don't know why or what i can do..... 
All other France tv channel seems to work on cachtup tv, only this one have issue for me. 

### To Reproduce

1. Open catchup tv and more (or iptv manager the issue was the same) 
2. Select France info channel 
3. Nothing happen, no stream for this channel

### Expected behavior
Only hope to have a fine stream for this channel 

### Your environment
 - Android tv on shield tv 
 - using catchup tv with iptv manager integration work very well expect for France info tv. 

 - Operating system version/name:
 - Kodi version: 18.8
 - Catch-up TV & More version: last version on this github
 - Installation method: installed with catchup tv repo

**Comment by wwark** [comment]
HI it is fixed in this ticket : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/502

**Comment by MrPatate87** [comment]
Sorry i don't see this ticket in the issues alreasy post here.
How can I install beta version ?

**Comment by popiggy** [comment]
@MrPatate87 you can upgrade to beta04 directly from CUTVM parameters. I confirm this issue is fixed with beta04

**Comment by MrPatate87** [comment]
Many Thanks for the speed reply and for this must have plugin !
