### ISSUE TITLE
Plus de dossier m3u

### ISSUE THREAD

**Issue by Almeyric** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#509]
### Describe the bug
A clear and concise description of what the bug is:
Depuis peu, le guide TV de kodi ne m'affiche plus rien.  D'ailleurs, je n'ai plus le dossier m3u dans les ressources. Malgré une réinstallation de l'extension. 

### Your environment
 - [ ] Windows 10

 - Operating system version/name: 20H2
 - Kodi version: 19
 - Catch-up TV & More version: dernière version
 - Installation method: Dépot

**Comment by daufinsyd** [comment]
Je crois que c'est lié à l'intégration d'IPTV Manager https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/494
Qui s'avère être bien moins fiable (à peu près chaque jour, je dois rafraîchir manuellement la listes des chaînes ; probablement à cause de ce bug : https://github.com/add-ons/service.iptv.manager/issues/82

**Comment by wwark** [comment]
Bonjour,

Le dossier m3u n'existe plus.
Il est remplacer par l'IPTV Manager.
https://catch-up-tv-and-more.github.io/fr/live_tv_installation/#ii-installation-de-iptv-manager

Merci,
Wwark

**Comment by sy6sy2** [comment]
Hello @Almeyric et @daufinsyd, pouvez vous nous donner la façon de reproduire ce problème svp ?

**Comment by Almeyric** [comment]
> Hello @Almeyric et @daufinsyd, pouvez vous nous donner la façon de reproduire ce problème svp ?

Bonsoir @sy6sy2,

Alors comme dis dans mon premier post, en réinstallant simplement l'extension sur Kodi Matrix, le dossier n'est plus présent. Mais sous Leia, le dossier était présent. Le guide de Kodi fonctionnait a merveille. J'ai l'impression que depuis le passage à Matrix il y a quelque bug avec plusieurs extensions, j'ai déjà eu un sacré bordel avec vstream résolu en parti...
Si besoin des logs, je peux les fournir. Je vais essayer de le reproduire dans une VM de mon labo.

Actuellement, j'ai pris une m3u en ligne mais les chaînes sont inconnus. Le lien de base n'a pas l'air d'être résolu par Kodi Matrix. Ce qui me paraît bizarre c'est que je trouve pas le plugin URL resolver....

Merci et bonne soirée

**Comment by sy6sy2** [comment]
Pour le dossier M3U qui n'est plus présent c'est normal comme le disait wwark.

Ce que je voulais dire c'est : après la configuration de IPTV Manager, comment reproduire le bug qui fait qu'il soit nécessaire de refresh manuellement.

**Comment by Almeyric** [comment]
@sy6sy2 

J'avais compris pour le dossier. ;)
Bon le problème à l'air d'être résolu. Je ne saurai dire comment... Ce que j'ai effectué, c'est une réinitialisation de la config d'IPTV par défaut, mais j'ai du le faire plusieurs fois... afin d'avoir un résultat.

Donc on peut clore le sujet. Les mystères de l'informatique...

**Comment by osmoze06** [comment]
J'ai le même soucis avec IPTV Manager, ça saute tous les jours. Obligé de faire un refresh sinon plus rien dans le client IPTV.

**Comment by Almeyric** [comment]
@osmoze06 

Je n'ai pas remarqué ce problème chez moi.

**Comment by sy6sy2** [comment]
Hello osmoze, avec quel OS? 
Je n'arrive pas à reproduire ce problème de "PVR vide".

**Comment by osmoze06** [comment]
J'utilise KODI 19 sur une clé Android Xioami MiStick.
Et de manière aléatoire, j'ai la liste de lecteur M3u8 dans le dossier addon_data de l'extension IPTVManager qui est vide.
Du coup, mon PVR est également vide.

Je sus obligé de forcer la mise a jour de la liste de chaines et du guide sur les options de l'addon et ça ne fonctionne pas toujours.

J'ai trouvé une solution de contournement en copiant la liste M3u8 lorsque celle-ci fonctionne, puis en la mettant dans un autre répertoire et lui changeant l'extension en .m3u.

J'ai du coup changer le chemin  d'accès à ma liste dans les paramètres du PVR Simple Client : Pour le moment, ça fonctionne bien ainsi.
J'ai juste constaté que le guide est parfois vide et nécessite une actualisation d'IPTVManager quand même.

Je me demande si en cas de perte de connexion Internet lorsque je lance Kodi, cela ne génère pas un bug qui m'efface tout à chaque fois...

**Comment by sy6sy2** [comment]
C'est au lancement de Kodi que tu constates que la liste des chaines est vide ?

**Comment by osmoze06** [comment]
Oui exactement. Mais je ne sais pas si c'est lié à une perte de connexion wifi car parfois mon wifi se coupe et s'il n'est pas connecté ça peut peut-être engendrer ce type de problème ?

**Comment by sy6sy2** [comment]
Je n'arrive pas du tout à reproduire ce problème sous macOS.
J'ai ouvert/fermé/ouvert Kodi de multiples fois, aves ou sans Wifi et la liste des chaines est toujours complete pour moi 😕

**Comment by osmoze06** [comment]
C'est peut-être lié à Android TV uniquement je ne sais pas car j'ai trois clé Android TV et ça me fait la même chose sur les trois télés.

C'est la liste qui m3u8 qui parfois se vide sans aucune raison particulière.

Mais pour ma part j'ai résolu le souci à la convertissant en m3u et en faissant pointer PVR vers le fichier.
Pour l'EPG, ça a l'air de tenir

**Comment by popiggy** [comment]
En effet ça semble lié à la playlist

Voici les erreurs retournées au boot:
ERROR: [service.iptv.manager] [resources.lib.modules.addon] Something went wrong while calling plugin.video.catchuptvandmore: [Errno -5] No address associated with hostname

ERROR: AddOnLog: PVR IPTV Simple Client: Unable to load channels from file '/storage/.kodi/userdata/addon_data/service.iptv.manager/playlist.m3u8': file is corrupted

**Comment by sy6sy2** [comment]
Je ferme ce ticket au profit de celui-ci: https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/507

**Comment by jordanpires449** [comment]
information nrj12
