### ISSUE TITLE
Chaine France télévision

### ISSUE THREAD

**Issue by Sky1414** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#511]
### Describe the bug
Le replay des  chaines France2 , France info , France 3... ne fonctionne plus , sur 2 postes ; mais ok pour le direct
Ok  replay et direct pour MyTf1 & M6
Je suis le seul ?

### To Reproduce
1.
2.
3.
4.

### Expected behavior
A clear and concise description of what you expected to happen:

### Actuel behavior
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: LibreELEC 9.2.6 RPi2.arm
 - Kodi version:   18.9 Leia
 - Catch-up TV & More version: Catch-UP 0.2.35 béta 04 
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by wwark** [comment]
Bonjour,

Je confirme le bug. Nous regardons pour corriger.
Merci

**Comment by wwark** [comment]
Pourriez-vous tester la dernière beta 0.2.35~beta05 ?
Une correction a été apportée.

Merci,

**Comment by enigma131** [comment]
fonctionne ici

**Comment by wwark** [comment]
Merci.
Corrigé et la release est disponible.
Le ticket est fermé.
