### ISSUE TITLE
Subtitles for STV Catch-Up 

### ISSUE THREAD

**Issue by chrissxuk** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#513]
**Is your feature request related to a problem? Please describe.**
Like many others I find it very difficult to watch TV without subtitles. I have noticed in the add-on settings that you can enable subtitles when available but no STV catch-up shows have them.

**Describe the solution you'd like**
 Subtitles for STV catch-up to be captured in the programming and and made available.

**Comment by sy6sy2** [comment]
Hi @chrissxuk,
Is it possible for you to install 0.2.36~beta03 version of the plugin and check if subtitles work for you?

You can install it manually with zip file or you can use our beta channel repo to automatically get any new beta version of the plugin (see https://catch-up-tv-and-more.github.io/installation/#ii-add-the-official-catch-up-tv--more-repository)

**Comment by chrissxuk** [comment]
Yes the subtitles are now working. Thank you very much.

**Comment by sy6sy2** [comment]
Good to know, thank you for the test!
