### ISSUE TITLE
Abonnement Replay M6

### ISSUE THREAD

**Issue by Cyberdr3am** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#514]
Bonjour, depuis peut de temps il faut un abonnement pour regarder certain replay de la chaine M6
Cependant même avec un abonnement il est impossible d'avoir accès au replay via kodi alors qu'en direct via le site cela marche sans soucis.
Pouvez-vous faire quelque chose ou m'indiquer comment faire ?
Merci

Hello, for a short time you need a subscription to watch some replay of the M6 ​​channel
However, even with a subscription it is impossible to have access to the replay via kodi while live via the site it works without worries.
Can you do something or tell me how to do it?
Thank you

**Comment by wwark** [comment]
Bonjour @Cyberdr3am,

Oui c'est suivi dans ce ticket : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/510

Je me permet de fermer ce ticket doublon !
Merci,
