### ISSUE TITLE
Replay RMC Decouverte error decoding str is not supported

### ISSUE THREAD

**Issue by nmaster2042** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#518]
### Describe the bug
error TypeError decoding str is not supported

### To Reproduce
Just try a replay of RMC Decouverte

### Expected behavior
The replay should start

### Actuel behavior
Only get the error, can't share log: Unable to retrieve the paste url

### Your environment
 - [X ] Linux

 - Operating system version/name: Ubuntu 20.10
 - Kodi version: 19.1
 - Catch-up TV & More version: 0.2.36 beta1
 - Installation method: Kodi: team-xbmc ppa, Catch UP TV And more repo
[kodi.old.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/6471932/kodi.old.log)

**Comment by enigma131** [comment]
I've just tested here, i'ts working . Linux mint 20.1 and Kodi 19.1 + Catch-up TV & More version: 0.2.36 beta1

**Comment by nmaster2042** [comment]
Finally, removing the extension + user data and installing again from official repo fixed the issue.
