### ISSUE TITLE
TV channels sorting issue

### ISSUE THREAD

**Issue by pasnox** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#519]
### Describe the bug
When moving channels order in the Kodi TV channel manager, the order is lost as soon as the IPTV manager refresh channels data.

### To Reproduce
1. Open Kodi TV channel manager
2. Move one or more channels
3. Validate
4. Go in Kodi TV channels
5. Order is lost

### Expected behavior
Order be kept

### Actuel behavior
Order is lost

### Your environment
 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 18 leia
 - Catch-up TV & More version: 0.2.35
 - Installation method: official libreelec repo

**Comment by sy6sy2** [comment]
Hi, this seems to be an issue with IPTV Manager. Can you open an issue on https://github.com/add-ons/service.iptv.manager please?

**Comment by joaopa00** [comment]
Not a Catchuptvmore bug. Closing this issue.
