### ISSUE TITLE
Erreur sur les device Android/librelec (ARM) - InputStream Adaptive: Unable to load widevine shared library (/storage/.kodi/cdm/libwidevinecdm.so) - pour tous les contenus protégés par DRM

### ISSUE THREAD

**Issue by AlarmeOrphee5** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#520]
Bonjour tout le monde,
Je vous écrit aujourd'hui car j'ai un problème avec les chaînes 6play.
Hier matin' pas de problème mais depuis le début d'après midi elles ne fonctionnent plus.
Le chargement se lance et puis rien, même pas un message d'erreur.
Pourriez vous m'aider ?

Mon matériel : 
Raspberry pi 3b+
Kodi via libreelec
Catch up tv and more

Merci d'avance.

**Comment by enigma131** [comment]
Fonctionne ici , kodi 19.1 Linux . Tu regardes depuis la France ?

**Comment by AlarmeOrphee5** [comment]
Ouais, depuis la France. J'ajoute que je n'ai plus le Replay d'aucune chaîne. Je suis sous la même version que toi.

**Comment by enigma131** [comment]
Ah oui effectivement je n'avais pas regardé les replays, toutes les chaînes du groupe HS

**Comment by AlarmeOrphee5** [comment]
Une idée d'où cela peu venir ? J'ai retenté une install toute neuve mais ça a rien donné.

**Comment by wwark** [comment]
Hello,
Je viens de tester de mon côté, j'ai pu regarder un replay de TopChef
Il faudrait les logs en mode débug suite à un cas de test. Est-ce que vous utilisez bien la dernière beta du plugin ?

MErci,

**Comment by AlarmeOrphee5** [comment]
Ha je n'en ai aucune idée je dois dire. Comment puis je te donner les logs ?

**Comment by wwark** [comment]
C'est détaillé dans ce WIKI : https://kodi.wiki/view/Log_file/Easy
Le chemin pour récupérer les logs diffère entre les OS.

MErci,

**Comment by Demgien** [comment]
Hello ! Pareil j’ai accès aux replays M6 mais pas W9 (une erreur lors de l’accès au répertoire)

**Comment by enigma131** [comment]
Zarbi ce matin cela fonctionne, même ordi mais beta mis à jour (mais à prioris rien à voir)

**Comment by AlarmeOrphee5** [comment]
Bonjour,
Voici les logs effectués ce matin. Je tiens a dire que j'ai perdu le replay de TF1 :(. 
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/6493074/kodi.log)

**Comment by Demgien** [comment]
> Zarbi ce matin cela fonctionne, même ordi mais beta mis à jour (mais à prioris rien à voir)

Visiblement, c’est revenu chez moi aussi sur xiaomi box.

**Comment by wwark** [comment]
@AlarmeOrphee5 merci pour le log.

> 2021-05-17 12:02:14.596 T:1473672064   DEBUG: AddOnLog: InputStream Adaptive: Supported URN: urn:uuid:EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED
2021-05-17 12:02:14.597 T:1473672064   DEBUG: CurlFile::Open(0x54e5ff30) https://origin-live-6play.video.bedrock.tech/6play/short/enc/m6/noscte/hdeindex.mpd
2021-05-17 12:02:14.749 T:1473672064   DEBUG: AddOnLog: InputStream Adaptive: Effective URL https://origin-live-6play.video.bedrock.tech/6play/short/enc/m6/noscte/hdeindex.mpd
2021-05-17 12:02:14.751 T:1473672064   DEBUG: AddOnLog: InputStream Adaptive: Download https://origin-live-6play.video.bedrock.tech/6play/short/enc/m6/noscte/hdeindex.mpd finished
2021-05-17 12:02:14.751 T:1473672064    INFO: AddOnLog: InputStream Adaptive: Successfully parsed .mpd file. #Periods: 1, #Streams in first period: 4, Type: live, Download speed: 0.0000 Bytes/s
2021-05-17 12:02:14.752 T:1473672064   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
2021-05-17 12:02:14.755 T:1473672064   DEBUG: Previous line repeats 1 times.
2021-05-17 12:02:14.755 T:1473672064   DEBUG: AddOnLog: InputStream Adaptive: Entering encryption section
**2021-05-17 12:02:14.758 T:1473672064   ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (/storage/.kodi/cdm/libwidevinecdm.so)**
2021-05-17 12:02:14.759 T:1473672064   ERROR: AddOnLog: InputStream Adaptive: OpenDRMSystem failed
2021-05-17 12:02:14.759 T:1473672064   DEBUG: AddOnLog: InputStream Adaptive: Session::~Session()
2021-05-17 12:02:14.760 T:1473672064   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.catchuptvandmore/resources/lib/channels/fr/6play/get_live_url/?_pickle_=80027d71012858070000006974656d5f6964710258020000006d36710355075f7469746c655f710458260000004d3620e2809420c38761207065757420766f75732061727269766572206368657a20766f75735808000000786d6c74765f696471055814000000433131382e6170692e74656c6572616d612e66727106752e]
2021-05-17 12:02:14.760 T:1473672064  NOTICE: CVideoPlayer::OnExit()
2021-05-17 12:02:14.764 T:1473672064   DEBUG: AddOnLog: InputStream Ada

Le souci est suvi par ce ticket : https://github.com/xbmc/inputstream.adaptive/issues/678
Ce point touche tous les devices de google et tous les contenus protégés par DRM.
La team inputstream.Adaptive travaille sur ce sujet.

**Comment by AlarmeOrphee5** [comment]
Ha merci pour ces infos utiles. Donc concrètement, aucun moyen de contournement ?
Il faut juste patienter que l'équip fasse son oeuvre.

**Comment by wwark** [comment]
en gros la lib (inputstream.adaptive) permettant la lecture des DRM ne veut pas se charger pour les cas listés ...
The impact is huge for Kodi ...

**Comment by AlarmeOrphee5** [comment]
Ha ba merci. Il n'existe pâs d'autres librairies ? (désolé j'y connais rien)

**Comment by wwark** [comment]
C'est la seule pour Kodi ...

**Comment by AlarmeOrphee5** [comment]
Ok, bon je vais me tenir informé par lelien que tu m'a envoyé. 
Merci encore a tous.

**Comment by chamchenko** [comment]
Réellement c'est un problème de la libwidevine, bibliothèque que inputstream adaptive utilise pour décrypter les contenus drm, pour les systèmes arm cette bibliothèque est récupérée par inputstream helper à partir des images system de chromebook, précisément sur la dernière version google ont fait des changements du coup ça ne marche plus, l'équipe inputstream a déjà suggéré un fix au équipe libreelec et coreelec. mais en attendant vous pouvez retrouver les contenus drm sur kodi en allant sur les paramètres du plugin inputstream helper choisissez la dernière option sur les paramètres restaurer la bibliothèque widevine cdm, puis choisissez une ancienne version et ça refonctionnera

**Comment by AlarmeOrphee5** [comment]
Ha cool, je vais essayer ca merci :)

**Comment by chamchenko** [comment]
PS: pour pouvoir restaurer à une ancienne version, il faut que cette version soit déjà installé précédemment ( par défaut inputstream helper garde 4 sauvegardes d'anciennes version) en gros cela veut dire que cette méthode ne marchera pas si c'est une nouvelle install car évidemment cela veut dire que vous n'avez pas de sauvegarde de l'ancienne libwidevine

**Comment by AlarmeOrphee5** [comment]
J'ai une install du mois de décembre, ca devrait aller

**Comment by chamchenko** [comment]
Oui ça devrait aller la nouvelle version qui a tout mis en désordre date de moins qu'une semaine

**Comment by AlarmeOrphee5** [comment]
Bonsoir,
après ta manip et 2 jours d'essais c'est nickel pour moi. 
J'ai fait une copie de la sd au cas ou.

**Comment by chamchenko** [comment]
C'est pas vraiment nécessaire selon [ce](https://github.com/xbmc/inputstream.adaptive/issues/678#issuecomment-837298366) message les anciennes version seront obsolete à partir de 31 mai.
Sinon pour coreelec le fix est déjà appliqué dans [ce](https://github.com/CoreELEC/CoreELEC/pull/287)  PR donc je pense que ça va être dans la version suivante.
L'équipe libreelec n'est pas à 100% convaincu par la solution proposé, mais ils dise qu'il vont quand même faire une version qui l'applique pour libreelec 9.2 et pour libreelec 10 , vous pouvez le constaté sur [ce](https://github.com/LibreELEC/LibreELEC.tv/pull/5376#issuecomment-841886593) message

**Comment by AlarmeOrphee5** [comment]
Ha ba merci, ben attendons la mise à jour. Espérons qu'elle sera la avant la fin du mois.

**Comment by peno64** [comment]
https://libreelec.tv/2021/05/le-9-2-7-10b4-fix-widevine/

**Comment by sy6sy2** [comment]
https://libreelec.tv/2021/07/18/le-9-2-fix-2-for-widevine/
