### ISSUE TITLE
Channel not display after update

### ISSUE THREAD

**Issue by Che-debarras** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#521]
### Describe the bug

Again each update brings more bugs lol, since weeks, each time i update the addol the channels list disappeared.
Using Iptv manager for refreshing or iptv simple to config automatically as suggested in github doesn't work

Android 
Kodi 18.9
Addon version 0.2.36 beta 3

**Comment by Psychoses** [comment]
Hi, It's in progress here https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/507

**Comment by wwark** [comment]
Thank you @Psychoses I will close this ticket.
This issue is followed on the 507.
