### ISSUE TITLE
Bugs de maj Encore !!!!

### ISSUE THREAD

**Issue by Che-debarras** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#524]
### Describe the bug

C'est toujours amusant de voir que chacune de vos mises à jour n'apportent aucune nouveauté de fonction ou de chaine tv mais toujours les mêmes bugs.

Pourquoi ne pas tester vos changements avant de les publier ?

Donc les mêmes bugs reviennent:

Replay Rts impossible à s'ouvrir : list index out of range
Replay Noovi impossible à s'ouvrir : runtimeError
Disparition des chaines intégrées à iptv kodi 

Je suis curieux de voir le changelog de vos mises jours qui n'apportent que bugs à répétition et aucune nouveautés (pas de chaine Libanaise, algerienne, d'ailleurs les chaines maroc ne fonctionne pas m. testez votre addon avant de publier une maj)

**Comment by sy6sy2** [comment]
Hello,

> Pourquoi ne pas tester vos changements avant de les publier ?

Nous essayons de tester le plugin autant que possible avant une release (il y a beaucoup de chaines donc difficile de tout faire).
Par contre on ne vérifie pas forcément tout après la sortie d'une nouvelle bêta (c'est le risque d'utiliser une version beta, comme pour n'importe quel logiciel...).

> Je suis curieux de voir le changelog de vos mises jours qui n'apportent que bugs à répétition et aucune nouveautés

Le changelog est toujours présent dans le fichier `addon.xml` dans la balise `news`. Pour plus de détails il faut regarder les commit sur la branche `dev`.

Je vais encore une fois de plus me répéter :

* Ce projet est open source, donc si ça n'avance pas assez vite à votre gout pour l'ajout de nouvelles chaines ou la résolution du bug nous acceptons de l'aide avec plaisir (les pulls request sont là pour ça).
* Aussi étonnant que ça puisse paraître nous avons une vraie vie et un vrai métier à coté du plugin donc il nous est impossible de dédier 100% de notre temps à CUTv&M.

Ce projet est un un passe temps, un moment de détente ou encore de plaisir ou nous souhaiterions que ça le reste. Malheureusement, quand on reçoit un nouveau mail avec pour objet `Bugs de maj Encore !!!!` (je pense qu'il n'y a pas assez de points d'exclamation d'ailleurs) la motivation et l'envie d'aider les utilisateurs laisse place à la frustration et à l'envie de tout laisser tomber.
N'oubliez pas qu'il ne s'agit pas d'un service, vous n'avez rien payé. Si vous souhaitez une qualité de service je vous invite à prendre un abonnement Molotov, Salto, Canal ou autre.

**Comment by Che-debarras** [comment]
Clore le sujet cela montre que vous n'êtes pas disposé à écouter les retours.

Et malheureusement vous devez vérifier chaque chaines chaque replay chaque fonction avant de publier une maj surtout que la c'est des toujours les mêmes bugs qui reviennent.

Une maj est la pour corriger des bugs pas en créer ou faire apparaître les anciens bugs.

La version master est pire que la beta  et les bugs sont toujours les mêmes que la bêta donc l'excuse que c'est une beta est pas crédible 

De même que l'excuse d'être open source, si vous n'êtes pas capable d'éviter le retour des anciens bugs ou de les verifier ou alors ne dites pas aux autres de le faire soi-même. 

C'est votre addon ne fait pas 2 fois plus de travail pour rien car vos maj n'apportent que des bugs deja connus et a vous de vous assurez qu'ils ont été corrigés avant de les publier.

Ca rime a quoi de faire une maj qui n'apportent rien a part des bugs connus piur ensuite vous les signaler pour les corriger et une fois corrigé on aura le retour de ces bugs dans une autee maj inutile 

On appelle ça du travail bâclé en allant trop vite.
Faut mieux prendre son temps et vérifier chaque chaine chaque replay et une fois listé les bugs vous les corriger et la vous n'aurez plus de retour de bugs.

On peut attendre 1 mois voire plus pour avoir un addon sans bugs à répétition donc ce n'est pas le temps qui manque donc l'excuse d'une vie à coté n'est pas crédible car vous avez tous le temps qu'il faut

Bref pour conclure si vous arrivez à vous detendre en developpant des bugs successifs sur votre addon, si vous avez du plaisir a travailler sur un addon qui n'apportent rien de fonctionnelle ni de nouveauté alors c'est que votre motivation n'est pas d'aider les utilisateurs. 

Ce n'est pas parce que votre addon est gratuit que cela est une raison pour qu'il soit non utilisable. Et je vous invite a laisser tomber car ce n'est pas ma première fois que je vous le dit, votre addon pose plus de problèmes.

A certain moment on prend son courage à 2 mains pour abandonner ce projet qui mène à rien surtout si vous n'êtes pas motivé pour résoudre les bugs de façon serieux et consciencieux.

Je pense que vous bâclez votre addon et que vous dites si l'utilisateur est pas content c'est pareil au même. 

Vous avez 2 choix,  soit prendre votre temps pour vérifier votre addon dans sa totalité avant de publier une maj qui va vous demander encore plus de temps soit abandonner cette addon car c'est sans fin 

NB:a quoi bon mettre autant de chaine et replay si cela ne fonctionne pas? Mettez en peu qui fonctionne et ajouter 1 a la fois en s assurant que les précédents sont toujours fonctionnels 
Solution : retirez tous ce qui marche pas et ajouter un replay, une chaine fonctionnelle à la fois, si la chaine ou le replay ne marche pas , ne pas l'ajouter.
Mais mettre autant de chaine et replay hs  normal que cela demande du temps a corriger.
C'est comme laisser les mauvaises herbes poussaient,  a force de se multiplier cela demandera un temps fou pour tout supprimer. 

Sur ce vous me faite pensez a Don Quichotte, vous acharnez sur une chose imaginaire qui n'existe pas (un addon TV multichannels et de replay )

**Comment by Che-debarras** [comment]
J'oubliais,  ya des addons bien fait qui affiches ces chaines tv gratuites et meme des applications gratuite pour ces mêmes chaines tv.
Je rappelle que vos chaines sont des chaines tnt gratuites donc on parle pas d'abonnement mais d'inscriptions.
