### ISSUE TITLE
La Une/Tipik/La Trois sometimes down sometimes not

### ISSUE THREAD

**Issue by dur3x** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#526]
### Describe the bug
Since one week I have some problems to read La Une/Tipik/La Trois (direct), sometimes the content loads sometimes not.
I have the feeling that can depend on the content they are "showing". For example right now, when it's Roland-Garros I have troubles but when it will be the "JT" it will be ok. 

### To Reproduce
Just try these three programs and with chance you will get the same error (not really error but nothing happens)

### Expected behavior
Loading of the program

### Actuel behavior
nothing happens

### Your environment
 - [X] Android
 - [X] OSX
 
 - Kodi version: 19.1
 - Catch-up TV & More version: 0.2.35

### Debug log
see attached file

[tipik_nok.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/6603936/tipik_nok.log)

**Comment by dur3x** [comment]
Je me demande si c'est pas la même merde que dans cette issue:
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/520

En gros depuis je dirais quasi une semaine j'ai des soucis de lecture (aussi bien sur mon mac que sur l'android tv) et j'ai l'impression que c'est au moment du load du DRM et qu'en fonction du contenu (même chaîne mais contenu différent) cela fonctionne ou non.

**Comment by sy6sy2** [comment]
Hello !
Hum, @wwark a plus suivi le sujet que moi, mais il me semble que #520 c'est seulement pour les devices Android/ARM donc macOS ne devrait pas être affecté.

Je vais essayer de regarder un peu mais wwark est le spécialiste DRM ici 😛

**Comment by alexbelgium** [comment]
Même observation (juste pour la une/tipik/trois) , sur libreelec installé sur un NUC Intel x64.

**Comment by wwark** [comment]
Hello,

Il faudrait les logs en mode debug de Kodi pour comprendre si c'est lié à inputstream.adaptive ou non.
Quand le soucis arrivent avez-vous le même soucis sur le site web de la chaine ?

Merci,
Wwark

**Comment by rbagd** [comment]
Bonjour,

Je crois que j'ai le même problème. Voici les logs en debug:

[auvio-error.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/6642233/auvio-error.log)

Il semble que le problème est indiqué ici

```
2021-06-12 15:13:00.896 T:140299349772032   ERROR: ffmpeg[7F99FCE7C700]: [hls,applehttp] SAMPLE-AES encryption is not supported yet
```

J'ai exactement la même chose avec l'application Auvio pour Kodi aussi. Sur le web, par contre, il n'y a pas de soucis.

**Comment by alexbelgium** [comment]
"J'ai exactement la même chose avec l'application Auvio pour Kodi aussi. Sur le web, par contre, il n'y a pas de soucis."

Exactement la même observation. Je rajouterais aussi mes log debug ce soir

**Comment by alexbelgium** [comment]
Pour se connecter au site il faut avoir un nom et mot de passe. Je me demande si le soucis n'est pas que l'addon n'inclus pas l'auth dans sa forme actuelle pour la rtbf... (ces 3 chaînes)

**Comment by wwark** [comment]
@rbagd Cette erreur indique que ce type de DRM n'est pas supporté par Kodi. Est-ce que tu as eu le soucis durant Roland Garros ? Est-ce que ça marche des fois comme l'indique @dur3x chez vous ?

@alexbelgium votre soucis est différent. De votre côté, vous avez une erreur qui indique le flux est non authorisé pour vous ? Est-ce que les lives fonctionnent de temps en temps comme décrit par @dur3x si ce n'est pas le cas vous devez avoir une configuration dans votre kodi (proxy, vpn) qui fait que le serveur de RTBF refuse la connexion.

Je vais essayer de regarder RTBF durant la période de Roland Garros pour voir si on voit quelques choses.

**Comment by rbagd** [comment]
@wwark, en effet, c'est fonctionnel pour certain type d'émissions mais problématique pour le RG ou encore l'Euro 2020. Pas impossible que la RTBF aient mis à jour leur DRM dernièrement...

Par exemple, je viens de lancer correctement un film sur La Trois 

```
2021-06-13 17:37:58.479 T:3145     INFO <general>: ffmpeg[0x55b350675480X]: [hls] Opening 'https://www.rtbf.be/api/drm/aeskey?stream_name=latrois' for reading
2021-06-13 17:37:58.666 T:3145     INFO <general>: ffmpeg[0x55b350675480X]: [hls] Opening 'crypto+https://rtbf-live.fl.freecaster.net/live/rtbf/geo/drm/latrois_aes-audio_vf=128000-video=499968-202949832.ts' for reading
```

J'en ai profité pour tester si c'est pas lié au Kodi 18 mais même suite à une mise à jour vers Kodi 19.1, ça n'a pas changé. Quant à la version `ffmpeg`, j'ai ceci

```
ffmpeg version 4.4 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10 (Debian 10.2.1-6)
```

**Comment by alexbelgium** [comment]
@wwark bonjour, merci en effet j'avais deux soucis en parallèle. Je confirme comme les autres observateurs : vers midi la une et tipik fonctionnaient pour des programmes comme le JT ou "le grand cactus". Par contre, même message d'erreur que citait dur3x: "SAMPLE-AES encryption is not supported yet" lorsque j'ai essayé de me connecter à RG ou aux matchs euro. Sur la même machine, chrome se connecte sans soucis (via un addon de libreelec). 

Bonne soirée

[kodi2.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/6644451/kodi2.log)

**Comment by nirolfa** [comment]
plus aucune chaine auvio / rtbf ne marche pour le live tv depuis qq jours :(
par contre les replay ca fonctionne encore 
sous kodi 18.9 / libreelec

2021-06-21 17:16:43.202 T:1937235984  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/All channels/pvr.iptvsimple_1067990925.pvr
2021-06-21 17:16:43.205 T:1690223488  NOTICE: Creating InputStream
2021-06-21 17:16:43.496 T:1690223488  NOTICE: Creating Demuxer
2021-06-21 17:17:14.317 T:1690223488   ERROR: OpenDemuxStream - Error creating demuxer
2021-06-21 17:17:14.317 T:1690223488  NOTICE: CVideoPlayer::OnExit()
2021-06-21 17:17:14.443 T:1937235984  NOTICE: CVideoPlayer::CloseFile()
2021-06-21 17:17:14.444 T:1937235984  NOTICE: VideoPlayer: waiting for threads to exit
2021-06-21 17:17:14.444 T:1937235984  NOTICE: VideoPlayer: finished waiting

**Comment by nirolfa** [comment]
j'ai récupéré qq infos depuis browser

urls : 
--------------
https://rtbf-live.fl.freecaster.net/live/rtbf/geo/drm/ladeux_drm/dash/ladeux_drm-audio_vf=128000-71631153270559.dash
https://rtbf-live.fl.freecaster.net/live/rtbf/geo/drm/ladeux_drm.mpd

https://wv-keyos.licensekeyserver.com/


contenu du mpd
----------------------
 <Period id="1" start="PT0S">
    <BaseURL>ladeux_drm/dash/</BaseURL>
    <EventStream schemeIdUri="urn:scte:scte35:2014:xml+bin" timescale="10000000">
      
      <Event presentationTime="16242897381200000" duration="484400000" id="3142565065">
        <Signal xmlns="http://www.scte.org/schemas/35/2016">
          <Binary>/DAlAAAAAA4QAP/wFAUBlNwhf+//+yBRUP4AQoWwAAEBAQAAg5YLDg==</Binary>
        </Signal>
      </Event>
    </EventStream>
    <AdaptationSet id="2" group="1" contentType="audio" lang="fr" segmentAlignment="true" audioSamplingRate="44100" mimeType="audio/mp4" codecs="mp4a.40.2" startWithSAP="1">
      <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
      
      <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="8EB7987C-E8D5-E347-4162-594C513BB79C"/>
      
      <ContentProtection schemeIdUri="urn:uuid:9A04F079-9840-4286-AB92-E65BE0885F95" value="MSPR 2.0"/>
      
      <ContentProtection schemeIdUri="urn:uuid:EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED"/>
      <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
      <SegmentTemplate timescale="44100" initialization="ladeux_drm-$RepresentationID$.dash" media="ladeux_drm-$RepresentationID$-$Time$.dash">

**Comment by alexbelgium** [comment]
> @alexbelgium c est quoi ton addon chrome pour librelec ?

Hello,
Tu peux le trouver en recherche addons depuis librelec. Il est dans les repositories par défaut. c'est juste assez complexe d'arriver à avoir le son, il faut encoder manuellement les paramètres sons dans la config (voir https://forum.libreelec.tv/thread/12879-google-chrome-addon-no-audio/?pageNo=2)

Au final, je déconnecte ma clé usb libreelec de mon NUC, boot en win10 et regarde depuis chrome... On peut dire ce qu'on veut, win10 reste quand même une solution backup tres utile pour moi...

Bonne soirée

**Comment by nirolfa** [comment]
petit update, certains jours  après 6 ou plus d'essais , ça finit par marcher
(pas toujours)

**Comment by alexbelgium** [comment]
It's really too bad it doesn't work, I really loved this addon... For other people how do you manage without this addon? Do you have installed a physical tuner?

**Comment by dur3x** [comment]
any news?

**Comment by alexbelgium** [comment]
Even if it is not merged (as the PR seems a bit old), you can install his forked addon, download the code, and update it manually from the zip file

**Comment by sy6sy2** [comment]
Fixed by #536

**Comment by stemy2** [comment]
> Fixed by [#536](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/pull/536)

Nope, it's absolutly not fixed, it still happening to me right now.
