### ISSUE TITLE
Le plugin fonctionne-t-il sur libreELEC ? sur RPI 3B+ il semble ne pas fonctionner :(

### ISSUE THREAD

**Issue by Maumtiesse** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#53]
Bonjour,
je viens d'installer le plugin, mais il semble ne pas fonctionner.
voici le log file de kodi.
Cependant, j'ai aussi des problèmes avec youtube plugin,...
Si un specialist pouvait nous aider ?!
[log libreelec.txt](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/1866212/log.libreelec.txt)

Merciii !!

**Comment by Maumtiesse** [comment]
I changed my advancedsetting file to improve buffer issue, but it doesn't fix it.
here's my new log
https://pastebin.com/5qNeGxQW

**Comment by wwark** [comment]
Bonjour,
Je confirme que le plugin fonctionne sur libreelec/OSMC et aussi surement sur le raspeberry PI 3B+. J'utilise OSMC de mon côté.

Le log indique que la vidéo remonte un HTTP 403 (non autorisé) pour une vidéo de M6.  J'ai testé une vidéo de l'émission de la vidéo remontant un HTTP 403 et je n'ai pas eu de soucis. Pouvez-vous donner le titre de l'épisode remontant l'erreur ?

Le HTTP 403 peut être remontée dans le cas où vous êtes hors de la France par exemple.

Le 3B+ est sorti il y a peu de temps. Il faudrait surement aussi utiliser les dernières versions de développement de libreelec pour avoir un meilleur support.

Est-ce que vous avez des erreurs avec d'autres plugin ? Est-ce que cette même vidéo est lisible sur libreelec avec un RPI 3 de votre côté ?

Wwark

**Comment by Maumtiesse** [comment]
1) le titre de l'épisode de la série Les Reines du Shopping : séduisante pour une photo de profil sur un site de rencontre. épisode du 26/03/2018 durée +/- 55 min.
3) Si je suis en Belgique, dois-je envisager l'utilisation d'un vpn pour visualiser une video de m6 par exemple ? (pour info, m6 n'est pas diffusée en Belgique)
2) libreELEC 8.2.4 (dernière version stable)
3) J'ai quelques soucis avec youtube. Mais je sais aussi qu'il y a pas mal de modif sur les ayants droit de visionnage (UE) sur les plateformes streaming pour le moment...

**Comment by wwark** [comment]
1 - testé fonctionne correctement en France
2 - Oui les live tv et replay peuvent être géolocalisé comme le cas de M6 il faut être sur le sol Français pour les lire ou utiliser un VPN.
3 - Je crois qu'il y a une version développement à voir si ça permet d'avoir un meilleur support.
4 - Sûrement ...
5 - pas de problème le 403 est lié à voter localisation en belgique.

Si mes réponses sont ok pour vous je vous laisse fermer ce ticket de support :)

**Comment by Maumtiesse** [comment]
Je confirme, grâce au vpn je peux visionner les émissions françaises
Fonctionne très bien sur RPI 3B+ avec libreELEC 8.2.4.
