### ISSUE TITLE
TV5Monde Replay Error

### ISSUE THREAD

**Issue by Rvhalewyn** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#530]
### Describe the bug
A clear and concise description of what the bug is: any programme: Error : List indices must be integers, not unicode 

### To Reproduce
1.Go to  Replay,International, TV5Monde, Toutes les vidéos 

### Expected behavior
A clear and concise description of what you expected to happen:
Program should play
### Actuel behavior
Tell us what happens instead:
Error message: List indices must be integers
### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 -  X Other - LibreELEC

 - Operating system version/name:
 - Kodi version: 18.9
 - Catch-up TV & More version: 0.2.36
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by sy6sy2** [comment]
Thank you for the issue and sorry for the delay. Should be fixed in 0.2.36~beta14
