### ISSUE TITLE
RMC BFM Play

### ISSUE THREAD

**Issue by Europe57** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#531]
### Content description

* Name: RMC BFM Play
* Type [e.g. TV channel, Catch-up TV, Website, Radio]: Catch-up TV
* Website URL: https://www.rmcbfmplay.com/
* Content language/country: Français/France

### Content access

- [x] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [ ] This content is geographically restricted

### More information

If you want to add more information, put it here: Nouveau sérvice de replay d'Altice qui comprend BFM, RMC Story, RMC Découverte, 01net TV. Des exclu avant diffusion et des programmes inédit en clair comme certaine émission de l'ancienne chaîne myCuisine (Masterchef, Les pires pâtissier...)

**Comment by melanie-30** [comment]
Même problème ici avec le plugin en version bêta.
BFM fonctionne en revanche.
Mais RMC impossible de voir le direct et idem avec les replays.
Il faut désormais un compte sur RMC pour pouvoir regarder les replays, à l'instar de M6.

**Comment by sy6sy2** [comment]
Hello !
Merci pour l'info, nous allons voir pour ajouter ce nouveau service à l'instar de 6play et myTF1 mais également retirer les dossiers qui ne sont plus valables comme BFM.

**Comment by sy6sy2** [comment]
WIP ici : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/tree/rmcbfmplay

**Comment by Tethias** [comment]
Hello @sy6sy2 ,
J'aimerai traité avec toi un autre sujet "issue" que j'ai posté pour ne pas différé à celui-ci que j'ai ouvert ici:
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/533#issue-936255844

J'ai aussi l'envoyé un email à: (catch.up.tv.and.more@gmail.com)

Je suis dispo tous les jours en attente de ton retour ;-)

**Comment by theoden11** [comment]
Je confirme pour RMC en direct (chaines TNT 23 et 24) mais cela fait déjà un bon moment qu'il y a un message d'erreur à la sélection d'un programme du guide. Je n'osais pas démarrer un nouveau ticket car il y a souvent redondance et je pensais que quelqu'un l'avait déjà fait. Je regarde peu la tv mais il y a des émissions intéressantes sur RMC que je ne peux plus regarder via le plugin, et ce sur mes 3 systèmes Kodi (Windows, linux et OSMC sur Raspberry).

**Comment by sy6sy2** [comment]
Hello tout le monde,
J'ai la navigation qui est quasi fonctionnelle (pas testé tous les cas mais j'arrive à accéder à BFM --> emissions --> Bourdon).
Par contre je bloque sur la lecture des vidéos à cause du DRM ...
Je me tape ça :

```
2021-07-14 17:33:57.101 T:2379459   ERROR <general>: CCurlFile::Open failed with code 412 for https://ws-backendtv.sfr.fr/asgard-drm-widevine/public/licence:
                                                   {"status":"KO","errorCode":"ASGWV0090","errorDetails":"INVALID_LICENSE_CHALLENGE - null"}
2021-07-14 17:33:57.101 T:2379459   ERROR <general>: AddOnLog: inputstream.adaptive: License server returned failure
2021-07-14 17:33:57.101 T:2379459   ERROR <general>: AddOnLog: inputstream.adaptive: License update not successful (no keys)
```

Si tu veux y regarder @wwark, je peux te fournir les traces s'il faut. Le WIP est ici :
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/17b7112b43a84b6c9ddcb9ab95afb47382b7953b/resources/lib/channels/fr/rmcbfmplay.py

**Comment by Arias800** [comment]
Le site a été ajouter, dans la branche dev.
Presque tous les menus fonctionne.
Il reste juste quelques petites choses à faire :

- [ ] Le support des podcasts héberger sur Spotify (les autres marchent).
- [ ] L'accès aux chaines en direct.
- [ ] La recherche.

**Comment by joaopa00** [comment]
Pour faciliter la gestion des rapports de bug (eviter les métabug style: je veux que Catchuptvmore fonctionne !! :D :D) , il est préférable d'ouvrir un rapport par problème. Si tu le souhaites, tu peux ouvrir un rapport pour les podcasts et un pour la recherche. Je fais fermer ce rapport.
