### ISSUE TITLE
France Television la 1ère

### ISSUE THREAD

**Issue by Tethias** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#533]
### Content description

* Name:  France Television
* Type: Live TV (DOM-TOM)
* Website URL: https://la1ere.francetvinfo.fr/
* Content language/country: FR

### Content access

- [ ] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [X] This content is geographically restricted

### More information

Je vous ai envoyé un e-mail à votre gmail (catch.up.tv.and.more@gmail.com)
@sy6sy2 @wwark avec plus de détails mais je résume ci-dessous

Voici les informations pour la restrictions quand on choisis depuis le site:
https://la1ere.francetvinfo.fr/
> Reunion
> Ensuite allez sur l'icone TV 
> Puis sur le bouton Direct TV (qui ouvrira un nouvelle onglet)
> Et la la restriction :/

**Voici mon analyse:**
https://player.webservices.francetelevisions.fr/v1/videos/19b91b27-d508-4597-a1dd-b8b920309785?country_code=FR&w=600&h=338&player_version=5.51.25&domain=la1ere.francetvinfo.fr&device_type=desktop&browser=firefox&browser_version=89&os=windows&os_version=10.0&gmt=+0200

Bien sûr en modifiant par: le code des pays (MQ,GP, WF,etc...) de la capture ci-dessous, l'API laisse passer mais comment rejouer la requête pour y accéder et récupérer le M3U8 etc..
Autre piste il y cette requête qui lui donne le code pays via ce résultat JSON:

https://geoftv-a.akamaihd.net/ws/edgescape.json

Je reste disponible en PV ou par email pour plus de détails.

**Comment by joaopa00** [comment]
Outrepasser une restriction géographique est malheureusement illégal. Je me vois dans l'obligation de clore ce rapport.
Désolé.
