### ISSUE TITLE
Toujours les mêmes problèmes à chaque maj 

### ISSUE THREAD

**Issue by Che-debarras** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#537]
Les dossiers replay ne s'ouvrent pas
Ex le replay suisse comme  RTS  
Ex le replay canada comme Noovo
Etc...

L'intégration a kodi live tv qui disparait 
L'outil iptv manager n'intègre pas les chaines.

Bref pourquoi vous ne testez pas votre addon avant de publier une maj
Et surtout pourquoi vous ne corriger pas les fonctions de bases de votre addon
Comme le direct et le replay.

Mettre des tas de chaines qui ne fonctionnent ni en direct ni en replay  , je ne vois pas l'utilité.
La liste de bugs s'allongent et se répète à chaque fois.

Faite un effort svp pour corriger les bugs  qui vous sont signalé et une vérification regulier des chaines vous ferez pas de mal

Addon complètement inutilisable.

**Comment by michaelarnauts** [comment]
@Che-debarras This isn't the right attitude to report a bug. I can understand frustration when something doesn't work, but remember that these Addons are a hobby-projects that are being worked on in free time. Don't spoil the fun!

**Comment by sy6sy2** [comment]
Sorry @Che-debarras, but this time I blocked you.
I am tired of your comments about what we should or should not do.
