### ISSUE TITLE
Replay M6 et W9 ne fonctionne pas

### ISSUE THREAD

**Issue by HpNoTiQ56** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#54]
Bonjour,
Je vous contacte car je suis actuellement en voyage et j'ai installé KODI (leia dernière night) sur mon PC.
Après installation de CatchupTV, j'ai accès aux replays de certaines chaines mais W9 et M6 ne fonctionnent pas malgré l'activation de RMTP input et inputstream adaptive.
Le fichier log n'est pas clair 👍 `19:02:01.999 T:7836 WARNING: plugin.video.catchuptvandmore [v.0.1.4]: Deprecation warning: Plugin category is no longer set via Plugin.run(). Use "category" parameter of Plugin.create_listing() instead.
19:02:03.157 T:7836   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\Am\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\addon.py", line 335, in <module>
                                                common.PLUGIN.run(window_title)
                                              File "C:\Users\Am\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\simpleplugin.py", line 1041, in run
                                                result = action_callable(params)
                                              File "C:\Users\Am\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\addon.py", line 260, in channel_entry
                                                return channel.channel_entry(params)
                                              File "C:\Users\Am\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\channels/fr/groupecanal.py", line 97, in channel_entry
                                                return list_live(params)
                                              File "C:\Users\Am\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\simpleplugin.py", line 684, in inner_wrapper
                                                return self._get_cached_data(cache, func, duration, *args, **kwargs)
                                              File "C:\Users\Am\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\simpleplugin.py", line 636, in _get_cached_data
                                                data = func(*args, **kwargs)
                                              File "C:\Users\Am\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\channels/fr/groupecanal.py", line 684, in list_live
                                                CHANNEL_NAME_CATALOG[params.channel_name], video_id_re[0]),
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
19:02:03.214 T:8272   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/?action=channel_entry&category=CPLUS%20Live%20TV&next=live_cat&window_title=CPLUS%20Live%20TV
19:02:03.215 T:8272   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/?action=channel_entry&category=CPLUS%20Live%20TV&next=live_cat&window_title=CPLUS%20Live%20TV) failed
19:02:04.376 T:6372  NOTICE: script.module.youtube.dl: youtube_dl core version: 2018.03.20
19:02:04.399 T:6372   ERROR: C:\Users\Am\AppData\Roaming\Kodi\addons\script.module.youtube.dl\lib\YDStreamExtractor.py:453: UserWarning: External use of disableDASHVideo() is deprecated. It is now handled by module settings
                                              warnings.warn("External use of disableDASHVideo() is deprecated. It is now handled by module settings")
19:02:04.406 T:6372 WARNING: plugin.video.catchuptvandmore [v.0.1.4]: Deprecation warning: Plugin category is no longer set via Plugin.run(). Use "category" parameter of Plugin.create_listing() instead.
19:02:07.081 T:9716  NOTICE: script.module.youtube.dl: youtube_dl core version: 2018.03.20
19:02:07.106 T:9716   ERROR: C:\Users\Am\AppData\Roaming\Kodi\addons\script.module.youtube.dl\lib\YDStreamExtractor.py:453: UserWarning: External use of disableDASHVideo() is deprecated. It is now handled by module settings
                                              warnings.warn("External use of disableDASHVideo() is deprecated. It is now handled by module settings")
19:02:07.111 T:9716 WARNING: plugin.video.catchuptvandmore [v.0.1.4]: Deprecation warning: Plugin category is no longer set via Plugin.run(). Use "category" parameter of Plugin.create_listing() instead.
19:02:10.786 T:7956  NOTICE: script.module.youtube.dl: youtube_dl core version: 2018.03.20
19:02:10.813 T:7956   ERROR: C:\Users\Am\AppData\Roaming\Kodi\addons\script.module.youtube.dl\lib\YDStreamExtractor.py:453: UserWarning: External use of disableDASHVideo() is deprecated. It is now handled by module settings
                                              warnings.warn("External use of disableDASHVideo() is deprecated. It is now handled by module settings")
19:02:10.817 T:7956 WARNING: plugin.video.catchuptvandmore [v.0.1.4]: Deprecation warning: Plugin category is no longer set via Plugin.run(). Use "category" parameter of Plugin.create_listing() instead.
19:02:14.253 T:10136  NOTICE: script.module.youtube.dl: youtube_dl core version: 2018.03.20
19:02:14.281 T:10136   ERROR: C:\Users\Am\AppData\Roaming\Kodi\addons\script.module.youtube.dl\lib\YDStreamExtractor.py:453: UserWarning: External use of disableDASHVideo() is deprecated. It is now handled by module settings
                                              warnings.warn("External use of disableDASHVideo() is deprecated. It is now handled by module settings")
19:02:14.285 T:10136 WARNING: plugin.video.catchuptvandmore [v.0.1.4]: Deprecation warning: Plugin category is no longer set via Plugin.run(). Use "category" parameter of Plugin.create_listing() instead.
19:02:17.952 T:10208  NOTICE: script.module.youtube.dl: youtube_dl core version: 2018.03.20
19:02:17.978 T:10208   ERROR: C:\Users\Am\AppData\Roaming\Kodi\addons\script.module.youtube.dl\lib\YDStreamExtractor.py:453: UserWarning: External use of disableDASHVideo() is deprecated. It is now handled by module settings
                                              warnings.warn("External use of disableDASHVideo() is deprecated. It is now handled by module settings")
19:02:17.986 T:10208 WARNING: plugin.video.catchuptvandmore [v.0.1.4]: Deprecation warning: Plugin category is no longer set via Plugin.run(). Use "category" parameter of Plugin.create_listing() instead.
19:02:21.360 T:2980  NOTICE: script.module.youtube.dl: youtube_dl core version: 2018.03.20
19:02:21.384 T:2980   ERROR: C:\Users\Am\AppData\Roaming\Kodi\addons\script.module.youtube.dl\lib\YDStreamExtractor.py:453: UserWarning: External use of disableDASHVideo() is deprecated. It is now handled by module settings
                                              warnings.warn("External use of disableDASHVideo() is deprecated. It is now handled by module settings")
19:02:21.391 T:2980 WARNING: plugin.video.catchuptvandmore [v.0.1.4]: Deprecation warning: Plugin category is no longer set via Plugin.run(). Use "category" parameter of Plugin.create_listing() instead.
19:02:24.019 T:10640  NOTICE: script.module.youtube.dl: youtube_dl core version: 2018.03.20
19:02:24.046 T:10640   ERROR: C:\Users\Am\AppData\Roaming\Kodi\addons\script.module.youtube.dl\lib\YDStreamExtractor.py:453: UserWarning: External use of disableDASHVideo() is deprecated. It is now handled by module settings
                                              warnings.warn("External use of disableDASHVideo() is deprecated. It is now handled by module settings")
19:02:24.050 T:10640 WARNING: plugin.video.catchuptvandmore [v.0.1.4]: Deprecation warning: Plugin category is no longer set via Plugin.run(). Use "category" parameter of Plugin.create_listing() instead.
19:02:25.856 T:8272  NOTICE: VideoPlayer::OpenFile: https://lbv2.cdn.m6web.fr/v1/resource/s/usp/mb_sd3/2/f/e/Wild-la-course-de-s_c11954047_Episode-3-la-ju/Wild-la-course-de-s_c11954047_Episode-3-la-ju_drmnp.ism/Manifest.m3u8?expiration=1523588543&scheme=https&groups%5B0%5D=m6web&countries=QUR8RlJ8R1B8R0Z8TVF8WVR8TUN8TkN8UEZ8UkV8Qkx8TUZ8UE18VEZ8V0Y%3D&customerName=m6web&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MjM1NTI1NDIsIm5iZiI6MTUyMzU1MjU0MiwiZXhwIjoxNTIzNTg4NTQzLCJyX2hhc2giOiI2MzhlOWI4OTlmOTQwMDg0NTYxZGY2MDM4ZDk4YTBhZTJiNDQ4ZDdhIn0.ecwIwUI1zZbx1cvt6jNojjcBFNrAV-RuCZh8LfIv04o
19:02:26.044 T:10952  NOTICE: Creating InputStream
19:02:27.009 T:10952  NOTICE: Creating Demuxer
19:02:31.941 T:10952   ERROR: CVideoPlayer::OpenDemuxStream - Error creating demuxer
19:02:31.941 T:10952  NOTICE: CVideoPlayer::OnExit()
19:02:34.783 T:2856  NOTICE: script.module.youtube.dl: youtube_dl core version: 2018.03.20
19:02:34.812 T:2856   ERROR: C:\Users\Am\AppData\Roaming\Kodi\addons\script.module.youtube.dl\lib\YDStreamExtractor.py:453: UserWarning: External use of disableDASHVideo() is deprecated. It is now handled by module settings
                                              warnings.warn("External use of disableDASHVideo() is deprecated. It is now handled by module settings")
19:02:34.816 T:2856 WARNING: plugin.video.catchuptvandmore [v.0.1.4]: Deprecation warning: Plugin category is no longer set via Plugin.run(). Use "category" parameter of Plugin.create_listing() instead.
19:02:37.069 T:9972  NOTICE: script.module.youtube.dl: youtube_dl core version: 2018.03.20
19:02:37.092 T:9972   ERROR: C:\Users\Am\AppData\Roaming\Kodi\addons\script.module.youtube.dl\lib\YDStreamExtractor.py:453: UserWarning: External use of disableDASHVideo() is deprecated. It is now handled by module settings
                                              warnings.warn("External use of disableDASHVideo() is deprecated. It is now handled by module settings")
19:02:37.098 T:9972 WARNING: plugin.video.catchuptvandmore [v.0.1.4]: Deprecation warning: Plugin category is no longer set via Plugin.run(). Use "category" parameter of Plugin.create_listing() instead.
19:02:39.322 T:2028  NOTICE: script.module.youtube.dl: youtube_dl core version: 2018.03.20
19:02:39.351 T:2028   ERROR: C:\Users\Am\AppData\Roaming\Kodi\addons\script.module.youtube.dl\lib\YDStreamExtractor.py:453: UserWarning: External use of disableDASHVideo() is deprecated. It is now handled by module settings
                                              warnings.warn("External use of disableDASHVideo() is deprecated. It is now handled by module settings")
19:02:39.359 T:2028 WARNING: plugin.video.catchuptvandmore [v.0.1.4]: Deprecation warning: Plugin category is no longer set via Plugin.run(). Use "category" parameter of Plugin.create_listing() instead.
19:02:41.669 T:13012  NOTICE: script.module.youtube.dl: youtube_dl core version: 2018.03.20
19:02:41.694 T:13012   ERROR: C:\Users\Am\AppData\Roaming\Kodi\addons\script.module.youtube.dl\lib\YDStreamExtractor.py:453: UserWarning: External use of disableDASHVideo() is deprecated. It is now handled by module settings
                                              warnings.warn("External use of disableDASHVideo() is deprecated. It is now handled by module settings")
19:02:41.700 T:13012 WARNING: plugin.video.catchuptvandmore [v.0.1.4]: Deprecation warning: Plugin category is no longer set via Plugin.run(). Use "category" parameter of Plugin.create_listing() instead.
19:02:46.976 T:9796  NOTICE: script.module.youtube.dl: youtube_dl core version: 2018.03.20
19:02:47.006 T:9796   ERROR: C:\Users\Am\AppData\Roaming\Kodi\addons\script.module.youtube.dl\lib\YDStreamExtractor.py:453: UserWarning: External use of disableDASHVideo() is deprecated. It is now handled by module settings
                                              warnings.warn("External use of disableDASHVideo() is deprecated. It is now handled by module settings")
19:02:47.013 T:9796 WARNING: plugin.video.catchuptvandmore [v.0.1.4]: Deprecation warning: Plugin category is no longer set via Plugin.run(). Use "category" parameter of Plugin.create_listing() instead.
19:02:49.757 T:3660  NOTICE: script.module.youtube.dl: youtube_dl core version: 2018.03.20`

**Comment by wwark** [comment]
Hello,
Suivant les logs fournis, vous utilisez une vielle version du plugin et des corrections ont été apportées sur la partie M6 et W9 depuis.

Vous pouvez suivre cette procédure pour installer notre propre repo et installer la dernière version du plugin; https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/wiki/Add-the-official-repository

Merci,
Wwark

**Comment by HpNoTiQ56** [comment]
Bonjour,
Effectivement, cela corrige le problème !
Merci!
