### ISSUE TITLE
Replay de france.tv nécessite désormais de s'authentifier

### ISSUE THREAD

**Issue by gguillemot** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#540]
### Describe the bug
Lorsqu'on essaye de lire une video en replay de France.tv (France 2, France 3, etc.), rien ne se passe et la lecture ne fonctionne pas.

### To Reproduce
1. Choisir un flux de france.tv (exemple : replay du journal de 20h de France 2)
2. Lancer le Replay
3. ...
4.

### Expected behavior
Lecture de la vidéo en replay.

### Actuel behavior
Pas de lecture du flux vidéo.
Dans les log, j'ai trouvé des 403 sur l'ouverture du flux vidéo

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [x] Other (Odroid)

 - Operating system version/name:
 - Kodi version: Coreelec 9.2.7
 - Catch-up TV & More version: 0.2.35
 - Installation method: 

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by gguillemot** [comment]
Sur le site de france.tv, une vidéo prise au hasard demande de créer un compte ou de s'authentifier. exemple : https://www.france.tv/france-5/sur-le-front/2399403-la-face-cachee-du-recyclage.html

**Comment by DodoLeDev** [comment]
Cependant, youtube-dl arrive néanmoins à fetch l'URL de stream, donc je pense qu'il est toujours possible de contourner cette authentification....

**Comment by sy6sy2** [comment]
Hello!
Arf, maintenant il faut créer des compte partout... je vais essayer de regarder ça. Merci.

**Comment by 0xced** [comment]
Je pense avoir trouvé la solution. Le fix est proposé dans la pull request #550.

**Comment by pipoprods** [comment]
Merci @0xced , j'ai transposé le fix pour les flux HLS dans la PR #556

**Comment by sy6sy2** [comment]
Hello tout le monde ! Désolé pour l'absence. Je regarde tout ça tout de suite, merci pour les PR !!

**Comment by sy6sy2** [comment]
Vos deux commit sont présents dans la version 0.2.36~beta13 du plugin, merci beaucoup !
