### ISSUE TITLE
France.tv live not working

### ISSUE THREAD

**Issue by themesser** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#542]
### Describe the bug
A clear and concise description of what the bug is:
Can connect to the stream then get an error.
TF1, M6, Arte work, but all France tv streams fail to play
### To Reproduce
1. Install and play (from within catch up addin)
2.
3.
4.

### Expected behavior
A clear and concise description of what you expected to happen:
Play
### Actuel behavior
Tell us what happens instead:
No playing
### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 19
 - Catch-up TV & More version: beta6
 - Installation method:
From catch up repository

### Additional context
Add any other context about the problem here:
I am streaming using a vpn with a server set in France (shadow socks) all other channel plays well except France 2,3,4,5
### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by guilhermevrs** [comment]
Same here. Worked like a charm all weekend, then stopped yesterday morning. Last night I got it working again,but no luck this morning.

**Comment by guilhermevrs** [comment]
Will check the logs today,but could be related to https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/517

**Comment by themesser** [comment]
Sur Molotov, ça marche sans problème, y’a peut être un truc a faire ?
Effectivement quand j’essaye de regarder france2 en utilisant mon serveur privé shadowsocks en France sur mon mac dans chrome, j’ai un message “vous utilisez un vpn...”

**Comment by gguillemot** [comment]
A priori, on est sur le même problème que https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/540

**Comment by guilhermevrs** [comment]
Pas sur, vu que ça marche de temps en temps.
Je pense vraiment que c'est un peu lié a #517 de ceux que je vois sur Reddit aussi. Il y a des gens qui ont des soucis quand france.tv "finds out" que tu es sur VPN.

Workaround qui marche tres bien, VPN + http://captvty.fr/

**Comment by nirolfa** [comment]
Pffff, et après ils te sortent des directives au niveau européen
 "Télévision sans Frontières" - >  https://fr.wikipedia.org/wiki/Directive_T%C3%A9l%C3%A9vision_sans_Fronti%C3%A8res :( 
directive dite "CabSat 2" du 17 avril 2019 -> https://www.legipresse.com/011-50310-l-autre-directive-la-nouvelle-directive-dite-cabsat-2-du-17-avril-2019.html
moi je dis, il faut faire une pétition ;)

sinon détection vpn -> ils se basent sur le range ip  je suppose ....  ? 
       -> qq un a testé avec un petit vpn/jump host, chez une hebergeur style ovh ou autre ?

**Comment by sy6sy2** [comment]
Hello, je viens de tester à l'instant depuis la France, pas de problème pour FR2 en live.

Est-ce que les personnes qui ont des problèmes sont toutes derrière un VPN, ou bien, est-ce que même avec une IP française de votre FAI vous avez de temps en temps des problèmes ?

Juste pour savoir si le problème ne concerne que les VPN ou bien si d'autres facteurs entres en jeu (heure de diffusion, programme diffusé, ...)

Merci.

**Comment by Lavabo68** [comment]
Moi en VPN du Canada (privatetunnel) le journal 20h de France 2 en replay,ne fonctionne plus depuis + 2 sem.  Cependant Affaire conclue en replay ça fonctionne.  Est ce relier au replay du Journal de 20h ?

**Comment by themesser** [comment]
Oui VPN , mais c’est une ip unique.

**Comment by funtravel1208** [comment]
I have the same issue, and it has been weeks that France Televisions TV on Kodi is not working. There is no error messages. The spinning ball runs, the little play icon appears on top right of the screen and then disappears. Nothings plays.
Other channels other than France Televisions do work. 
When I try on my computer from the France Televisions website using the same VPN program, it's working.
Could you try to figure out what's the deal? I appreciate it
Thanks

**Comment by joaopa00** [comment]
No news since one year. I close the bug report. If the issue still occurs please open a new bug report and attach a log.
