### ISSUE TITLE
Arte replay list index error 

### ISSUE THREAD

**Issue by Rvhalewyn** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#543]
### Describe the bug
A clear and concise description of what the bug is: when opening Arte Replay you get a list index error. 

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - x Other: LibreElec 

 - Operating system version/name:
 - Kodi version: 18.9
 - Catch-up TV & More version: 0.2.36 beta 08
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by nonobio** [comment]
### Describe the bug
Hi, trying to access to Arte Replays give this error.

### Screenshots
https://i.imgur.com/iDf5h1j.png

### Your environment
Windows 7

Kodi version: 18.9

Catch-up TV & More version: 0.2.36 beta 08

### Debug log
https://paste.kodi.tv/dihoxehuve.kodi

Thanks :)

**Comment by sy6sy2** [comment]
I just pushed an extremely alpha version (0.2.36~beta10) to fix Arte replay. I need to find more time to fix it.

**Comment by sy6sy2** [comment]
For some videos, Kodi fails to open the stream, seems to be an FFMPEG issue. I opened an issue here https://github.com/xbmc/xbmc/issues/20039

**Comment by joaopa00** [comment]
Je ferme cette issue. Elle est principalement fixée. Pour les problèmes restants, merci d'ouvrir un nouveau rapport de bug.
