### ISSUE TITLE
Arte.tv and Gulli does not work

### ISSUE THREAD

**Issue by rican13** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#544]
### Describe the bug
A clear and concise description of what the bug is:
Arte.tv and Gulli does not work

### To Reproduce
1. 
2.
3.
4.

### Expected behavior
A clear and concise description of what you expected to happen:

### Actuel behavior
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: Android ARM 32-bit 7.1.2
 - Kodi version: 19.1.0 Git:20210508-85e05228b4
 - Catch-up TV & More version: catchuptvandmore.kodi.krypton.release v0.0.6 + plugin.video.catchuptvandmore v0.2.35+matrix.1
 - Installation method: Android application

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):
https://paste.kodi.tv/dutunonugu.kodi

**Comment by sy6sy2** [comment]
Hi, Arte bug should be fixed (see https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/546).

Concerning Gulli, what's the problem, live TV or replay? Thank you!
