### ISSUE TITLE
 IPTV Simple Client : DATABASE ERROR

### ISSUE THREAD

**Issue by nirolfa** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#545]
### Describe the bug
même bug que  IPTV Simple Client : DATABASE ERROR #467 
Lors du lancement d'une chaine, j'obtiens le message "DATABASE ERROR : database disk image is malformed".
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/467

### To Reproduce
1.Lors du lancement d'une chaine, j'obtiens le message "DATABASE ERROR : database disk image is malformed".

### Expected behavior
Lancement chaine

### Actuel behavior
Message d'erreur

### Your environment
 - [X] Raspberry-Pi

 - Operating system version/name:
 - Kodi version: 18 latest
 - Catch-up TV & More version: latest

**Comment by sy6sy2** [comment]
Hello, j'avoue ne pas réussir à reproduire le problème ; peux-tu essayer de backup ta config Kodi et de tester sur une install fraiche pour vérifier si cela fonctionne ?

**Comment by joaopa00** [comment]
Est-ce que le problème est encore d'actualité?

**Comment by joaopa00** [comment]
Pas de réponse depuis 10 mois. Je ferme. Si le problème est reproductible, n'hésitez pas à réouvrir.
