### ISSUE TITLE
FR2 replay journal 20h  

### ISSUE THREAD

**Issue by Lavabo68** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#549]
### Describe the bug
En VPN du Canada (privatetunnel) le journal 20h de France 2 en replay,ne fonctionne plus depuis + 2 sem.
Cependant Affaire Conclue en replay ça fonctionne. Est ce relier au replay du Journal de 20h ?
Sur plusieurs kodi Windows 10, Matrix et Leia même problématique.:

### To Reproduce
1.FR2/info et societe
2.journal20h
3.a revoir
4.

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x ] Windows
 - [ ] Other

 - Operating system version/name: Windows 10
 - Kodi version: Leia et Matrix.1
 - Catch-up TV & More version: 0.2.35

**Comment by funtravel1208** [comment]
Same issue here but in the US - No replays from France Televisions are currently working. Some settings may need to be updated. Would you mind to get the ball rolling for troubleshooting?

Thanks!

**Comment by Lavabo68** [comment]
What do you mean get the ball rolling? 
I have about 4 windows 10 laptop with kodi,  one with leia, one with Matrix.0 and 2 with MAtrix.1 and all do the same.

**Comment by funtravel1208** [comment]
> What do you mean get the ball rolling?
> I have about 4 windows 10 laptop with kodi, one with leia, one with Matrix.0 and 2 with MAtrix.1 and all do the same.

Sorry for the confusion- I was asking the developers to figure out what was the issue. I am not sure why but the developers are not responsive at all - They used to have a very quick turnaround but now no answer. I am wondering if they stopped maintaining this app. Any idea?

**Comment by sy6sy2** [comment]
Hi, sorry for the delay but we currently have a lot to do in real life.
Can you try if 0.2.36~beta13 version solves your issue? (see #540).

**Comment by funtravel1208** [comment]
I tried to uninstall and reinstall Catch Up TV & More to make sure it was not an issue on my side but when I click on "Install from Repository", I only get the version 2 : SylvainCecchetto,wwark - 0.2.37~beta02 - How do I get 0.2.36-beta13?
it looks like the issue is not only for replays for France TV - all channels in live are not working neither.
Does anyone else have the same issue? However, it's working if I watch France channels directly from their website

**Comment by sy6sy2** [comment]
Hi,
Do not try to use 0.2.36-beta13 version anymore, instead install the latest beta version available (0.2.37~beta07 at this time I guess).

**Comment by joaopa00** [comment]
Hello. Does the bug still occur with the latest beta version?
https://codeload.github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/zip/refs/heads/dev

**Comment by joaopa00** [comment]
Assume fixed. Please, reopen if the bug still occurs. Thank you.
