### ISSUE TITLE
Replay RTBF Auvio - ajout des sous categories pour les categories Musiques, Films, ....

### ISSUE THREAD

**Issue by Laurentwb** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#55]
Bonjour,

Tout d'abord, je voudrais vous remercier pour cette excellente extension.
Comme indiqué dans le titre, je vous contacte pour dire que les Replay Auvio RTBF ne fonctionnent pas.
Par contre, les directs fonctionnent normalement.

J'utilise un Raspberry avec Libreelec et Kodi 17.6.
Version du plugin : 0.1.10

Bien à vous.

Laurent

**Comment by wwark** [comment]
Bonjour,

Merci pour l'utilisation de cette extension :)
Depuis quelques temps une partie des replays de RTBF sont protégés par DRM. Kodi (plugin) n'est pas capable de les lire.
Dans la version de développement, nous avons rajouté une notification pour prévenir l'utilisateur.

Est-ce qu'il serait possible de nous envoyer les logs ? Par exemple, si vous essayez de regarder le replay du journal est-ce que vous avez aussi des erreurs ?

Merci,
Wwark.

**Comment by Laurentwb** [comment]
Je vous enverrai des logs dés que possible.
Ce qui m'étonne c'est qu'i y a un add-on qui s'appelle Belgium TV Replay quiarrive à les lire. Par contre il n'est plus mis à jour et bien qu'il fonctionne, il n'est pas très agréable à utiliser.

**Comment by Laurentwb** [comment]
Voici un lien vers un log comme promis : https://paste.kodi.tv/defasuduga
Je précise que l'add-on a démarré un replay (ce n'est pas le dernier).
Bon week-end.

**Comment by wwark** [comment]
Merci pour ces logs je confirme que les liens tester à part un sont protégés par des drm.
Si vous rechercher "drm" dans le log du pastebin vous verrez que la plupart des liens testés sont des liens protégés par drm.

Wwark.

**Comment by Laurentwb** [comment]
Merci pour l'info.
Comment expliquer que l'add-on "Belgium TV Replay" arrive a les lire ?

Laurent

**Comment by wwark** [comment]
Bonjour,
Je vais vérifier si nous avons d'autres flux qui ne serait pas protégés par DRM.
Je vous tiens au courant.

Merci,
Wwark

**Comment by wwark** [comment]
J'ai testé le film Night and Day sur les deux plugins. Aucun des deux ne peut lire ce contenu.
Il possible qu'il y est des cas proposant des flux protégés en non protégés pour le même contenu.
Est-ce que vous avez un exemple d'une vidéo fonctionnant sur Belgium TV Replay et pas sur Catchup TV & More ?

D'avance merci,
Wwark.

**Comment by Laurentwb** [comment]
The Voice Belgique S07 - Live 4  du 10/04/2018, par exemple.
Il est d'ailleurs comique de constater que Catch-Up me demande même si je veux reprendre la où je m'étais arrêté alors que c'est Belgium TV Replay qui avait démarré la stream.
Je constate aussi que cette émission porte des noms différents dans les 2 add-ons. Je me demande donc si ils utilisent les mêmes liens. 

Voici un nouveau log : https://paste.kodi.tv/itunazerey
Les deux derniers streams sont supposées être les mêmes ouvertes avec les add-ons différents.

**Comment by wwark** [comment]
Merci pour ces nouveaux logs.
Oui je confirme dans les logs que les deux plugins récupèrent les même liens. 
Kodi doit reconnaitre le lien et reprendre la lecture quelque soit l'addon utilisé.
J'ai testé de nouveau les deux plugins et la vidéo pour The Voice Belgique S07 - Live 4 ne passent pas chez moi ... (DRM issue).
Je l'ai aussi testé sur VLC et j'ai le même problème. Est-ce que le vidéo passe aussi sur VLC chez vous ?

Je vais continuer à chercher mais pour l'instant je n'ai pas de piste ...

Wwark.

**Comment by wwark** [comment]
Hello @Laurentwb 
Pourrez tu tester ? @darodi a fait un PR pour le cas des DRM qui devraient maintenant fonctionner.
Merci à lui :)
Si tout est bon. Nous pourrons fermer ce ticket.

**Comment by Laurentwb** [comment]
Je viens d'essayer la version que j'ai trouvé sur le github mais je ne suis pas du tout sûr que ce soit la bonne.
Peut-être pourriez vous m'envoyer un lien vers un Zip pour être tt a fait sûr.

En tout cas, celle que je viens d'essayer ne peut pas lire les émissions "Affaire conclue" qui a aussi le DRM.
De plus, je ne trouve plus les émissions Thé Voice Belgique 2018. Je ne sais pas s'il il y a un lien.

Laurent

**Comment by darodi** [comment]
Salut @Laurentwb 

Il s'agit de la branche dev dans le github ou avec zip:
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/archive/dev.zip

**Comment by wwark** [comment]
Désolé je viens de voir mon précédent message il manquait l'info de la version à tester. Merci Darodi.
On peut vérifier aussi la version dans Kodi. Il faut faire le test sur la version 0.1.13~beta008 ou superieur.

Pour l'emission The Voice Belgique 2018 elle n'apparait plus aussi sur le site RTBF Auvio. La modification apportée n'a pas d'impact sur la récupération des contenus sur le site de RTBF juste choisir un flux non protégé par DRM proposée par RTBF Auvio

**Comment by Laurentwb** [comment]
J'ai essayé la  version 0.1.13~beta008.
Ça a l'air de fonctionner pour les flux DRM (au moins pour l'émission Affaire Conclue).

Par contre, je dois vous contredire pour Thé Voice Belgium. Elle est toujours disponible sur Auvio dans l'onglet Musique. Celui-ci contient plusieurs catégories dont une qui est The Voice Belgium.
_ce sont ces categories qui ne sont pas visibles dans l'App Catch-Up TV & More _.

J'espère que ce retour vous sera utile pour le développement de l'App.

Laurent

**Comment by wwark** [comment]
Merci pour votre retour.
Je vais regarder pour les categories musique pour faire apparaitre ces sous-categories. Je pense qu'on doit avoir le même cas pour les autres categories (Films, etc...).

Merci,
Wwark.

**Comment by Laurentwb** [comment]
Probablement mais pour être franc, je n'ai pas regardé dans les autres
catégories.
Si cela vous est utile, je peux le faire.
Dites moi quoi

**Comment by wwark** [comment]
non pas utile ! merci :)

**Comment by wwark** [comment]
J'ai un peu avancé sur le sujet aujourd'hui. On affiche maintenant les sous-categories.
Reste à faire:
* Afficher les sous-categories manquante (juste les deux premières sous-categories sont affichées)
* Ajouter un bouton "More videos"

Merci,
Wwark

**Comment by Laurentwb** [comment]
Bonjour,

Aurez-vous l'occasion à un moment de vous dépêcher sur ceci ?
Merci d'avance.

Laurent

**Comment by wwark** [comment]
Bonjour Laurent,
Désolé je n'ai pas encore regardé. Nous essayons de l'ajouter pour la prochaine release.

Merci,
Wwark

**Comment by SylvainCecchetto** [comment]
Bonjour tout le monde,

Wwark, j'ai seulement lu en diagonal cette issue ; cependant voici un fork que quelqu'un a fait qui pourra nous être utile : https://github.com/darodi/plugin.video.catchuptvandmore/commit/7866477d61a2002ec3d6449a0c8853199bc3716f

Je colle ce lien seulement pour le garder sous la main ;-)

**Comment by wwark** [comment]
Bonjour Sylvain,
C'est une autre cause que les DRM. Celle ci est corrigée.
On doit parser des nouvelles pages pour ajouter des menus non presents sur le plugin mais accessible sur le site.
Merci,
Wwark.

**Comment by darodi** [comment]
@SylvainCecchetto 
Mon commit a en effet déjà été mergé. ;)

@wwark , @Laurentwb 
Je n'ai pas vraiment le temps, sinon je vous aurais bien aidé pour les menus et les pages multiples.
Cette fonctionnalité m’intéresse.
Merci pour votre boulot en tout cas.

**Comment by wwark** [comment]
Il faut construire cette URL : https://www.rtbf.be/news/api/block?data%5B0%5D%5Buuid%5D=widget-8647-3821&data%5B0%5D%5Btype%5D=widget&data%5B0%5D%5Bsettings%5D%5Bid%5D=8647&data%5B0%5D%5Bsettings%5D%5Bparams%5D%5Border%5D=3&data%5B0%5D%5Bsettings%5D%5Bparams%5D%5BdisplayTitle%5D=true&data%5B0%5D%5Bsettings%5D%5Bparams%5D%5BarticleId%5D=false&data%5B0%5D%5Bsettings%5D%5Bparams%5D%5Bdisplay%5D=container&data%5B0%5D%5Bsettings%5D%5Bparams%5D%5Bposition%5D=center&data%5B0%5D%5Bcache%5D%5Bnamespace%5D=sidebar&data%5B0%5D%5Bcache%5D%5Bentries%5D%5Bcategory_id%5D=1
pour chaque menu et parser les données deux fois pour avoir le titre et afficher les vidéos.
cas de la categorie info.

**Comment by wwark** [comment]
Quelques videos ne proposent pas de m3u8 format. Ce serait des videos youtubes. J'ai fait un commit pour ne plus remonter d'erreur mais pour l'instant le flux vidéo est à null. On doit parser l'id youtube et voir si on peut avoir d'autre format .... (beacoup de vidéos vivacité semblent impactées)

**Comment by wwark** [comment]
Je pense avoir régler les différentes erreurs.
Pouvez-vous tester et me dire si il y a des regressions ou des cas qui ne sont pas correctement gérés. Merci Wwark.

**Comment by Laurentwb** [comment]
Super, grand merci pour votre aide.
Je ne peux pas tester ce matin mais le ferai ce soir.
Bonne journée.

**Comment by Laurentwb** [comment]
Voilà . J'ai essayé la version 15beta6.
Il me semble que les remous sont pas mal du tout mais il va me falloir un peu de temps pour avoir une image globale. Il y a une catégorie "émissions" qui n'existe pas dans auvio.
Du côté du direct, c'est moins clair. Il y a des choses qui manquent. Par exemple, il devrait y avoir "PureVision" la plupart du temps mais il n'apparaît pas dance catch-up.

En tout cas, grand merci pour les efforts !

Laurent

**Comment by wwark** [comment]
![screenshot from 2018-10-18 20-58-24](https://user-images.githubusercontent.com/469461/47177400-a1153e80-d318-11e8-97af-94cb95a92c92.png)

Hello LaurentWeb,

On travaille pour migrer le plugin vers un nouveau Framework.
J'ai pu avoir PureFM mais il est protégé par DRM.
Je vais voir s'il est possible de l'ajouter dans le plugin test DRM.

Merci,
Wwark

**Comment by Laurentwb** [comment]
Il y a un add-on qui donne accès exclusivement a Auvio. Il y a peut-être qq
chose a apprendre dedans.
Bien à vous.

**Comment by Laurentwb** [comment]
Bonjour,

J'ai essayé la version codequick mais elle ne démarre pas et m'envoie une erreur. Voici mon log : https://paste.kodi.tv/cotapocawa .
Bonne journée.

**Comment by wwark** [comment]
On a poussé un possible fix pour le plugin Codequick. Est-ce que tu pourrais tester de nouveau?
Merci d'avance.
Wwark

**Comment by Laurentwb** [comment]
Bonjour,
Voilà, j'ai testé les 2 versions comme demandé. Pure FM fonctionnent dans les 2 !
C'est super et je vous remercie chaleureusement pour vos efforts !

Par contre, j'ai quelques questions :
- j'ai voulu changer l'ordre des chaînes mais je n'ai pas pigé si c'est possible
- je ne peux voir a peu près aucune chaîne française en direct ici en Belgique bien qu'elles soient toutes distribuées sur le câble. Est-ce une question de droit ?
- j'utilise la skin (fuse)jeudi qui est bien sympa avec un fond foncé. Les icônes transparentes (*.PNG ?) telles que celle d'Auvio ne rendent pas très bien car les zones claires transparentes sont noires alors que pas mal d'entre elles devraient être blanches. C'est évidemment un détail et certainement pas une priorité mais peut-être a considérer dans l'avenir pour augmenter la flexibilité de votre application.

Tout ceci étant dit,  encore merci pour vos efforts et félicitations pour votre application qui est un énorme plus pour les utilisateurs francophones de Kofi.

Bonne journée.

Laurent

**Comment by wwark** [comment]
Bonjour,

Merci d'avoir tester les deux versions. Le fix de l'erreur sur codequick est donc correct  !

Pour changer l'ordre des chaînes, il suffit de faire un appui long sur une chaine pour avoir un menu "move up" and "move down". La chaîne devrait se déplacer en haut ou en bas.

La majorité des contenus proposés sont géolocalisés. Il faut avoir une IP dans le pays. Le plugin se base sur les sites web de la chaîne. Si le contenu n'est pas accessible depuis votre PC alors le plugin aura le même comportement.

Le plugin est développé sur le skin par défaut. Il faudrait qu'on regarde s'il est possible d'avoir des images fonctionnant dans tous les cas ...

Merci ! Et merci aussi à @SylvainCecchetto pour son travail !

Je ferme ticket.
Wwark
