### ISSUE TITLE
Arte en basse résolution

### ISSUE THREAD

**Issue by Phigen** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#552]
Bonjour,
Depuis quelques jours, le flux Arte est en très basse résolution. Testé sur Libreelec sur RPI4 et box s912.
Les autres flux sont bons.
Utilisation de la version Beta du plugin.
Merci.

**Comment by enigma131** [comment]
Bonjour, flux live ? replay ? version de kodi? .. Pour info Libreelec vient de sortir la version avec kodi 19.

**Comment by Phigen** [comment]
Désolé pour le retard : flux live uniquement, Kodi Matrix, (Libreelec RPI4 ou Linux Mint PC, même problème), plugin 0.2.36-beta12.
Merci

**Comment by theoden11** [comment]
Bonjour. Confirmation du problème. Arte est en résolution 320x400, autant dire dégueulasse. Et il n'y a qu'un seul flux video.

**Comment by enigma131** [comment]
Le flux est en basse résolution aussi ici

**Comment by SimonClavier** [comment]
Same problem signaled here > https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/546#issuecomment-903160353
> (...) Catchup-tv v. 0.2.36-beta12 (...) the video quality of the Arte stream seems to be stuck at 320x180. I have no problem with other channels, and default quality is set to BEST in the plugin settings. Any idea?

**Comment by sy6sy2** [comment]
Hello tout le monde, désolé pour le délai ; pas mal occupé en ce moment.
Pouvez vous tester la version 0.2.36~beta15 ? ça semble régler le problème chez moi.
Merci

**Comment by enigma131** [comment]
Réglé pour la béta 15 . Kodi 19.1 linux
