### ISSUE TITLE
osmc et catchuptvandmore

### ISSUE THREAD

**Issue by caywin25** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#559]
Bonsoir, 

Merci pour votre travail.
Je viens d'installer omsc sur mon pi4 et certaines chaines ne fonctionnent pas : les chaines de FranceTV, les chaines du groupe m6 etc...
TF1 fonctionne en revanche.

Certains de mes films fonctionnent et d'autres non.

Je me pose la question de savoir s'il manquent des codecs ou autres.
Pourriez-vous m'aider svp ?

Merci

**Comment by Grouickman** [comment]
Hello,

Pour les chaines du groupe M6, voir : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/553
la manip à faire est vers le bas de la discussion.

Pour les chaines France TV, j'ai ouvert une issue : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/558

**Comment by caywin25** [comment]
Top pour le chaines m6 ça fonctionne.
En revanche pour la plupart de mes films j'ai toujours les erreurs :(

**Comment by Grouickman** [comment]
> Top merci pour le chaines m6 ça fonctionne.
> En revanche pour la plupart de mes films j'ai toujours les erreurs :(

Là tu ne parle pas de films en VOD/replay mais de la lecture de fichier vidéo en local? Si c'est ça, ça n'a rien à voir avec "CatchupTV & More" mais c'est purement la partie Kodi. Tu devrais plutôt regarder dans les FAQs et Forums OSMC.
Mais c'est probablement un soucis d'encodage de tes videos/films (ce serait pas du H265 ? C'est pas supporté sur Raspberry PI, à moins peut-être sur les PI4, mais je ne peux pas confirmer).

Si c'est le replay de France TV, il y a eu également un changement d'après ce que j'ai vu, cela requiert de s'authentifier maintenant. Voir : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/540

**Comment by caywin25** [comment]
Tous ne sont pas en h265  non
Le h265 fonctionnent sous le pi4 et tous les films fonctionnait sous LibreElec :D
Je vais regarder sur les forums yes !

Ça fait qq mois que le replay de FranceTV requiert une Auth. Ça fonctionnait avant sans compte.
Je vois que quelqu'un a proposé une MR et que celle-ci est dans la 0.2.36 beta13.
Je vais essayer de tester avec cette version 

Merci @Grouickman

**Comment by caywin25** [comment]
Mon soucis de lecture de fichiers local est résolu.
C'est tout simplement que les vidéos était propriétaires de root et que le user osmc ne pouvait pas les lire.
Tout est rentré dans l'ordre :)
Merci
