### ISSUE TITLE
RTL play not working

### ISSUE THREAD

**Issue by PowaBanga** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#564]
### Describe the bug
All rtl french channel are not working. Since i think 2 week
Rtl tvi
Plug rtl
Club rtl

### To Reproduce
Simply launch a replay video

### Expected behavior
Video work

### Your environment
 - [ ] Android
 - [ ] iOS
 - [*] Linux
 - [ ] OSX
 - [*] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: archlinuxarm
 - Kodi version: last
 - Catch-up TV & More version: lastfrom kodi's official repository
 - Installation method: installed from official repository

**Comment by darodi** [comment]
essayer la méthode de l'issue #553 a fonctionné pour moi

**Comment by joaopa00** [comment]
Surement fixé. Si ce n'est pas le cas, ouvrez un nouveau rapport de bug.
