### ISSUE TITLE
Guide TV en panne

### ISSUE THREAD

**Issue by theoden11** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#569]
http://bit.ly/tvguidefr ou http://bit.ly/tvguidebe ne marchent plus depuis ce matin. Enfin disons que l'url marche mais le guide fourni par ces url, qui sont des redirections vers https://raw.githubusercontent.com/Catch-up-TV-and-More/xmltv/master/tv_guide_fr.xml ou https://raw.githubusercontent.com/Catch-up-TV-and-More/xmltv/master/tv_guide_be.xml ne sont plus mis à jour depuis le 08 octobre. La mise en cache du guide fait qu'on ne s'en aperçoit qu'à retardement, sauf ceux qui venaient d'installer leur système, cela va de soi.
Conséquence : une fois le guide en cache arrivé à expiration, votre guide TV sera vide. Inutile de chercher à réparer, il n'y a rien à faire sauf à changer d'url de fournisseur de guide.
Le même problème se pose si on utilise l'intégration IPTV de Catchup puisque cela utilise le même paramètre.

Résolution provisoire:
Editer [votre répertoire Kodi]\userdata\addon_data\pvr.iptvsimple\settings.xml
changer l'url dans la ligne <setting id="epgUrl"></epgUrl>
On peut le faire via l'interface, mais avec la télécommande, bof, je préfère faire un copier-coller via SSH, c'est bien plus rapide !
Rebooter (c'est également le plus rapide)

**Comment by theoden11** [comment]
Bonjour chef. Merci pour l'info... à retardement. J'ai encore galéré sur ce problème, d'où le fait que je donne une soluce provisoire.

**Comment by Phigen** [comment]
Mise à jour ce matin... merci !
