### ISSUE TITLE
No EPG through IPTV Manager

### ISSUE THREAD

**Issue by Rvhalewyn** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#570]
Since yesterday I have got no EPG for the channels I linked to my live TV via IPTV Manager (French and Belgian French + Arte). The channels I linked with other apps like VRT NU work normally.

**Comment by jano1294** [comment]
Since I updated to 19.2 Matrix,I ave EPG for Pluto,Not for CatchUpTV&more

**Comment by sy6sy2** [comment]
EPG should works now, internet is back at home!
