### ISSUE TITLE
TV channels not wortking

### ISSUE THREAD

**Issue by guilders** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#573]
Hi All,

Running Kodi through LibreElec, have issues watching TV channels with Catch-Up TV & More.
Everything set up correclty with PVR IPTV simple.

Here is a link to error message I have when picking up a TV channel : https://ibb.co/j35M6s5

Here is the link to the logfile : http://ix.io/3CpY

I have no idea what is wrong, I tried deleting the databases filtes in userdata but it didn't fix the issue.

Hope you can help.

**Comment by sy6sy2** [comment]
Hi,
Is the error happens for all channels?

I check your log file but it seems not complete because I don't see the error.

**Comment by guilders** [comment]
Solved by deinstalling catchup and installing again.
