### ISSUE TITLE
Enregistrements non fonctionnels avec script.module.youtube.dl

### ISSUE THREAD

**Issue by Phigen** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#578]
Bonjour,
Je n'arrive pas à enregistrer le Replay lorsque j'active les options :
- enregistrer en arrière plan,
- renommer automatiquement le fichier.

Dans le 2e cas, j'ai une erreur d'encodage ASCII.
Une solution alternative est de désactiver ces 2 options, mais c'est dommage car elles sont bien pratiques (surtout la 2e).

Tester sous LE 10 sur RPI4.
Sous LE 9, cela fonctionne correctement, j'imagine que le passage à Python 3 a été fatal à ces options.
Merci.

Edit : l'enregistrement en arrière plan ne fonctionne pas non plus sous Leia.
Redit : l'enregistrement en arrière plan fonctionne sous Leia avec la version "Dev" de youtube-dl.

**Comment by jmzambon** [comment]
Bonjour Phigen,

Merci pour le retour. Serait-il possible d'avoir plus de précisions sur l'erreur sous LE 10 ?

L'idéal serait de joindre l'extrait du log correspondant. Pour activer le log : *Paramètres -> Journal des événements -> Paramètres -> Journalisation -> Activer le mode de débogage*. Le chemin du fichier kodi.log sera affiché dans le coin supérieur gauche de l'écran.

Merci.

**Comment by joaopa00** [comment]
Pas de nouvelle du rapporteur depuis 6 mois. Je ferme. Si le problème persiste, n'hésite pas à réouvrir cette issue en y appirtant les renseignements demandés.
