### ISSUE TITLE
France 5 no VOD

### ISSUE THREAD

**Issue by Rvhalewyn** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#579]
### Describe the bug
A clear and concise description of what the bug is:
Get http error object has no attribute code 

### To Reproduce
1.
2.
3.
4.

### Expected behavior
A clear and concise description of what you expected to happen:

### Actuel behavior
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - libreelec 
 - [ ] 

 - Operating system version/name:
 - Kodi version: 18.9
 - Catch-up TV & More version: 0.2.36
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment]
J'ai testé quelques videos (C dans l'air). Tout fonctionne pour moi: Linux Ubuntu-21.10, kodi 19.1 catcuptvmore 0.2.36
Donne le nom des vidéos qui ne fonctionnent pas. Et attache un log pour voir ce qui ne fonctionne pas chez toi.

merci d'avance.

**Comment by Rvhalewyn** [comment]
Comme demandé 

https://www.dropbox.com/sh/r0fefj30yz0vh3b/AABP7xKsLV6yNNq8VoQiqLlEa?dl=0

**Comment by joaopa00** [comment]
J'ai essayé la vidéo <<La case du siècle: l'affaire Baudis, la rumeur meurtirère>> sur Kodi 19.3 androidtv catchuptvmore 0.2.36. Elle fonctionne parfaitement. Tu devrais mettre à jour Kodi, je pense.

**Comment by Rvhalewyn** [comment]
Merci.
Hélas, ma boîte Eminem ne supporte pas (encore?) kodi 19.x
Une question de Widevine, je suppose ?
