### ISSUE TITLE
CNEWS de nouveau KO

### ISSUE THREAD

**Issue by joaopa00** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#580]
Il est de nouveau impossible de se connecter sur le direct de CNEWS.
La changement pour réparer est facile: dans le fichier lib/channels/fr/cnews.py ligne , remplacer data-videoid  par data-video-id

**Comment by enigma131** [comment]
Fonctionne parfaitement ici. Tu as quelle version et quel host ?

**Comment by joaopa00** [comment]
En effet, ça remarche. Les responsables du site ont dû remodifier leur code. Au final, c'est toujours le même identifiant de la video sur Dailymotion (x3b68jn) qui est appelé. Ce ne serait pas possible de le coder en dur pour éviter ce genre de désagrément?

**Comment by sy6sy2** [comment]
Hello,
Merci pour l'info, j'ai hardcodé l'ID x3b68jn qui devrait être utilisé en cas d'erreur.
