### ISSUE TITLE
Catchuptvmore ne peut pas atteindre les vidéos du site de la FFF

### ISSUE THREAD

**Issue by joaopa00** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#586]
Catchuptvmore crashes immédiatement lorsque l'on veut regarder les vidéos du site.

**Comment by sy6sy2** [comment]
Hello !
Merci pour l'info.
Est-ce que tu peux essayer la version 0.2.37~beta04 stp ?

**Comment by joaopa00** [comment]
Bonne nouvellle. Les videos disponibles sont maintenant affichées. Mauvaise nouvelles, elles ne se lancent pas
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/7628296/kodi.log)

**Comment by sy6sy2** [comment]
Hello, désolé du délai.
Peux tu essayer la version 0.2.37~beta08 stp ?

**Comment by joaopa00** [comment]
Testé et approuvé !! :D

Merci pour le boulot !!
