### ISSUE TITLE
Lumni content not listed

### ISSUE THREAD

**Issue by nicolaspernoud** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#588]
### Describe the bug
When trying to use Lumni Replay, no contents are listed.

### To Reproduce
1. Open Lumni
2. Go to Primaire
3. No content is available

### Expected behavior
List and access content.

### Actuel behavior
Tell us what happens instead: no content
![Lumni](https://user-images.githubusercontent.com/28347998/143282897-974a532e-da7a-4e2a-9449-b5040df3814b.png)

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [ ] Other

 - Operating system version/name: Windows 11
 - Kodi version: 19
 - Catch-up TV & More version: tested on both 0.2.37beta2 and 0.2.36
 - Installation method: Kodi default repos for 0.2.36 and beta repo for 0.2.37

### Additional context
Same problem on windows and librelec 10

**Comment by joaopa00** [comment]
Devrait être fixé dans la branche dev. S'il y a des bugs, merci d'ouvrir un nouveau rapport de bug en y ajoutant un log.

**Comment by nicolaspernoud** [comment]
C’est noté, merci et bravo pour cette extension !

**Comment by joaopa00** [comment]
Peux-tu donner un petit retour de test? Merci d'avance.

**Comment by nicolaspernoud** [comment]
C'est tout bon : émissions listées et visionnables. Merci.
