### ISSUE TITLE
C NEWS - NE MARCHE PLUS

### ISSUE THREAD

**Issue by gilles0606** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#59]
bonjour,

replay tv - france - CNews
ne marche plus.

test sur raspberry et sur windows, pareil....

merci

**Comment by wwark** [comment]
Bonjour,
Merci pour l'alerte. Le site a changé. 
Nous regardons pour corriger.
Wwark

**Comment by wwark** [comment]
Le replay et le direct TV de CNews ont été corrigé.
Pour le replay il reste encore des problèmes d'encodage dans les  titres (Dans la TODO)
