### ISSUE TITLE
Erreur chaine suisse italienne 

### ISSUE THREAD

**Issue by untiiis** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#597]
### Describe the bug
A clear and concise description of what the bug is:

### To Reproduce
1.
2.
3.
4.

### Expected behavior
A clear and concise description of what you expected to happen:

### Actuel behavior
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version:
 - Catch-up TV & More version:
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

Bonjour,
J'utilise kodi 18.9 sur Android
Quand je veux voir les chaînes suisses ou italiennes, j'ai toujours une erreur, devrai-je utiliser un vpn ou d'où vient le souci
Merci

**Comment by joaopa00** [comment]
Pas de nouvelles depuis deux mois. Si le problème persiste, tu peux réouvrir.
