### ISSUE TITLE
No subtitles on Arte videos (at least with TV Show "Inside No. 9")

### ISSUE THREAD

**Issue by nonobio** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#598]
### Describe the bug
A clear and concise description of what the bug is:

Hi,

When I play episode of the TV Show "Inside No. 9" I don't have subtitles. However, the add-on ask me which stream I want to play, and I choose "Original with FR subtitles".

Thanks :)

### To Reproduce
1. Open Catch-up add-on
2. Choose Replay TV, International, Arte (FR), Les series, Inside No. 9, Saison 6, 
3. Choose an episode
4. Choose "Version original - ST français"

### Expected behavior
A clear and concise description of what you expected to happen:

Have subtitles displayed.

### Actuel behavior
Tell us what happens instead:

The video is played well but without subtitles.

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Other

 - Operating system version/name: Windows 7 64 bits
 - Kodi version: 19.3
 - Catch-up TV & More version: 0.2.36+matrix.1
 - Installation method: Official Catch-up TV Repository

### Additional context
Add any other context about the problem here:

I tried to enable "Language settings" in Kodi: "Enable coded subtitles": same issue.
I also tried "player settings" in Kodi: "Accessibility: "prefer hard of hearing subtitles": same issue.

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by sy6sy2** [comment]
Hi,
Unfortunately it's not a CUTV&M issue but a Kodi issue.
I just tried with the first episode of Inside No. 9, Saison 6 and this is the m3u8 url : https://arte-cmafhls.akamaized.net/am/cmaf-webonly/103000/103400/103429-007-A_VO-STF/211027012627/103429-007-A_VO-STF_XQ.m3u8
If you download the m3u8 file you will see that the last line is the subtitle command.

I tried this URL with multiple player:
* VLC: no subtitle
* IINA: no subtitle
* Kodi: No subtitle
* Online player https://hls-js.netlify.app/demo/: Subtitle works!

I enabled FFMPEG logging in Kodi and this what I can see:

```
2022-01-19 13:31:24.458 T:4263638   DEBUG <general>: ffmpeg[0x7febef2ce040X]: [hls] Can't support the subtitle(uri: medias/103429-007-A_st_VO-FRA.m3u8)
```

I will try to see what's happen with the Kodi team, I guess that subtitle format used by Arte is not supported yet by Kodi ... 😕

**Comment by sy6sy2** [comment]
Ok, it's not a Kodi problem but an FFMPEG one. See this: https://github.com/FFmpeg/FFmpeg/blob/c8b5f2848dcdc7103a5b85c50c4c3082382d1f82/libavformat/hls.c#L506-L511

Nothing we can do until FFMPEG guys fix this, sorry 😕

**Comment by nonobio** [comment]
Hi,

Ok, thanks a lot.

Are they aware of the problem? I think yes because can see " /* TODO: handle subtitles" on the page, but I don't understand this page; it isn't an "Issue" as usual on Github...

**Comment by sy6sy2** [comment]
Yes they are aware because the TODO line that you see was written by a developer of ffmpeg directly in the source code of the file used to handle HLS m3u files like the one used by Arte 😉 

They "just" need to write the missing code part able to handle the subtitles.

**Comment by joaopa00** [comment]
It is not a Catchuptvandmore bug. Closing...
