### ISSUE TITLE
NRJ12 ne fonctionne plus

### ISSUE THREAD

**Issue by Nico83500** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#60]
Bonjour,
Depuis hier NRJ12 ne fonctionne plus chez moi, j'ai simplement la liste de Toutes les vidéos.
Merci par avance pour la résolution du problème et merci encore pour tout le travail fourni !

Version du plugin : 0.1.11
Système : Box S905X sous LibreELEC

**Comment by wwark** [comment]
Hello,
Le site web a changé et les flux vidéos récupérés renvoient un HTTP 404.

On regarde pour corriger.
Merci pour l'alerte.
Wwark

**Comment by wwark** [comment]
Corrigé sur la branche de développement
