### ISSUE TITLE
Subtitles on STV Catch-up 

### ISSUE THREAD

**Issue by chrissxuk** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#603]
### Describe the bug
In the settings the "enable subtitle if present" is not working properly, the subtitles always appear on STV catch-up regardless of this setting. 
### To Reproduce
1. In Catch-Up TV navigate to STV in United Kingdom. 
2. Play any show.
3. Subtitles will always appear regardless of the general settings. 
3. Go to subtitles as video is playing and subtitles will be enabled. 
4. Toggle enabled off and subtitles will stop.

### Expected behavior
A clear and concise description of what you expected to happen:
Subtitles should only display if the general settings "enable subtitle if present" is on or if enabled while video is playing. 

### Actuel behavior
Tell us what happens instead:
Subtitles always display by default regardless of the general settings. 

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: Firestick and Android on Formuler Z8 
 - Kodi version: 19.3
 - Catch-up TV & More version: 0.2.37~BETA08
 - Installation method: Beta repository from Github 

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by sy6sy2** [comment]
Hi,
The "Enable subtitle if present" is an old setting and I'm pretty sure that it's not used anymore (at least most of the time).
Now, each time we have a subtitle we give it to the Kodi player so that the user can enable or disable subtitles directly from the native Kodi player.

You can disable subtitle by default with this:

> Note: To make Kodi turn off subtitles by default: While playing a video, bring up the on screen display and select the audio options -> Turn off "subtitles" -> scroll down and select "save as default for all videos". 

See https://kodi.wiki/view/Subtitles

**Comment by chrissxuk** [comment]
Thank you for your reply but I'm still a little confused by this.

The "enable subtitle if present" is a setting in your add-on (quality and content) not a Kodi setting. This setting does nothing, are you just confirming that you are aware of that?

With regards the fix if I bring up the screen while playing I can switch on/off subtitles by clicking the box top row far left but this action will only apply to the video I'm watching there is no way to save for all videos. To get the audio settings while the video is playing I need to click the cog top row far right but the audio settings do not include the option to turn on/off subtitles.

This is not really a problem for me because I use subtitles and at present by default they always come on. I was actually asking this question for someone else who has to switch off the subtitles for every video.

I have attached some images to show what I mean.
![20220126_220148](https://user-images.githubusercontent.com/79976943/151254090-cbe1f6f8-9a36-4e64-86c4-b0e56fb084ba.jpg)
![20220126_220026](https://user-images.githubusercontent.com/79976943/151254129-c12a098e-983d-462e-89f1-7eab6805c964.jpg)
![20220126_215952](https://user-images.githubusercontent.com/79976943/151254133-17574d5a-eceb-408e-a1c0-09a015df9b85.jpg)

**Comment by chrissxuk** [comment]
Further to my last comment I have now discovered that if I switch on/off the subtitles while the video is playing (by clicking the box on left) I can save that setting for all videos by then going to the audio settings (by clicking the cog on right) and set as default for all media. 

Sorry if I've wasted your time but I do find it a little confusing saving a setting from one menu in a different menu and compounded by having an add-on settings that does not do what it says.

**Comment by chrissxuk** [comment]
Hi is there a problem today with STV in catch-up tv and more?

Trying to play a show that played yesterday and I get a playback error.
Someone else mentioned this on the Kodi forum too so it's not just me.

Thanks

Get BlueMail for Android <https://bluemail.me>

**Comment by joaopa00** [comment]
That's a new issue. Please open a new one. And don't forget to tell all the steps to reproduce the issue and attach a log.

**Comment by chrissxuk** [comment]
I am a little confused with this because I definitely did NOT make this comment 2 hours ago I haven't made any comments for months. I have no issues with this add-on.

**Comment by joaopa00** [comment]
Very strange. I will erase these messages then. Thanks for pointing this very strange thing.
