### ISSUE TITLE
Ajout chaines M6 International

### ISSUE THREAD

**Issue by guilders** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#605]
### Content description

* Name: proposition ajout de la chaine M6 INT FHD
* Type [e.g. TV channel, Catch-up TV, Website, Radio]: chaines TV
* Website URL:  https://shls-m6-int-prod-dub.shahid.net/out/v1/a315ab77ee7343a7a17dbe7e32eee3ba/index_2.m3u8?checkedby:iptvcat.com
* Content language/country: FR

### Content access

- [ X ] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [ ] This content is geographically restricted

### More information

If you want to add more information, put it here:
M6 International propose un contenu différent de la chaine M6, il serait intéressant de pouvoir en profiter dans Catch Up TV and more.

**Comment by darodi** [comment]
sur le site 
https://www.m6international.tv/

Avez-vous le même résultat?
Est-ce juste un problème de cache pour la Belgique?


![image](https://user-images.githubusercontent.com/4682830/156874554-ffac9cf5-8c62-45a2-b810-bad578d9ab25.png)

```

await fetch("https://player.vimeo.com/video/651993950?h=85a6dcb91b?autoplay=1&color=ffffff&title=0&byline=0&portrait=0&badge=0", {
    "credentials": "omit",
    "headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
        "Accept-Language": "fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3",
        "Upgrade-Insecure-Requests": "1",
        "Sec-Fetch-Dest": "iframe",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-Site": "cross-site",
        "Pragma": "no-cache",
        "Cache-Control": "no-cache"
    },
    "referrer": "https://www.m6international.tv/",
    "method": "GET",
    "mode": "cors"
});
```
HTTP/1.1 404 Not Found

**Comment by guilders** [comment]
J'ai la meme chose sur ce site

**Comment by darodi** [comment]
le lien iptvcat contient un lien vers sahid.net

Sur la page officielle de sahid
https://shahid.mbc.net/en/livestream/M6/livechannel-872343

Après 5 minutes 

> Shahid VIPYou reached your daily free preview limit. 
>  Join Shahid VIP now to continue watching Live TV channels in Full HD

https://shahid.mbc.net/en/widgets/subscription
**6.59 EUR / Month**

----

##   iptvcat n'est pas legit ! 

sur leur site:

> Notice
> We (IPTV Cat) DO NOT host or stream any videos on this website, we only RE-SHARE free Iptv links which are already at public accessible websites. We urge all copyright owners, to recognize that links contained within this site are located somewhere else on the web. Please direct all copyright infringement issues to the companies that host these files.

merci d’arrêter de proposer ces flux pour CUTVM




## Content access

**shahid.mbc.net**
- [x] This content or some part of this content require a paid account

**Comment by joaopa00** [comment]
Le site ne fait pas qu'agréger des liens. Ils les modfifient (on voit bien que le fichier m3u8 n'est pas celui du site de M6).
Je ferme pour éviter tout problème.
