### ISSUE TITLE
Ajout chaine Freesports HD

### ISSUE THREAD

**Issue by guilders** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#606]
### Content description

* Name: FreeSports HD
* Type [e.g. TV channel, Catch-up TV, Website, Radio]: TV channel
* Website URL: http://51.154.28.81:2052/play/a06i?checkedby:iptvcat.com
* Content language/country: UK

### Content access

- [ X ] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [ ] This content is geographically restricted

### More information

If you want to add more information, put it here:

I know Freesports is already included in Catch up TV, but I can't have it working, while the URL I am submitting is working for me, also this one is in HD, I am not sure about the one included in CatchUp.

**Comment by darodi** [comment]
restriction géographique sur le site officiel.
Il faut être au UK

![image](https://user-images.githubusercontent.com/4682830/156874300-c30ca862-d810-4987-82ac-b9cee735cbd2.png)

**Comment by darodi** [comment]
Duplicate of #604

**Comment by guilders** [comment]
Étrangement, précédemment la chaine fonctionnait.
Et depuis leur site web ou application mobile, je peux voir la chaine Freesport.
Je suis en Belgique.
J'ai depuis configuré un VPN pour la France, est-ce que le problème viendrait de là ?
-> chaine visible depuis al Belgique mais pas depuis la France ?

**Comment by darodi** [comment]
Semble fonctionner sur le site officiel depuis la Belgique aujourd'hui.
la restriction géographique dépend peut être du type de live retransmis.

![image](https://user-images.githubusercontent.com/4682830/157950482-c7723038-f202-4d73-b671-95546076da1c.png)

**Comment by darodi** [comment]
après un refresh de la page.
Ça dépend donc bien du type de retransmission

![image](https://user-images.githubusercontent.com/4682830/157950787-288008f1-6493-493f-8947-4bb0ef3e6f34.png)

**Comment by darodi** [comment]
même remarque que #605 

##   iptvcat n'est pas legit ! 

sur leur site:

> Notice
> We (IPTV Cat) DO NOT host or stream any videos on this website, we only RE-SHARE free Iptv links which are already at public accessible websites. We urge all copyright owners, to recognize that links contained within this site are located somewhere else on the web. Please direct all copyright infringement issues to the companies that host these files.

merci d’arrêter de proposer ces flux pour CUTVM

**Comment by joaopa00** [comment]
Je ferme.
