### ISSUE TITLE
Impossible d'avancer Replay Arte

### ISSUE THREAD

**Issue by elbartoolamuerte** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#607]
### Describe the bug
A clear and concise description of what the bug is:
Dans le Replay d'Arte, il est impossible d'avancer dans une vidéo, ou de reprendre une vidéo depuis un temps spécifique. La vidéo frizze, obligé de quitter.

### To Reproduce
1. Ouvrir le Replay Arte dans le plugin sur Kodi
2. Lancer une video
3. Avancer
4.

### Expected behavior
A clear and concise description of what you expected to happen:

### Actuel behavior
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [X ] Other

 - Operating system version/name: FireTV
 - Kodi version:19.3
 - Catch-up TV & More version: Last Beta
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by sy6sy2** [comment]
Hello,
Merci pour l'issue, en effet j'avais également remarqué ce problème, malheureusement il s'agit probablement d'une limitation de FFMPEG avec le format utilisé par ARTE (on a également un problème sur les sous titres https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/598).
Du coup c'est aux gars de FFMPEG de corriger le problème 😕

**Comment by joaopa00** [comment]
Pas un bug de Catchuptvandmore. Je ferme.
