### ISSUE TITLE
Les videos du site de la FFF ne fonctionnent pas de nouveau

### ISSUE THREAD

**Issue by joaopa00** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#608]
Il est de nouveau impossible de lire les vidéos du site de la FFF
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/7919077/kodi.log)
.

**Comment by sy6sy2** [comment]
Hello, as-tu une vidéo qui ne fonctionne pas chez toi ? J'en ai essayé quelques une mais je n'arrive pas à reproduire le problème.
Merci

**Comment by joaopa00** [comment]
C'était la video red-star chambly. Je l'ai retestée. Elle fonctionne. Ca devait surement être un problème du serveur.
