### ISSUE TITLE
[Demande] Ajout section Favorie

### ISSUE THREAD

**Issue by Alexis67330** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#61]
Salut,

Comme déjà mentionné ici : 
https://forum.mpdb.tv/index.php/topic,35713.msg277477.html?PHPSESSID=7f9a9faaec179fad6c2339b920ace371#msg277477

Serait il possible d'ajouté une ou plusieurs sections Favoris dans Catch-up-TV-and-More ???

Une section Favorie pour les mètres les chaines directe en favorite et une deuxièmes pour les chaines replay... 

Si cela est possible je vous remercie d'avant

**Comment by wwark** [comment]
0.2.6 est disponible.
