### ISSUE TITLE
#593 breaks the add-on on Kodi 18 with Python 2

### ISSUE THREAD

**Issue by simonpils** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#610]
### Describe the bug
#593 breaks the add-on on Kodi 18 with Python 2, because collections.abc does not exist for Python 2

### To Reproduce

1. Open the add-on on Kodi 18
2. The add-on crashes

### Expected behavior
The add-on should not crash

### Actuel behavior
The add-on crashes

### Screenshots
N/A

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: LibreELEC 9.2.8 for RPi 2
 - Kodi version: 18
 - Catch-up TV & More version: beta
 - Installation method: repository

### Additional context
N/A

### Debug log
N/A

### Proposed fix
```
try:
    from collections.abc import MutableMapping
except ImportError:
    from collections import MutableMapping
```

**Comment by sy6sy2** [comment]
Thank you for this issue!
Should be fixed in 0.2.37~beta10
