### ISSUE TITLE
France TV down

### ISSUE THREAD

**Issue by wixaw** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#616]
Hello
Tous les replays de france.tv ne fonctionnent plus erreur 401
Même sur le canal beta
Merci d'avance

**Comment by Mexx62** [comment]
Effectivement, je viens de regarder et j'ai l'impression que le process a changé côté FranceTV : récupérer l'url du média directement après le premier appel à `player.webservices.francetelevisions.fr` finit en 403, il faut maintenant récupérer le "token" suite à cet appel, qui correspond à une url, pour ensuite l'appeler en GET en ajoutant en query param la fameuse url qu'on utilisait avant. En faisant ça on retrouve la suite du process actuel : on récupère une url, on l'appelle en GET, ça retourne une 302 et l'endroit vers lequel ça pointe c'est le `manifest.mpd`

**Comment by opengk** [comment]
Je confirme, même souci d'erreur 403 sur mon install kodi.

**Comment by zertyuio296** [comment]
Bonjour,
Je confirme le problème depuis 3 jours environ pour les video protégés par DRM.
Il semble y avoir un sujet similaire sur youtube-dl:
https://github.com/ytdl-org/youtube-dl/issues/29956
est-ce qu'une mise à jour de youtube-dl pourrait résoudre le problème?

Merci

**Comment by gaudreaser** [comment]
Moi aussi je n'ai plus accès à aucun replay de France 3 ex Des chiffres et des lettres depuis le 25 janvier autant sur version stable que beta. Un dump du log disponible si désiré

**Comment by Kiks67** [comment]
> Pareil ici, aucun replay sur FranceTV depuis plusieurs jours. @Mexx62 a isolé le problème et semble indiquer une solution. Malheureusement je n'ai pas les compétences pour modifier le code!

Un lien vers la solution ?

**Comment by Kiks67** [comment]
Top, ça fonctionne nickel.
Merci beaucoup

@mateusbirnbaum : Tu as Kodi sur quoi comme équipement ?

**Comment by mateusbirnbaum** [comment]
Merci! Ça fonctionne impec.
@Kiks67 J'utilise kodi sur un NUC avec OpenSuseTW via Flatpak. Pourquoi?

**Comment by djreedoo** [comment]
> Top, ça fonctionne nickel. Merci beaucoup
> 
> @mateusbirnbaum : Tu as Kodi sur quoi comme équipement ?

Bonjour, 
y a-t-il un lien vers la solution ?
Je ne trouve rien. 
désolé si je passe à côté...

**Comment by Kiks67** [comment]
> Merci! Ça fonctionne impec. @Kiks67 J'utilise kodi sur un NUC avec OpenSuseTW via Flatpak. Pourquoi?

Tu disais ne pas savoir modifier le code, c'était pour ça. Mais ça semble OK pour toi


> > Top, ça fonctionne nickel. Merci beaucoup
> > @mateusbirnbaum : Tu as Kodi sur quoi comme équipement ?
> 
> Bonjour, y a-t-il un lien vers la solution ? Je ne trouve rien. désolé si je passe à côté...

https://github.com/Arias800/plugin.video.catchuptvandmore/commit/9718f4995cd71e3ea88b40eaf1abdee8ab789b32

Il faut modifier le fichier "resources/lib/resolver_proxy.py" et soit supprimer, soit commenter la ligne 333

**Comment by GregAce** [comment]
Merci, ça fonctionne !

**Comment by djreedoo** [comment]
Merci beaucoup, ça marche !
J'utilise une box S905X3 avec CORELEC et la skin AEON MQ8 et c'est parfaitement fonctionnel et très beau .
Est-ce que l'addon est toujours maintenu ?
j'ai pu lire sur certains forums qu'il y avait un doute là-dessus.

**Comment by aldo7410** [comment]
Bonjour à tous, j'ai mon addons France tv avec Kodi 18 qui ne fonctionne pas, quelqu'un pourrait me passer le fichier en question
 resolver_proxy.py ou du moins ce qu'il faut écrire dedans parce que je suis novice et j'ai toujours une erreur...merci à vous et bonne continuation....

**Comment by djreedoo** [comment]
> 

Bonjour, c'est juste décrit plus haut.
"Il faut modifier le fichier "resources/lib/resolver_proxy.py" et soit supprimer, soit commenter la ligne 333"

**Comment by aldo7410** [comment]
Merci, mais justement c'est ça que je ne comprends pas, supprimer ç n'a pas fonctionner pour moi, et commenter la ligne 333 je ne sais pas ce que ça veut dire, mais je vais chercher....

**Comment by djreedoo** [comment]
Mettez un # en début de ligneLe 17 févr. 2022 11:16, aldo7410 ***@***.***> a écrit :

Merci, mais justement c'est ça que je ne comprends pas, supprimer ç n'a pas fonctionner pour moi, et commenter la ligne 333 je ne sais pas ce que ça veut dire, mais je vais chercher....

**Comment by aldo7410** [comment]
Merci bien l'ami, je vois voir ça....

**Comment by wixaw** [comment]
Pourquoi n'y a til plus de mises à jour ? je vois mal la belle mère faire ce genre de modif sur un player android xD

**Comment by joaopa00** [comment]
WWark semble avoir abandonné le projet.  Depuis deux semaines,, sy6sy2 n'est pas venu sur ce site. Il est peut-être en vacanes ou indisponible. Si lui aussi a abandonné le projet, l'extension est morte, puisque personne ne pourra la mettre dans le repo de Kodi. Il faudra faire un fork et demander à Kodi dans le mettre dans son repo.

**Comment by joaopa00** [comment]
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/dev/resources/lib/channels/wo/arte.py

**Comment by djreedoo** [comment]
c'est bien dommage car cet add-on est une pépite...

**Comment by aldo7410** [comment]
Salut à tous....hey l'ami joaopa00, prends l'addons en charge si tu peux le faire, ça dépannera tout le monde, perso, je ne suis pas programmeur, juste bidouilleur....lol....bonne journée à tous....

**Comment by sy6sy2** [comment]
Hello tout le monde,
Désolé pour le retard, je suis pas mal occupé en ce moment et malheureusement j'ai moins le temps de passer par ici.
Merci à tous pour le fix, logiquement il est dispo dans la version 0.2.37~beta12.

@joaopa00 a proposé son aide ici https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/630 ; les portes sont grandes ouvertes si des personnes souhaites participer au projet ! C'est avec grand plaisir !
Que ce soit pour maintenant le plugin (un peu de Python et de scrapping) ou même pour la gestion des issues des utilisateurs 😉 

Je ferme l'issue pour le moment, à re-open si besoin.

**Comment by djreedoo** [comment]
> Hello tout le monde, Désolé pour le retard, je suis pas mal occupé en ce moment et malheureusement j'ai moins le temps de passer par ici. Merci à tous pour le fix, logiquement il est dispo dans la version 0.2.37~beta12.
> 
> @joaopa00 a proposé son aide ici #630 ; les portes sont grandes ouvertes si des personnes souhaites participer au projet ! C'est avec grand plaisir ! Que ce soit pour maintenant le plugin (un peu de Python et de scrapping) ou même pour la gestion des issues des utilisateurs 😉
> 
> Je ferme l'issue pour le moment, à re-open si besoin.
Un grand merci à toi et à tous ceux qui oeuvrent et entretiennent ce genre d'addon pour le bien de toute la communauté.
