### ISSUE TITLE
[BE - AB3] live broken

### ISSUE THREAD

**Issue by darodi** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#617]
### Describe the bug
[BE - AB3] live broken

same problem for AB xplore? I haven't tried.

### To Reproduce
Steps to reproduce the behaviour:
1.  Live TV  
2. Belgium
3. AB3

### Expected behaviour
live working

### Actual behaviour
live not working

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [ ] Other

 - Operating system version/name:
   - Linux osmc 5.10.32-2-osmc Mon Aug 2 04:28:32 UTC 2021 armv7l GNU/         
   - windows 10                                                                                                                                                    
 - Kodi version:
   - kodi v19.3 Matrix
 - Catch-up TV & More version:
   - 0.2.37~beta11
 - Installation method:
   - repository beta & git dev

### Additional context

url api changed;
```
# URL_API = 'https://subscription.digital.api.abweb.com/api/subscription/has-live-rights/%s/%s'
URL_API = 'https://subscription.digital.api.abweb.com/api/player/live/%s/%s'
```
it gives a 

- streamBaseUrl
`   # streamBaseUrl	"https://mediawan-cji-bks.akamaized.net/mwab3/mwab3.isml"`
- hdnts to use as a parameter for the url
`    # hdnts	"exp=164349`....`~acl=/*~hmac=ab3ff47e68eb2844a15dc6f937566cfa3`.....`"`
- smToken to be used in com.widevine.alpha licence request?
`# smToken	"eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMjU2R`....`"`

the url to call seems to be:
https://mediawan-cji-bks.akamaized.net/mwab3/mwab3.ism/index.mpd?hdnts=....

url for licence key? (haven't tried yet)

`URL_LICENCE_KEY = 'https://mediawan.fe.cloud.vo.services/drmgateway/v1/drm/widevine/license?drmLicenseToken=%s|User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0&Accept=*/*&Accept-Language=fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3&Accept-Encoding=gzip, deflate, br&Origin=https://live-replay.ab3.be&DNT=1&Connection=keep-alive&Referer=https://live-replay.ab3.be/&Sec-Fetch-Dest=empty&Sec-Fetch-Mode=cors&Sec-Fetch-Site=cross-site|R{SSM}|'`

**Comment by joaopa00** [comment]
Merci pour le travail effectué sur ce bug. Je ferme cette issue. S'il apparaît un bug, merci d'ouvrir un nouveau rapport de bug et d'y attacher un log. Merci d'avance.
