### ISSUE TITLE
Add Albi TV (local French TV)

### ISSUE THREAD

**Issue by HydrelioxGitHub** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#620]
### Content description

* Name: Albi TV
* Type [e.g. TV channel, Catch-up TV, Website, Radio]: TV Channel / Website
* Website URL: https://www.albi-tv.fr
* Content language/country: FR/France

### Content access

- [ ] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [ ] This content is geographically restricted

### More information

If you want to add more information, put it here:

**Comment by joaopa00** [comment]
Le live est implémenté. Je regarde pour le replay.

**Comment by joaopa00** [comment]
Le replay utilise la plateforme wimxp pour héberger les vidéos. Impossible de trouver l'API pour les récupérer. Si quelqu'un a une idée, n'hésiter pas.

**Comment by HydrelioxGitHub** [comment]
Déjà si il y a le live c'est bien. C'est une obligation le replay pour être validé sur Catch-up ?

**Comment by Arias800** [comment]
> Le replay utilise la plateforme wimxp pour héberger les vidéos. Impossible de trouver l'API pour les récupérer. Si quelqu'un a une idée, n'hésiter pas.

C'est bon, j'ai globalement compris comment ça marche.
Je peux m'en occuper.

**Comment by joaopa00** [comment]
Super! Merci.

**Comment by joaopa00** [comment]
Merci encore Arias800 pour cet énorme travail. Maintenant que tout est implémenté, on peut fermer ce rapport.
