### ISSUE TITLE
[résolu] son décalé sur la chaine française C8

### ISSUE THREAD

**Issue by guilders** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#621]
### Describe the bug
A clear and concise description of what the bug is: cela fait quelques jours que le son est fort décalé par rapport à l'image sur la chaine C8

### To Reproduce
1. regarder la chaine C8
2.
3.
4.

### Expected behavior
A clear and concise description of what you expected to happen: son et image synchros

### Actuel behavior
Tell us what happens instead: son décalé

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ x] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: libreelec
 - Kodi version: kodi 9 ou 10
 - Catch-up TV & More version: dernière beta
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by theoden11** [comment]
Bonjour. Problème confirmé depuis plusieurs jours, j'allais ouvrir un ticket mais c'est déjà fait. OSMC dernière version (kodi 19.3) + Catchup dernière version beta. Il y a presque 10s de décalage entre son et image dans mon cas, le son précède l'image.

**Comment by Arias800** [comment]
C'est un problème du flux Dailymotion.
Il faudrait voir si le flux du site rencontre le même problème, si c'est n'est pas le cas, il faudrait voir pour utiliser ce flux dans l'addon.
(ce n'est pas sûr que ce sois possible à cause du DRM).

**Comment by Arias800** [comment]
Multi Weather sera bientôt mis à jour (il y a eu une modification du côté de Yahoo qui rendait la récupération des données impossible).
L'addon Dailymotion ne semble plus mis à jour.

Par contre, bonne nouvelle, le décalage son est corrigé sur Dailymotion.
Donc tout remarche correctement sur Catchup.

**Comment by theoden11** [comment]
Cool. Que des bonnes nouvelles en somme ! Si seulement on pouvait faire marcher RMC... les émissions de voiture me manquent !

**Comment by Arias800** [comment]
Je me bats actuellement pour faire marcher le DRM, car sinon la partie replay du site est quasiment fonctionnel à 100%...

**Comment by guilders** [comment]
Problème résolue, je confirme, par contre problème identique, moins marqué, sur CStar.

**Comment by joaopa00** [comment]
@guilders. Peux-tu confirmer que l'issue n'est pas présente sur Cstar?

**Comment by joaopa00** [comment]
Supposé fixé maintenant. Ouvre un nouveau rapport de bug si tu vois encore le problème pour CStar.
