### ISSUE TITLE
Addon start error: Guadeloupe - KeyError

### ISSUE THREAD

**Issue by Nux007** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#63]
All is in the log :-)

12:06:30.065 T:139802339727104   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('Guadeloupe 1\xc3\xa8re',)
                                            Traceback (most recent call last):
                                              File "/home/nux007/.kodi/addons/plugin.video.catchuptvandmore/addon.py", line 27, in <module>
                                                from resources.lib.root.channels.fr import live_tv_fr
                                              File "/home/nux007/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/root/channels/fr/live_tv_fr.py", line 97, in <module>
                                                'la_1ere.region')],
                                            KeyError: ('Guadeloupe 1\xc3\xa8re',)
                                            -->End of Python script error report<--

**Comment by Nux007** [comment]
Le fichier settings situé dans userdata entrait en conflit, après suppression, tous est ok...

**Comment by wwark** [comment]
Merci pour l'alerte. C'est sûrement lié aux changements de nom des régions pour la 1ère lié aux changement d'API des derniers commits ....
Je vais regarder pour voir s'il est possible de forcer la recréation du settings.xml dans ce cas ...
