### ISSUE TITLE
Gestion du site

### ISSUE THREAD

**Issue by joaopa00** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#630]
Pour éviter des délais trop longs pour la mise à jour de l'extension lors de l'absence de l'administrateur, je me propose aussi comme administrateur. sy6sy2, acceptes-tu ma proposition?

**Comment by sy6sy2** [comment]
Hello joaopa00,

C'est avec grand plaisir que j'accepte de l'aide pour le plugin, malheureusement le temps me manque pour suivre les issues mais également la correction de bugs donc tout coup de mains et plus que le bienvenue 😉 

Je vais te donner les droits sur l'Organisation Catch UP TV & More.
Concernant le repo du plugin, la branche principale est la branche `dev` ; quand tu le souhaites tu peux incrémenter la version beta du plugin dans le fichier `addon.xml`, ce qui déclenche automatiquement la mise à disposition du plugin sur le repo bêta.
Concernant les releases sur le repo officiel de Kodi il faut encore faire la soumission "à la main" sur le GitHub de Kodi ; je veux bien continuer à m'en charger si tu veux 😉 

Si tu as besoin d'aide n'hésite pas à me contacter par mail ! Encore merci pour ta proposition de participation !!

**Comment by joaopa00** [comment]
Super. Je viens d'accepter la proposition. Je te remercie pour  ta confiance. J'espère être à la hauteur.
