### ISSUE TITLE
Catch up tv and more accounts to visualise channels 

### ISSUE THREAD

**Issue by rave84** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#634]
Hi
Using kodi with catch up tv & more addon, and in parameters of catch up tv, it request accounts to be able to view some channels. It requests user name and password, but I'm unable to type "@" for my account name (it's my email address). "@" key doesn't appear neither on alphanumeric keys nor on special characters part of keyboard. Any suggestion if I have missed a step or done something wrong?
Using it on android phone, all up to date.

**Comment by darodi** [comment]
"@" should appear when you use the shift key.
