### ISSUE TITLE
Qualité du flux adaptée à la connexion

### ISSUE THREAD

**Issue by joaopa00** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#638]
Pour certains flux, il est possible de choisir la qualité manuellement: best ,dialog....

Il serait bien d'avoir une option qui permet de choisir si ll'on suhaite que la qualité du flux s'adapte automatiquement le flux à la vitesse de la connexion. Inputstream-adaptie est capable de faire cela.

**Comment by darodi** [comment]
Dans l'item, on peut setter une valeur de 
https://github.com/xbmc/inputstream.adaptive/wiki/Integration#inputstreamadaptivemax_bandwidth

Mais sinon c'est pas déjà la cas?
Si l'item n'est pas setté, par défaut, il prend la valeur donnée dans les propriétés du plugin inputstream.adaptive: 
- quand on a une valeur différente de 0: il limite le flux aux valeurs max demandées https://github.com/xbmc/inputstream.adaptive/commit/9f3502a101c60094ea75c9d1a086847fbfeedf6c
- si la valeur est 0, il ne s'adapte pas à la vitesse de connexion déjà?

On a plusieurs cas dans catchuptvandmore:

- Pour BE-RTBFauvio par exemple, on a un lien mpd, qui contient plusieurs qualités, on peut ensuite choisir la qualité dans le menu engrenage lors de la lecture.
- Pour BE-RTLplay ou FR-6play, on a plusieurs liens mpd, un par qualité LO, SD, HD, pas de choix dans le menu engrenage pendant la lecture.

**Comment by darodi** [comment]
donc utiliser inputstream.adaptative pour dailymotion à la place de YouTube.DL quand download_mode est à false?

`resources.lib.resolver_proxy.get_stream_dailymotion`

**Comment by joaopa00** [comment]
Oui, je pensais à ca...

**Comment by Arias800** [comment]
L'idéal, ce serait de pouvoir utiliser inpustream adaptive avec Dailymotion, mais pour le moment, ce n'est pas possible à cause d'un bug: https://github.com/xbmc/inputstream.adaptive/issues/496

**Comment by joaopa00** [comment]
J'ai vu que tu as donné la solution au problème :D . Ce n'est qu'une question de temps que le problème avec Dailymotion soit fixé. Croisons les doigts. Car InputStream est d'une utilisation beaucoup plus confortable que Youtube-Downloader.

**Comment by darodi** [comment]
new discussion
- #692

**Comment by joaopa00** [comment]
Grâce au trvail de Darodi, on peut considérer cette issue comme fixé. Elle le sera totalement lors inputstream sera fixé. Mais cela n'est pas un problème de Catchuptvmore. Il faudra aussi faire la transition des anciennes méthodes de lecture fu flux vers la nouvelle pour tous les fichiers.
