### ISSUE TITLE
[Website argonautes] Le site a changé d'adresse

### ISSUE THREAD

**Issue by darodi** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#645]
Le site a changé d'adresse. Il est disponible ici. Malheureusement, pour moi, il est géo-bloqué.
https://squat.telequebec.tv/les-argonautes

Je pense qu'on ne devrait pas désactiver cette partie, mais essayer de la réparer.

_Originally posted by @joaopa00 in https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/641#issuecomment-1053110148_

**Comment by joaopa00** [comment]
Avec un proxy canadien, j'obtiens l'erreur 500.

**Comment by joaopa00** [comment]
Pour la personne, il serait m^me intéressant d'essayer de récupérer toutes les vidéos de ce site. Il y a des programmes assez sympathiques.

**Comment by joaopa00** [comment]
Devrait être résolu dans GIT.
