### ISSUE TITLE
[WO - RT] live FR, DDoS protection by DDoS-GUARD

### ISSUE THREAD

**Issue by darodi** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#667]
### Describe the bug
[WO - RT] live FR, DDoS protection by DDoS-GUARD

### To Reproduce
Steps to reproduce the behaviour:
1. live FR for RT

### Expected behaviour
live working

### Actual behaviour
sometimes, live doesn't work. 
html gives DDoS protection by DDoS-GUARD and can't be parsed for video url

**Comment by joaopa00** [comment]
La chaîne a été fermé par l'UE. Il n'y a plus de diffusion

https://francais.rt.com/player

**Comment by darodi** [comment]
pourquoi je la vois en direct sur le site alors? :)

**Comment by darodi** [comment]
![Clipboard02s](https://user-images.githubusercontent.com/4682830/156250315-7452af22-e176-4b37-96b3-6b875f76fa4b.png)

**Comment by joaopa00** [comment]
Ah bah oui ca marche. C'est ça l'UE!

**Comment by darodi** [comment]
Ah voilà l’explication. ça commence demain.

> Les 27 pays membres de l'Union européenne (UE) ont donné le 1er mars leur feu vert pour interdire la diffusion dans l'UE de RT et Sputnik (comme l'avait annoncé la président de la Commission européenne) et pour exclure «certaines banques russes» du système de messagerie Swift, rouage clé de la finance internationale, a annoncé la présidence française de l'UE. 
> 
> Selon l'AFP, ces mesures sont censées entrer en vigueur le 2 mars après publication de la décision au Journal officiel de l'UE.
