### ISSUE TITLE
L'equipe TV sur raspberry

### ISSUE THREAD

**Issue by Fraisdos** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#67]
Bonjour,

L'equipe TV fonctionne sous Kodi sous Mac OS, pas sous Kodi sous raspberry.

**Comment by wwark** [comment]
Bonjour @Fraisdos,
Est-ce que tu utilises la même version du plugin dans les deux cas ?
Si c'est le cas le plugin fait son travail mais la version de Kodi semble poser problème.
Est-ce qu'il serait possible d'avoir les logs en DEBUG de kodi durant un test de l'équipe TV ?

Merci,
marc.

**Comment by Fraisdos** [comment]
Bonjour Marc,

Même version de plugins, par contre Kodi 18 sous Mac et 17 sous raspberry. 
Je fais suivre le log à mon retour mercredi soir. 

Merci,
Frédéric

Envoyé de mon iPhone

**Comment by Fraisdos** [comment]
Bonjour,

Je viens de tester ce matin avec la dernière version, ça fonctionne.

Bonne journée et merci pour le travail effectué.
Frédéric


Le 2018-05-21 11:05, Marc Roy a écrit :

**Comment by wwark** [comment]
La dernière version du plugin ou de Kodi ?
Je ferme ce ticket comme ça fonctionne maintenant.

**Comment by Fraisdos** [comment]
Dernière version du plugin. 
Bonne journée 

Envoyé de mon iPhone

**Comment by wwark** [comment]
merci pour votre retour :)
