### ISSUE TITLE
RMC BFM Play

### ISSUE THREAD

**Issue by Europe57** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#670]
### Describe the bug
A clear and concise description of what the bug is:

### To Reproduce
Steps to reproduce the behaviour:
1. Ouvertue de la page du replay (Replay -> France -> RMC BFM Play) ou du direct (TV en direct -> RMC Découverte)
2.
3.
4.

### Expected behaviour
A clear and concise description of what you expected to happen: À chaque tentative = 403 Client Error: Forbidden for https://sso-client.sfr.fr/cas/services/rest/3.2/createToken.json?duration=84600

### Actual behaviour
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [x] Android 
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 19.3
 - Catch-up TV & More version: 0.2.37~beta53
 - Installation method: Repository Beta

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment]
Quelle version de Catchuptvmore as-tu utlisé?

**Comment by Europe57** [comment]
Ok, problème régler, en faite, quand j'allais sur leur site j'étais connecter, mais j'ai tenter de me déconnecter et reconnecter, et là, le site me dit, que mon compte est bloquer, j'ai fais la procédure de déblocage et ça marche. Désolé pour le signalement.

Merci de la réponse.
