### ISSUE TITLE
No access to a program

### ISSUE THREAD

**Issue by Canos78** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#676]
Bonjour, 

Je ne peux accéder à certains contenus replay sur Mytf1, la série Grey anatomy plus précisément
Je ne peux seulement accéder aux "extraits" et "exclus" mais pas les épisodes, j'ai le message "Runtime error No items found" qui s'affiche. Serais-je le seul ?

J'utilise l'add-on la version beta sur xiaomi box tv (kodi 19.3)

Merci pour votre aide

**Comment by joaopa00** [comment]
Est-ce que tu y as accès à travers un navigateur internet?

**Comment by Canos78** [comment]
Heu c'est à dire via navigateur ?
J'utilise kodi sur la xiaomi box tv, donc non pas de navigateur.

**Comment by joaopa00** [comment]
Je veux dire en essayant sur un PC pour voir si la video est bien disponible et surtout jouable.
Si ce n'est pas le cas, il est normal que Catchuptvandmore ne peut pas lire la vidéo.

**Comment by Canos78** [comment]
Je viens d'essayer sous windows, j'ai le même problème...
Mais comment se fait-il que les autres séries fonctionnent (même des américaines), et que surtout, j'ai tout de même accès aux replays et extraits de la série ?

Merci

**Comment by joaopa00** [comment]
incrimer = <<mettre en cause >> Il n'y pas d'émotions ou de jugement de valeur derrière. C'est juste le terme adéquat à la situation.
