### ISSUE TITLE
Error on unmask channel from masked list

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#677]
### Describe the bug
A clear and concise description of what the bug is:
Can't unmask a channel from masked list

### To Reproduce
Steps to reproduce the behaviour:
1.
2.
3.
4.

### Expected behaviour
A clear and concise description of what you expected to happen:

### Actual behaviour
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 19.4
 - Catch-up TV & More version: 0.38.0
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

extract : 
2022-03-07 13:27:22.076 T:2227    ERROR <general>: [Catch-up-TV-&-More.support] 'fun_radio'
                                                   Traceback (most recent call last):
                                                     File "/home/enigma/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                     File "/home/enigma/.kodi/addons/script.module.codequick/lib/codequick/script.py", line 169, in __call__
                                                       return route.function(self, *args, **kwargs)
                                                     File "/home/enigma/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/menu_utils.py", line 366, in unmask_items
                                                       labels.insert(0, get_item_label(last_item_id, module.menu[last_item_id]))
                                                   KeyError: 'fun_radio'

**Comment by joaopa00** [comment]
Il n'y a que pour la chaîne Fun-radio que tu as le problème? Tu utlises un IPTV manager?

**Comment by enigma131** [comment]
Je voulais retourner dans la liste des blacklistées, mais il ne me l'affiche plus. Je voulais restaurer certaines chaines. Je n'ai pas iptvmanager car j'utiise aussi hts.pvr et dvbviewer.pvr.

**Comment by enigma131** [comment]
Sous windows cela fonctionne. Les chaines masquées sont stockées ou ?

**Comment by enigma131** [comment]
J'ai trouvé le fichier à corriger : menus_settings.json . Corrigé manuellement en retirant de numéros (order) qui étaient insérés dedans. Sujet clos

**Comment by joaopa00** [comment]
C'est chouette que tu aies trouvé la solution. Sais-tu d'où vient le fichier  menus_settings.json.
Je ne le trouve pas dans Catchuptvandmore.

**Comment by enigma131** [comment]
Il est dans .kodi/userdata/addon_datas/plugin.video.cachuptvandmore

**Comment by enigma131** [comment]
Comme des chaines ont été résolues, j'ai voulu à nouveau démasquer certaines ... et paf pas aces à la liste à nouveau ....
Il semblerai qu'il y ai une erreur de codage....
