### ISSUE TITLE
Problème direct France CUTV and More 0.2.37

### ISSUE THREAD

**Issue by f28gin** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#678]
### Content description

* Name: Bug sur le direct France
* Type [e.g. TV channel, Catch-up TV, Website, Radio]: Catch-up TV
* Website URL:
* Content language/country: France

### Content access

- [ ] This content or some part of this content require a free account
- [ ] Bonjour et merci pour cet Addon !!
- [ ] Mon problème est que quand je veux regarder les chaines directes France, j'ai ce message d'erreur :
- [ ] UnicodeEncodeError 'ascii' codec can't encode character u'\xe9' in position 5: ordinal not in range : (128)
je suis avec un Raspi3 et Libreelec 9.2.8
Merci d'avance
très bonne journée

- [ ] This content or some part of this content require a paid account
- [ ] This content is geographically restricted

### More information

If you want to add more information, put it here:

**Comment by f28gin** [comment]
bonjour et merci de me répondre !

non, pas d'IPTV manager juste l'addon ...
pour le log je vais regarder où il peut ce trouver ...

Merci d'avance

**Comment by f28gin** [comment]
bonjour à tous,

J'ai fait un test en modifiant le fichier "fr_live.py" et remplacé les caractères accentués par exemple "é" par "e" et ça fonctionne BIEN !!! sauf pour les chaines RMCBFM même avec un login et password actif ....

A suivre ;-)

**Comment by joaopa00** [comment]
Peux-tu essayer la versionde développement?
https://codeload.github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/zip/refs/heads/dev

**Comment by f28gin** [comment]
Merci pour l'info !!

je viens de tester et ça fonctionne bien sauf pour RMC BFM "Routemissing"
"unable to import route module: resources.lib.channels.fr.rmcbfmplay"

merci pour ce premier test presque concluant ;-)

**Comment by joaopa00** [comment]
Umm non, ce n'est pas bon du tout. Il faut vraiment le log pour pouvoir enquêter plus. Peux-tu le fournir en l'attachant ici. Merci d'avance.

**Comment by f28gin** [comment]
Merci pour ta réponse !!!!

je le trouve où le log ??

**Comment by joaopa00** [comment]
Normalement, il devrait être dans le répertoire .kodi/temp. Il devrait y avoir un fichier kodi.log. C'est celui ci.
Si tu ne trouves pas le répertoire .kodi/temp, essaie le répertoire .kodi/userdata/temp.

**Comment by joaopa00** [comment]
Utilises-tu un IPTV manager?

Dans tous les cas, cela me semble être un problème de cache. Tu devrais le supprimer (attention, cela supprimera toutes les données de KOdi)

**Comment by f28gin** [comment]
je n'utilise pas IPTV manager ....

pour le cache j'ai supprimé le cache LIBREELEC mais je ne sais pas comment supprimer le cache Kodi !!??

**Comment by joaopa00** [comment]
Si tu n'as pas peu de perdre toutes tes configurations pour Kodi, supprime le repertoire .kodi

**Comment by f28gin** [comment]
Aïe Aïe ... là c'est du HARD ... j'ai eu pas mal de soucis pour installer certains Addon et extentions ... 
je vais sauvegarder le répertoire avant et je ferais le test 

merci de ta réactivité ça fait vraiment plaisir ;-)

**Comment by f28gin** [comment]
Bonjour,

j'ai fait un test ce matin à supprimer juste le dossier CUTV dans .kodi ... etc ...
réinstalle de l'Addon et toujours le même message d'erreur "RouteMissing" sur les chaines RMCBFM ...
vérification de mon login et password sur le site RMCBFM et tout est OK ...

toujours à suivre ;-)

**Comment by joaopa00** [comment]
As-tu résolu ton problème? Tu peux essayer ce qui est proposé dans https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/685

**Comment by f28gin** [comment]
pour France TV tout est OK ... juste les chaines RMC BFM qui ne fonctionnent toujours pas .... :(

merci pour la suite ....

**Comment by joaopa00** [comment]
As-tu bien installé l'addon locale?

**Comment by joaopa00** [comment]
Dans l'issue #695 la mise a jour à LibreElec 10.0 a résolu un problème avec widevine. Essaie de tenter le coup.

**Comment by f28gin** [comment]
bonjour !

Je suis avec un PI3 donc pas de maj en version 10 malheureusement ...

bonne journée et grand merci pour les infos !!!!

**Comment by f28gin** [comment]
re bonjour

Version 10 installée et testé ... en effet les chaines RMC BFM fonctionnent ... mais ! il y a un MAIS .. en direct ou en replay c'est la cata ... image figée et son avec des coupures ou décalé ...

je repasse en version 9.2.8 qui fonctionnait largement mieux en dehors de RMC BFM ....

Merci pour votre boulot mais kodi MATRIX pas pour moi pour l'instant ;-)

très bonne journée !!!

**Comment by joaopa00** [comment]
J'ai installé une Ubuntu Focal 20-04 et Kodi-18. J'ai réussi à reproduire le problème. J'enquête pour savoir pourquoi cela se passe. Merci pour le rapport de bug.

**Comment by joaopa00** [comment]
Après investigations, je epux affirmer que le problème n'a rien à voir avec l'encodage UTF-8. Le problème est que RMCBFMPPLAY.py  importe urllib.parse qui n'est disponible que pour Python3. Importer urllib fixe le problème de route  pour Leai. Malheureusement, cela n'est pas suffisant pour faire fonctionner RMCBFMPLAY sur Leia puisque les URLs récupérés sous Leai ne sont pas les mêmes que ceux sous Matrix et ils ont la mauvaise idée de faire crasher FFMPEG...

**Comment by joaopa00** [comment]
Devrait être fixé avec la dernière béta. Le module inputstream adaptive doit être à jour.
La vieille version de Inputstream adaptive pour Leia disponible dans le repo de Kodi pour ubuntu  ne permet pas de lancer les chaines. Mais les liens récupérés fonctionnent parfaitement avec la derniere version de Inpustream adaptive fournie par Matrix. Pour ceux qui sont bien à jour dans leur version de Kodi Leai,mer ci de tester la dernière béta et de rapporter si le bug est encore présent. Merci d'avance.

**Comment by f28gin** [comment]
Bonjour !

Maj avec le zip de la beta 09 ...
plus du tout de chaines en direct (tous les pays) avec le message d'erreur : invalid syntax (xml.py, line 489)

bonne journée et MERCI du suivi +1:

**Comment by joaopa00** [comment]
Ce n'est pas plutôt xmltv.py?

**Comment by f28gin** [comment]
oui oui ... désolé j'ai écrit trop vite :+1:

**Comment by joaopa00** [comment]
Le problème devrait être fixé dans la dernière béta. Peux-tu faire un test?

**Comment by f28gin** [comment]
Hé bien !!

L'installation du zip a échoué !! erreur structure invalide ... :(

désolé !

**Comment by joaopa00** [comment]
Fonctionne bien chez moi. Peux-tu réessayer? Tu utilises le fichier zip ou le dépôt béta?

**Comment by f28gin** [comment]
j'ai utilisé le zip de : https://codeload.github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/zip/refs/heads/dev

**Comment by joaopa00** [comment]
Pas de problème pour moi. Certainement un problème de téléchargement chez toi. Peux-tu re-télécharger et rester?

**Comment by f28gin** [comment]
on continue .... LOL

après un redémarrage j'ai l'erreur : invalid syntax (sd_json.py, line 56)

pas cool ... ;-)

**Comment by joaopa00** [comment]
Donc c'était bien un problème de téléchargement chez toi?

**Comment by joaopa00** [comment]
Nouvelle version de disponible. Peux-tu tester?

**Comment by f28gin** [comment]
Echec à l"installation ....

**Comment by joaopa00** [comment]
Comme d'habiture retélécharge et installe nouveau en pas oubliant d'éteindre kodi et de le relancer.

**Comment by f28gin** [comment]
bonjour,

toujours pas cool :( après un redémarrage j'ai l'erreur sur les live France et autres pays : invalid syntax (sd_json.py, line 101)

mais le replay fonctionne correctement ...

merci encore !!

**Comment by joaopa00** [comment]
On va s'en sortir. Peux-tu donner un essai à la dernière version mise en ligne? Toujours fermer kodi avant de re-télécharger Catchuptvandmore et alors relancer kodi.

**Comment by f28gin** [comment]
pareil après le redémarrage ...
après un redémarrage j'ai l'erreur sur les live France et autres pays : invalid syntax (sd_json.py, line 126)

**Comment by joaopa00** [comment]
Peux-tu retester? Avec toujours la même procédure....

**Comment by f28gin** [comment]
STOP !! on ne touche plus à rien ... LOL

c'est OKKKK ... j'ai juste des petites coupures toutes les 10 sec. sur RMCBFM ... sur le reste c'est impec !

BRAVO et un grand merci :+1:

**Comment by joaopa00** [comment]
J'ai poussé une rustine dans git. Peux-tu essayer la toute dernière version?
Merci d'avance.

**Comment by joaopa00** [comment]
Devrait être fixé dans git. Tu peux réouvrir si le problème persiste.

**Comment by f28gin** [comment]
bonjour,

test ce matin avec le DEV et après un redémarrage j'ai l'erreur sur les live France et autres pays : invalid syntax (sd_json.py, line 102)

J'ai gardé le zip qui fonctionne pour être tranquille ...

bon dimanche et encore bravo pour ce boulot ;-)

**Comment by joaopa00** [comment]
Ce n'est pas normal. Peux-tu attacher le fichier log.txt en ayant activer le mode debug danskodi/ Merci d'avance.

**Comment by f28gin** [comment]
Voilà ...
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/8310986/kodi.log)

**Comment by joaopa00** [comment]
Tu as besoin d'installer le paquet future-fstring. Malheureusement, il n'est pas disponible dans les dépôts officiels d'Ubuntu. Tu peux l'installer à travers pip ou mieux (peu-être ?) à travers le dépôt teirs kern7: [dépôt kern](https://kernsuite.info/packages/)

**Comment by f28gin** [comment]
et bien là ... avec un PI3 et Libreelec 9.2.8 ...ça va être durdur ...

je reste avec l'ancien ADDON CUTV ..

j'attend que la version Matrix soit plus stable sur mon PI3 sinon plus de maj pour moi !! LOL

bon dimanche sous nos applaudissements !!!

**Comment by darodi** [comment]
@f28gin 

Pas de problème de stabilité sous rpi 3 ici.
Je suis sous Linux osmc 5.10.78-5-osmc kodi  VERSION_ID="2022.03-1"  Kodi (19.4).

**Comment by joaopa00** [comment]
Le problème avec les f-strings est que cela n'a été introduit qu'avec Python 3.6. Et f28gin utilise Leia qui utilise Python 2.7
Sous un  OS "normal" on peut importer le module future_fstring qui apporte la compatibilit pour Python2. Mais malheureusement, il n'y pas ce module tout prêt dans Kodi.

**Comment by joaopa00** [comment]
Peux tu essayer cette version de développement? Merci d'avance.

[version de test](https://docs.google.com/uc?export=download&id=1RyAvCKQ1KvRhfbMSrgsZMfYeiBDvT6on)

**Comment by joaopa00** [comment]
Oui c'est normal. Ne t'inquiètes pas.

**Comment by joaopa00** [comment]
C'est possible d'avoir le fichier log.txt. Je voudrais savoir si le fichier future_fstring est bien trouvé (et appelé).

**Comment by f28gin** [comment]
pas de soucis ....
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/8317916/kodi.log)

**Comment by f28gin** [comment]
Ah !! flutte désolé ... pas penser à le faire ..

je ferais ça demain matin ...
Bonne soirée

**Comment by joaopa00** [comment]
Peux-tu essayer cette version
[version de test](https://docs.google.com/uc?export=download&id=11C0MSp-o245itbtZfhFn-SiVUbGNVxep)
