### ISSUE TITLE
Can't play any content

### ISSUE THREAD

**Issue by AlpacaDries** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#684]
I can only play local Belgian channels such as TV Oost and Focus WTV. When I try to play other channels or replays, I get the error message in Dutch "This selection triggered an unexpected error." It also says "IndexError list Index out of range" Sharing the logbook also does not work. This also aplies to RTL en VRTnu where you have to log in. This is the case in both the addon itself and IPTV manager. I tried it on 2 different devices and it's the same.

This applies to live channels and replay channels

### To Reproduce
Steps to reproduce the behaviour:
1. open the addon
2. Belgium
3. play any content but local channels
4. error message

### Expected behaviour
A clear and concise description of what you expected to happen: the stream/video would play

### Actual behaviour
Tell us what happens instead: I get the error message

### Screenshots
If applicable, add screenshots to help explain your problem:
![afbeelding](https://user-images.githubusercontent.com/96911359/157481718-2d99b27c-04c7-428b-9962-c3d5c2958350.png)

### Your environment
 - [ ] Raspberry-Pi
 - [ ] HP laptop

 - Operating system version/name: LibreELEC, Windows 11
 - Kodi version: 18.9, 19.3
 - Catch-up TV & More version: v0.2.37 
 - Installation method: the repository

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment]
The usual question: do you use an IPTV manager?

**Comment by darodi** [comment]
@AlpacaDries 

I fixed TV Lux.
Could you list other lives not working?

**Comment by darodi** [comment]
- [ ] Fix Télé MB

```
ERROR <general>: [Catch-up-TV-&-More.support] list index out of range
   Traceback (most recent call last):
	 File "C:\Users\RoDi\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 306, in run_callback
	   redirect = parent_ins(route, arg_params, self.callback_params)
	 File "C:\Users\RoDi\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\resolver.py", line 67, in __call__
	   results = super(Resolver, self).__call__(route, args, kwargs)
	 File "C:\Users\RoDi\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\script.py", line 169, in __call__
	   return route.function(self, *args, **kwargs)
	 File "C:\Users\RoDi\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\channels\be\telemb.py", line 105, in get_live_url
	   return re.compile(
   IndexError: list index out of range
```

- [ ] Fix RTL info: 
`item is unplayable`

- [ ] Fix Één: 
`item is unplayable`

- [ ] Fix Canvas: 
`unable to resolve url`

- [ ] Fix Ketnet: 
`unable to resolve url`

- [ ] Fix RTL sport: 
`item is unplayable`

- [ ] Fix Canal C: 
`403 forbidden`

**Comment by darodi** [comment]
@joaopa00 

I think we can close this issue now

**Comment by joaopa00** [comment]
Thank you for this great work Darodi .Closing.
