### ISSUE TITLE
"Add the official repository"  section in wiki

### ISSUE THREAD

**Issue by darodi** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#693]
the repository given here is not correct

https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/wiki/Add-the-official-repository

> Fill in the repository URL: https://repo.cecchettosylvain.fr/zip

![image](https://user-images.githubusercontent.com/4682830/157749872-7cc33407-83ea-42cd-b9b7-586717cc9ee0.png)

forwards to this page if we accept the security risk

![image](https://user-images.githubusercontent.com/4682830/157749998-ddd23ead-3bfe-4bde-a04c-801b4dea7ab1.png)

_Originally posted by @darodi in https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/688#issuecomment-1064480760_

**Comment by darodi** [comment]
wiki updated here

https://github.com/darodi/plugin.video.catchuptvandmore.wiki.git

**Comment by sy6sy2** [comment]
Thanks @darodi , it should be ok on https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/wiki/Add-the-official-repository now?

**Comment by darodi** [comment]
@sy6sy2 

you should maybe pull/merge/rebase my wiki git, I changed the references to krypton/jarvis to stable/beta,
fixed some typos, even in other pages in a second commit

**Comment by darodi** [comment]
@joaopa00 
thanks for the last changes

here are the fixes for the typos in the wiki
[fix_typos.patch.zip](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/8233993/fix_typos.patch.zip)

**Comment by joaopa00** [comment]
Done. Thanks for the patch.
Joaopa

    Le vendredi 11 mars 2022, 07:20:28 UTC−10, darodi ***@***.***> a écrit :  
 
 


@joaopa00
thanks for the last changes

here are the fixes for the typos in the wiki
fix_typos.patch.zip

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
