### ISSUE TITLE
Utilisation de Catch Up TV and More sur mac (M1)

### ISSUE THREAD

**Issue by Dayoros** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#694]
Bonjour,
Je rencontre quelques problèmes à la lecture de toutes les chaînes du groupe TF1 depuis mon Mac.

Description :
Lors de la lecture d'une chaine de TV du groupe TF1 (ou même le replay), la lecture semble fonctionner mais aucune image n'apparait. En revanche, j'ai bien le son !
J'ai testé les chaines du groupe M6, et ça fonctionne sans soucis (avec téléchargement du plugin Widevine - qui m'a été proposé). 

Contexte Technique :
Mac OS 12.2.1
Macbook air M1.
Kodi 19.4 (idem en 18.9)
Catch up TV and more : dernière.

A noter que j'utilise aussi la même version de Kodi sur une amazon fire stick, et tout fonctionne sans soucis ;)
J'ai fait une capture écran pour illustrer le bug rencontré.
![Kodi TF1 Mac](https://user-images.githubusercontent.com/96288364/158072778-ce4ea509-71e8-42ac-aa4c-d244344057d8.png)

Merci d'avance !
Cordialement,

**Comment by joaopa00** [comment]
Clairement, ce n'est pas un problème de Catchuptvandmore. C'est plus vraisemblablement u nproblème de Inputstream Adaptive et le décodage matériel sur mac.
Il n'y a rien que l'on puisse faire.

**Comment by sy6sy2** [comment]
Hello,
Dans le doute tu peux tester de désactiver le décodage matériel dans les réglages de Kodi ... sinon tu auras plus de chances sur le forum/GitHub issues de Kodi 😉

**Comment by joaopa00** [comment]
Du point de vue fonctionnel de KOdi, le problème n'est pas réglé sur Kodi. Tu devrais ouvrir un ticket dans le github de Kodi.

**Comment by etienne0x7C1** [comment]
Même problème, même remède. Effectivement il y'a un souci vidéo sur M1 visiblement non résolu.
