### ISSUE TITLE
[Add new content] Add Sud radio

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#696]
### Content description

* Name: Sud Radio
* Type: TV channel
* Website URL:  https://www.sudradio.fr/
* Content language/country: Fr

### Content access

Free

### More information

Resolution 480p:
https://stream-07.ix7.dailymotion.com/sec(CFYS0CyzC0phI1myd5MCS7ngAfQuFLLft5R4Zhcyx40)/dm/3/x75yzts/s/live-1.m3u8
Resolution 720p:
https://stream-02.ix7.dailymotion.com/sec(CFYS0CyzC0phI1myd5MCS7ngAfQuFLLft5R4Zhcyx40)/dm/3/x75yzts/s/live-2.m3u8

**Comment by joaopa00** [comment]
Dans git. Sera disponible dans la prochaine sortie béta.

**Comment by enigma131** [comment]
Merci

**Comment by joaopa00** [comment]
Fixé dans la dernière béta.

**Comment by enigma131** [comment]
Fonctionne en multi résolution , alors que #385 ne fonctionne toujours pas en multi resolution. Pourquoi ?
