### ISSUE TITLE
FranceTV Sport - Direct TV limiter à 10 min 

### ISSUE THREAD

**Issue by wwark** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#70]
Hi,
Ce ticket pour suivre ce cas et voir comment mettre à jour le flux video afin que la vidéo continue sans avoir besoin de relancer le flux toutes les 10 min.

11:13:22.594 T:1911078912 NOTICE: VideoPlayer: Opening: https://ftvensport01hls-i.akamaihd.net/hls/live/660101/SPORT_LV02/master.m3u8?hdnea=exp=1527499401~acl=%2fhls%2flive%2f660101%2fSPORT_LV02*~hmac=a4464f903381ccd03aca35cb25ed4ca648589bae07ba5263f10dc977510208c5

Ce qui est mis en gras indique le temps avant expiration.
Conversion results (1527499401) epoch time
1527499401 converts to Monday May 28, 2018 11:23:21 (am) in time zone Europe/Paris (CEST)
The offset (difference to Greenwich Time/GMT) is +02:00 or in seconds 7200.
This date is in daylight saving time.

**Comment by wwark** [comment]
J'ai testé sur VLC et j'ai pu regarder plus de 10 min.
Je n'ai rien trouvé pour le moment dans kodi pour gérer ce point.
Est-ce que quelqu'un arrive sur Kodi à garder plus de 10 min ?

**Comment by hotlittlewhitedog** [comment]
Je n'ai pas testé FranceTV mais j'ai eu le mème problème de 10 min en regardant un match de foot live (Coupe du monde en Russie). Finalement j'ai utilisé un stream IFR et il n'était plus coupé.

**Comment by wwark** [comment]
Bonjour, vous avez testé quelle chaîne France 2 ?
Il est possible qu'il applique la même restriction sur tous les événements sportifs.
Merci,
Wwark

**Comment by wwark** [comment]
Ce bug ne semble plus présent suite aux derniers retours d'utilisateurs.
Je vais donc fermer ce ticket.
N'hésitez pas à le rouvrir si besoin.
Merci,
Wwark
