### ISSUE TITLE
[IT - RTL.IT] Add content

### ISSUE THREAD

**Issue by darodi** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#704]
[IT - RTL.IT] Add live content

see 

- #385 

same thing for all radio tv lives here:
https://www.rtl.it/

- [x] https://www.rtl.it/radiofreccia-radiovisione/  **done**
- [x] https://www.rtl.it/radiovisione/
- [x] https://www.rtl.it/radio-zeta-radiovisione/
- [x] https://www.rtl.it/romeo-and-juliet-tv/
- [x] https://www.rtl.it/bro-and-sis-tv/
- [x] https://www.rtl.it/rtl-1025-extra/
- [x] https://www.rtl.it/rtl-1025-doc-tv/
- [x] https://www.rtl.it/rtl-1025-news-tv/
- [x] https://www.rtl.it/rtl-1025-best-tv/
- [x] https://www.rtl.it/rtl-1025-napule-tv/

We could also add replays

**Comment by joaopa00** [comment]
Je ne sais qu'lle serait la meilleure chose à faire ici: soit faire comme avec BFM Régions et mettre les choix dans un menu soit toutes les listées. Je pencherais plutôt pour la première solution mais peut-être as-tu u avis contraire?

**Comment by darodi** [comment]
oui je pensais renommer radiofreccia.py en rtl.py et faire un sous-menu en fonction des chaînes trouvées dans la section "on air" de
https://play.rtl.it/ via une méthode list_lives

**Comment by enigma131** [comment]
Merci. Fonctionne avec sous répertoires mais toujours pas de choix pour la résolution vidéo ? Ces choix sont possibles via Firefox. Exemple pour Radiofreccia et pour vlc : 
		<track>
			<location>https://streamcdnb4-dd782ed59e2a4e86aabf6fc508674b59.msvdn.net/live/S3160845/0tuSetc8UFkF/chunklist_b2816000.m3u8</location>
			<title>Radiofreccia 1920p</title>
			<duration>19190</duration>
			<extension application="http://www.videolan.org/vlc/playlist/0">
				<vlc:id>2</vlc:id>
				<vlc:option>network-caching=1000</vlc:option>
			</extension>
		</track>
		<track>
			<location>https://streamcdnb1-dd782ed59e2a4e86aabf6fc508674b59.msvdn.net/live/S3160845/0tuSetc8UFkF/chunklist_b1728000.m3u8</location>
			<title>Radiofreccia 1024p</title>
			<duration>16790</duration>
			<extension application="http://www.videolan.org/vlc/playlist/0">
				<vlc:id>3</vlc:id>
				<vlc:option>network-caching=1000</vlc:option>
			</extension>
		</track>
		<track>
			<location>https://streamcdnb1-dd782ed59e2a4e86aabf6fc508674b59.msvdn.net/live/S3160845/0tuSetc8UFkF/chunklist_b1128000.m3u8</location>
			<title>Radiofreccia 854p</title>
			<duration>16790</duration>
			<extension application="http://www.videolan.org/vlc/playlist/0">
				<vlc:id>4</vlc:id>
				<vlc:option>network-caching=1000</vlc:option>
			</extension>
		</track>
		<track>
			<location>https://streamcdnb1-dd782ed59e2a4e86aabf6fc508674b59.msvdn.net/live/S3160845/0tuSetc8UFkF/chunklist_b732000.m3u8</location>
			<title>Radiofreccia 640p</title>
			<duration>16790</duration>
			<extension application="http://www.videolan.org/vlc/playlist/0">
				<vlc:id>5</vlc:id>
				<vlc:option>network-caching=1000</vlc:option>
			</extension>
		</track>
		<track>
			<location>https://streamcdnb1-dd782ed59e2a4e86aabf6fc508674b59.msvdn.net/live/S3160845/0tuSetc8UFkF/chunklist_b332000.m3u8</location>
			<title>Radiofreccia 320p</title>
			<duration>19180</duration>
			<extension application="http://www.videolan.org/vlc/playlist/0">
				<vlc:id>6</vlc:id>
				<vlc:option>network-caching=1000</vlc:option>
			</extension>
		</track>

**Comment by darodi** [comment]
@enigma131 

Aller dans 

- addon setting
- quality and content
- video quality

choisir
`Dialog`

pour avoir le choix

**Comment by enigma131** [comment]
J'ai dialoque ici, car je veux choisir en fonction de ce que l'on fait ici ( je n'ai pas la fibre ...) .Pas de dialogue pour Rtl.it alors que je l'ai pour toutes les autres chaines , par exemple cstar ...

**Comment by enigma131** [comment]
Beta 14 , still no choice for video resolution

**Comment by darodi** [comment]
@enigma131 

tu es vraiment sûr que tu n'utilises pas inputstream adaptative?
si DIALOG est choisi, il y a le choix.
sinon le choix est dans inputstream adaptative

- `settings - inputstream adaptative`
- `stream selection`
choisir manually `select all streams`

![Clipboard01s](https://user-images.githubusercontent.com/4682830/159168325-c09342c7-9bf9-4624-8ad4-4ccbc3cfba8c.png)
![Clipboard02s](https://user-images.githubusercontent.com/4682830/159168331-17e2b215-00f3-4627-8fee-e88c6fa74d1d.png)
![Clipboard03s](https://user-images.githubusercontent.com/4682830/159168332-c3483a91-48df-4b21-88d9-420879cc505f.png)

**Comment by enigma131** [comment]
La première ligne est grisée chez moi:
![kodi](https://user-images.githubusercontent.com/31815445/159174114-798b78c0-5f14-4de9-ac15-c18b8ab6e6e3.png)

**Comment by darodi** [comment]
As-tu bien fait ceci?
- `Add-ons`
- `My Add-ons`
- `VideoPlayer inputstream`
- `inputstream adaptative`
- `configure`
- `settings - inputstream adaptative`
- `stream selection`
choisir `manually select all streams`

**Comment by enigma131** [comment]
Ah, j'étais jamais allé dans ce menu, les chaines Fr sont pas traitées come cela.
Cela fonctionne, en plus le réglage est gardé en mémoire chaine par chaine.
Super, c'est du bon boulot. Sujet clos.

**Comment by darodi** [comment]
on va essayer de rendre le choix des qualités un peu plus cohérent dans l'app

**Comment by enigma131** [comment]
C'est vrai que la méthode du dialogue pour chaque chaîne qui le propose est plus adapté dans mon cas. Pour un smartphone, il faudrait même un choix 'qualité minimale" pour ne pas 'taper' dans le forfait GSM.

**Comment by darodi** [comment]
Dans la config d'input stream adaptative, sur ton téléphone, tu peux choisir une valeur pour 

- Max bandwitdh 
- Max resolution general decoder
- Max resolution secure decoder
