### ISSUE TITLE
FranceTV Sport / Ubuntu

### ISSUE THREAD

**Issue by simonbpro** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#71]
Bonjour,
Impossible de lire les flux FranceTV Sports sur mon install Kodi 17.6 / Ubuntu 18.04 LTS.
Les autres channels FranceTV fonctionnent correctement. 
Voici la trace 
[trace_kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/2053862/trace_kodi.log)
Une idée de ce qui pourrait clocher ? 
Merci.

**Comment by wwark** [comment]
Bonjour,
La cause est liée à la version utilisé du plugin 0.1.12 (dernière release) qui ne fonctionnent pas avec les direct TV de FranceTV.
Un correctif a été apporté il y a quelques jours sur la branche de développement.

Vous pouvez télécharger le zip ici https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/tree/dev ou installer le répo betâ du plugin.

Merci,
Wwark.

**Comment by wwark** [comment]
autre point, les direct TV de FranceTV sport ne fonctionne que durant 10 min. Nous avons un autre ticket sur ce sujet.

**Comment by simonbpro** [comment]
Bonjour, 
Merci, c'est effectivement cela.. Je n'avais pas vu le correctif apporté ... Mea Culpa ! 
Et par contre j'avais bien vu le second point ... Je guette le correctif ;-)
Merci pour le coup de main.
