### ISSUE TITLE
M6 Replay - Buffering systématique au bout de 45-55min (Top Chef)

### ISSUE THREAD

**Issue by Shasdo** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#716]
### Describe the bug
Je lance un Replay de Top Chef, la lecture est parfaite et au bout d'un certain temps et cela quelque soit l'épisode, du buffering systématique apparait au bout de 45-55min environ. 
Au début, espacés de 2-3 min et rapidement ca devient infernal, je n'ai malheureusement pas été en mesure de dépasser les 1h de replay ou presque.

### Your environment
 - Shield Pro 2019 - Android 9.0.1 (A jour)
 - Kodi Matrix 19.3
 - Catch Up TV & More v0;2;36+matrix.1 (App Repo)

### Debug log
Pas de log, dites moi quoi remonter et je regarderai ce que je peux faire.

**Comment by darodi** [comment]
Tu peux peut être essayer de diminuer la bande passante ou la résolution?

Comme ceci:

- `Add-ons`
- `My Add-ons`
- `VideoPlayer inputstream`
- `inputstream adaptive`
- `configure`
- `settings - inputstream adaptive`
- `stream selection`
choisir `manually select all streams`

Ensuite on peut choisir la qualité par l’icône engrenage 

![Clipboard01s](https://user-images.githubusercontent.com/4682830/159168325-c09342c7-9bf9-4624-8ad4-4ccbc3cfba8c.png)
![Clipboard02s](https://user-images.githubusercontent.com/4682830/159168331-17e2b215-00f3-4627-8fee-e88c6fa74d1d.png)
![Clipboard03s](https://user-images.githubusercontent.com/4682830/159168332-c3483a91-48df-4b21-88d9-420879cc505f.png)


ou alors dans la config d'input stream adaptive, tu peux choisir une valeur pour 

- Max bandwitdh 
- Max resolution general decoder
- Max resolution secure decoder

**Comment by wongounay** [comment]
Bonjour,
Même problème avec plusieurs Replay M6.

Shield 2017
Kodi 19.2
Catch-up last stable

**Comment by joaopa00** [comment]
Je pense pas que cela sit un problème de Catchuptvandmore. Si 225/75 représente des kilo-octets, ta bande passante est trop petite pour la HD. Tu dois baisser la qualité, conseil déjà donné par Darodi.

**Comment by wongounay** [comment]
C'est en Mbps.
Je suis en train de tester en ce moment, j'ai vu un épisode de 50min sans problème, mais au second ça s'est remis à charger toutes les 30s.

**Comment by joaopa00** [comment]
Peux-tu essayer sur un PC?  C'est certainement un problème avec Shield.

**Comment by wongounay** [comment]
Je n'ai pas de PC a disposition avec Kodi installé.

J'ai retesté plusieurs fois sur Shield. Je confirme que la qualité ne change rien, ça marche parfaitement en 720p pendant un temps (1h environ), puis ça charge en permanence, même en très faible qualité.

L'heure à laquelle je lance l'épisode ne change rien.

Si je met Stop quand ça commence à charger, que j'attend 1 minute, et que je reprends l'épisode, ça refonctionne sans charger pendant 5-10min.

Si je kill Kodi, que je regarde autre chose et que j'y reviens, ça fonctionne parfaitement comme au premier lancement.

Si je kill Kodi et que j'attends 1 minute, ça fait comme si je met sur Stop, ça remarche pendant 5-10min et ça charge.

C'est comme si 6play réduisait le débit si la session dépasse 50min.

**Comment by joaopa00** [comment]
Sur le site [IA](https://github.com/xbmc/inputstream.adaptive/issues/877) on lit que certains ont le même problème et que le problème est résolu en changeant la version de WIdevine. Tu pourrais tester ça.

**Comment by Xilophon3** [comment]
Salut, j'ai exactement le même problème sur Android TV, Kodi 19.3, je n'arrive pas à résoudre le problème, une solution ?

**Comment by joaopa00** [comment]
C'est seulement pour les videos e Top Chef ou toutes les vidéos?

**Comment by joaopa00** [comment]
Testé sur AndroidTv Saison 13 episode 1 et le complément de top chef. Pas de problème. Poivez-vous donner la video qui ne fonctionne pas?

**Comment by Xilophon3** [comment]
> C'est seulement pour les videos de Top Chef ou toutes les vidéos?

Je crois que c'est uniquement sur les Replay de 6play.

**Comment by joaopa00** [comment]
Il faudrait le log

**Comment by Xilophon3** [comment]
Comment faire (désolé je débute).

**Comment by wongounay** [comment]
Bonjour, 
J'ai retesté plusieurs fois, le comportement est bizarre.
- j'ai essayé "chasseurs d'appart" (50min), j'ai pu tout regarder mais c'est toujours très lent sur les 10/20 dernières minutes. Mettre sur stop aide à avancer un peu, changer la qualité n'arrange rien.
- j'ai aussi essayé "recherche appartement ou maison" (1h30). J'ai pu regarder le premier en 720p pendant 1h sans interruption, puis c'est devenu vraiment impossible. Mettre sur stop ou quitter ne change rien, ça fait que charger. Je n'ai pas pu le terminer.
- ce qui est vraiment bizarre, c'est que depuis cet épisode, tous les autres chargent directement, dès le lancement. J'ai tenté différents épisodes a different moments, rien ne marche. (Toujours pour "recherche maison ou appartement")

**Comment by Xilophon3** [comment]
Idem, pourtant j'ai une bonne connexion
![IMG_20220402_101512](https://user-images.githubusercontent.com/102830809/161374018-c803b7cb-53d2-4fc6-95f5-9bb0b955a4b2.jpg)

Je suis entrain de tester sur pc avec la même configuration, pour l'instant je n'ai pas de problème je laisse tourner pour voir.

**Comment by Arias800** [comment]
> [Edit] Sur ma TV android, j'ai plus d'image avec les replays M6 mais uniquement le son, pourtant je n'ai rien changé.

Il faut impérativement que l'accélération matérielle soit activée dans les paramètres de Kodi.

**Comment by Xilophon3** [comment]
Ok j'ai tout réinstallé proprement, j'ai récupéré l'image et le son, maintenant reste à résoudre le pb de buffering sur tv android.

**Comment by wongounay** [comment]
Samedi, j'ai presque pu regarder 2 épisodes complets de "recherche appartement ou maison" (1h30 / épisode) en 720p (qualité max) sans aucun changement.
Ça a commencé à charger à la fin du 2ème.

Dimanche j'ai essayé d'en lancer un 3eme, je n'ai pas pu le voir, ça ne faisait que charger.

**Comment by Xilophon3** [comment]
C'est vraiment aléatoire, j'ai pas l'impression qu'il y ait ce problème sur les Replay de TF1 par exemple, j'ai regardé kohlanta sans problème, j'ai que des problèmes sur les Replay de M6.

**Comment by Shasdo** [comment]
Je n'a pas eu de soucis sur le dernier Replay Top Chef S13e07 (Guerre des Restos) fini à 21h samedi soir.

Je n'ai pas changé les paramètres, donc stream en qualité max.

Je suis fibré Sosh 300/300, Shield en RJ45 avec Fibre, je stream du film de 20Go via Plex depuis un serveur extérieur à mon réseau local.

Quand à faire des test de lecture, le problème c'est qu'il faut le faire tourner 45min-1h avant de voir si il y a un soucis.
Pas facile à caler dans l'emploi du temps.

Vu le caractère aléatoire, peut-on envisager que ca vienne de M6 qui "brident" les utilisateurs, voir ceux de catchup spécifiquement ?

**Comment by mbLc** [comment]
Bonsoir, j’ai le même problème avec une shield et sur les replay de 6play. Perso je regarde les replay de Pékin express, épisode 6 et 7, ça buffer énormément quasiment des le début je n’ai pas besoin d’attendre 45 minutes.

Ça a dû me le faire également sur les épisodes d’avant mais je me disais que ça venait de 6play et non pas de l’add-on.

**Comment by Xilophon3** [comment]
Alors nouveau test aujourd'hui, j'ai pris le dernier épisode de Pékin Express et top chef, sur ma TV Android ça buffer toutes les 2 minutes, j'ai pris les même épisode sur PC et la idem problème de buffering au bout de quelques instants, donc j'en conclu que ça vient bien de 6play ou de catchuptv.

**Comment by joaopa00** [comment]
Sur PC,  tu as lu la vidéo à travers Kodi ou directement dans le navigateur?

**Comment by Xilophon3** [comment]
Avec Kodi 19.4

**Comment by joaopa00** [comment]
Tu peux tester avec un navigateur?

**Comment by Arias800** [comment]
Avec Kodi 19, Inpustream Adaptive n'a pas de buffer et ça pose pas mal de problème de lecture.
La version Kodi 20 règlera le problème normalement.

**Comment by joaopa00** [comment]
Tu vas sur le site de M6Replay et tu testes une vidéo qui pose problème

**Comment by Xilophon3** [comment]
Ah pardon j'avais mal compris, via 6play sur navigateur ou via l'application officielle 6play je n'ai pas de problème avec les Replay.

**Comment by Arias800** [comment]
@joaopa00 Tu as raté ta mention :p
Pour ce qui est de ta question, non ce ne sera pas backportée.
Il y a eu beaucoup trop de changement pour que ce sois possible.

**Comment by Xilophon3** [comment]
Je vais patienter et atteindre la version 20 :)

**Comment by joaopa00** [comment]
Ce n'est donc pas un problème de Catchuptvandmore. Je ferme...
