### ISSUE TITLE
Chaînes françaises (direct) hors-service

### ISSUE THREAD

**Issue by joaopa00** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#726]
Les chaînes françaises suivantes ne fonctionnent plus:
Weo
TV Vendée
TVPI Télévision d'ICI
TébéSud
Tébéo

**Comment by joaopa00** [comment]
TV Vendée fixé

**Comment by f28gin** [comment]
toujours aussi efficace @joaopa00  ;-)

**Comment by joaopa00** [comment]
TVPI fixé

**Comment by joaopa00** [comment]
TEBE* fixé

**Comment by joaopa00** [comment]
WEO fixé pour terminer. Malheureusement les videos de Weo souffrent du même bug que les vidéos de Dailymotion avec InputStream adaptive. On ne peut donc l'utiliser.

**Comment by joaopa00** [comment]
Tous les lives sont de retour. Je ferme.
