### ISSUE TITLE
Impossibilité d'avoir TF1

### ISSUE THREAD

**Issue by camillebuire** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#728]
### Describe the bug
A clear and concise description of what the bug is: je suis dans l'impossiblité d'avoir TF1

### To Reproduce
Steps to reproduce the behaviour:
1. J'allume mon android BOX
2. Je lance Kodi
3. J'ouvre mon extension catch up tv & more
4. Je lance TF1
5. J'ai un message d'erreur : « Echec de lecture d’un ou plusieurs fichiers. Consulter le journal pour plus d’informations » ce n'est pas systématique mais c'est très souvent 8 fois sur 10

### Expected behaviour
A clear and concise description of what you expected to happen: Je veux pouvoir regarder les chaines du groupe TF1

### Screenshots
If applicable, add screenshots to help explain your problem:

![image](https://user-images.githubusercontent.com/80039900/159880090-94323620-059b-4618-802d-1c877fb5fdd5.png)

### Your environment
 - Android box MIBOX3 version 9
- version du noyau : 4.9.113
- Build PI.3934 release-keys
 - Kodi version: Matrix 19.3
 - Catch-up TV & More version: 0.2.38~beta15
 - Installation method: installation depuis un fichier ZIP avec depot sur https://catch-up-tv-and-more.github.io/repo/

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy): Je ne parviens pas à récupérer les logs sur mon disque dur externe impossible de copier/coller

**Comment by camillebuire** [comment]
[kodi (1).log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/8340618/kodi.1.log)


Bonjour,
Voici les logs de mon kodi avec l'erreur
Merci pour votre retour

**Comment by joaopa00** [comment]
Ce genre de problème est les pires à résoudre!! Ils sont généralement liés à la façon dont se comportent les librairies de bas niveau utilisées. Tu peux essayer sur un ordinateur si tu as le même problème?

**Comment by joaopa00** [comment]
Malheureusement, du côté de Catchuptvandmore, on ne peut rien y faire. Ilfaudrait que tu reportes le bug à Kodi.
C'est certainement un problème de timing dans les requêtes internet.

**Comment by camillebuire** [comment]
c'est vraiment étrange car l'incident se prduit depuis que j'ai déménagé. J'ai tenté de désinstaller et réinstaller mais rien y fait...
Merci quand même de votre aide.

**Comment by joaopa00** [comment]
Puisque l'erreur est 403 (forbidden), peut-être est-ce un problème de droits liés à Widevine. La dernière mouture de WIdevine pose des problèmes à beaucoup de monde (voir [IA](https://github.com/xbmc/inputstream.adaptive/issues/877))
Si récemment tu as eu une mise à jour de WIdevine, peut-être peux-tu essayer de revenir à une version plus ancienne sur laquelle tu n'avais aucun problème.

**Comment by camillebuire** [comment]
Au risque de paraitre bête comment passe-t-on à une ancienne version de WIdevine ?

**Comment by camillebuire** [comment]
Merci
