### ISSUE TITLE
Erreur lors du lancement d'une chaîne M6 : "echec de lecture d'un ou plusieurs fichiers"

### ISSUE THREAD

**Issue by 0Gentleman** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#739]
Bonjour,
Ayant fraîchement installé Catch-up-TV-and-More sur mon raspberry je suis dans l'impossibilité de lire un Replay ou live d'une chaîne du groupe M6. Les autres fonctionnent.
J'ai un message d'erreur "echec de lecture d'un ou plusieurs fichiers" me demandant de vérifier les logs. J'ai beau les regarder et chercher des solutions je ne comprends pas comment solutionner le problème.

J'ai essayé de comparer les éléments et les versions avec mon installation sur une mi box mais je ne vois pas de différence.

Je vous joins le log !

Merci beaucoup à celui qui pourra me venir en aide. Catch-up-TV-and-More est vraiment une application de fou furieux et j'aimerais vraiment pouvoir en bénéficier sur mon installation.

### Screenshots
![20220326_095611](https://user-images.githubusercontent.com/23058608/160233058-845d0e72-cb2f-41e4-9799-84c2aecb586a.jpg)

### Your environment
 - Raspberry-Pi 4

 - Operating system version/name:
 - Kodi version: 19.1
 - Catch-up TV & More version: 0.2.36+matrix.1
 - Installation method : OSMC 2021.08-1 (De même avec la version de mars 2022)

### Debug log
https://paste.kodi.tv/ehohahobig

**Comment by darodi** [comment]
> 2022-03-26 09:54:27.220 T:566     FATAL <general>: [script.module.inputstreamhelper] ['ldd', '/home/osmc/.kodi/cdm/libwidevinecdm.so'] cmd failed.
> 2022-03-26 09:54:27.220 T:566     FATAL <general>: [script.module.inputstreamhelper] Failed to check for missing Widevine libraries.

il faudrait installer widevine

- extensions
- mes extensions
- extensions programmes
- input stream helper
- configurer
- (re)installer la bibliotheque widevine CDM

et rebooter le rpi


S'il y a un problème de saccades à la lecture avec la dernière version de widevine, il se peut qu'il faille installer une version plus ancienne de la bibliothèque et le plus simple est de passer par le repo de SlyGuy

cf.
- https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/565#issuecomment-1052635675
- https://github.com/xbmc/inputstream.adaptive/issues/877#issuecomment-1021644008

ça marche mieux avec cette version apparemment
**4.10.2252.5**

>  Follow this to force update: https://www.matthuisman.nz/2021/07/force-update-slyguy-add-ons.html
>  And then after its updated, Services > Slyguy Common > Advanced > Re(install) Widevine CDM

**Comment by 0Gentleman** [comment]
Bonjour @darodi  et merci pour cette réponse si rapide ! 
Widevine était bien installé mais j'ai fais la manip que tu m'as expliqué et rebooté le pi
J'ai toujours le même message d'erreur, voici le nouveau logo
https://paste.kodi.tv/uxopibiqad

Dans le doute je vais essayer de mettre la version 4.10.2252.5

**Comment by darodi** [comment]
@0Gentleman 

je suis sous la version suivante sans problème: 

- NAME="OSMC", VERSION_ID="2022.03-1"
- widevine: 4.10.2252.5


voir aussi ceci, une **mise à jour de libc6** peut expliquer que ldd arrive à charger la lib

https://github.com/xbmc/inputstream.adaptive/issues/678#issuecomment-1030918662

> On OSMC/Kodi 18 I found that I only needed to run:
> ```
> sudo apt-get update
> sudo apt-get install --only-upgrade libc6
> curl https://k.slyguy.xyz/.decryptmodules/widevine/4.10.2252.0-linux-armv7.so | sudo tee /home/osmc/.kodi/cdm/libwidevinecdm.so >/dev/null
> sudo reboot
> ```

**Comment by 0Gentleman** [comment]
@darodi 
J'ai mis à jour libc6 et ça semble fonctionner !!
Merci beaucoup tu as été super efficace et rapide je ne pensais vraiment pas y arriver ! 
Je te remercie sincèrement
Bon weekend :-)

**Comment by darodi** [comment]
@0Gentleman @joaopa00 
Peut être fermé je pense.
Merci

**Comment by joaopa00** [comment]
Je ferme donc....
