### ISSUE TITLE
Saccades dans le stream et installation widewine / stuttering while streaming and Widewine install

### ISSUE THREAD

**Issue by darodi** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#740]
### saccades dans le stream et installation widewine

Dans le cas de cette erreur:

> 2022-03-26 09:54:27.220 T:566     FATAL <general>: [script.module.inputstreamhelper] ['ldd', '/home/osmc/.kodi/cdm/libwidevinecdm.so'] cmd failed.
> 2022-03-26 09:54:27.220 T:566     FATAL <general>: [script.module.inputstreamhelper] Failed to check for missing Widevine libraries.

il faut (re)installer widevine

- extensions
- mes extensions
- extensions programmes
- input stream helper
- configurer
- (re)installer la bibliotheque widevine CDM
- **et rebooter le rpi**

---

**La dernière version Widevine `4.10.2449.0` devrait fonctionner correctement.**

~~S'il y a un problème de saccades à la lecture avec la dernière version de widevine, il se peut qu'il faille installer une version plus ancienne de la bibliothèque et le plus simple est de passer par le repo de SlyGuy~~

~~https://www.matthuisman.nz/2020/02/slyguy-kodi-repository.html~~

~~ça marche mieux avec cette version apparemment
**`4.10.2252.5`**~~

>  ~~Follow this to force update: https://www.matthuisman.nz/2021/07/force-update-slyguy-add-ons.html~~
>  ~~And then after its updated, Services > Slyguy Common > Advanced > Re(install) Widevine CDM~~

~~_Originally posted by @darodi in https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/739#issuecomment-1079661647_~~

---

### mise à jour de libc6 (OSMC)
voir aussi ceci, une **mise à jour de libc6** peut expliquer que ldd arrive à charger la lib

https://github.com/xbmc/inputstream.adaptive/issues/678#issuecomment-1030918662

> On OSMC/Kodi 18 I found that I only needed to run:
> ```
> sudo apt-get update
> sudo apt-get install --only-upgrade libc6
> curl https://k.slyguy.xyz/.decryptmodules/widevine/4.10.2449.0-linux-armv7.so | sudo tee /home/osmc/.kodi/cdm/libwidevinecdm.so >/dev/null
> sudo reboot
> ```

-----
### stuttering while streaming and Widewine install

If you get this error:

> 2022-03-26 09:54:27.220 T:566     FATAL <general>: [script.module.inputstreamhelper] ['ldd', '/home/osmc/.kodi/cdm/libwidevinecdm.so'] cmd failed.
> 2022-03-26 09:54:27.220 T:566     FATAL <general>: [script.module.inputstreamhelper] Failed to check for missing Widevine libraries.

You need to (re)install widevine

- Add-ons
- My add-ons
- Program add-ons
- input stream helper
- configure
- (re)install Widevine CDM library
- **and reboot your machine/rpi**

---

**last Widevine version `4.10.2449.0` should work correctly**

~~If there is a stuttering playback issue with the latest version of Widevine, you may need to install an older version of the library and the easiest way is to use the SlyGuy repository~~

~~https://www.matthuisman.nz/2020/02/slyguy-kodi-repository.html~~

~~seems to work better with this version~~
~~**`4.10.2252.5`**~~

>  ~~Follow this to force update: https://www.matthuisman.nz/2021/07/force-update-slyguy-add-ons.html~~
>  ~~And then after its updated, Services > Slyguy Common > Advanced > Re(install) Widevine CDM~~

### update libc6 (OSMC)
see this, **updating libc6** can make ldd able to load the library

https://github.com/xbmc/inputstream.adaptive/issues/678#issuecomment-1030918662

> On OSMC/Kodi 18 I found that I only needed to run:
> ```
> sudo apt-get update
> sudo apt-get install --only-upgrade libc6
> curl https://k.slyguy.xyz/.decryptmodules/widevine/4.10.2449.0-linux-armv7.so | sudo tee /home/osmc/.kodi/cdm/libwidevinecdm.so >/dev/null
> sudo reboot
> ```

-----------

cf.
- https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/565#issuecomment-1052635675
- https://github.com/xbmc/inputstream.adaptive/issues/877#issuecomment-1021644008
- https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/739#issuecomment-1079661647

**Comment by darodi** [comment]
@joaopa00 

Peux-tu mettre cette issue en sticky issue?
Elle revient souvent, ça éviterait de nouvelles issues

**Comment by joaopa00** [comment]
Fait. Merci pour le tutoriel.

**Comment by darodi** [comment]
> Fait. Merci pour le tutoriel. Peut-être peux-tu parler de la mise à jour de libc?

ajouté

**Comment by joaopa00** [comment]
On peut estimer que c'est résolu, je suppose...
