### ISSUE TITLE
C17 : pas de son et blocage au bout de 10 secondes

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#748]
Tout est dans le titre, dernière beta et kodi 19.4 Linux.

Extrait du log : 

2022-03-28 17:11:23.470 T:22387    INFO <general>: Loading skin file: VideoFullScreen.xml, load type: KEEP_IN_MEMORY
2022-03-28 17:11:23.474 T:22392 WARNING <general>: ActiveAE - large audio sync error: 338061.670010
2022-03-28 17:11:23.476 T:22392 WARNING <general>: ActiveAE - large audio sync error: 338060.671902
2022-03-28 17:11:23.561 T:22418    INFO <general>: found KodiSink
                                                   output sink: /org/pulseaudio/core1/sink1
                                                   ----------
                                                   self_sink   : /org/pulseaudio/core1/sink1
                                                   out_sink    : /org/pulseaudio/core1/sink0
                                                   should_out  : /org/pulseaudio/core1/sink0
                                                   self_type   : filter
                                                   driver      : module-equalizer-sink.c
                                                   sink is fiter
                                                   out is corret
                                                   ----------------
                                                   end-----------
                                                   
2022-03-28 17:11:23.809 T:22392 WARNING <general>: ActiveAE - large audio sync error: 337960.829317
2022-03-28 17:11:23.970 T:22392 WARNING <general>: ActiveAE - large audio sync error: 337860.737013
2022-03-28 17:11:23.970 T:22392 WARNING <general>: ActiveAE - large audio sync error: 337760.739689

C8 et Cnews du même groupe Ok

**Comment by joaopa00** [comment]
Même problème sans Kodis ur un PC en utilisant un navigateur ou MPV. Problème du site, pas de Catchuptvandmore.

**Comment by enigma131** [comment]
C'est toujours HS ce matin.

**Comment by enigma131** [comment]
La chaîne live fonctionne ici : https://www.canalplus.com/chaines/cstar , de quel site tu parles ?

**Comment by joaopa00** [comment]
Le site utilisé est [dailymotion](https://www.dailymotion.com/video/x5gv5v0)

**Comment by enigma131** [comment]
Ok je  comprends mieux. Ils en mettent du temps chez dailymotion pour réparer ...

**Comment by enigma131** [comment]
La question est désormais: le site Dailymotion va-t-il être réparé pour C17 ou ont-il changé de flux? Pas possible 5 jours d'interruption....

**Comment by joaopa00** [comment]
mpv https://www.dailymotion.com/video/x2zpc0q
[ytdl_hook] ERROR: dailymotion said: Channel offline. 
[ytdl_hook] youtube-dl failed: unexpected error occurred 
Failed to recognize file format.

Exiting... (Errors when loading file)

**Comment by enigma131** [comment]
Toujours cassé. Faut-il changer de source ?

**Comment by Arias800** [comment]
J'en ai marre des stream Dailymotion qui ne sont pas mis à jour.
Je suis donc en train d'implémenter les flux officiels du site.

**Comment by Arias800** [comment]
Pull requests fait.
Il ne reste plus qu'à attendre la validation.

**Comment by joaopa00** [comment]
La PR est mergée. Je ferme cette issue. Il ne faudra pas oublier de faire une possibilité de choisir les liens dailymotion pour nos compatriotes d'outre-mer.
