### ISSUE TITLE
Direct France TV inaccessible 

### ISSUE THREAD

**Issue by QuentinLf** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#753]
Bonjour,

J'ai installé Kodi puis Catch Up & More sur une télé androïd. Quand je lance un direct d'une chaine de France TV (France 2 ou France 3), ça charge 20 secondes puis j'ai un message indiquant : "Échec de lecture d'un ou plusieurs fichiers. Consulter le journal pour plus d'informations". J'ai essayé de désinstaller et réinstaller catch-up mais il y a toujours le même soucis. J'ai la version 0.2.382beta21.

Pourtant fin janvier je pouvais voir France 2 en direct (pendant les JO), la chaine mettait 20secondes à se charger mais ça fonctionnait.

Y a t'il eu des changement du côté des chaine France tv ou dans catch-up ?

Merci de votre aide

**Comment by joaopa00** [comment]
Pas de problème de lecture chez moi. J'utilse aussi AndroidTV.
Dans le pire des cas, desinstalle et reinstalle complètement Kodi.

**Comment by joaopa00** [comment]
Il y a eu une modification pour le direct de France TV . Peux-tu faire un test?
Voici un lien à téléchargre pour tester:[version de test](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/archive/refs/heads/dev.zip)

**Comment by joaopa00** [comment]
Ca doit être fixé dans git. Je ferme. Tu peux réouvrir si le problème persiste.
