### ISSUE TITLE
CNews problème d'encodage sur les Replay

### ISSUE THREAD

**Issue by wwark** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#76]

**Comment by gilles0606** [comment]
ok, dés que tu commit demande si tu as besoins que je teste...

**Comment by wwark** [comment]
OK merci :) je te tiens au courant.

**Comment by wwark** [comment]
Normalement avec la dernière version 0.1.14~beta006 les problèmes d'encodage pour CNews sont fixés.
Je ferme le ticket.
N'hésite pas à le rouvrir si tu vois encore des caractères mal encodé.

**Comment by gilles0606** [comment]
hello @wwark 
tout est nikel je confirme l'encodage est parfait...

une fois de plus... Merci
