### ISSUE TITLE
Live TV Integration - Manual Channel Order ?

### ISSUE THREAD

**Issue by Shasdo** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#764]
Hello,

**Is there a way to give manually each selected channel a specific number ?**

I would like to follow the french TNT order and eventually skip some number for those channel that I didn't add (mostly news channel).
But I still would like the numbering to be true to the TNT.

Am I missing an option ? Maybe it is not CuTvaM related but on Kodi's side?

I did not tagged this question as a feature request or issue, feel free to do so if needed.

Keep up the good work.

Best regards

**Comment by darodi** [comment]
- Go in TV menu
- use the "C" key, or open the context menu with your remote
- choose manage

![image](https://user-images.githubusercontent.com/4682830/166310433-1f4e2ed9-a0cc-42db-8d39-b7e6e80ab9ec.png)

- choose channel manager
- select a channel
- use the "C" key, or open the context menu with your remote

![image](https://user-images.githubusercontent.com/4682830/166310625-45bd8e72-84b6-47a6-9763-326e0b66b077.png)

- choose move

you can change the order.

**Comment by joaopa00** [comment]
Closing....
