### ISSUE TITLE
France TV , plus de son et résolution médiocre

### ISSUE THREAD

**Issue by enigma131** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#768]
Depuis la MAJ beta 23, plus de son et résolution vidéo médiocre
Kodi 19.4 
Peut être la source ?

**Comment by joaopa00** [comment]
Pas de problème pour moi. Son correcte et choix possibles des résolutions.

**Comment by enigma131** [comment]
Flux audio : unknow , et qualité 640 * 368, pas de choix possible.  Vais essayer sous W10

**Comment by enigma131** [comment]
J'ai trouvé: ce sont mes favorits qui sont cassés. Comment c'est possible ?

**Comment by joaopa00** [comment]
Le problème étant résolu, je ferme.
