### ISSUE TITLE
Catch up et Freplay ne fonxtionnent pas

### ISSUE THREAD

**Issue by lyvio** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#77]
Derniere version des deux addons: check
VPN activé avec IPVanish check
Android box MXQ pro: check
Kodi 17.6 krypton: check

Tout fonctionnait tres bien jusqu'à vendredi. J'ai changé d'appartement et depuis, plus rien ne fonctionne. La seule difference est que j'utilise la wifi au lieu du cordon now. Alors ca serait facile de dire de faire le test mais je n'arrive pas à crore que ca soit "ce probleme" là.

Tout semble fonctionner mais à la fin, j'ai: one or more items failed to play.....

**Comment by wwark** [comment]
Bonjour @lyvio,
Est-ce que tu as testé plusieurs replay / direct tv ? les erreurs sont à chaque fois?
Est-ce que tu as aussi le souci sur le plugin.video.youtube par exemple?

Pourrais-tu nous fournir les logs de Kodi ?
D'avance merci,
Wwark.

**Comment by lyvio** [comment]
Bonjour Wwark, 

Alors tf1 fonctionnait mais pas M6. 
Apres different manip (reinstallation, update, debug...), plus rien ne fonctionne et pareil pour freplay. 
Je te joins un lien qui permet de voir l'erreur en entier. 
https://paste.kodi.tv/oberibuzed

Lyvio

**Comment by wwark** [comment]
Bonjour @lyvio,
Merci pour le log.

Le plugin arrive a récupérer le flux video et le propose à Kodi.
https://lbv2.cdn.m6web.fr/v1/resource/s/usp/mb_sd3/0/2/9/Recherche-apparteme_c12054861_Gregoire-et-Ste/Recherche-apparteme_c12054861_Gregoire-et-Ste_unpnp.ism/Manifest.m3u8?expiration=1530787356&scheme=https&groups%5B0%5D=m6web&customerName=m6web&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MzA3NTEzNTUsIm5iZiI6MTUzMDc1MTM1NSwiZXhwIjoxNTMwNzg3MzU2LCJyX2hhc2giOiJiYjdhODU2MmExZWRmZGNkZDQyMGZmMTQyNWMzMTQ1NTNlMTFiZDI5In0.MOTonCqDKecbpTbcqR0bPNbq0wD0xhBE3-1ZnRI4uiA

Lors de la lecture de ce flux vidéo, Kodi renvoie une erreur "CCurlFile::FillBuffer - Failed: SSL connect error(35)"
Dans la documentation de curl 'https://curl.haxx.se/libcurl/c/libcurl-errors.html'
CURLE_SSL_CONNECT_ERROR (35)
A problem occurred somewhere in the SSL/TLS handshake. You really want the error buffer and read the message there as it pinpoints the problem slightly more. Could be certificates (file formats, paths, permissions), passwords, and others. 

Le plugin fait donc son boulot mais Kodi n'arrive pas lire le flux vidéo. Dans les logs, la version de Kodi utilisé est 17.6. 
Ce week-end j'aurai un peu de temps pour regarder les forums pour voir si le cas est déjà arrivé.

Suivant la configuration, il est possible de que ce soit lié au VPN.
Il faudrait récupérer le flux video dans les logs et tester sur VLC depuis votre connexion internet pour voir si le problème est au niveau réseau ou dans une configuration dans Kodi.

Merci,
Wwark.

**Comment by lyvio** [comment]
Bonjour Marc, 

Merci pour l'aide. Ce qui est fou, c'est que TF1 fonctionne. D'autres chaines fonctionnent egalement mais fonctionnement tres lentement. Quant à M6, tu sens qu'il veut s'ouvrir car j'ai le triangle de lecture qui s'affiche mais c'est comme si il n'arrivait à joindre le flux lui permettant de fonctionner. 
J'ai une forte impression que c'est du à mon internet que j'ai changé. Je vais faire des changements demain pour ca. Je te tiendrais au courant mais si jamais tu trouves une meilleure idée, please let me know. 
Merci
Lyvio

**Comment by wwark** [comment]
Bonjour Lyvio,
Je pensais que rien ne fonctionnait. Vous avez que des erreurs pour M6 ? Est-ce que vous avez fait des changements depuis votre précédent message.
Est-ce qu'il est possible d'avoir l'erreur dans les logs si elle est différente?
Il est possible aussi que M6 bloque certains VPN. Vous êtes dans quel pays ?

Merci,
Wwark.

**Comment by lyvio** [comment]
Salut Marc, 
TF1 ne fonctionnait pas et puis ca fonctionne. Bon apres, j'ai toujours quelques ralentissement du a ma mauvaise connection internet que je vais arranger mais M6 ne fonctionne pas. 
Voici le log que j'ai: https://paste.kodi.tv/doriruroko

En esperant que ca aide. Ce que je comprends pas c'est que fonctionnait tres bien et puis maintenant non. 
Mon VPN est à jour et me montre connecté en France.

Lyvio T.

**Comment by lyvio** [comment]
Hey Marc, 

la connexion est tres lente. j'ai pense a la meme chose donc j'ai fait des modifications d'emplacement de ma box pour voir si ca pouvait fixer le probleme. Au pire je vais upgrader mon internet. 
J'ai teste m6 replay avec mon phone (comme mon vpn est aussi sur mon phone) et ca fonctionne tres bien, genre pas de ralentissement rien du tout. ce qui est drole c'est qu'au moment ou je regardais sur mon phone, j'etais a meme pas 1m de ma box. 
je vais tenter de voir les settings de kodi. Apparemment Kodi m'a fait voir que catch up avait une mise a jour (bien que je pensais avoir toutes les mises a jour). Je suis entrain d'installer et je tiens au courant. 

Lyvio

**Comment by wwark** [comment]
Hello Lyvio,
Je pense que la mise à jour du plugin ne changera rien. Le soucis est au niveau de Kodi.
Autre point, le device Android utilisé pour faire tourner Kodi possède une vielle version du WIFI voir peut être des problèmes avec la box WIFI ? Si vous installer l'application M6 replay sur ce device est-ce que la lecture video est normale ou lente?

Autre point à tester sont avec l'activation ou non de ces propriétés pour voir voir si ça change quelques choses 
![image](https://user-images.githubusercontent.com/469461/42611975-9f5dca5e-85d3-11e8-9fc8-e5ca5b5885d6.png)

Merci,
WWark

**Comment by lyvio** [comment]
Bonjour Marc, 

tu avais totalement raison car la mise à jour du plugin n'a rien changé. J'ai déplacé ma box pour la wifi, et le problème persistait. Je me suis dis donc que je vais suivre tes conseils: 
- verifier Imputstream adaptive is checked: Yes
- verifier RTMP Input is checked: Yes

le problème persistait.....Je ne savais de quelle application tu parlais pour M6 donc j'ai pas pus essayer. Existe t'il un plugin pour M6 uniquement sur Kodi krypton? 

J'ai donc changé les options avancées de Kodi via le fichier advancesettings.xml ce qui me permet aujourd'hui de voir des series sans aucun ralentissement mais M6, w9 (je pense toutes les chaines liées à M6) ne fonctionnenent tjrs pas. 

Alors je veux essayer de brancher directement ma box à mon modem pour voir si c'est vraiment un problème de connexion mais ca me parait bizarre que les autres chaines fonctionnent, mais pas M6.

Je suis le seul avec ce problème jusqu'à maintenant?

Merci pour ton aide. 

Lyvio T.

**Comment by wwark** [comment]
Bonjour Lyvio,
Je pensais à l'application Android de M6Play. Il est possible qu'il n'utilise pas les mêmes flux mais ça pourrait être un bon test.

Les direct tv et les replays sont completements différent d'une chaîne à l'autre et le test n'est pas suffisant.
Je vais vérifier de nouveau de mon côté pour voir si le replay M6 sont en erreur.

Est-ce que d'autres personnes ont le même soucis ?
Merci,
Wwark

**Comment by wwark** [comment]
Hi,
Zone interdite de M6 n'est pas géolocalisé normalement. Est-ce qu'il possible de faire un test sans le VPN ?

Merci,
Wwark

**Comment by lyvio** [comment]
Salut Marc, 

Bizarre, mais ce matin j'ai déconnecté le vpn for essayer Zone interdite de M6 et ca a fonctionné.
Une explication? est-ce seulement M6?

Merci, 
Lyvio Talcone

**Comment by wwark** [comment]
Bonjour Lyvio,

Comme indiqué plus haut chaque chaîne est différente. La meilleur compatibilité pour les chaînes françaises est d'utiliser le plugin en France.
Le fait de passer par un VPN permet d'acceder à des contenus géolocalisés mais ce n'est pas toujours garanti. (Avoir plusieuirs VPN ? pas sûr non plus que ce soit la bonne solution)
Certains des contenus ne sont pas géolocalisés comme pour M6 zone interdite, France 2 (JT), etc .....
Pour le cas de M6 pourquoi ça bloque via le VPN que vous utisé je ne sais pas ... 

Je vais fermer ce ticket car on a trouvé un contournement pour visionner les replays M6.

Merci,
Wwark.
