### ISSUE TITLE
Kodi très lent à se fermer après utilisation du plugin

### ISSUE THREAD

**Issue by jeff2900** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#78]
Bonjour,

Avant tout je vous remercie pour votre travail. J'utilise votre addon pour regarder les émissions de la TV française en décalées. Maintenant que l'addon FReplay n'est plus mis à jour.

Voici pourquoi je remonte un incident.
Machine: Nvidia Shield TV
OS: Android 8.0
Kodi: 17.6
Addon: plugin.video.catchuptvandmore version 0.1.14-bate011

Avec le version 0.1.14-beta011 j'ai remarqué que la fermeture de Kodi est très longue:

- 	Sur Nvidia Shiel TV elle dure près de 2 minutes

- 	Sur PC portable sous Windows 10 elle dure près de 15 secondes
	
Alors que si je ne lance pas l'addon la fermeture de Kodi est instantanée.
Le simple fait de lancer l’addon suffit à provoquer le blocage sans même aller dans les sous-menus pour lancer une vidéo.

Dans le fichier kodo.log j'ai le message suivant:
```
10:35:29.334 T:1928   ERROR: CPythonInvoker(4, C:\Users\nicolas\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\addon.py): script didn't stop in 5 seconds - let's kill it
10:35:40.085 T:4996    INFO: Python script interrupted by user
```

En faisant un retour-arrière je suis remonté jusqu'à la version 0.1.10-beta13 pour me plus avoir ce time-out si important avant la fermeture de Kodi. 

La durée de fermeture de Kodi semble s'allonger version après version.

Avez-vous constater le même phénomène ?

Je vous remercie encore une fois pour votre addon et les améliorations de vous y apporter jour à près jour.

**Comment by wwark** [comment]
Bonjour @jeff2900,

Merci pour la remontée de ce cas qui sera suivi par ce ticket.

Wwark

**Comment by SylvainCecchetto** [comment]
Bonjour à vous deux,

Pas encore testé sous Windows mais par contre je n'arrive pas à reproduire le problème sous Mac OS.

**Comment by SylvainCecchetto** [comment]
Bonsoir @jeff2900 ,

Apparement c'est notre fonction qui permet de télécharger le programme TV en arrière plan qui engendre ce probleme (On lance un Thread que Windows n'aime pas trop apparemment).

Nous sommes actuellement en train de faire migrer le plugin vers un nouveau Framework et on en profite pour faire un peu le ménage. Entre autre nous avons supprimé ce Thread au profit d'une option dans les réglages du plugin laissant le choix à l'utilisateur de télécharger ou non le programme TV pour le Live TV France.

Si vous le pouvez nous vous proposons de tester cette version du plugin sous Kodi Leia : https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmoretestdrmkodi18

Il n'y a que les chaines DRM pour le moment mais c'est simplement pour tester si le problème de fermeture de Kodi est toujours présent.

Merci !

**Comment by jeff2900** [comment]
Je vous remercie pour votre réponse.

Je viens de finir une série de test de la version catchuptvandmoretestdrmkodi18 pour kodi 18.

Comme je n'utilisai pas kodi 18. J'ai effectué une installation de la dernière version en date.

Windows 10:
> 
	kodi-18.0-Leia_beta3-x64.exe
	
Nvidia shield TV:	
>
 	kodi-18.0-Leia_beta3-arm64-v8a.apk

Amlogic S912:
> 
	kodi-18.0-Leia_beta3-armeabi-v7a.apk

Amlogic S905:

>
 	LibreELEC-S905.arm-9.0-nightly-20181002-8b3e678.img.gz
>
 	LibreELEC-S905.arm-9.0-devel-20181008103608-b0cca57.img.gz
 

Je n'ai pas reproduit le problème de lenteur en sortie de Kodi sur aucun des environnementst.
J'ai donc testé sous Kodi 18 la version 0.1.16-beta04 de l'addon catchuptvandmore et là non plus je n'ai pas constaté le problème.

J'ai donc essayé l'installer l'addon sous kodi 17.6, mais cela ne fonctionne pas.

En conclusion:
II n'y a pas de problème de lenteur en sortie de Kodi sous Kodi 18-beta3.
Comme votre addon me permet de regarder les vidéo sous DRM de TF1 et M6 je n'ai aucune hésitation à remplacer Kodi 17 pour Kodi 18.

Merci pour cette nouvelle version de catchuptvandmore.

Le ticket peut être clos.

**Comment by SylvainCecchetto** [comment]
Merci pour toute cette batterie de tests !!

Parfait alors si le problème a disparu, mais effectivement j'avais lu sur je ne sais plus quel thread d'un forum Kodi que c'était un problème lié au Thread + Windows, donc il y avait de fortes chances qu'on soit dans ce cas là.

Le fait que la version catchuptvandmoretestdrmkodi18 de l'addon ne s'installe pas sur Kodi 17 est normal (dans le fichier addon.xml il est spécifié que la version minimale de Kodi pour l'installation soir Kodi 18).

Cependant nous allons bientôt fusionner nos deux versions de l'addon car la version catchuptvandmoretestdrmkodi18 codée par Wwark n'était là que pour tester la fonctionnalité DRM de Kodi 18 ;-)

Théoriquement la version fusionnée sera installable sur Kodi 17 et 18 (et 16?), cependant les chaines DRM ne fonctionneront que sous Kodi 18 ...
