### ISSUE TITLE
Replay RMC Découverte message erreur , catchup tv a déclenché une erreur innatendue 

### ISSUE THREAD

**Issue by ktm520** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#780]
Bonjour a tous , impossible de regarder le replay RMC découverte , j'ai le message suivant : catchup tv a déclenché une erreur innatendue  , j'utilise KODI version 19.3 , et , la version Catchup TV version 0.2.36+matrix.1 , existe t il une solution , pour résoudre le problème . J'ai un compte RMC BFM PLAY .

 - [x] Android sur Box Tv  Alfawise
 

 - Kodi version:19.3
 - Catch-up TV & More version:0.2.36+matrix.1
 - Installation method:zip

**Comment by Exomatic** [comment]
ces 5 utilisateurs maximum sur rmc bfmplay  peut etre due à ça, va sur le site mon compte reglages Appareils connectés tu veras si ça vient de la. sashant que 1 navigateur = 1 utilisateur pour rmc bfm play (si tu utilse firfox + google chrome sur la meme machine c'est égale a 2 utilisateurs)

**Comment by joaopa00** [comment]
C'est surtout que la version 0.2.36 de matrix ne fonctionne pas avec RMCBFMPLAY. Il faut faire une mise à jour à travers le repo du site de catchuptvandmore et non pas à travers le repo de Kodi. Je ferme. Si le problème persite aorès la mise à jour, n'hésite pas à réouvrir.

**Comment by ktm520** [comment]
Bonjour a tous , je viens vous donner des nouvelles , installation version Catchup TV Béta  via  mise à jour à travers le repo du site de catchuptvandmore , pour  l'instant cela fonctionne , affaire a suivre .
Un grand MERCI , pour votre aide .
C 'est sympa de votre part .

**Comment by joaopa00** [comment]
Super!! Merci pour le retour.
