### ISSUE TITLE
Installation de widevine

### ISSUE THREAD

**Issue by loglyy** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#781]
Bonjour,
Il m'est impossible d'installer widevine que ce soit sur osmc ou libreelec.
L'image de récup de chrome se télécharge, mais l'extraction échoue.
Le message est Echec de lecture : Echec de lecture d'un ou plusieurs fichiers. Consulter de journal pour plus d'informations sur ce message.
Auriez-vous une solution?
Merci pour votre aide.

**Comment by joaopa00** [comment]
Supprime le cache de Kodi, au pire supprime complètement Kod et réinstalle le tout.

En tout cas, ce n'est pas un problème de Catchuptvandmore. Je ferme.
