### ISSUE TITLE
TF1 et DRM

### ISSUE THREAD

**Issue by Nico83500** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#79]
Bonjour,
Certains replays de TF1 ne fonctionnent pas car la vidéo est protégée par DRM. C'est le cas de New York Unité Spéciale par exemple.
Est-ce qu'il est possible de faire quelque chose ou malheureusement les DRM sont obligatoires ?
Merci !

**Comment by wwark** [comment]
Bonjour,
La future version de Kodi 18 pemettra de gérer certains des DRM.
Nous avons des replays et des directs tv qui sont protégés par les DRM (TF1, M6, RTBF, Canal+ ....)

Nous commencerons à travailler sur ce sujet quand la version dernière version RC de Kodi 18 sera disponible.

Merci,
Wwark

**Comment by wwark** [comment]
- [x] Groupe M6
- [ ] Groupe TF1
- [ ] Live TV RMC Découverte
- [ ] Groupe RTL BE
- [ ] Groupe RTBF
- [ ] Groupe France TV

**Comment by wwark** [comment]
Done
