### ISSUE TITLE
Chargement infini ou son sans image pendant quelques secondes puis plus rien

### ISSUE THREAD

**Issue by Yahou68** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#795]
### Describe the bug

Bonjour, 

Sur une Mi Box S, J'ai installé Kodi 19.3 et Catch-up v 0.2.36 le mois dernier, tout fonctionnait presque parfaitement (direct et replay TF1 M6 principalement) à part de temps en temps les erreurs lectures de fichier ou récemment le buffering intempestif sur M6 (direct et replay). Sauf que depuis hier, plus rien ne fonctionne, soit ça charge à l'infini, soit je vois le 100% apparaître ou le logo de chargement qui se fige mais je n'ai que le son et cela dure quelques secondes puis plus rien.

J'ai réinstallé Kodi 19.3 et cette fois-ci avec Catch-up 0.2.37 ou la dernière béta mais le problème est toujours là.

Quelqu'un a t'il le même problème ? 

Les deux erreurs qui reviennent en boucle d'après le log sont: 
ERROR <general>:
CDVDVideoCodecAndroidMediaCodec::GetPicture dequeueInputBuffer failed
CDVDVideoCodecAndroidMediaCodec::GetOutputPicture dequeueOutputBuffer failed

Au départ il y a aussi: 
ERROR <general>: AddOnLog: inpurstreamadaptative/ Key system request: com.widevine.alpha
ERROR <general>: GetDirectory - Error getting /data/user/0/org.xbmc.kodi/cache/apk/assests/addons/inputstream.adaptive/

Auriez-vous une idée pour résoudre mon problème ?

Cordialement.

**Comment by joaopa00** [comment]
Il faudrait au moins tenter de désinstaller et réinstaller inpustream adaptive . Sinon voir [le](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/740)

**Comment by Yahou68** [comment]
Le problème est que dans les paramètres de inputstreamadaptative, l'icône désinstaller est grisée, je ne peux pas désinstaller de cette manière. J'ai essayé de lancer un fichier zip v 19.0.3 (version que  j'ai déjà) mais l'installation échoue. Dans le fil que vous avez mis en lien, en suivant le cheminement, je ne vois pas (re)installer la bibliotheque widevine CDM, je n'ai que install widevine from avec un url. 

J'ai installé depuis un zip: script.module.inputstreamhelper-0.5.8+matrix.1-install_from-101f947.

J'ai aussi copier la version 4.10.2252.5 en la renommant libwidevinecdm.so dans le dossier userdata/cdm et cdm/widevine mais ça ne change rien.

**Comment by joaopa00** [comment]
Le plus simple: tu désinstalles KOdi. Tu n'oubles pas de supprimer le cache s'il existe encore et tu reinstalles le tout.
