### ISSUE TITLE
route missing: resources.lib.main

### ISSUE THREAD

**Issue by eric-blabla** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#798]
Hello, I run kodi 18.9 on a raspberry 3 with   LibreElec 9.2.8. Cath-up-&-more had problems  "route missing" in the previous version 0.2.36. 

So I installed 0.2.37 (stable) via this github repo: same problem. 
I deleted again & installed beta 0.2.38 beta25: same problem.  Reboot = no improvement.

Now I am stuck. Any help PLEASE? Its a permanent struggle with my wife to keep my raspberry/kodi instead  of some payed provider-box, and I really rely on catchup&more for that ...  Thanks you

**Comment by eric-blabla** [comment]
more precisely: 0.2.37 gives the "ascii codec can't encode u\xe9" error. "Share error log fails" as well.  The "route missing is happening in 0.2.36 * 0.2.38 beta25 ...

**Comment by joaopa00** [comment]
You have to insntall the locales package.

**Comment by eric-blabla** [comment]
thank you jaopa00. How would I do that, please? It's a std repo package? From some zip file?  Thanks

**Comment by joaopa00** [comment]
see issue #700 and issue #740

**Comment by eric-blabla** [comment]
Found locale plugin (was indeed missing). Seems to have fixed. I have to check further. If it works I close issue in < 12h. Thank you!

**Comment by joaopa00** [comment]
Assuming fixing. Please, reopen if the bug persists
