### ISSUE TITLE
TVA (Canada)

### ISSUE THREAD

**Issue by Europe57** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#799]
### Describe the bug
A clear and concise description of what the bug is:

### To Reproduce
Steps to reproduce the behaviour:
1. TVA
2. TVA sur demande
3. DOC
4. Saison 1
5. Épisodes
6. Doc - Ép 06. Bol d'air

### Expected behaviour
A clear and concise description of what you expected to happen: 

### Actual behaviour
Tell us what happens instead: Exceeded 30 redirects.

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 19.4
 - Catch-up TV & More version: 0.2.38~beta25
 - Installation method: Reposity

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment]
At least, one needs the URL of the site.

**Comment by Europe57** [comment]
Le nouveau site : https://www.qub.ca/tvaplus

**Comment by joaopa00** [comment]
Should be fixed in git.
