### ISSUE TITLE
RMC BFM Play KO

### ISSUE THREAD

**Issue by alexdaums** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#830]
### Describe the bug
Impossible d'accéder aux replay de RMC et BFM Play.
L'erreur suivante se produit :
`2022-05-08 11:57:27.250 T:1527772032   ERROR: [Catch-up-TV-&-More.support] 'unable to import route module: resources.lib.channels.fr.rmcbfmplay'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 300, in run_callback
                                                route = self.get_route(self.selector)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 250, in get_route
                                                raise RouteMissing("unable to import route module: %s" % module_path)
                                            RouteMissing: 'unable to import route module: resources.lib.channels.fr.rmcbfmplay'`

### To Reproduce
Steps to reproduce the behaviour:
1. Lancer l'extension.
2. Aller dans "Replay TV", puis "France" et "RMC BFM Play.
3. L'erreur apparaît lorsque je clique.

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: LibreElec 9.2.8
 - Kodi version: 18.9
 - Catch-up TV & More version: 0.2.38-beta01
 - Installation method: Dépôts Catch-Up béta

### Debug log
Ci-joint le log complet.
[01_KODI.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/8647227/01_KODI.log)

Cordialement,
Alexandre

**Comment by joaopa00** [comment]
Comme d'habitude sur Rasperri: installer l'addon locale puis voir l'issue #740

**Comment by alexdaums** [comment]
Bonsoir merci de votre aide.
J'ai donc installé l'addon locale depuis les dépôts de LibreElec. C'est la version 9.2.0.102.
Configuré l'extension sur fr_FR en UTF8.
Réinstallé Widevine comme décrit dans le #740 
Mais j'ai toujours l'erreur.

[01_KODI.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/8647440/01_KODI.log)

**Comment by joaopa00** [comment]
Tu as bien renseigné tes identifiants?

**Comment by alexdaums** [comment]
> Tu as bien renseigné tes identifiants?

Oui ils sont bien reseignés.

> Et teste avec la version beta 0.2.38 beta27 Un rapport e bug n'est intéressant que s'il est testé contre la dernière version de développement puisqu'il y a des chances que le bug soit déjà fixe.

Alors je suis tout à fait d'accord avec ceci mais en fait cela fait tellement longtemps que ça marche que mon installation est restée bloquée à la beta01. J'ai donc réinstallé le dépôt et je vois bien une version beta26 hier soir.
Je vais donc tout reprendre ce soir car en installant cette version beta26 par dessus ma beta01 plus rien ne marche j'ai un message similaire à mon erreur BFM play mais dès que je lance l'extension.

Donc auriez vous une procédure de désinstallation propre pour repartir sur une base neuve?
 
> Et attacher une partie d'une log est aussi inutile. Il faut attacher le log complet avec l'option de debug activée.
Où doit on activer l'option débug?

Cordialement,

**Comment by alexdaums** [comment]
Bon j'ai fait une réinstallation neuve de l'extension et de widevine CDM.
Et maintenant j'ai l'erreur systématiquement lors du lancement de l'application.
Voici le fichier de log en mode debug.
[01_KODI.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/8663480/01_KODI.log)

**Comment by darodi** [comment]
On peut voir:

```
File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/addon_utils.py", line 9, in <module>
                                                from enum import Enum
                                            ImportError: No module named enum

```

Installe enum sur python 2.7
`pip install enum34
`

**Comment by alexdaums** [comment]
> On peut voir:
> 
> ```
> File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/addon_utils.py", line 9, in <module>
>                                                 from enum import Enum
>                                             ImportError: No module named enum
> ```
> 
> Installe enum sur python 2.7 `pip install enum34 `

Ok mais je vois pas comment installer ce module sous LibreElec?
Je ne suis pas sûr de pouvoir me connecter en SSH et faire une `pip install`

**Comment by alexdaums** [comment]
> Ah oui... J'oubliais les limitations de librelec. C'est pour ça que j'utilise OSMC 😋
> 
> > The final version of LibreELEC 10.0.2 has been released, bringing Kodi (Matrix) v19.4 to our users.
> 
> Avec la version 3.x de python qui comprend le module enum

Oui mais j'hésite à mettre à jour à cause de ceci :

> RASPBERRY PI 2-3
> As new addition we support RPi2 and RPi3 at LE10. Please keep in mind this is still brand new and not widely tested. Likely bugs are still possible. Overall, the current version is properly useable.
> Note that GPU accelerated H265 decoding is no longer available in LE 10 and future versions. If this is important to you stay at LE 9.2.

**Comment by darodi** [comment]
> Oui mais j'hésite à mettre à jour à cause de ceci :
> 
> > RASPBERRY PI 2-3
> > As new addition we support RPi2 and RPi3 at LE10. Please keep in mind this is still brand new and not widely tested. Likely bugs are still possible. Overall, the current version is properly useable.
> > Note that GPU accelerated H265 decoding is no longer available in LE 10 and future versions. If this is important to you stay at LE 9.2.

Es-tu sous raspberry 4? Je pense que le 3 et plus petits n'ont pas de décodeur hardware pour le h265 de toute façon.

**Comment by alexdaums** [comment]
> je confirme, le hevc/h265 ne fonctionne plus sur rpi 3b+ sous kodi 19.x je me limite au h264

Avec ma version de LE c'est encore fonctionnel !
Et vu la pénurie de RPI 4 je suis pas prêt de pouvoir faire la bascule de mes 2 Kodi.
Donc pour l'instant ... j'aimerais bien éviter de remettre  à jour mes RPI 3b+ car j'ai peur de perdre ma médiathèque malgré la sauvegarde.

**Comment by darodi** [comment]
@alexdaums 

Peux-tu faire un test avec cette version de dev?

https://github.com/darodi/plugin.video.catchuptvandmore/archive/refs/heads/enum_lib.zip

si c'est OK, je créerai la pull request pour l'intégrer à la version beta

**Comment by alexdaums** [comment]
> @alexdaums
> 
> Peux-tu faire un test avec cette version de dev?
> 
> https://github.com/darodi/plugin.video.catchuptvandmore/archive/refs/heads/enum_lib.zip
> 
> si c'est OK, je créerai la pull request pour l'intégrer à la version beta

Super merci mais comment j'installe ceci ?
Car via les extension en ZIP ça ne passe pas.
[01_KODI.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/8666867/01_KODI.log)

**Comment by darodi** [comment]
Pour que ça marche comme extensions zip,
le zip doit être retravaillé pour contenir un répertoire plugin.video.catchuptvandmore comme ceci.

Est-ce qu'avec ce fichier ça s'installe?

[plugin.video.catchuptvandmore.zip](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/8672223/plugin.video.catchuptvandmore.zip)

**Comment by alexdaums** [comment]
> Pour que ça marche comme extension zip, le zip doit être retravaillé pour contenir un répertoire plugin.video.catchuptvandmore comme ceci.
> 
> Est-ce qu'avec ce fichier ça s'installe?
> 
> [plugin.video.catchuptvandmore.zip](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/8672223/plugin.video.catchuptvandmore.zip)

Bon j'avais un problème pour installer et d'après le log c'était un problème sur le fichier addon.xml ligne 174 colonne 30 apparemment c'est le symbole "&" qui gène. J'ai supprimé ce "&" et recréé un .zip et l'installation à fonctionné mais avec une erreur.

Par contre maintenant je peux lancer l'extension et avoir accès à l'arborescence des chaine, des replays ...
Mais de temps en temps j'ai une erreur qui s'affiche en haut mais qui ne plante pas l'extension.
Je te joint le fichier log ... j'espère que tu y trouveras ce qu'il faut.
[01_KODI.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/8672686/01_KODI.log)

**Comment by darodi** [comment]
je ne pense pas que tu as bien installé la version.

Dans ton log, il y a toujours:
```
    from resources.lib.addon_utils import get_item_label, get_item_media_path
  File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/addon_utils.py", line 9, in <module>
    from enum import Enum
ImportError: No module named enum
```

Or, la ligne 9 dans l'ancienne version

https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/a7c02d873bb62dfcd1423e778f54c934a0ad1e0d/resources/lib/addon_utils.py#L9

La ligne 9 dans la version que je t'ai donnée.
https://github.com/darodi/plugin.video.catchuptvandmore/blob/cd4902ee63d5b2b27bbf9cc136a761722bc37942/resources/lib/addon_utils.py#L9-L15

![image](https://user-images.githubusercontent.com/4682830/167944582-fae3019f-56c6-44f1-9f3b-180d8a7abf3b.png)


Quelle est l'erreur obtenue lors de l'installation?

**Comment by darodi** [comment]
[plugin.video.catchuptvandmore.zip](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/8673376/plugin.video.catchuptvandmore.zip)


version avec le addon.xml corrigé

**Comment by alexdaums** [comment]
Bon je pense que le problème venait du ait de ne pas avoir désinstallé avant.
J'ai désinstallé ma version beta26 puis lancé l'installation de ta version et c'est OK pas d'erreur à l'installation.

Ce soir je vais reparamétrer les comptes 6play et bfmplay et je testerais.
Je te ferais un retour dans la foulée.

**Comment by alexdaums** [comment]
Bonsoir,

Alors chose promise chose due.  Voici mon retour sur cette version spéciale.
Comme déjà précisé pas de problème d'installation avec la version du addon.xml corrigé.

Bon nous n'utilisons pas chez nous le live TV,  uniquement les replays avec Catch-Up.
Pour les replay j'ai fais des tests sur les 3 principaux groupes que nous utilisons 95% du temps : MyTF1, 6Play, RMC BFM Play.

1. Pour MyTF1 tout semble fonctionner j'ai lancé plusieurs replays sur plusieurs chaines du groupe.
2. Pour 6play idem j'ai lancé plusieurs replay de plusieurs chaines ... mais j'ai quelques replay M6 qui m'ont carrément crashé le système avec un figeage complet et un reboot. C'est difficile à reproduire donc j'ouvrirai un nouveau bug si ça se reproduit.
3. Pour RMC BFM Play c'est plus compliqué j'ai une erreur de la page d'authentification je suppose. Ci-dessous le fichier .log. J'ai contrôlé mes identifiant sont OK puisque je les utilise sur leur site WEB sur PC.
[01_KODI_erreursfr.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/8681237/01_KODI_erreursfr.log)

**Comment by darodi** [comment]
Merci du retour.
Je vais déjà publier mon correctif pour la compatibilité kodi 18.x

Il reste donc ceci à regarder

```
2022-05-12 18:25:15.522 T:1727779712   ERROR: [Catch-up-TV-&-More.support] 403 Client Error: Forbidden for url: https://sso-client.sfr.fr/cas/services/rest/3.2/createToken.json?duration=86400
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                redirect = parent_ins(route, arg_params, self.callback_params)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 196, in __call__
                                                session_data = self._process_results(results)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 210, in _process_results
                                                listitems = validate_listitems(results)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 39, in validate_listitems
                                                raw_listitems = list(raw_listitems)
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/rmcbfmplay.py", line 89, in rmcbfmplay_root
                                                token = get_token()
                                              File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/rmcbfmplay.py", line 57, in get_token
                                                resp = urlquick.get(url, params=params, headers=headers).json()
                                              File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 493, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 487, in request
                                                return s.request(method=method, url=url, **kwargs)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 442, in request
                                                self._raise_for_status(response, raise_for_status)
                                              File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 415, in _raise_for_status
                                                response.raise_for_status()
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 940, in raise_for_status
                                                raise HTTPError(http_error_msg, response=self)
                                            HTTPError: 403 Client Error: Forbidden for url: https://sso-client.sfr.fr/cas/services/rest/3.2/createToken.json?duration=86400
```

**Comment by alexdaums** [comment]
> Il reste donc ceci à regarder
> 
> ```
> 2022-05-12 18:25:15.522 T:1727779712   ERROR: [Catch-up-TV-&-More.support] 403 Client Error: Forbidden for url: https://sso-client.sfr.fr/cas/services/rest/3.2/createToken.json?duration=86400
>                                             Traceback (most recent call last):
>                                               File "/storage/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
>                                                 redirect = parent_ins(route, arg_params, self.callback_params)
>                                               File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 196, in __call__
>                                                 session_data = self._process_results(results)
>                                               File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 210, in _process_results
>                                                 listitems = validate_listitems(results)
>                                               File "/storage/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 39, in validate_listitems
>                                                 raw_listitems = list(raw_listitems)
>                                               File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/rmcbfmplay.py", line 89, in rmcbfmplay_root
>                                                 token = get_token()
>                                               File "/storage/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/fr/rmcbfmplay.py", line 57, in get_token
>                                                 resp = urlquick.get(url, params=params, headers=headers).json()
>                                               File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 493, in get
>                                                 return request('get', url, params=params, **kwargs)
>                                               File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 487, in request
>                                                 return s.request(method=method, url=url, **kwargs)
>                                               File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 442, in request
>                                                 self._raise_for_status(response, raise_for_status)
>                                               File "/storage/.kodi/addons/script.module.codequick/lib/urlquick.py", line 415, in _raise_for_status
>                                                 response.raise_for_status()
>                                               File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 940, in raise_for_status
>                                                 raise HTTPError(http_error_msg, response=self)
>                                             HTTPError: 403 Client Error: Forbidden for url: https://sso-client.sfr.fr/cas/services/rest/3.2/createToken.json?duration=86400
> ```

Je ne sais pas si c'est rapide pour toi mais est ce que c'est possible de tester ce lien?
[https://sso-client.rmcbfmreplay.com/cas/services/rest/3.3/createToken.json?duration=86400](https://sso-client.rmcbfmreplay.com/cas/services/rest/3.3/createToken.json?duration=86400)

Merci.

**Comment by joaopa00** [comment]
Il faudrait au moins donner le nom de la vidéo qui pose c problème.

**Comment by joaopa00** [comment]
Le log que tu as attaché dans le message 830 est pollué avec des changements de chaines.
Attache un nouveau log en ne manipulant qu'une chaine RMC.

**Comment by alexdaums** [comment]
> Le log que tu as attaché dans le message 830 est pollué avec des changements de chaines. Attache un nouveau log en ne manipulant qu'une chaine RMC.

J'espère que ce fichier ira bien.
Pour rappel l'erreur apparait quand je veux rentrer dans le service pas au moment de choisir une chaine.
Le parcours : 

1. Extension Catch Up = OK
2. Tv de rattrapage = OK
3. France = OK
4. RMC BFM Play = ERREUR

[01_KODI.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/8690069/01_KODI.log)

**Comment by darodi** [comment]
@alexdaums 

`2022-05-13 20:30:29.388 T:1523397504   DEBUG: [urllib3.connectionpool] https://sso-client.sfr.fr:443 "GET /cas/services/rest/3.2/createToken.json?duration=86400 HTTP/1.1" 403 119`

Le HTTP 403 est un code d'état HTTP signifiant que l'accès à la ressource demandée est interdit. 

https://sso-client.rmcbfmreplay.com/cas/services/rest/3.3/createToken.json?duration=86400
est utilisé pour tout pour récupérer un token pour la suite du traitement.

Avant toute chose, peux tu vérifier si ton login/pass est correct?
tu peux voir la valeur dans  
`userdata\addon_data\plugin.video.catchuptvandmore\settings.xml`

```
<setting id="rmcbfmplay.login">blablah</setting>
<setting id="rmcbfmplay.password">truc</setting>
```

**Comment by Arias800** [comment]
> Pour info j'ai bien contrôlé mes identifiants. Et je les utilisent depuis plusieurs mois sur le site web avec mon pc.
Il faut tester via l'application Android pour tester la connexion @alexdaums .
Le système de connexion du site marche différemment sur PC et catchup est basé sur la version Android (pour une raison technique).

**Comment by alexdaums** [comment]
> > Pour info j'ai bien contrôlé mes identifiants. Et je les utilisent depuis plusieurs mois sur le site web avec mon pc.
> 
> Il faut tester via l'application Android pour tester la connexion @alexdaums . Le système de connexion du site marche différemment sur PC et catchup est basé sur la version Android (pour une raison technique).

Oui j'utilise aussi l'application Android et mes identifiants fonctionnement correctement.
Pour tous mes identifiants pro et perso j'utilise Bitwarden pour créer et sauvegarder mes mots de passe donc pas de trou de mémoire.

**Comment by alexdaums** [comment]
> catchuptvandmore

Bon ben c'était bien un problème de mot de passe.
Pour taper les mots de passe j'utilise une télécommande avec un clavier et la lettre V est presque morte.
Il manquait donc un V dans mon mot de passe.

Encore merci pour toute votre aide  apporter je peux clore le sujet!

**Comment by xXMiryokuXx** [comment]
Bonjour j'ai le même souci sauf que mois j'ai vérifier plusieurs fois le mdp et c'est pas ça. Ps je suis sur Android. Help plz :)

**Comment by xXMiryokuXx** [comment]
https://sso-client.sfr.fr:443 "GET /cas/services/rest/3.2/createToken.json?duration=86400 HTTP/1.1" 403 119`


Bonjour j'ai le même souci sauf que mois j'ai vérifier plusieurs fois le mdp et c'est pas ça. Ps je suis sur Android. Help plz :)
