### ISSUE TITLE
RTBF Auvio - lecture s'arrête pour charger le cache

### ISSUE THREAD

**Issue by dmu7004** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#837]
Bonsoir,

Lors de la lecture du contenu "série corner" de la chaîne RTBF Auvio, la lecture s'arrête +- toutes les 2min pour recharger le cache.
Le même phénomène arrive parfois lors de la lecture de "La Une" en direct. Mais plus rarement, le fait de faire STOP puis PLAY le problème disparaît.

Avec les replay de TMC je n'ai pas ce soucis.

-  Raspberry-Pi 4  8Go
 - Kodi version: Librelec 10.0.2- kodi 19.4 Matrix
 - Catch-up TV & More version: 0.2.36+matrix1
 
J'ai tenté de trouver une solution dans les différents forum mais je ne trouve rien de concluant.

J'ai mis dans le fichier advancedsettings.xml : 

```
<advancedsettings>
	<cache>
		<buffermode>1</buffermode>
		<memorysize>2389904190</memorysize>
		<readfactor>20</readfactor>
	</cache>
</advancedsettings>
```

Mais rien y fait, la lecture s'arrête pour recharger le cache.

Je ne rencontre ce soucis qu'avec la RTBF, le regarde NETFLIX via ce KODI et je n'ai pas de problème de cache.

Est-ce que vous auriez une idée d'où provient le problème ? (KODI , le plugin RTBF, etc...)

Merci d'avance

Dany

**Comment by dmu7004** [comment]
Bonjour Darodi,

Après avoir installer le canal beta,  lorsque que je veux y entrer j'ai le message suivant  : "Impossible de se connecter au dépôt".

:(

**Comment by dmu7004** [comment]
Désolé, j'avais pas redémarrer le Rpi :)

J'ai testé avec les options, toujours le même soucis de cache et en plus avec cette version beta je ne retrouve pas dans le dossier "série corner" la même liste de série, elle est tronquée etje ne vois plus la série que je regardais avec le problème de cache

**Comment by joaopa00** [comment]
La béta a été libérée...

**Comment by darodi** [comment]
les api sont appelées avec un paramètre `limit=100`... c'est un peu trop restrictif de se limiter à 100 résultats.
il faudrait ajouter une pagination.

**Comment by darodi** [comment]
@dmu7004 

- le fix #838 
  est disponible dans la dernière version beta si tu fais une mise à jour.

Peux tu refaire un test avec cette version et le bitrate moins élevé?



> La série c'est "Il Cacciatore - The hunter S03"

Je vais rajouter une pagination.
En attendant, tu peux utiliser 
le menu "search programs", en indiquant cherchant "Cacciatore"
ou le menu "all programs"

**Comment by dmu7004** [comment]
Bonjour Darodi,


Merci pour le tuyau "Rechercher" je n'y avais pas pensé :)


Voilà j'ai testé avec un bitrate plus bas (1000 & 1500), cela fonctionne en résolution "DEFAUT". La video est juste légèrement moins fluide, lors des scènes d'actions je vois un très léger freeze dans la fluidité. 

J'ai une question :) : est-ce le flux envoyé par la RTBF qui pose problème et qui demande à diminuer la résolution à 480p ? Car je regarde Netflix ou d'autres chaînes en HD ou FULL HD sans prob.

Merci pour l'aide.

Dany

**Comment by darodi** [comment]
> 
> Merci pour le tuyau "Rechercher" je n'y avais pas pensé :)
> 

J'ai ajouté de la pagination sur rtbf auvio.
Elle sera disponible sur le canal beta lorsque tu verras le prochain `"addon.xml: Update"` ici:
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/commits/dev

> Voilà j'ai testé avec un bitrate plus bas (1000 & 1500), cela fonctionne en résolution "DEFAUT". La video est juste légèrement moins fluide, lors des scènes d'actions je vois un très léger freeze dans la fluidité.
> 
> J'ai une question :) : est-ce le flux envoyé par la RTBF qui pose problème et qui demande à diminuer la résolution à 480p ? Car je regarde Netflix ou d'autres chaînes en HD ou FULL HD sans prob.

Il doit y avoir un problème de cache, parfois le stream rbtf est plus lent. Ca devrait se corriger avec Kodi 20 qui introduira un meilleur système de cache sur les flux.
Une autre solution, si tu veux regarder en plus haute qualité et de manière plus fluide serait peut être de télécharger le contenu que tu veux voir et le regarder en local dans ton réseau/sur ta machine.

https://github.com/yt-dlp/yt-dlp

`yt-dlp.exe -F https://www.rtbf.be/auvio/detail_il-cacciatore-the-hunter-s03?id=2872429`
pour voir les résolutions disponibles
`yt-dlp.exe -f hls-2342 https://www.rtbf.be/auvio/detail_il-cacciatore-the-hunter-s03?id=2872429`
pour choisir une résolution

> 
> Merci pour l'aide.
> 
> Dany

Il n'y a pas de quoi.
Bon amusement.

**Comment by joaopa00** [comment]
Le problème étant circonscrit à un problème ne dépendant pas de Catchuptvandmore, je ferme l'issue. Si il est encore là avec la version Nexus, n'hésite pas à réouvrir.
