### ISSUE TITLE
New York Times Website fails to open, with error: KeyError 'data'

### ISSUE THREAD

**Issue by kevwag** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#844]
### Describe the bug
Trying to open "New York Times" from the websites menu fails, producing a KeyError 'data' notification.

### To Reproduce
Steps to reproduce the behaviour:
1. Launch the addon
2. Select "New York Times

### Expected behaviour
List of videos or categories from the New York Times website should appear.

### Actual behaviour
List does not open and a KeyError 'data' notification shows at the top of the screen.

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [x] Linux
 - [x] Windows

 - Operating system version/name: Windows 10 & CoreELEC 20
 - Kodi version: 20 Nexus Nightly Build
 - Catch-up TV & More version: 0.2.38-beta28
 - Installation method: Zip file

### Debug log
    ERROR <general>: CImageLoader::DoWork - Direct texture file loading failed for resource://resource.images.catchuptvandmore/websites/30millionsdamis_fanart.jpg
    ERROR <general>: CImageLoader::DoWork - Direct texture file loading failed for resource://resource.images.catchuptvandmore/websites/nytimes_fanart.jpg
    ERROR <general>: [Catch-up-TV-&-More.support] 'data'
           Traceback (most recent call last):
             File "C:\Users\Kevin\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\support.py", line 306, in run_callback
               redirect = parent_ins(route, arg_params, self.callback_params)
             File "C:\Users\Kevin\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\route.py", line 196, in __call__
               session_data = self._process_results(results)
             File "C:\Users\Kevin\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\route.py", line 210, in _process_results
               listitems = validate_listitems(results)
             File "C:\Users\Kevin\AppData\Roaming\Kodi\addons\script.module.codequick\lib\codequick\route.py", line 39, in validate_listitems
               raw_listitems = list(raw_listitems)
             File "C:\Users\Kevin\AppData\Roaming\Kodi\addons\plugin.video.catchuptvandmore\resources\lib\websites\nytimes.py", line 88, in website_root
               for anywork in json_parser2['data']['anyWorks']:
               KeyError: 'data'
    ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.catchuptvandmore/resources/lib/websites/nytimes/website_root/?_pickle_=80049540000000000000007d94288c075f7469746c655f948c0e4e657720596f726b2054696d6573948c08786d6c74765f6964944e8c076974656d5f6964948c076e7974696d657394752e
    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.catchuptvandmore/resources/lib/websites/nytimes/website_root/?_pickle_=80049540000000000000007d94288c075f7469746c655f948c0e4e657720596f726b2054696d6573948c08786d6c74765f6964944e8c076974656d5f6964948c076e7974696d657394752e) failed
    WARNING <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
    ERROR <general>: Skipped 12 duplicate messages..
    ERROR <general>: CImageLoader::DoWork - Direct texture file loading failed for resource://resource.images.catchuptvandmore/websites/nfb_fanart.jpg
    ERROR <general>: CImageLoader::DoWork - Direct texture file loading failed for resource://resource.images.catchuptvandmore/websites/marmiton_fanart.jpg
    ERROR <general>: CImageLoader::DoWork - Direct texture file loading failed for resource://resource.images.catchuptvandmore/websites/nationalfff_fanart.jpg

**Comment by darodi** [comment]
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/blob/682c15ab07ca9167cca30748b4114f88da0b8f98/resources/lib/websites/nytimes.py#L80

gives 

`{'errors': [{'message': 'PersistedQueryNotFound'}]}`

They changed their web site API.
Some reverse engineering will be needed to get the new sha256Hashes values  :detective: :sweat_smile:
I'll have a look.
