### ISSUE TITLE
Please add functionality for Veely

### ISSUE THREAD

**Issue by kevwag** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#850]
### Content description
[Veely](https://veely.tv) is the online platform of Little Dot Studios Ltd
It includes 6 Live [IPTV channels](https://veely.tv/live/) with [EPG guide](https://veely.tv/tvguide):

- [Real Stories](https://veely.tv/live/realstories)
- [Timeline](https://veely.tv/live/timeline)
- [Wonder](https://veely.tv/live/wonder)
- [Real Crime](https://veely.tv/live/realcrime)
- [Real Wild](https://veely.tv/live/realwild)
- [Real Life](https://veely.tv/live/reallife)

It also has [On-Demand](https://veely.tv/explore/6165) content from 10 of their channel brands:

- [Real Stories](https://veely.tv/explore/6912)
- [Timeline](https://veely.tv/explore/6913)
- [Wonder](https://veely.tv/explore/6914)
- [Real Crime](https://veely.tv/explore/9600)
- [Real Wild](https://veely.tv/explore/9601)
- [Real Life](https://veely.tv/explore/7316)
- [Real Drama](https://veely.tv/explore/11547)
- [Real Royalty](https://veely.tv/explore/14102)
- [Spark](https://veely.tv/explore/11692)
- [Don't Tell The Bride](https://veely.tv/explore/9455)

* Name: Veely
* Type [e.g. TV channel, Catch-up TV, Website, Radio]: 6x TV Channels and 10 On-Demand services
* Website URL: [https://veely.tv](https://veely.tv)
* Content language/country: English / Multiple cCountries

### Content access

- [x] All Veely content is free and does not require an account.

### More information

Veely is available on the [Veely website](https://veely.tv) and on the Veely apps for Android and IOS.

**Comment by kevwag** [comment]
That's really cool guys, thank you!
Just a couple of small observations:
The live tv section does not show the channel names, just the name of the show that's currently playing. Could you add the channel names?

On-demand content has no metadata (show descriptions etc). Also, if you browse to On-demand>>Timeline>>Programmes, there's a show that's just called "Episode 1 S1EP1" with no indication what show it belongs to.

Finally, if the tv guide ever gets fixed, could these channels be added to it please?

**Comment by darodi** [comment]
> ...  Also, when watching a series, inside the season folders, the episode titles are shown but not the episode numbers. Could the episode number be added as a prefix to the title?

Do you have an example for this?
Here I get the following:

![image](https://user-images.githubusercontent.com/4682830/169113217-a9587564-4966-45d6-ae21-9b1b25def118.png)

**Comment by kevwag** [comment]
Thumbnails and metadata working great now - thank you :)

**Comment by kevwag** [comment]
> Do you have an example for this?
> Here I get the following:

If you browse to:
On-Demand>>Real Drama>>Series>>Underbelly>>Season 1
The episodes have no episode numbers:

<img width="951" alt="Veely Episodes Within Season" src="https://user-images.githubusercontent.com/16394531/169689374-f5b3ab80-1e1c-4036-8cda-3ec05a39f426.png">

I think this is also preventing the external Trakt addon from identifying the episodes and marking them as watched on my Trakt account. 
Episodes I watch elsewhere in the addon (UKTV Play on-demand content, for example) DO sync properly with Trakt and I think Trakt relies in part, on the season and episode number being the first part of the title it reads.

**Comment by darodi** [comment]
@kevwag 

see
- #857 
- #862
