### ISSUE TITLE
unable to import route module: resources.lib.channels.fr.cnews

### ISSUE THREAD

**Issue by Golemizator** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#856]
### Describe the bug
Bonjour, j'ai une erreur lorsque j'essaie d'accéder aux replays de CNews.

### To Reproduce
1. Télévision de rattrapage
2. France
3. CNews

### Expected behaviour
Accès aux replays de CNews

### Actual behaviour
'unable to import route module: resources.lib.channels.fr.cnews'

### Your environment
 - [X] Raspberry-Pi

 - Operating system version/name: LibreElec
 - Kodi version: 18.9
 - Catch-up TV & More version: 0.2.38-beta29

Le replay de CNews ne fonctionne pas non plus en version 0.2.36, ni en 0.2.37.

Je vous remercie pour votre aide.

**Comment by joaopa00** [comment]
As-tu installé l'addon locales?

**Comment by darodi** [comment]
Peux-tu envoyer les logs?

**Comment by Golemizator** [comment]
Oui j'ai bien l'addon locale d'installé, en dernière version.

Voici le log : https://paste.kodi.tv/eduhoxohab?fbclid=IwAR2BeszAYg7HRU9TeKWugj3Q05YRNMkGWc_UHdPf8RfIKl6m-5pZpErhbrY

**Comment by Golemizator** [comment]
Super merci beaucoup, savez-vous à peu près quand la prochaine beta sort pour que je puisse tester ?

**Comment by joaopa00** [comment]
Dans le courant de la semaine prochaine certainement

**Comment by Golemizator** [comment]
J'ai pu tester sur la beta 30, malheureusement le souci est toujours là :(
Exactement le même log

**Comment by joaopa00** [comment]
Ton système est joliment cassé. 
>LoadJpeg: unable to load resource://resource.images.catchuptvandmore/channels/fr/cnews_fanart.jpg
ne devrait pas apparaître si Catchuptvandmore a été installé convenablement.
Les méthodes officielles pour installer Kodi sont là:
https://catch-up-tv-and-more.github.io/fr/installation/

Répare ton système pour commencer. Si le bug persiste, envoie un nouveau log.
