### ISSUE TITLE
Add "Euronews Romania"

### ISSUE THREAD

**Issue by RONTVHD** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#868]
### Content description

* Name: Euronews (RO)
* Type [e.g. TV channel, Catch-up TV, Website, Radio]: TV channel
* Website URL: https://www.youtube.com/watch?v=tdwXKd9Gqb8
* Content language/country: RO

### Content access

- [ ] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [ ] This content is geographically restricted

### More information

If you want to add more information, put it here:

**Comment by darodi** [comment]
![image](https://user-images.githubusercontent.com/4682830/170242524-dae9225d-0ca8-4b49-867f-56f40dc21702.png)

**Comment by darodi** [comment]
live here
https://www.youtube.com/watch?v=tdwXKd9Gqb8
