### ISSUE TITLE
All France 3 Régions and RMC Découverte HS

### ISSUE THREAD

**Issue by FouineInfo** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#873]
### Describe the bug
All France 3 Regions are : HTTP Error, 403 Client Error: Forbidden for url: https://live-regions.p.ftven.fr/hls/live/2037536/F3_Alpes/index.m3u8
RMC Découverte have a nice black screen : no sound, no picture.

All other channels are working

### To Reproduce
Steps to reproduce the behaviour:
1. Launch France 3 region (regardless of the region) -> HTTP Error, 403 Client Error: Forbidden for url: https://live-regions.p.ftven.fr/hls/live/2037536/F3_Alpes/index.m3u8
2. Lauch RMC Découverte -> Black screen, no sound, no picture.

### Your environment

 - Operating system version/name: Xiaomi Mi Box S Android TV 9.0
 - Kodi version: 19.4
 - Catch-up TV & More version: 0.2.38 -beta29

**Comment by nmaster2042** [comment]
I confirm for France 3 any region.

RMC Decouverte live is OK for me.

Your environment

    Operating system version/name: Kubuntu 21.10
    Kodi version: 19.4
    Catch-up TV & More version: 0.2.38 -beta29

**Comment by joaopa00** [comment]
Le problème de France 3 Régions devrait ête fixé dans la dernière béta.
Le problème pour RMC n'a lieu que chez toi.
En outre, une bonne pratique de report de bug est: un problème par report.
Cette issue ne sera plus dédiée que pour FranceTV Régions. Si tu veux que l"on regarde ton problème pour RMC, ouvre une autre issue. Merci d'avance.

**Comment by FouineInfo** [comment]
Cool, merci pour le retour de France 3 Régions.
Depuis hier soir RMC Découverte à de nouveau du son et de l'image, sur tous les support : Tablette, PC, Android, Mac et Android TV
Merci ;-)
