### ISSUE TITLE
Rechargement des pages

### ISSUE THREAD

**Issue by mmtest1** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#88]
Bonjour,
je vous remercie pour votre excellente extension
J'utilise votre extension sous kodi 17.6 sous osmc et rpi b+ et je rencontre un problème lors de la navigation dans les menus : lors d'un retour au menu précédent la page doit être rechargée et cela prend un certain temps rendant la navigation dans l'extension relativement lente et laborieuse, serait-il possible que les menu soit conservés dans le cache et éviter le rechargement car avec un matériel plutôt limité (rpi b+) cela est très contraignant.
merci

**Comment by mmtest1** [comment]
bonsoir,
lors de la navigation dans les menus replay il faut plus d'une minute pour le retour sur chaque page précédente, je sais que le rpi b+ n'est pas un foudre de guerre mais c'est plutôt laborieux, sur d'autres extensions que j'utilise il y a une latence de chargement sur une navigation "en avant" mais pas sur précédent

**Comment by wwark** [comment]
Bonjour mmtest1,

Est-ce qu'il serait possible de tester la nouvelle branche codequick (nouveau framework) en cours de migration https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/tree/codequick pour voir si le problème est toujours présent ?

Merci,
Wwark

**Comment by mmtest1** [comment]
Bonjour wwark,

je viens de faire un essaie avec la version codequick et le problème est toujours présent, il faut toujours recharger la page précedente,
je vous remercie pour le suivi et suis disponible pour d'autres essais si nécessaire

Voici un extrait du fichier log si cela peut aider : 

`14:46:01.429 T:2759287552 WARNING: CPythonInvoker(7, /home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py): the python script "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui8ListItemE
14:46:40.881 T:2759287552 WARNING: CPythonInvoker(8, /home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py): the python script "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui8ListItemE
14:46:41.830 T:2575467264 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
14:46:41.832 T:2575467264 WARNING: Previous line repeats 1 times.
14:46:41.832 T:2575467264  NOTICE: LoadJpeg: unable to load /home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/media/channels/fr/tf1_fanart.jpg
14:46:42.973 T:2742510336 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
14:46:42.976 T:2742510336 WARNING: Previous line repeats 1 times.
14:46:42.976 T:2742510336  NOTICE: LoadJpeg: unable to load /home/osmc/.kodi/addons/plugin.video.catchuptvandmore/resources/media/channels/fr/france-2_fanart.jpg
14:47:02.143 T:2525135616 WARNING: CPythonInvoker(9, /home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py): the python script "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui8ListItemE
`

merci,
mmtest1

**Comment by SylvainCecchetto** [comment]
Bonjour mmtest1,

Ce comportement de "Recharger la page précédente" lors d'un retour en arrière me semble étonnant. Je n'ai pas du tout ce comportement de mon coté.

En regardant le log, je n'ai pas l'impression d'avoir cette ligne dans mes logs à moi :

```
14:46:40.881 T:2759287552 WARNING: CPythonInvoker(8, /home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py): the python script "/home/osmc/.kodi/addons/plugin.video.catchuptvandmore/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui8ListItemE 
```

Est-ce que tu aurais la possibilité de tester de nouveau sur une nouvelle instance d'OSMC ou LibreELEC si tu as une autre carte SD pour ton RB2 ? Ceci afin d'être certain que ce ne soit pas ton instance d'OSMC qui pose problème ?

J'ai un vieux RB2 qui traine chez moi, si j'ai le temps j'essaierai de faire le test de mon coté aussi pour comparer. Perso j'utilise LibreELEC mais il ne doit pas y avoir trop de différences.

Merci à toi en tout cas pour les test !

**Comment by SylvainCecchetto** [comment]
Je viens de faire le test sur mon vieux RB (en fait c'est un RB1 Model B donc vraiment pas puissant).

Et c'est vrai que le chargement est long pour aller au niveau +1 (bon ça ne m'étonne pas sur mon RB), mais par contre je remarque aussi un chargement pour le passage au niveau -1. Ce qui effectivement ne ce produit pas sur l'addon YouTube par exemple.

Et effectivement, je pense que ce chargement pour aller au niveau -1 est présent lui aussi sur mon Mac mais comme il est bien plus puissant que le RB je ne le vois pas.

Je vais essayer de cerner le problème sur le RB pour voir s'il s'agit d'un problème de Codequick ou non ;-)

**Comment by SylvainCecchetto** [comment]
Hey!

Bon c'était bien un paramètre du coté du framework CodeQuick. Le dev de Codequick a fait la modification mais celle-ci ne sera disponible sur les dépôts de Kodi que dans un petit moment :-/

En attendant j'ai ajouté dans Catch-Up TV & More quelques lignes pour au moins supprimer le délai dans les premiers menus (jusqu'à la liste des chaines).

Pour résoudre le problème sur tous les menus tu peux, soit attendre la mise à jour de Codequick, soit installer la dernière version à la main depuis le branch dev du dépôt : https://github.com/willforde/script.module.codequick/tree/dev

En attendant, merci d'avoir soulevé ce problème !

Je laisse l'issue ouvert tant que Willforde n'a pas poussé la mise à jour chez Kodi.

**Comment by mmtest1** [comment]
Bonjour et merci pour le suivi,
Il est vrai que mon rpi b+ commence a se faire vieux et n'est pas bien rapide.... mais cela permet au moins de relever des "bugs" qui permettra d'accélérer l'extension sur des systèmes ou cela n'était pas visible
Je vais essayer la mise à jour de codequick et je vous ferais un retour si cela ne marche pas
Merci

**Comment by SylvainCecchetto** [comment]
Je ferme cette issue pour inactivité.
Re-ouvrir si nécessaire ;-)
