### ISSUE TITLE
Please add posibility to use zattoo.com, wilmaa.com or teleboy.ch with Replay TV

### ISSUE THREAD

**Issue by Mannshoch** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#89]
I'm looking for a TV Provider with Replay TV. My choose for a provider depends on the support for Replay TV in KODI.

**Comment by wwark** [comment]
Hi,
Regarding your request, we will add just tattoo.com because others are just HUB for IPTV and we add directly the website of the channel. In this HUB of IPTV which channels do you want to add?

- [ ] Tattoo.com (add website)

Thanks,
Wwark

**Comment by Mannshoch** [comment]
Sorry i wrote the website wrong. It's Zattoo.com.

What do you mean with a hub for IPTV? 

My goal is to get a premium service (I'm looking for the 7-days-Replay TV)  from one of these three Website. But I wish to use it with KODI. But this three Website only deliver their own app for Apple, Android or their webplayer.

**Comment by wwark** [comment]
No problem :)

Sorry I mean this plugin connect to each website of all channels (MyTF1, RTBF, ...) we proposed, 
These websites are different and we don't think to add them on this plugin. 
I search and found Kodi have already a plugin for Zattoo and for Teleboy.

**Comment by wwark** [comment]
I close this issue.
Thanks,
Wwark.
