### ISSUE TITLE
Impossible de regarder les vidéos TF1

### ISSUE THREAD

**Issue by Nessa42** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#890]
### Describe the bug
Bonjour ,

Je ne peux plus regarder les vidéos de TF1.

### To Reproduce
Steps to reproduce the behaviour:
1.
2.
3.
4.

### Expected behaviour
A clear and concise description of what you expected to happen:

### Actual behaviour
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Other

 - Operating system version/name: windows 10
 - Kodi version: matrix
 - Catch-up TV & More version: beta
 - Installation method: repository

### Additional context
Add any other context about the problem here:

### Debug log
 
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/8847541/kodi.log)
):

**Comment by darodi** [comment]
>  Error Type: <class 'PermissionError'>
>                                                    Error Contents: [WinError 32] Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus: 'C:\\Users\\Nessa\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\script.module.inputstreamhelper\\temp\\4.10.2449.0-win-x64.zip'
>                                             

> 
> 2022-06-06 20:59:52.882 T:11564   ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting C:\Program Files\Kodi\addons\inputstream.adaptive\
> 2022-06-06 20:59:53.006 T:11564    INFO <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file. #Periods: 1, #Streams in first period: 4, Type: VOD, Download speed: 0.0000 Bytes/s
> 2022-06-06 20:59:53.009 T:11564   ERROR <general>: AddOnLog: inputstream.adaptive: Unable to load widevine shared library (C:\Users\Nessa\AppData\Roaming\Kodi\cdm\widevinecdm.dll)
> 2022-06-06 20:59:53.009 T:11564   ERROR <general>: AddOnLog: inputstream.adaptive: OpenDRMSystem failed


C'est un problème d'installation sur ton pc, pas un problème de CUTVM.

reboot ton pc pour éviter que 2 processus utilisent inputstream helper en même temps et puis réinstalle 
inputstream helper, inputstream adaptive et widevine

voir.
- https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/740

**Comment by joaopa00** [comment]
Pas de nouvelles du reporter. On part du principe que le problème est résolu. Si cela n'est pas le cas, n'hésite pas à réouvrir.
