### ISSUE TITLE
echec de lecture  journal fichiers

### ISSUE THREAD

**Issue by jordanpires449** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#892]
### Content description

* Name:
* Type [e.g. TV channel, Catch-up TV, Website, Radio]:
* Website URL:
* Content language/country:

### Content access

- [ ] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [ ] This content is geographically restricted

### More information

If you want to add more information, put it here:

**Comment by jordanpires449** [comment]
422

**Comment by darodi** [comment]
@jordanpires449 

Sans descriptif de ton problème, on ne peut pas deviner

**Comment by joaopa00** [comment]
Avec un tel rapport de bug, rien ne peut être fait.
Si le reporter a l'intention d'apporter les précisions demandées, qu'il n'hésite pas à réouvrir le fil.
