### ISSUE TITLE
Bug lancement chaine Francaise

### ISSUE THREAD

**Issue by ssAxl** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#893]
### Describe the bug
A clear and concise description of what the bug is:
Lorsque je choisi le pays (France en l'occurence), j'obtiens le message suivant:
"UnicodeEncodeError
'ascii' codec can't encode character u'\xe9' in postition 5: ordinal not in range (128)"

 - Operating system version/name: Librelec 9.2.6 (Rpi 3b)
 - Kodi version: 18.9
 - Catch-up TV & More version: 2.3.7

### Additional context
Add any other context about the problem here:
Cela fait suite à la mise à jour vers 2.3.7. Pas de problème avant.
J'ai cherché sur le net les bug "unicode encore error" mais je n'ai rien trouver qui m'aide.
Lors de la selection d'autre pays, cela fonctionne.

J'en profite au passage pour vous remercier pour ce plugin! Un must have!

Cordialement

ssAxl

**Comment by joaopa00** [comment]
As-tu installé l'extension locale?

**Comment by ssAxl** [comment]
Ola!

YEEES trop fort! J'avais zapé l'extension "service locale".
Merci pour votre rapidité de réponse et merci à l'équipe pour CatchUp !

ssAxl
