### ISSUE TITLE
information

### ISSUE THREAD

**Issue by jordanpires449** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#894]
### Content description

* Name:
* Type [e.g. TV channel, Catch-up TV, Website, Radio]:
* Website URL:
* Content language/country:

### Content access

- [x] This content or some part of this content require a free account
- [x] This content or some part of this content require a paid account
- [x] This content is geographically restricted

### More information

If you want to add more information, put it here:

**Comment by darodi** [comment]
@jordanpires449 

2e ticket sans descriptif... Que veux-tu qu'on fasse de ça à part le fermer?

@joaopa00 

Peux tu fermer ? Merci

**Comment by joaopa00** [comment]
@darodi.
Pas de problème. Ca ne mérite pas mieux.
