### ISSUE TITLE
Arte

### ISSUE THREAD

**Issue by jordanpires449** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#897]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jordanpires449** [comment]
Arte fr belgque Catch up tv More

**Comment by darodi** [comment]
@joaopa00 


- 3e ticket sans descriptif https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/895
- 4e ticket sans descriptif https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/896
- 5e ticket sans descriptif https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/897

Là ça devient du spam... On ne bloquerait pas [jordanpires449](https://github.com/jordanpires449) ?

**Comment by joaopa00** [comment]
Merci pour le conseil. C'est fait (enfin, je pense...)
