### ISSUE TITLE
All Chinese CCTV Channels Not Working

### ISSUE THREAD

**Issue by Madkat2** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#900]
### To Reproduce
Steps to reproduce the behaviour:
1.Open any CCTV Channel
2.Error Message
3.JSON Decoder Error
4.Error Log Upload Fail

### Expected behaviour
I thought the channels would work

### Actual behaviour
Channels do not work

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: Matrix
 - Catch-up TV & More version: 0.2.37
 - Installation method: Kodi repo

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by Madkat2** [comment]
No I'm not, sorry I didn't realise they were geoblocked

**Comment by joaopa00** [comment]
I close this ticket then. There is no bug in Catchuptvandmore.

**Comment by Madkat2** [comment]
Ok, thanks for the help

**Comment by joaopa00** [comment]
I reopen then.
Can you give the link of the appli?

**Comment by Madkat2** [comment]
I was able to watch all the channels live at:
https://tv.cctv.com/live/cctv1/m/index.shtml?spm=C28340.PkyZU989m3Vf.EJSxeEkPNal5.2

The streaming app is at this link:
https://app.cctv.com/special/download/ysyy/index.html

Thanks for the reply!

**Comment by Madkat2** [comment]
The channels are all working for me, I'm in the UK?

**Comment by joaopa00** [comment]
What is the link for the android app?

**Comment by Madkat2** [comment]
This page, just hit download:
https://app.cctv.com/special/download/ysyy/index.html

**Comment by joaopa00** [comment]
Should be fixed in the next beta thanks to Darodi.

**Comment by Madkat2** [comment]
That's great, thanks a million again

**Comment by joaopa00** [comment]
This thread is older than the other. But the other has more technical infos. I close this one.
