### ISSUE TITLE
Bug BFMTV

### ISSUE THREAD

**Issue by ssAxl** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#901]
### Describe the bug
A clear and concise description of what the bug is:
Lorsque je lance bfmtv, j'obtiens le message suivant:
"unable to import route module: ressources.lib.channeles.fr.rmcbfmplay"

### To Reproduce
Steps to reproduce the behaviour:
1. Lancer la chaine BFMTV

### Expected behaviour
A clear and concise description of what you expected to happen:

### Actual behaviour
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: Librelec 9.2.6 (Rpi 3b)
 - Kodi version: 18.9
 - Catch-up TV & More version: 2.3.7

### Additional context
Add any other context about the problem here:
Cela ne fonctionne plus depuis la mise à jour 2.3.7
Les autres chaines fonctionnent.

Merci !
ssAxl

**Comment by joaopa00** [comment]
La version stable ne permet pas de regarder les chaines de RMC (BFM en particulier). Il faut utiliser la version beta.
