### ISSUE TITLE
Arte Replay (again and again)

### ISSUE THREAD

**Issue by eric-blabla** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#904]
### Describe the bug
A clear and concise description of what the bug is:

404 error while Arte Replay.

### To Reproduce
Steps to reproduce the behaviour:
1. Install fresh LibreElec (Kodi 19.4) on SDcard
2. Insert in Raspberry 3
3. Install CUTV (0.2.37+ matrix.1) and its dependecies  
4.Install locale plugin to Kodi (to avoid previous error source for arte.tv problems)

### Expected behaviour
A clear and concise description of what you expected to happen:
Arte.TV replay should work

### Actual behaviour
Tell us what happens instead:
  404 Client Error: Not Found for url: https://api.arte.tv/api/player/v1/config/fr/093690-003-A
  Live TV works well, though.

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi 3
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 19.4.0 LibreElec 10.0.2
 - Catch-up TV & More version: 0.2.37+matrix.1
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

http://ix.io/418S

**Comment by joaopa00** [comment]
Il faut installer la béta pour avoir Arte.

**Comment by darodi** [comment]
@eric-blabla 

installer le repository beta 

https://catch-up-tv-and-more.github.io/installation/#ii-add-the-official-catch-up-tv--more-repository

**Comment by eric-blabla** [comment]
Merci mais cela ne répond pas à la question: dois-je d'abord DES-installer   le CUTV existant? Si oui, avec fichiers config, ou sans? Merci

**Comment by darodi** [comment]
non pas besoin de deinstaller

**Comment by eric-blabla** [comment]
merci darodi

**Comment by eric-blabla** [comment]
SOLVED. THANK YOU !
