### ISSUE TITLE
journal arte

### ISSUE THREAD

**Issue by jordanpires449** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#905]
### Content description

* Name:
* Type [e.g. TV channel, Catch-up TV, Website, Radio]:
* Website URL:
* Content language/country:

### Content access

- [ ] This content or some part of this content require a free account
- [x] This content or some part of this content require a paid account
- [x] This content is geographically restricted

### More information

If you want to add more information, put it here:

**Comment by jordanpires449** [comment]
essayer journal arte

**Comment by joaopa00** [comment]
Il faut donner le no de la video et la démarche pour y accéder avec catchuptvandmoe.
Et attacher ici le log de kodi.

**Comment by darodi** [comment]
@joaopa00

une longue série :)

- 1e ticket sans descriptif https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/892
- 2e ticket sans descriptif https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/894
- 3e ticket sans descriptif https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/895
- 4e ticket sans descriptif https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/896
- 5e ticket sans descriptif https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/897
- 6e ticket sans descriptif https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/905

**Comment by joaopa00** [comment]
Ah, je pensais l'avoir bloqué celui-là!
En tout cas, je ferme.
