### ISSUE TITLE
No access to the RTLplay and RTBF Auvio channels

### ISSUE THREAD

**Issue by david63236** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#911]
Error when trying to access RTLplay (Live tv and Replay tv) with Kodi 18.8 on Windows
ERROR: [Catch-up-TV-&-More.support] 'return' with argument inside generator (rtlplaybe.py, line 212)
I tested the other Belgium channels and found the same problem for RTBF (rtbf.py line 636).
All other Belgium channels are working.

I tested it with Kodi 19.1 on Windows, and with this version there are no problems.

**Comment by joaopa00** [comment]
What version of catchuptvandmore do you use?

**Comment by david63236** [comment]
Tested the zip: Problem solved for RTBF but not for RTLPlay.
The error still exists on line 212 in rtlplay.py (and line 239).
The solution is to comment the lines 212 and 239 in rtlplay.py

**Comment by nirolfa** [comment]
auvio replay not working since last week
they changed something about account to be verified, but even if you do it
replay not working 
(rtl play is working)

**Comment by joaopa00** [comment]
See also [video help forum](https://forum.videohelp.com/threads/405189-Download-from-RTBF)

**Comment by nirolfa** [comment]
> I confirm some new videos don't work
> 
> For example, in the fort-boyard emission, all videos work except the last one. this link doesn't work, https://www.rtbf.be/auvio/detail_fort-boyard?id=2920410
> 
> the api gives this url 'https://www.rtbf.be/tarmac/play/detail_fort-boyard?id=2920410' which points to nothing.
> 
> but the real auvio page uses this api url to get the stream https://exposure.api.redbee.live/v2/customer/RTBF/businessunit/Auvio/entitlement/2920410_6BA97Bb/play
> 
> This might help later:
> 
>     * [RTBF Broken yt-dlp/yt-dlp#4443](https://github.com/yt-dlp/yt-dlp/issues/4443)
> 
>     * [[rtbf.be] New videos not available for download ytdl-org/youtube-dl#31114](https://github.com/ytdl-org/youtube-dl/issues/31114)

yt-dlp fixed see ->https://github.com/elyse0/yt-dlp/tree/rtbf

**Comment by david63236** [comment]
The original problem of this issue (the 'return' with argument inside generator problem) has been solved
for RTBF and is solvable for RTLplay by commenting lines 212 and 239, so I close this issue.

A new issue has been created for the new RTBF stream provider change problem (issue #920)

**Comment by david63236** [comment]
The original problem of this issue (the 'return' with argument inside generator problem) has been solved
for RTBF and is solvable for RTLplay by commenting lines 212 and 239, so I close this issue.

A new issue has been created for the new RTBF stream provider change problem (issue https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/920)

**Comment by joaopa00** [comment]
I am not sure that removing the lines 212 and 239 is the correct fix. I will reopen this issue thi somebody using Kodi 18 will have this problem.

**Comment by joaopa00** [comment]
Should be fixed in git. I close

**Comment by Gaet81** [comment]
hi,
it isn't ix, I still do have the issue 'return' with argument inside generator in Kodi 18 on RTLPlay live and replay with Catchup 0.2.39-beta01
