### ISSUE TITLE
Les télévisions locales belges en direct ne fonctionnent plus + Quelques autres chaînes

### ISSUE THREAD

**Issue by JerryCrazy** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#912]
Bonjour, une partie des chaînes de la télévision locale belge francophone semblent ne plus fonctionner sur le direct.

https://mediasdeproximite.be/nos-medias-regionaux

Je ne sais pas si ça vous aidera, mais voici les liens que j'ai trouvé dans la console pour les flux en direct :

Antenne Centre TV https://tvlocales-live.freecaster.com/95d2f733-1bc2-4bd5-9b96-c53ed3fc450f/95d2f733-1bc2-4bd5-9b96-c53ed3fc450f.isml/95d2f733-1bc2-4bd5-9b96-c53ed3fc450f-audio_und=128000-video=5200000.m3u8
TéléSambre https://tvlocales-live.freecaster.com/95d2f67c-de80-486b-9e60-9c72cb2782e2/95d2f67c-de80-486b-9e60-9c72cb2782e2.isml/95d2f67c-de80-486b-9e60-9c72cb2782e2-audio_und=128000-video=2600000.m3u8
Boukè https://tvlocales-live.freecaster.com/95d2f70d-9229-478b-9aed-bc4fa220316d/95d2f70d-9229-478b-9aed-bc4fa220316d.isml/95d2f70d-9229-478b-9aed-bc4fa220316d-audio_und=128000-video=2600000.m3u8
Canal Zoom https://tvlocales-live.freecaster.com/95d2e3af-5ab8-45a9-9dc9-f544d006b5d5/95d2e3af-5ab8-45a9-9dc9-f544d006b5d5.isml/95d2e3af-5ab8-45a9-9dc9-f544d006b5d5-audio_und=128000-video=2600000.m3u8
MaTélé https://live.matele.be/hls/live.m3u8
NoTélé https://streaming01.divercom.be/notele_live/_definst_/direct.stream/playlist.m3u8
RTC Télé Liège https://tvlocales-live.freecaster.com/95d2f6eb-6f01-4d1d-8543-d14966de7b04/95d2f6eb-6f01-4d1d-8543-d14966de7b04.isml/95d2f6eb-6f01-4d1d-8543-d14966de7b04-audio_und=128000-video=5200000.m3u8
TéléMB https://tvlocales-live.freecaster.com/95d2f6c9-e85f-4388-8e9c-596260a4206f/95d2f6c9-e85f-4388-8e9c-596260a4206f.isml/95d2f6c9-e85f-4388-8e9c-596260a4206f-audio_und=128000-video=2600000.m3u8
TV Com https://tvlocales-live.freecaster.com/95d2f656-50f1-432b-84a6-ce11c6cdb482/95d2f656-50f1-432b-84a6-ce11c6cdb482.isml/95d2f656-50f1-432b-84a6-ce11c6cdb482-audio_und=128000-video=5200000.m3u8
TV Lux https://tvlocales-live.freecaster.com/95d2f631-8941-4efd-b223-0ebd56a033c4/95d2f631-8941-4efd-b223-0ebd56a033c4.isml/95d2f631-8941-4efd-b223-0ebd56a033c4-audio_und=128000-video=5200000.m3u8

Tant qu'à faire, il y a aussi Vedia qui n'est pas dans la liste des chaînes :
Vedia https://vedia.be
https://tvlocales-live.freecaster.com/95d2f480-3c9f-48ba-ba4e-af64b58431ef/95d2f480-3c9f-48ba-ba4e-af64b58431ef.isml/95d2f480-3c9f-48ba-ba4e-af64b58431ef-audio_und=128000-video=5200000.m3u8

Les flux de la VRT (Één, Canvas, Ketnet) ne fonctionnent plus sur Catch-Up TV And More, tout du moins, je n'ai pas de compte VRT NU, je ne sais pas si ça a une influence quelconque.
Ils sont disponibles là et fonctionnent sans comptes : https://vrt.be/vrtnu/livestream

La chaîne NRJ Hits TV n'existe plus en flux linéaire.
Canal C n'existe plus, remplacée par Boukè.

En international, les flux EuroNews semblent cassés, sur le site, ça passe par YouTube, je ne sais pas si ça a un rapport avec le soucis.

Merci à vous !

**Comment by joaopa00** [comment]
Pour moi avec la beta 0..2.37
TéléSambre, TéléMb RTC Télé Liege, Antenne CentreTVfontionnent

TV Lux, TV Com, , Bouké  ne fonctionne pas .


Peux-tu confirmer?

**Comment by joaopa00** [comment]
Je ferme cette issue car une majorité de chaines fonctionnent.
Si tu es encore intéressé pour fixer des chaines qui ne fonctionnent,
ouvre une issue par chaine qui ne fonctionne pas. C'est plus facile à gérer.
