### ISSUE TITLE
Plus de son France tv

### ISSUE THREAD

**Issue by KzANeo** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#914]
Bonjour,

Depuis plusieurs jours, je n' ai plus aucun son sur toutes les chaînes de France tv, je n ai que l image
Les autres chaînes fonctionnent parfaitement .
Quelqu un d autres est dans le mm cas ?

Merci.

**Comment by joaopa00** [comment]
Ca marche chez moi.

**Comment by KzANeo** [comment]
Je viens de tout refresh et toujours la même chose.
Au niveau du Flux Audio, j ai bien le canal utilisé pour les autres chaînes, alors que pour toutes les chaînes de France TV, il est indiqué Aucun, ce qui me explique pourquoi je n' ai pas de son😄.. maintenant, il reste à savoir pourquoi 😅

**Comment by KzANeo** [comment]
Vider la cache au niveau du module en mode expert
