### ISSUE TITLE
https://sso-client.sfr.fr:443 "GET /cas/services/rest/3.2/createToken.json?duration=86400

### ISSUE THREAD

**Issue by xXMiryokuXx** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#915]
https://sso-client.sfr.fr:443 "GET /cas/services/rest/3.2/createToken.json?duration=86400

Bonjour impossible d'acceder a rcm et bfm tv, j'ai vérifier plusieurs fois le mdp et c'est pas ça. Ps je suis sur Android. Help plz :)

_Originally posted by @xXMiryokuXx in https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/830#issuecomment-1191954043_

**Comment by joaopa00** [comment]
Utilises-tu la dernère versio, beta?Actuellement c'est la version 0-2.39.

**Comment by xXMiryokuXx** [comment]
> 

Bonjour non 0.2.37

**Comment by xXMiryokuXx** [comment]
> Utilises-tu la dernère versio, beta?Actuellement c'est la version 0-2.39.

J'ai installé la bêta et ça fonctionne merciiii ;)
