### ISSUE TITLE
Certains replay de tf1 ne sont plus accessibles.

### ISSUE THREAD

**Issue by totolao** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#917]
Depuis une semaine que cela soit sur le site de mytf1 ou l'appli mytf1 pour android certains replay ne sont accessibles que si on est inscrit sur le site. Est-il possible de rajouter mytf1 dans l'option compte à la suite de M6, NRJ12 et BFMTV.
Merci.

**Comment by joaopa00** [comment]
Peux-tu donner le lien d'une vidéo qui requiert un compte et qui ne fonctionne pas sur Catchuptvandmore?

**Comment by joaopa00** [comment]
Pas de nouvelles du reporter. Je ferme.

**Comment by totolao** [comment]
Pardon pour cette réponse tardive.
Sur tf1 les séries Esprits criminels, les experts, Nez York unité speciale ne sont pas accessibles.
Je suis sur Kodi pour android tv. Je ne sais pas où récupérer le log.

Cordialement.
JC


Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : ***@***.***>
Envoyé le :vendredi 29 juillet 2022 23:26
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [Catch-up-TV-and-More/plugin.video.catchuptvandmore] Certains replay de tf1 ne sont plus accessibles. (Issue #917)


Peux-tu donner le lien d'une vidéo qui requiert un compte et qui ne fonctionne pas sur Catchuptvandmore?

**Comment by joaopa00** [comment]
Je confirme qu'il y a un problème avec ces videos.

**Comment by Arias800** [comment]
J'ai un fix de prêts.
Je fais le pull request une fois le nettoyage fini.
