### ISSUE TITLE
Les replays de NRJ12 et Chérie25 ne marchent plus

### ISSUE THREAD

**Issue by smax86** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#918]
### Describe the bug
Les replays de NRJ12 et Chérie25 ne marchent plus. La petite roulette bleue de chargement tourne indéfiniement.

### To Reproduce
Steps to reproduce the behaviour:
1. Essayer de lire n'importe quelle vidéo du replay de NRJ12 ou Chérie 25
2.
3.
4.

### Expected behaviour
A clear and concise description of what you expected to happen:
Que la vidéo sélectionnée démarre.

### Actual behaviour
Tell us what happens instead:
Une fois que l'on sélectionne une vidéo, la petite roulette bleue de chargement tourne indéfiniement.

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ X ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version:
 - Catch-up TV & More version:
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment]
Should be fixed in git. Or you can wait for the next release of the beta.

**Comment by smax86** [comment]
Testé, c'est effectivement à nouveau fonctionnel. Merci
