### ISSUE TITLE
Le live de Canal+, C8... ne marche plus (Index Error - list index out of range)

### ISSUE THREAD

**Issue by smax86** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#919]
### Describe the bug
A clear and concise description of what the bug is:
Le live de Canal+, C8... ne marche plus.
Lorsqu'une de ces chaînes est sélectionnée, le message d'erreur suivant s'affiche instantannément:
"Index Error - list index out of range"

### To Reproduce
Steps to reproduce the behaviour:
1. Essayer d'afficher le live de Canal+ ou C8 par exemple.
2.
3.
4.

### Expected behaviour
A clear and concise description of what you expected to happen:
Que le live de Canal+ ou C8 par exemple fonctionne.

### Actual behaviour
Tell us what happens instead:
Lorsque le live de Canal+ ou C8 est sélectionné, le message d'erreur suivant s'affiche instantannément:
"Index Error - list index out of range"

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version:
 - Catch-up TV & More version:
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment]
En attendant, il doit être possible d'utiliser les liens dailymotion (à configurer dans les options de Catchuptvandmore)

**Comment by smax86** [comment]
Ca marche à nouveau, je ferme le ticket.
