### ISSUE TITLE
Would it be possible to get replay with VO and subtitles ?

### ISSUE THREAD

**Issue by alexismorillo** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#92]
It would be a nice feature to replay in VOST.

**Comment by wwark** [comment]
Hi Alexis,

It depends of channel. There is some VO for France TV Live TV and also recently in this plugin Kodi 18 test DRM https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmoretestdrmkodi18 
Some Replay (US TV shows) for M6 group channels have VO and subtitle.
BR,
Wwark

**Comment by wwark** [comment]
Arte.tv have also some VO. You need to activate DIALOG (quality) in the configuration of the plugin to access to these contents.

**Comment by wwark** [comment]
Hi,
I hope my answer is good.
I closed this ticket. Do not hesitate if you need to reopen it.
Thanks,
Wwark

**Comment by alexismorillo** [comment]
Yes, it is perfect. I tried it and it worked like a charm. Thank you for the quick answer.
