### ISSUE TITLE
Live TV | France 24 (EN): HTTP error 400 Bad Request

### ISSUE THREAD

**Issue by mearubato** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#921]
Back in June I reported a problem in the [forum](https://forum.kodi.tv/showthread.php?tid=307107&pid=3100848#pid3100848) about the subject station. At that time the error was:

ERROR <general>: [Catch-up-TV-&-More.support] Exceeded 30 redirects

I reported again in July it was still not working, but the error had changed to:

DEBUG <general>: ffmpeg[0x5594da3710X]: [http] HTTP error 400 Bad Request

and it has continued in that state since. I have since tried re-installing the add-on from the GitHub repository as described in the Wiki page of this project - using both the stable and beta channels. I have also tried installing the "dev.zip" posted in the "List of known issues (read first)" page of this project. The problem is the same with each.

Steps to reproduce the behaviour:
1. Launch the Catch-Up TV & More add-on from Add-ons in Kodi
2. Navigate: Live TV | International | France 24 (EN)
3. Press enter.

Expected Behaviour:
Launching the broadcast should present a rotating gear object, the screen may blink, but should continue rotating until the broadcast is presented on the screen.

### Actual behaviour
The rotating gear object appears briefly, the screen blinks but returns to the list of stations. The broadcast never starts and there's no error message presented on the screen.

Your Environment:
- Raspberry-Pi 4 with 4GB RAM
- Operating system version/name: Raspberry Pi OS, 11 Bullseye, kernel 5.15.32-v8+, aarch64
- Kodi version: 19.4
- Catch-up TV & More version: 0.2.37+matrix.1, 0.2.38 and "dev.zip"
- Installation method: Install from repository for Kodi official version and Install from Zip for one from this project's repository

Debug Log
https://paste.kodi.tv/fupomiyoqi

I have checked through the existing list of issues and don't see anyone reporting this particular problem. I am in Canada and configure the add-on with the "EN" language.

Thanks,
John

**Comment by joaopa00** [comment]
Should be fixed in the latest beta.

**Comment by mearubato** [comment]
Installed latest beta version 0.2.38~beta42. Problem fixed.

Thanks
