### ISSUE TITLE
Live TV | DW (EN): Invalid URL '': No scheme supplied

### ISSUE THREAD

**Issue by mearubato** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#922]
Back in June I reported a problem in the [forum](https://forum.kodi.tv/showthread.php?tid=307107&pid=3104399#pid3104399) about the subject station. At that time the error was:

Error: [Catch-up-TV-&-More.support] Unable to resolve url

A couple of weeks later I updated the forum in July that the problem had resolved itself. Today I see that the problem is back again, but the error has changed to:

ERROR <general>: [Catch-up-TV-&-More.support] Invalid URL '': No scheme supplied. Perhaps you meant http://?

I have since tried re-installing the add-on from the GitHub repository as described in the Wiki page of this project - using both the stable and beta channels. I have also tried installing the "dev.zip" posted in the "List of known issues (read first)" page of this project. The problem is the same with each.

Steps to reproduce the behaviour:
1. Launch the Catch-Up TV & More add-on from Add-ons in Kodi
2. Navigate: Live TV | International | DW (EN)
3. Press enter.

Expected Behaviour:
Launching the broadcast should present a rotating gear object, the screen may blink, but should continue rotating until the broadcast is presented on the screen.

Actual Behaviour:
The rotating gear object appears briefly, then an Information dialog is presented reporting an unexpected error asking if I wish to share the error log. I click "No" and the screen returns to the list of stations. The broadcast never starts.

Your Environment:
- Raspberry-Pi 4 with 4GB RAM
- Operating system version/name: Raspberry Pi OS, 11 Bullseye, kernel 5.15.32-v8+, aarch64
- Kodi version: 19.4
- Catch-up TV & More version: 0.2.37+matrix.1, 0.2.38 and "dev.zip"
- Installation method: Install from repository for Kodi official version and Install from Zip for one from this project's repository

Debug Log
https://paste.kodi.tv/oqiyiqanut

I have checked through the existing list of issues and don't see anyone reporting this particular problem. I am in Canada and configure the add-on with the "EN" language.

Thanks,
John

**Comment by joaopa00** [comment]
Should be fixed in Git

**Comment by mearubato** [comment]
Installed latest beta version 0.2.38~beta42. Problem fixed.

Thanks
