### ISSUE TITLE
France 24 in french

### ISSUE THREAD

**Issue by frator33** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#923]
France 24 in french doesn't works with Kodi 19.3 and cutvm 0.2.38~beta41

**Comment by joaopa00** [comment]
Should be fixed in the latest beta.

**Comment by frator33** [comment]
Thanks for the message and for all the job !

⁣Télécharger TypeApp pour Android ​

Le 16 août 2022, 13:48, à 13:48, joaopa00 ***@***.***> a écrit:
>Should be fixed in the latest beta.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/923#issuecomment-1216527529
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by joaopa00** [comment]
Since this problem is solved, I close the issue.

**Comment by frator33** [comment]
I've seen, thanks a lot 😉

⁣Télécharger TypeApp pour Android ​

Le 16 août 2022, 20:44, à 20:44, joaopa00 ***@***.***> a écrit:
>Since this problem is solved, I close the issue.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/923#issuecomment-1217013892
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>
