### ISSUE TITLE
ERT channels and ERTFlix

### ISSUE THREAD

**Issue by RONTVHD** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#926]
### Content description

* Name: ERT
* Type [e.g. TV channel, Catch-up TV, Website, Radio]: TV channels and Catch-up TV
* Website URL: https://www.ertflix.gr
* Content language/country: Greece

### Content access

- [ ] This content or some part of this content require a free account
- [ ] This content or some part of this content require a paid account
- [X] This content is geographically restricted (Only EPT 1-3 and Sports)

### More information

If you want to add more information, put it here:

**Comment by joaopa00** [comment]
At least, live channels should be fixed in git.
