### ISSUE TITLE
Unable to download replay video

### ISSUE THREAD

**Issue by ilyatout** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#928]
### Describe the bug
A clear and concise description of what the bug is:
The option to download a replay video is not displayed. I can Read a vidéo but not download it
### To Reproduce
Steps to reproduce the behaviour:
1. Open replay of m6 
2. Chose à replay video
3.no option to download :(
4.

### Expected behaviour
A clear and concise description of what you expected to happen:

### Actual behaviour
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [x ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version:
 - Catch-up TV & More version:
 - Installation method:

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment]
It's normal. Some videos from M6 use DRM. DRM does not allow to download. Since Catchuptvandmore is  a legal software, it does not not ( nad will never not) implement workarounds to bypass this restriction.

So, it is not an issue.

Sorry.
