### ISSUE TITLE
[BE RTBF auvio] DRM content doesn't work on android/rpi

### ISSUE THREAD

**Issue by darodi** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#935]
Le cas qui me pose problème, avec DRM:

- rechercher les programmes
- Boyard
- Fort Boyard
- Lancer la dernière vidéo du 12/08

Sur windows, la vidéo se lance. OK
Sur raspberry pi, j'ai l'erreur suivante. KO

- PRETTY_NAME="Open Source Media Center"
- NAME="OSMC"
- VERSION="March 2022"
- VERSION_ID="2022.03-1"

même problème sous android KO

OK sous windows

```
2022-08-17 22:55:45.002 T:1324     INFO <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file. #Periods: 1, #Streams in first period: 2, Type: VOD, Download speed: 2854526.4441 Bytes/s
2022-08-17 22:55:46.193 T:1324    ERROR <general>: CCurlFile::FillBuffer - Failed: HTTP returned error 502
2022-08-17 22:55:46.193 T:1324    ERROR <general>: CCurlFile::Open failed with code 502 for https://rbm-rtbf.live.ott.irdeto.com/licenseServer/widevine/v1/rbm-rtbf/license
```

Peut-être une différence avec "inputstream adaptive/inputstream helper" entre les périphériques....
`...`

_Originally posted by @darodi in https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/924#issuecomment-1219737389_

**Comment by darodi** [comment]
plus d'infos et logs dans

- https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/920

**Comment by darodi** [comment]
même problème pour les lives avec DRM

**Comment by joaopa00** [comment]
L'explication la plus probable est dans la requete que Inputstreamhelper fait au serveur. Certainement, le header n'est pas identique entre android et windows et il y a quelque chose que le serveur de RTBF n'aime pas.

**Comment by joaopa00** [comment]
On peut supposer que c'est fixé maintenant.

**Comment by nirolfa** [comment]
@Gaet81 live is not working anymore since yesterday evening
403 error from redbee
the replay are working fine

**Comment by darodi** [comment]
@nirolfa 


> For the live, as it has a different url for each live it's no more possible to get it on the PVR...
`...`
> You need to go to RTBF auvio folder in the live to get it works.

_Originally posted by @Gaet81 in https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/937

**Comment by nirolfa** [comment]
@darodi thanks for the tip, missed it ;)

**Comment by 750913372** [comment]
Thank you for the tip for the usage of the RTBF Auvio folder for live on Android, but currently I just have entries for RTBF radio channels broadcast (and not always the same).
Does anybody else has the same?  Or instead a list of the RTBF TV Channels (La Une, La Deux La Trois) as (I) expected ?
Thank you.
