### ISSUE TITLE
Pas de flux vidéo pour les chaînes 6Play

### ISSUE THREAD

**Issue by enzolry** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#942]
### Describe the bug
Lorsque je sélectionne une chaîne du groupe 6Play (M6 ou W9), l'authentification fonctionne et je suis bien redirigé sur la chaîne mais je n'ai que le son. Il y a aussi parfois le temps qui défile en bas, mais pas de flux vidéo, seulement le fond bleu de l'application.

### To Reproduce
1. Lancer KODI
2. Se rendre dans l'onglet TV
3. Sélectionner la chaîne M6 ou W9
4. Même en patientant plus d'une minute, il n'y a que le son

### Your environment
 - [x] Android 11
 - [x] Raspberry-Pi 4B 4Go revision 1.2

 - Operating system version/name: LineageOS 18.1 - Android 11 (TV)
 - Kodi version: 19.3.0 (J'ai également essayé avec la 18.9 et la 18.8)
 - Catch-up TV & More version: 0.2.39~beta02 (J'ai également essayé avec la 0.2.38 et la 0.2.37+matrix.1)
 - Installation method: Installation de l'OS en suivant ce tuto https://konstakang.com/devices/rpi4/LineageOS18-ATV/ et toute la partie Catch-up en suivant les instructions du site.

**Comment by joaopa00** [comment]
Fonctionne bien sous linux, windows et android. Surement un problement avec WIdevine sous rasperri. Sûrement, ce n'est pas un problème de Catchuptvandmore.

**Comment by enzolry** [comment]
J'ai trouvé une solution radicale, en basculant de LineageOS et toute sa surcouche Android TV vers LibreELEC 9.2.8 et Kodi 18 (La dernière version de LibreELEC ne fonctionne pas avec Catch-up). Kodi a bien déclenché l'installation de Widevine lorsque j'ai lancé M6 la première fois.
