### ISSUE TITLE
Cnews replay incohérent

### ISSUE THREAD

**Issue by gilles0606** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#943]
Bonjour,

sur Cnews dans le replay il y a une liste d’émission.
imaginons je veux voir soir info d'hier...

je prend soir info dans la liste, et là, il n'y a pas la bonne date, il n'y a pas celle d'hier et d'avant hier par exemple.

il faut que je ressorte de là, et je trouve tous les soir info de la liste et que je trouve le bon.
parfois il est en page 7 ou 8, et il faut 10 essais avant de trouver le bon...

c'est un enfer....

on peut faire quelque chose ?

Merci

**Comment by darodi** [comment]
Peux-tu donner un exemple?
Je vois que c'est trié par date décroissante

![image](https://user-images.githubusercontent.com/4682830/189538695-f0850ea9-f3ce-4960-b022-0170a682b72d.png)


Quand tu vas dans le menu de gauche, comment est fait le tri?

![image](https://user-images.githubusercontent.com/4682830/189538785-49d7a4c3-c1e7-4124-89f8-14e41603956e.png)

**Comment by gilles0606** [comment]
Bonsoir,

 

Déjà merci d’avoir regardé…

Tu as exactement trouvé le bug, enfin tu l’as reproduit.

L’image que tu donnes est le lien Soir info de la première page du plug-in…

Si tu explores les 8 premières pages… (oui c’est long…)

Tu trouves plein d’autres Soir info

Et tu les explores un à un, et sur la page 7 ou 8 tu trouves enfin…

 



 

Car les soirs infos sont tous différents, et il faut trouver le bon, celui ici qui contient le soir info du 09/09.

Il met plein de soirs info, mais ils sont tous différents et le dernier, celui qui contient la dernière émission est parfois loin… loin…

 

Bien à toi…

 

Gilles

 

 

 

De : darodi ***@***.***> 
Envoyé : dimanche 11 septembre 2022 18:33
À : Catch-up-TV-and-More/plugin.video.catchuptvandmore ***@***.***>
Cc : gilles0606 ***@***.***>; Author ***@***.***>
Objet : Re: [Catch-up-TV-and-More/plugin.video.catchuptvandmore] Cnews replay incohérent (Issue #943)

 

Peux-tu donner un exemple?
Je vois que c'est trié par date décroissante

 <https://user-images.githubusercontent.com/4682830/189538695-f0850ea9-f3ce-4960-b022-0170a682b72d.png> 

Quand tu vas dans le menu de gauche, comment est fait le tri?

 <https://user-images.githubusercontent.com/4682830/189538785-49d7a4c3-c1e7-4124-89f8-14e41603956e.png>

**Comment by gilles0606** [comment]
![image](https://user-images.githubusercontent.com/38776814/189544500-f5c44ac7-1455-487a-bf76-da2710b93321.png)

**Comment by gilles0606** [comment]
Bonsoir,

Déjà merci d’avoir regardé…
Tu as exactement trouvé le bug, enfin tu l’as reproduit.
L’image que tu donnes est le lien Soir info de la première page du plug-in…
Si tu explores les 8 premières pages… (oui c’est long…)
Tu trouves plein d’autres Soir info
Et tu les explores un à un, et sur la page 7 ou 8 tu trouves enfin…


![image](https://user-images.githubusercontent.com/38776814/189544517-96b8ea48-6657-4464-a44e-f9afb7e9dc7d.png)


Car les soirs infos sont tous différents, et il faut trouver le bon, celui ici qui contient le soir info du 09/09.
Il met plein de soirs info, mais ils sont tous différents et le dernier, celui qui contient la dernière émission est parfois loin… loin…
Bien à toi…

Gilles
