### ISSUE TITLE
Impossible to watch TVA canada replay

### ISSUE THREAD

**Issue by JustBeta** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#945]
### Describe the bug
Impossible to watch TVA canada replay.
find the program on list select this and no start .
Kodi left popup AssociatedEtities

### To Reproduce
Steps to reproduce the behaviour:
1. just watch replay of TVA canada 

### Expected behaviour
Just view the program select

### Actual behaviour
the program not start, just one popup left on Kodi with message AssociatedEtities

### Screenshots
![image](https://user-images.githubusercontent.com/25150896/188319480-5be869f4-9e6d-4a62-864f-9681b086c1d7.png)

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ X] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 19.4
 - Catch-up TV & More version: 0.2.39~beta02
 - Installation method: 
by the repository

### Additional context
Add any other context about the problem here:
use NordVPN for acces this

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/9484912/kodi.log)

**Comment by joaopa00** [comment]
>just watch replay of TVA canada

is not enough to help to reproduce tbe problem. You have to indicate all the steps to reproduce the problem.

**Comment by JustBeta** [comment]
Hello, 

here is my description:
I'm start my vpn and connect to canada.
check my ip is correct for this country
start Kodi
go to extension menu
select CatchUpTV
select 'Television de rattrapage' replay
select Canada Country
select TVA
select TVA
select L letter in list
find 'les feux de l'amour'
select saisons 17
and get error

thank's,

**Comment by joaopa00** [comment]
Thanks. I managed to reproduce the problem.

**Comment by JustBeta** [comment]
thank you for your help

**Comment by JustBeta** [comment]
I confirm, Thank's for your help.
