### ISSUE TITLE
Canal ou RMC ? :)

### ISSUE THREAD

**Issue by OoAnikioO** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#947]
### Describe the bug
A clear and concise description of what the bug is:

impossible d'avoir le groupe canal et rmc en même temps avec la même version de catchup

### To Reproduce
Steps to reproduce the behaviour:

1. 

### Expected behaviour
A clear and concise description of what you expected to happen:

Une solution pour avoir les 2 groupes avec une seule version de catchup installer

### Actual behaviour
Tell us what happens instead:

Au départ, je n'arrivais pas à lire les chaînes du groupe RMC, j'avais une erreur de type.

"[https://sso-client.sfr.fr:443](https://sso-client.sfr.fr/) "GET /cas/services/rest/3.2/createToken.json?duration=86400"

Mais pas de problème avec le groupe canal (ceci avec la version stable de catchup)
Suite à des recherches, ou on conseille d'installer la beta de catchup, je le fais, et là, j'ai le groupe rmc, mais plus canal erreur de type : 

"indexerror, list index out of range"

J'ai pensé que c'était du a une installation de catchup l'une sur l'autre, stable sur beta, j'ai donc tout effacer, kodi y compris, et recommencer. Et bien même erreur, avec la stable, pas de rmc, mais canal et avec la beta, pas de canal, mais rmc avec les erreurs ci-dessus

PS : j'ai bien fait gaffe a mes identifiants...

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [X ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: 
 - Kodi version: 19.4
 - Catch-up TV & More version: version beta et stable
 - Installation method: celle du site

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment]
Tu utilises certainement une vieille verion de Catchuptvandmore. Tu dois mettre à jour. Je te conseille laversion beta. Sinon tu peux installer la version stable ici
https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/releases/tag/v0.2.38

**Comment by Arias800** [comment]
Chez moi, le site Mycanal ne marche tout simplement pas.
Donc ça vient potentiellement de là.
Dans les options de Catchup tv and more, il y a une option pour utiliser le flux Dailymotion, il peut dépanner.

**Comment by OoAnikioO** [comment]
> Tu utilises certainement une vieille verion de Catchuptvandmore. Tu dois mettre à jour. Je te conseille laversion beta. Sinon tu peux installer la version stable ici https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/releases/tag/v0.2.38

je pense que tu as mal lu mon texte, beta : rmc, pas canal    stable : canal, pas rmc   c'est soit l'un soit l'autre, du coup je jongle entre chaque version quand je veux regarder l'un ou l'autre

**Comment by darodi** [comment]
@OoAnikioO 

avec la dernière version beta, pour canal, comment obtiens-tu
`"indexerror, list index out of range"`
Peux-tu donner un exemple?
Merci

**Comment by Arias800** [comment]
J'ai trouvé l'origine du bug, je bosse sur une correction.

C'est cette option : 
![image](https://user-images.githubusercontent.com/24809312/189693908-dbad6f1b-a555-4ed8-811d-92f4b4d69f74.png)

**Comment by OoAnikioO** [comment]
c'est corrigé ? je re-telecharge la beta ? ou c'est un patch ?

**Comment by darodi** [comment]
@OoAnikioO 

il faut attendre le merge de la pull request #950 pour avoir une beta corrigée.
ou alors utiliser les sources de https://github.com/Arias800/plugin.video.catchuptvandmore/tree/patch-2
