### ISSUE TITLE
TVA New bug

### ISSUE THREAD

**Issue by JustBeta** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#954]
### Describe the bug
Obtention de l'erreur 404 en accèdent au flux TVA
la précédente modification a parfaitement fonctionné jusqu'au lendemain de ca sortie

### To Reproduce
Steps to reproduce the behaviour:
1. Démarrage de mon vpn et connexion au canada.
2. Verification que l'IP correspond au pays
3. Démarrage de Kodi
4. Accès au menu extension
5. Selection de CatchUpTV
6. Selection de 'Television de rattrapage'
7. Selection de Canada
8. Selection de TVA
9. Selection de TVA
et obtention de l'erreur.

### Expected behaviour
A clear and concise description of what you expected to happen:

### Actual behaviour
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:
![tva1](https://user-images.githubusercontent.com/25150896/190562567-cacb7a5f-3189-4f90-b888-a2fce23db3dc.png)
![tva2](https://user-images.githubusercontent.com/25150896/190562576-20a5f9b2-fabe-4963-929b-ce78590ea64f.png)

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 19.4
 - Catch-up TV & More version: 0.2.39~beta03
 - Installation method: via le repository dev

### Additional context
Add any other context about the problem here:

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/9580905/kodi.log)

**Comment by JustBeta** [comment]
Merci, c'est OK avec la 0.2.39~beta04.
Cependant, pour info, avec l'update, cela ne fonctionné pas non plus.
J'ai désinstallé l'Add-Ons et réinstallé la version zip. Et cela a fonctionné.
Peut être (surement) lié à ma config, mais juste pour l'information.

**Comment by darodi** [comment]
@JustBeta 

le changement sera dans la beta5 ou alors il faut prendre le code de la branche dev dans github

**Comment by JustBeta** [comment]
ok merci pour l'info.
