### ISSUE TITLE
M6 group channel stopped working

### ISSUE THREAD

**Issue by mac1202** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#959]
Hello I have upgraded to the latest version available on the beta repo. And now the channel from M6 group stopped working. I have an error "6play: erreur de l'authentification". Thanks.

**Comment by joaopa00** [comment]
I am unable to reproduce the problem. M6 channel works fine for me. You report is very incomplete. You have to tell all the steps to reproduce the problem.

**Comment by darodi** [comment]
![image](https://user-images.githubusercontent.com/4682830/191325735-9053c21e-e8d6-4af3-9904-5bf238517ce3.png)

**Comment by mac1202** [comment]
Try again I have updated the link.

**Comment by joaopa00** [comment]
Unable to reproduce in Linux, android and windows. All the channels work fine.
My advice. Rewrite your credentials. Logout out Kodi. And reopen Kodi.

**Comment by mac1202** [comment]
Already try that, didnt fix it.

**Comment by mac1202** [comment]
I find the issue, my 6play account has been deleted. Recreate it and now it work again. Thank for taking the time to test on your side it help me to search issue outside of kodi.
