### ISSUE TITLE
No watched/unwatched indicator

### ISSUE THREAD

**Issue by Flavien** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#97]
There doesn't seem to be an indicator that shows whether the show was watched or not.

Is it possible to add one?

**Comment by wwark** [comment]
Hi Flavien,
What is the version of the plugin do you use ?
Do you have some examples of contents doesn't show watched and unwatched ?

Thanks,
Wwark

**Comment by Flavien** [comment]
I'm on version 0.2.0~beta11 from the dev branch, running on Kodi 18 beta 5.

See below there is no indication for watched/unwatched items:

![image](https://user-images.githubusercontent.com/296540/48135700-90137980-e295-11e8-9fd5-4cce498e377d.png)

Marking an item as watched doesn't do anything.

**Comment by wwark** [comment]
we opened this ticket https://github.com/willforde/script.module.codequick/issues/19

**Comment by willforde** [comment]
Same for me, not working. But it is working for the youtube add-on now.
I might be doing something that is conflicting and did some testing. I found that watched/unwatched worked when a Listitem is linking directly to a video, instead of redirecting back to the add-on to be resolved.

**Comment by wwark** [comment]
Hi Flavien,
The developper of the framework Codequick make a fix in the development branch of codequick. Thanks to him !
You can install it to test it but in the next release of codequick the fix will be present.

I let open the ticket and close it when the new version of codequick is released.
Thanks,
Wwark

**Comment by Flavien** [comment]
Cool, well done to both.

Unrelated question: when do you plan to merge the Leia DRM changes into the main add-on? I have been using it since it plays the 6play channels in 480p instead of 240p, and it seems to work well.

**Comment by wwark** [comment]
Thanks !
For your question, we will released 0.2.0 after finish test on it.
After we will merge the test DRM plugin in the principal one (developpement) and we will released the version 0.2.1. Normally it will around the release of Kodi 18.
Wwark

**Comment by Flavien** [comment]
Ok, thanks. Looking forward to it.

**Comment by wwark** [comment]
Codequick 0.9.7 is out with the fix.
I close this ticket.
