### ISSUE TITLE
NRJ Group (NRJ12 and Chérie25)  broken

### ISSUE THREAD

**Issue by darodi** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#971]
### Describe the bug

      Hi !
      I'm running catchup TV with NRJ Play to access french channels from the NRJ Group (NRJ12 and Chérie25) but it doesn't correctly works. When I'm trying to play one of these channels, the servers seems to detect that the client is not an official player authorized by NRJ Group. So I got this message in a loop presentation video :
      
      understand : "this broadcast is unavailable on this application or website"
      Sometimes only one channel got this error and sometimes both...
      
      Thanking you in advance Smile

_Originally posted by [strike0707](https://forum.kodi.tv/member.php?action=profile&uid=474746) in https://forum.kodi.tv/showthread.php?tid=369942

**Comment by Arias800** [comment]
It's not a bug.
This message appears on the website too.

That's stupid, but It can't be fixed.

**Comment by darodi** [comment]
ok closed then
I'll reply in that forum
