### ISSUE TITLE
Japan Shows Broken - Tver API update

### ISSUE THREAD

**Issue by kalun85** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#976]
Hi.  It seems like TVer has updated their search APIs.

Currently in the Catch-up TV code (resources/lib/channels/jp/tver.py), base, the following API call is used:

`URL_REPLAY_PROGRAM = 'https://platform-api.tver.jp/service/api/v1/callSearch?platform_uid={}&platform_token={}'`

Previously, this returns the show result, but now, it will just return 
```

{
    "message": "Not Found"
}
```

I did some digging, it seems like searching for a full list of shows is dead, but you can search via different TV channels.

In your code, here are the mapping I can find:
```

BROADCASTER = {
    'abc': ['ABCテレビ'],
    'cx': ['フジテレビ', 'テレビ愛媛', 'テレビ宮崎', 'さんいん中央テレビ', 'BSフジ', '北海道文化放送', '仙台放送', '福井テレビ', 'テレビ西日本', '東海テレビ', 'STSサガテレビ', '沖縄テレビ', 'テレビ熊本', 'OHK 岡山放送', 'テレビ静岡'],
    'ex': ['テレビ朝日', 'KBCテレビ', 'BS朝日', 'KAB熊本朝日放送', '静岡朝日テレビ'],
    'ktv': ['カンテレ'],
    'mbs': ['MBS毎日放送'],
    'nhk': ['NHK', 'NHK総合・東京', 'NHK Eテレ・東京'],
    'ntv': ['日テレ', '山梨放送', 'BS日テレ', 'KKTくまもと県民テレビ', '日本海テレビ', 'TeNY', 'tvk', 'Daiichi-TV', '中京テレビ', 'FBS福岡放送', 'テレ玉', 'テレビ信州', '高知放送', '長崎国際テレビ', 'STV札幌テレビ放送', '福島中央テレビ', 'TOKYO MX', 'チバテレ', '広島テレビオンデマンド', 'RAB青森放送', '鹿児島読売テレビ', 'BS11', '南海放送', '福井放送'],
    'tbs': ['TBS', 'TUYテレビユー山形', 'CBCテレビ', 'RKK熊本放送', 'HBC北海道放送', 'BS-TBS', 'MRO', 'RCCテレビ', 'BSN', 'TUFテレビユー福島', 'SBC信越放送', 'RKB毎日放送'],
    'tver': ['TVER'],
    'tvo': ['テレビ大阪'],
    'tx': ['テレビ東京', 'TVh', 'ＢＳテレ東', 'ＢＳテレ東 ほか', 'TVQ九州放送'],
    'ytv': ['読売テレ']
}
```
The new format follows:

`https://platform-api.tver.jp/service/api/v1/callTagSearch/{broadcaster tag}?platform_uid={platform ID}&platform_token={platform_token}
`
for example, cx on the list = , and URL would be

`https://platform-api.tver.jp/service/api/v1/callTagSearch/fns?platform_uid={platform ID}&platform_token={platform_token}
`
Here is the mapping I can find

```
abc = abc
cx = fns
ex = exnetwork
ktv = ktv
mbs = mbs
nhk = nhknet
ntv = nns
tbs = jnn
tver = tver
tvo = tvo
tx = txn
ytv = ytv

```

It seems like the old broadcast ID Tag still works on searching via broadcaster (for example, if you use cx and fns as the broadcast id).  Not sure when they will change that

**Comment by joaopa00** [comment]
Should be fixed in git.
Thanks for the fix.

**Comment by kalun85** [comment]
tested, seems to work, thanks :)
