### ISSUE TITLE
guide TV vide depuis le 27 octobre

### ISSUE THREAD

**Issue by theoden11** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#979]
Toutes plateformes
Le guide TV est vide
L'url https://raw.githubusercontent.com/Catch-up-TV-and-More/xmltv/master/tv_guide_fr.xml montre que le grabber ne fonctionne plus depuis le 27/10

**Comment by joaopa00** [comment]
J'ai mis à jour le fichier de récupération des programmes français. Malheureusement, je ne pense pas que cela soit suffisant pour régler tous les problèmes. Cela devrait tenir une petite semaine et après retour des problèmes.

**Comment by theoden11** [comment]
Bonsoir. Pour l'instant le guide TV marche toujours après 5j de vide entre le 28 octobre et le 2 novembre, il manque juste Arte dans les chaines françaises. Il y a aussi un décalage de numérotation qui s'est produit, probablement parce que j'ai cherché, donc effacé les paramètres puis réinstallé captchuptv et réactivé l'intégration TV; pensant comme toujours que le problème venait de ma machine au départ. Les chaines 20 à 25 sont décalées de 1 en moins : la 20 est affectée au 19, RMC découverte qui devrait être la 24 se retrouve en 23 etc. Je n'ai rien modifié et je n'ai pas retrouvé le moyen de changer facilement le numéro de la chaine, ce qui par le passé était possible. Ca ne pose pas de problème pour voir la chaine, c'est juste  psychologique car il y a décalage avec le programme TV sur Orange ou le zappeur par ex. Le souci est que sur la 19 il ne devrait rien y avoir, avant c'étant France O qui a disparu.

**Comment by theoden11** [comment]
J'ai depuis longtemps d'autres url de guide TV xml tout prêt; je les utilisais auparavant avec catchuptv avant l'intégration TV en remplacement de bit.ly/tv_guide_fr. A voir s'il est possible et où on peut intégrer cette url dans catchup en mode dégradé. Avant, c'était facile, c'était dans userdata, dans les paramètres de PVR IPTV simple. Maintenant ça ne marche plus, ça a l'air plus compliqué.

**Comment by Kanolm** [comment]
Salut,
Je me trouve confronté au même souci.
J'utilise Kodi avec Catchup sur une box android.
Il semblerait que l'url des guides tv pointe vers un fichier qui n'existe pas:
[Catch-up-TV-&-More] xmltv module failed with error: 404 Client Error: Not Found for url: https://github.com/Catch-up-TV-and-More/xmltv/raw/master/tv_guide_fr_20221113.xml
Alors que l'url qui est en ligne est:
https://github.com/Catch-up-TV-and-More/xmltv/tree/master/raw/tv_guide_fr_telerama_20221103.xml

J'ai cherché dans l'application mais je n'ai pas trouvé comment juste rajouter l'occurrence "telerama" dans l'url.

**Comment by theoden11** [comment]
Bonjour. Ce n'est pas tellement telerama le problème, mais le fait que les url basées sur la date (_20221113.xml) ne sont plus générées et donc sont en erreur 404 car inexistantes. Il y a une url correspondant à un fichier xml par jour apparemment.

**Comment by Kanolm** [comment]
Je viens également de trouver ça:

https://github.com/Catch-up-TV-and-More/xmltv/issues/13

Apparemment, quelqu'un lance un script de chez lui pour la mise à jour des fichiers.

Mes compétences sont limités mais pour xmltv.py, est-ce qu'il ne suffirait pas (en workaround) d'ajouter le telerama à 'url' étant donné qu'il l'appelle pour construire le lien?
Ca donnerait quelque chose du genre:

xmltv_infos = {
    'fr_live':
        {
            'method': 'CUTV_xmltv_github',
            'url': 'https://github.com/Catch-up-TV-and-More/xmltv/raw/master/tv_guide_fr_telerama_{}.xml',
            'md5_url': 'https://github.com/Catch-up-TV-and-More/xmltv/raw/master/tv_guide_fr_{}_md5.txt',
            'keyword': 'tv_guide_fr_'
        },

**Comment by theoden11** [comment]
Ca ne changera pas le problème évoqué ci-dessus pour la journalisation du xml qui ne se fait plus. Tu peux ajouter telerama en effet comme tu l'as écrit mais ça ne changera rien, je gage.

**Comment by theoden11** [comment]
Qu'il n'y ait plus de guide, c'est une chose, mais le souci est que 2 fois sur 2 ça empêche le gestionnaire IPTV de démarrer, sans compter les erreurs 404, et donc on ne peut carrément plus utiliser le plugin... il faut vider le cache, forcer une réactualisation du guide plusieurs fois, quand ça marche, au risque d'avoir une erreur 403, pour avoir au moins les chaines TV présentes dans le guide vide. C'est pénible à chaque démarrage.

**Comment by Kanolm** [comment]
De mon côté je n'ai pas de problème pour visualiser les chaînes. Il s'agit uniquement de l'affichage du guide.

**Comment by theoden11** [comment]
Oui, pareil (quand on arrive à initialiser le guide quand même).
Je viens de passer sur le plugin OrangeTV et cela semble marcher, avec guide TV fonctionnel. Evidemment cela ne résoudra pas les problèmes des TV étrangères, mais pour moi ça fait le taf. Dommage...

**Comment by Kanolm** [comment]
Le plugin orange a besoin d'un compte orange pour fonctionner?

**Comment by theoden11** [comment]
ben oui, très probablement... comme je suis chez Orange, je ne me pose pas la question...

**Comment by Kanolm** [comment]
Je suis chez Sosh et ça fonctionne sans soucis aussi!

**Comment by joaopa00** [comment]
Devrait être fixé pour les EPG différent du Royaume-Uni.
