### ISSUE TITLE
[Question] Missing Live TV option

### ISSUE THREAD

**Issue by sviet2k** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#98]
Hi,

I installed Catch-up version 0.1.16 on my phone, my tablet and my Android box.
But on My Android box, I don't have the Live TV option. I only see Catch-up TV and Websites.
On the setting, the Live TV option is checked.
Please help me to fix this problem.

Thanks a lot in advance for your help.

**Comment by sviet2k** [comment]
Hi,

I installed Catch-up version 0.1.16 on my phone, my tablet and my Android box.
But on My Android box, I don't have the Live TV option. I only see Catch-up TV and Websites.
On the setting, the Live TV option is checked.
Please help me to fix this problem.

Thanks a lot in advance for your help.

**Comment by wwark** [comment]
Hi Sviet2k,

It is possible to send us (with removing password of account) settings.xml of the plugin. This file is present <path_user_data>/plugin.video.catchuptvandmore/
the path user_data depends of the OS. You can find information here: https://kodi.wiki/view/Userdata

Could you please start the plugin and get the logs in debug mode with this settings.xml?

Can you please also do a test to rename this file add "*.save" at the end and restart kodi and try to access the plugin again ?

Thanks you

**Comment by wwark** [comment]
Première question je vois que tu utilises cette version de Kodi "Starting Ftmc (16.2-31 Git:2017-09-07-b42e794-dirty)" sur ton android box.
Est-ce que c'est la même version de kodi déployer sur ton téléphone et la tablette ?

**Comment by sviet2k** [comment]
Oui la meme FTMC (kodi jarvis) pour les trois platformes.
La seule grande difference est la version Android: la boite a Android 5, les autres ont 6.
J'ai le probleme de version de codequick 0.9.5 pendant l'installation de la version de developement.

Encore merci

**Comment by wwark** [comment]
Merci pour ces retours.

L'analyse des logs ne remontent pas d'erreur et je n'ai pas de box android pour tester FTMC @SylvainCecchetto. Est-ce qu'il serait possible de poster sur le forum de FTMC et voir si une personne rencontre le même problème et surement avoir de l'aide un developpeur de FTMC pour nous aider à déterminer la cause.

Pour information, la prochaine version du plugin ne sera donc pas compatible avec les versions inférieures à Kodi 17 Krypton. (Lié au nouveau Framework ne s'intallant qu'à partir de Kodi 17). Ce point explique l'erreur rencontré.

Est-ce qu'il serait possible de mettre à jour vos différents supports en version Kodi 17? La version Kodi 18 arrive bientôt pour information.

Nous garderons une version legacy compatible Kodi 16 mais aucun nouveau contenu ne sera ajouté et nous apporterons peut être des petite corrections sur ce plugin.

Merci pour votre compréhension.

**Comment by sviet2k** [comment]
Merci beaucoup pour vos supports et l'information.
Je vais attendre la nouvelle version avec Kodi 17 pour continuer le test.
Note: Meme probleme de Live TV sur mes boites android avec Kodi 17.

**Comment by wwark** [comment]
Bonsoir @sviet2k 
Quelle est la version du plugin avec Kodi 17 où le problème est présent? Quel est le modèle de la box android?
Est-ce qu'il serait possible d'avoir les logs avec Kodi 17 pour voir le problème?
Est-ce que tu utilises un skin particulier ?

Merci,
Wwark

**Comment by sviet2k** [comment]
Bonjour Wwark,

J'ai fai un erreur. J'ai utilise la version Kodi 16 plugin sur Kodi 17.
Je vais refaire le test avec la version Kodi 17 du plugin.
Je connais aussi python. Je peux ajouter xbmc.log si tu me dis ou dans les modules.

Merci encore de votre support

**Comment by wwark** [comment]
Bonjour @sviet2k, 
La seule différence entre les deux versions du plugin est une version d'une librairie dans le fichier addon.xml.

La différence:
Kodi 17 : <import addon="xbmc.python" version="2.25.0"/>
Kodi 16 : <import addon="xbmc.python" version="2.24.0"/>

Le plugin pour kodi 16 peut s'intaller sur tous les Kodi 16 et supérieur.
Le comportement sera surement le même avec ton nouveau test. Il n'y a pas d'autres différences.

Il faudrait voir pour renommer ton repertoire ".kodi" afin d'avoir une installation sans ancienne configuration et voir si le problème persiste. Pour récupérer tes anciennes configurations il faudra renommer de nouveau ton repertoire en ".kodi" afin de retrouver ta configuration. 

Merci,
Wwark

**Comment by wwark** [comment]
Bonjour @sviet2k,

Est-ce que tu as pu refaire des tests?
Merci,
Wwark

**Comment by sviet2k** [comment]
Bonjour @wwark 

Desole de prendre du temps pour re-faire le test sur Kodi 17.
J'ai un-installe Kodi 17 and re-installe Kodi 17.
Installer adddon avec le repo de Kodi 16 et apres avec celui de Kodi 17.

Voici les resultats:
Le Live TV apparait dans les deux versions de Kodi 16  et Kodi 17. :) 
Seulement que la chaine RDI (que j'aime bien) n'est plus la.

Je pense que le Live TV est compatible seulement avec Kodi 17.

Encore merci pour votre aide.

**Comment by wwark** [comment]
Bonne nouvelle merci pour vos nombreux tests !

Je vais donc fermer ce ticket !
Bon direct tv et Replay :)
