### ISSUE TITLE
ARTE (FR) can't chose replay to watch

### ISSUE THREAD

**Issue by nmaster2042** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#980]
### Describe the bug
A clear and concise description of what the bug is: It's no more possible to watch ARTE (FR) replays.
When choosing a menu item it fails with error such this ex for "Le dessous des cartes":
[Catch-up-TV-&-More.support] Invalid URL '/fr/videos/RC-014036/le-dessous-des-cartes/': No scheme supplied. Perhaps you meant http:///fr/videos/RC-014036/le-dessous-des-cartes/?

### To Reproduce
Steps to reproduce the behaviour:
1. go to Catch up TV and More
2. go to "télévision de rattrapage" / "International" / ARTE (FR)
3. select "Toutes les émissions"
4. select "Le dessous des cartes - décrypter le monde avec des cartes"
5. Error

### Expected behaviour
After choosing "Le dessous des cartes - décrypter le monde avec des cartes" we should get the list of corresponding replays. We can chose one to watch.

### Actual behaviour
Tell us what happens instead:
ERROR No scheme supplied. Perhaps you meant http:///fr/videos/RC-014036/le-dessous-des-cartes/?

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ X] Android
 - [ ] iOS
 - [ X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: Linux: Kubuntu 22.10 x86_64 / Android TV 11 on Nvidia SHIELD
 - Kodi version: 19.4 on Linux / 19.3 on Android TV
 - Catch-up TV & More version: 0.2.39Beta10 on both Linux & Android TV
 - Installation method: Official BETA repository on both

### Additional context
Add any other context about the problem here:
Erroron all ARTE (FR) replays, not only my example

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):
[kodi.log](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/files/9895665/kodi.log)

**Comment by joaopa00** [comment]
Should be fixed in git.
Thanks for this very precise report.
