### ISSUE TITLE
TFOU in loop instead of TF1 programs - TFOU en boucle a la place des programmes de TF1

### ISSUE THREAD

**Issue by pcsystemd** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#983]
Hello,

Since a few days I don't have TF1 live anymore but instead it's Tfou in loop. However there is well to indicate the program of TF1!

I uninstalled Kodi and Catch-up tv but still the same. I don't have TF1 live anymore.

Kodi version : 19.3
Catch-up TV version : 0.2.39-beta07

Any idea?

Thanks
-----------------------------------------------------------
Bonjour,

depuis quelques jours je n'ai plus la chaine TF1 en direct mais a la place c'est Tfou en boucle. Pourtant il y a bien d'indiquer le programme de TF1!

J'ai désinstallé Kodi et Catch-up tv mais toujours pareil. Je n'ai plus TF1 en direct.

Version de Kodi : 19.3
Version de Catch-up TV ; 0.2.39-beta07

Une idée?

Merci

**Comment by joaopa00** [comment]
Peux-tu être plus précis?
Sur quel appareil as-tu le problème?
Le programme qui se lance est-il toujours exactement le même?
Cela se passe t-il pour les autres chaines du groupe TF1?

Personnellement, j'ai un problème sur TF1, mais ce n'est pas celui que tu décris.
La vidéo est en retard de plusieurs heures par rapport au direct. Est-ce ton problème aussi?

**Comment by pcsystemd** [comment]
Alors pour répondre aux questions:

Sur quel appareil as-tu le problème?
Xiaomi mibox 4K 
Le programme qui se lance est-il toujours exactement le même?
Oui il reprend en boucle sans arrêt.

**Comment by varzight** [comment]
J’ai aussi un problème, uniquement pour tf1, et la vidéo est en effet en retard de plusieurs heures. (à 17h30 le « live » diffuse le journal de 13h)

**Comment by joaopa00** [comment]
Xiaomi mibox 4K, c'est sous android?

**Comment by yoichy** [comment]
Bonjour j'ai aussi un soucis je pense que cela est lié: 

Un décalage de 4 heures de retard au lancement de TF1 et quand j'avance j'ai au final un décalage de 15 à 20 minutes mais le décalage de 4 h revient dés que je recharge TF1

J'ai réinstallé aussi bien catch-up que la liste des chaines.

Your environment

 Other
Firestick

Operating system version/name:

Kodi version: 19.4

Catch-up TV & More version: 0.2.39beta07

Installation method: Repo

Additional context
Fonctionnait encore dimanche soir.

**Comment by joaopa00** [comment]
Bonne nouvelle, je crois savoir quel est le bug. Mauvaise nouvelle, ce n'est pas un problème de Catchuptvandmore, mais de inputstream adaptive. Ce qu'il se passe est que le live de TF1 (et pour l'instant cele ne se passe que pour TF1, mais cela va certainement changer très vite) est diviser en chaptre. Et le mçme fichier ser pour plusieurs heures. Malheureusement, IA lit les chapitres dans l'ordre (le 1 donc pour commencer). Ce chapitre ne correspond pas à l'heure du direct en général.

Il n'y a rien que Catchuptvandmore puisse régler par lui-même. Il y a eu des changements dans IA dans la version 20.3.1 concernant le flux DASH. Peut-eêre est-ce fixé dans cette dernière version (je ne peux pas tester pour le moment). Même si c'est le cas, comme les changements pour IA ne sont pas rétroportés pour les versions inférieures à Nexus, il faudra mettre à jour à Nexus pour que le problème soit réglé.

**Comment by pcsystemd** [comment]
Pas tout compris car je ne sais pas à ce que correspond IA et Nexus mais merci.
Oui oui la mibox est sous android

**Comment by joaopa00** [comment]
Nexus est le nom de code de la version 20 de Kodi. Elle est encore en phase de développement.
IA=Inputstream Adaptive. C'est une extension de Kodi qui pemet de gérer les DRM.

**Comment by patneze** [comment]
Salut,
j'ai le même souci .
Donc si je comprends bien ce qui est dit + haut, il faut installer la new version de Kodi (v20) ?

**Comment by joaopa00** [comment]
J'ai pu tester la version 20.Cela ne règle pas le problème malheureusement.

**Comment by patneze** [comment]
OK pas cool. C'est pas très bon pour mon WAF :)

**Comment by joaopa00** [comment]
C'est bien un bug dans inputstreamadaptive (voir [bug report](https://github.com/xbmc/inputstream.adaptive/issues/1066))Malheureusement,ce bug ne peut pas êre fixé dans IA (voir [explication technique](https://github.com/xbmc/inputstream.adaptive/issues/574)) Mais heureusement, il y a une solution de contournement. Je l'ai implémentée dans la version beta 12 de catchuptvandmore. Vous pouvez tester.

Pour le bug original, essaie de mettre à jour avec cette beta et regarde ce que cela donne.

**Comment by pcsystemd** [comment]
Merci pour ton aide .

Pour cette beta 12 on peut la récupérer comment? En effet pour ma box sous android j installe catchuptvandmore via fichier zip en récupérant le repository suivant:

Pour la version stable 
 https// repository.catchuptvandmore.stable-0.0.6.zip

Pour la version beta
 https// repository.catchuptvandmore.beta-0.0.6.zip

**Comment by joaopa00** [comment]
C'est ça. La beta 12 sera disponible certainement  demain, tant que le site se mette  à jour.

**Comment by Florian-GM** [comment]
Même problème ici depuis plusieurs jours. Toujours un décalage énorme entre le live et ce que j'ai sur kodi... J'ai crû que c'était TF1 qui avait oublié de changé d'heure le premier jour 😂

**Comment by kdurand44** [comment]
Ça fonctionne super avec la maj 12
Par contre sur France 2 les programmes bloquent a chaque pub... Je suis le seul ?
Un grand merci pour votre travail :)

**Comment by Florian-GM** [comment]
@kdurand44 on la trouve où la MAJ 12 ?

**Comment by kdurand44** [comment]
Sur le repo beta catch up TV and more

**Comment by Florian-GM** [comment]
@kdurand44 t'as un lien, j'arrive pas à installer depuis repo bêta. Échec à chaque fois. Je le fais en manuel depuis zip du coup

**Comment by Florian-GM** [comment]
Je confirme ça fonctionne ! Merci !

**Comment by pcsystemd** [comment]
Pour la part via l url du repo https://catch-up-tv-and-more.github.io/repo/  je n arrive toujours pas à récupérer la beta 12!

Une idée ?
Merci

**Comment by kdurand44** [comment]
Tu as bien tout redémarrer ?

Quelqu'un a une idée pour France 2, le fait que ça me bloque a chaque pub ?

**Comment by pcsystemd** [comment]
Oui bien sûr . 
D ailleurs si tu cliques sur l url du repo tu verras que c est la beta 0.0.6 et pas la 12

**Comment by joaopa00** [comment]
Il faut lire le wiki jusqu'à la fin.

**Comment by kdurand44** [comment]
Pour le problème de France 2 ?

**Comment by joaopa00** [comment]
Ce n'est pas le sujet de ce fil. Si tu as un problème, ouvre un autre rapport e bug s'il te plaît et on regardera.

**Comment by kdurand44** [comment]
Ok merci :)

**Comment by pcsystemd** [comment]
> Il faut lire le wiki jusqu'à la fin [wiki](https://catch-up-tv-and-more.github.io/installation/)

Si c est à moi qu est adressée ta réponse, je l ai lu jusqu à la fin et a moins que j ai pas tout compris je ne vois rien de particulier si c n est qu’ il est dit que si on installe la version beta cette dernière sera mise à jour automatiquement avec la dernière version de GitHub . Donc je ne dois pas tenir en compte la version du zip?

**Comment by joaopa00** [comment]
As-tu fait l'étape installer depuis le déôt?
Si non, il faut obligatoirement la faire.

**Comment by pcsystemd** [comment]
Oui je l avais déjà fait.
Bon j ai désinstallé Kody et tout réinstaller et c est ok cela fonctionne j ai bien récupérer la beta12.
Merci en tout cas pour ton patch.

**Comment by joaopa00** [comment]
Bonne nouvelle. Merci pour le retour. Je ferme ce rapport puisque tout fonctionne maintenant.

**Comment by antoineauger** [comment]
@joaopa00 Merci pour le workaround. 

Pour info, avec la release `beta12`, TF1 re-marchait correctement mais j'observais toujours le même problème avec TMC (Raspberry pi4, Kodi `19.4`).

J'ai édité localement le fichier sur mon raspberry dans le dossier `addons` avant de redémarrer, pour tester. 

Ça semble bel et bien résoudre le problème pour l'instant:

```python
if video_id == 'L_TF1' or video_id == 'L_TMC':
        workaround = '1'
    else:
        workaround = None
```

**Comment by joaopa00** [comment]
Ca se passe sur toutes les chaines du groupe  TF1 ou seulement sur TMC et TF1?
Si c'est pour toutes les chaines, autant forcer le workaround.

**Comment by antoineauger** [comment]
> Ca se passe sur toutes les chaines du groupe TF1 ou seulement sur TMC et TF1? Si c'est pour toutes les chaines, autant forcer le workaround.

J'avoue ne pas avoir testé avec les autres chaînes du groupe que je ne regarde jamais 🙇🏻
