### ISSUE TITLE
Bug France 2

### ISSUE THREAD

**Issue by kdurand44** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#984]
Bonjour

J'ai un souci avec le streaming de France 2. Le live coupe systématiquement au moment des pubs ?

Avez-vous le même souci ?

Merci d'avance ;)

**Comment by joaopa00** [comment]
C'est normal. C'est ce qui se passe sur le france télévision. voir aussi [problème pour captvty](https://captvty.fr/)
