### ISSUE TITLE
france 2 / france 3 - live décalés

### ISSUE THREAD

**Issue by khalistoo** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#986]
Il me semble que c'est le meme problem que le bug de tf1 résolu dernièrement avec la beta release 12. 
Il y a un décalage de quelques heures sur les live de France 2 et France 3

Je n ai pas teste avec la version stable

**Comment by joaopa00** [comment]
Pas de problème pour moi. Le journal de 6H00 était bien à l'heure.

**Comment by khalistoo** [comment]
Exact je confirme que c'est rentre dans l'ordre ce matin... chelou !!
