### ISSUE TITLE
Some missing channels - La 1ère - Add programs (shows, documentary, ...)

### ISSUE THREAD

**Issue by Che-debarras** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#99]
Hi 

I am looking for replay of a french channel la1ere (outre-mer) it has disapeared from the list

It will come back or not? If not why ? Thanks

**Comment by wwark** [comment]
Hi,
It is ok on my side cf screenshot below.
Can you please take a screenshot on your side?
What is the version of the plugin you using?

![screenshot from 2018-11-16 18-55-36](https://user-images.githubusercontent.com/469461/48639239-46ccd380-e9d3-11e8-87f7-174b3e48b3de.png)
![screenshot from 2018-11-16 18-55-31](https://user-images.githubusercontent.com/469461/48639240-46ccd380-e9d3-11e8-824c-6b509c8488ce.png)

Thanks,
Wwark

**Comment by Che-debarras** [comment]
An old one because when i update it is not listed on newer version.

Which one do you use?
Do we need a vpn or something because this channel only work in its country (outre mer)
Nothing happens here in France. 

Can you play this channel or play a replay video?

**Comment by wwark** [comment]
For Live TV Outre Mer doesn't exist but other Guadeloupe, Martinique are geolocalised.
For Replay Outre Mer exist and they are not geolocalised.
I used the last development of the plugin 0.2.0~beta19.

**Comment by Che-debarras** [comment]
Where do you find tgis 0.2.0 beta please

**Comment by wwark** [comment]
You need an IP on the country to watch geolocalised content (live tv or replay)
For use this beta version, you can follow this explanation (https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/wiki/Add-the-official-repository) to install on our repo and choose the "Krypton Beta" choice.

**Comment by Che-debarras** [comment]
Thank you for your help
I managed to install the beta one
But there is no replay video 
La1ere outre mer shoulf have some video
There are showed on older version of the addon but not on the beta one

Where are the videos ? The is only the evening news but no films no series etc..
If you install the 0.1.0 you will the all the replay video even the updated one like tv show "Empire season 4"

**Comment by wwark** [comment]
Ok I start to understand.
We changed api to get video for La1ere and the new one propose just JT, Meteo. 
We have a todo to add more programs.
So for the moment you need to keep old version to get this contents.
I will change the title of this issue

**Comment by Che-debarras** [comment]
[](url)
![screenshot_20181116-213625_kodi](https://user-images.githubusercontent.com/44464129/48646062-ed22d400-e9e7-11e8-9544-9067b0af488f.jpg)
![screenshot_20181116-213608_kodi](https://user-images.githubusercontent.com/44464129/48646075-f6ac3c00-e9e7-11e8-89e9-f4532c84f828.jpg)

![screenshot_20181116-213554_kodi](https://user-images.githubusercontent.com/44464129/48646085-00ce3a80-e9e8-11e8-81c0-89836b3f741c.jpg)


This is screenshot of tv channel la1ere
we have a lot of categories of replay videos from this channel on v0.1.10 
Version after 0.1 10 show only news or weather

But i cannot keep this old version car the replay is not working on this channel when i play a video. Nothing happen
We see the contents but they cannot be played this is why i wonder if replay it geolocalized for this channels

Thanks for you help

**Comment by wwark** [comment]
Ok it means maybe the previous API not work.
In the logs do you have some error?
Can you please do a test to play a video of La1ere with v0.1.10 with logs in debug mode and share the logs? We will see the error if it error HTTP 403 maybe the content is geolocalized.

Nevertheless, we let this ticket to add more programs for La1ère.
With 0.2.0~beta19, can you confirm the replay are OK "info soir" on your side?

**Comment by wwark** [comment]
Also you can test the video on the website. If the website said it is geo-localized it means it will not available also in this plugin.

**Comment by Che-debarras** [comment]
Thank  you for ur time to help me
I will test everything tomorrow
But on the website it is definitively geolocalised 
A message is saying not available in the country

When i updated i got 0.2.0 beta 18 not beta 19
Where is beta 19?

**Comment by Che-debarras** [comment]
Any news about this feature?

**Comment by wwark** [comment]
Hello @Che-debarras,

No work on this subject for the moment. Maybe it will be available for the next release.
We will inform you in this ticket.

Thanks,
Wwark

**Comment by Che-debarras** [comment]
Yes i will test in few minutes Thanks

**Comment by wwark** [comment]
Hi,
If it is geolocalised we can't change that. You need an IP of DOM/TOM to play them. If the website said it is geo-localized it means it will not available also in this plugin.

Regarding C8 it is normal a lot of contents are DRM protected now. We have a ticket to follow that https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/48 We will inform when the plugin can play this type of DRM.

I close this ticket because we implement the list of TV shows for La 1ère.

Thank for your understanding,
Wwark
