### ISSUE TITLE
Channel 4 catch-up KeyError: 'assetId'

### ISSUE THREAD

**Issue by tibbsbrookside** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#995]
### Describe the bug
A clear and concise description of what the bug is:
The following error is logged when trying to select "The Last Leg" from the Channel 4 catch-up section:
KeyError: 'assetId'

### To Reproduce
Steps to reproduce the behaviour:
1. Open the addon
2. Select Channel 4 from the catch-up menu
3. Select The Last Leg from one of the menus

### Expected behaviour
A clear and concise description of what you expected to happen:
A list of available programmes are displayed

### Actual behaviour
Tell us what happens instead:
Error is logged

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name: LibreELEC 10.0.3
 - Kodi version: 19.4.0
 - Catch-up TV & More version: 0.2.39~beta13
 - Installation method: Beta repo

### Additional context
Add any other context about the problem here:
Everything else works fine, including many other Channel 4 programmes.
As far as I can see, there are available programmes listed on the website.
Thanks in advance.

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):
https://pastebin.com/sQg8LCnk

**Comment by joaopa00** [comment]
Should be fixed in git
