### ISSUE TITLE
FranceTV channels won't play | Asking to upgrade to Kodi 18 because of DRM

### ISSUE THREAD

**Issue by Kiblyn11** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#996]
### Describe the bug
Trying to play live FranceTV channels results in DRM error, saying that I should upgrade Kodi to version 18 at least in order to play content.

### To Reproduce
Steps to reproduce the behaviour:
1. Install latest beta from github
2.Open Kodi
3. Start CatchUpTV Channel 2

### Expected behaviour
Channel works

### Actual behaviour
Not working, asking for Kodi upgrade because of DRM

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [x] Android | FireTV
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 19.4
 - Catch-up TV & More version: 0.2.39~beta13
 - Installation method: From beta repository

### Additional context
I upgraded to beta because of issues with TF1 group channels not playing actual live content. But FranceTV channels were wroking fine.
Now TF1 channels are working, but FranceTV is not.

### Debug log
If you can, please add your debug log information (Tutorial available here: https://kodi.wiki/view/Log_file/Easy):

**Comment by joaopa00** [comment]
Should be fixed in git.
