### ISSUE TITLE
TF1 Playback error

### ISSUE THREAD

**Issue by kbn53** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#997]
### Describe the bug
Hi, 

I've a bug when I try to launch TF1 (French). "Playback Error' The other channel works very well"

### To Reproduce
Steps to reproduce the behaviour:
1. Live TV
2. France
3. TF1
4. ERROR PLAYBACK

### Expected behaviour
A clear and concise description of what you expected to happen:

### Actual behaviour
Tell us what happens instead:

### Screenshots
If applicable, add screenshots to help explain your problem:

### Your environment
 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Other

 - Operating system version/name:
 - Kodi version: 
 - Catch-up TV & More version: Matrix last stable
 - Installation method: Android TV

**Comment by joaopa00** [comment]
You have to give some infos. What version of Kodi do you use, what version of Cathuptvandmore. As such, your report is pretty useless.

**Comment by kbn53** [comment]
> You have to give some infos. What version of Kodi do you use, what version of Cathuptvandmore. As such, your report is pretty useless. And please, attach a log.

Hi,

Kodi : 19.3
Catchup : 0.2.37+matrix.1

**Comment by joaopa00** [comment]
Update to the beta channel.

**Comment by kbn53** [comment]
> Update to the beta channel. [WIKI for installation](https://catch-up-tv-and-more.github.io/installation/)


Yes !

It's working with the latest beta.

Thanks for your reactivity and help

**Comment by joaopa00** [comment]
I close then.
