### ISSUE TITLE
France 24 Returns "Unable to resolve url" Error

### ISSUE THREAD

**Issue by mearubato** [Catch-up-TV-and-More/plugin.video.catchuptvandmore#998]
A week or two ago I started experiencing a problem launching the France 24 stream. It's not going away, so I'm opening this issue. The error summary is:

ERROR <general>: [Catch-up-TV-&-More.support] Unable to resolve url

Installing the latest beta release (0.2.39-beta14) did not resolve the problem.

Steps to reproduce the behaviour:
- Launch the Catch-Up TV & More add-on from Add-ons in Kodi
- Navigate: Live TV | International | France 24 (EN)
- Press enter.

Expected Behavior:
- Launching the broadcast should present a rotating gear object
- The screen may blink, but should continue rotating 
- Stream is successfully presented on the screen

Actual Behavior:
- An information dialog is immediately presented stating the selection triggered an unexpected error
- In the upper right-hand corner of the screen is:
   - RunTime Error: Unable to resolve url

Environment:
- Raspberry-Pi 4 with 4GB RAM
- OS version/name: Raspberry Pi OS, 11 Bullseye, kernel 5.15.76-v8+, aarch64
- Kodi version: 19.4
- Catch-up TV & More version: 0.2.39-beta14 and 0.2.39-beta07
- Installation method: 
   - Install from repository for Kodi official version
   - Install from Zip of this project's repository

Debug Log:
- https://paste.kodi.tv/qokajeriko.kodi

I have checked through the existing list of issues and don't see anyone reporting this particular problem. I am in Canada and configure the add-on with the "EN" language.

Thanks,
John

**Comment by joaopa00** [comment]
Unable to reproduce here as well the english channel as the french channel.
>script.module.youtube.dl: _getYoutubeDLVideo() failed::getVideoInfo (405) - name 'basestring' is not defined

You have a problem of dependency. Yo should fix that. It is not a problem of catchuptvandmore.
